<?php
$l_warp_unlinked = "Doelsector ([target_sector]) heeft nog een link van deze sector.";
$l_warp_forbidtwo = "Met behulp van een Warp-editor om verwijderen van een twee-weg koppeling aan sector [target_sector] is niet toegestaan.";
$l_warp_removed = "Link verwijderd";
$l_warp_removedtwo = "Link verwijderd van en naar";
$l_warp_nomoney = "Je hebt niet genoeg credits met de ketting link te verwijderen.";
$l_warp_noenergy = "Je hebt niet genoeg energie om de warp link te verwijderen.";
?>
