<?php
$l_artifact_title = "Ophalen Artifact";
$l_artifact_list_title = "Lijst van Verworven Artifacts";
$l_artifact_noscan = "Uw scanners kon het niet vinden het artefact.";
$l_artifact_noturn = "Je hebt niet genoeg blijkt te pikken dit artefact.";
$l_artifact_classname = "Artefact Naam";
$l_artifact_description = "Artefact Beschrijving";
$l_artifact_imagename = "Artefact Afbeelding";
$l_artifact_incomplete = "Artefact Pieces";
$l_artifact_process = "Gebruik de &#39;Completed Artefact";

?>
