<?php
$l_md_title = "Sector verdedigingen";
$l_md_invalid = "Ongeldige sector defensie";
$l_md_nolonger = "De sector defensie heeft geselecteerd is er niet meer.";
$l_md_you = "jij";
$l_md_bmines = "Uw balken vernietigd";
$l_md_msgdownerb = "[name] vernietigd [mines] mijnen in de sector [sector].";
$l_md_retr = "U teruggevonden";
$l_md_consist = "Deze sector bestaat uit de verdediging van [qty] [type] eigendom van [owner].";
$l_md_youcan = "U kunt";
$l_md_retrieve = "Ophalen";
$l_md_attack = "Attack";
$l_md_attdef = "Aanval op de sector defensie. Alle sectoren-strijders zullen wreken.";
$l_md_noturn = "Je hebt minimaal een beurt.";
$l_md_nothere = "Je moet in dezelfde sector als de sector defensie.";
$l_md_notyours = "Actie is niet toegestaan. Die sector verdediging horen niet bij jou.";
$l_md_yours = "U kunt niet aanvallen uw eigen sector verdedigingen.";
?>
