<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Unchartered ruimte";
$l_zname[2] = "Federatie ruimte";
$l_zname[3] = "Alliance ruimte";
$l_zname[4] = "War Zone";

$l_nova = "Nova";
$l_nova = "Nova Bomb";
$l_lssd = "Laatste schip gezien apparaat";
$l_lss = "Laatste schip gezien in deze sector";

// Common to : warpedit 1-3.php

$l_warp_title = "Gebruik Warp-editor";
$l_warp_turn = "Je hebt minimaal een beurt gebruik maken van een warp-editor.";
$l_warp_none = "U hebt geen warp redacteuren.";
$l_warp_forbid = "Met behulp van een Warp-editor in deze sector is niet toegestaan.";
$l_swarp_forbid = "Met behulp van een Warp-editor of van SG sectoren is niet toegestaan.";
$l_warp_nosector = "Sector bestaat niet.";

// Not yet confirmed common to multiple files:

$l_yes = "Ja";
$l_no = "Nee";
$l_here = "hier";
$l_submit = "Indienen";
$l_reset = "Reset";
$l_all = "Alle";
$l_max = "Max";

$l_trade = "Handel";
$l_ore = "Ore";
$l_commodity = "Commodity";
$l_commodities = "Commodities";
$l_organics = "Organics";
$l_goods = "Goederen";
$l_energy = "Energie";
$l_colonists = "Kolonisten";
$l_credits = "Credits";
$l_units = "eenheden van";
$l_special = "Special";
$l_upgrade_ports = "Upgrades";
$l_device_ports = "Apparaten";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_dig = "Hoogwaardigheidsbekleders";
$l_spy = "Spies";

$l_cargo = "Cargo";
$l_fighters = "Fighters";
$l_mines = "Mijnen";
$l_torps = "Torpedo&#39;s";

$l_none = "Geen";
$l_unnamed = "Naamloos";
$l_name = "Naam";
$l_unowned = "Onbeheerd";
$l_unknown = "Onbekend";
$l_clickme = "Klik hier";
$l_player = "Speler";
$l_ship = "Schip";
$l_ships = "Schepen";
$l_set = "instellen";
$l_realspace = "Realspace";
$l_armorpts = "Armor punten";
$l_links = "Links";
$l_login_email = "E-mail adres:";
$l_add = "Toevoegen";
$l_teamforum = "Team Forum";
$l_teamships = "Team Schepen";
$l_tutorial = "Tutorial / Help";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Puin";
$l_localmap = "Regiokaart";
$l_arm_weap = "Armor en wapens";
$l_3dmap = "3D Galaxy Kaart";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Ruimtesondes";
$l_warpeditors = "Warp Redactie";
$l_genesistorps = "Genesis Torpedo&#39;s";
$l_sgtorps = "SG Torpedo&#39;s";
$l_minesfighters = "Mijnbouw / Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Verslagen";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Kaarten";
$l_messages = "Berichten";
$l_shiptype = "Type schip";
$l_help = "Help";
$l_rank = "Rank";

$l_teamplanets = "Team Planeten";
$l_teamdefenses = "Team verdedigingen";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet verdedigingen";
$l_changeproduction = "Verander Productie";
$l_galacticarm = "Galactic Arm";

$l_armor = "Armor";
$l_news_none = "Sorry, geen nieuws vandaag.";

$l_ranks_good = "Goed";
$l_ranks_evil = "Slecht";
$l_ranks_neutral = "Neutraal";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zone is nu een War Zone!";
$l_global_nzone = "Zone is een neutrale zone.";
$l_global_team = "Zone behoort nu tot team";
$l_global_player = "Zone behoort nu tot speler";
$l_global_nochange = "Zone eigenaar veranderde niet";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "Petty Officer Derde Klasse";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Lieutenant junior grade";
$l_insignia_name[11] = "Luitenant";
$l_insignia_name[12] = "Lieutenant Commander";
$l_insignia_name[13] = "Commander";
$l_insignia_name[14] = "Captain";
$l_insignia_name[15] = "Rear Admiral (onderste helft)";
$l_insignia_name[16] = "Rear Admiral (bovenste helft)";
$l_insignia_name[17] = "Vice-admiraal";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Admiraal";

$l_main_title = "Main Menu";
$l_main_warpto = "Warp naar";
$l_main_autoroute = "Autoroute naar";
$l_main_rs_to = "RSMove aan";
$l_main_other = "Ander";
$l_main_shipyard1 = "Scheepswerf";
$l_main_shipyard2 = "Toegang tot de";
$l_traderoutes = "Handel Routes";
$l_trade_control = "Controle op de handel";
$l_youhave = "U hebt";
$l_turns_used = "Turns gebruikt:";
$l_turns_have = "Turns beschikbaar:";
$l_score = "Score:";
$l_sector = "Sector";
$l_help = "Help";
$l_faq = "Veelgestelde vragen";
$l_feedback = "Feedback";
$l_forums = "Forums";
$l_logout = "Afmelden";
$l_commands = "Commando&#39;s";
$l_command_no = "Opdracht niet beschikbaar.";
$l_devices = "Apparaten";
$l_planets = "Planeten";
$l_log = "Inloggen";
$l_sector_def = "Sector verdedigingen";
$l_defense = "Verdediging";
$l_read_msg = "Lees Berichten";
$l_send_msg = "Stuur Berichten";
$l_rankings = "Rankings";
$l_teams = "Teams";
$l_ohno = "Self-Destruct";
$l_options = "Opties";
$l_navcomp = "Nav Computer";
$l_incompletemove = "Je hebt niet het afronden van uw vorige zet.";
$l_clicktocontinue = "Klik hier om verder te gaan";
$l_toplanetmenu = "te gaan naar de planeet menu.";
$l_nonexistant_pl = "Op een niet-bestaand planeet??";
$l_abord = ", Aan boord van de";
$l_messages_wait = "Berichten voor u klaar.";
$l_no_warplink = "Geen ketting links";
$l_scan = "scan";
$l_fullscan = "Full scan";
$l_port = "Port";
$l_tradingport = "Trading haven";
$l_planet_in_sec = "Planeten in de sector";
$l_ships_in_sec = "Andere schepen in de sector";
$l_sector_0 = "Er is zoveel verkeer in Sol dat je zelfs niet kan isoleren van andere schepen!";
$l_map = "Kaart";
$l_probe = "Probes";
$l_autotrade = "Autotrades";
$l_onboard = "aan boord van een";
$l_classship = "klasse schip";
$l_traveled = "reisde naar sector";
$l_max_planets = "Maximale habital planeten";
$l_block_msg = "Blok Berichten";
$l_sectorinfo = "Sector Info";
$l_add_note = "Opmerking toevoegen";
$l_view_note = "Bekijken";
$l_notes = "Notities";
$l_global_limitreached = "Je hebt een limiet bereikt voor de hoeveelheid tijd die je mag online te zijn elke dag. Aanmelden morgen weer na middernacht.";
$l_onlinetimeleft = "Remaining Time:";
$l_planetmax = "Planetaire Maximum:";
$l_storedshipreport = "Opgeslagen Schepen";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federatie informatie Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Vorige pagina";
$l_common_next = "Next Page";
$l_common_totalpages = "Totaal Pagina&#39;s";
$l_common_selectpage = "Selecteer Pagina:";
$l_common_page = "Pagina:";
$l_templatechange = "Wil je dit sjabloon te houden?";

$l_im_fed_bounty = "De Federatie heeft geplaatst een bounty op je voor de aanval op een dergelijk laag geplaatste speler. De Federatie zal aanvallen uw schip op een regelmatige basis terug te betalen totdat u uw genade. U kunt betalen van uw premie op elke upgrade Port of Spacedock.";
$l_im_fed_bounty_title = "Federatie bovenaan een Bounty op je!";
$l_im_alliance_bounty = "De Alliantie heeft geplaatst een bounty op je voor de aanval op een dergelijk laag geplaatste speler. Het bondgenootschap zal aanval uw schip op een regelmatige basis terug te betalen totdat u uw genade. U kunt betalen van uw premie op elke upgrade Port of Spacedock.";
$l_im_alliance_bounty_title = "Alliance bovenaan een Bounty op je!";
$l_instant_messages_waiting = "U hebt [count] boodschappen voor u klaar.";

$l_home_planet = "Thuisplaneet";

$l_hold_space_used = "Holds gevuld:";
$l_hold_space_free = "Holds Leeg:";
$l_port_buys = "Port Buys:";

?>
