<?php
$l_novabomb_turns = "De Nova Bomb vereist atleast [turns] blijkt te vuren.";
$l_novabomb_planetsdamaged = "Planeten beschadigd door de Nova Bomb";
$l_novabomb_planet = "Planet [name] schade heeft geleden van de Nova Bomb.";
$l_novabomb_novaexplode = "Nova bom ontplofte zoals het werd ontslagen en uw schip heeft enorme schade geleden.";
$l_novabomb_novaexplode2 = "Nova bom ontplofte zoals het was ontslagen en uw schip werd verwoest.";
$l_novabomb_notfedsec = "Nova Bomb kan niet worden gebruikt op eigendom Federatie sectoren.";
$l_novabomb_destroyed_planet = "Uw nova bom gebarsten het oppervlak van de planeet en geboord in de kern waar het ontplofte waardoor de planeet te breken.";
$l_novabomb_wrongclass = "Dit schip klasse kan geen brand a Nova Bomb apparaat.";
$l_novabomb_nonova = "Je hebt geen Nova Bomb geïnstalleerd.";
$l_novabomb_novamiss = "De Nova Bomb mist eng maar schade toebrengt op de planeet.";
$l_novabomb_success = "Sector [sector] is Nova Bombed!";
$l_novabomb_mines = "Vernietigd [mines] sector Mines.";
$l_novabomb_fighters = "Vernietigd [fighters] sector Fighters.";
$l_novabomb_shipsdamaged = "Schepen beschadigd door de Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] schade heeft geleden van de Nova Bomb.";
$l_novabomb_ship_survived = "Uw schip was ver genoeg weg toen de bom ontplofte Nova eventuele schade te voorkomen.";
?>
