<?php
$l_autotrade_title = "Auto Traderoute Menu";
$l_autotrade_dismiss2 = "Auto handelsroutes schrappen.";
$l_autotrade_report = "Auto Traderoute Verslag";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energie";
$l_autotrade_capacity = "Capaciteit";
$l_autotrade_goods = "Goederen Prijs";
$l_autotrade_ore = "Ore Prijs";
$l_autotrade_organics = "Organics Prijs";
$l_autotrade_energy = "Energie Prijs";
$l_autotrade_colonist = "Kolonist Prijs";
$l_autotrade_credits = "Handel Credits";
$l_autotrade_delete = "Wissen <br> Route";
$l_autotrade_unnamed = "Naamloos";
$l_autotrade_noroute = "Route nr.";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "credits";
$l_autotrade_deletebutton = "Wissen";
$l_autotrade_noroute2 = "U hebt geen setup geen Auto handelsroutes.";
?>
