<?php
$l_chf_youretreatback = "Je terugtrekken terug naar de vorige locatie";
$l_chf_movefailed = "Verplaatsen is mislukt.";
$l_chf_thefightersdetectyou = "De strijders bespeur je!";
$l_chf_therearetotalfightersindest = "Er zijn [chf_total_sector_fighters] strijders in uw bestemming sector.";
$l_chf_youcanretreat = "<B>Retreat</b> - kost een extra beurt.";
$l_chf_inputfight = "<B>Fight</b> - U moet verslaan alle vechters om naar de sector.";
$l_chf_inputcloak = "<B>Cloak</b> - Gebruik uw cloaking apparaat en proberen om de strijders te voorkomen.";
$l_chf_go = "Gaan";
$l_chf_inputrun = "<B>Attack and Run</b> - Je hebt een bliksem aanval uitvoeren en retraite. Maar je kan enige beschadiging tijdens de retraite.";
?>
