<?php
// New News Items

$l_news_planets = "planeten";
$l_news_cols = "Miljoen kolonisten";
$l_news_p_headline = "[player] &#39;s Rijk nu heeft [total] planeten";
$l_news_c_headline = "[player] &#39;s Rijk nu heeft [total] miljoen kolonisten";
$l_news_p_textXX = "De Federatie heeft afgegeven waarschuwingen betreffende het Rijk van [name]. [name] heeft een controle van de [total] planeten en moet worden beschouwd als zeer gevaarlijk. Alle sectoren moeten toenemen sector verdediging onmiddellijk.";
$l_news_c_textXX = "Het Rijk van [name] ervaart enorme drukte op alle planeten met meer dan [total] miljoen kolonisten. Voedselschaarste kunnen veroorzaken onrust. Alle sectoren moeten zich bewust zijn van mogelijke agressieve acties van [name] in de toekomst.";

$l_created_universe = "&#39;Universe Creation&#39;";
$l_created_universe_full = "&#39;Wetenschappers onderzoek naar het ontstaan van het heelal hebben unaniem besloten dat het vandaag de statistisch meest waarschijnlijke dag voor Universe Creation te hebben plaatsgevonden worden genomen &quot;";

$l_news_p_text5 = "De stijgende rijk van [name] heeft nu vijf planeten, zal de FNN kijken naar de activiteiten van [name] nauwer te betrekken bij de toekomst!";
$l_news_p_text10 = "De groeiende imperium van [name] controleert nu tien planeten, Verslagen van FNN zeggen dat verdere uitbreiding van [name] zou kunnen leiden tot oorlog!";
$l_news_p_text25 = "Het enorme rijk van [name] gekoloniseerde planeten al 25, in een interview, [name] werd aangekondigd dat hij zou overwegen te vertragen zijn expansie in de toekomst!";
$l_news_p_text50 = "De enorme uitgestrekte rijk van [name], vertegenwoordigd door 50 planeten in het hele melkwegstelsel is het verkrijgen van een dreigende kracht. Een van de verslaggevers FNN erachter dat [name] zijn schip de planning van een grote oorlog is de upgrade. In een interview [name] werd aangekondigd dat gedaan wordt op defensie-doeleinden!";
$l_news_c_text25 = "De stijgende rijk van [name] heeft nu 25 miljoen kolonisten, zal de FNN kijken naar de activiteiten van [name] meer te betrekken bij de toekomst, maar zijn zeer duidelijk dat het lage geboortecijfer te gaan om te ontploffen!";
$l_news_c_text100 = "De aspirant-imperium van [name] heeft nu 100 miljoen kolonisten, na een explosie van geboortecijfers, [name] kolonies leek een goede plek voor gezinnen te regelen!";
$l_news_c_text500 = "Het grote rijk van [name] heeft nu 500 miljoen kolonisten, [name] zei in een interview dat de kolonisatie van het melkwegstelsel heeft alleen nog niet begonnen";
$l_news_c_text1000 = "De gigantische rijk van [name] heeft nu een miljard kolonisten, FNN verslaggevers ontdekte dat [name] in het bezit is van een paar vreemde klonen mechanisme waardoor hij nieuwe kolonisten in enorme hoeveelheden ras. Met dit bedrag van de kolonisten, is de econmic kracht van dit enorme rijk, FNN hoopt dat [name] niet zijn geld uitgeven aan oorlogvoering";

$l_news_indi_short = "FNN Gerucht: meer dan [planets] verklaart de onafhankelijkheid.";
$l_news_indi = "FNN heeft het op goede autoriteit die meer dan [planets] planeten hebben besloten dat ze beter worden geregeerd door zichzelf en zijn onafhankelijk te worden.";

$l_news_nova_short = "FNN Verslag: [name] maakt gebruik van Nova Bomb.";
$l_news_nova = "FNN heeft breaking news dat [name] gebruik heeft gemaakt van de gevreesde Nova Bomb [total] tijd (s) naar een planeet en alle schepen op het te vernietigen.";
$l_news_nova_m_short = "FNN Verslag: [name] maakt gebruik van Nova Bom en mist.";
$l_news_nova_m = "FNN heeft breaking news dat [name] gebruik heeft gemaakt van de gevreesde Nova Bomb [total] tijd (s) om te proberen en te vernietigen, een planeet. De Nova Bomb opgeblazen buiten de planeten sfeer en zorgde voor enorme schade aan de planetaire infrastructuur.";

$l_news_bounty = "FNN Verslag: [name] plaatst een [amount] credit bounty op [name2].";

$l_news_attackerpod_p_short = "FNN Verslag: [name] &#39;s schip wordt vernietigd.";
$l_news_attackerpod_P = "[name] &#39;s schip werd vernietigd, terwijl het aanvallen van een planeet. Gelukkig [name] had een Escape Pod en overleefd.";

$l_news_attackerdie_p_short = "FNN Verslag: [name] sterft!";
$l_news_attackerdie_p = "[name] &#39;s schip werd vernietigd, terwijl het aanvallen van een planeet en zij werden gedood omdat ze niet naar een Escape Pod te kopen.";

$l_news_destroyed_p_short = "FNN Verslag: [name] aanvallen en vernietigt een planeet!";
$l_news_destroyed_p = "[name] aangevallen [total] planet (s) die eigendom zijn van [owner] en de bevolking van elke planeet vernietigden de planeet te voorkomen dat het gevangen genomen!";

$l_news_defeated_p_short = "FNN Verslag: [name] aanvallen en verslaat een planeet!";
$l_news_defeated_p = "[name] aangevallen [total] planet (s) die eigendom zijn van [owner] en versloeg de verdediging van de planeet krachten!";

$l_news_notdefeated_p_short = "FNN Verslag: [name] een planeet aanvallen en verliest!";
$l_news_notdefeated_p = "[name] aangevallen [total] planet (s) die eigendom zijn van [owner] en de planetaire verdediging hield tegen de niet aflatende aanvallen!";

$l_news_targetepod_short = "FNN Verslag: [name] aanvallen van [owner] en wint!";
$l_news_targetepod = "[name] aangevallen [owner] &#39;s van schepen en het volledig vernietigd. Gelukkig [owner] was voorzien van hun schip met een Escape Pod en ze overleefden.";

$l_news_targetdies_short = "FNN Verslag: [name] aanvallen van [owner] en doodt hen!";
$l_news_targetdies = "[name] aangevallen [owner] &#39;s van schepen en het volledig vernietigd. Helaas [owner] niet voorzien van hun schip met een Escape Pod en ze waren verdampt.";

$l_news_fedcolbounty_short = "FNN Verslag: De Federatie pakt [name]!";
$l_news_fedcolbounty = "De Federatie van vandaag heeft gekraakt naar beneden op de beruchte piraat ruimte [name]! [name], die stelselmatig geschonden enkele ruimte verdragen, werd kort genomen door de Federatie slagkruiser, die toegebracht [amount] aan kredieten ten belope van de schade aan het vaartuig van de piraat. Federatie ambtenaren belofte meer van zulke acties in de toekomst!";

$l_news_alliancecolbounty_short = "FNN Verslag: De Alliantie pakt [name]!";
$l_news_alliancecolbounty = "De Alliantie is vandaag gekraakt naar beneden op de beruchte piraat ruimte [name]! [name], die stelselmatig geschonden enkele ruimte verdragen, werd kort genomen door de Alliantie, die toegebracht [amount] aan kredieten ten belope van de schade aan het vaartuig van de piraat. Alliance ambtenaren belofte meer van zulke acties in de toekomst!";

$l_news_fedcol_pbounty_short = "FNN Verslag: De Federatie jaagt down [name]!";
$l_news_fedcol_pbounty = "De Federatie van vandaag heeft gekraakt naar beneden op de beruchte piraat ruimte [name]! [name], die stelselmatig geschonden enkele ruimte verdragen, werd kort genomen door de Federatie slagkruiser, die de planeet in beslag genomen [planetname] ter waarde van [amount] kredieten in de sector [sector]. Federatie ambtenaren belofte meer van zulke acties in de toekomst!";

$l_news_alliancecol_pbounty_short = "FNN Verslag: De Alliantie jaagt van [name]!";
$l_news_alliancecol_pbounty = "De Alliantie is vandaag gekraakt naar beneden op de beruchte piraat ruimte [name]! [name], die stelselmatig geschonden enkele ruimte verdragen, werd kort genomen door de Alliantie, die de planeet in beslag genomen [planetname] ter waarde van [amount] kredieten in de sector [sector]. Alliance ambtenaren belofte meer van zulke acties in de toekomst!";

$l_news_fedcol_sbounty_short = "FNN Verslag: De Federatie jaagt down [name]!";
$l_news_fedcol_sbounty = "De Federatie van vandaag heeft gekraakt naar beneden op de beruchte piraat ruimte [name]! [name], die stelselmatig geschonden enkele ruimte verdragen, werd kort genomen door de Federatie slagkruiser, die een schip ([shiptype]) de moeite waard [cost] in de sector [sector]. Federatie ambtenaren belofte meer van zulke acties in de toekomst!";

$l_news_alliancecol_sbounty_short = "FNN Verslag: De Alliantie jaagt van [name]!";
$l_news_alliancecol_sbounty = "De Alliantie is vandaag gekraakt naar beneden op de beruchte piraat ruimte [name]! [name], die stelselmatig geschonden enkele ruimte verdragen, werd kort genomen door de Alliantie, die een schip in beslag genomen [shiptype] waard [cost] in de sector [sector]. Alliance ambtenaren belofte meer van zulke acties in de toekomst!";

$l_killheadline = "[target] werd gedood in een ongeval";
$l_news_killed = "[target] werd gedood in een tragisch ongeval vandaag. Hoe heldhaftig - [target] was het laatste lid aan boord van zijn schip, toen hij merkte dat er was geen uitweg pod lieten voor hem. Moge hij rusten in vrede!";

$l_killSDheadline = "[target] werd gedood door Sector Defenses.";
$l_news_killedSD = "[target] werd gedood door een overweldigend aantal van de sector Defenses eigendom van [killer]! Helaas was het schip niet uitgerust met een escape pod.";

$l_killplanetheadline = "[target] werd gedood aanvallen van een planeet.";
$l_news_killedplanet = "[target] werd gedood tijdens een aanval op onze planeet in handen van [killer] vandaag. Helaas was het schip niet uitgerust met een escape pod.";

$l_killshipheadline = "[target] werd gedood schip te bestrijden.";
$l_news_killedship = "[target] werd gedood in het schip ter bestrijding van het schip met [killer] vandaag. De kapitein blijkbaar vergeten om het schip uit te rusten met een escape pod.";

$l_killsuicideheadline = "[target] zelfmoord gepleegd.";
$l_news_killedsuicide = "[target] vandaag zelfmoord gepleegd. Ze namen de laffe uitweg omdat ze het vermogen of de moed om opgewassen te zijn tegen de druk van de commandant van hun eigen schip ontbrak.";

$l_killsofaheadline = "[target] werd gedood bank het aanvallen van een planeet.";
$l_news_killedsofa = "[target] werd gedood terwijl de bank een planeet in handen van [killer] vandaag aan te vallen. Helaas was het schip niet uitgerust met een escape pod.";

$l_killnovaheadline = "[target] werd gedood tijdens een aanval nova.";
$l_news_killednova = "[target] werd gedood door [killer] tijdens een nova bomaanslag vandaag. Helaas was het schip niet uitgerust met een escape pod.";

$l_killnovabackfireheadline = "[target] werd gedood uit een nova averechts werken.";
$l_news_killednovabackfire = "[target] werd gedood toen hun nova bom mislukte vandaag. Helaas was het schip niet uitgerust met een escape pod.";

$l_killsectormissileheadline = "[target] werd gedood uit een sector Missile.";
$l_news_killedsectormissile = "[target] werd gedood toen een sector Missile van [killer] invloed op hun schilden. Helaas was het schip niet uitgerust met een escape pod.";

$l_killhunterprobeheadline = "[target] werd gedood door een jager Probe.";
$l_news_killedhunterprobe = "[target] werd gedood toen een Hunter Probe van [killer] invloed op hun schilden. Helaas was het schip niet uitgerust met een escape pod.";

$l_killtrapprobeheadline = "[target] werd gedood door een Sentry Trap Probe.";
$l_news_killedtrapprobe = "[target] werd gedood toen een Sentry Trap Probe van [killer] invloed op hun schilden. Helaas was het schip niet uitgerust met een escape pod.";

//-------------------

$l_killpodheadline = "[target] &#39;s schip werd vernietigd in een ongeval";
$l_news_killedpod = "[target] &#39;s schip werd vernietigd in een tragisch ongeval vandaag. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killSDpodheadline = "[target] &#39;s schip werd vernietigd door de sector Defenses.";
$l_news_killedSDpod = "[target] &#39;s schip werd vernietigd door een overweldigend aantal van de sector Defenses eigendom van [killer]! Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killplanetpodheadline = "[target] &#39;s schip werd vernietigd, het aanvallen van een planeet.";
$l_news_killedplanetpod = "[target] &#39;s schip werd vernietigd, terwijl het aanvallen van een planeet in handen van [killer] vandaag. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killshippodheadline = "[target] &#39;s schip werd vernietigd in het schip te bestrijden.";
$l_news_killedshippod = "[target] &#39;s schip werd vernietigd in het schip ter bestrijding van het schip met [killer] vandaag. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killsofapodheadline = "[target] &#39;s schip werd vernietigd, terwijl bank een planeet aanvallen.";
$l_news_killedsofapod = "[target] &#39;s schip werd vernietigd, terwijl bank een planeet in handen van [killer] vandaag aan te vallen. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killnovapodheadline = "[target] &#39;s schip werd verwoest tijdens een nova aanval.";
$l_news_killednovapod = "[target] &#39;s schip werd verwoest door [killer] tijdens een nova bomaanslag vandaag. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &#39;s schip werd verwoest van een nova averechts werken.";
$l_news_killednovabackfirepod = "[target] &#39;s schip werd verwoest toen de bom nova mislukte vandaag. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &#39;s schip werd verwoest door een sector Missile.";
$l_news_killedsectormissilepod = "[target] &#39;s schip werd verwoest toen een sector Missile van [killer] invloed op hun schilden. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &#39;s schip werd verwoest door een Hunter Probe.";
$l_news_killedhunterprobepod = "[target] &#39;s schip werd verwoest toen een Hunter Probe van [killer] invloed op hun schilden. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &#39;s schip werd verwoest door een Sentry Trap Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s schip werd verwoest toen een Sentry Trap Probe van [killer] invloed op hun schilden. Een Escape Pod transponder werd opgespoord door de Federatie Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] is gepromoveerd tot [rank]";
$l_news_promoted = "De Federatie is verheugd over de bevordering van [name] te kondigen tot de rang van [rank].";

$l_news_demotedheadline = "[name] is gedegradeerd tot [rank]";
$l_news_demoted = "De federatie betreurt de degradatie van [name] te kondigen tot de rang van [rank].";

$l_news_namechangedheadline = "[oldname] haar naam veranderde in [newname]";
$l_news_namechanged = "[oldname] toegepast bij de Federatie Review Board om hun naam te veranderen in [newname]. De Federatie heeft verleend de naam te wijzigen. Vanaf deze dag [oldname] nu als wordt bekend [newname]. Alle schepen en planeten moeten werken hun gegevens onmiddellijk.";

$l_news_found_planets_short = "Federatie Survey: [found_planets] new gelegen planeten.";
$l_news_found_planets = "Federatie Survey Scouts hebben gelegen [found_planets] nieuwe planeten in recent ontdekte sectoren.";

$l_news_new_ports_short = "Federatie Survey: [new_ports] nieuw gebouwde havens.";
$l_news_new_ports = "Federatie van Ingenieurs hebben gebouwd [new_ports] nieuwe havens in recent ontdekte sectoren.";

$l_news_addedsectors_short = "Federatie Survey: [addedsectors] sectoren ontdekt.";
$l_news_addedsectors = "Federatie Survey Scouts hebben ontdekt [addedsectors] nieuwe sectoren. Voorzichtigheid is geboden.";

$l_news_artifactheadline = "[playername] afgerond [artifact]";
$l_news_artifact = "[playername] gevonden heeft alle stukken van de [artifact] en heeft alle macht te kunnen bieden.";

$l_news_artifactfoundheadline = "[playername] gevonden [artifact] stuk";
$l_news_artifactfound = "[playername] heeft gevonden een van de stukken van de [artifact] en behoeften [pieces] meer [piece].";

?>
