<?php
$l_warp_cantsame = "Je kunt niet een link maken als de bron is dezelfde als de bestemming.";
$l_warp_twoerror = "Met behulp van een Warp-editor om een twee-weg koppeling aan sector [target_sector] is niet toegestaan.";
$l_warp_sectex = "Cannot create warp link van de huidige sector - die verder gaat dan het maximum van $ link_max per sector.";
$l_warp_linked = "Doelsector ([target_sector]) is al een link van deze sector.";
$l_warp_coneway = "Koppeling gemaakt-een manier om";
$l_warp_ctwoway = "Koppeling gemaakt naar en van";
$l_warp_nomoney = "Je hebt niet genoeg credits met de ketting link te maken.";
$l_warp_noenergy = "Je hebt niet genoeg energie om de warp link te maken.";
?>
