<?php
$l_login_title = "Inloggen";
$l_login_pw = "Wachtwoord:";
$l_login_chooseres = "Kan uw schermresolutie bepalen. Kies het beste past:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problemen?";
$l_login_emailus = "E-mail ons";
$l_login_forgot_pw = "Wachtwoord vergeten? Vul dit veld leeg en druk op login.";
$l_login_settings = "Game-instellingen";
$l_login_change = "Veranderen";
$l_login_title2 = "Algemene Login voor AATraders";
$l_login_reset1 = "Geen Reset Geplande";
$l_login_reset2 = "Geplande Reset:";
$l_login_reset3 = "Geregelde Reset:";
$l_login_notice = "Belangrijk bericht:";
$l_login_endadminnews = "Einde van de Admin Nieuws";
$l_login_tourney_signup = "Toernooi Aanmeldingen Enabled";

$l_login_profile_only = "Alleen voor het profiel";
$l_login_newclosed_message = "Nieuwe aanmeldingen Gesloten";
$l_login_tourneymode = "Toernooi Running";
$l_login_tourneystarts = "Starts:";
?>
