<?php
$l_opt2_title = "Opties voor opslaan";
$l_opt2_passunchanged = "Wachtwoord is ongewijzigd gelaten. <BR><BR>";
$l_opt2_srcpassfalse = "Originele wachtwoord onjuist. Wachtwoord is ongewijzigd gelaten. <BR><BR>";
$l_opt2_newpassnomatch = "Nieuw wachtwoord velden komen niet overeen. Wachtwoord is ongewijzigd gelaten. <BR><BR>";
$l_opt2_passchanged = "Password changed. <BR><BR>";
$l_opt2_passchangeerr = "Fout bij wijzigen van het wachtwoord <BR><BR>";
$l_opt2_userintup = "User interface actualiseren. <BR><BR>";
$l_opt2_userintfail = "Failed to update user interface setting. <BR><BR>";
$l_opt2_chlang = "Taal is ingesteld op [lang]. <p>";
$l_opt2_chtemplate = "Template is ingesteld op [template]. <p>";
$l_opt2_dhtmlup = "Dynamic HTML actualiseren. <BR><BR>";
$l_opt2_dhtmlfail = "Failed to update dynamische html-instelling. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname gewijzigd in [name]. <BR><BR>";
$l_opt2_playernamechanged = "Speler naam veranderd in [name] en [amount] credits afgetrokken van uw schip rekening. <BR><BR>";
$l_opt2_mapwidth = "Lokaal en de Galaxy Map Breedte:";
?>
