<?php
$l_gns_title = "Gebruik Genesis Device";
$l_gns_turn = "Je hebt minimaal een beurt het gebruik van een apparaat ontstaan.";
$l_gns_onplanet = "U kunt geen gebruik maken van dit apparaat, terwijl op de planeet.";
$l_gns_full = "Het zonnestelsel is al vol.";
$l_gns_planetex = "Er is al een planeet in deze sector.";
$l_gns_nogenesis = "U hebt geen genese apparaten.";
$l_gns_forbid = "Het maken van een planeet in deze sector is niet toegestaan.";
$l_gns_bforbid = "De bases in deze sector te mengen met uw apparaat ontstaan. Planet schepping niet mogelijk.";
$l_gns_pcreate = "Planet gemaakt.";
$l_sgns_title = "Gebruik Sector Genesis Device";
$l_sgns_pcreate = "Sector [name] gemaakt.";
$l_sgns_nogenesis = "U hoeft niet iedere sector ontstaan apparaten.";
$l_sgns_forbid = "Het creëren van een sector ontstaan wormgat in deze sector is niet toegestaan.";
$l_sgns_forbid1 = "Het creëren van een sector ontstaan wormgat een Federatie sector is niet toegestaan.";
$l_sgcreate = "Nieuwe Sector Genesis Sector";
$l_sgcreatens = "Nieuwe Sector Genesis Link terug aan de bekende ruimte";
$l_sgns_forbid2 = "Meer dan [limit] links in SG sectoren zijn niet toegestaan.";
$l_sgns_forbid3 = "Cannot create Sector Genesis ketting koppeling van de huidige sector - die verder gaat dan het maximum van [limit] per sector.";
$l_sgns_nocredits = "Je hebt niet genoeg credits om een nieuwe sector te creëren.";
$l_sgns_shipcredits = "Credits op het schip:";
$l_sgns_createcost = "Kosten voor het creëren van nieuwe Sector:";
$l_sgns_complete = "Normaal Space Link Complete";
$l_sgns_sectorname = "Voer Sector Naam:";
$l_gns_max_unbased_planets = "De Federatie zal niet toestaan dat de creatie van meer planeten tot je minder dan [max_unbased_planets] unbased planeten.";

?>
