<?php
// port.php port_purchase.php
$l_trade = "Handel";
$l_title_port = "Port Trading";
$l_title_trade = "Trading Commodities";
$l_sector_war = "Oorlog embargo";
$l_war_info = "Oorlog woedt in deze sector. U kunt niet bij de poort door alle vijandelijke krachten.";
$l_no_trade = "Handel verboden";
$l_no_trade_out = "Trading bij deze poort is niet toegestaan voor buitenstaanders";
$l_no_trade_info = "Trading bij deze poort is niet toegestaan";
$l_buying = "Kopen";
$l_selling = "Verkopen";
$l_commodity = "Commodity";
$l_amount = "Hoeveelheid";
$l_price = "Prijs";
$l_buy = "Kopen";
$l_sell = "Verkopen";
$l_trade_st_info = "U hebt [free_holds] lege laadruimten, kunnen uitvoeren [free_power] meer energie-eenheden, en hebben [credits] credits.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Niet genoeg credits";
$l_creds_to_spend = "U hebt [credits] credits te geven.";
$l_cost = "Kosten";
$l_avail = "Beschikbaar";
$l_profit = "Winst";
$l_current = "Huidige";
$l_current_level = "Huidige niveau";
$l_current_qty = "Huidige Hoeveelheden";
$l_max = "Max";
$l_ifyouneedmore = "Als je meer je [igb]";
$l_ifyouneedplan = "De toegang van de planeet";
$l_igb_term = "IGB Banking Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Onbeperkt";
$l_full = "Vol";
$l_equipped = "Uitgerust";
$l_n_a = "n / a";
$l_item = "Item";
$l_totalcost = "Totale kosten";
$l_would_dump = "Wilt u op al uw kolonisten hier dumpen, klikt u op";
$l_noport = "Er is geen haven hier!";
$l_trade_turnneed = "Je hebt minimaal een beurt voor de handel op een haven of een planeet.";
$l_returnto_port1 = "hier";
$l_returnto_port2 = "Klik op [port_link] om terug te keren naar de haven menu.";
$l_notenough_cargo = "Je hebt niet genoeg de laadruimten voor de goederen die u wilt aanschaffen.";
$l_notenough_power = "Je hebt niet genoeg kracht opslag voor de energie die je wilt kopen.";
$l_notenough_credits = "Je hebt niet genoeg credits om de transactie te voltooien.";
$l_notenough_turns = "Je hebt niet genoeg wendt zich tot de transactie te voltooien.";
$l_trade_result = "Resultaten voor deze handel";
$l_trade_complete = "Handel afgesloten";
$l_trade_upgraded = "Opgewaardeerd naar niveau";
$l_trade_added = "toegevoegd";
$l_trade_installed = "geïnstalleerd";
$l_port_bounty = "U kunt geen toegang krijgen tot een speciale poort terwijl je een bounty op je gebracht door de Federatie hebben. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Je hebt niet genoeg credtis aan de overvloed van [amount] credits. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "De IGB heeft een vergrendeling op uw schip rekening te wijten aan een lening te late betaling. U kunt niet de handel op een speciale poort totdat u uw lening terug te betalen.";
$l_port_returntospecial = "terug te keren naar het aanbod depot.";
$l_toprobemenu = "te gaan naar de sonde menu.";
$l_ports_shiplimit = "Minimaal klasse schepen te monteren apparaat:";
$l_ports_needrepair = "Reparatie";

$l_ports_needcredits = "Je hebt niet genoeg credits voor deze transactie. De totale kosten";
$l_ports_needcredits1 = "credits en heb je alleen";

$l_ports_tradeforbidden = "Handel verboden";
$l_ports_nooutsiders = "Trading bij deze poort is niet toegestaan voor buitenstaanders.";

$l_bought = "Je hebt gekocht";
$l_sold = "U verkocht";
$l_notenough_commodity = "Je hebt niet genoeg [commodity] om de transactie te voltooien.";
$l_exceed_commodity = "Aantal [commodity] groter is dan de vraag en aanbod.";
$l_port_shiptoolarge = "Uw schip is te groot voor de handel op deze poort.";

$l_port_hold_unit = "Holds per eenheid";


$l_port_welcome = "Port [sectorname] Welkom op [player]";
$l_port_amountforsale = "De haven heeft [amount] eenheden van [commodity] te koop op [credits] credits per stuk.";
$l_port_holdsperunit = "[holds] de laadruimten nodig per eenheid.";
$l_port_howmanypurchase = "Hoeveel [commodity] eenheden zou u willen kopen?";
$l_port_unitstobuy = "Units te Koop";
$l_port_shipcarryingbuy = "Uw schip vervoert [shipunits] eenheden van [commodity]. U kunt de aankoop [buyunits] eenheden met de beschikbare laadruimte ruimte.";
$l_port_howmanysell = "[amount] eenheden van [commodity] @ [credits] credits per stuk.";
$l_port_unitstosell = "Eenheden to Sell";
$l_port_perform = "Voer Transactie";
$l_port_cargoholds = "Cargo Holds";

?>
