<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] hit [chm_roll] mijnen in de sector [chm_sector].";
$l_chm_youlostminedeflectors = "Je hebt verloren [chm_roll] mijne deflectoren.";
$l_chm_youlostallminedeflectors = "Je hebt verloren al uw mijne deflectoren.";
$l_chm_youhadnominedeflectors = "Je had niet de mijne deflectoren.";
$l_chm_yourshieldshitforminesdmg = "Uw schilden zijn getroffen voor [chm_mines_left] schade.";
$l_chm_yourshieldsaredown = "Uw schilden zijn naar beneden!";
$l_chm_youlostallyourshields = "Je hebt verloren al uw schild!";
$l_chm_yourarmorhitforminesdmg = "Je armor is getroffen voor [chm_mines_left] schade.";
$l_chm_yourhullisbreached = "Uw romp wordt overtreden!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] werd vernietigd door de mijnen in de sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Uw schip is vernietigd!";
$l_chm_luckescapepod = "Gelukkig heb je een escape-pod!";

$l_chm_yourdeflectormalf1 = "Mine Deflector lancering systeem is defect.";
$l_chm_yourdeflectormalf2 = "Je hebt alleen in staat geweest om te starten";
$l_chm_yourdeflectormalf3 = "procent van je mijn deflectoren.";
$l_chm_enemytorpfailshields = "heeft nog geen torpedo&#39;s gelanceerd tegen je schilden.";
$l_chm_enemytorpfailarmor = "heeft nog geen torpedo&#39;s gelanceerd tegen je armor.";

$l_chm_minemalf1 = "Enemy Mines hebben defect.";
$l_chm_minemalf2 = "Enige";
$l_chm_minemalf3 = "procent van de mijnen gevonden aanvallende uw schip.";

$l_chm_youhitsomemines = "Je slaat [chm_roll] mijnen van de [total_mines] mijnen!";
$l_chm_yourdeflectormalf2a = "Je hebt alleen in staat geweest om [deflectors] procent van je mijn deflectoren starten.";
$l_chm_mines_destroyed = "[number] van [target] mijnen zijn vernietigd!";
$l_chm_mine_deflectors_left = "U hebt [number] van mij deflectoren links.";
$l_chm_mines_left = "Er zijn [number] mijnen links en ze zijn impact heeft op je armor!";
$l_chm_minemalf2a = "Slechts [deflectors] procent van de mijnen gevonden aanvallende uw schip.";
$l_chm_mines_exhausted = "[player] Mines Uitgeput!";
$l_chm_armor_left = "U hebt [number] armor punten meer!";

?>
