<?php
$l_s_yes = "Ja";
$l_s_no = "Nee";
$l_s_enabled = "Ingeschakeld";
$l_s_disabled = "Gehandicapten";

$l_s_modules = "Modules";
$l_s_modulename = "Module Naam";
$l_s_moduleauthor = "Auteur";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "Geen modules zijn geladen";

$l_s_gamestatus = "Game Status";
$l_s_allowpl = "Spelers toestaan";
$l_s_allownewpl = "Laat Nieuwe Spelers";

$l_s_gameoptions = "Spelopties";
$l_s_allowteamplcreds = "Laat Team Planet Credit Transfer";
$l_s_allowfullscan = "Allow Full Long Range Scan";
$l_s_sofa = "Laat Sub-Orbital Fighter Aanvallen";
$l_s_showpassword = "Display Wachtwoord op registreren";
$l_s_genesisdestroy = "Genesis torps planeten kan vernietigen";
$l_s_igb = "Intergalactic Bank (IGB)";
$l_s_ksm = "Bekende Ruimte Maps";
$l_s_navcomp = "Navigatie Computer";
$l_s_newbienice = "Beginner Nice";
$l_s_spies = "Spy-systeem";
$l_s_spycapture = "Laat Spies naar planeten veroveren";

$l_s_gamesettings = "Game-instellingen";
$l_s_gameversion = "Game versie:";
$l_s_minhullmines = "Minimale romp omvang die nodig is om de mijnen hit";
$l_s_averagetechewd = "Tech gemiddeld niveau Als Emergency Warp Breekt";
$l_s_numsectors = "Aantal Sectoren";
$l_s_maxwarpspersector = "Maximale Links per sector";
$l_s_averagetechfed = "Maximale gemiddelde tech-niveau voor Federatie Sectoren";
$l_s_igbirateperupdate = "IGB Rente per update";
$l_s_igblrateperupdate = "IGB Lening tarief per update";
$l_s_techupgradebase = "Tech Level upgrade voor Bases";
$l_s_collimit = "Kolonisten Limit";
$l_s_maxturns = "Maximum aantal omwentelingen van de geaccumuleerde";
$l_s_maxplanetssector = "Maximum aantal planeten per sector";
$l_s_maxtraderoutes = "Maximum aantal handelsroutes per speler";
$l_s_colreprodrate = "Kolonist Geboortecijfer";
$l_s_energyperfighter = "Eenheid van energie die wordt gebruikt per sector vechter";
$l_s_secfighterdegrade = "Sector vechter afbraak percentage";
$l_s_planetinterest = "Planet rente";
$l_s_spiesperplanet = "Maximum aantal spionnen per planeet";
$l_s_spysuccessfactor = "Spy succesfactor";
$l_s_spykillfactor = "Spy doden factor";
$l_s_colsperfighter = "Kolonisten die nodig zijn om de productie van 1 Fighter per beurt";
$l_s_colspertorp = "Kolonisten die nodig zijn om de productie van 1 Torpedo per beurt";
$l_s_colsperore = "Kolonisten die nodig is voor 1 Ore per beurt";
$l_s_colsperorganics = "Kolonisten die nodig zijn om de productie van 1 Organics per beurt";
$l_s_colspergoods = "Kolonisten die nodig is voor 1 Goederen per beurt";
$l_s_colsperenergy = "Kolonisten die nodig is voor 1 Energie per beurt";
$l_s_colspercreds = "Kolonisten die nodig zijn om de productie van 1 Credits per beurt";
$l_s_colsper = "Kolonisten die nodig is om 1 te produceren [commodity] per beurt";

$l_s_gameschedsettings = "Game Scheduler Instellingen";
$l_s_schedtype = "Scheduler Type";
$l_s_cronbased = "Cron basis";
$l_s_playertriggered = "Speler Triggered";
$l_s_minutes = "minuten";
$l_s_ticksupdate = "Teken gebeuren om de";
$l_s_turnsupdate = "Zet er gaat gebeuren om de";
$l_s_npcupdate = "Het bondgenootschap zal spelen om de";
$l_s_igbturnsupdate = "Interesten op de rekeningen IGB zal worden verzameld om de";
$l_s_newsupdate = "Nieuws zal worden gegenereerd om de";
$l_s_planetupdate = "Planeten zal genereren om de productie";
$l_s_spyupdate = "Spies zal optreden om de";
$l_s_portsupdate = "Havens regenereert elke";
$l_s_towupdate = "Schepen zullen worden getrokken uit alle sectoren gevoed";
$l_s_scoreupdate = "Klassement zal worden gegenereerd om de";
$l_s_secdefdegrupdate = "Sector verdediging zal worden afgebroken om de";
$l_s_apocalypseupdate = "De planetaire apocalyps zal gebeuren elk";
$l_s_release_version = "Game release versie";
$l_s_time_since_reset = "Tijd sinds laatste reset";
$l_s_independence = "Planetaire Onafhankelijkheid";
$l_s_dignitaryupdate = "Hoogwaardigheidsbekleders zal optreden om de";

$l_s_turnsupdate = "maakt van elke";
?>
