<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Je hebt minimaal een beurt voor het scannen van een ander schip.";
$l_scan_ron = "Scan resultaten op";
$l_scan_capt = "Captained door:";
$l_scan_arma = "Bewapening:";
$l_scan_carry = "Uitvoering:";
$l_scan_bounty = "Dit schip heeft een totale premie op het van [amount] credits.";
$l_scan_fedbounty = "Dit schip heeft een premie op het van de Federatie.";
$l_by_nofedbounty = "Een aanval op deze speler zal <B>niet</b> resulteren in de Federatie het plaatsen van een bounty op je.";
?>
