<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Probe Niveaus";
$l_probe_engine = "Engine";
$l_probe_sensors = "Sensoren";
$l_probe_cloak = "Cloak";
$l_probe_title = "Space Probe Menu";
$l_probe_none = "U bent niet in dezelfde sector als de sonde, zodat je niet kunt communiceren met haar.";

$l_probe_named = "Welkom op de Probe nummer [probename], eigendom van [name], gelegen in de sector [sector].";
$l_probe_orders = "[orders] Probe om te zoeken universum";
$l_probe_orders_link = "Programma";
$l_probe_upgrade = "[upgrade] staafsensoren / Motor / Cloak";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] Probe voor latere plaatsing";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Update";

$l_probe_att_link = "Attack";
$l_probe_att = "[attack] op sonde";
$l_probe_att_sure = "Ben je zeker ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] sonde";

$l_probe_unknown = "Onbekend";
$l_plant_scn_turn = "Je hebt minimaal een beurt voor het scannen van een sonde.";
$l_probe_noscan = "Sensoren krijg er geen fix op schema!";
$l_probe_logscanA = "[name] probeerde een van de sondes in de sector scan [sector], maar dat mislukte.";
$l_probe_logscanB = "Een van de sondes in de sector [sector] werd gescand door [name].";
$l_probe_scn_report = "Scan resultaten op [name], die eigendom zijn van: [owner]";

$l_probe_caplog = "Uw sonde &#39;[probename]&#39; in de sector [sector] werd gevangen genomen door [name].";
$l_probe_scan = "Probe scans sector [sector] en vondsten:";
$l_probe_destroyprobe = "Destroy sonde";
$l_probe_destroyed = "Probe Vernietigd!";
$l_probe_warning = "Door dit te doen, wordt het totaal vernietigen deze sonde";
$l_probe_confirm = "Wil je echt bij deze sonde te vernietigen?";
$l_gns_turn = "Je hebt niet genoeg blijkt te vernietigen deze sonde";
$l_probe_type = "Probe Type";
$l_probe_type0 = "Stationaire Probe";
$l_probe_type1 = "Sentry Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sequential Realspace Probe";
$l_probe_target = "Doelgroep";
$l_probe_ordered = "Probe geprogrammeerd en zal beginnen met zoeken.";
$l_probe_order2 = "Probe is een [type] en is gericht op de sector [target]";
$l_probe_pickedup = "Probe opgepikt en geplaatst in actieve opslag";
$l_probe_title = "Probe Menu";
$l_probe_messages = "om te zien wat je spionnen hebben ontdekt.";

$l_probe_defaulttitle1 = "Actieve sondes";
$l_probe_defaulttitle2 = "Probes je hebt opgepikt";
$l_probe_defaulttitle3 = "Probes op de planeten";
$l_probe_defaulttitle4 = "Sondes op je schip";
$l_probe_linkback = "te gaan naar de sonde menu.";
$l_probe_no1 = "U heeft nog geen actieve sondes.";
$l_probe_no2 = "U hebt geen sondes in de opslag.";
$l_probe_no3 = "U hebt geen sondes op je planeten.";
$l_probe_no4 = "U hebt geen sondes op uw schip.";
$l_probe_noprobeatall = "U hebt geen probes.";
$l_probe_notknown = "Onbekend";
$l_probe_launch = "Laten vallen";
$l_probe_detect = "Herkend";
$l_probe_codenumber = "Code";
$l_probe_job = "Baan";
$l_probe_percent = "Percentage";
$l_probe_move = "Beweging";
$l_probe_view = "Bekijken";
$l_probe_action = "Actie";
$l_probe_shipowner = "Reder";
$l_probe_shipname = "Naam van het schip";
$l_probe_shiptype = "Schip Klasse";
$l_probe_shiplocation = "Ship Lokatie";
$l_probe_planetowner = "Planet Eigenaar";
$l_probe_planetname = "Planet";
$l_probe_sector = "Huidige sector";
$l_probe_tsector = "Doelgroep";
$l_probe_type = "Probe Type";
$l_probe_forbid = "U kunt geen sondes daling in deze sector";

$l_probe2_title = "Lancering Space Probe";
$l_probe2_turn = "Je hebt minimaal een beurt het gebruik van een ruimtesonde.";
$l_probe2_onplanet = "U kunt geen gebruik maken van dit apparaat, terwijl op de planeet.";
$l_probe2_noprobe = "U hebt geen ruimtesondes.";
$l_probe2_forbid = "De lancering van een sonde in deze sector is niet toegestaan.";
$l_probe2_launched = "Ruimtesonde gelanceerd!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Speler";
$l_probe2_onboarda = "aan boord van een";
$l_probe2_classship = "klasse schip";
$l_probe2_traveled = "reisde naar sector";
$l_probe2_fedjammed = "Federatie stoort alle sensor scant naar Sector 1.";
$l_probe2_lastseen = "Laatste schip Seen";
$l_probe2_portfound = "Port gevonden";
$l_probe2_supports = "Ondersteunt";
$l_probe2_planets = "planeten";
$l_probe2_sectord = "Sector verdediging Detected";
$l_probe2_mines = "Mijnen";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Schepen Detected";
$l_probe2_ships2 = "Schip Detected";
$l_probe2_noneowned = "Geen planeten geen eigendom is van u zijn gevonden.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Niets gedetecteerd";
$l_probe2_nocredits = "Je hebt niet genoeg credits voor deze transactie. De totale kosten is [total] credits en heb je alleen [credits] credits.";

$l_probe_forbidSG = "U kunt geen Realspace type sonde in Sector Genesis gemaakt sectoren.";
$l_probe_forbidFED = "U kunt geen Realspace type sonde in de Federatie of Alliantie in handen sectoren.";
$l_probe_forbidINVALID = "Uw bestemming sector is een sector ongeldige naam.";
?>
