<?php
$l_warp_linkto = "Links leiden uit deze sector te";
$l_warp_nolink = "Er zijn geen links uit deze sector.";
$l_warp_query = "Welke sector wilt u een link naar?";
$l_warp_oneway = "One-way?";
$l_warp_dest = "Als alternatief kunt u vernietigen een link naar de sector.";
$l_warp_destquery = "Welke sector wilt u verwijderen van een link naar?";
$l_warp_bothway = "Zowel-manieren";
$l_warp_create = "Maak een warp verband tussen Sector:";
$l_warp_andsector = "en Sector:";
$l_warp_distance = "met een afstand van";
$l_warp_lightyears = "lichtjaren";
$l_warp_delete = "Verwijderen warp verband tussen Sector:";
$l_warp_costcreate = "Kosten te maken:";
$l_warp_costdelete = "Kosten voor het verwijderen:";
$l_warp_costenergy = "Energie die nodig is:";
$l_warp_twoerror = "Met behulp van een Warp-editor om een twee-weg koppeling aan sector [target_sector] is niet toegestaan.";
?>
