<?php
$l_mail_title = "Mail Wachtwoord";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Wachtwoord is verzonden naar";
$l_mail_topic = "$ game_name Wachtwoord";
$l_mail_message = "Greetings, \ n \ nSomeone van het IP-adres $ ip verzocht om uw wachtwoord voor $ game_name naar u worden verzonden \ n \ nDe wachtwoord is: [pass] \ n \ u nThank \ n \ nDe $ game_name webteam.";
$l_new_login = "om naar het inlogscherm.";
$l_mail_failed = "Wachtwoord niet te sturen naar";
?>
