<?php
$l_defense_deploy_title = "Implementeer sector Mijnbouw &amp; Fighters";
$l_defense_deploy_noturn = "Je hebt minimaal een beurt te implementeren sector verdedigingen.";
$l_defense_deploy_nopermit = "Het implementeren van Mijnen en Fighters in deze sector is niet toegestaan.";
$l_defense_deploy_nodeploy = "Kan hier niet te zetten. Een ander schip of Team heeft mijnen of strijders in deze sector.";
$l_defense_deploy_info1 = "U bevindt zich momenteel in de sector [sector]. Er zijn [mines] mijnen en [fighters] strijders hier.";
$l_defense_deploy_info2 = "U hebt [mines] mijnen en [fighters] vechters beschikbaar te implementeren";
$l_defense_deploy_deploy = "Deploy";
$l_defense_deploy_deployed = "Ingezet";
$l_defense_deploy_att = "Attack";
$l_defense_deploy_notorps = "Je hebt niet genoeg torpedo&#39;s.";
$l_defense_deploy_nofighters = "Je hebt niet genoeg vechters";
$l_defense_deploy_dmines = "Ingezet [mines] mijnen.";
$l_defense_deploy_dfighter = "Ingezet [fighters] strijders.";
$l_defense_deploy_max_fighters = "Deze sector kan ondersteunen een maximum van [amount] strijders.";
$l_defense_deploy_toomanyfighters = "U hebt geprobeerd om meer strijders te zetten dan de sector kunnen ondersteunen.";
?>
