<?php
$l_contact_admin_title = "Contacteer Game Administrator";
$l_contact_admin_thanks = "Bedankt voor je reactie.";
$l_contact_admin_email_alert = "Geef een geldig e-mailadres.";
$l_contact_admin_name_alert = "Vul uw naam in.";
$l_contact_admin_comment_alert = "Geef hier uw commentaar.";
$l_contact_admin_name = "Naam";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Vraag / Opmerking";
$l_contact_admin_submit = "Met vragen / opmerkingen";
$l_contact_admin_close = "Sluit het venster";
$l_contact_admin_thanks_comment = "Bedankt voor uw vraag of opmerking. Wij zullen eventuele vragen en e-mail die u met onze reactie.";

?>
