<?php
$l_opt_title = "Opties";
$l_opt_chpass = "Wachtwoord wijzigen";
$l_opt_curpass = "Huidig wachtwoord:";
$l_opt_newpass = "Nieuw wachtwoord:";
$l_opt_newpagain = "Nieuw wachtwoord (nogmaals):";
$l_opt_userint = "User interface";
$l_opt_usenew = "Gebruik de nieuwe lay-out?";
$l_opt_lang = "Taal";
$l_opt_template = "Template";
$l_opt_select = "Maak een keuze:";
$l_opt_enabled = "Ingeschakeld";
$l_opt_save = "Redden";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Lokaal en de Galaxy Map Breedte:";
$l_opt_profiletitle = "Profiel";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Ingeschreven bij Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Wanneer u uw speler op een andere server van de sjabloon, de shoutbox en nieuws bovenstaande instellingen zullen gebruikt worden op de server.";
$l_opt_showshoutbox = "Toon Shoutbox:";
$l_opt_shownewscrawl = "Show Nieuws Crawl:";
$l_opt_playername = "Player Naam:";
$l_opt_playernamecost = "Federatie Name Change Fee: [amount] credits";
?>
