<?php
$l_readm_title = "Lees Bericht";
$l_readm_delete = "Bericht gewist";
$l_readm_nomessage = "Je hebt geen berichten voor u klaar ...";
$l_readm_center = "Bericht ontvangen Center";
$l_readm_sender = "Bericht Afzender";
$l_readm_captn = "Kapitein van de";
$l_readm_del = "Wissen";
$l_readm_repl = "Antwoorden";
$l_readm_return = "Klik hier om terug te keren naar het hoofdmenu";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Delete All";
$l_readm_subject = "Onderwerp";
$l_readm_quote = "Citeren";
$l_readm_block = "Afzender blokkeren";
$l_readm_alert = "Waarschuwingssysteem";
$l_readm_alertbody = "Schip Computer";
?>
