<?php
$l_ze_title = "Zone bewerken";
$l_ze_notowner = "U bent niet de eigenaar van dit gebied, zodat u kunt deze niet bewerken.";
$l_ze_name = "Naam van zone";
$l_ze_allow = "Toestaan";
$l_ze_attacks = "Laat aanvallen van andere schepen";
$l_ze_genesis = "Laat het creëren van nieuwe planeten";
$l_ze_return = "om terug te keren naar de zone-informatie pagina";
$l_ze_saved = "Uw wijzigingen zijn opgeslagen.";
$l_ze_namematch = "FOUT: de zone die u hebt opgegeven is vergelijkbaar met lucifers of een bestaande zone naam.";
?>
