<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&#39;Welkom in het Casino, bieden we momenteel de volgende Spelen en voorzieningen";
$l_casino_option = "&quot;Kamers";
$l_casino_detail = "&quot;Beschrijving";

// Blackjack
$l_bet = "&quot;Wedden dat";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;First Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Verzekeringen";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Splitsen";
$l_credits = "Credits";
$l_yourbet = "&quot;Uw Bet";
$l_nobet = "&quot;Uw inzet heeft uw kredietlimiet overschreden, kunt u inzet opnieuw.";
$l_dealerwins = "Dealer Wins!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer verliest!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Speler wint!";
$l_playerbust = "&quot;Speler Busts!";
$l_playerloses = "&quot;Speler verliest!";
$l_playerblackjack = "&quot;Speler BlackJack!";
$l_place_bet = "&quot;Plaats uw inzet";
?>
