<?php
$l_nav_title = "Navigatie Computer";
$l_nav_nocomp = "Navigatie Computer is niet beschikbaar";
$l_nav_query = "Voer de sector om het pad te vinden:";
$l_nav_pathfnd = "Pad gevonden";
$l_nav_answ1 = "Het zal u";
$l_nav_answ2 = "bochten te krijgen op deze sector.";
$l_nav_proper = "U moet uw Fighter Bay technologie-upgrade voor je vechters vind je een warp route voor die afstand.";
$l_nav_autoroutename = "Optioneel Autoroute Naam:";
$l_nav_manuallist = "Handmatig gebouwd WarpLink Autoroute Lijst";
$l_nav_warplinksleaving = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Er zijn geen warplinks het verlaten van deze sector.";
$l_nav_warp_from = "Warp uit";
$l_nav_rs_from = "RSMove uit";
$l_nav_notinlogs = "Er zijn geen gegevens beschikbaar over deze sector.";
?>
