<?php
$l_sf_attacking = "Sector verdediging strijders zijn je aanvalt! <BR>";
$l_sf_destfight = "Uw balken vernietigd [lost] strijders <BR>";
$l_sf_destfightb = "Uw balken vernietigd [lost] strijders <BR>";
$l_sf_torphit = "Torpedo&#39;s hit:";
$l_sf_destfightt = "Uw torpedo&#39;s vernietigd [lost] strijders <BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "U vernietigde alle vechters. <BR>";
$l_sf_destfightt2 = "U vernietigd [lost] strijders. <BR>";
$l_sf_lostfight = "Je hebt verloren alle vechters. <BR>";
$l_sf_lostfight2 = "Je hebt verloren [lost] strijders. <BR>";
$l_sf_armorbreach = "Je armor wordt overtreden! <BR>";
$l_sf_armorbreach2 = "Je armor is getroffen voor [lost] schade. <BR>";
$l_sf_sendlog = "[player] vernietigd [lost]-sector defensie-strijders in de sector [sector].";
$l_sf_lreport = "Je hebt verloren [armor] armor punten, [fighters] vechters, en gebruikt [torps] torpedo&#39;s. <BR><BR>";
$l_sf_shipdestroyed = "Uw schip is vernietigd! <BR><BR>";
$l_sf_sendlog2 = "Sector verdediging gevechtsvliegtuigen vernietigd [player] in de sector [sector].";
$l_sf_escape = "Gelukkig heb je een escape-pod! <BR><BR>";

$l_sf_fnoattack = "is niet het verzenden van een strijders aan te vallen je vechters.";
$l_sf_fnoattackt = "is niet het verzenden van een strijders aan te vallen je torpedo&#39;s.";
$l_sf_fnoattacka = "is niet het verzenden van een strijders aan te vallen je schild.";
$l_sf_flaunchmalf1 = "Uw vechter lancering systeem is defect.";
$l_sf_flaunchmalf2 = "Je hebt alleen in staat geweest om te starten";
$l_sf_flaunchmalf3 = "procent van je vechters.";
$l_sf_fightertorpexg = "Fighter van Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Schip Torpedo naar Sector Fighter Exchange";
$l_sf_fighterarmorexg = "Sector Fighter bij Ship Armor Exchange";
$l_sf_tlaunchmalf1 = "Uw torpedo lanceren systeem is defect.";
$l_sf_tlaunchmalf2 = "Je hebt alleen in staat geweest om te starten";
$l_sf_tlaunchmalf3 = "procent van je torpedo&#39;s.";
$l_sf_bountysd = "U hebt aangevallen een sector met een planeet die zou geven u een premie als je de planeet aangevallen. De Federatie heeft geactiveerd een automatische zelfvernietiging op al uw strijders en torpedo&#39;s. Niet aanvallen van de sector defensie weer in deze sector. U bent gewaarschuwd!";
?>
