<?php
$l_sn_title = "Sector Notes";
$l_sn_pntitle = "Sectoren met persoonlijke notities";
$l_sn_tntitle = "Sectoren met Team Notes";
$l_sn_psntitle = "Personal Sector Notes";
$l_sn_tsntitle = "Team Sector Notes";
$l_sn_editnote = "Edit Sector Opmerking:";
$l_sn_deleteedit = "Verwijderen of bewerken:";
$l_sn_addnote = "Voeg Sector Opmerking:";
$l_sn_list = "Lijst Sectoren Notes";
$l_sn_listts = "Lijst Sectoren met Team Notes";
$l_sn_addteam = "Voeg Team";
$l_sn_deleteteam = "Verwijderen Team";
$l_sn_delete = "Wissen";
$l_sn_saveteam = "Opslaan Team";
$l_sn_deletepersonal = "Verwijderen van persoonlijke";
$l_sn_addpersonal = "Voeg Personal";
$l_sn_savepersonal = "Opslaan Personal";
$l_sn_editpersonal = "Aanmaken Persoonlijke";
$l_sn_editteam = "Team bewerken";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Type";
$l_sn_hdowner = "Eigenaar / Team";
$l_sn_hdplanets = "Planeten";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mijnen";
$l_sn_hdscanfrom = "Scannen vanaf";
$l_sn_hddetail = "Detail";
$l_sn_hddate = "Datum / Tijd";
$l_sn_hddelete = "Wissen";
$l_sn_hdteam = "Team";
$l_sn_view = "Bekijken";
$l_sn_no = "Nee";
$l_sn_yes = "Ja";
$l_sn_nonotes = "Geen enkele sector merkt gevonden";

?>
