<?php
$l_by_title = "Bounties";
$l_by_noturn = "Je hebt minimaal een beurt te plaatsen of een premie te wijzigen.";
$l_by_amount = "Bounty Bedrag";
$l_by_place = "Plaats Bounty";
$l_by_nobounties = "Er zijn momenteel geen premies.";
$l_by_bountyon = "Bounty Op";
$l_by_placedby = "Geplaatst door";
$l_by_thefeds = "De Federatie";
$l_by_cancel = "Annuleren";
$l_by_yourself = "U kunt geen plaats een bounty op je zelf.";
$l_by_notenough = "Je hebt niet genoeg credits om een premie van dat bedrag plaats.";
$l_by_toomuch = "U kunt geen plek die genade. Maximale premie toegestaan op een andere speler is [percent] procent van je vermogen";
$l_by_zeroamount = "Bounties moet groter zijn dan 0 studiepunten.";
$l_by_placed = "De premie is geplaatst.";
$l_by_nobounty = "Die premie bestaat niet meer.";
$l_by_notyours = "Die premie was niet geplaatst door jou.";
$l_by_canceled = "De premie is geannuleerd.";
$l_by_action = "Actie";
$l_by_placebounty = "Plaats of bekijk premies.";
$l_by_moredetails = "Klik op de naam voor meer details.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "De speler die je, zetten de premie op niet bestaat.";
$l_by_destroyed = "U kunt geen plaats een premie op een speler met een verwoest schip.";
$l_by_nofedbounty = "U ontvangt een premie als je deze spelers schip of planeet aan te vallen.";
$l_by_fedcollectonly = "Alleen Federatie kan Collect Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "U ontvangt een premie als je een spion plaats op deze planeet spelers.";
$l_pay_partial = "Maak gedeeltelijke betaling";
$l_pay_button = "Betaal";

$l_by_thealliance = "De Alliantie";
$l_by_alliancecollectonly = "Alleen de Alliance kan Collect Bounty";
$l_by_bountyscan = "Bounty";
?>
