<?php
$l_news_title = "Universum Nieuws";
$l_news_info = "FNN is een van de leiders van de Galaxy&#39;s <br> in nieuws-en informatievoorziening. <br> Personeel 24 uur, zeven dagen per week door een <br> toegewijde medewerkers in de melkweg hoofdkwartier FNN&#39;s <br> in Proxima Centauri en in bureaus galaxywide!";
$l_news_for = "Nieuws voor";
$l_news_prev = "vorige dag";
$l_news_next = "volgende dag";
$l_news_none = "Sorry, geen nieuws vandaag.";
$l_news_flash = "News Flash";
$l_news_end = "Einde van het nieuws";
$l_news_bestviewed = "Best bekeken in Opera, Safari en IE";
$l_news_fedannouncements = "Federatie Mededelingen";
$l_news_planetarynews = "Planetaire Nieuws";
$l_news_planetshipnews = "Planetaire en Schip Nieuws";
$l_news_afteractionnews = "After Action Combat Nieuws";
?>
