<?php
$l_cu_storing = "Storing";
$l_cu_inistored = "<b>Alle ini-waarden zijn met succes opgeslagen.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Route Auto-ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto Route Bestemming";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Route wissen";
$l_cu_info = "Klik op de Start-sector Realspace op de sector en beginnen te vervormen naar de bestemming sector.";
$l_cu_delete2 = "Verwijderen Routes";
$l_cu_noroutes = "Geen Auto routes";
$l_cu_createroute = "Nieuwe Auto-Route";
$l_cu_deleted = "Auto routes geschrapt.";
$l_cu_return = "Terug naar Auto Route Menu klik";
$l_cu_created = "Auto route is gemaakt.";
$l_cu_realmove = "Realspace naar sector";
$l_cu_warpmove = "Warp naar volgende sector";
$l_cu_warpfinal = "Warp naar laatste sector";
?>
