<?php
$l_beacon_title = "Deploy Space Beacon";
$l_beacon_notpermitted = "Het implementeren van de ruimte bakens in deze sector is niet toegestaan.";
$l_beacon_reads = "Present baken keer gelezen";
$l_beacon_none = "Er is op dit moment niet een baken in deze sector.";
$l_beacon_enter = "Voer tekst in voor baken";
$l_beacon_nowreads = "Beacon luidt nu";
$l_beacon_donthave = "U hoeft niet een ruimte baken.";
?>
