<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Je hebt minimaal 1 wenden tot het bouwen van een basis";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "De Nova Bomb mist eng maar schade toebrengt op de planeet.";
$l_planet_novaturns = "De Nova Bomb vereist atleast [turns] blijkt te schieten.";
$l_planet_novafed = "De Nova Bomb zal niet van de macht in de Federatie sectoren.";
$l_planet_nonova = "U hoeft niet een Nova Bomb geïnstalleerd.";
$l_planet_firenova = "Fire Nova Bomb";
$l_planet_novaexplode = "Nova bom ontplofte als het werd ontslagen en je schip heeft enorme schade geleden.";
$l_planet_novaexplode2 = "Nova bom ontplofte als het werd ontslagen en je schip werd verwoest.";
$l_planet_noautotrade = "Auto Handel route niet ingesteld voor deze planeet.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] in de haven [dest_id]";
$l_planet_autotradedelete = "Verwijderen Auto Handel.";
$l_planet_autotradeadd = "Maak Auto Handel.";
$l_planet_tradedeleted = "Auto Trade Route schrappen.";
$l_planet_tradeadded = "Nieuwe Auto Handel Route Added.";
$l_planet_autotype = "Selecteer het item voor de handel";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Je moet een vrachtschip te kopen voor deze planeet voordat u een automatische handelsroute kunt instellen.";
$l_planet_purchasecargo = "Als u wilt kopen een vrachtschip";
$l_planet_upgradecargo = "Wilt u een upgrade van uw vrachtschepen";

$l_planet_cargocapacity = "Capaciteit:";
$l_planet_cargoowned = "U heeft al een vrachtschip voor deze planeet.";
$l_planet_cargoshipbuy = "Aankoop Cargo Ship";
$l_planet_cargoshipupgrade = "Upgrade voor vrachtschepen";
$l_planet_cargoatmax = "Uw vrachtschip is op het maximale niveau opwaarderen.";
$l_planet_cargoshipbuyinfo = "Selecteer een preset voor vrachtschepen";
$l_planet_cargoshipupgradeinfo = "Upgrade uw vrachtschepen Hull.";
$l_planet_cargoshipbuildinfo = "Bouw uw eigen vrachtschepen";
$l_planet_tradehelp = "1. U kunt een trade port voor elk type grondstof. <br> 2. Je kunt niet een commodity handel op een poort die dezelfde grondstof verkoopt. <br> De handel in goederen in een haven Goederen, erts in een Ore Port, ect. niets zullen doen. <br> 3. Als u niet wilt dat bepaalde grondstoffen handel voert u 0 voor de havensector.";
$l_planet_cargocredits = "Auto Handel Credits Received:";
$l_planet_cargonoown = "U moet eigenaar zijn van de planeet om een Auto Traderoute.";
$l_planet_digtrans = "Overdracht hoogwaardigheidsbekleder";
$l_planet_nocredits1 = "Je hebt niet genoeg credits voor deze transactie. De totale kosten";
$l_planet_nocredits2 = "credits en heb je alleen";
$l_planet_nobase = "Je moet een basis om de planeet verdediging levels te beheren.";
$l_planet_genesisnoturn = "Je hebt minimaal 1 beurt aan Genesis apparaat te gebruiken op de planeet.";
$l_planet_nogenesis = "Je hebt een Genesis Apparaat om een planeet te vernietigen.";
$l_planet_wrongclass = "Dit schip klasse kan geen brand-a-Nova Bomb apparaat.";

$l_planet_combatpreview = "Combat Preview";
$l_planet_beamfire1 = "Uw aanval is ontdekt. Planetaire Balken schieten! Verhoogde Breedte Vuur als uw schip komt in het te dicht bij de planeet om strijders te starten.";
$l_planet_beamfire2 = "Uw aanval is ontdekt. Planetaire Balken schieten! Enorme brand snelheid van de planeet als Beam Batterijen slot op voor meerdere hits!";
$l_planet_beamfire3 = "Uw aanval is ontdekt. Planetaire Balken schieten! Breedte Batterijen over de hele planeet zijn vergrendeling op voor de massale meerdere vuur! Breedte brand veel hoger dan geraamd!";
$l_planet_beamfire4 = "Uw aanval is ontdekt. Planetaire Balken schieten! Breedte verdediging kan alleen een slot op voor het bakken pass.";

$l_planet_sofanobeamsshields = "is niet vuren balken op je schilden.";
$l_planet_sofanobeamsarmor = "is niet vuren balken op je wapenuitrusting.";
$l_planet_flauncherfailed1 = "Uw vechter lancering systeem is defect.";
$l_planet_flauncherfailed2 = "Je hebt alleen in staat geweest om te starten";
$l_planet_flauncherfailed3 = "procent van je vechters.";
$l_planet_nodfightertofighter = "is niet het verzenden van een strijders aan te vallen je vechters.";
$l_planet_nodfightertotorp = "is niet het verzenden van een strijders aan te vallen uw torps.";
$l_planet_flauncherfailed3 = "procent van je vechters.";
$l_planet_autotradetype = "- [source_type] in de haven [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "aanvalt";
$l_planet_iminsector = "in de sector";
$l_planet_imnova = "wordt met behulp van een Nova Apparaat";
$l_planet_imsofa = "SOFA is Bombing";
$l_planet_team = "Deze planeet is in handen van een teamgenoot en je hebt geen toestemming om de informatie voor deze planeet toegang.";
?>
