<?php
$l_login_sclosed = "Server Gesloten";
$l_login_closed_message = "Server gesloten tot nader order.";
$l_login_title2 = "Log in fase twee";
$l_login_banned = "<b>Je bent verbannen van dit spel door de beheerder. U bent niet langer welkom om te spelen op deze server. Volgende keer gedragen.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "Vanwege de ernst van dit misdrijf en de vicieuze aanval tegen u, heeft de federatie besloten genadig te voorzien in een gratis klonen van je blijft. Helaas, zelfs in deze tijd kunnen er nieuwe klonen geen eigen pand, naast de basis om te leven. U wordt uitgerust met een eenvoudige schip en een aantal credits om mee te beginnen. Hopelijk is uw volgende leven beter zal zijn.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Je had geen ontkomen pod, en als gevolg van uw bescheiden succes in dit leven, de Federatie weigert kloon je. Je blijft moet uiteindelijk vallen in een zwaartekracht goed, hopelijk worden gebruikt om leven te creëren elders ... enkele miljarden jaren van nu. <BR><BR> Better luck next game ...";
$l_login_4gotpw1 = "Het ingevoerde wachtwoord is onjuist. <BR><BR> Als u uw wachtwoord bent vergeten,";
$l_login_4gotpw2 = "te laten e-mailen naar je. <BR><BR> Anders,";
$l_login_4gotpw3 = "om opnieuw te proberen. Poging aangemeld met een IP-adres van";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Je hebt het leven in een verschrikkelijke incident.";
$l_login_blackbox = "is de blackbox informatie die werd opgehaald uit uw schepen wrak.";
$l_new_login = "om naar het inlogscherm.";
$l_login_playerlimit = "De server heeft het maximum aantal spelers wordt ondersteund. Meld je aan op een later tijdstip.";
?>
