<?php
$l_opt_title = "Kies een team Icon";
$l_opt_errorsize = "Fout: Uw afbeelding mag niet groter zijn dan 64x64 pixels.";
$l_opt_errortype = "Fout: Foto moet worden JPG, GIF of PNG";
$l_opt_errornographic = "Fout: geen grafische geselecteerd.";
$l_opt_currentavatar = "Uw huidige team Icon";
$l_opt_uploadavatar = "Upload een Icon";
$l_opt_directory = "Selecteer Team Icon-gids";
$l_opt_change = "Change Directory";
$l_opt_select = "Selecteer Team Icon";
$l_opt_noteam = "U bent niet in een team.";
$l_opt_notleader = "Alleen de Team Coördinator kunt het Team Icon.";
$l_opt_inuse = "Alle Team Pictogrammen in deze map in gebruik zijn.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
