<?php
$l_opt_title = "Selecteer een Avatar";
$l_opt_errorsize = "Fout: Uw afbeelding mag niet groter zijn dan 64x64 pixels.";
$l_opt_errortype = "Fout: Foto moet worden JPG, GIF of PNG";
$l_opt_errornographic = "Fout: geen grafische geselecteerd.";
$l_opt_currentavatar = "Uw huidige Avatar";
$l_opt_uploadavatar = "Upload een Avatar";
$l_opt_directory = "Selecteer Avatar Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Selecteer Avatar";
$l_opt_inuse = "Alle avatars in deze directory in gebruik zijn.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
