<?php
$l_pre_title = "Verander Realspace Presets";
$l_pre_exceed = "Preset [preset] overschrijdt universum max van [sector_max]. Geen presets opgeslagen. <BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Redden";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] is een ongeldige naam sector.";
$l_pre_invalidchange = "[sector] is een sector Genesis Sector. Uw oude preset is ongewijzigd.";
?>
