<?php
$l_new_pwis = "Uw wachtwoord is";
$l_new_charis = "Jouw personage heet";
$l_new_title2 = "Nieuwe Speler Fase Twee";
$l_new_blank = "E-mail, naam van het schip, en het karakter naam mag niet leeg zijn.";
$l_new_inuse = "E-mail adres [username] is al in gebruik.";
$l_new_forgotpw = "Wachtwoord vergeten?";
$l_new_inusechar = "Karakter naam [character], is al in gebruik.";
$l_new_similar_inusechar = "Je personage naam klinkt ook gelijk aan [character], een naam die al in gebruik.";
$l_new_inuseship = "Naam van het schip [shipname], is al in gebruik.";
$l_new_similar_inuseship = "Uw naam van het schip klinkt te lijken op [shipname], een naam die al in gebruik.";
$l_new_pwsent = "Wachtwoord is verzonden naar [username].";
$l_new_err = "Probeer opnieuw";
$l_new_topic = "Alien Assault Traders Wachtwoord";
$l_new_message = "Greetings, \ n \ nSomeone van het IP-adres $ ip verzocht om uw wachtwoord voor Handelaren naar u worden verzonden. \ N \ nDe wachtwoord is: [pass] \ n \ u nThank \ n \ nDe Traders webteam.";
$l_new_invalidemail = "Ongeldig e-mailadres.";
$l_new_tutorial = "Klik hier om te lezen van de Mini-handleiding voor het inloggen op het spel.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "om naar het inlogscherm.";

?>
