<?php
$l_ship2_buytitle = "Het kopen van een nieuw schip";
$l_ship2_storetitle = "Scheepswerf Storage Facility";
$l_ship2_wrongclass = "Verkeerde klasse schip opgegeven";
$l_ship2_buying = "U koopt:";
$l_ship2_tradein = "Handel in:";
$l_ship2_value = "Huidig schepen Waarde:";
$l_ship2_newvalue = "Nieuwe schepen Waarde:";
$l_ship2_totalcost = "Totale kosten:";
$l_ship2_nomoney = "Je hebt niet genoeg credits om dit schip te kopen.";
$l_ship2_purchase = "Kopen";
$l_ship2_buynstore = "Koop Nieuw schip en opslaan van oude";
$l_ship2_nomoney2 = "Je hebt niet genoeg credits om deze transactie te voltooien.";
$l_ship2_paystorage = "Je hebt verwijderd van uw schip uit de opslagplaats.";
$l_ship2_turns = "Je hebt tenminste [turns] wendt zich tot het uitvoeren van deze actie";
$l_ship2_error = "Interne fout. Kan niet vinden schip klasse.";
$l_ship2_owned = "U heeft al een eigen model van dit schip.";
$l_ship2_shipbought = "U heeft net kochten een nieuw schip!";

?>
