<?php
$l_sm_title = "Sector lanceren van raketten";
$l_sm_invalid = "Er is niet een warp verband tussen deze sector en de sector van bestemming.";
$l_sm_notarg = "Target niet in deze sector.";
$l_sm_noturn = "Je hebt minimaal een beurt bij brand uw sector Missile.";
$l_sm_nosectormissile = "U bent niet die enige sector Raketten.";
$l_sm_noscan = "Sensoren krijg er geen fix op schema!";
$l_sm_flee = "Streefwaarde manoeuvreerde de sector Missile!";
$l_sm_ewd = "Target die een nood-warp-apparaat wanneer het ontdekt de sector Missile!";
$l_sm_imtitle = "Schip Under Attack";
$l_sm_imbody = "[playername] is tijdens de aanval van uw schip met een sector Missile!";
$l_sm_sectormissilefail = "De sector Missile defect raken als het schild van de vijandelijke schepen!";
$l_sm_sectormissilefail2 = "De sector Missile wanneer het defect raken van de vijandelijke schepen harnas!";
$l_sm_shieldhit = "[target] &#39;s schilden zijn hit voor [amount] schade!";
$l_sm_shieldsdown = "[target] &#39;s schilden zijn naar beneden!";
$l_sm_armorhit = "[target] &#39;s harnas wordt getroffen voor [amount] schade!";
$l_sm_armorbreached = "[target] &#39;s armor geschonden!";
$l_sm_targetnoenergy = "Het vijandelijk schip heeft geen energie! Sector Missile mislukt!";
$l_sm_attacking = "Aanvallen [target] aan boord van de [shipname]";
$l_sm_targetok = "U hebt geen destory [name] &#39;s schip.";
$l_sm_lost = "[target] verloren [armor] armor punten en [energy] energie-eenheden.";
$l_sm_destroyed = "[target] &#39;s schip is vernietigd.";
$l_sm_escapepod = "Een escape-pod is gelanceerd!";
?>
