<?php
$l_footer_one_player_on = "Er is 1 player online.";
$l_footer_players_on_1 = "Er zijn";
$l_footer_players_on_2 = "Spelers online:";
$l_footer_until_update = "seconden tot de volgende update.";
$l_footer_no_players_on = "Er zijn geen spelers online.";

$l_footer_news = "Lokaal FNN Nieuws";
$l_footer_title = "Alien Assault Handelaren";
$l_footer_help = "voor hulp over deze pagina.";
$l_footer_click = "Klik op";

$l_footer_open_slots = "Maximum Online:";
$l_footer_onlinereset = "Spelers Online Time Reset";
$l_footer_onlinecountdown = "Spelers Online Time Countdown:";
?>
