<?php
$l_zi_title = "Zone-informatie";
$l_zi_nexist = "Dit gedeelte van de ruimte bestaat niet!";
$l_zi_feds = "Federatie";
$l_zi_traders = "Alliance Space";
$l_zi_nobody = "Niemand";
$l_zi_war = "Betwiste ruimte";
$l_zi_allow = "Toegestaan";
$l_zi_notallow = "Niet toegestaan";
$l_zi_limit = "Beperkt tot de eigenaar en bondgenoten";
$l_zi_ul = "Onbeperkt";
$l_zi_control = "U bent in controle van deze zone";
$l_zi_tochange = "te veranderen zijn wetten.";
$l_zi_owner = "Zone eigenaar";
$l_zi_maxhull = "Maximale gemiddelde tech niveau toegestaan";
?>
