<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: Shoutbox::.";
$l_shout_public = "Publiek";
$l_shout_team = "Team";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "anders";
$l_shout_refresh = "Vernieuwen";
$l_shout_close = "Sluit het venster";
$l_shout_saved = "Shout gered!";
$l_shout_return = "Terug naar de";
$l_shout_prev = "Vorige";
$l_shout_next = "Volgende";
$l_shout_selectpage = "Selecteer Pagina";
$l_shout_page = "Pagina:";
$l_shout_teamtitle = ".:: TEAM Shoutbox::.";
?>
