<?php
$l_autoroute_missingwarp = "Volgende warplink ontbreekt in deze sector. Warp verhuizing afgebroken.";
$l_autoroute_SDabort = "Verplaats Afgebroken vanwege Sector Defenses in de sector.";
$l_autoroute_turns = "Afgetrokken [triptime] Turns en verhuisde naar [targetlink]";
$l_autoroute_noturns = "U bent uit de bocht.";
$l_autoroute_title = "Auto routes";
$l_autoroute_id = "Route Auto-ID";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination = "Auto Route Bestemming";
$l_autoroute_warps = "Auto Route Warps";
$l_autoroute_deleteroute = "Route wissen";
$l_autoroute_info = "Klik op de Start-sector Realspace op de sector en beginnen te vervormen naar de bestemming sector.";
$l_autoroute_delete2 = "Verwijderen Routes";
$l_autoroute_noroutes = "Geen Auto routes";
$l_autoroute_createroute = "Nieuwe Auto-Route";
$l_autoroute_deleted = "Auto routes geschrapt.";
$l_autoroute_return = "Terug naar Auto Route Menu klik";
$l_autoroute_created = "Auto route is gemaakt.";
$l_autoroute_realmove = "Realspace naar sector";
$l_autoroute_warpmove = "Warp naar volgende sector";
$l_autoroute_warpfinal = "Warp naar laatste sector";
$l_autoroute_editname = "Naam bewerken";
?>
