<?php
$l_att_title = "Attack Ship";
$l_att_notarg = "Target niet in deze sector.";
$l_att_noturn = "Je hebt minimaal een beurt aan te vallen.";
$l_att_noatt = "Een aanval op iemand die in deze sector is niet toegestaan.";
$l_att_flee = "Streefwaarde gemanoeuvreerd u!";
$l_att_ewd = "Target die een nood-warp apparaat wanneer aangevallen!";
$l_att_att = "Attacking";
$l_att_beams = "Breedte Exchange";
$l_att_torps = "Torpedo Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost = "verloren";
$l_att_ylost = "Je hebt verloren";
$l_att_sdown = "&#39;s schilden zijn naar beneden!";
$l_att_ydown = "Uw schilden zijn naar beneden!";
$l_att_shits = "&#39;s schilden zijn voor hit";
$l_att_yhits = "Uw schilden zijn voor de getroffen";
$l_att_dmg = "schade";
$l_att_sarm = "&#39;s armor geschonden!";
$l_att_yarm = "Je armor heeft geschonden!";
$l_att_ashit = "&#39;s armor is voor hit";
$l_att_ayhit = "Je armor is voor hit";

$l_att_efhit = "&#39;s-strijders worden vernietigd.";
$l_att_yfhit = "van uw strijders worden vernietigd.";
$l_att_ethit = "&#39;s torpedo&#39;s worden vernietigd.";
$l_att_ythit = "van uw torpedo&#39;s worden vernietigd.";
$l_att_of = "van";
$l_att_lostt = "verloor alle torpedo&#39;s.";
$l_att_ylostt = "Je hebt verloren alle torpedo&#39;s.";

$l_att_lostf = "verloor alle vechters.";
$l_att_ylostf = "Je hebt verloren alle vechters.";
$l_att_sdest = "&#39;t schip is vernietigd.";
$l_att_espod = "Een escape-pod is gelanceerd!";
$l_att_ysalv = "U geborgen [ship_salvage_rate]% van het schip voor [ship_salvage] credits. <BR> Uw cijfer veranderd door [rating_change] punten.";
$l_att_andused = "en gebruikt";
$l_att_stilship = "U hebt geen destory [name] &#39;s schip.";
$l_att_atyou = "u het slachtoffer bent";
$l_att_and = "en";
$l_att_yshiplost = "Uw schip is vernietigd!";
$l_att_salv = "[name] geborgen [ship_salvage_rate]% van het schip voor [ship_salvage] credits";
$l_att_loosepod = "Gelukkig heb je een escape-pod!";

$l_att_tnobeams = "naden zijn uit zijn bundel energie.";
$l_att_tnobeamsf = "naden zijn uit zijn bundel van energie en kan niet aanvallen je vechters.";
$l_att_tnobeamst = "naden zijn uit zijn bundel van energie en kan niet aanvallen je torpedo&#39;s.";
$l_att_tfnoattack = "is niet het verzenden van een strijders aan te vallen uw schip.";
$l_att_tnotorps = "lijkt uit te worden van de torpedo&#39;s.";

$l_att_anobeams = "U hebt uitgeput je schepen stralingsenergie.";
$l_att_anobeamsf = "U hebt uitgeput je schepen stralingsenergie en kan niet een aanval op de vijandelijke strijders.";
$l_att_anobeamst = "U hebt uitgeput je schepen stralingsenergie en kan niet een aanval op de vijandelijke torpedo&#39;s.";
$l_att_anofighters = "Uw schip heeft al availible strijders.";
$l_att_anotorps = "U hebt uitgeput uw availible torpedo&#39;s.";
$l_att_imtitle = "Schip Under Attack";
$l_att_imbody = "aanvalt uw schip.";

$l_att_luckybeams = "Enemy balken overbelasting van het toebrengen van";
$l_att_luckyfighters = "Vijandelijke strijders een verrassing bliksem aanval en veroorzaken";
$l_att_luckytorps = "Vijandelijke torpedo&#39;s veroorzaken een cascade-effect veroorzaken schade";
$l_att_luckytimes = "keer de normale schade!";
?>
