<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Uw scanners beschikken niet over lange afstand volledige scan-mogelijkheden.";
$l_lrs_noturns = "Je moet ten minste $ fullscan_cost beurt (en) aan een lange reeks volledige scan te starten.";
$l_lrs_used = "Gebruikt";
$l_lrs_turns = "turn (s)";
$l_lrs_left = "links";
$l_lrs_reach = "De volgende locaties kan bereikt worden vanuit de sector [sector]:";
$l_lrs_links = "Links";
$l_lrs_ships = "Schepen";
$l_lrs_click = "Klik op een van de links om naar die sector.";
$l_lrs_cantscan = "Kan niet scannen sector van de huidige sector!";
$l_lrs_zero = "Sector 1 is te druk om te scannen op schepen!";
$l_lrs_moveto = "om naar de sector";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Logboek";
$l_lrs_fedjammed = "Federatie stoort alle sensor-scans.";
$l_lrs_sectormissile_question = "bij brand sector raket.";
$l_log_months = "array ( &#39;Januari&#39;, &#39;Februari&#39;, &#39;Maart&#39;, &#39;April&#39;, &#39;Mei&#39;, &#39;Juni&#39;, &#39;Juli&#39;, &#39;Augustus&#39;, &#39;September&#39;, &#39;Oktober&#39;, &#39;November&#39;, &#39;December&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;februari&#39;, &#39;Mar&#39;, &#39;april&#39;, &#39;mei&#39;, &#39;juni&#39;, &#39;juli&#39;, &#39;augustus&#39;, &#39;september&#39;, &#39;oktober&#39;, &#39;november&#39;, &#39;december&#39;)";
?>
