<?php
$l_shipyard_title = "Scheepswerf";
$l_planet = "Planet";
$l_ship_welcome = "Welkom bij uw Planetaire scheepswerf. Momenteel bieden we deze modellen te koop.";
$l_ship_class = "Klasse";
$l_ship_properties = "Klasse-eigenschappen";
$l_ship_current = "Huidige";
$l_ship_outstorage = "Get out of opslag";
$l_ship_storagecost = "Opslagkosten";
$l_ship_storagewarn = "Zodra u uw Pioneer uit de opslag je verliest degene die u zijn afgegeven op uw eerste schip vernietiging.";
$l_ship_levels = "Schip Componenten Niveaus";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Prijs";
$l_ship_turns = "Zet op te bouwen";
$l_ship_purchase = "Kopen";
$l_ship_stored = "Opgeslagen";
$l_ship_basehull = "Base Romp:";

$l_ship_averagemaxtech = "Gemiddelde Maximum Tech Level:";
$l_ship_averagenormaltech = "Gemiddelde Normaal Tech Level:";
$l_ship_averagecurrenttech = "Gemiddelde huidige Tech Level:";
?>
