<?php
///SPIES
$l_spy_title = "Spy Menu";
$l_spy = "Spies";
$l_spy_disabled = "Spionnen worden uitgeschakeld!";
$l_spy_noturn = "Je hebt minimaal een beurt om een spion te sturen naar een planeet.";
$l_spy_notonboard = "U hebt geen spionnen aan boord.";
$l_spy_ownplanet = "Je kunt niet sturen een spion naar je eigen planeet.";
$l_spy_unownedplanet = "Je kunt niet sturen een spion naar onbeheerd planeet.";
$l_spy_planetfull = "Er zijn reeds toegestaan [max] spionnen op die planeet.";
$l_spy_sendtitle = "Het verzenden van een spion [spyID] om de planeet: <BR> Selecteer spion&#39;s missie:";
$l_spy_type1 = "De spion alleen besluiten op die planeet.";
$l_spy_type2 = "De spion probeert te infiltreren in een schip dat een planetaire overbrenging uitvoert.";
$l_spy_type3 = "De spion probeert te infiltreren in een schip dat een planetaire overbrenging uitvoert en vervolgens te infiltreren naar een andere planeet.";
$l_spy_sendbutton = "Stuur naar planeet";
$l_spy_sendsuccessful = "Uw spion infiltreert in de wereld en wacht op het juiste moment om actie te beginnen.";
$l_spy_sendfailed = "Planet&#39;s Sensoren ontdekt uw spion, omdat uw Cloak apparaat hem niet konden dekken. Uw spion wordt gedood.";
$l_spy_noturn2 = "Je hebt minimaal een beurt om terug te bellen een spion.";
$l_spy_confirm = "Weet u zeker dat u terug te bellen uw spion [spyID]?";
$l_spy_cleanupplanet = "om schoon te maken die planeet van de vijandelijke spionnen.";
$l_spy_cleanupship = "Als u wilt opruimen uw schip tegen vijandelijke spionnen, klikt u op";
$l_spy_yourspies = "Uw spionnen op die planeet";
$l_spy_sendnew = "Stuur een nieuwe spion";

$l_spy_codenumber = "Code";
$l_spy_job = "Baan";
$l_spy_percent = "Percentage";
$l_spy_move = "Beweging";
$l_spy_action = "Actie";
$l_spy_shipowner = "Reder";
$l_spy_shipname = "Naam van het schip";
$l_spy_shiptype = "Schip Klasse";
$l_spy_shiplocation = "Ship Lokatie";
$l_spy_planetowner = "Planet Eigenaar";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "Beweegt niet";
$l_spy_moves['toship'] = "Om schip";
$l_spy_moves['toplanet'] = "Om planeet";

$l_spy_comeback = "Call back";
$l_spy_nospieshere = "U hebt geen spionnen op deze planeet!";
$l_spy_transferred = "spionnen overgedragen";
$l_spy_backonship = "De spion is nu op uw schip.";
$l_spy_backfailed = "Call back mislukt.";
$l_spy_changetitle = "Veranderende spion [spyID] eigenschappen:";
$l_spy_occupied = "Uw spion [spyID] in dienst is als [job], met een procent [percent].";
$l_spy_dismiss = "Negeren van de spion?";
$l_spy_changebutton = "Veranderen";
$l_spy_changejob = "Van baan veranderen of Movement";
$l_spy_linkback = "naar de spion menu.";
$l_spy_changed1 = "Beweging veranderd.";
$l_spy_changed2 = "Spion ontslagen en zijn beweging veranderd.";
$l_spy_changefailed = "Verandering is mislukt.";
$l_spy_cleanupplanettitle = "Het opruimen van uw planeet van de vijandelijke spionnen:";
$l_spy_notyourplanet = "Het is niet jouw planeet.";
$l_spy_cleanuptext[1] = "Snelle cleanup. Bestedingen [creds] credits en [turns] beurten.";
$l_spy_cleanuptext[2] = "Beter opruimen. Bestedingen [creds] credits en [turns] beurten.";
$l_spy_cleanuptext[3] = "De beste cleanup. Bestedingen [creds] credits en [turns] beurten.";
$l_spy_cannotcleanupplanet = "U heeft slechts [credits] credits op die planeet en [turns] beurten.";
$l_spy_cleanupbutton1 = "Start sanering van de planeet";
$l_spy_cleanupplanettitle2 = "Je draaide op uw Sensoren om vijandelijke spionnen te vinden op deze planeet.";
$l_spy_spyfoundonplanet = "Je vond een [player] &#39;s spion [spyID] op de planeet. Je vermoorde die spion.";
$l_spy_spynotfoundonplanet = "U heeft geen enkele vijandige spionnen op die planeet.";
$l_spy_notenough = "Je hebt niet genoeg credits of draait om opruimen beginnen.";

$l_spy_cleanupshiptitle = "Het opruimen van uw schip tegen vijandelijke spionnen:";
$l_spy_notinspecial = "Je moet bij een haven Inrichtingen voor het reinigen van uw schip.";
$l_spy_cleanupshiptext[1] = "Snelle cleanup. Bestedingen [creds] credits en [turns] beurten.";
$l_spy_cleanupshiptext[2] = "Beter opruimen. Bestedingen [creds] credits en [turns] beurten.";
$l_spy_cleanupshiptext[3] = "De beste cleanup. Bestedingen [creds] credits en [turns] beurten.";
$l_spy_cannotcleanupship = "U heeft slechts [credits] credits en [turns] beurten.";
$l_spy_cleanupbutton2 = "Start het opruimen van uw schip";
$l_spy_cleanupshiptitle2 = "Je draaide op uw Sensoren om vijandelijke spionnen te vinden op uw schip.";
$l_spy_spyfoundonship = "Je vond een [player] &#39;s spion [spyID] op uw schip. Je vermoorde die spion.";
$l_spy_spynotfoundonship = "U heeft geen enkele vijandige spionnen op uw schip.";

$l_spy_infodeleted = "Bericht gewist";
$l_spy_infonotyours = "Het is niet uw boodschap.";
$l_spy_noinfo = "Uw spionnen op vijandelijke schepen opsporen niets toegevoegd.";
$l_spy_infotitle = "Uw spionnen hebben ontdekt, de volgende informatie";
$l_spy_time = "Tijd";
$l_spy_type = "Type";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Er is een [player] &#39;s planeet [planet] in de sector [sector].";
$l_spy_delete = "Wissen";
$l_spy_messages = "om te zien wat je spionnen hebben ontdekt.";
$l_spy_defaulttitle1 = "Spies op vijandelijke schepen";
$l_spy_defaulttitle2 = "Spies op vijandelijke planeten";
$l_spy_defaulttitle3 = "Spies op uw planeten";
$l_spy_defaulttitle4 = "Spies op uw schip";

$l_spy_no1 = "U hebt geen spionnen op vijandelijke schepen.";
$l_spy_no2 = "U hebt geen spionnen op vijandelijke planeten.";
$l_spy_no3 = "U hebt geen spionnen op je planeten.";
$l_spy_no4 = "U hebt geen spionnen op uw schip.";
$l_spy_nospiesatall = "U hebt geen spionnen.";
$l_spy_notknown = "Onbekend";


$l_spy_trytitle = "Op de planeet deze spion zal proberen om";

$l_spy_cantsendfeds = "Sorry, maar Spies kan niet worden verzonden naar Federation of Independent planeten.";
$l_spy_cantsendteam = "U kunt geen Spies plaats op een planeet teamgenoten.";
$l_spy_messagesdeleted = "Alle verwijderde berichten";
$l_spy_deleteall = "Delete All";
$l_spy_onplanet = "Spionnen op de planeet";
$l_spy_menu = "terug te keren naar Spy-menu.";
?>
