<?php
$l_move_title = "Bewegen";
$l_move_turn = "Je hebt minimaal een beurt om te verhuizen.";
$l_move_failed = "Move failed!";
$l_rs_title = "RealSpace Move";
$l_rs_whichsector = "Welke sector wilt u bereiken via RealSpace?";
$l_rs_insector = "U bevindt zich momenteel in de sector [sector] - en er zijn sectoren die beschikbaar zijn vanaf 1 tot en met [sector_max].";
$l_rs_submit = "Compute";
$l_rs_movetime = "Met uw motoren, zal het nemen [triptime] draait om de reis te voltooien.";
$l_rs_energy = "Je zou verzamelen [energy] eenheden van energie";
$l_rs_noturns = "Je hebt niet genoeg draait naar links, en kan niet beginnen aan deze reis.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "U hebt [turns] beurten. [engage] motoren?";
$l_rs_invalid = "U kunt niet realspace op die sector van hier.";
$l_rs_ready = "U bent nu in de sector [sector]. U gebruikt [triptime] draait, en die is opgedaan [energy] energie-eenheden.";
$l_warp_invalid = "U kunt niet krom om die sector vanaf hier.";
$l_move_unknown = "Onbekend Movetype";
?>
