<?php
$l_die_title = "Self-Destruct";
$l_die_rusure = "Weet u zeker dat u uw schip te vernietigen? Hiermee verwijdert u uit het spel.";
$l_die_goodbye = "Vaarwel wrede melkweg!";
$l_die_check = "Bent u ervan overtuigd dat u wilt uzelf te verwijderen uit het spel?";
$l_die_nonono = "NEE! NEE! NEE!";
$l_die_what = "What was I thinking?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Je schip en alles wat aan boord van zijn verdampt.";
$l_die_please1 = "uitloggen";
$l_die_please2 = "Please, [logout_link]";
$l_die_exploit = "Speel niet met wat je niet begrijpt.";
?>
