<?php
///SPIES
$l_dig_title = "Hoogwaardigheidsbekleder Menu";
$l_dig = "Hoogwaardigheidsbekleders";
$l_dig_disabled = "Dignataries zijn uitgeschakeld!";
$l_dig_noturn = "Je hebt minimaal een beurt om een hoogwaardigheidsbekleder te sturen naar een planeet.";
$l_dig_notonboard = "U hebt geen hoogwaardigheidsbekleder aan boord.";
$l_dig_ownplanet = "U kunt niet een hoogwaardigheidsbekleder aan een vijandelijke planeet.";
$l_dig_unownedplanet = "U kunt niet een hoogwaardigheidsbekleder te onbeheerd planeet.";
$l_dig_planetfull = "Er zijn reeds toegestaan [max] hoogwaardigheidsbekleders op die planeet.";
$l_dig_sendtitle = "Het verzenden van een hoogwaardigheidsbekleder [digID] om de planeet: <BR> Selecteer hoogwaardigheidsbekleder&#39;s missie:";

$l_dig_codenumber = "Code";
$l_dig_job = "Baan";
$l_dig_percent = "Percentage";
$l_dig_move = "Beweging";
$l_dig_action = "Actie";
$l_dig_shipowner = "Reder";
$l_dig_shipname = "Naam van het schip";
$l_dig_shiptype = "Schip Klasse";
$l_dig_shiplocation = "Ship Lokatie";
$l_dig_planetowner = "Planet Eigenaar";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Maximum per Planet";
$l_dig_legend = "Hoogwaardigheidsbekleder Legend";
$l_dig_description = "Hoogwaardigheidsbekleder Beschrijving";
$l_dig_waiting_description = "Hoogwaardigheidsbekleder zal creëren torpedo&#39;s en strijders tijdens het wachten op een baan opdracht.";
$l_dig_changeerror = "Hoogwaardigheidsbekleder van baan te veranderen Verslag";

$l_dig_nospieshere = "U hebt geen hoogwaardigheidsbekleders op deze planeet!";
$l_dig_transferred = "hoogwaardigheidsbekleders overgedragen";
$l_dig_backonship = "De hoogwaardigheidsbekleder is nu op uw schip.";
$l_dig_dismiss = "Negeren van de hoogwaardigheidsbekleder?";
$l_dig_changebutton = "Veranderen";
$l_dig_notyourplanet = "Het is niet jouw planeet.";

$l_dig_defaulttitle1 = "Hoogwaardigheidsbekleders op vijandelijke schepen";
$l_dig_defaulttitle2 = "Hoogwaardigheidsbekleders op de planeten";
$l_dig_defaulttitle3 = "Hoogwaardigheidsbekleders op de planeten";
$l_dig_defaulttitle4 = "Hoogwaardigheidsbekleders op uw schip";

$l_dig_no1 = "U hebt geen hoogwaardigheidsbekleders op vijandelijke schepen.";
$l_dig_no2 = "U hebt geen hoogwaardigheidsbekleders op de planeten.";
$l_dig_no3 = "U hebt geen hoogwaardigheidsbekleders op de planeten.";
$l_dig_no4 = "U hebt geen hoogwaardigheidsbekleders op uw schip.";
$l_dig_nodignitaryatall = "U hebt geen hoogwaardigheidsbekleders.";
$l_dig_notknown = "Onbekend";
$l_dig_dismiss = "Negeren";
$l_dig_dismiss2 = "Hoogwaardigheidsbekleders afgewezen.";
$l_dig_menu = "terug te keren naar hoogwaardigheidsbekleder Menu.";

?>
