<?php
$l_profile_title = "Profiel Registratie";
$l_profile_notenabled = "Profielen zijn niet ingeschakeld op deze server.";
$l_profile_registered = "Deze speler is nu geregistreerd bij de Meester Profiel Server.";
$l_profile_nomatch = "Kan niet overeen met een profiel op de Meester Profiel Server met de naam en het wachtwoord voor de server ingevoerd.";
$l_profile_tryagain = "Voor het invoeren van uw speler profielnaam en wachtwoord voor de server opnieuw klik";
$l_profile_name = "Profiel Naam speler";
$l_profile_password = "Profiel Server Password";
$l_profile_bannedserver = "Deze server is niet toegestaan om het profiel van informatie aan de Meester Profiel Server.";
$l_profile_bannedplayer = "Je bent verbannen uit de Master Profiel Server en kan geen spelers te registreren.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Deze server <u><b>vereist dat</b></u> iedere nieuwe speler te zijn een geregistreerde profiel. Je zal niet worden toegestaan om een nieuwe speler, tenzij je wel een geregistreerde profiel.";
$l_profile_updated = "Uw sjabloon, de shoutbox en nieuws doorzoeken algemene instellingen zijn bijgewerkt op het profiel Master Server. Deze instellingen worden automatisch gebruikt wanneer u zich registreert uw profiel op elk spel.";

?>
