<?php
///SPIES
$l_spy_title = "Menu espion";
$l_spy = "Espions";
$l_spy_disabled = "Les espions sot désactivés!";
$l_spy_noturn = "Vous avez besoin d'au moin un tours pour envoyer un espion sur une planète.";
$l_spy_notonboard = "Vous n'avez pas d'espions a bord.";
$l_spy_ownplanet = "Vous ne pouvez pas envoyer un espion sur votre planète.";
$l_spy_unownedplanet = "Vous ne pouvez pas envoyer d'espion sur une planète n'apartenant a personne.";
$l_spy_planetfull = "Il y a déja [max] espions sur cette planète.";
$l_spy_sendtitle = "Envoyer un espion [spyID] sur la planète:<BR>Choisisez la mission de l'espion:";
$l_spy_type1 = " L'espion agit seulement sur cette planète.";
$l_spy_type2 = " L'espion essaye d'infiltrer un vaissau lors d'un transfert planétaire.";
$l_spy_type3 = " L'espion essaye d'infiltrer un vaissau lors d'un transfert planétaire, et il infiltre une autre planète.";
$l_spy_sendbutton = "envoyer sur la planète";
$l_spy_sendsuccessful = "Votre espion a infiltrer la planète et attend le bon moment pour agir.";
$l_spy_sendfailed = "Les détecteurs de la planète on détecter votre espion, parce que votre camouflage ne l'as pas couvert. Votre espion est mort.";
$l_spy_noturn2 = "Vous avez besoin d'au moin un tour pour rapeler un espion.";
$l_spy_confirm = "êtes vous sur de vouloir rapeler l'espion [spyID]?";
$l_spy_cleanupplanet = "Pour vous débarasez des espions enemis sur cette planète.";
$l_spy_cleanupship = "Si vous voulez vous débaraser des espions enemis sur votre vaissau, cliquez";
$l_spy_yourspies = "Votre espion sur cette planète";
$l_spy_sendnew = "Envoyer un nouveau espion";

$l_spy_codenumber = "Code";
$l_spy_job = "Travail";
$l_spy_percent = "%";
$l_spy_move = "Mouvement";
$l_spy_action = "Action";
$l_spy_shipowner = "Propriétaire du vaissau";
$l_spy_shipname = "Nom du vaissau";
$l_spy_shiptype = "classe du vaissau";
$l_spy_shiplocation = "Emplacement du vaissau";
$l_spy_planetowner = "Propriétaire de la planète";
$l_spy_planetname = "Planète";
$l_spy_sector = "Secteur";

$l_spy_moves['none'] = "Ne pas bouger";
$l_spy_moves['toship'] = "Vers le vaissau";
$l_spy_moves['toplanet'] = "Vers la planète";

$l_spy_comeback = "Rapeller";
$l_spy_nospieshere = "Il n'y a pas d'espions vous appartenant sur ceyye planète";
$l_spy_transferred = "Espion transférer";
$l_spy_backonship = "L'espion est maintenant sur votre vaissau.";
$l_spy_backfailed = "Rapel rater.";
$l_spy_changetitle = "changer les propliéter de l'espion [spyID]:";
$l_spy_occupied = "Votre espion [spyID] est employer à [job], avec le pourcentage [percent].";
$l_spy_dismiss = "Renvoyer l'espion?";
$l_spy_changebutton = "Changer";
$l_spy_changejob = "Changement d&#39;emploi ou mouvement";
$l_spy_linkback = "Pour aller vers le menu espion.";
$l_spy_changed1 = "Mouvement changer.";
$l_spy_changed2 = "Espion renvoyer et ses déplacement ont changer.";
$l_spy_changefailed = "Changement rater.";
$l_spy_cleanupplanettitle = "Détecter les espion enemis sur votre planète:";
$l_spy_notyourplanet = "Ce n'est pas votre planète.";
$l_spy_cleanuptext[1] = "Détection rapide. Coût [creds] crédits et [turns] tours.";
$l_spy_cleanuptext[2] = "Détection normale. Coût [creds] crédits et [turns] tours.";
$l_spy_cleanuptext[3] = "Détection aprofondie. Coût [creds] crédits et [turns] tours.";
$l_spy_cannotcleanupplanet = "Vous avez seulement [credits] crédits sur cette planète et [turns] tours.";
$l_spy_cleanupbutton1 = "Démarer le netoyage d'espion enemis sur votre planète";
$l_spy_cleanupplanettitle2 = "Vous utiliser vos détecteur pour trouver les espion enemis sur votre planète.";
$l_spy_spyfoundonplanet = "Vous avez trouver un espion [spyID] à [player] sur votre vaissau. Vous l'avez tuer.";
$l_spy_spynotfoundonplanet = "Vous n'avez pas trouver d'espions enemis sur votre planète.";
$l_spy_notenough = "Vous n'avez pas asser de crédit et de tours pour démarer le netoyage.";

$l_spy_cleanupshiptitle = "Détection d'espions enemis de votre vaissau:";
$l_spy_notinspecial = "You need to be at a Devices port to clean up your ship."; //TODO: Translate it, please
$l_spy_cleanupshiptext[1] = "Détection rapide. Coût [creds] crédits et [turns] tours.";
$l_spy_cleanupshiptext[2] = "Détection normale. Coût [creds] crédits et [turns] tours.";
$l_spy_cleanupshiptext[3] = "Détection aprofondie. Coût [creds] crédits et [turns] tours.";
$l_spy_cannotcleanupship = "Vous avez seulement [credits] crédits et [turns] tours.";
$l_spy_cleanupbutton2 = "Démarer le netoyage d'espion enemis";
$l_spy_cleanupshiptitle2 = "Vous utilisez vos détecteur pour trouver des espions enemis sur votre vaissau.";
$l_spy_spyfoundonship = "Vous avez trouver un espion [spyID] à [player] sur votre vaissau. Vous l'avez tuer.";
$l_spy_spynotfoundonship = "Vous n'avez pas trouver d'espions enemis sur votre vaissau.";

$l_spy_infodeleted = "Message effacé";
$l_spy_infonotyours = "Ce n'est pas votre message.";
$l_spy_noinfo = "Vos espions sur les vaissaux enemis n'ont encore rien détecter.";
$l_spy_infotitle = "Vos espions ont détecter les information suivantes";
$l_spy_time = "Date";
$l_spy_type = "Type";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planète";
$l_spy_datatype[2] = "Message";
$l_spy_datatext[1] = "Il y a une planète a [player] nomée [planet] dans le secteur [sector].";
$l_spy_datatext[2] = "Le joueur [sender] a envoyer a l'aliance [receiver] un message:<BR> [letter].";
$l_spy_datatext[3] = "Le joueur [sender] a envoyer au joueur [receiver] un message:<BR> [letter].";
$l_spy_delete = "Effacé";
$l_spy_messages = "pour voir ce que vos espions ont détecter.";
$l_spy_defaulttitle1 = "Espions sur vaissaux enemis";
$l_spy_defaulttitle2 = "Espions sur planètes enemies";
$l_spy_defaulttitle3 = "Espions sur vos planètes";
$l_spy_defaulttitle4 = "Espions sur votre vaissau";

$l_spy_no1 = "Vous n'avez pas d'espions sur les vaissaux enemis.";
$l_spy_no2 = "Vous n'avez pas d'espions sur les planètes enemies.";
$l_spy_no3 = "Vous n'avez pas d'espions sur vos planètes.";
$l_spy_no4 = "Vous n'avez pas d'espions sur votre vaissau.";
$l_spy_nospiesatall = "Vous n'avez pas d'espions.";
$l_spy_notknown = "Inconnu";

//TODO: Translate it, please
$l_spy_trytitle = "Sur la planète cet espion tentera de";

$l_spy_cantsendfeds = "Désolé, Spies ne peut être envoyé à la Fédération ou des planètes indépendants.";
$l_spy_cantsendteam = "Vous ne pouvez pas placer Spies sur la planète coéquipiers A.";
$l_spy_messagesdeleted = "Tous les messages supprimés";
$l_spy_deleteall = "Supprimer tout";
$l_spy_onplanet = "Espions sur la planète";
$l_spy_menu = "pour revenir à Spy Menu.";
?>
