<?php
$l_zi_title		 = "Informations sur la zone";
$l_zi_nexist		 = "Cette section d'espace n'existe pas!";
$l_zi_feds		 = "Fédération";
$l_zi_traders = "Space Alliance";
$l_zi_nobody		 = "Personne";
$l_zi_war		 = "Espace contesté";
$l_zi_allow		 = "Permis";
$l_zi_notallow		 = "Non permis";
$l_zi_limit		 = "Limité aux allié";
$l_zi_ul		 = "Illimité";
$l_zi_control		 = "Vous êtes en contôle de cette zone";
$l_zi_tochange		 = "pour changer ses lois.";
$l_zi_owner		 = "Responsable de la zone";
$l_zi_maxhull		 = "Coque maximum permise";
?>
