<?php
$l_sn_title = "Secteur Notes";
$l_sn_pntitle = "Secteurs des notes personnelles";
$l_sn_tntitle = "Secteurs avec les notes de l&#39;équipe";
$l_sn_psntitle = "Secteur Notes personnelles";
$l_sn_tsntitle = "Équipe sectorielle Notes";
$l_sn_editnote = "Modifier Secteur Note:";
$l_sn_deleteedit = "Supprimer ou Modifier:";
$l_sn_addnote = "Ajouter Secteur Note:";
$l_sn_list = "Remarques Liste des secteurs";
$l_sn_listts = "Veuillez indiquer les secteurs avec les notes de l&#39;équipe";
$l_sn_addteam = "Ajouter Team";
$l_sn_deleteteam = "Supprimer Team";
$l_sn_delete = "Supprimer";
$l_sn_saveteam = "Sauvegarder Team";
$l_sn_deletepersonal = "Supprimer personnels";
$l_sn_addpersonal = "Ajouter personnels";
$l_sn_savepersonal = "Sauvegarder personnels";
$l_sn_editpersonal = "Edit Personal";
$l_sn_editteam = "Modifier l&#39;équipe";

$l_sn_hdsector = "Secteur";
$l_sn_hdtype = "Type";
$l_sn_hdowner = "Propriétaire / Team";
$l_sn_hdplanets = "Planètes";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mines";
$l_sn_hdscanfrom = "Numériser à partir de";
$l_sn_hddetail = "Détails";
$l_sn_hddate = "Date / Heure";
$l_sn_hddelete = "Supprimer";
$l_sn_hdteam = "Équipe";
$l_sn_view = "Affichage";
$l_sn_no = "Non";
$l_sn_yes = "Oui";
$l_sn_nonotes = "Aucun secteur notes trouvées";

?>
