<?php
$l_scan_title		 = "Sonder un vaisseau";
$l_scan_turn		 = "Vous avez besoin d'au moins un tour pour sonder un autre vaisseau.";
$l_scan_ron		 = "Résultats de la sonde sur";
$l_scan_capt		 = "Capitaine:";
$l_scan_arma		 = "Armement:";
$l_scan_carry		 = "Cargaison:";
$l_scan_bounty           = "Ce vaissau a une mise à prix totale de [amount] credits.";
$l_scan_fedbounty        = "Ce vaissau a une mise à prix de la Fédération.";
$l_by_nofedbounty        = "Si vous attaquez ce joueurs, la Fédération ne placera <B>PAS</B> une mise à prix sur vous.";
?>
