<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Bienvenue dans le casino, nous vous offrons actuellement ce qui suit jeux et installations";
$l_casino_option = "&quot;Les Chambres";
$l_casino_detail = "&quot;Description";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "»Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;First Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "«L&#39;assurance";
$l_doubledown = "Double Down";
$l_lobby = "«Lobby";
$l_split = "Diviser";
$l_credits = "Crédits";
$l_yourbet = "«Votre pari";
$l_nobet = "«Votre pari a dépassé votre limite de crédit, s&#39;il vous plaît mise à nouveau.";
$l_dealerwins = "Dealer gagne!";
$l_dealerbust = "Marchand Bust!";
$l_dealerloses = "Défaites Dealer!";
$l_dealerblackjack = "Marchand Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Le joueur gagne!";
$l_playerbust = "&quot;Joueur Bustes!";
$l_playerloses = "&quot;Le joueur perd!";
$l_playerblackjack = "&quot;Joueur de blackjack!";
$l_place_bet = "«Placez votre pari";
?>
