<?php
$l_artifact_title = "Récupérer Artefact";
$l_artifact_list_title = "La liste des artefacts Acquise";
$l_artifact_noscan = "Vos scanners n&#39;a pas pu trouver l&#39;artefact.";
$l_artifact_noturn = "Vous n&#39;avez pas assez de tours pour ramasser cet objet.";
$l_artifact_classname = "Artifact Nom";
$l_artifact_description = "Artifact Description";
$l_artifact_imagename = "Artefact d&#39;image";
$l_artifact_incomplete = "Artifact Pieces";
$l_artifact_process = "Utilisez le Artifact Terminé";

?>
