<?php
$l_att_title		 = "Attaque de vaisseau";
$l_att_notarg		 = "La cible n'est pas dans ce secteur.";
$l_att_noturn		 = "Vous avez besoin d'au moins un tour pour pouvoir attaquer.";
$l_att_noatt		 = "Il n'est pas permis d'attaquer quelqu'un dans ce secteur.";
$l_att_flee		 = "Le vaisseau ennemi vous échape!";
$l_att_ewd		 = "Le vaisseau est entré d'urgence dans l'hyper-espace quand vous l'avez attaqué!";
$l_att_att		 = "Attaque ";
$l_att_beams = "Faisceau d&#39;échange";
$l_att_torps = "Torpedo Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost		 = "a perdu";
$l_att_ylost		 = "Vous avez perdu";
$l_att_sdown		 = " -> Boucliers tombent!";
$l_att_ydown		 = "Vos boucliers sont tombés!";
$l_att_shits		 = " -> Boucliers touchés de";
$l_att_yhits		 = "Vos boucliers sont touchés de";
$l_att_dmg		 = "points de dommage";
$l_att_sarm		 = " -> Armure pénétrée";
$l_att_yarm		 = "Votre armure est pénétrée!";
$l_att_ashit		 = " -> Armure touchée de";
$l_att_ayhit		 = "Votre armure est touchée de";

$l_att_efhit = "&#39;s combattants sont détruits.";
$l_att_yfhit = "de vos combattants sont détruits.";
$l_att_ethit = "&#39;s torpilles sont détruits.";
$l_att_ythit = "de vos torpilles sont détruits.";
$l_att_of = "de";
$l_att_lostt = "perdu toutes les torpilles.";
$l_att_ylostt = "Vous avez perdu toutes les torpilles.";

$l_att_lostf		 = "a perdu tous ses intercepteurs.";
$l_att_ylostf		 = "Vous avez perdu tous vos intercepteurs.";
$l_att_sdest		 = " -> Vaisseau détruit.";
$l_att_espod		 = "Un module de secours a été lancé!";
$l_att_ysalv		 = "Vous récupérez et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits.<BR>Vous gagnez [rating_change] points.";
$l_att_andused		 = "et utilisé";
$l_att_stilship		 = "Vous n'avez pas détruit le vaisseau de [name].";
$l_att_atyou = "attaqués vous";
$l_att_and		 = "et";
$l_att_yshiplost	 = "Votre vaisseau a été détruit!";
$l_att_salv		 = "[name] a récupéré et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits";

$l_att_tnobeams = "coutures d&#39;être hors de l&#39;énergie de faisceau.";
$l_att_tnobeamsf = "coutures d&#39;être hors de l&#39;énergie du faisceau et ne peuvent pas attaquer vos combattants.";
$l_att_tnobeamst = "coutures d&#39;être hors de l&#39;énergie du faisceau et ne peuvent pas attaquer vos torpilles.";
$l_att_tfnoattack = "n&#39;envoie pas de tous les combattants d&#39;attaquer votre vaisseau.";
$l_att_tnotorps = "semble être hors de torpilles.";

$l_att_anobeams = "Vous avez épuisé vos navires énergie du faisceau.";
$l_att_anobeamsf = "Vous avez épuisé vos navires de l&#39;énergie du faisceau et ne peuvent pas attaquer les combattants ennemis.";
$l_att_anobeamst = "Vous avez épuisé vos navires énergie du faisceau et ne peuvent pas attaquer l&#39;ennemi torpilles.";
$l_att_anofighters = "Votre navire a épuisé tous les combattants availible.";
$l_att_anotorps = "Vous avez épuisé vos torpilles availible.";
$l_att_loosepod = "Heureusement, vous avez une capsule de sauvetage!";
$l_att_imtitle = "Ship Under Attack";
$l_att_imbody = "attaque votre bateau.";

$l_att_luckybeams = "Enemy poutres surcharge infligeant";
$l_att_luckyfighters = "Combattants ennemis faire une attaque surprise d&#39;allégement et de la cause";
$l_att_luckytorps = "Torpilles induire un effet de dégâts en cascade entraînant Enemy";
$l_att_luckytimes = "fois le dommage normal!";
?>
