<?php
$l_mail_title			="Envoyer le mot de passe";
$l_mail_noplayer		="Ce joueur n'existe pas! - Créer un nouveau joueur <a href=new_player.php>ici</a>.";
$l_mail_sent			="Le mot de passe a été envoyé à";
$l_mail_topic			="Mot de passe pour $game_name";
$l_mail_message			="Salutations,\n\nQuelqu'un avec l'ip $ip a demandé que votre mot de passe pour Blacknova Traders soit envoyé à cette adresse.\n\nVotre mot de passe est: [pass]\n\nMerci\n\nL'équipe de Blacknova Traders.";
$l_mail_failed = "Mot de passe omis de communiquer à";
$l_new_login = "pour aller à l&#39;écran de connexion.";
?>
