<?php
$l_news_title		 = "Nouvelles de l'Univers";
$l_news_info		 = "FNN est la meilleur source<br>de nouvelles et informations dans l'univers.<br>Une équipe qui travaille 24 heures, sept jours par <br>semaines vous apporte toutes les manchettes! Nos <br>bureaux sont disséminés à travers toute la galaxie!";
$l_news_for		 = "Manchettes pour";
$l_news_prev		 = "jour précédent";
$l_news_next		 = "jour suivant";
$l_news_none		 = "Désolé, aucune nouvelles ajourd'hui.";
$l_news_flash		 = "Manchette!";
$l_news_end      = "Fin des news";
$l_news_bestviewed = "Best viewed in Opera, Safari et IE";
$l_news_fedannouncements = "Fédération Annonces";
$l_news_planetarynews = "Planetary Nouvelles";
$l_news_planetshipnews = "Planetary and Ship Nouvelles";
$l_news_afteractionnews = "Après l&#39;action de combat Nouvelles";

?>
