<?php
$l_die_title		 = "Auto-destruction";
$l_die_rusure		 = "Êtes-vous certain que vous voulez détruire votre vaisseau? Cette action vous retirera du jeu.";
$l_die_goodbye		 = "Adieu, cruelle galaxie!";
$l_die_check		 = "Êtes-vous vraiment certain que vous voulez vous retirer du jeu?";
$l_die_nonono		 = "NON! NON! NON!";
$l_die_what		 = "À quoi je pensais?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor		 = "Votre vaisseau et tous ceux à bord ont été vaporisés.";
$l_die_please		 = "Quittez>";
$l_die_please2           = "S'il vous plaît, [logout_link]";
$l_die_exploit		 = "Ne jouez pas avec ce que vous ne comprenez pas.";
$l_die_please1 = "logout";
?>
