<?php
$l_login_sclosed		= "Le serveur est fermé";
$l_login_closed_message		="Le serveur est fermé jusqu'à nouvel ordre.";
$l_login_title2			="Phase deux de la connection";
$l_login_banned			="<b>Vous avez été bannis de ce serveur par l'administrateur. La prochaine fois, conduisez-vous mieux</b>";
$l_login_died			="Votre vaisseau a été détruit, mais votre module de secours vous a sauvé vous ainsi que votre équipage.  Cliquez <A HREF=main.php>ici</A> pour recommencer avec un nouveau vaisseau.";
$l_login_newbie			="À cause du degré de ce crime contre vous, la Fédération a gracieusement accepté de vous cloner. Malheureusement, même en cet âge, les nouveaux clones ne peuvent avoir de propriété, sauf les besoins essentiels. Vous aurez un vaisseau de base et quelque crédits pour commencer une nouvelle vie. Espérons qu'elle sera meilleure que l'ancienne.";
$l_login_newlife		="Cliquez <A HREF=main.php>ici</A> pour continuer vers une nouvelle vie.";
$l_login_looser			="Vous n'aviez pas de module de secours, donc vous avez péri.<BR><BR> Meilleure chance la prochaine fois...";
$l_login_4gotpw1		= "Le mot de passe que vous avez entré est incorrect.<BR><BR>  Si vous avez oublié votre mot de passe, ";
$l_login_4gotpw2		= "pour le recevoir par e-mail.<BR><BR>  Sinon,";
$l_login_4gotpw3		= "pour essayer encore une fois.  La tentative a été enregistrée, de l'ip";
$l_login_noone			= "Ce joueur n'existe pas! - Créer un nouveau joueur <A HREF=new_player.php>ici</A>.";
$l_login_diedincident = "Vous êtes morts dans un incident horrible.";
$l_login_blackbox = "Blackbox est l&#39;information qui a été récupérée de l&#39;épave habituellement votre fichier.";
$l_new_login = "pour aller à l&#39;écran de connexion.";
$l_login_playerlimit = "Le serveur a atteint le nombre maximum de joueurs qu&#39;il soutient. S&#39;il vous plaît essayez de vous connecter à un moment ultérieur.";
?>
