<?php
$l_lrs_title		 = "Sonde longue distance";
$l_lrs_nofull		 = "Vos sondeurs ne possèdent aucune fonction longue distance.";
$l_lrs_noturns		 = "Vous avez besoin d'au moins $fullscan_cost tour(s) pour performer un sondage complet.";
$l_lrs_used		 = "Vous avez utilisé";
$l_lrs_turns		 = "tour(s)";
$l_lrs_left		 = "restant";
$l_lrs_reach		 = "Les locations suivantes peuvent être atteinte à partir du secteur [sector]:";
$l_lrs_links		 = "Liens";
$l_lrs_ships		 = "Vaisseaux";
$l_lrs_click		 = "Cliquez sur un des liens pour vous déplacer vers ce secteur.";
$l_lrs_cantscan		 = "Vous ne pouvez sonder ce secteur à partir du secteur courant!";
$l_lrs_zero		 = "Le secteur 1 montre beaucoup trop d'activité pour isoler les vaisseaux!";
$l_lrs_moveto		 = "pour vous déplacer vers le secteur";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Afficher le journal";
$l_lrs_fedjammed = "Fédération est le brouillage tous les capteurs scans.";
$l_lrs_imtitle             = "Sector Under Attack";
$l_lrs_imbody             = "is using a Sector Nova on";
$l_lrs_sectormissile_question = "au feu des missiles secteur.";
$l_log_months = array('jaanuar','veebruar','m&auml;rts','aprill','mai','juuni','juuli','august','september','oktoober','november','detsember');
$l_log_months_short = array('jaan','veebr','m&auml;rts','apr','mai','juuni','juuli','aug','sept','okt','nov','dets');
?>
