<?php
$l_gns_title		 = "Torpille Genesis";
$l_gns_turn		 = "Vous avez besoin d'au moins un tour pour utiliser une torpille genesis.";
$l_gns_onplanet		 = "Vous ne pouvez utiliser une torpille genesis à la surface d'une planète.";
$l_gns_full		 = "Ce système solaire est déjà plein.";
$l_gns_planetex = "Il existe déjà une planète dans ce secteur.";
$l_gns_nogenesis	 = "Vous ne possédez aucune torpille genesis.";
$l_gns_forbid		 = "La création d'une planète dans ce secteur n'est pas permise.";
$l_gns_bforbid		 = "Les bases dans se secteur interferent avec la torpille genesis. La création d'une planète est impossible.";
$l_gns_pcreate		 = "Une nouvelle planète est créée.";
$l_sgns_title = "Genèse des secteurs d&#39;utilisation de périphériques";
$l_sgns_pcreate = "Secteur [name] créé.";
$l_sgns_nogenesis = "Vous n&#39;avez pas de périphérique genèse secteur.";
$l_sgns_forbid = "Création d&#39;un trou de ver genèse secteur dans ce secteur ne sont pas autorisés.";
$l_sgns_forbid1 = "Création d&#39;une genèse secteur wormhole un secteur Fédération n&#39;est pas permise.";
$l_sgcreate = "Créer un nouveau Secteur de la Genèse Secteur";
$l_sgcreatens = "Créer un nouveau Secteur de la Genèse Lien vers l&#39;espace connu";
$l_sgns_forbid2 = "Plus de [limit] liens dans les secteurs SG ne sont pas autorisés.";
$l_sgns_forbid3 = "Impossible de créer Secteur Genesis lien chaîne du secteur actuels - ce qui dépasserait le maximum de [limit] par secteur.";
$l_sgns_nocredits = "Vous n&#39;avez pas assez de crédits pour créer un nouveau secteur.";
$l_sgns_shipcredits = "Crédits sur le bateau:";
$l_sgns_createcost = "Coût de créer de nouveaux Secteur:";
$l_sgns_complete = "Plein Space Link complet";
$l_sgns_sectorname = "Entrez Secteur commercial:";
$l_gns_max_unbased_planets = "La Fédération ne permettra pas la création de planètes plus jusqu&#39;à ce que vous avez moins de [max_unbased_planets] unbased planètes.";


?>
