<?php
$l_move_title 		 = "Déplacement";
$l_move_turn		 = "Vous avez besoin d'au moins un tour pour vous déplacer.";
$l_move_failed		 = "Le déplacement a échoué!";
$l_rs_title 		= "Déplacement en espace réel";
$l_rs_whichsector       = "Quel secteur aimeriez-vous atteindre à travers l'espace réel?";
$l_rs_insector		= "Vous êtes présentement dans le secteur [sector] - et les secteurs disponibles vont de 1 à [sector_max].";
$l_rs_submit		= "Calculer";
$l_rs_movetime		= "Avec vos moteurs, vous prendrez [triptime] tours pour compléter le voyage.";
$l_rs_energy		= "Vous collecterez [energy] unités d'énergie";
$l_rs_noturns		= "Vous n'avez pas assez de tours disponibles, donc vous ne pouvez faire ce voyage.";
$l_rs_engage_link	= "activer";
$l_rs_engage		= "Vous avez [turns] tours. [engage] les moteurs?";
$l_rs_invalid = "Vous ne pouvez pas REALSPACE à ce secteur d&#39;ici.";
$l_rs_ready 		= "Vous êtes maintenant dans le sector [sector]. Vous avez utilisé [triptime] tours et collecté [energy] unités d'énergie.";
$l_warp_invalid = "Vous ne pouvez pas de chaîne à ce secteur d&#39;ici.";
$l_move_unknown = "Inconnu Movetype";
?>
