<?php
$l_footer_one_player_on	= "Il y a un joueur en ligne.";
$l_footer_no_players_on = "There are no players online."; //Translate it, please
$l_footer_players_on_1	= "Il y a";
$l_footer_players_on_2 = "Joueurs en ligne:";
$l_footer_until_update	= "secondes avant la prochaine mise à jour.";

$l_footer_news = "FNN Nouvelles locales";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = "l&#39;aide pour cette page.";
$l_footer_click = "Cliquez sur";

$l_footer_open_slots = "Maximum en ligne:";
$l_footer_onlinereset = "Player Online temps de réinitialisation";
$l_footer_onlinecountdown = "Player Online compte à rebours:";
?>
