<?php
$l_sf_attacking = "Les défenses de secteur vous attaquent!<BR>";
$l_sf_destfight = "Vos rayons détruisent [lost] intercepteurs<BR>";
$l_sf_destfightb = "Vos rayons détruisent [lost] intercepteurs<BR>";
$l_sf_torphit = "Les torpilles touchent:";
$l_sf_destfightt = "Vos torpilles ont détruit [lost] intercepteurs<BR>";
$l_sf_fighthit = "Les intercepteurs attaquent:";
$l_sf_destfightall = "Vous détruisez tous les intercepteurs.<BR>";
$l_sf_destfightt2 = "Vous détruisez [lost] intercepteurs.<BR>";
$l_sf_lostfight = "Vous perdez tous vos intercepteurs.<BR>";
$l_sf_lostfight2 = "Vous perdez [lost] intercepteurs.<BR>";
$l_sf_armorbreach = "Votre armure a été traversée!<BR>";
$l_sf_armorbreach2 = "Votre armure est touchée pour [lost] points de dommage.<BR>";
$l_sf_sendlog = "[player] a détruit [lost] intercepteurs en défense dans le secteur [sector].";
$l_sf_lreport = "Vous avez perdu [armor] points d'armure, [fighters] intercepteurs et avez utilisé [torps] torpilles.<BR><BR>";
$l_sf_shipdestroyed = "Votre vaisseau a été détruit!<BR><BR>";
$l_sf_sendlog2 = "Les intercepteurs en défense dans le secteur [sector] ont détruit [player].";
$l_sf_escape = "Heureusement vous aviez un module de secours!<BR><BR>";

$l_sf_fnoattack = "n&#39;envoie pas de tous les combattants pour attaquer vos combattants.";
$l_sf_fnoattackt = "n&#39;envoie pas de tous les combattants pour attaquer vos torpilles.";
$l_sf_fnoattacka = "n&#39;envoie pas de tous les combattants d&#39;attaquer votre armure.";
$l_sf_flaunchmalf1 = "Votre avion de chasse système de lancement a mal fonctionné.";
$l_sf_flaunchmalf2 = "Vous avez seulement été capables de lancer";
$l_sf_flaunchmalf3 = "pour cent de vos combattants.";
$l_sf_fightertorpexg = "Fighter à Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Ship Torpedo au secteur Fighter Exchange";
$l_sf_fighterarmorexg = "Secteur de chasse à bord des navires Armor Exchange";
$l_sf_tlaunchmalf1 = "Votre système de lancement de torpilles a mal fonctionné.";
$l_sf_tlaunchmalf2 = "Vous avez seulement été capables de lancer";
$l_sf_tlaunchmalf3 = "pour cent de vos torpilles.";
$l_sf_bountysd = "Vous avez attaqué un secteur contenant une planète qui vous donnerait une prime si vous avez attaqué la planète. La Fédération a activé une auto-destruction automatique de tous vos combattants et des torpilles. Ne pas attaquer les défenses du secteur dans ce secteur à nouveau. Vous avez été averti!";
?>
