<?php
$l_ze_title		 = "Éditer une zone";
$l_ze_notowner		 = "Cette zone ne vous appartient pas alors vous ne pouvez la modifier.";
$l_ze_name		 = "Nom de la zone";
$l_ze_allow		 = "Permettre";
$l_ze_attacks		 = "Permettre l'attaque de vaisseaux";
$l_ze_genesis		 = "Permettre la création de planètes";
$l_ze_return		 = "pour retourner à la page d'information sur la zone.";
$l_ze_saved		 = "Vos modifications ont été sauvegardées.";
$l_ze_namematch = "ERREUR: Le Nom de la zone que vous avez fourni est semblable ou correspond à un nom existant Zone.";
?>
