<?php
$l_opt_title = "Options";
$l_opt_chpass = "Changer le mot de passe";
$l_opt_curpass = "Mot de passe actuel:";
$l_opt_newpass = "Nouveau mot de passe:";
$l_opt_newpagain = "Nouveau mot de passe (encore):";
$l_opt_userint = "Interface utilisateur";
$l_opt_usenew = "Nouvelle interface?";
$l_opt_lang = "Langue";
$l_opt_template = "Template";
$l_opt_select = "Choisissez une:";
$l_opt_enabled = "Activé";
$l_opt_save = "Sauvegarder";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "NomExpédition:";
$l_opt_mapwidth = "Locales et Galaxy Carte Largeur:";
$l_opt_profiletitle = "Profil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Enregistré auprès du mode serveur";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Lorsque vous vous inscrivez votre lecteur sur un autre serveur le modèle, shoutbox et les paramètres de nouvelles ci-dessus sera utilisé sur le serveur.";
$l_opt_showshoutbox = "Voir la Shoutbox:";
$l_opt_shownewscrawl = "Afficher Nouvelles Crawl:";
$l_opt_playername = "Nom du lecteur:";
$l_opt_playernamecost = "Federation Nom Changement de frais: [amount] crédits";
?>
