<?php
///SPIES
$l_dig_title = "Dignitaire Menu";
$l_dig = "Dignitaires";
$l_dig_disabled = "Dignitaires sont désactivées!";
$l_dig_noturn = "Vous devez avoir au moins un tour pour envoyer un dignitaire à une planète.";
$l_dig_notonboard = "Vous n&#39;avez pas tout dignitaire à bord.";
$l_dig_ownplanet = "Vous ne pouvez pas envoyer un dignitaire à une planète ennemie.";
$l_dig_unownedplanet = "Vous ne pouvez pas envoyer un dignitaire à la planète unowned.";
$l_dig_planetfull = "Il ya déjà admis [max] dignitaires sur cette planète.";
$l_dig_sendtitle = "Envoi d&#39;un Digid [digID] à la planète: <BR> Dignitaire Select mission:";

$l_dig_codenumber = "Code";
$l_dig_job = "Travail";
$l_dig_percent = "Pour cent";
$l_dig_move = "Mouvement";
$l_dig_action = "Action";
$l_dig_shipowner = "Propriétaire du navire";
$l_dig_shipname = "Nom du navire";
$l_dig_shiptype = "Navire de la classe";
$l_dig_shiplocation = "Ship";
$l_dig_planetowner = "Planet Propriétaire";
$l_dig_planetname = "Planet";
$l_dig_sector = "Secteur";

$l_dig_waiting = "En attente d&#39;un emploi";
$l_dig_max = "Maximum par Planet";
$l_dig_legend = "Dignitaire Légende";
$l_dig_description = "Dignitaire Description";
$l_dig_waiting_description = "Dignitaire créera des torpilles et des combattants en attente d&#39;une attribution des postes.";
$l_dig_changeerror = "Dignitaire Job Change Report";

$l_dig_nospieshere = "Vous n&#39;avez pas d&#39;dignitaires sur cette planète!";
$l_dig_transferred = "dignitaires transférés";
$l_dig_backonship = "Le dignitaire est maintenant sur votre bateau.";
$l_dig_dismiss = "Rejeter le dignitaire?";
$l_dig_changebutton = "Changer";
$l_dig_notyourplanet = "Ce n&#39;est pas votre planète.";

$l_dig_defaulttitle1 = "Dignitaires sur les navires ennemis";
$l_dig_defaulttitle2 = "Dignitaires sur vos planètes";
$l_dig_defaulttitle3 = "Dignitaires sur vos planètes";
$l_dig_defaulttitle4 = "Dignitaires sur votre bateau";

$l_dig_no1 = "Vous n&#39;avez pas d&#39;dignitaires sur les navires ennemis.";
$l_dig_no2 = "Vous n&#39;avez pas d&#39;dignitaires sur vos planètes.";
$l_dig_no3 = "Vous n&#39;avez pas d&#39;dignitaires sur vos planètes.";
$l_dig_no4 = "Vous n&#39;avez pas d&#39;dignitaires sur votre bateau.";
$l_dig_nodignitaryatall = "Vous n&#39;avez pas d&#39;dignitaires.";
$l_dig_notknown = "Inconnu";
$l_dig_dismiss = "Rejeter";
$l_dig_dismiss2 = "Dignitaires rejeté.";
$l_dig_menu = "pour revenir à Dignitaire Menu.";

?>
