<?php
$l_chf_youretreatback   = "Vous battez en retraite jusqu'à votre position précédente";
$l_chf_movefailed       = "Le déplacement a échoué.";
$l_chf_thefightersdetectyou     = "Les intercepteurs vous détectent!";
$l_chf_therearetotalfightersindest      = "Il y a [chf_total_sector_fighters] intercepteurs dans votre secteur de destination.";
$l_chf_youcanretreat    = "<B>Battre en retraite</B> - Ceci vous coûtera un tour.";
$l_chf_inputfight       = "<B>Combattre</B> - Vous devez détruire tous les intercepteurs pour entrer dans le secteur.";
$l_chf_inputcloak       = "<B>Camouflage</B> - Utiliser votre camouflage pour essayer de passer les intercepteurs.";
$l_chf_go       = "Aller";
$l_chf_inputrun = "<B>Attack and Run</b> - Vous faites une répétition d&#39;allégement attaque et retraite. Mais vous pouvez prendre quelques dommages pendant la retraite.";
?>
