<?php
$l_beacon_title		 = "Déployer une bouée spatiale";
$l_beacon_notpermitted	 = "Les bouées spatiales ne sont pas permises dans ce secteur.";
$l_beacon_reads		 = "La bouée présente affiche :";
$l_beacon_none		 = "Il n'y a présentement aucune bouée dans ce secteur.";
$l_beacon_enter		 = "Entrez le texte de la bouée";
$l_beacon_nowreads	 = "La bouée affiche maintenant";
$l_beacon_donthave	 = "Vous n'avez aucun bouée.";

?>
