<?php
$l_nav_title		 = "Ordinateur de bord";
$l_nav_nocomp		 = "L'ordinateur de bord n'est pas disponible";
$l_nav_query		 = "Entrez le sector que vous voudriez atteindre: ";
$l_nav_pathfnd		 = "Chemin trouvé:";
$l_nav_answ1		 = "Vous utiliserez";
$l_nav_answ2		 = "tours pour atteindre ce secteur.";
$l_nav_proper = "Vous devez mettre à jour votre combattant technologie Bay avant de vos combattants peuvent trouver un itinéraire chaîne pour cette distance.";
$l_nav_autoroutename = "Facultatif Nom Autoroute:";
$l_nav_manuallist = "Construit manuellement WarpLink Liste Autoroute";
$l_nav_warplinksleaving = "Warp Liens Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Il n&#39;y a pas warplinks quitter ce secteur.";
$l_nav_warp_from = "Courbure de";
$l_nav_rs_from = "RSMove de";
$l_nav_notinlogs = "Pas de données disponibles sur ce secteur.";
?>
