<?php
$l_readm_title		 = "Lire les messages";
$l_readm_delete		 = "MESSAGE EFFACÉ";
$l_readm_nomessage	 = "Vous n'avez aucun message en attente";
$l_readm_center		 = "Centre de messagerie";
$l_readm_sender		 = "Source";
$l_readm_captn		 = "Capitaine du ";
$l_readm_del		 = "Effacer";
$l_readm_repl		 = "Répondre";
$l_readm_return = "Cliquez ici pour retourner au menu principal";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Supprimer tout";
$l_readm_subject = "Sujet";
$l_readm_quote = "Citer";
$l_readm_block = "Bloquer l&#39;expéditeur";
$l_readm_alert = "Système d&#39;alerte";
$l_readm_alertbody = "Ship Computer";
?>
