<?php
$l_cu_storing = "Stockage";
$l_cu_inistored = "<b>Toutes les valeurs ini ont été sauvé avec succès.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Route Auto ID";
$l_cu_start = "Route Auto Start";
$l_cu_destination = "Auto Route Destination";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Supprimer l&#39;itinéraire";
$l_cu_info = "Cliquez sur Démarrer pour le secteur REALSPACE à ce secteur et commencer à déformer au secteur de destination.";
$l_cu_delete2 = "Supprimer des routes";
$l_cu_noroutes = "Non Auto Routes";
$l_cu_createroute = "Créer une nouvelle Auto Route";
$l_cu_deleted = "Auto Routes supprimé.";
$l_cu_return = "Retour au Menu Cliquez Auto Route";
$l_cu_created = "Auto Route a été créé.";
$l_cu_realmove = "Déplacer REALSPACE au secteur";
$l_cu_warpmove = "Warp se déplacer au secteur de la prochaine";
$l_cu_warpfinal = "Warp se déplacer au secteur de la finale";
?>
