<?php
$l_warp_cantsame = "Vous ne pouvez pas créer un lien lorsque la source est la même que la destination.";
$l_warp_twoerror	 = "L'utilisation d'un éditeur de lien pour créer un lien vers [target_sector] n'est pas permis.";
$l_warp_sectex		 = "Vous ne pouvez créer un lien à partir du secteur courant - vous dépasseriez la limited de $link_max par secteur.";
$l_warp_linked		 = "Le secteur cible ([target_sector]) à déjà un lien à partir de ce secteur.";
$l_warp_coneway	         = "Lien a sens unique créé vers";
$l_warp_ctwoway		 = "Lien créé de et vers";
$l_warp_nomoney = "Vous n&#39;avez pas assez de crédits pour créer le lien de chaîne.";
$l_warp_noenergy = "Vous n&#39;avez pas assez d&#39;énergie pour créer le lien de chaîne.";
?>
