<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] a touché [chm_roll] mines dans le secteur [chm_sector].";
$l_chm_youlostminedeflectors    = "Vous perdez [chm_roll] déflecteurs.";
$l_chm_youlostallminedeflectors = "Vous perdez tous vos déflecteurs.";
$l_chm_youhadnominedeflectors  = "Vous n'aviez aucun déflecteur.";
$l_chm_yourshieldshitforminesdmg        = "Vos boucliers sont touchés pour [chm_mines_left] points de dommage.";
$l_chm_yourshieldsaredown       = "Vos boucliers sont tombés!";
$l_chm_youlostallyourshields    = "Vous avez perdu tous vos boucliers!";
$l_chm_yourarmorhitforminesdmg  = "Votre armure a été touchée pour [chm_mines_left] points de dommage.";
$l_chm_yourhullisbreached       = "Votre coque a été pénétrée!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] a été détruit par vos mines dans le secteur [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Votre vaisseau a été détruit!";
$l_chm_luckescapepod    = "Heureusement vous aviez un module de secours!";

$l_chm_yourdeflectormalf1 = "Mine Déflecteur système de lancement a mal fonctionné.";
$l_chm_yourdeflectormalf2 = "Vous avez seulement été capables de lancer";
$l_chm_yourdeflectormalf3 = "pour cent de vos déflecteurs mine.";
$l_chm_enemytorpfailshields = "n&#39;a pas lancé de torpilles contre vos boucliers.";
$l_chm_enemytorpfailarmor = "n&#39;a pas lancé de torpilles contre votre armure.";

$l_chm_minemalf1 = "Mines ennemis ont mal fonctionné.";
$l_chm_minemalf2 = "Uniquement";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines = "Tu as frappé [chm_roll] mines sur [total_mines] mines!";
$l_chm_yourdeflectormalf2a = "Vous avez seulement été en mesure de lancer [deflectors] pour cent de vos déflecteurs mine.";
$l_chm_mines_destroyed = "[number] de [target] des mines ont été détruites!";
$l_chm_mine_deflectors_left = "Avez-vous [number] déflecteurs mine gauche.";
$l_chm_mines_left = "Il ya [number] mines abandonnées et elles ont une incidence sur votre armure!";
$l_chm_minemalf2a = "Seulement [deflectors] pour cent des mines d&#39;attaquer trouve votre bateau.";
$l_chm_mines_exhausted = "[player] mines épuisées!";
$l_chm_armor_left = "Tu as [number] points d&#39;armure à gauche!";

?>
