<?php
$l_sm_title = "Secteur de lancement de missiles";
$l_sm_invalid = "Il n&#39;ya pas un lien de chaîne entre ce secteur et le secteur de destination.";
$l_sm_notarg = "Cible non dans ce secteur.";
$l_sm_noturn = "Vous devez avoir au moins un tour à feu de votre secteur des missiles.";
$l_sm_nosectormissile = "Vous ne transportent aucune Missiles Secteur.";
$l_sm_noscan = "Les capteurs peuvent pas obtenir un correctif sur la cible!";
$l_sm_flee = "Objectif à manoeuvré l&#39;missiles Secteur!";
$l_sm_ewd = "Target a engagé un dispositif de chaîne d&#39;urgence quand il a détecté la Missile Secteur!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] est d&#39;attaquer votre navire avec un missile Secteur!";
$l_sm_sectormissilefail = "The Missile Secteur mal fonctionné quand il a heurté les navires ennemis bouclier!";
$l_sm_sectormissilefail2 = "The Missile Secteur mal fonctionné quand il a heurté les navires ennemis armure!";
$l_sm_shieldhit = "[target] &#39;s boucliers sont frappés de [amount] dégâts!";
$l_sm_shieldsdown = "[target] &#39;s boucliers sont en baisse!";
$l_sm_armorhit = "[target] &#39;s Armor est frappé de [amount] dégâts!";
$l_sm_armorbreached = "[target] &#39;s Armor violée!";
$l_sm_targetnoenergy = "Le vaisseau ennemi ne possède pas d&#39;énergie! Secteur des missiles échoue!";
$l_sm_attacking = "Attaquer [target] avec le [shipname]";
$l_sm_targetok = "Vous n&#39;avez pas destory [name] &#39;s navire.";
$l_sm_lost = "[target] perdu [armor] points de l&#39;armure et les [energy].";
$l_sm_destroyed = "[target] &#39;s navire a été détruit.";
$l_sm_escapepod = "Un module de secours a été lancé!";
?>
