<?php
$l_ship2_buytitle = "L&#39;achat d&#39;un nouveau navire";
$l_ship2_storetitle = "Shipyard installation de stockage";
$l_ship2_wrongclass = "Navire de la classe spécifiée est incorrecte";
$l_ship2_buying = "Vous achetez:";
$l_ship2_tradein = "Commerce:";
$l_ship2_value = "Valeur actuelle du navire:";
$l_ship2_newvalue = "New Ship Valeur:";
$l_ship2_totalcost = "Coût total:";
$l_ship2_nomoney = "Vous n&#39;avez pas assez de crédits pour acheter ce bateau.";
$l_ship2_purchase = "Acheter";
$l_ship2_buynstore = "Acheter un bateau neuf et ancien magasin";
$l_ship2_nomoney2 = "Vous n&#39;avez pas assez de crédits pour effectuer cette transaction.";
$l_ship2_paystorage = "Vous avez retiré votre navire de stockage.";
$l_ship2_turns = "Vous devez avoir au moins [turns] tourne pour effectuer cette action";
$l_ship2_error = "Erreur interne. Impossible de trouver le navire de la classe.";
$l_ship2_owned = "Vous possédez déjà ce modèle de navire.";
$l_ship2_shipbought = "Vous venez d&#39;acheter un navire neuf!";

?>
