<?php
$l_md_title		 = "Défenses de secteur";
$l_md_invalid		 = "Défense invalide";
$l_md_nolonger		 = "La défense que vous avez choisi n'est plus dans ce secteur.";
$l_md_you		 = "Vous";
$l_md_bmines		 = "Vos rayons détruisent";
$l_md_msgdownerb	 = "[name] a détruit [mines] mines dans le secteur [sector].";
$l_md_retr		 = "Vous récupérez";
$l_md_consist		 = "Cette défense consiste de [qty] [type], appartenant à [owner].";
$l_md_youcan		 = "Vous pouvez";
$l_md_retrieve		 = "Récupérer";
$l_md_attack		 = "Attaque";
$l_md_attdef		 = "Attaquer les défenses de secteur. Tous les intercepteurs présents vont converger vers vous.";
$l_md_noturn	  	 = "Vous avez besoin d'au moins un tour.";
$l_md_nothere            = "Vous devez être dans le même secteur que les défenses.";
$l_md_notyours           = "Cette action n'est pas permise. Ces défenses ne vous appartiennent pas.";
$l_md_yours              = "Vous ne pouvez attaquer vos propre défenses.";
?>
