<?php
$l_pre_title = "Changer les raccourcis d'espace réel";
$l_pre_exceed = "Le raccourci [preset] dépasse le nombre maximum de secteurs [sector_max]. Aucun raccourci sauvegardé.<BR><BR>";
$l_pre_set = "Le raccourci";
$l_pre_save = "Sauvegarder";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] est un nom de secteur non valide.";
$l_pre_invalidchange = "[sector] est un secteur Secteur de la Genèse. Votre vieux prédéfini est inchangé.";
?>
