<?php
// New News Items

$l_news_planets		 = " planetes";
$l_news_cols		 = " Million de colons";
$l_news_p_headline 	 = "Empire [player] a à present [total] planetes";
$l_news_c_headline 	 = "Empire [player] a à present [total] million de colons";
$l_news_p_textXX = "La Fédération a émis des avertissements concernant l&#39;Empire de [name]. [name] a le contrôle de [total] planètes et devrait être considéré comme très dangereux. Tous les secteurs devraient augmenter les défenses du secteur immédiatement.";
$l_news_c_textXX = "L&#39;Empire de [name] connaît une surpopulation massive sur toutes les planètes avec plus de [total] millions de colons. Les pénuries alimentaires mai causer des troubles. Tous les secteurs devraient être au courant des actions possibles agressive par [name] dans le futur.";

$l_created_universe             = 'Création D\'Univers';
$l_created_universe_full        = 'Les scientifiques recherchant le commencements de l\'univers ont unanimement décidé que c\'est aujourd\'hui le jour le plus statistiquement  probable pour que la création d\'univers ait lieu';

$l_news_p_text5		 = "L'empire emergeant de [name] a maintenant cinq planètes, le FNN observera les actions de [name] plus étroitement à l'avenir!";
$l_news_p_text10	 = "L'empire croissant de [name] controle maintenant dix planètes, Les rapports de FNN indiquent cette autre expansion de [name] pourrait engendrer la guerre!";
$l_news_p_text25	 = "L'énorme Empire de [name] qui a déjà colonisé 25 planètes, dans une entrevue, [name] a annoncé qu'il pourrait ralentir son expansion à l'avenir!";
$l_news_p_text50	 = "L'énorme et vaste empire de [name], représenté par 50 planètes dans la galaxie entière represente une force menaçante. Un des journalistes de FNN a découvert que [name] améliore son vaisseau, projetant une guerre importante. Dans une entrevue, [name] a annoncé que c'est seulement dans un but défenssif!";
$l_news_c_text25	 = "L'empire emmergeant de [name] a maintenant 25 millions de colons, le FNN observera les actions de [name] plus étroitement à l'avenir, mais il est fortement évident que le taux de naissance vas éclater!";
$l_news_c_text100	 = "L'empire de [name] a maintenant 100 millions de colons, après une explosion du taux de natalité, les colonies de [name] semble être un bon endroit pour les familles.!";
$l_news_c_text500	 = "Le grand empire de [name] a maintenant 500 millions colons, [name] dit dans une entrevue que la colonisation de la galaxie à juste seulement commencé";
$l_news_c_text1000	 = "L'empire giguentesque de [name] a maintenant un milliard de colons, Les journalistes de FNN ont découvert que [name] est en possesion d'un certain mécanisme étrange de clonage, lui permettant de multiplier de nouveaux colons dans des montants énormes. Avec cette quantité de colons, la force economique de cet empire est énorme, FNN espère que [name] ne dépense pas son argent pour une future guerre";

$l_news_indi_short	 = "Rumeur de FNN: au-dessus de [planets] déclarez l'independance.";
$l_news_indi	 = "FNN a de sources sures que plus de [planets] planètes ont décidé qu'elles serai mieux gerer par elles-mêmes et sont devenues independant.";

$l_news_nova_short	 = "Rapport de FNN: [name] a utilisé la bombe Nova.";
$l_news_nova	 = "FNN divulgue la nouvelles que [name] a employé la terrible bombe nova [total] fois pour détruire une planète et tous les vaisseaux qui s'y trouvaient.";
$l_news_nova_m_short	 = "Rapport de FNN: [name] a utilisé la bombe Nova et manqua sa cible.";
$l_news_nova_m	 = "FNN divulgue la nouvelles que [name] a employé la terrible bombe nova [total] fois pour essayer de détruire une planète.  La bombe nova a explosé en dehors de l'atmosphère de le planète et a endommagé massivement l'infrastructure planétaire.";

$l_news_bounty	 = "Rapport de FNN: [name] place une prime de [amount] sur la tete de [name2].";

$l_news_attackerpod_p_short	 = "Rapport de FNN: le vaisseau de [name] a ete detruit.";
$l_news_attackerpod_P	 = "le vaisseau de [name] a été détruit en attaquant une planète.  Heureusement, [name] avait un module d'evaquation et a survécu.";

$l_news_attackerdie_p_short	 = "Rapport de FNN: [name] est mort!";
$l_news_attackerdie_p	 = "le vaisseau de [name] a été détruit en attaquant une planète et il a été tués parce qu'il n'avait pas acheté une module d'évaquation.";

$l_news_destroyed_p_short	 = "Rapport de FNN: [name] attaque et détruit une planète!";
$l_news_destroyed_p	 = "[name] a attaqué [total] fois la planete possédé par [owner] mais la population a prefer détruire la planète plutot que d'etre capturé!";

$l_news_defeated_p_short	 = "Rapport de FNN: [name] attaque et detruits les defenses d'une planete!";
$l_news_defeated_p	 = "[name] a attaqué [total] fois la planete possédé par [owner] et défait les forces planétaires de défense!";

$l_news_notdefeated_p_short	 = "Rapport de FNN: [name] attaque une planète et perd!";
$l_news_notdefeated_p	 = "[name] a attaqué [total] fois la planete possédé par [owner] et les défenses planétaires ont tenues contre les attaques implacables!";

$l_news_targetepod_short	 = "Rapport de FNN: [name] attaque [owner] et gagne!";
$l_news_targetepod	 = "[name] a attaqué le vaisseau de [owner] et le detruit completement. Heureusement, [owner] avait equipé son vaisseau avec un module d'évaquation et il a survécu.";

$l_news_targetdies_short	 = "Rapport de FNN: [name] attaque [owner] et le tue!";
$l_news_targetdies	 = "[name] a attaqué le vaisseau de [owner] et le detruit completement.  Malheureusement [owner] n'avait pas equipé son vaisseau avec un module d'évaquation et il a été vaporisés.";

$l_news_fedcolbounty_short = "FNN Rapport: La Fédération des fissures vers le bas sur [name]!";
$l_news_fedcolbounty = "La Fédération compte aujourd&#39;hui attaqués à la tristement célèbre pirate de l&#39;espace [name]! [name], qui a systématiquement violé les traités sur l&#39;espace de plusieurs, a été brièvement engagé par le Battlecruiser Fédération, qui ont infligé de [amount] Les crédits de dollars de dégâts sur le navire du pirate. Responsables de la fédération promettent en outre de telles actions dans l&#39;avenir!";

$l_news_alliancecolbounty_short = "FNN Report: The Alliance fissures vers le bas sur [name]!";
$l_news_alliancecolbounty = "L&#39;Alliance aujourd&#39;hui a réprimé le fameux pirate de l&#39;espace [name]! [name], qui a systématiquement violé les traités sur l&#39;espace de plusieurs, a été brièvement engagé par l&#39;Alliance, qui ont infligé de [amount] Les crédits de dollars de dégâts sur le navire du pirate. Responsables de l&#39;Alliance promets en outre, de telles actions dans l&#39;avenir!";

$l_news_fedcol_pbounty_short = "FNN Rapport: La Fédération de traque [name]!";
$l_news_fedcol_pbounty = "La Fédération compte aujourd&#39;hui attaqués à la tristement célèbre pirate de l&#39;espace [name]! [name], qui a systématiquement violé les traités sur l&#39;espace de plusieurs, a été brièvement engagé par le Battlecruiser Fédération, qui a confisqué la planète [planetname] planetname une valeur de [amount] crédits dans le secteur [sector]. Responsables de la fédération promettent en outre de telles actions dans l&#39;avenir!";

$l_news_alliancecol_pbounty_short = "FNN Report: The Alliance traque [name]!";
$l_news_alliancecol_pbounty = "L&#39;Alliance aujourd&#39;hui a réprimé le fameux pirate de l&#39;espace [name]! [name], qui a systématiquement violé les traités sur l&#39;espace de plusieurs, a été brièvement engagé par l&#39;Alliance, qui a confisqué la planète [planetname] planetname une valeur de [amount] crédits dans le secteur [sector]. Responsables de l&#39;Alliance promets en outre, de telles actions dans l&#39;avenir!";

$l_news_fedcol_sbounty_short = "FNN Rapport: La Fédération de traque [name]!";
$l_news_fedcol_sbounty = "La Fédération compte aujourd&#39;hui attaqués à la tristement célèbre pirate de l&#39;espace [name]! [name], qui a systématiquement violé les traités sur l&#39;espace de plusieurs, a été brièvement engagé par le Battlecruiser Fédération, qui a confisqué un navire ([shiptype]) pour une valeur [cost] dans le secteur [sector]. Responsables de la fédération promettent en outre de telles actions dans l&#39;avenir!";

$l_news_alliancecol_sbounty_short = "FNN Report: The Alliance traque [name]!";
$l_news_alliancecol_sbounty = "L&#39;Alliance aujourd&#39;hui a réprimé le fameux pirate de l&#39;espace [name]! [name], qui a systématiquement violé les traités sur l&#39;espace de plusieurs, a été brièvement engagé par l&#39;Alliance, qui a confisqué un navire [shiptype] une valeur de type de navire [cost] dans le secteur [sector]. Responsables de l&#39;Alliance promets en outre, de telles actions dans l&#39;avenir!";

$l_killheadline		 ="[target] a été tué dans un accident";
$l_news_killed 		 = "[target] a été tué dans un accident tragique aujourd'hui. héroïquement - le captaine [target] était le dernier membre à bord de son vaisseau, quand il a noté qu'il n'y avait plus de module d'evacuation pour lui. Qu'il reposent en paix !";

$l_killSDheadline = "[target] a été tué par les défenses du secteur.";
$l_news_killedSD = "[target] a été tué par un très grand nombre de défenses du secteur appartenant à [killer]! Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killplanetheadline = "[target] a été tué d&#39;attaquer une planète.";
$l_news_killedplanet = "[target] a été tué en attaquant une planète appartenant à [killer] aujourd&#39;hui. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killshipheadline = "[target] a été tué de combat de bateau.";
$l_news_killedship = "[target] a été tué dans un navire à combattre avec [killer] aujourd&#39;hui. Le commandant de bord avait oublié d&#39;équiper le bateau avec une capsule de sauvetage.";

$l_killsuicideheadline = "[target] se suicide.";
$l_news_killedsuicide = "[target] suicide commis aujourd&#39;hui. Ils ont pris le chemin des lâches parce qu&#39;ils n&#39;avaient pas la capacité ou le courage de tenir tête aux pressions de commander son propre navire.";

$l_killsofaheadline = "[target] a été tué canapé attaquer une planète.";
$l_news_killedsofa = "[target] a été tué alors qu&#39;il canapé attaquer une planète appartenant à [killer] aujourd&#39;hui. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killnovaheadline = "[target] a été tué lors d&#39;une attaque nova.";
$l_news_killednova = "[target] a été tué par [killer] lors d&#39;une attaque à la bombe nova aujourd&#39;hui. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killnovabackfireheadline = "[target] a été tuée d&#39;une nova retour de flamme.";
$l_news_killednovabackfire = "[target] a été tué lorsque leur bombe nova s&#39;est retournée contre aujourd&#39;hui. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killsectormissileheadline = "[target] a été tué par un missile Secteur.";
$l_news_killedsectormissile = "[target] a été tué quand un missile Secteur de [killer] affecté leurs boucliers. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killhunterprobeheadline = "[target] a été tué d&#39;une sonde Hunter.";
$l_news_killedhunterprobe = "[target] a été tué quand un traducteur Hunter de [killer] affecté leurs boucliers. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

$l_killtrapprobeheadline = "[target] a été tué d&#39;une sonde Trap Sentry.";
$l_news_killedtrapprobe = "[target] a été tué quand un traducteur Sentry Piège à partir de [killer] affecté leurs boucliers. Malheureusement, le navire n&#39;était pas équipé d&#39;un module de secours.";

//-------------------

$l_killpodheadline = "[target] &#39;s navire a été détruit dans un accident";
$l_news_killedpod = "[target] &#39;s navire a été détruit dans un accident tragique survenu aujourd&#39;hui. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killSDpodheadline = "[target] &#39;s navire a été détruit par les défenses du secteur.";
$l_news_killedSDpod = "[target] &#39;s navire a été détruit par un très grand nombre de défenses du secteur appartenant à [killer]! Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killplanetpodheadline = "[target] &#39;s navire a été détruit attaquer une planète.";
$l_news_killedplanetpod = "[target] &#39;s navire a été détruit en attaquant une planète appartenant à [killer] aujourd&#39;hui. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killshippodheadline = "[target] &#39;s navire a été détruit dans des combats spatiaux.";
$l_news_killedshippod = "[target] &#39;s navire a été détruit dans un navire à combattre avec [killer] aujourd&#39;hui. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killsofapodheadline = "[target] &#39;s navire a été détruit au cours canapé attaquer une planète.";
$l_news_killedsofapod = "[target] &#39;s navire a été détruit au cours canapé attaquer une planète appartenant à [killer] aujourd&#39;hui. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killnovapodheadline = "[target] &#39;s navire a été détruit lors d&#39;un attentat-nova.";
$l_news_killednovapod = "[target] &#39;s navire a été détruit par [killer] lors d&#39;une attaque à la bombe nova aujourd&#39;hui. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killnovabackfirepodheadline = "[target] &#39;s navire a été détruit à partir d&#39;un nova retour de flamme.";
$l_news_killednovabackfirepod = "[target] &#39;s navire a été détruite lors de leur bombe nova s&#39;est retournée contre aujourd&#39;hui. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killsectormissilepodheadline = "[target] &#39;s navire a été détruit par un missile Secteur.";
$l_news_killedsectormissilepod = "[target] &#39;s navire a été détruit par un missile Secteur de [killer] affecté leurs boucliers. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killhunterprobepodheadline = "[target] &#39;s navire a été détruit par une sonde Hunter.";
$l_news_killedhunterprobepod = "[target] &#39;s navire a été détruite quand un traducteur Hunter de [killer] affecté leurs boucliers. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

$l_killtrapprobepodheadline = "[target] &#39;s navire a été détruit par une sonde Trap Sentry.";
$l_news_killedtrapprobepod = "[target] &#39;s navire a été détruite quand un traducteur Sentry Piège à partir de [killer] affecté leurs boucliers. Un transpondeur Escape Pod a été détectée par la Fédération de recherche et de sauvetage.";

// --------------------------

$l_news_promotedheadline = "[name] a été promu au [rank]";
$l_news_promoted = "La Fédération est heureuse d&#39;annoncer la promotion de [name] au rang de [rank].";

$l_news_demotedheadline = "[name] a été rétrogradé au [rank]";
$l_news_demoted = "La Fédération a le regret d&#39;annoncer la rétrogradation de [name] au rang de [rank].";

$l_news_namechangedheadline = "[oldname] a changé de nom à [newname]";
$l_news_namechanged = "[oldname] appliqué à la Commission d&#39;examen Fédération de changer de nom à [newname]. La Fédération a obtenu le changement de nom. Partir de ce jour [oldname] doit maintenant être connu comme [newname]. Tous les navires et les planètes devrait mettre à jour leurs dossiers immédiatement.";

$l_news_found_planets_short = "Fédération de l&#39;enquête: [found_planets] nouvelles planètes situées.";
$l_news_found_planets = "Fédération des Scouts Enquête avez localisé [found_planets] de nouvelles planètes dans les secteurs récemment découverts.";

$l_news_new_ports_short = "Fédération de l&#39;enquête: [new_ports] nouveaux ports construits.";
$l_news_new_ports = "Fédération des ingénieurs ont construit [new_ports] nouveaux ports dans les secteurs récemment découverts.";

$l_news_addedsectors_short = "Fédération de l&#39;enquête: [addedsectors] secteurs découverts.";
$l_news_addedsectors = "Fédération des Scouts Survey ont découvert [addedsectors] de nouveaux secteurs. La prudence est conseillée.";

$l_news_artifactheadline = "[playername] [artifact]";
$l_news_artifact = "[playername] a trouvé tous les morceaux de l&#39;artefact [artifact] et a toute la puissance qu&#39;il peut fournir.";

$l_news_artifactfoundheadline = "[playername] trouvés [artifact] morceau";
$l_news_artifactfound = "[playername] a trouvé l&#39;une des pièces de l&#39;artefact [artifact] et des besoins [pieces] plus [piece].";

?>
