<?php
$l_opt_title = "Sélectionner un Avatar";
$l_opt_errorsize = "Erreur: Votre image ne doit pas être plus grands que 64x64 pixels.";
$l_opt_errortype = "Erreur: l&#39;image doit être JPG, GIF ou PNG";
$l_opt_errornographic = "Erreur: aucun graphique choisie.";
$l_opt_currentavatar = "Your Current Avatar";
$l_opt_uploadavatar = "Publier un Avatar";
$l_opt_directory = "Sélectionnez Avatar Directory";
$l_opt_change = "Changer de répertoire";
$l_opt_select = "Sélectionnez Avatar";
$l_opt_inuse = "Tous les Avatars dans ce répertoire sont en cours d&#39;utilisation.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
