<?php
$l_opt_title = "Choisissez une équipe Icon";
$l_opt_errorsize = "Erreur: Votre image ne doit pas être plus grands que 64x64 pixels.";
$l_opt_errortype = "Erreur: l&#39;image doit être JPG, GIF ou PNG";
$l_opt_errornographic = "Erreur: aucun graphique choisie.";
$l_opt_currentavatar = "Votre équipe actuelle Icon";
$l_opt_uploadavatar = "Envoyez une icône";
$l_opt_directory = "Choisir l&#39;Equipe Icon Directory";
$l_opt_change = "Changer de répertoire";
$l_opt_select = "Choisir l&#39;Equipe Icon";
$l_opt_noteam = "Vous n&#39;êtes pas dans une équipe.";
$l_opt_notleader = "Seul le coordonnateur de l&#39;équipe peuvent changer l&#39;icône d&#39;équipe.";
$l_opt_inuse = "Toutes les icônes de l&#39;équipe dans ce répertoire sont en cours d&#39;utilisation.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
