<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1]         = "Espace non-exploré";
$l_zname[2]         = "Espace de la Fédération";
$l_zname[3] = "Space Alliance";
$l_zname[4]         = "Zonne de Guerre";

$l_nova = "Nova";
$l_nova = "Nouvelle-Bomb";
$l_lssd 		 = "Dernier appareil vu";
$l_lss 			 = "Dernier vaissau vu dans ce secteur";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Éditeur de liens";
$l_warp_turn		 = "Vous avez besoin d'au moins un tour pour utiliser un éditeur de liens.";
$l_warp_none		 = "Vous n'avez aucun éditeur de liens.";
$l_warp_forbid		 = "Il n'est pas permis d'utiliser un éditeur de liens.";
$l_warp_nosector	 = "Ce secteur n'existe pas.";
$l_swarp_forbid = "Utilisant un éditeur de Warp, ou à partir SG secteurs n&#39;est pas permise.";
// Not yet confirmed common to multiple files:

$l_yes 			 = "Oui";
$l_no			 = "Non";
$l_here			 = "ici";
$l_submit		 = "Envoyer";
$l_reset		 = "Restaurer";
$l_all			 = "Tout";
$l_max = "Max";

$l_trade = "Commerce";
$l_ore			 = "Métaux";
$l_commodity = "Commodity";
$l_commodities = "Matières premières";
$l_organics		 = "Végétaux";
$l_goods		 = "Produits";
$l_energy		 = "Énergie";
$l_colonists		 = "Colons";
$l_credits 		 = "Crédits";
$l_units		 = "unités de ";
$l_special		 = "Spécial";
$l_upgrade_ports = "Mises à jour";
$l_device_ports = "Dispositifs";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_spy = "Espions";
$l_dig = "Dignitaires";

$l_cargo		 = "Cargaison";
$l_fighters		 = "Intercepteurs";
$l_mines = "Mines";
$l_torps		 = "Torpilles";

$l_none			 = "Aucun";
$l_unnamed		 = "Sans Nom";
$l_name			 = "Nom";
$l_unowned		 = "Libre";
$l_unknown		 = "Inconnu";
$l_clickme 		 = "Cliquer ici";
$l_player  		 = "Joueur";
$l_ship			 = "Vaisseau";
$l_ships		 = "Vaisseaux";
$l_set			 = "Mod";
$l_realspace		 = "Espace Réel";
$l_armorpts		 = "Points d'armure";
$l_links		 = "Liens";
$l_login_email          = "Adresse e-mail:";
$l_submit               = "envoyer";
$l_reset                = "retaurer";
$l_add = "Ajouter";
$l_teamforum = "Équipe du Forum";
$l_teamships = "Team Ships";
$l_tutorial = "Tutorial / Aide";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Debris";
$l_localmap = "Carte Locale";
$l_arm_weap = "Armor &amp; Weapons";
$l_3dmap = "Carte 3D Galaxy";

$l_sectormissile = "Secteur des missiles";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Sondes spatiales";
$l_warpeditors = "Warp Editors";
$l_genesistorps = "Genesis Torpilles";
$l_sgtorps = "SG Torpilles";
$l_minesfighters = "Mines / Fighters";
$l_ewarp = "Warp urgence";
$l_reports = "Rapports";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Secteur Notes";
$l_maps = "Cartes";
$l_messages = "Messages";
$l_shiptype = "Type de navire";
$l_help = "Aider";
$l_rank = "Classement";

$l_teamplanets = "Team Planètes";
$l_teamdefenses = "Team défenses";
$l_planetstatus = "Planet Etat";
$l_planetdefenses = "Défenses Planet";
$l_changeproduction = "Changement de production";
$l_galacticarm = "Galactic Arm";
$l_armor = "Armor";
$l_news_none		 = "Désolé, aucune nouvelles ajourd'hui.";

$l_ranks_good = "Bien";
$l_ranks_evil = "Mauvais";
$l_ranks_neutral = "Neutre";

$l_global_mmenu			="Cliquez <A HREF=main.php>ici</A> pour retourner au menu principal.";
$l_global_mlogin		="Cliquez <A HREF=index.php>ici</A> pour retourner à l'écran de connection.";
$l_global_needlogin		="Vous devez vous connecter, cliquez <A HREF=index.php>ici</A>.";
$l_global_died			="Vous êtes mort! <a href=log.php>Voici</a> ce qui vous est arrivé<BR><BR>Meilleure chance la prochaine fois!";
$l_global_warzone		="La zone est maintenant une Zone de Guerre!";
$l_global_nzone			="La zone est maintenant une Zone Neutre.";
$l_global_team			="La zone appartient maintenant à l'alliance";
$l_global_player		="La zone appartient maintenant au joueur";
$l_global_nochange      ="Zone ownership didn't change"; //TODO Translate it, please
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "Maître de troisième classe";
$l_insignia_name[4] = "Maître de deuxième classe";
$l_insignia_name[5] = "Maître de première classe";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Lieutenant Junior Grade";
$l_insignia_name[11] = "Lieutenant";
$l_insignia_name[12] = "Lieutenant Commander";
$l_insignia_name[13] = "Commandant";
$l_insignia_name[14] = "Capitaine";
$l_insignia_name[15] = "Contre-amiral (moitié inférieure)";
$l_insignia_name[16] = "Contre-amiral (moitié supérieure)";
$l_insignia_name[17] = "Le vice-amiral";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Flotte de l&#39;amiral";

$l_main_title 		 = "Menu Principal";
$l_main_warpto = "Hyper-espace";
$l_main_autoroute = "Autoroute à";
$l_main_rs_to = "RSMove à";
$l_main_other            = "Autre";
$l_main_shipyard1        = "Achat de vaissaux";
$l_main_shipyard2        = "Acceder à l' ";
$l_traderoutes		 = "Commerce";
$l_trade_control	 = "Modifier";
$l_youhave 		 = "Vous avez ";
$l_turns_used		 = "Tours utilisés: ";
$l_turns_have		 = "Tours disponibles: ";
$l_score		 = "Points: ";
$l_sector		 = "Secteur";
$l_help			 = "Aide";
$l_faq = "FAQ";
$l_feedback		 = "Commentaires";
$l_forums = "Forums";
$l_logout		 = "Quitter";
$l_commands		 = "Commandes";
$l_command_no		 = "Commande non disponible.";
$l_devices		 = "Appareils";
$l_planets		 = "Planètes";
$l_log			 = "Journal";
$l_sector_def		 = "Défenses";
$l_defense		 = "Défenses";
$l_read_msg		 = "Lire Messages";
$l_send_msg		 = "Écrire Messages";
$l_rankings		 = "Rangs";
$l_teams		 = "Alliances";
$l_ohno			 = "Auto-Destruction";
$l_options = "Options";
$l_navcomp		         = "Ordinateur";
$l_incompletemove 	 = "Vous n'avez pas complété votre dernier déplacement.";
$l_clicktocontinue	 = "Cliquez ici pour continuer";
$l_toplanetmenu   	 = "Pour aller au menu de planète.";
$l_nonexistant_pl	 = "Sur une planète qui n'existe pas???";
$l_abord		 = ", à bord du ";
$l_messages_wait	 = " Messages qui vous attendent.";
$l_no_warplink		 = "Aucun liens";
$l_scan			 = "sonder";
$l_fullscan		 = "Sonder tout";
$l_port = "Port";
$l_tradingport		 = "Port commercial";
$l_planet_in_sec	 = "Planètes dans le secteur ";
$l_ships_in_sec		 = "Autres vaisseaux dans le secteur ";
$l_sector_0		 = "Il y a tellement de déplacements dans Sol que vous ne pouvez distinguer les vaisseaux entre eux!";
$l_map                   = "Carte";
$l_autotrade = "Autotrades";
$l_onboard = "à bord d&#39;un";
$l_classship = "navire de la classe";
$l_traveled = "voyagé au secteur";
$l_max_planets = "Maximum planètes habital";
$l_block_msg = "Bloquer les messages";
$l_probe = "Sondes";
$l_sectorinfo = "Information sectorielle";
$l_add_note = "Ajouter une note";
$l_view_note = "Affichage";
$l_notes = "Notes";
$l_global_limitreached = "Vous avez atteint la limite de la quantité de fois que vous êtes autorisé à être en ligne chaque jour. Connectez-vous à nouveau demain après minuit.";
$l_onlinetimeleft = "Temps restant:";
$l_planetmax = "Planetary maximale:";
$l_storedshipreport = "Stockées navires";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Fédération Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Page Précédente";
$l_common_next = "Page suivante";
$l_common_totalpages = "Total Pages";
$l_common_selectpage = "Choisissez la page:";
$l_common_page = "Page:";
$l_templatechange = "Souhaitez-vous conserver ce modèle?";

$l_im_fed_bounty = "La Fédération a mis une prime sur vous pour attaquer un joueur faible classés. La Fédération va attaquer votre vaisseau sur une base régulière jusqu&#39;à ce que vous remboursez votre prime. Vous pouvez payer votre prime à un port Upgrade ou Spacedock.";
$l_im_fed_bounty_title = "Fédération placé une prime sur vous!";
$l_im_alliance_bounty = "L&#39;Alliance a placé une prime sur vous pour attaquer un joueur faible classés. L&#39;Alliance va attaquer votre vaisseau sur une base régulière jusqu&#39;à ce que vous remboursez votre prime. Vous pouvez payer votre prime à un port Upgrade ou Spacedock.";
$l_im_alliance_bounty_title = "Alliance placé une prime sur vous!";
$l_instant_messages_waiting = "Avez-vous [count] Messages en attente pour vous.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Cales pleines:";
$l_hold_space_free = "Cales sont vides:";
$l_port_buys = "Port achète sur le marché:";

?>
