<?php
$l_warp_linkto		 = "Il y a des liens de ce secteur vers";
$l_warp_nolink		 = "Il n'y a aucun lien sortant de ce secteur.";
$l_warp_query		 = "Vers quel secteur voudriez-vous créer un lien?";
$l_warp_oneway		 = "Sens unique?";
$l_warp_dest		 = "Vous pouvez aussi détruire un lien vers ce secteur";
$l_warp_destquery	 = "Vers quel secteur voudriez-vous détruire le lien?";
$l_warp_bothway		 = "Deux sens";
$l_warp_create = "Créer un lien entre le secteur de chaîne:";
$l_warp_andsector = "et secteur:";
$l_warp_distance = "avec une distance de";
$l_warp_lightyears = "Light Years";
$l_warp_delete = "Supprimer le lien entre le secteur de chaîne:";
$l_warp_costcreate = "Coût de créer:";
$l_warp_costdelete = "Coût à supprimer:";
$l_warp_costenergy = "Énergie nécessaire:";
$l_warp_twoerror	 = "L'utilisation d'un éditeur de lien pour créer un lien vers [target_sector] n'est pas permis.";
?>
