<?php
$l_shipyard_title        = "Achat de vaissaux";
$l_planet                = "Planète";
$l_ship_welcome = "Bienvenue sur votre chantier planétaire. Nous offrons actuellement ces modèles à la vente.";
$l_ship_class = "Classe";
$l_ship_properties = "Propriétés de classe";
$l_ship_current = "Actuel";
$l_ship_outstorage = "Get Out of Storage";
$l_ship_storagecost = "Coût de stockage";
$l_ship_storagewarn = "Une fois que vous prenez votre Pioneer hors du stockage vous perdrez ceux que vous ont été émises lors de votre destruction du navire initial.";
$l_ship_levels = "Ship Composants Niveaux";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Prix";
$l_ship_turns = "Tours à construire";
$l_ship_purchase = "Acheter";
$l_ship_stored = "Stockée";
$l_ship_basehull = "Base de la coque:";

$l_ship_averagemaxtech = "Moyenne maximale Tech Niveau:";
$l_ship_averagenormaltech = "Moyenne normale Tech Niveau:";
$l_ship_averagecurrenttech = "Courant moyen Tech Niveau:";
?>
