<?php
$l_autotrade_title = "Auto Traderoute Menu";
$l_autotrade_dismiss2 = "Auto Routes commerciales supprimés.";
$l_autotrade_report = "Auto Traderoute Rapport";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energie";
$l_autotrade_capacity = "Capacité";
$l_autotrade_goods = "Prix des biens";
$l_autotrade_ore = "Prix du minerai de";
$l_autotrade_organics = "Biologique Prix";
$l_autotrade_energy = "Prix de l&#39;énergie";
$l_autotrade_colonist = "Colonist Prix";
$l_autotrade_credits = "Crédits commerciaux";
$l_autotrade_delete = "Supprimer <br> Route";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "Pas d&#39;itinéraire";
$l_autotrade_sector = "Secteur";
$l_autotrade_credit2 = "crédits";
$l_autotrade_deletebutton = "Supprimer";
$l_autotrade_noroute2 = "Vous n&#39;avez pas configuré tout Routes commerciales Auto.";
?>
