<?php
$l_profile_title = "Profil Inscription";
$l_profile_notenabled = "Profils ne sont pas activés sur ce serveur.";
$l_profile_registered = "Ce joueur est maintenant enregistrée avec le serveur de profils Master.";
$l_profile_nomatch = "Pourrait ne pas correspondre à un profil sur le serveur de profils de maître avec le nom et le mot de passe serveur entré.";
$l_profile_tryagain = "Pour entrer votre nom de joueur profil et mot de passe serveur cliquer à nouveau sur";
$l_profile_name = "Profil Nom Player";
$l_profile_password = "Mot de passe du mode serveur";
$l_profile_bannedserver = "Ce serveur n&#39;est pas autorisé à soumettre des informations de profil sur le serveur maître Profil.";
$l_profile_bannedplayer = "Vous avez été bannis du serveur maître et le profil mai pas enregistrer des joueurs.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Ce serveur <u><b>exige que</b></u> chaque nouveau joueur d&#39;avoir un profil enregistré. Vous ne serez pas autorisé à créer un nouveau joueur, sauf si vous avez un profil enregistré.";
$l_profile_updated = "Votre modèle, shoutbox et des nouvelles d&#39;exploration des paramètres globaux ont été mis à jour sur le serveur maître Profil. Ces paramètres seront automatiquement utilisés lorsque vous enregistrez votre profil sur n&#39;importe quel match.";

?>
