<?php
$l_by_title = "Mises à prix";
$l_by_noturn = "Vous avez besoin d'un tours pour modifier une mise a prix.";
$l_by_amount = "Montant de la mise à prix";
$l_by_place = "Placer une mise à prix";
$l_by_nobounties = "Il n'y a pas de mises à prix.";
$l_by_bountyon = "Mise à prix sur";
$l_by_placedby = "Placée par";
$l_by_thefeds  = "La Fédération";
$l_by_cancel   = "Annuler";
$l_by_yourself = "Vous ne pouvez pas plancer une mise à prix sur vous même.";
$l_by_notenough = "Vous n'avez pas asser de credit pour placer cette mise à prix";
$l_by_toomuch   = "Vous ne pouvez pas placer cette mise à prix. La mise à prix maximum que vous pouvez placer sur un autre joueur est [percent] % de votre valeur.";
$l_by_zeroamount = "Les mises à prix doivent être supérieur a 0 crédits.";
$l_by_placed     = "La mise à prix a bien été placée.";
$l_by_nobounty = "cette mise à prix n'existe plus.";
$l_by_notyours = "Cette mise à prix n'a pas été placée par vous.";
$l_by_canceled = "La mise à prix a été annulée.";
$l_by_action = "Action";
$l_by_placebounty = "Placer ou voirs les mises à prix.";
$l_by_moredetails = "Cliquez sur le nom pour plus de détails.";
$l_by_fedbounty = "<font color='red' size='4'><b>Si vous attaquez ce joueurs, la Fédération placera une mise à prix sur vous.</b></font>";
$l_by_fedbounty2 = "<font color='red' size='4'><b>La Fédération n'a pas aprécier que vous attaqiez ce vaissau. Elle a placée une mise à prix sur vous.</b></font>";
$l_by_notexists = "Le joueurs sur lequel vous voulez placer la mise à prix n'existe pas.";
$l_by_destroyed = "Vous ne pouvez pas metre une mise à pix sur un joueur avec un vaissau détruit.";
$l_by_nofedbounty = "Vous ne recevrez une prime si vous attaquez ce navire joueurs ou planète.";
$l_by_fedcollectonly = "Seule la Fédération peut recueillir Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color='red' size='4'><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color='red' size='4'><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Vous ne recevrez une prime si vous placez un espion sur la planète joueurs cela.";
$l_pay_partial = "Effectuer un paiement partiel";
$l_pay_button = "Pay";
$l_by_thealliance = "L&#39;Alliance";
$l_by_alliancecollectonly = "Seule l&#39;Alliance peut Collect Bounty";
$l_by_bountyscan = "Bounty";
?>
