<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: Shoutbox::.";
$l_shout_public = "Public";
$l_shout_team = "Équipe";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "autre";
$l_shout_refresh = "Refresh";
$l_shout_close = "Fermer la fenêtre";
$l_shout_saved = "A sauvé!";
$l_shout_return = "Retour à la";
$l_shout_prev = "Précédent";
$l_shout_next = "Suivant";
$l_shout_selectpage = "Choisissez la page";
$l_shout_page = "Page:";
$l_shout_teamtitle = ".:: Shoutbox TEAM::.";
?>
