<?php
$l_opt2_title = "Sauvegarde des options";
$l_opt2_passunchanged = "Le mot de passe n'a pas été changé.<BR><BR>";
$l_opt2_srcpassfalse = "Le mot de passe original n'était pas valide. Le mot de passe n'a pas été modifié.<BR><BR>";
$l_opt2_newpassnomatch = "Les mots de passe entrés comme nouveau mots de passe ne concordent pas. Le mot de passe n'a pas été modifié.<BR><BR>";
$l_opt2_passchanged = "Mot de passe modifié.<BR><BR>";
$l_opt2_passchangeerr = "Erreur durant le changement de mot de passe.<BR><BR>";
$l_opt2_userintup = "L'interface utilisateur a été mis a jour.<BR><BR>";
$l_opt2_userintfail = "Erreur durant la mise à jour de l'interface utilisateur.<BR><BR>";
$l_opt2_chlang = "La langue a été changée pour [lang].<p>";
$l_opt2_chtemplate = "Modèle a été réglé sur [template]. <p>";
$l_opt2_dhtmlup = "Les paramètres de HTML dynamique ont été changés.<BR><BR>";
$l_opt2_dhtmlfail = "Erreur durant la mise à jour des paramètres DHTML.<BR><BR>";
$l_opt2_shipnamechanged = "NomExpédition changé à [name]. <BR><BR>";
$l_opt2_playernamechanged = "Nom du joueur devient [name] et [amount] crédits déduits de votre compte navire. <BR><BR>";
$l_opt2_mapwidth = "Locales et Galaxy Carte Largeur:";
?>
