<?php
$l_login_title			= "Connection";
$l_login_pw			= "Mot de passe:";
$l_login_chooseres		= "La résolution de votre écran n'a pu être déterminée. Veuillez choisir le plus près:";
$l_login_newp			= "Si vous êtes un nouveau joueur, cliquez <A HREF=\"new_player.php\">ici</A>.";
$l_login_prbs			= "Problèmes?";
$l_login_emailus		= "Écrivez nous";
$l_login_forgot_pw		= "Vous avez oublier votre mot de passe? Laissez le vide et apuyez sur connecter.";
$l_login_settings 		= "Paramètres de la partie";
$l_login_change			= "Changer";
$l_login_title2 = "Login pour les principales AATraders";
$l_login_reset1 = "Pas de réinitialisation Prévu";
$l_login_reset2 = "Prévu Reset:";
$l_login_reset3 = "Annexe Reset:";
$l_login_notice = "Avis important:";
$l_login_endadminnews = "Fin de l&#39;Admin Nouvelles";
$l_login_tourney_signup = "Tournoi Signups Enabled";

$l_login_profile_only = "Seul le profil";
$l_login_newclosed_message = "Nouvelle Signups Closed";
$l_login_tourneymode = "Tournoi en cours";
$l_login_tourneystarts = "Starts:";
?>
