<?php
$l_defense_deploy_title			="Déployer des intercepteurs & mines";
$l_defense_deploy_noturn		 	="Vous avez besoin d'au moins un tour pour déployer des défenses de secteur.";
$l_defense_deploy_nopermit		="Le déploiement de défenses dans ce secteur n'est pas permis.";
$l_defense_deploy_nodeploy		="Vous ne pouvez déployer ici. Un autre vaisseau ou alliance a déjà des défenses dans ce secteur.";
$l_defense_deploy_info1			="Vous êtes présentement dans le secteur [sector]. Il y a [mines] mines et [fighters] intercepteurs ici.";
$l_defense_deploy_info2			="Vous avez [mines] mines et [fighters] intercepteurs disponibles";
$l_defense_deploy_deploy			="Déployer";
$l_defense_deploy_deployed		="Deployés";
$l_defense_deploy_att			="Attaque";
$l_defense_deploy_notorps		="Vous n'avez pas suffisament de torpilles.";
$l_defense_deploy_nofighters		="Vous n'avez pas suffisament d'intercepteurs";
$l_defense_deploy_dmines			="Vous avez déployé [mines] mines.";
$l_defense_deploy_dfighter		="Vous avez déployé [fighters] intercepteurs.";
$l_defense_deploy_max_fighters = "Ce secteur peut prendre en charge un maximum de [amount] combattants.";
$l_defense_deploy_toomanyfighters = "Vous avez essayé de déployer des combattants plus que le secteur peut supporter.";
?>
