<?php
$l_novabomb_turns = "The Bomb Nouvelle exige atleast [turns] se tourne vers le feu.";
$l_novabomb_planetsdamaged = "Planètes endommagés par la bombe en Nouvelle -";
$l_novabomb_planet = "Planet [name] a subi des dommages de la bombe Nova.";
$l_novabomb_novaexplode = "Nouvelle bombe a explosé comme il a été congédié et votre navire a subi des dégâts considérables.";
$l_novabomb_novaexplode2 = "Nouvelle bombe a explosé comme il a été licencié et votre vaisseau a été détruit.";
$l_novabomb_notfedsec = "Nouvelle bombe peut pas être utilisée sur des secteurs appartenant à la Fédération.";
$l_novabomb_destroyed_planet = "Votre bombe nova craquage la surface de la planète et forés dans le noyau où il a explosé causant la planète à faire voler en éclats.";
$l_novabomb_wrongclass = "Cette classe de navire ne peut pas tirer un périphérique Nova Bomb.";
$l_novabomb_nonova = "Vous n&#39;avez pas une bombe en Nouvelle-installé.";
$l_novabomb_novamiss = "The Bomb Nouvelle manque de justesse, mais inflige des dégâts sur la planète.";
$l_novabomb_success = "Secteur [sector], a été bombardé Nova!";
$l_novabomb_mines = "Détruits [mines] le secteur des Mines.";
$l_novabomb_fighters = "Détruits [fighters] Fighters secteur.";
$l_novabomb_shipsdamaged = "Navires endommagés par la bombe en Nouvelle -";
$l_novabomb_ship_damage = "Starship [shipname] subi les dommages causés par la bombe Nova.";
$l_novabomb_ship_survived = "Votre navire a été assez loin quand la bombe a explosé Nova pour éviter tout dommage.";
?>
