<?php
$l_autoroute_missingwarp = "WarpLink suivante est manquant dans ce secteur. Warp déplacer avortés.";
$l_autoroute_SDabort = "Déplacez abandonnée en raison de défenses du secteur dans le secteur.";
$l_autoroute_turns = "Déduit [triptime] Active et a déménagé à [targetlink]";
$l_autoroute_noturns = "Vous êtes en dehors de tours.";
$l_autoroute_title = "Auto Routes";
$l_autoroute_id = "Route Auto ID";
$l_autoroute_start = "Route Auto Start";
$l_autoroute_destination = "Auto Route Destination";
$l_autoroute_warps = "Auto Route Warps";
$l_autoroute_deleteroute = "Supprimer l&#39;itinéraire";
$l_autoroute_info = "Cliquez sur Démarrer pour le secteur REALSPACE à ce secteur et commencer à déformer au secteur de destination.";
$l_autoroute_delete2 = "Supprimer des routes";
$l_autoroute_noroutes = "Non Auto Routes";
$l_autoroute_createroute = "Créer une nouvelle Auto Route";
$l_autoroute_deleted = "Auto Routes supprimé.";
$l_autoroute_return = "Retour au Menu Cliquez Auto Route";
$l_autoroute_created = "Auto Route a été créé.";
$l_autoroute_realmove = "Déplacer REALSPACE au secteur";
$l_autoroute_warpmove = "Warp se déplacer au secteur de la prochaine";
$l_autoroute_warpfinal = "Warp se déplacer au secteur de la finale";
$l_autoroute_editname = "Modifier le nom du";
?>
