<?php
$l_contact_admin_title = "Contactez l&#39;administrateur du jeu";
$l_contact_admin_thanks = "Merci pour votre commentaire.";
$l_contact_admin_email_alert = "S&#39;il vous plaît entrer une adresse email valide.";
$l_contact_admin_name_alert = "S&#39;il vous plaît entrer votre nom.";
$l_contact_admin_comment_alert = "S&#39;il vous plaît entrer vos commentaires.";
$l_contact_admin_name = "Nom";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Question / Commentaire";
$l_contact_admin_submit = "Soumettre des questions / commentaires";
$l_contact_admin_close = "Fermer la fenêtre";
$l_contact_admin_thanks_comment = "Merci pour votre commentaire ou question. Nous allons répondre à toute question et email vous avec notre réponse.";

?>
