main.php
done

// This is the base template list.  In an effort to cut down on database
// queries and load on the server this list was created.  This is a list of all the programs
// that should build the base full template data for this template.  Most templates will
// only need to use the main.php but ALL of the programs in the game can access the full
// template data if needed.  Do not add any program to this list unless you are going to use
// data that would be created by the base template function.