<?php
$l_autoroute_missingwarp = "Nästa warplink saknas i denna sektor. Warp flytta aborterade.";
$l_autoroute_SDabort = "Flytta Aborted grund Sektor försvaret i sektorn.";
$l_autoroute_turns = "Avdragen [triptime] Sätter och flyttade till [targetlink]";
$l_autoroute_noturns = "Du är ute varv.";
$l_autoroute_title = "Auto Rutter";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination = "Auto ruttdestination";
$l_autoroute_warps = "Auto Route trålvarpet";
$l_autoroute_deleteroute = "Ta bort rutt";
$l_autoroute_info = "Klicka på Start-sektorn att Realspace till denna sektor och börjar slå sig till destinationen sektorn.";
$l_autoroute_delete2 = "Radera Rutter";
$l_autoroute_noroutes = "Ingen Auto Rutter";
$l_autoroute_createroute = "Skapa ny Auto Route";
$l_autoroute_deleted = "Auto Rutter utgå.";
$l_autoroute_return = "Återgå till Auto ruttmenyn klicka";
$l_autoroute_created = "Auto Route har skapats.";
$l_autoroute_realmove = "Realspace flytta till sektor";
$l_autoroute_warpmove = "Warp flytta till nästa sektor";
$l_autoroute_warpfinal = "Warp flytta till sista sektorn";
$l_autoroute_editname = "Namnändring";
?>
