<?php
$l_news_title = "Universe News";
$l_news_info = "FNN är bland galaxens ledare <br> på nyheter och information leverans. <br> Bemannad 24 timmar, sju dagar i veckan med <br> engagerad personal i FNN Galaxy högkvarter <br> i Proxima Centauri och bureaus galaxywide!";
$l_news_for = "Nyheter för";
$l_news_prev = "gårdagen";
$l_news_next = "Dagen";
$l_news_none = "Tyvärr, inga nyheter idag.";
$l_news_flash = "Nyhetsrapporten";
$l_news_end = "Slut på nyheter";
$l_news_bestviewed = "Ses bäst i Opera, Safari och IE";
$l_news_fedannouncements = "Federation Announcements";
$l_news_planetarynews = "Planetary Nyheter";
$l_news_planetshipnews = "Planetary and Ship Nyheter";
$l_news_afteractionnews = "Efter åtgärder mot News";
?>
