<?php
$l_opt_title = "Välj en Avatar";
$l_opt_errorsize = "Fel: Din bild får inte vara större än 64x64 pixlar.";
$l_opt_errortype = "Fel: Bilden måste vara JPG, GIF eller PNG";
$l_opt_errornographic = "Fel: Inga grafik vald.";
$l_opt_currentavatar = "Din nuvarande Avatar";
$l_opt_uploadavatar = "Ladda upp en Avatar";
$l_opt_directory = "Välj Avatar Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Välj bild";
$l_opt_inuse = "Alla avatarer i denna katalog är i bruk.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
