<?php
$l_beacon_title = "Deploy Space Beacon";
$l_beacon_notpermitted = "Driftsätta utrymme beacons inom denna sektor är inte tillåten.";
$l_beacon_reads = "Present beacon läsningar";
$l_beacon_none = "Det finns för närvarande inte är en ledstjärna inom denna sektor.";
$l_beacon_enter = "Ange text för beacon";
$l_beacon_nowreads = "Beacon lyda";
$l_beacon_donthave = "Du har inte en plats ledstjärna.";
?>
