<?php
$l_shipyard_title = "Shipyard";
$l_planet = "Planet";
$l_ship_welcome = "Välkommen till din Planetary varv. Vi erbjuder för närvarande dessa modeller till salu.";
$l_ship_class = "TCLASS";
$l_ship_properties = "Klass Egenskaper";
$l_ship_current = "Nuvarande";
$l_ship_outstorage = "Ut Storage";
$l_ship_storagecost = "Lagringskostnad";
$l_ship_storagewarn = "När du tar din Pioneer ut lagringsutrymme du förlorar det du har utfärdats på din första fartyget förstörelse.";
$l_ship_levels = "Fartygsdelar Levels";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Pris";
$l_ship_turns = "Sätter bygga";
$l_ship_purchase = "Köpa";
$l_ship_stored = "Lagrade";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Genomsnitt Högsta Tech Nivå:";
$l_ship_averagenormaltech = "Genomsnittliga normalvärdet Tech Nivå:";
$l_ship_averagecurrenttech = "Genomsnittsström Tech Nivå:";
?>
