<?php
$l_warp_unlinked = "Målsektor ([target_sector]) har inte en länk från denna sektor.";
$l_warp_forbidtwo = "Använda en Warp för att ta bort en dubbelriktad koppling till sektorn [target_sector] är inte tillåtet.";
$l_warp_removed = "Länk flyttat till";
$l_warp_removedtwo = "Länk flyttat till och från";
$l_warp_nomoney = "Du har inte tillräckligt med krediter för att ta bort varp länken.";
$l_warp_noenergy = "Du har inte tillräckligt med energi för att ta bort varp länken.";
?>
