<?php
$l_s_yes = "Ja";
$l_s_no = "Nej";
$l_s_enabled = "Enabled";
$l_s_disabled = "Disabled";

$l_s_modules = "Moduler";
$l_s_modulename = "Modulnamn";
$l_s_moduleauthor = "Författare";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "Ingen Modules Loaded";

$l_s_gamestatus = "Spelstatus";
$l_s_allowpl = "Tillåt Spelare";
$l_s_allownewpl = "Tillåta nya spelare";

$l_s_gameoptions = "Spelinställningar";
$l_s_allowteamplcreds = "Tillåt Team Planet Credit Transfer";
$l_s_allowfullscan = "Tillåt Full Long Range Scan";
$l_s_sofa = "Tillåt Sub-Orbital Fighter Attacks";
$l_s_showpassword = "Display Lösenord på Registrering";
$l_s_genesisdestroy = "Genesis Torps kan förstöra planeter";
$l_s_igb = "Intergalactic Bank (IGB)";
$l_s_ksm = "Known Space Kartor";
$l_s_navcomp = "Navigation Computer";
$l_s_newbienice = "Newbie Nice";
$l_s_spies = "Spy System";
$l_s_spycapture = "Låt Spies att fånga planeter";

$l_s_gamesettings = "Spelinställningar";
$l_s_gameversion = "Game version:";
$l_s_minhullmines = "Minsta skrovstorlek behövs för att slå gruvor";
$l_s_averagetechewd = "Genomsnittet Tech nivå När Emergency Warp Bryts ned";
$l_s_numsectors = "Antal sektorer";
$l_s_maxwarpspersector = "Högsta Länkar per sektor";
$l_s_averagetechfed = "Högsta genomsnittliga tech nivå för Federation Sektorer";
$l_s_igbirateperupdate = "IGB Ränta per uppdatering";
$l_s_igblrateperupdate = "IGB utlåningsränta per uppdatering";
$l_s_techupgradebase = "Tech Level uppgradering av baser";
$l_s_collimit = "Kolonister Limit";
$l_s_maxturns = "Maximalt antal ackumulerade varv";
$l_s_maxplanetssector = "Maximalt antal planeter per sektor";
$l_s_maxtraderoutes = "Maximalt antal traderoutes per spelare";
$l_s_colreprodrate = "NYBYGGARE Nativitet";
$l_s_energyperfighter = "Enheten för energi som används per sektor fighter";
$l_s_secfighterdegrade = "Sector fighter nedbrytning procentsats";
$l_s_planetinterest = "Planet ränta";
$l_s_spiesperplanet = "Maximalt antal spioner per planet";
$l_s_spysuccessfactor = "Spy framgångsfaktor";
$l_s_spykillfactor = "Spy kill factor";
$l_s_colsperfighter = "Kolonister som behövs för att producera 1 Fighter varje tur";
$l_s_colspertorp = "Kolonister som behövs för att producera 1 Torpedo varje tur";
$l_s_colsperore = "Kolonister behövs för att producera 1 öre varje tur";
$l_s_colsperorganics = "Kolonister som behövs för att producera 1 Organics varje tur";
$l_s_colspergoods = "Kolonister som behövs för att producera 1 Varor varje tur";
$l_s_colsperenergy = "Kolonister som behövs för att producera 1 Energi varje tur";
$l_s_colspercreds = "Kolonister som behövs för att producera 1 poäng vardera tur";
$l_s_colsper = "Kolonister som behövs för att producera 1 [commodity] varje tur";

$l_s_gameschedsettings = "Game Scheduler Settings";
$l_s_schedtype = "Scheduler Type";
$l_s_cronbased = "Cron Based";
$l_s_playertriggered = "Spelare Triggered";
$l_s_minutes = "minuter";
$l_s_ticksupdate = "Ticks hända varje";
$l_s_turnsupdate = "Sätter hända kommer alla";
$l_s_npcupdate = "Alliansen kommer att spela varje";
$l_s_igbturnsupdate = "Intressen IGB konton kommer att ackumuleras varje";
$l_s_newsupdate = "Nyheter kommer att genereras varje";
$l_s_planetupdate = "Planets genererar produktion varje";
$l_s_spyupdate = "Spioner agerar varje";
$l_s_portsupdate = "Hamnar genereras varje";
$l_s_towupdate = "Fartygen kommer att bogseras från Fed sektorer varje";
$l_s_scoreupdate = "Rankings skapas varje";
$l_s_secdefdegrupdate = "Sector försvar försämrar varje";
$l_s_apocalypseupdate = "Planetariska apokalyps kommer att inträffa varje";
$l_s_release_version = "Spelsläppet version";
$l_s_time_since_reset = "Tid sedan senaste nollställningen";
$l_s_independence = "Planetary Independence";
$l_s_dignitaryupdate = "Dignitärer kommer att agera varje";

$l_s_turnsupdate = "gör varje";
?>
