<?php
// port.php port_purchase.php
$l_trade = "Handel";
$l_title_port = "Port Trading";
$l_title_trade = "Trading Commodities";
$l_sector_war = "War embargo";
$l_war_info = "Kriget rasar i denna sektor. Du kan inte nå hamnen genom alla fientliga krafter.";
$l_no_trade = "Handel förbjuden";
$l_no_trade_out = "Handel vid denna hamn är inte tillåtet för utomstående";
$l_no_trade_info = "Handel vid denna hamn är inte tillåtet";
$l_buying = "Köpa";
$l_selling = "Selling";
$l_commodity = "Commodity";
$l_amount = "Belopp";
$l_price = "Pris";
$l_buy = "Köpa";
$l_sell = "Sälja";
$l_trade_st_info = "Du har [free_holds] tomma lastutrymmen kan bära [free_power] mer energi enheter, och har [credits] krediter.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Inte tillräckligt med krediter";
$l_creds_to_spend = "Du har [credits] krediter att spendera.";
$l_cost = "Kostnad";
$l_avail = "Tillgänglig";
$l_profit = "Resultat";
$l_current = "Nuvarande";
$l_current_level = "Nuvarande nivå";
$l_current_qty = "Aktuella Kvantiteter";
$l_max = "Max";
$l_ifyouneedmore = "Om du behöver mer du kan få tillgång till denna hamns [igb]";
$l_ifyouneedplan = "Tillgång planetens";
$l_igb_term = "IGB Banking Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Obegränsad";
$l_full = "Full";
$l_equipped = "Utrustad";
$l_n_a = "n / a";
$l_item = "Artikel";
$l_totalcost = "Totalkostnad";
$l_would_dump = "Om du vill dumpa alla dina kolonister här, klicka på";
$l_noport = "Det finns ingen hamn här!";
$l_trade_turnneed = "Du behöver minst en tur till handel på en hamn eller planet.";
$l_returnto_port1 = "här";
$l_returnto_port2 = "Klicka på [port_link] för att återgå till hamnen menyn.";
$l_notenough_cargo = "Du har inte tillräckligt med lastutrymmen för de varor du vill köpa.";
$l_notenough_power = "Du har inte tillräckligt med ström för lagring av den energi du vill köpa.";
$l_notenough_credits = "Du har inte tillräckligt med krediter för att slutföra transaktionen.";
$l_notenough_turns = "Du har inte tillräckligt vänder slutföra transaktionen.";
$l_trade_result = "Resultat för denna handel";
$l_trade_complete = "Handel avslutad";
$l_trade_upgraded = "Uppgraderas till nivå";
$l_trade_added = "la";
$l_trade_installed = "installerade";
$l_port_bounty = "Du kan inte komma åt en speciell port medan du har en bounty på dig omhändertagits av federationen. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Du har inte tillräckligt credtis betala bounty på [amount] krediter. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "Den IGB har utfärdat en inlåst på ditt skepp pga ett sent lån betalning. Du kan inte byta till en särskild hamn tills du betalar tillbaka ditt lån.";
$l_port_returntospecial = "att återgå till leverans depån.";
$l_toprobemenu = "att gå till sonden menyn.";
$l_ports_shiplimit = "Minsta Ship klass att montera enheten:";
$l_ports_needrepair = "Reparation";

$l_ports_needcredits = "Du har inte tillräckligt med krediter för denna transaktion. Den totala kostnaden är";
$l_ports_needcredits1 = "krediter och du bara har";

$l_ports_tradeforbidden = "Handel förbjuden";
$l_ports_nooutsiders = "Handel vid denna hamn är inte tillåtet för utomstående.";

$l_bought = "Du köpte";
$l_sold = "Du sålde";
$l_notenough_commodity = "Du har inte tillräckligt [commodity] för att slutföra transaktionen.";
$l_exceed_commodity = "Antal [commodity] större än tillgången och efterfrågan.";
$l_port_shiptoolarge = "Ditt skepp är för stor för handeln på denna port.";

$l_port_hold_unit = "Rymmer per enhet";


$l_port_welcome = "Port [sectorname] Välkommen&#39;s [player]";
$l_port_amountforsale = "Hamnen har [amount] enheter [commodity] till försäljning [credits] Poäng per enhet.";
$l_port_holdsperunit = "[holds] lastrum behövs per enhet.";
$l_port_howmanypurchase = "Hur många [commodity] enheter vill du köpa?";
$l_port_unitstobuy = "Enheter till Köp";
$l_port_shipcarryingbuy = "Din fartyget medför [shipunits] enheter [commodity]. Du kan köpa [buyunits] enheter med tillgängliga lastrummet utrymme.";
$l_port_howmanysell = "[amount] enheter [commodity] @ [credits] Poäng per enhet.";
$l_port_unitstosell = "Enheter säljer";
$l_port_perform = "Utför Transaction";
$l_port_cargoholds = "Lastrummen";

?>
