<?php
$l_novabomb_turns = "Nova Bomb kräver atleast [turns] blir till eld.";
$l_novabomb_planetsdamaged = "Planeter skadas av Nova Bomb";
$l_novabomb_planet = "Planet [name] har lidit skada från Nova Bomb.";
$l_novabomb_novaexplode = "Nova Bomb exploderade som avlossades och ditt skepp har lidit stor skada.";
$l_novabomb_novaexplode2 = "Nova Bomb exploderade som avlossades och ditt skepp förstördes.";
$l_novabomb_notfedsec = "Nova Bomb kan inte användas på federationen ägs sektorer.";
$l_novabomb_destroyed_planet = "Din nova bomb spruckna ytan på planeten och borrade i kärnan där den exploderade orsakar planeten splittras.";
$l_novabomb_wrongclass = "Detta fartyg klass kan inte avfyra en Nova Bomb enhet.";
$l_novabomb_nonova = "Du har inte en Nova Bomb installerad.";
$l_novabomb_novamiss = "Nova Bomb missar snävt men förorsakar skada på planeten.";
$l_novabomb_success = "Sector [sector] har Nova bombat!";
$l_novabomb_mines = "Förstörda [mines] sektor Mines.";
$l_novabomb_fighters = "Förstörda [fighters] Fighters sektor.";
$l_novabomb_shipsdamaged = "Fartyg skadas av Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] lidit skada från Nova Bomb.";
$l_novabomb_ship_survived = "Ditt skepp var tillräckligt långt borta när Nova Bomb exploderade att undvika skador.";
?>
