<?php
$l_warp_cantsame = "Du kan inte skapa en länk när källan är densamma som destination.";
$l_warp_twoerror = "Använda en Warp Editor för att skapa en ömsesidig koppling till sektorn [target_sector] är inte tillåtet.";
$l_warp_sectex = "Kan inte skapa varp länk från nuvarande sektor - det skulle överstiga den högsta av $ link_max per sektor.";
$l_warp_linked = "Målsektor ([target_sector]) har redan en länk från denna sektor.";
$l_warp_coneway = "Link skapade en väg till";
$l_warp_ctwoway = "Länk skapade till och från";
$l_warp_nomoney = "Du har inte tillräckligt med krediter för att skapa varp länken.";
$l_warp_noenergy = "Du har inte tillräckligt med energi för att skapa varp länken.";
?>
