<?php
$l_cu_storing = "Förvaring";
$l_cu_inistored = "<b>Alla ini värden har framgångsrikt lagrats.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto ruttdestination";
$l_cu_warps = "Auto Route trålvarpet";
$l_cu_deleteroute = "Ta bort rutt";
$l_cu_info = "Klicka på Start-sektorn att Realspace till denna sektor och börjar slå sig till destinationen sektorn.";
$l_cu_delete2 = "Radera Rutter";
$l_cu_noroutes = "Ingen Auto Rutter";
$l_cu_createroute = "Skapa ny Auto Route";
$l_cu_deleted = "Auto Rutter utgå.";
$l_cu_return = "Återgå till Auto ruttmenyn klicka";
$l_cu_created = "Auto Route har skapats.";
$l_cu_realmove = "Realspace flytta till sektor";
$l_cu_warpmove = "Warp flytta till nästa sektor";
$l_cu_warpfinal = "Warp flytta till sista sektorn";
?>
