<?php
$l_die_title = "Självförstörande";
$l_die_rusure = "Är du säker på att du vill förstöra ditt skepp? Detta tar bort dig från spelet.";
$l_die_goodbye = "Goodbye Cruel galaxen!";
$l_die_check = "Är du säker på att du vill ta bort dig från spelet?";
$l_die_nonono = "NEJ! NEJ! NEJ!";
$l_die_what = "Vad tänkte jag på?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Du fartyg och alla ombord har förgasas.";
$l_die_please1 = "logout";
$l_die_please2 = "Please, [logout_link]";
$l_die_exploit = "Lek inte med det du inte förstår.";
?>
