<?php
$l_opt_title = "Välj en Team Icon";
$l_opt_errorsize = "Fel: Din bild får inte vara större än 64x64 pixlar.";
$l_opt_errortype = "Fel: Bilden måste vara JPG, GIF eller PNG";
$l_opt_errornographic = "Fel: Inga grafik vald.";
$l_opt_currentavatar = "Din nuvarande Team Icon";
$l_opt_uploadavatar = "Upp en ikon";
$l_opt_directory = "Välj Team Icon Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Select Team Icon";
$l_opt_noteam = "Du är inte på ett lag.";
$l_opt_notleader = "Endast Team Coordinator kan ändra Team Icon.";
$l_opt_inuse = "Alla Team Symboler i denna katalog är i bruk.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
