<?php
$l_artifact_title = "Hämta Artefakt";
$l_artifact_list_title = "Lista över Förvärvade Artifacts";
$l_artifact_noscan = "Din skannrar kunde inte hitta artefakt.";
$l_artifact_noturn = "Du har inte tillräckligt vänder för att plocka upp denna artefakt.";
$l_artifact_classname = "Artefakt Namn";
$l_artifact_description = "Artefakt Beskrivning";
$l_artifact_imagename = "Artefakt Bild";
$l_artifact_incomplete = "Artefakt Pieces";
$l_artifact_process = "Använd Completed Artefakt";

?>
