<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Du behöver minst 1 tur att bygga en bas";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "Nova Bomb missar snävt men förorsakar skada på planeten.";
$l_planet_novaturns = "Nova Bomb kräver atleast [turns] blir till eld.";
$l_planet_novafed = "Nova Bomb får ingen ström i federationen sektorer.";
$l_planet_nonova = "Du har inte en Nova Bomb installerad.";
$l_planet_firenova = "Fire Nova Bomb";
$l_planet_novaexplode = "Nova Bomb exploderade som avlossades och ditt skepp har lidit stor skada.";
$l_planet_novaexplode2 = "Nova Bomb exploderade som avlossades och ditt skepp förstördes.";
$l_planet_noautotrade = "Auto handelsväg som inte för den här planeten.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] i hamn [dest_id]";
$l_planet_autotradedelete = "Radera bilhandeln.";
$l_planet_autotradeadd = "Skapa bilhandeln.";
$l_planet_tradedeleted = "Bilhandeln Resan utgår.";
$l_planet_tradeadded = "Ny Auto handelsväg Added.";
$l_planet_autotype = "Markera objektet handel";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Du måste köpa ett fraktfartyg för den här planeten innan du kan ställa in en automatisk handelsväg.";
$l_planet_purchasecargo = "Om du vill köpa ett lastfartyg";
$l_planet_upgradecargo = "Om du vill uppgradera din Cargo Ship";

$l_planet_cargocapacity = "Kapacitet:";
$l_planet_cargoowned = "Du äger redan ett lastfartyg för den här planeten.";
$l_planet_cargoshipbuy = "Inköp Cargo Ship";
$l_planet_cargoshipupgrade = "Upgrade Cargo Ship";
$l_planet_cargoatmax = "Din lastfartyg är högst uppgraderingen nivå.";
$l_planet_cargoshipbuyinfo = "Välj ett förinställt Cargo Ship";
$l_planet_cargoshipupgradeinfo = "Uppgradera din Lastfartyg Hull.";
$l_planet_cargoshipbuildinfo = "Bygg din egen Cargo Ship";
$l_planet_tradehelp = "1. Du kan ange ett handels-port för varje typ av råvara. <br> 2. Du kan inte byta en vara i en hamn som säljer samma vara. <br> Handla med varor på en Varor Port, malm vid en Ore Port, ect. kommer att göra ingenting. <br> 3. Om du inte vill handla vissa varor bara ange 0 för hamnsektorn.";
$l_planet_cargocredits = "Auto Trade Credits Received:";
$l_planet_cargonoown = "Du måste äga planeten att skapa en automatisk Traderoute.";
$l_planet_digtrans = "Transfer dignitär";
$l_planet_nocredits1 = "Du har inte tillräckligt med krediter för denna transaktion. Den totala kostnaden är";
$l_planet_nocredits2 = "krediter och du bara har";
$l_planet_nobase = "Du måste ha en bas för att hantera planeten försvaret nivåer.";
$l_planet_genesisnoturn = "Du behöver minst 1 tur att använda Genesis Device på planeten.";
$l_planet_nogenesis = "Du behöver en Genesis enhet att förstöra en planet.";
$l_planet_wrongclass = "Detta fartyg klass kan inte avfyra en Nova Bomb enhet.";

$l_planet_combatpreview = "Combat Preview";
$l_planet_beamfire1 = "Ditt angrepp har upptäckts. Planetary Balkar skjuta! Ökad Beam Fire som ditt fartyg kommer in alltför nära planeten att lansera fighters.";
$l_planet_beamfire2 = "Ditt angrepp har upptäckts. Planetary Balkar skjuta! Omfattande brand ränta från planeten som Beam Batterier lås för flera hits!";
$l_planet_beamfire3 = "Ditt angrepp har upptäckts. Planetary Balkar skjuta! Beam Batterier över hela planeten är låsning på för massiv flera eld! Beam eld mycket högre än beräknat!";
$l_planet_beamfire4 = "Ditt angrepp har upptäckts. Planetary Balkar skjuta! Beam försvar kan bara låsa den för en bränning pass.";

$l_planet_sofanobeamsshields = "inte skjuter balkar på din sköldar.";
$l_planet_sofanobeamsarmor = "inte skjuter balkar på din rustning.";
$l_planet_flauncherfailed1 = "Din fighter lansera systemet har skadats.";
$l_planet_flauncherfailed2 = "Du har bara kunnat lansera";
$l_planet_flauncherfailed3 = "procent av din krigare.";
$l_planet_nodfightertofighter = "sänder inte någon fighters att attackera din krigare.";
$l_planet_nodfightertotorp = "sänder inte någon fighters att attackera din Torps.";
$l_planet_flauncherfailed3 = "procent av din krigare.";
$l_planet_autotradetype = "- [source_type] i hamn [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "attackerar";
$l_planet_iminsector = "i sektor";
$l_planet_imnova = "använder en Nova Enheten";
$l_planet_imsofa = "är SOFA Bombing";
$l_planet_team = "Denna planet ägs av en lagkompis och du inte har behörighet att komma åt informationen för den här planeten.";
?>
