<?php
$l_ship2_buytitle = "Att köpa ett nytt fartyg";
$l_ship2_storetitle = "Shipyard lagringsanläggning";
$l_ship2_wrongclass = "Fel fartyg klass specificeras";
$l_ship2_buying = "Du köper:";
$l_ship2_tradein = "Trade I:";
$l_ship2_value = "Nuvarande Ship Värde:";
$l_ship2_newvalue = "New Ship Värde:";
$l_ship2_totalcost = "Total Insats:";
$l_ship2_nomoney = "Du har inte tillräckligt med krediter för att köpa fartyget.";
$l_ship2_purchase = "Köpa";
$l_ship2_buynstore = "Köpa nya fartyg och lagra gamla";
$l_ship2_nomoney2 = "Du har inte tillräckligt med krediter för att slutföra transaktionen.";
$l_ship2_paystorage = "Din har tagit bort ditt skepp från lagret.";
$l_ship2_turns = "Du behöver minst [turns] visar att utföra denna åtgärd";
$l_ship2_error = "Internt fel. Kan inte hitta fartyg klass.";
$l_ship2_owned = "Du redan äger denna modell av fartyget.";
$l_ship2_shipbought = "Du har precis köpt ett nytt fartyg!";

?>
