<?php
$l_opt2_title = "Sparalternativ";
$l_opt2_passunchanged = "Lösenord lämnades oförändrad. <BR><BR>";
$l_opt2_srcpassfalse = "Original lösenord felaktigt. Lösenord lämnades oförändrad. <BR><BR>";
$l_opt2_newpassnomatch = "Nytt lösenord fält matchar inte. Lösenord lämnades oförändrad. <BR><BR>";
$l_opt2_passchanged = "Lösenordet är ändrat. <BR><BR>";
$l_opt2_passchangeerr = "Fel vid ändring av lösenord <BR><BR>";
$l_opt2_userintup = "Användargränssnitt Fastställa uppdaterade. <BR><BR>";
$l_opt2_userintfail = "Misslyckades med att uppdatera inställningen användargränssnitt. <BR><BR>";
$l_opt2_chlang = "Språket har varit inställd på [lang]. <p>";
$l_opt2_chtemplate = "Mall har satts till [template]. <p>";
$l_opt2_dhtmlup = "Dynamisk html Fastställa uppdaterade. <BR><BR>";
$l_opt2_dhtmlfail = "Misslyckades med att uppdatera dynamisk html inställning. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname bytt till [name]. <BR><BR>";
$l_opt2_playernamechanged = "Spelare namnändrat till [name] och [amount] krediter dras från ditt skepp konto. <BR><BR>";
$l_opt2_mapwidth = "Lokala och Galaxy Karta Bredd:";
?>
