<?php
///SPIES
$l_spy_title = "Spy Meny";
$l_spy = "Spioner";
$l_spy_disabled = "Spioner är handikappade!";
$l_spy_noturn = "Du behöver minst en tur för att skicka en spion till en planet.";
$l_spy_notonboard = "Du har inga spioner ombord.";
$l_spy_ownplanet = "Du kan inte skicka en spion till din egen planet.";
$l_spy_unownedplanet = "Du kan inte skicka en spion till herrelösa planet.";
$l_spy_planetfull = "Det finns redan möjlighet [max] spionerar på denna planet.";
$l_spy_sendtitle = "Skicka en spion [spyID] till planet: <BR> Välj spy uppdrag:";
$l_spy_type1 = "Spionen fungerar endast på denna planet.";
$l_spy_type2 = "Spionen försöker infiltrera ett fartyg som utför en planetarisk överföring.";
$l_spy_type3 = "Spionen försöker infiltrera ett fartyg som utför en planetarisk överföring och sedan infiltrera till en annan planet.";
$l_spy_sendbutton = "Skicka till planet";
$l_spy_sendsuccessful = "Din spionera infiltrerar planet och väntar på rätt tillfälle att starta verksamhet.";
$l_spy_sendfailed = "Planet givare upptäcks din spion, eftersom din Cloak enheten inte kan omfatta honom. Din Spy dödas.";
$l_spy_noturn2 = "Du behöver minst en tur ringa upp en spion.";
$l_spy_confirm = "Är du säker på att du vill ringa upp din spion [spyID]?";
$l_spy_cleanupplanet = "att städa upp planeten från fiendens spioner.";
$l_spy_cleanupship = "Om du vill rensa ditt skepp från fiendens spioner, klicka";
$l_spy_yourspies = "Din spioner på denna planet";
$l_spy_sendnew = "Skicka ett nytt spion";

$l_spy_codenumber = "Kod";
$l_spy_job = "Jobb";
$l_spy_percent = "Procent";
$l_spy_move = "Movement";
$l_spy_action = "Action";
$l_spy_shipowner = "Fartygsägaren";
$l_spy_shipname = "Fartygsnamn";
$l_spy_shiptype = "Ship tCLASS";
$l_spy_shiplocation = "Ship Location";
$l_spy_planetowner = "Planet Ägare";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "Rör sig inte";
$l_spy_moves['toship'] = "Leverera";
$l_spy_moves['toplanet'] = "Till planet";

$l_spy_comeback = "Call back";
$l_spy_nospieshere = "Du har inte någon spionerar på denna planet!";
$l_spy_transferred = "spioner överförda";
$l_spy_backonship = "Spionen är nu på ditt skepp.";
$l_spy_backfailed = "Ring inte tillbaka.";
$l_spy_changetitle = "Ändra spionera [spyID] egenskaper:";
$l_spy_occupied = "Din spionera [spyID] har använts som [job], med procent [percent].";
$l_spy_dismiss = "Ogilla spion?";
$l_spy_changebutton = "Ändra";
$l_spy_changejob = "Byta jobb eller rörelser";
$l_spy_linkback = "att gå till Spy menyn.";
$l_spy_changed1 = "Movement förändrats.";
$l_spy_changed2 = "Spy ogillas och hans rörelse förändrats.";
$l_spy_changefailed = "Ändra misslyckades.";
$l_spy_cleanupplanettitle = "Rensa upp din planet från fiendens spioner:";
$l_spy_notyourplanet = "Det är inte din planet.";
$l_spy_cleanuptext[1] = "Fast cleanup. Använder [creds] krediter och [turns] varv.";
$l_spy_cleanuptext[2] = "Bättre cleanup. Använder [creds] krediter och [turns] varv.";
$l_spy_cleanuptext[3] = "Det bästa cleanup. Använder [creds] krediter och [turns] varv.";
$l_spy_cannotcleanupplanet = "Du har bara [credits] Poäng på denna planet och [turns] varv.";
$l_spy_cleanupbutton1 = "Börja städa upp planeten";
$l_spy_cleanupplanettitle2 = "Du slagit på Sensorer för att hitta fiendens spioner på denna planet.";
$l_spy_spyfoundonplanet = "Du hittade en [player] &#39;s spion [spyID] på planeten. Du dödade den spion.";
$l_spy_spynotfoundonplanet = "Du har inte hittat någon fiende spionerar på denna planet.";
$l_spy_notenough = "Du har inte tillräckligt med krediter eller vänder börja cleanup.";

$l_spy_cleanupshiptitle = "Rensa upp ditt skepp från fiendens spioner:";
$l_spy_notinspecial = "Du måste vara en produkt hamn för att rensa upp ditt skepp.";
$l_spy_cleanupshiptext[1] = "Fast cleanup. Använder [creds] krediter och [turns] varv.";
$l_spy_cleanupshiptext[2] = "Bättre cleanup. Använder [creds] krediter och [turns] varv.";
$l_spy_cleanupshiptext[3] = "Det bästa cleanup. Använder [creds] krediter och [turns] varv.";
$l_spy_cannotcleanupship = "Du har bara [credits] Poäng och [turns] varv.";
$l_spy_cleanupbutton2 = "Börja städa upp ditt skepp";
$l_spy_cleanupshiptitle2 = "Du slagit på Sensorer för att hitta fiendens spioner på ditt skepp.";
$l_spy_spyfoundonship = "Du hittade en [player] &#39;s spion [spyID] på ditt skepp. Du dödade den spion.";
$l_spy_spynotfoundonship = "Du har inte hittat någon fiende spionerar på ditt skepp.";

$l_spy_infodeleted = "Meddelande borttaget";
$l_spy_infonotyours = "Det är inte ditt meddelande.";
$l_spy_noinfo = "Din spionerar på fiendens fartyg har inte avslöja något ännu.";
$l_spy_infotitle = "Din spioner har upptäckt följande information";
$l_spy_time = "Tid";
$l_spy_type = "Typ";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Det finns en [player] Planet [planet] inom sektorn [sector].";
$l_spy_delete = "Ta bort";
$l_spy_messages = "att se vad dina spioner har upptäckts.";
$l_spy_defaulttitle1 = "Spionerar på fiendens fartyg";
$l_spy_defaulttitle2 = "Spionerar på fiendens planeter";
$l_spy_defaulttitle3 = "Spionerar på din planeter";
$l_spy_defaulttitle4 = "Spionerar på ditt skepp";

$l_spy_no1 = "Du har inte någon spionerar på fiendens fartyg.";
$l_spy_no2 = "Du har inte någon spionerar på fiendens planeter.";
$l_spy_no3 = "Du har inte någon spionerar på dina planeter.";
$l_spy_no4 = "Du har inte någon spionerar på ditt skepp.";
$l_spy_nospiesatall = "Du har inga spioner.";
$l_spy_notknown = "Okänd";


$l_spy_trytitle = "På planeten detta spion kommer att försöka";

$l_spy_cantsendfeds = "Sorry but Spies kan inte skickas till förbundet eller Independent Planets.";
$l_spy_cantsendteam = "Du kan inte placera Spioner på en lagkamrater planet.";
$l_spy_messagesdeleted = "Alla raderade meddelanden";
$l_spy_deleteall = "Radera alla";
$l_spy_onplanet = "Spionerar på planet";
$l_spy_menu = "att återgå till Spy Meny.";
?>
