<?php
$l_opt_title = "Options";
$l_opt_chpass = "Byt lösenord";
$l_opt_curpass = "Nuvarande lösenord:";
$l_opt_newpass = "Nytt lösenord:";
$l_opt_newpagain = "Nytt lösenord (igen):";
$l_opt_userint = "Användargränssnitt";
$l_opt_usenew = "Använd nya layout?";
$l_opt_lang = "Språk";
$l_opt_template = "Mall";
$l_opt_select = "Select One:";
$l_opt_enabled = "Enabled";
$l_opt_save = "Spara";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Lokala och Galaxy Karta Bredd:";
$l_opt_profiletitle = "Profil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registrerats med Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "När du registrerar din spelare på en annan server mallen shoutbox och inställningar nyheter ovan kommer att användas på servern.";
$l_opt_showshoutbox = "Visa Shoutbox:";
$l_opt_shownewscrawl = "Visa Nyhetssökning:";
$l_opt_playername = "Spelarnamn:";
$l_opt_playernamecost = "Federation Namnändring Avgift: [amount] Poäng";
?>
