<?php
$l_zi_title = "Zoninformation";
$l_zi_nexist = "Detta avsnitt av utrymmet finns inte!";
$l_zi_feds = "Federation";
$l_zi_traders = "Alliance Space";
$l_zi_nobody = "Nobody";
$l_zi_war = "Ifrågasatta space";
$l_zi_allow = "Tillåten";
$l_zi_notallow = "Inte tillåtet";
$l_zi_limit = "Begränsad till ägare och allierade";
$l_zi_ul = "Obegränsad";
$l_zi_control = "Du har kontroll över detta område";
$l_zi_tochange = "att ändra sina lagar.";
$l_zi_owner = "Zone ägare";
$l_zi_maxhull = "Högsta genomsnittliga tech nivå som tillåts";
?>
