<?php
$l_md_title = "Sector försvar";
$l_md_invalid = "Ogiltig Sector försvar";
$l_md_nolonger = "Sektorn försvar valt finns inte längre där.";
$l_md_you = "du";
$l_md_bmines = "Din balkar förstöras";
$l_md_msgdownerb = "[name] förstöras [mines] gruvor inom sektorn [sector].";
$l_md_retr = "Du hämtas";
$l_md_consist = "Denna sektor försvar består av [qty] [type] ägs av [owner].";
$l_md_youcan = "Du kan";
$l_md_retrieve = "";
$l_md_attack = "Attack";
$l_md_attdef = "Angripa Sector försvar. Alla sektor fighters kommer att vidta motåtgärder.";
$l_md_noturn = "Du behöver minst ett varv.";
$l_md_nothere = "Du måste vara i samma sektor som sektorn försvar.";
$l_md_notyours = "Åtgärden inte tillåtet. Dessa sektor försvar inte tillhör dig.";
$l_md_yours = "Du kan inte attackera din egen sektor försvar.";
?>
