<?php
$l_login_sclosed = "Server Stängt";
$l_login_closed_message = "Server stängt tills vidare.";
$l_login_title2 = "Login Fas två";
$l_login_banned = "<b>Du har förbjudits från detta spel av administratören. Du är inte längre välkommen att spela på den här servern. Nästa gång, beter sig.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "På grund av allvaret i detta brott och den våldsamma attacken mot dig, har förbundet beslutat nådigt att ge en gratis kloning från din kvarstår. Tråkigt nog, även i vår tid, kan nya kloner inte egen egendom, bortsett från grunderna till att försörja sig. Du kommer att få en grundläggande fartyg och några krediter för att komma igång. Förhoppningsvis ditt nästa liv blir bättre.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Du hade ingen flykt pod, och på grund av din blygsam framgång i detta liv, avstår förbundet att klona dig. Din fortfarande bör så småningom hamnar i en allvarlig väl, förhoppningsvis användas för att skapa liv någon annanstans ... flera miljarder år. <BR><BR> Bättre lycka nästa omgång ...";
$l_login_4gotpw1 = "Lösenordet du angav är felaktig. <BR><BR> Om du har glömt ditt lösenord,";
$l_login_4gotpw2 = "ha den e-post till dig. <BR><BR> Annorlunda,";
$l_login_4gotpw3 = "att försöka igen. Försök loggas med IP-adress";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Du har dött i en hemsk olycka.";
$l_login_blackbox = "är blackbox information som hämtas från dina skepp vraket.";
$l_new_login = "att gå till inloggningssidan.";
$l_login_playerlimit = "Servern har nått det maximala antalet spelare den stöder. Prova att logga in vid ett senare tillfälle.";
?>
