<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Välkommen till Casino erbjuder vi för närvarande följande spel och Facilities";
$l_casino_option = "&quot;Rum";
$l_casino_detail = "&quot;Beskrivning";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "Stå";
$l_hit = "Hit";
$l_firsthand = "&quot;First Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Försäkring";
$l_doubledown = "Dubbla";
$l_lobby = "Lobby";
$l_split = "Dela";
$l_credits = "Credits";
$l_yourbet = "&quot;Your Bet";
$l_nobet = "&quot;Din insats har överskridit kreditgränsen, vänligen satsning igen.";
$l_dealerwins = "Dealern vinner!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer Loses!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Spelaren vinner!";
$l_playerbust = "&quot;Player byster!";
$l_playerloses = "&quot;Förlorar spelaren!";
$l_playerblackjack = "&quot;Player BlackJack!";
$l_place_bet = "&quot;Satsa";
?>
