<?php
$l_move_title = "Flytta";
$l_move_turn = "Du behöver minst ett varv för att flytta.";
$l_move_failed = "Flytta misslyckades!";
$l_rs_title = "RealSpace Flytta";
$l_rs_whichsector = "Vilken sektor vill du nå genom RealSpace?";
$l_rs_insector = "Du är för närvarande inom sektorn [sector] - och det finns sektorer finns från 1 till [sector_max].";
$l_rs_submit = "Compute";
$l_rs_movetime = "Med din motorer, kommer det att ta [triptime] visar att fullfölja resan.";
$l_rs_energy = "Du skulle samla [energy] energienheter";
$l_rs_noturns = "Du har inte tillräckligt svänger vänster, och kan inte slå in på denna resa.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "Du har [turns] varv. [engage] motorer?";
$l_rs_invalid = "Du kan inte realspace på denna sektor härifrån.";
$l_rs_ready = "Du är nu i sektorn [sector]. Du använde [triptime] varv, och fick [energy] energi enheter.";
$l_warp_invalid = "Du kan inte varpen på denna sektor härifrån.";
$l_move_unknown = "Okänd Movetype";
?>
