<?php
$l_sn_title = "Sector Notes";
$l_sn_pntitle = "Sektorer med personliga anteckningar";
$l_sn_tntitle = "Sektorer med Team Notes";
$l_sn_psntitle = "Personlig Sector Notes";
$l_sn_tsntitle = "Team Sector Notes";
$l_sn_editnote = "Edit Sector Anmärkning:";
$l_sn_deleteedit = "Bort eller redigera:";
$l_sn_addnote = "Lägg Sector Anmärkning:";
$l_sn_list = "Lista Sektorer Notes";
$l_sn_listts = "Lista Sektorer med Team Notes";
$l_sn_addteam = "Lägg Team";
$l_sn_deleteteam = "Radera Team";
$l_sn_delete = "Ta bort";
$l_sn_saveteam = "Spara Team";
$l_sn_deletepersonal = "Utplåna personuppgifter";
$l_sn_addpersonal = "Lägg till personlig";
$l_sn_savepersonal = "Spara personlig";
$l_sn_editpersonal = "Redigera personlig";
$l_sn_editteam = "Edit Team";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Typ";
$l_sn_hdowner = "Ägare / Team";
$l_sn_hdplanets = "Planets";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mines";
$l_sn_hdscanfrom = "Skanna från";
$l_sn_hddetail = "Detalj";
$l_sn_hddate = "Datum / tid";
$l_sn_hddelete = "Ta bort";
$l_sn_hdteam = "Team";
$l_sn_view = "Visa";
$l_sn_no = "Nej";
$l_sn_yes = "Ja";
$l_sn_nonotes = "Ingen sektor Notes Found";

?>
