<?php
$l_mail_title = "Mail Lösenord";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Lösenord har skickats till";
$l_mail_topic = "$ game_name Lösenord";
$l_mail_message = "Hälsningar, \ n \ nSomeone från IP-adressen $ ip begärt att lösenordet för $ game_name skickas till dig \ n \ nDin lösenord är: [pass] \ n \ nMed vänliga hälsningar \ n \ nDet $ game_name webbteam.";
$l_new_login = "att gå till inloggningssidan.";
$l_mail_failed = "Lösenord kunde inte skickas till";
?>
