<?php
$l_shout_title = "Banner_klimatshop";
$l_shout_title2 = ".:: SHOUTBOX::.";
$l_shout_public = "Public";
$l_shout_team = "Team";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "annan";
$l_shout_refresh = "Uppdatera";
$l_shout_close = "Stäng fönstret";
$l_shout_saved = "Shout sparats!";
$l_shout_return = "Återgå till";
$l_shout_prev = "Föregående";
$l_shout_next = "Nästa";
$l_shout_selectpage = "Välj sida";
$l_shout_page = "Sida:";
$l_shout_teamtitle = ".:: TEAM SHOUTBOX::.";
?>
