<?php
// New News Items

$l_news_planets = "planeter";
$l_news_cols = "Million kolonister";
$l_news_p_headline = "[player] &#39;s Empire nu har [total] planeter";
$l_news_c_headline = "[player] &#39;s Empire nu har [total] miljoner kolonister";
$l_news_p_textXX = "Förbundet har utfärdat varningar om kejsardömet [name]. [name] har kontroll över [total] planeter och bör betraktas som mycket farlig. Alla sektorer bör öka sektorns försvar omedelbart.";
$l_news_c_textXX = "Kejsardömet [name] har drabbats av massiva överbeläggningen på alla planeter med över [total] miljoner kolonister. Livsmedelsbrist kan orsaka oro. Alla sektorer bör vara medvetna om eventuella aggressiva åtgärder från [name] i framtiden.";

$l_created_universe = "&quot;Universe Creation &#39;";
$l_created_universe_full = "&quot;Forskare undersöker början av universum har enhälligt beslutat att det i dag är den statistiskt mest sannolika dag för Universum Creation ha ägt rum&quot;";

$l_news_p_text5 = "De stigande imperium av [name] har nu fem planeter kommer FNN titta agerande [name] i högre grad i framtiden!";
$l_news_p_text10 = "Den växande imperium av [name] kontrollerar nu tio planeter, rapporter FNN säga att en fortsatt utbyggnad av [name] kan leda till krig!";
$l_news_p_text25 = "De enorma imperium av [name] koloniserade 25 planeter redan, i en intervju, [name] meddelade att han kan tänka sig att sakta ner sin expansion i framtiden!";
$l_news_p_text50 = "Den enorma stort imperium av [name], företrädd av 50 planeter i hela galaxen blir en hotande styrka. En av de FNN reportrar fick reda på att [name] är att uppgradera sitt skepp planerar ett storkrig. I en intervju [name] skrevs som är gjort på försvar syfte bara!";
$l_news_c_text25 = "De stigande imperium av [name] har nu 25 miljoner kolonister kommer FNN titta agerande [name] mer i framtiden, men dess mycket tydligt att födelsetalen kommer att explodera!";
$l_news_c_text100 = "Den aspirerande imperium av [name] har nu 100 miljoner kolonister, efter en explosion av födelsetal, [name] kolonier verkade vara ett bra ställe för familjer att bosätta sig!";
$l_news_c_text500 = "Den stora imperium av [name] har nu 500 miljoner kolonister, [name] sade i en intervju att koloniseringen av galaxen har just börjat";
$l_news_c_text1000 = "Den humongous imperium av [name] har nu en miljard kolonister, FNN reportrar fick veta att [name] är i besittning av någon konstig kloning mekanism som tillåter honom att odla nya kolonister i enorma mängder. Med detta belopp kolonister, är econmic kraften i detta enorma imperium, FNN hoppas att [name] inte spenderar sina pengar på krigföring";

$l_news_indi_short = "FNN Rykte: över [planets] förklara sig självständiga.";
$l_news_indi = "FNN har fått veta att över [planets] planeter har beslutat att de är bättre styrs av sig själva och har blivit självständiga.";

$l_news_nova_short = "FNN Rapportera: [name] använder Nova Bomb.";
$l_news_nova = "FNN har breaking news att [name] har använt den fruktade Nova Bomb [total] tid (s) att förstöra en planet och alla fartyg på det.";
$l_news_nova_m_short = "FNN Rapportera: [name] använder Nova Bomb och missar.";
$l_news_nova_m = "FNN har breaking news att [name] har använt den fruktade Nova Bomb [total] tid (s) att försöka förstöra en planet. Nova Bomb exploderade utanför planeternas atmosfär och orsakade omfattande skador på de planetariska infrastrukturen.";

$l_news_bounty = "FNN Rapportera: [name] placerar [amount] kredit bounty [name2].";

$l_news_attackerpod_p_short = "FNN Rapport: [name] &#39;s skepp förstörs.";
$l_news_attackerpod_P = "[name] &#39;s skepp förstördes under attackera en planet. Lyckligtvis [name] hade en Escape Pod och överlevde.";

$l_news_attackerdie_p_short = "FNN Rapportera: [name] dör!";
$l_news_attackerdie_p = "[name] &#39;s skepp förstördes under attackera en planet och de dödades därför att de inte köpa en Escape Pod.";

$l_news_destroyed_p_short = "FNN Rapportera: [name] angriper och förstör en planet!";
$l_news_destroyed_p = "[name] anföll [total] planet (s) som ägs av [owner] och befolkningen i varje planet förstörda planeten att förhindra att fångas!";

$l_news_defeated_p_short = "FNN Rapportera: [name] attacker och besegrar en planet!";
$l_news_defeated_p = "[name] anföll [total] planet (s) som ägs av [owner] och besegrade de planetariska försvaret!";

$l_news_notdefeated_p_short = "FNN Rapportera: [name] attacker en planet och förlorar!";
$l_news_notdefeated_p = "[name] anföll [total] planet (s) som ägs av [owner] och planetariska försvar höll mot den obarmhärtiga attacker!";

$l_news_targetepod_short = "FNN Rapportera: [name] attacker a [owner] och vinner!";
$l_news_targetepod = "[name] anföll [owner] &#39;s skepp och förstörde det helt. Lyckligtvis [owner] hade försett sina fartyg med Escape Pod och de överlevde.";

$l_news_targetdies_short = "FNN Rapportera: [name] attacker a [owner] och dödar dem!";
$l_news_targetdies = "[name] anföll [owner] &#39;s skepp och förstörde det helt. Sadly [owner] inte försett sina fartyg med Escape Pod och de var förgasas.";

$l_news_fedcolbounty_short = "FNN Rapportera: Förbundet sprickor ned på [name]!";
$l_news_fedcolbounty = "Förbundet har idag slagit ned på den ökända utrymme pirat [name]! [name], som rutinmässigt brutit flera utrymme fördrag, var engagerad kort av förbundet slagkryssare, som orsakade [amount] krediter till ett värde av skada på Pirate&#39;s fartyget. Federation tjänstemän löfte ytterligare sådana åtgärder i framtiden!";

$l_news_alliancecolbounty_short = "FNN Rapportera: Alliansen sprickor ned på [name]!";
$l_news_alliancecolbounty = "Alliansen har idag slagit ned på den ökända utrymme pirat [name]! [name], som rutinmässigt brutit flera utrymme fördrag, var engagerad kort av alliansen, som orsakade [amount] krediter till ett värde av skada på Pirate&#39;s fartyget. Alliansen tjänstemän löfte ytterligare sådana åtgärder i framtiden!";

$l_news_fedcol_pbounty_short = "FNN Rapportera: Förbundet jagar [name]!";
$l_news_fedcol_pbounty = "Förbundet har idag slagit ned på den ökända utrymme pirat [name]! [name], som rutinmässigt brutit flera utrymme fördrag, var engagerad kort av förbundet slagkryssare, som konfiskerade planeten [planetname] värde [amount] krediter i sektorn [sector]. Federation tjänstemän löfte ytterligare sådana åtgärder i framtiden!";

$l_news_alliancecol_pbounty_short = "FNN Rapportera: Alliansen jagar [name]!";
$l_news_alliancecol_pbounty = "Alliansen har idag slagit ned på den ökända utrymme pirat [name]! [name], som rutinmässigt brutit flera utrymme fördrag, var engagerad kort av alliansen, som konfiskerade planeten [planetname] värde [amount] krediter i sektorn [sector]. Alliansen tjänstemän löfte ytterligare sådana åtgärder i framtiden!";

$l_news_fedcol_sbounty_short = "FNN Rapportera: Förbundet jagar [name]!";
$l_news_fedcol_sbounty = "Förbundet har idag slagit ned på den ökända utrymme pirat [name]! [name], som rutinmässigt brutit flera utrymme fördrag, var engagerad kort av förbundet slagkryssare, som konfiskerade fartyg ([shiptype]) värd [cost] inom sektorn [sector]. Federation tjänstemän löfte ytterligare sådana åtgärder i framtiden!";

$l_news_alliancecol_sbounty_short = "FNN Rapportera: Alliansen jagar [name]!";
$l_news_alliancecol_sbounty = "Alliansen har idag slagit ned på den ökända utrymme pirat [name]! [name], som rutinmässigt brutit flera utrymme fördrag, var engagerad kort av alliansen, som konfiskerade ett fartyg [shiptype] värde [cost] inom sektorn [sector]. Alliansen tjänstemän löfte ytterligare sådana åtgärder i framtiden!";

$l_killheadline = "[target] dödades i en olycka";
$l_news_killed = "";

$l_killSDheadline = "[target] dödades av Sector försvaret.";
$l_news_killedSD = "[target] dödades av en överväldigande antal Sector försvaret som ägs av [killer]! Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killplanetheadline = "[target] dödades attackera en planet.";
$l_news_killedplanet = "[target] dödades medan attackera en planet som ägs av [killer] idag. Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killshipheadline = "[target] dödades fartyg bekämpa.";
$l_news_killedship = "[target] dödades i mellan fartyg bekämpa med [killer] idag. Kaptenen glömde tydligen att förse fartyget med en escape pod.";

$l_killsuicideheadline = "[target] begått självmord.";
$l_news_killedsuicide = "[target] begått självmord i dag. De tog den fega vägen ut eftersom de saknade förmåga eller mod att stå emot trycket från kommenderade sina egna skepp.";

$l_killsofaheadline = "[target] dödades soffa attackera en planet.";
$l_news_killedsofa = "[target] dödades medan soffa attackera en planet som ägs av [killer] idag. Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killnovaheadline = "[target] dödades under en nova attack.";
$l_news_killednova = "[target] dödades av [killer] under en nova bombattack i dag. Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killnovabackfireheadline = "[target] dödades av en nova slå tillbaka.";
$l_news_killednovabackfire = "[target] dödades när deras nova bomb slint i dag. Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killsectormissileheadline = "[target] dödades av en sektor missil.";
$l_news_killedsectormissile = "[target] dödades när en sektor missil från [killer] påverkat deras sköldar. Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killhunterprobeheadline = "[target] dödades av en jägare Probe.";
$l_news_killedhunterprobe = "[target] dödades när en jägare Probe från [killer] påverkat deras sköldar. Tyvärr var fartyget inte är utrustat med en escape pod.";

$l_killtrapprobeheadline = "[target] dödades av en Sentry Trap Probe.";
$l_news_killedtrapprobe = "[target] dödades när en Sentry Trap Probe från [killer] påverkat deras sköldar. Tyvärr var fartyget inte är utrustat med en escape pod.";

//-------------------

$l_killpodheadline = "[target] &#39;s skepp förstördes i en olycka";
$l_news_killedpod = "[target] &#39;s skepp förstördes i en tragisk olycka i dag. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killSDpodheadline = "[target] &#39;s skepp förstördes av Sector försvaret.";
$l_news_killedSDpod = "[target] &#39;s skepp förstördes av ett överväldigande antal Sector försvaret som ägs av [killer]! En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killplanetpodheadline = "[target] &#39;s skepp förstördes attackera en planet.";
$l_news_killedplanetpod = "[target] &#39;s skepp förstördes under attackerade en planet som ägs av [killer] idag. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killshippodheadline = "[target] &#39;s skepp förstördes skepp bekämpa.";
$l_news_killedshippod = "[target] &#39;s skepp förstördes mellan fartyg bekämpa med [killer] idag. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killsofapodheadline = "[target] &#39;s skepp förstördes under soffa attackera en planet.";
$l_news_killedsofapod = "[target] &#39;s skepp förstördes under soffa attackera en planet som ägs av [killer] idag. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killnovapodheadline = "[target] &#39;s skepp förstördes under en nova attack.";
$l_news_killednovapod = "[target] &#39;s skepp förstördes av [killer] under en nova bombattack i dag. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &#39;s skepp förstördes av en nova slå tillbaka.";
$l_news_killednovabackfirepod = "[target] &#39;s skepp förstördes när deras nova bomb slint i dag. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &#39;s skepp förstördes av en sektor missil.";
$l_news_killedsectormissilepod = "[target] &#39;s skepp förstördes när en sektor missil från [killer] påverkat deras sköldar. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &#39;s skepp förstördes av en jägare Probe.";
$l_news_killedhunterprobepod = "[target] &#39;s skepp förstördes när en Hunter Probe från [killer] påverkat deras sköldar. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &#39;s skepp förstördes av en Sentry Trap Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s skepp förstördes när en Sentry Trap Probe från [killer] påverkat deras sköldar. En Escape Pod transponder upptäcktes av federationen Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] har befordrats till [rank]";
$l_news_promoted = "Förbundet har nöjet att meddela främjandet av [name] till rang av [rank].";

$l_news_demotedheadline = "[name] har blivit degraderad till [rank]";
$l_news_demoted = "Förbundet beklagar att tillkännage degradering av [name] till rang av [rank].";

$l_news_namechangedheadline = "[oldname] bytt namn till [newname]";
$l_news_namechanged = "[oldname] tillämpas på förbundet Review Board att byta namn till [newname]. Förbundet har beviljat namnbytet. Från denna dag framåt [oldname] oldname ska nu kallas [newname]. Alla fartyg och planeter bör uppdatera sina register omedelbart.";

$l_news_found_planets_short = "";
$l_news_found_planets = "Federation Survey scouter har lokaliserat [found_planets] nya planeter i nyupptäckta sektorer.";

$l_news_new_ports_short = "Federation Survey: [new_ports] ny konstruerade hamnar.";
$l_news_new_ports = "Federation ingenjörer har konstruerat [new_ports] nya hamnar i nyupptäckta sektorer.";

$l_news_addedsectors_short = "Federation Survey: [addedsectors] sektorer upptäckt.";
$l_news_addedsectors = "Federation Survey scouter har upptäckt [addedsectors] nya sektorer. Försiktighet rekommenderas.";

$l_news_artifactheadline = "[playername] avslutats [artifact]";
$l_news_artifact = "[playername] har hittat alla bitar av [artifact] och har all den makt det kan ge.";

$l_news_artifactfoundheadline = "[playername] hittade [artifact] styck";
$l_news_artifactfound = "[playername] har hittat en av bitar av [artifact] och behov [pieces] mer [piece].";

?>
