<?php
$l_sf_attacking = "Sector försvar fighters attackerar dig! <BR>";
$l_sf_destfight = "Din balkar förstöras [lost] fighters <BR>";
$l_sf_destfightb = "Din balkar förstöras [lost] fighters <BR>";
$l_sf_torphit = "Torpeder hit:";
$l_sf_destfightt = "Din torpeder förstöras [lost] fighters <BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "Du förstörde alla de stridande. <BR>";
$l_sf_destfightt2 = "Du förstörde [lost] fighters. <BR>";
$l_sf_lostfight = "Du har förlorat all fighters. <BR>";
$l_sf_lostfight2 = "Du förlorade [lost] fighters. <BR>";
$l_sf_armorbreach = "Din pansar brutit! <BR>";
$l_sf_armorbreach2 = "Din pansar hit för [lost] skada. <BR>";
$l_sf_sendlog = "[player] förstöras [lost] fighters sektor försvar i sektorn [sector].";
$l_sf_lreport = "Du förlorade [armor] Armor poäng, [fighters] fighters, och används [torps] torpeder. <BR><BR>";
$l_sf_shipdestroyed = "Ditt skepp har förstörts! <BR><BR>";
$l_sf_sendlog2 = "Sector försvar fighters förstöras [player] inom sektorn [sector].";
$l_sf_escape = "Som tur du har en escape pod! <BR><BR>";

$l_sf_fnoattack = "sänder inte någon fighters att attackera din krigare.";
$l_sf_fnoattackt = "sänder inte någon fighters att attackera din torpeder.";
$l_sf_fnoattacka = "sänder inte någon fighters att attackera din rustning.";
$l_sf_flaunchmalf1 = "Din fighter lansera systemet har skadats.";
$l_sf_flaunchmalf2 = "Du har bara kunnat lansera";
$l_sf_flaunchmalf3 = "procent av din krigare.";
$l_sf_fightertorpexg = "Fighter till Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Ship Torpedo att Sector Fighter Exchange";
$l_sf_fighterarmorexg = "Sektor Fighter till Ship Armor Exchange";
$l_sf_tlaunchmalf1 = "Din torped lansera systemet har skadats.";
$l_sf_tlaunchmalf2 = "Du har bara kunnat lansera";
$l_sf_tlaunchmalf3 = "procent av din torpeder.";
$l_sf_bountysd = "Du har attackerat en sektor som innehåller en planet som skulle ge dig en belöning om du attackeras planeten. Förbundet har aktiverat en automatisk självförstörande på alla dina soldater och torpeder. Angriper inte den sektor försvar i denna sektor igen. Ni har blivit varnade!";
?>
