<?php
$l_gns_title = "Använd Genesis Device";
$l_gns_turn = "Du behöver minst en tur att använda ett blivande enhet.";
$l_gns_onplanet = "Du kan inte använda enheten medan den är planetens yta.";
$l_gns_full = "Detta solsystem är redan full.";
$l_gns_planetex = "Det finns redan en planet inom denna sektor.";
$l_gns_nogenesis = "Du har inga genesis enheter.";
$l_gns_forbid = "Skapa en planet inom denna sektor är inte tillåten.";
$l_gns_bforbid = "Serna i denna sektor stör din genesis enheten. Planet skapande not possible.";
$l_gns_pcreate = "Planet skapas.";
$l_sgns_title = "Använd Sector Genesis Device";
$l_sgns_pcreate = "Sector [name] har skapats.";
$l_sgns_nogenesis = "Du har inga produkter sektor genesis.";
$l_sgns_forbid = "Skapa ett maskhål sektor tillkomst i denna sektor är inte tillåten.";
$l_sgns_forbid1 = "Skapa en sektor Genesis maskhål en federation sektor är inte tillåtet.";
$l_sgcreate = "Skapa ny Sector Genesis Sector";
$l_sgcreatens = "Skapa ny Sector Genesis länka tillbaka till kända rymden";
$l_sgns_forbid2 = "Mer än [limit] länkar i SG Sektorer är inte tillåtna.";
$l_sgns_forbid3 = "Kan inte skapa Sector Genesis varp länk från nuvarande sektor - det skulle överstiga den högsta av [limit] per sektor.";
$l_sgns_nocredits = "Du har inte tillräckligt med krediter för att skapa en ny sektor.";
$l_sgns_shipcredits = "Krediter på fartyget:";
$l_sgns_createcost = "Kostnad för att skapa nya Sektor:";
$l_sgns_complete = "Normal Space Link Complete";
$l_sgns_sectorname = "Ange Sector Namn:";
$l_gns_max_unbased_planets = "Förbundet kommer inte att tillåta att skapa fler planeter tills du har mindre än [max_unbased_planets] unbased planeter.";

?>
