<?php
$l_new_pwis = "Ditt lösenord";
$l_new_charis = "Din karaktär heter";
$l_new_title2 = "Skapa ny Player Phase Two";
$l_new_blank = "E-post, fartygets namn och karaktär namn får inte vara tomt.";
$l_new_inuse = "E-postadress [username] är redan i bruk.";
$l_new_forgotpw = "Har du glömt ditt lösenord?";
$l_new_inusechar = "Tecken namn [character], är redan i bruk.";
$l_new_similar_inusechar = "Din karaktär namnet låter för likt [character], ett namn som redan används.";
$l_new_inuseship = "Fartygets namn [shipname], är redan i bruk.";
$l_new_similar_inuseship = "Ditt skepp namnet låter för likt [shipname], ett namn som redan används.";
$l_new_pwsent = "Lösenord har skickats till [username].";
$l_new_err = "Försök igen";
$l_new_topic = "Alien Assault Traders Lösenord";
$l_new_message = "Hälsningar, \ n \ nSomeone från IP-adressen $ ip begärt att ditt lösenord för näringsidkare att skickas till dig. \ N \ nDin lösenord är: [pass] \ n \ nMed vänliga hälsningar \ n \ nDet Traders webbteam.";
$l_new_invalidemail = "Ogiltig e-postadress.";
$l_new_tutorial = "Klicka här för att läsa mini-handledning innan du loggar in i spelet.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "att gå till inloggningssidan.";

?>
