<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Du behöver minst en tur för att söka ett annat fartyg.";
$l_scan_ron = "Scan resultat";
$l_scan_capt = "Kapten:";
$l_scan_arma = "Bestyckning";
$l_scan_carry = "Carrying:";
$l_scan_bounty = "Detta fartyg har en total bounty om det på [amount] krediter.";
$l_scan_fedbounty = "Detta fartyg har en bounty på det från förbundet.";
$l_by_nofedbounty = "Anfalla denna spelare kommer <B>inte</b> att resultera i federationen släppa en bounty på dig.";
?>
