<?php
$l_ze_title = "Edit Zone";
$l_ze_notowner = "Du är inte ägaren till denna zon så att du inte kan redigera den.";
$l_ze_name = "Zonnamnet";
$l_ze_allow = "Tillåta";
$l_ze_attacks = "Tillåt attackera andra fartyg";
$l_ze_genesis = "Möjligt att skapa nya planeter";
$l_ze_return = "att återgå till zon informationssida";
$l_ze_saved = "Dina ändringar har sparats.";
$l_ze_namematch = "FEL: zonnamnet du som är liknande eller matchar en befintlig Områdesnamn.";
?>
