<?php
$l_profile_title = "Profil Registrering";
$l_profile_notenabled = "Profiler aktiveras inte på denna server.";
$l_profile_registered = "Denna spelare är nu registrerad hos Master Profil Server.";
$l_profile_nomatch = "Kunde inte matcha en profil på Master profil Server med namn och serverlösenord in.";
$l_profile_tryagain = "Att ange ditt namn spelarprofil och server lösenord igen klickar";
$l_profile_name = "Profil Player Name";
$l_profile_password = "Profil Server Lösenord";
$l_profile_bannedserver = "Här servern är inte tillåtet att lämna profilen information till Master Profil Server.";
$l_profile_bannedplayer = "Du har blivit avstängd från Master Profil Server och får inte registrera spelare.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Den här servern <u><b>kräver</b></u> varje ny spelare att ha en registrerad profil. Du kommer inte att tillåtas att skapa en ny spelare om du inte har en registrerad profil.";
$l_profile_updated = "Mallen shoutbox och Nyhetssökning globala inställningar har uppdaterats på profil Master Server. Dessa inställningar kommer automatiskt att användas när du registrerar din profil på valfritt spel.";

?>
