<?php
$l_chf_youretreatback = "Du reträtt tillbaka till föregående plats";
$l_chf_movefailed = "Flytta misslyckades.";
$l_chf_thefightersdetectyou = "Kämparna upptäcka dig!";
$l_chf_therearetotalfightersindest = "Finns [chf_total_sector_fighters] krigare i din destination sektor.";
$l_chf_youcanretreat = "<B>Retreat</b> - kommer att kosta en extra sväng.";
$l_chf_inputfight = "<B>Fight</b> - Du måste besegra alla de stridande att komma in i branschen.";
$l_chf_inputcloak = "<B>Kappa</b> - Använd din elektroniska sköld och försöka undvika de stridande.";
$l_chf_go = "Gå";
$l_chf_inputrun = "<B>Attack and Run</b> - Du gör en lättnad attack springa och reträtt. Men du kan ta lite skador under reträtt.";
?>
