<?php
$l_contact_admin_title = "Kontakt Game Administrator";
$l_contact_admin_thanks = "Tack för din kommentar.";
$l_contact_admin_email_alert = "Ange en giltig e-postadress.";
$l_contact_admin_name_alert = "Ange ditt namn.";
$l_contact_admin_comment_alert = "Ange dina kommentarer.";
$l_contact_admin_name = "Namn";
$l_contact_admin_email = "E-post";
$l_contact_admin_comment = "Fråga / Kommentar";
$l_contact_admin_submit = "Skicka frågor / kommentarer";
$l_contact_admin_close = "Stäng fönstret";
$l_contact_admin_thanks_comment = "Tack för din kommentar eller fråga. Vi kommer att behandla några frågor och skicka dig vårt svar.";

?>
