<?php
$l_sm_title = "Sector Missile Launch";
$l_sm_invalid = "Det finns inte en varp koppling mellan denna sektor och destinationen sektorn.";
$l_sm_notarg = "Målet inte i denna sektor.";
$l_sm_noturn = "Du behöver minst ett varv till brand din sektor Missile.";
$l_sm_nosectormissile = "Du är inte medför någon sektor missiler.";
$l_sm_noscan = "Sensorer kan inte få en fix för mål!";
$l_sm_flee = "Target manövrerade ut Sector Missile!";
$l_sm_ewd = "Target anlitat en enhet nödsituation varp när det upptäcks sektorsöverenskommelsen Missile!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] attackerar ditt skepp med en sektor missil!";
$l_sm_sectormissilefail = "Sektorsöverenskommelsen Missile skadats när den slog fienden fartyg sköld!";
$l_sm_sectormissilefail2 = "Sektorsöverenskommelsen Missile skadats när den slog fienden fartyg rustning!";
$l_sm_shieldhit = "[target] &#39;s sköldar träffas för [amount] skada!";
$l_sm_shieldsdown = "[target] &#39;s sköldarna är nere!";
$l_sm_armorhit = "[target] &#39;s pansar hit för [amount] skada!";
$l_sm_armorbreached = "[target] &#39;s rustning brutit!";
$l_sm_targetnoenergy = "Fienden fartyg har ingen energi! Sector Missile misslyckas!";
$l_sm_attacking = "Attackerande [target] ombord på [shipname]";
$l_sm_targetok = "Du har inte destory [name] &#39;s skepp.";
$l_sm_lost = "[target] förlorat [armor] punkter rustning och [energy] enheter energi.";
$l_sm_destroyed = "[target] &#39;s skepp har förstörts.";
$l_sm_escapepod = "En escape pod inleddes!";
?>
