<?php
$l_autotrade_title = "Auto Traderoute Meny";
$l_autotrade_dismiss2 = "Auto Traderoutes utgår.";
$l_autotrade_report = "Auto Traderoute Report";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energi";
$l_autotrade_capacity = "Kapacitet";
$l_autotrade_goods = "Varor Pris";
$l_autotrade_ore = "Malm";
$l_autotrade_organics = "Organics Pris";
$l_autotrade_energy = "Energipris";
$l_autotrade_colonist = "NYBYGGARE Pris";
$l_autotrade_credits = "Handelskrediter";
$l_autotrade_delete = "Ta bort <br> Route";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "Ingen Route";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "Poäng";
$l_autotrade_deletebutton = "Ta bort";
$l_autotrade_noroute2 = "Du har inte setup några Auto Traderoutes.";
?>
