<?php
$l_warp_linkto = "Länkarna leder från denna sektor";
$l_warp_nolink = "Det finns inga länkar från denna sektor.";
$l_warp_query = "Vilken sektor vill du skapa en länk till?";
$l_warp_oneway = "One-way?";
$l_warp_dest = "Alternativt kan du förstöra en länk till sektor.";
$l_warp_destquery = "Vilken sektor skulle du vilja ta bort en länk till?";
$l_warp_bothway = "Båda-vägar";
$l_warp_create = "Skapa en varp koppling mellan Sektor:";
$l_warp_andsector = "och Sektor:";
$l_warp_distance = "med ett avstånd";
$l_warp_lightyears = "ljusår";
$l_warp_delete = "Bort warp koppling mellan Sektor:";
$l_warp_costcreate = "Kostnad för att skapa:";
$l_warp_costdelete = "Kostnad för att ta bort:";
$l_warp_costenergy = "Energi som behövs:";
$l_warp_twoerror = "Använda en Warp Editor för att skapa en ömsesidig koppling till sektorn [target_sector] är inte tillåtet.";
?>
