<?php
///SPIES
$l_dig_title = "Dignitär Meny";
$l_dig = "Dignitärer";
$l_dig_disabled = "Dignataries är handikappade!";
$l_dig_noturn = "Du behöver minst en tur för att skicka en ämbetsman till en planet.";
$l_dig_notonboard = "Du har inte någon ämbetsman ombord.";
$l_dig_ownplanet = "Du kan inte skicka en ämbetsman till en fiende planet.";
$l_dig_unownedplanet = "Du kan inte skicka en ämbetsman till herrelösa planet.";
$l_dig_planetfull = "Det finns redan möjlighet [max] dignitärer på denna planet.";
$l_dig_sendtitle = "Skicka ett dignitär [digID] till planet: <BR> Välj dignitär uppdrag:";

$l_dig_codenumber = "Kod";
$l_dig_job = "Jobb";
$l_dig_percent = "Procent";
$l_dig_move = "Movement";
$l_dig_action = "Action";
$l_dig_shipowner = "Fartygsägaren";
$l_dig_shipname = "Fartygsnamn";
$l_dig_shiptype = "Ship tCLASS";
$l_dig_shiplocation = "Ship Location";
$l_dig_planetowner = "Planet Ägare";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Högsta Per Planet";
$l_dig_legend = "Dignitär Legend";
$l_dig_description = "Dignitär Beskrivning";
$l_dig_waiting_description = "Dignitär skapar torpeder och kämpar i väntan på ett jobb uppdrag.";
$l_dig_changeerror = "Dignitär Job Change Report";

$l_dig_nospieshere = "Du har inte några dignitärer på denna planet!";
$l_dig_transferred = "dignitärer överförda";
$l_dig_backonship = "Den ämbetsman är nu på ditt skepp.";
$l_dig_dismiss = "Ogilla ämbetsman?";
$l_dig_changebutton = "Ändra";
$l_dig_notyourplanet = "Det är inte din planet.";

$l_dig_defaulttitle1 = "Dignitärer på fiendens fartyg";
$l_dig_defaulttitle2 = "Dignitärer på din planeter";
$l_dig_defaulttitle3 = "Dignitärer på din planeter";
$l_dig_defaulttitle4 = "Dignitärer på ditt skepp";

$l_dig_no1 = "Du har inte några dignitärer på fiendens fartyg.";
$l_dig_no2 = "Du har inte några dignitärer på planeter.";
$l_dig_no3 = "Du har inte några dignitärer på planeter.";
$l_dig_no4 = "Du har inte några dignitärer på ditt skepp.";
$l_dig_nodignitaryatall = "Du har inga dignitärer.";
$l_dig_notknown = "Okänd";
$l_dig_dismiss = "Avslå";
$l_dig_dismiss2 = "Dignitärer ogillas.";
$l_dig_menu = "";

?>
