<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Din skannrar inte innehar fullständigt lång räckvidd scan kapacitet.";
$l_lrs_noturns = "Du behöver minst $ fullscan_cost tur (s) att köra en hel lång räckvidd scan.";
$l_lrs_used = "Begagnade";
$l_lrs_turns = "tur (s)";
$l_lrs_left = "vänster";
$l_lrs_reach = "Följande platser kan nås från sektorn [sector]:";
$l_lrs_links = "Länkar";
$l_lrs_ships = "Fartyg";
$l_lrs_click = "Klicka på en av länkarna för att flytta till denna sektor.";
$l_lrs_cantscan = "Går inte att skanna sektor från nuvarande sektor!";
$l_lrs_zero = "Sector 1 är för trångt för att söka efter fartyg!";
$l_lrs_moveto = "att flytta till sektor";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Visa logg";
$l_lrs_fedjammed = "Federationen är jamming alla givare scans.";
$l_lrs_sectormissile_question = "till brand sektor missil.";
$l_log_months = "array ( &#39;januari&#39;, &#39;februari&#39;, &#39;mars&#39;, &#39;April&#39;, &#39;mars&#39;, &#39;Juni&#39;, &#39;Juli&#39;, &#39;augusti&#39;, &#39;September&#39;, &#39;oktober&#39;, &#39;November&#39;, &#39;December&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;februari&#39;, &#39;mar&#39;, &#39;april&#39;, &#39;Maj&#39;, &#39;juni&#39;, &#39;juli&#39;, &#39;augusti&#39;, &#39;september&#39;, &#39;oktober&#39;, &#39;november&#39;, &#39;december&#39;)";
?>
