<?php
$l_pre_title = "Ändra Realspace Presets";
$l_pre_exceed = "Förinställda [preset] överstiger universum max för [sector_max]. Inga presets sparas. <BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Spara";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] är ett ogiltigt sektor namn.";
$l_pre_invalidchange = "[sector] är en sektor Genesis Sector. Din gamla förinställda är oförändrad.";
?>
