<?php
$l_by_title = "Skottpengar";
$l_by_noturn = "Du behöver minst en tur till plats eller ändra en bounty.";
$l_by_amount = "Bounty Belopp";
$l_by_place = "Place Bounty";
$l_by_nobounties = "Det finns för närvarande inga gåvor.";
$l_by_bountyon = "Bounty";
$l_by_placedby = "Placerats av";
$l_by_thefeds = "Federationen";
$l_by_cancel = "Avbryt";
$l_by_yourself = "Du kan inte placera en bounty på dig själv.";
$l_by_notenough = "Du har inte tillräckligt med krediter för att placera en bounty av detta belopp.";
$l_by_toomuch = "Du kan inte placera det frikostighet. Högsta tillåtna skottpengar på en annan spelare är [percent] procent av din nettoförmögenhet";
$l_by_zeroamount = "Skottpengar måste vara större än 0 poäng.";
$l_by_placed = "The Bounty har placerats.";
$l_by_nobounty = "Det bounty inte längre existerar.";
$l_by_notyours = "Det bounty sattes inte av dig.";
$l_by_canceled = "The Bounty har avbrutits.";
$l_by_action = "Action";
$l_by_placebounty = "Plats eller skottpengar view.";
$l_by_moredetails = "Klicka på namnet för mer information.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "Spelaren du utsätter bounty på existerar inte.";
$l_by_destroyed = "Du kan inte placera en bounty på en spelare med en förstörd fartyg.";
$l_by_nofedbounty = "Du kommer inte att få en belöning om du attackerar denna spelare fartyget eller planet.";
$l_by_fedcollectonly = "Endast federationen kan samla Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Du kommer inte att få en belöning om du placerar en spion på denna spelare planet.";
$l_pay_partial = "Gör delbetalning";
$l_pay_button = "Betala";

$l_by_thealliance = "Alliansen";
$l_by_alliancecollectonly = "Endast alliansen kan samla Bounty";
$l_by_bountyscan = "Bounty";
?>
