<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] hit [chm_roll] gruvor i sektorn [chm_sector].";
$l_chm_youlostminedeflectors = "Du förlorade [chm_roll] avvisare gruva.";
$l_chm_youlostallminedeflectors = "Du har förlorat alla mina avvisare.";
$l_chm_youhadnominedeflectors = "Du hade ingen gruva avvisare.";
$l_chm_yourshieldshitforminesdmg = "Din sköldar drabbas för [chm_mines_left] skada.";
$l_chm_yourshieldsaredown = "Din sköldarna är nere!";
$l_chm_youlostallyourshields = "Du förlorat alla dina sköldar!";
$l_chm_yourarmorhitforminesdmg = "Din pansar hit för [chm_mines_left] skada.";
$l_chm_yourhullisbreached = "";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] förstördes av din gruvor inom sektorn [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Ditt skepp har förstörts!";
$l_chm_luckescapepod = "Som tur du har en escape pod!";

$l_chm_yourdeflectormalf1 = "Mine Deflektor lansera systemet har skadats.";
$l_chm_yourdeflectormalf2 = "Du har bara kunnat lansera";
$l_chm_yourdeflectormalf3 = "procent av din min avvisare.";
$l_chm_enemytorpfailshields = "har inte inlett några torpeder mot dina sköldar.";
$l_chm_enemytorpfailarmor = "har inte inlett några torpeder mot din rustning.";

$l_chm_minemalf1 = "Enemy Mines har skadats.";
$l_chm_minemalf2 = "Endast";
$l_chm_minemalf3 = "procent av gruvorna anfalla hittade ditt skepp.";

$l_chm_youhitsomemines = "Du slår [chm_roll] gruvor av [total_mines] gruvor!";
$l_chm_yourdeflectormalf2a = "Du har bara kunnat lansera [deflectors] procent av din min avvisare.";
$l_chm_mines_destroyed = "[number] av [target] minor har förstörts!";
$l_chm_mine_deflectors_left = "Du har [number] gruva avvisare vänster.";
$l_chm_mines_left = "Det är [number] minor kvar och de är som påverkar din rustning!";
$l_chm_minemalf2a = "Endast [deflectors] procent av gruvorna anfalla hittade ditt skepp.";
$l_chm_mines_exhausted = "[player] Mines Utmattad!";
$l_chm_armor_left = "Du har [number] Armor poäng kvar!";

?>
