<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Probe Levels";
$l_probe_engine = "Motor";
$l_probe_sensors = "Sensorer";
$l_probe_cloak = "Kappa";
$l_probe_title = "Space Probe Meny";
$l_probe_none = "Du är inte i samma sektor som denna sond, så att du inte kan interagera med det.";

$l_probe_named = "Välkommen till Probe Antal [probename], som ägs av [name], beläget i sektorn [sector].";
$l_probe_orders = "[orders] Probe att söka universum";
$l_probe_orders_link = "Program";
$l_probe_upgrade = "[upgrade] Probe Sensorer / Motor / mantel";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] Probe för senare placering";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Uppdatera";

$l_probe_att_link = "Attack";
$l_probe_att = "[attack] om sond";
$l_probe_att_sure = "Är du säker ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] sond";

$l_probe_unknown = "Okänd";
$l_plant_scn_turn = "Du behöver minst en tur för att skanna en sond.";
$l_probe_noscan = "Sensorer kan inte få en fix för mål!";
$l_probe_logscanA = "[name] försökte skanna en av dina sonder inom sektorn [sector], men misslyckades.";
$l_probe_logscanB = "En av dina sonder inom sektorn [sector] skannades av [name].";
$l_probe_scn_report = "Scan resultat på [name], som ägs av: [owner]";

$l_probe_caplog = "Din probe &quot;[probename]&quot; inom sektorn [sector] tillfångatogs av [name].";
$l_probe_scan = "Probe scans sektor [sector] och konstaterar:";
$l_probe_destroyprobe = "Destroy sond";
$l_probe_destroyed = "Probe Destroyed!";
$l_probe_warning = "Göra detta kommer att totalt förstöra denna sond";
$l_probe_confirm = "Vill du verkligen förstöra detta prob?";
$l_gns_turn = "Du har inte tillräckligt visar att förstöra denna sond";
$l_probe_type = "Probe Type";
$l_probe_type0 = "Stationära Probe";
$l_probe_type1 = "Vaktpost Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sekventiell Realspace Probe";
$l_probe_target = "Målsektor";
$l_probe_ordered = "Probe programmeras och börjar söka.";
$l_probe_order2 = "Probe är en [type] och är inriktad på sektorn [target]";
$l_probe_pickedup = "Probe plockas upp och placeras i aktiv lager";
$l_probe_title = "Probe Meny";
$l_probe_messages = "att se vad dina spioner har upptäckts.";

$l_probe_defaulttitle1 = "Aktiv Probes";
$l_probe_defaulttitle2 = "Sonder du har plockat upp";
$l_probe_defaulttitle3 = "Sonder på din planeter";
$l_probe_defaulttitle4 = "Sonder på ditt skepp";
$l_probe_linkback = "att gå till sonden menyn.";
$l_probe_no1 = "Du har inga aktiva prober.";
$l_probe_no2 = "Du har inga prober i lager.";
$l_probe_no3 = "Du har inga prober på dina planeter.";
$l_probe_no4 = "Du har inga prober på ditt skepp.";
$l_probe_noprobeatall = "Du har inga sonder.";
$l_probe_notknown = "Okänd";
$l_probe_launch = "Tappa";
$l_probe_detect = "Detected";
$l_probe_codenumber = "Kod";
$l_probe_job = "Jobb";
$l_probe_percent = "Procent";
$l_probe_move = "Movement";
$l_probe_view = "Visa";
$l_probe_action = "Action";
$l_probe_shipowner = "Fartygsägaren";
$l_probe_shipname = "Fartygsnamn";
$l_probe_shiptype = "Ship tCLASS";
$l_probe_shiplocation = "Ship Location";
$l_probe_planetowner = "Planet Ägare";
$l_probe_planetname = "Planet";
$l_probe_sector = "Aktuella Sector";
$l_probe_tsector = "Målsektor";
$l_probe_type = "Probe Type";
$l_probe_forbid = "Du kan inte släppa sonder inom denna sektor";

$l_probe2_title = "Launch Space Probe";
$l_probe2_turn = "Du behöver minst en tur att använda en rymdsond.";
$l_probe2_onplanet = "Du kan inte använda enheten medan den är planetens yta.";
$l_probe2_noprobe = "Du har inga rymdsonder.";
$l_probe2_forbid = "Lansering av en sond i denna sektor är inte tillåten.";
$l_probe2_launched = "Rymdsond lanserat!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Player";
$l_probe2_onboarda = "ombord på";
$l_probe2_classship = "class fartyg";
$l_probe2_traveled = "reste till sektor";
$l_probe2_fedjammed = "Federationen är jamming alla givare försök att få Sector 1.";
$l_probe2_lastseen = "Senast Ship Seen";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Stöder";
$l_probe2_planets = "planeter";
$l_probe2_sectord = "Sector försvar Detected";
$l_probe2_mines = "Mines";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Fartyg Detected";
$l_probe2_ships2 = "Ship Detected";
$l_probe2_noneowned = "Nej planeter som inte ägs av dig har upptäckts.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Inget Detected";
$l_probe2_nocredits = "Du har inte tillräckligt med krediter för denna transaktion. Den totala kostnaden är [total] krediter och du bara har [credits] krediter.";

$l_probe_forbidSG = "Du kan inte skicka en Realspace typ sond till Sector Genesis skapade sektorer.";
$l_probe_forbidFED = "Du kan inte skicka en Realspace typ sond i federationen eller Alliance ägs sektorer.";
$l_probe_forbidINVALID = "Destinationen sektor är ett ogiltigt sektor namn.";
?>
