<?php
$l_nav_title = "Navigation Computer";
$l_nav_nocomp = "Navigation dator är inte tillgänglig";
$l_nav_query = "Ange sektor att finna vägen till:";
$l_nav_pathfnd = "Path hittades";
$l_nav_answ1 = "Det tar";
$l_nav_answ2 = "vänder komma till denna sektor.";
$l_nav_proper = "Du behöver uppgradera din Fighter Bay tekniken innan din fighters kan hitta en varp väg för denna sträcka.";
$l_nav_autoroutename = "Valfritt Autoroute Namn:";
$l_nav_manuallist = "Manuellt Built WarpLink Autoroute List";
$l_nav_warplinksleaving = "Warp Länkar Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Det finns inga warplinks lämnar denna sektor.";
$l_nav_warp_from = "Warp från";
$l_nav_rs_from = "RSMove från";
$l_nav_notinlogs = "Inga uppgifter finns om denna sektor.";
?>
