<?php
$l_login_title = "Logga in";
$l_login_pw = "Lösenord:";
$l_login_chooseres = "Det går inte att avgöra din skärmupplösning. Välj det passar bäst:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problem?";
$l_login_emailus = "E-posta oss";
$l_login_forgot_pw = "Har du glömt ditt lösenord? Ange det tomt och tryck Logga in.";
$l_login_settings = "Spelinställningar";
$l_login_change = "Ändra";
$l_login_title2 = "Main Login för AATraders";
$l_login_reset1 = "Nej Reset Schemalagda";
$l_login_reset2 = "Schemalagda Reset:";
$l_login_reset3 = "Mallen Reset:";
$l_login_notice = "Viktigt meddelande:";
$l_login_endadminnews = "Slutet av Admin News";
$l_login_tourney_signup = "Tournament Registreringar Enabled";

$l_login_profile_only = "Profil Only";
$l_login_newclosed_message = "Nya registreringar Stängt";
$l_login_tourneymode = "Turnering";
$l_login_tourneystarts = "Startar:";
?>
