<?php
$l_defense_deploy_title = "Distribuera Sector Mines &amp; Fighters";
$l_defense_deploy_noturn = "Du behöver minst en tur distribuera sektor försvar.";
$l_defense_deploy_nopermit = "Driftsätta Gruvor och Fighters inom denna sektor är inte tillåten.";
$l_defense_deploy_nodeploy = "Kan inte använda här. Annat fartyg eller Team har gruvor eller fighters i denna sektor.";
$l_defense_deploy_info1 = "Du är för närvarande inom sektorn [sector]. Finns [mines] gruvor och [fighters] fighters här.";
$l_defense_deploy_info2 = "Du har [mines] gruvor och [fighters] fighters tillgänglig för distribution";
$l_defense_deploy_deploy = "Deploy";
$l_defense_deploy_deployed = "Användas";
$l_defense_deploy_att = "Attack";
$l_defense_deploy_notorps = "Du har inte tillräckligt med torpeder.";
$l_defense_deploy_nofighters = "Du har inte tillräckligt fighters";
$l_defense_deploy_dmines = "Användas [mines] gruvor.";
$l_defense_deploy_dfighter = "Användas [fighters] fighters.";
$l_defense_deploy_max_fighters = "Denna sektor kan stödja högst [amount] fighters.";
$l_defense_deploy_toomanyfighters = "Du har försökt att sätta in fler flygplan än sektorn kan stödja.";
?>
