<?php
$l_footer_one_player_on = "Det är 1 spelare online.";
$l_footer_players_on_1 = "Finns";
$l_footer_players_on_2 = "Spelare online:";
$l_footer_until_update = "sekunder tills nästa uppdatering.";
$l_footer_no_players_on = "Det finns inga spelare online.";

$l_footer_news = "Lokala FNN News";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = "för hjälp om den här sidan.";
$l_footer_click = "Klicka";

$l_footer_open_slots = "Maximum Online:";
$l_footer_onlinereset = "Spelare Online Time Reset i";
$l_footer_onlinecountdown = "Spelare online Tid Countdown:";
?>
