<?php
$l_att_title = "Attack Ship";
$l_att_notarg = "Målet inte i denna sektor.";
$l_att_noturn = "Du behöver minst en tur till attack.";
$l_att_noatt = "Att attackera någon i denna sektor är inte tillåten.";
$l_att_flee = "Target manövrerade ut dig!";
$l_att_ewd = "Target anlitat en enhet nödsituation varp när attackerade!";
$l_att_att = "Attacking";
$l_att_beams = "Beam Exchange";
$l_att_torps = "Torped Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost = "tappade";
$l_att_ylost = "Du förlorade";
$l_att_sdown = "s sköldarna är nere!";
$l_att_ydown = "Din sköldarna är nere!";
$l_att_shits = "s sköldar träffas för";
$l_att_yhits = "Din sköldar drabbas av";
$l_att_dmg = "skada";
$l_att_sarm = "s rustning brutit!";
$l_att_yarm = "Din rustning har överträtts!";
$l_att_ashit = "s pansar hit för";
$l_att_ayhit = "Din pansar hit för";

$l_att_efhit = "s fighters förstörs.";
$l_att_yfhit = "din fighters förstörs.";
$l_att_ethit = "s torpeder förstörs.";
$l_att_ythit = "din torpeder förstörs.";
$l_att_of = "av";
$l_att_lostt = "förlorat all torpeder.";
$l_att_ylostt = "Du har förlorat all torpeder.";

$l_att_lostf = "förlorat all fighters.";
$l_att_ylostf = "Du har förlorat all fighters.";
$l_att_sdest = "&#39;s skepp har förstörts.";
$l_att_espod = "En escape pod inleddes!";
$l_att_ysalv = "Du avstyckade [ship_salvage_rate]% av fartygets för [ship_salvage] krediter. <BR> Ditt betyg förändrats genom [rating_change] punkter.";
$l_att_andused = "och används";
$l_att_stilship = "Du har inte destory [name] &#39;s skepp.";
$l_att_atyou = "attackerade er";
$l_att_and = "och";
$l_att_yshiplost = "Ditt skepp har förstörts!";
$l_att_salv = "[name] räddas [ship_salvage_rate]% av fartygets för [ship_salvage] Poäng";
$l_att_loosepod = "Som tur du har en escape pod!";

$l_att_tnobeams = "sömmar för att vara ur strålenergi.";
$l_att_tnobeamsf = "sömmar för att vara ur strålenergi och kan inte attackera din fighters.";
$l_att_tnobeamst = "sömmar för att vara ur strålenergi och kan inte attackera din torpeder.";
$l_att_tfnoattack = "sänder inte någon fighters att attackera ditt skepp.";
$l_att_tnotorps = "verkar vara av torpeder.";

$l_att_anobeams = "Du har förbrukat dina skepp strålenergi.";
$l_att_anobeamsf = "Du har förbrukat dina skepp strålenergi och kan inte attackera fientliga jaktplan.";
$l_att_anobeamst = "Du har förbrukat dina skepp strålenergi och kan inte attackera fienden torpeder.";
$l_att_anofighters = "Ditt skepp har uttömt alla availible fighters.";
$l_att_anotorps = "Du har förbrukat din availible torpeder.";
$l_att_imtitle = "Ship Under Attack";
$l_att_imbody = "attackerar ditt skepp.";

$l_att_luckybeams = "Enemy balkar överbelastning vålla";
$l_att_luckyfighters = "Fientliga jaktplan göra ett överraskande lättnad attack och orsaka";
$l_att_luckytorps = "Enemy torpeder inducera en forsande skada effekt orsakar";
$l_att_luckytimes = "gånger den normala skador!";
?>
