<?php
$l_readm_title = "Read Message";
$l_readm_delete = "Meddelande borttaget";
$l_readm_nomessage = "Du har inga meddelanden väntar på dig ...";
$l_readm_center = "Ta emot Center";
$l_readm_sender = "Message Sender";
$l_readm_captn = "Kaptenen på";
$l_readm_del = "Ta bort";
$l_readm_repl = "Svara";
$l_readm_return = "Klicka här för att återgå till huvudmenyn";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Radera alla";
$l_readm_subject = "Ämne";
$l_readm_quote = "Offert";
$l_readm_block = "Blockera avsändare";
$l_readm_alert = "System Alert";
$l_readm_alertbody = "Ship Computer";
?>
