<?php
$l_chf_youretreatback               = "Sa liikusid tagasi oma eelmisesse asukohta";
$l_chf_movefailed                   = "Liikumine eba&otilde;nnestus.";
$l_chf_thefightersdetectyou         = "H&auml;vitajad avastasid Su!";
$l_chf_therearetotalfightersindest  = "Sektoris, kuhu Sa liikuda soovid, on [chf_total_sector_fighters] h&auml;vitajat.";
$l_chf_youcanretreat                = "<B>Tagasi liikuda</B> - see l&auml;heb Sulle lisak&auml;igu maksma.";
$l_chf_inputfight                   = "<B>V&otilde;idelda</B> - Sa pead k&otilde;ik sektori h&auml;vitajad &auml;ra v&otilde;itma.";
$l_chf_inputcloak                   = "<B>Sisse hiilida</B> - kasutad oma radarisegajat ja p&uuml;&uuml;ad h&auml;vitajaid v&auml;ltida.";
$l_chf_go                           = "Mine";
$l_chf_inputrun = "<B>Attack ja Run</b> - Te kergendada rünnak kestab ja taganema. Aga sa võib võtta mõne kahju jooksul taanduma.";
?>
