<?php
$l_move_title 		 = "Varpimine";
$l_move_turn		 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et varpida.";
$l_move_failed		 = "Varpimine eba&otilde;nnestus!";
$l_rs_title        = "Liikumine avakosmoses";
$l_rs_whichsector  = "Kuhu sektorisse Sa soovid lennata?";
$l_rs_insector     = "Sa oled praegu sektoris [sector] ja Sa v&otilde;id lennata sektoritesse 1 kuni [sector_max].";
$l_rs_submit       = "Arvuta";
$l_rs_movetime     = "Praeguste mootoritega v&otilde;tab see reis aega [triptime] k&auml;iku.";
$l_rs_energy       = "Teel olles genereeritakse [energy] &uuml;hikut energiat";
$l_rs_noturns      = "Sule ei ole piisavalt k&auml;ike, et seda reisi ette v&otilde;tta.";
$l_rs_engage_link  = "K&auml;ivita";
$l_rs_engage       = "Sul on [turns] k&auml;iku. [engage] mootorid?";
$l_rs_invalid = "Sa ei saa realspace kõnealuse sektori siit.";
$l_rs_ready        = "Oled j&otilde;udnud sektorisse [sector]. Sa kulutasid selleks [triptime] k&auml;iku ja genereerisid [energy] &uuml;hikut energiat.";
$l_warp_invalid = "Sa ei saa sulatada kõnealuse sektori siit.";
$l_move_unknown = "Teadmata Movetype";
?>
