<?php
$l_login_title        ="Logi sisse";
$l_login_pw           ="Parool:";
$l_login_chooseres    ="Ei suuda m&auml;&auml;rata Su ekraani resolutsiooni. Palun vali l&auml;hedasim:";
$l_login_newp         = "Kui Sa oled uus m&auml;ngija, vajuta <A HREF=\"new_player.php\">siia</A>.";
$l_login_prbs         = "Probleemid?";
$l_login_emailus      = "Kirjuta meile.";
$l_login_forgot_pw    = "Unustasid oma parooli? J&auml;ta see lahter t&uuml;hjaks ja vajuta 'Logi sisse'.";
$l_login_settings     = "M&auml;ngu parameetrid";
$l_login_change       = "Muuda";
$l_login_title2 = "Main Sisselogimine AATraders";
$l_login_reset1 = "Nr Nulli Plaaniline";
$l_login_reset2 = "Plaaniline Nulli:";
$l_login_reset3 = "Sched Nulli:";
$l_login_notice = "Important Notice:";
$l_login_endadminnews = "Lõpp Admin Uudised";
$l_login_tourney_signup = "Turniiri Kirjautumiset Enabled";

$l_login_profile_only = "Profiil Ainult";
$l_login_newclosed_message = "Uued registreerujad Suletud";
$l_login_tourneymode = "Käimasolevad turniirid";
$l_login_tourneystarts = "Algus:";
?>
