<?php
$l_ship2_buytitle = "Ostmine uus laev";
$l_ship2_storetitle = "Shipyard hoidla";
$l_ship2_wrongclass = "Vale laeva klassi nimetatud";
$l_ship2_buying = "Kui ostad:";
$l_ship2_tradein = "Kauplemine:";
$l_ship2_value = "Jooksev Laev Maksumus:";
$l_ship2_newvalue = "Uus laev Maksumus:";
$l_ship2_totalcost = "Kogumaksumus:";
$l_ship2_nomoney = "Sul ei ole piisavalt krediiti osta see laev.";
$l_ship2_purchase = "Ostma";
$l_ship2_buynstore = "Osta uus laev ja säilitada vana";
$l_ship2_nomoney2 = "Sul ei ole piisavalt krediiti, et tehingu sooritamiseks.";
$l_ship2_paystorage = "Teie kaotanud oma laeva laost.";
$l_ship2_turns = "Sa pead vähemalt [turns] selgub, et seda funktsiooni";
$l_ship2_error = "Sisemine viga. Ei leia laeva klass.";
$l_ship2_owned = "Sa juba ise selle mudeli laevale.";
$l_ship2_shipbought = "Te olete just ostnud uue laeva!";

?>
