<?php
$l_feedback_title      ="Tagasiside";
$l_feedback_to         ="Saaja:";
$l_feedback_from       ="Saatja:";
$l_feedback_topi       ="Pealkiri:";
$l_feedback_feedback   ="Tagasiside";
$l_feedback_message    ="Teade:";
$l_feedback_messent    ="Tagasiside info saadetud";
$l_feedback_subj = "AATraders-mängu Tagasiside";
$l_feedback_info       ="Palun saada tagasisidet ainult eesti v&otilde;i inglise keeles."; // gameadmins put all your languages here
?>
