<?php
$l_defense_deploy_title       ="Sektori kaitsete paigutamine";
$l_defense_deploy_noturn      ="Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et sektori kaitseid paigutada.";
$l_defense_deploy_nopermit    ="Siia sektorisse ei ole lubatud sektori kaitseid paigutada.";
$l_defense_deploy_nodeploy    ="Siia ei saa sektori kaitseid paigutada. Siin on juba mingi tese liidu v&otilde;i m&auml;ngija sektori kaitsed.";
$l_defense_deploy_info1       ="Sa oled praegu sektoris [sector]. Siin on praegu [mines] miini ja [fighters] h&auml;vitajat.";
$l_defense_deploy_info2       ="Sul on pardal [mines] miini ehk torpeedot ja [fighters] h&auml;vitajat.";
$l_defense_deploy_deploy      ="Paiguta";
$l_defense_deploy_deployed    ="Paigutatud"; //not used any more
$l_defense_deploy_att         ="r&uuml;nnak";
$l_defense_deploy_notorps     ="Sul ei ole piisavalt torpeedosid.";
$l_defense_deploy_nofighters  ="Sul ei ole piisavalt h&auml;vitajaid";
$l_defense_deploy_dmines      ="Paigutasid [mines] miini.";
$l_defense_deploy_dfighter = "Tarvitusele [fighters] hävitajaid.";
$l_defense_deploy_max_fighters = "See sektor võib toetada maksimaalselt [amount] hävitajaid.";
$l_defense_deploy_toomanyfighters = "Proovisid kasutada rohkem hävitajaid kui sektor on valmis toetama.";
?>
