<?php
$l_autotrade_title = "Auto Traderoute Menüü";
$l_autotrade_dismiss2 = "Auto Traderoutes kustutatud.";
$l_autotrade_report = "Auto Traderoute Aruanne";
$l_autotrade_planet = "Planeet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energeetika";
$l_autotrade_capacity = "Capacity";
$l_autotrade_goods = "Kaubad Hind";
$l_autotrade_ore = "Ore Hind";
$l_autotrade_organics = "Organics Hind";
$l_autotrade_energy = "Energeetika Hind";
$l_autotrade_colonist = "Kolonist Hind";
$l_autotrade_credits = "Kaubandus Autorid";
$l_autotrade_delete = "Kustutama <br> Marsruut";
$l_autotrade_unnamed = "Nimetu";
$l_autotrade_noroute = "No Route";
$l_autotrade_sector = "Sektor";
$l_autotrade_credit2 = "Autorid";
$l_autotrade_deletebutton = "Kustutama";
$l_autotrade_noroute2 = "Sa ei ole seadistus igal Auto Traderoutes.";
?>
