<?php
$l_opt2_title           = "Seadete salvestamine";
$l_opt2_passunchanged   = "Parool j&auml;eti muutmata.<BR><BR>";
$l_opt2_srcpassfalse    = "Praegune parool ei olnud &otilde;ige. Parool j&auml;eti muutmata.<BR><BR>";
$l_opt2_newpassnomatch  = "Uued paroolid ei olnud &uuml;hesugused. Parool j&auml;eti muutmata.<BR><BR>";
$l_opt2_passchanged     = "Parool muudetud.<BR><BR>";
$l_opt2_passchangeerr   = "Viga parooli muutmisel<BR><BR>";
$l_opt2_userintup       = "Kasutajaliidese seaded uuendatud.<BR><BR>";
$l_opt2_userintfail     = "Kasutajaliidese seadete muutmine eba&otilde;nnestus.<BR><BR>";
$l_opt2_chlang          = "Kasutusele v&otilde;eti [lang] keel.<p>";
$l_opt2_chtemplate = "Mall on seatud [template]. <p>";
$l_opt2_dhtmlup         = "D&uuml;naamilise html-i seaded uuendatud.<BR><BR>";
$l_opt2_dhtmlfail       = "D&uuml;naamilise html-i seadete muutmine eba&otilde;nnestus.<BR><BR>";
$l_opt2_shipnamechanged = "Shipname muuta [name]. <BR><BR>";
$l_opt2_playernamechanged = "Mängija nimi on muudetud, et [name] ja [amount] krediiti maha Teie laev võtta. <BR><BR>";
$l_opt2_mapwidth = "Kohalikud ja Galaxy Kaart Laius:";
?>
