<?php
$l_shipyard_title = "Laevatehas";
$l_planet         = "Planeet";
$l_ship_welcome = "Tere tulemast Planetary laevatehases. Pakume praegu neid mudeleid müügiks.";
$l_ship_class = "Klass";
$l_ship_properties = "Klassi omaduste";
$l_ship_current = "Praegune";
$l_ship_outstorage = "Kao Storage";
$l_ship_storagecost = "Storage cost";
$l_ship_storagewarn = "Kui te kasutate Pioneer läbi ladustamise siis lahti see, mida on välja antud pärast oma esialgse laeva hävitamiseks.";
$l_ship_levels = "Laev Komponendid Tase";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Hind";
$l_ship_turns = "Turns ehitada";
$l_ship_purchase = "Ostma";
$l_ship_stored = "Salvestatud";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Keskmine maksimaalne Tech Tase:";
$l_ship_averagenormaltech = "Keskmine Tavaline Tech Tase:";
$l_ship_averagecurrenttech = "Keskmine Jooksev Tech Tase:";
?>
