<?php
$l_login_sclosed        = "Server on suletud";
$l_login_closed_message ="Server on suletud kuni j&auml;rgmiste teadeteni.";
$l_login_title2         ="Sisse logimise teine faas";
$l_login_banned         ="<b>M&auml;ngu administraator on Su sellest m&auml;ngust eemaldanud. Sellel serveril Sa enam m&auml;ngida ei saa. K&auml;itu j&auml;rgmine kord paremini.</b>";
$l_login_died           ="Su laev h&auml;vitati, aga Su p&auml;&auml;stekapsel s&auml;&auml;stis nii Sind kui Su meeskonda.  Vajuta <A HREF=main.php>siia</A> et j&auml;tkata m&auml;ngu uue laevaga.";
$l_login_newbie         ="L&auml;htudes selle kuriteo t&otilde;sidusest ja j&otilde;hkrusest Sinu vastu otsustas F&ouml;deratsioon tasuda Sinu j&auml;&auml;nuste kloonimise kulud. Kahjuks ei anta isegi t&auml;nap&auml;eval kloonidele omandit, v&auml;lja arvatud esmatarbekaubad.  Sind varustati algelise laeva ja v&auml;ikese rahasummaga, et Sul oleks kusagilt alustada. Loodetavasti kujuneb Su uus elu ilusamaks...";
$l_login_newlife        ="Vajuta <A HREF=main.php>siia</A> et j&auml;tkata oma uut elu.";
$l_login_looser         ="Sul ei olnud p&auml;&auml;stekapslit ja kuna Su areng eelmises elus ei olnud just eriti peadp&ouml;&ouml;ritav, siis keeldus F&ouml;deratsioon Su kloonimisest. Su j&auml;&auml;nused langevad ilmselt m&otilde;nda Musta Auku, et kunagi kusagil mujal uuele elule alus panna... m&otilde;ne miljardi aasta p&auml;rast.<BR><BR> Ehk veab Sul uues m&auml;ngus rohkem...";
$l_login_4gotpw1        = "Parool ei olnud &otilde;ige.<BR><BR>  Kui Sa oled oma parooli unustanud, siis ";
$l_login_4gotpw2        = "ja see saadetakse Sulle e-mailile.<BR><BR>  Vastasel juhul";
$l_login_4gotpw3        = "et uuesti proovida. See &uuml;ritamine kirjutati logisse, aadress";
$l_login_noone          = "Sellist m&auml;ngijat ei ole! - Tee <A HREF=new_player.php>siin</A> uus m&auml;ngija.";
$l_login_diedincident = "Sul on surnud jube vahejuhtum.";
$l_login_blackbox = "on blackbox teavet, mis oli laaditud oma laevade riismed.";
$l_new_login = "minna login screen.";
$l_login_playerlimit = "Server on maksimaalne arv mängijaid, mida ta toetab. Logige hilisemal ajal.";
?>
