<?php
$l_warp_unlinked      = "Sihtpunktist (sektor [target_sector]) ei ole varp-koridori siia sektorisse.";
$l_warp_forbidtwo     = "Varp-koridori m&otilde;lema suuna h&auml;vitamine sektoriga [target_sector] ei ole lubatud.";
$l_warp_removed       = "H&auml;vitati varp-koridor sektorisse";
$l_warp_removedtwo    = "H&auml;vitati m&otilde;lemasuunaline varp-koridor sektoriga";
$l_warp_nomoney = "Sul ei ole piisavalt krediiti kustutada lõime seost.";
$l_warp_noenergy = "Sul ei ole piisavalt energiat, et kustutada lõime seost.";
?>
