<?php
$l_autoroute_missingwarp = "Järgmine warplink puudub selles valdkonnas. Warp liikuda aborted.";
$l_autoroute_SDabort = "Move Katkestatud tõttu Sector keinojasi sektoris.";
$l_autoroute_turns = "Maha [triptime] Turns ja kolis [targetlink]";
$l_autoroute_noturns = "Olete välja lülitab.";
$l_autoroute_title = "Auto Marsruudid";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination = "Auto Route Sihtkoht";
$l_autoroute_warps = "Auto Route vaierid";
$l_autoroute_deleteroute = "Kustuta Marsruut";
$l_autoroute_info = "Vajuta Start sektori Realspace kõnealuse sektori ja alustada koolutamine sihtkohta sektoris.";
$l_autoroute_delete2 = "Kustuta Marsruudid";
$l_autoroute_noroutes = "Nr Auto Marsruudid";
$l_autoroute_createroute = "Loo uus Auto Route";
$l_autoroute_deleted = "Auto Marsruudid välja.";
$l_autoroute_return = "Tagasi Auto Route Kliki";
$l_autoroute_created = "Auto Route on loodud.";
$l_autoroute_realmove = "Realspace liikuda sektor";
$l_autoroute_warpmove = "Warp liikuda järgmise sektori";
$l_autoroute_warpfinal = "Warp liikuda lõpliku sektor";
$l_autoroute_editname = "Muuda nimi";
?>
