<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Welcome to Casino, pakume praegu järgmine Mängud ja Teenused";
$l_casino_option = "&quot;Toad";
$l_casino_detail = "&quot;Kirjeldus";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Tulemus";
$l_firsthand = "&quot;Esimene Hand";
$l_secondhand = "&quot;Second hand";
$l_insurance = "&quot;Kindlustus";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Tükeldama";
$l_credits = "Autorid";
$l_yourbet = "&quot;Teie ennustus";
$l_nobet = "&quot;Sinu ennustus on ületanud oma krediidilimiiti, palun bet uuesti.";
$l_dealerwins = "Diiler võidab!";
$l_dealerbust = "Vahendaja Bust!";
$l_dealerloses = "Vahendaja Loses!";
$l_dealerblackjack = "Diiler Jack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Mängija võidab!";
$l_playerbust = "&quot;Mängija Busts!";
$l_playerloses = "&quot;Mängija kaotab!";
$l_playerblackjack = "&quot;Mängija BlackJack!";
$l_place_bet = "&quot;Tehke oma panus";
?>
