<?php
$l_ze_title    = "Tsooni muutmine";
$l_ze_notowner = "Sa ei ole selle tsooni omanik, seega ei saa Sa selle reegleid muuta.";
$l_ze_name     = "Tsooni nimi";
$l_ze_allow    = "Luba";
$l_ze_attacks  = "Luba laevade r&uuml;ndamine";
$l_ze_genesis  = "Luba uute planeetide tekitamine";
$l_ze_return   = "et minna tsooni info lehele";
$l_ze_saved    = "Muudatused salvestatud.";
$l_ze_namematch = "VIGA: Ala nimi andsite on sarnane või sobib olemasolevate Ala nimi.";
?>
