<?php
$l_new_pwis              = "Su parool on";
$l_new_charis            = "Su m&auml;ngija nimi on";
$l_new_title2            = "Uue m&auml;ngija loomise teine faas";
$l_new_blank             ="e-mail, laeva nimi ega m&auml;ngijanimi ei tohi t&uuml;hjaks j&auml;&auml;da.";
$l_new_inuse             ="See e-maili aadress <B>[username]</B> on juba kasutusel.";
$l_new_forgotpw          ="Unustasid parooli?";
$l_new_inusechar         ="M&auml;ngija nimi </B>[character]</B> on juba kasutusel.";
$l_new_similar_inusechar ="M&auml;ngija nimi on liiga sarnane kasutusel oleva nimega <B>[character]</B>.";
$l_new_inuseship         ="Laeva nimi <B>[shipname]</B> on juba kasutusel.";
$l_new_similar_inuseship = "Su laeva nimi on liiga sarnane kasutusel oleva nimega <B>[shipname]</B>.";
$l_new_pwsent            ="Parool on saadetud aadressile [username].";
$l_new_err               ="Palun proovi uuesti";
$l_new_topic             ="NGS:TKI parool";
$l_new_message           ="Tervitus,\n\nKeegi IP-aadressilt $ip soovis, et Sulle saadetaks Sinu NGS:TKI parool.\n\nSu parool on: [pass]\n\nAitäh\n\nNGS:TKI veebitiim.";
$l_new_invalidemail = "E-posti aadress.";
$l_new_tutorial = "Loe siit Mini-Loengumaterjal enne sisse logida mängu.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "minna login screen.";
?>
