<?php
$l_mail_title     ="Parooli saatmine";
$l_mail_noplayer  ="Sellist m&auml;ngijat ei ole! - Tee <A HREF=new_player.php>siin</A> uus m&auml;ngija.";
$l_mail_sent      ="Parool on saadetud aadressile";
$l_mail_topic     ="$game_name parool";
$l_mail_message   ="Tervitus,\n\nKeegi aadressilt $ip soovis saada parooli m&auml;ngule $game_name.\n\nSu parool on: [pass]\n\nAit&auml;h\n\n$game_name veebitiim.";
$l_new_login      ="et minna sisse logimise men&uuml;&uuml;sse.";
$l_mail_failed = "Parool suutnud saata";
?>
