<?php
$l_artifact_title = "Too Tehis";
$l_artifact_list_title = "Nimekiri Omandatud esemeid";
$l_artifact_noscan = "Teie skannerid ei leia artefaktist.";
$l_artifact_noturn = "Sul ei ole piisavalt pööret kiirenemist käesoleva artefaktist.";
$l_artifact_classname = "Tehis Nimi";
$l_artifact_description = "Tehis kirjeldus";
$l_artifact_imagename = "Tehis Pildid";
$l_artifact_incomplete = "Tehis Pieces";
$l_artifact_process = "Kasutage Teostatud Tehis";

?>
