<?php
$l_warp_linkto     = "Siit sektorist v&auml;ljuvad varp-koridorid j&auml;rgmistesse sektoritesse:";
$l_warp_nolink     = "Sellest sektorist ei v&auml;lju &uuml;htegi varp-koridori.";
$l_warp_query     = "Millisesse sektorisse Sa soovid luua varp-koridori?";
$l_warp_oneway     = "&Uuml;hesuunalist";
$l_warp_dest     = "Sa v&otilde;id ka h&auml;vitada varp-koridore.";
$l_warp_destquery   = "Millise sektori varp-koridori Sa h&auml;vitada soovid?";
$l_warp_bothway     = "M&otilde;lemad suunad";
$l_warp_create = "Loo lõime seost Valdkond:";
$l_warp_andsector = "ja Sektor:";
$l_warp_distance = "kusjuures vahemaa";
$l_warp_lightyears = "valgusaasta";
$l_warp_delete = "Kustuta lõime seost Valdkond:";
$l_warp_costcreate = "Kulud, et luua:";
$l_warp_costdelete = "Kulud kustutada:";
$l_warp_costenergy = "Energia vaja:";
$l_warp_twoerror   = "Kahesuunalise varp-koridori loomine sektoriga [target_sector] ei ole lubatud.";
?>
