<?php
$l_scan_title     = "Laeva skaneering";
$l_scan_turn      = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et teist laeva skaneerida.";
$l_scan_ron       = "Skaneerisid laeva";
$l_scan_capt      = "mille omanik on";
$l_scan_arma      = "Varustus:";
$l_scan_carry     = "Laadung:";
$l_scan_bounty    = "Selle laeva eest on kokku [amount] raha suurune pearaha v&auml;lja pandud.";
$l_scan_fedbounty = "Selle laeva eest on F&ouml;deratsioon pearaha v&auml;lja pannud.";
$l_by_nofedbounty = "Selle m&auml;ngija r&uuml;ndamise eest <B>EI</B> pane F&ouml;deratsioon Su laeva eest pearaha v&auml;lja.";
?>
