<?php
$l_beacon_title          = "Majaka seadmine";
$l_beacon_notpermitted   = "Siia sektorisse ei tohi majakaid p&uuml;stitada.";
$l_beacon_reads          = "Praegune majakas teatab";
$l_beacon_none           = "Siin ei ole praegu majakat.";
$l_beacon_enter          = "Sisesta majaka tekst";
$l_beacon_nowreads       = "Majakas teatab n&uuml;&uuml;d";
$l_beacon_donthave       = "Sul ei ole &uuml;htegi majakat.";
?>
