<?php
$l_sf_attacking     = "Sektori kaitse h&auml;vitajad r&uuml;ndasid Sind!<BR>";
$l_sf_destfight     = "Su laserid purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_destfightb    = "Su laserid purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_torphit       = "Torpeedod tulistati v&auml;lja:";
$l_sf_destfightt    = "Su torpeedod purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_fighthit      = "H&auml;vitajad r&uuml;ndasid:";
$l_sf_destfightall  = "Sa purustasid k&otilde;ik h&auml;vitajad.<BR>";
$l_sf_destfightt2   = "Sa purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_lostfight     = "Sa kaotasid k&otilde;ik h&auml;vitajad.<BR>";
$l_sf_lostfight2    = "Sa kaotasid [lost] h&auml;vitajat.<BR>";
$l_sf_armorbreach   = "Su soomus on purustatud!<BR>";
$l_sf_armorbreach2  = "Su soomus sai [lost] punkti ulatuses vigastada.<BR>";
$l_sf_sendlog       = "[player] purustas [lost] sektori kaitse h&auml;vitajat sektoris [sector].";
$l_sf_lreport       = "Sa kaotasid [armor] soomusepunkti, [fighters] h&auml;vitajat ja kasutasid &auml;ra [torps] torpeedot.<BR><BR>";
$l_sf_shipdestroyed = "<B>Su laev on purustatud!</B><BR><BR>";
$l_sf_sendlog2      = "Sektori kaitse h&auml;vitajad purustasid m&auml;ngija [player] sektoris [sector].";
$l_sf_escape        = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!<BR><BR>";

$l_sf_fnoattack = "ei saadetaks hävitajaid rünnata oma elud.";
$l_sf_fnoattackt = "ei saadetaks hävitajaid rünnata oma torpeedod.";
$l_sf_fnoattacka = "ei saadetaks hävitajaid rünnata oma armor.";
$l_sf_flaunchmalf1 = "Teie võitleja käivitamise süsteem on malfunctioned.";
$l_sf_flaunchmalf2 = "Olete olnud suuteline käivitama";
$l_sf_flaunchmalf3 = "protsenti oma elud.";
$l_sf_fightertorpexg = "Fighter et Torpedo / Mine Börs";
$l_sf_torpfighterexg = "Laev Torpedo valdkondlike Fighter Börs";
$l_sf_fighterarmorexg = "Valdkond Fighter laeva Armor Börs";
$l_sf_tlaunchmalf1 = "Teie torpeedo käivitamise süsteem on malfunctioned.";
$l_sf_tlaunchmalf2 = "Olete olnud suuteline käivitama";
$l_sf_tlaunchmalf3 = "protsenti oma torpeedod.";
$l_sf_bountysd = "Sul on rünnanud sektori sisaldab planeet, mis annab sulle halastus kui sa ründasid planeedil. Föderatsioon on aktiveeritud automaatne ise hävitada kõik oma hävitajaid ja torpeedod. Ärge rünnaku sektori keinojasi selles sektoris uuesti. You have been warned!";
?>
