<?php
$l_att_title     = "Laeva r&uuml;ndamine";
$l_att_notarg     = "Sihtm&auml;rk ei ole selles sektoris.";
$l_att_noturn     = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et r&uuml;nnata.";
$l_att_noatt     = "Selles sektoris ei tohi kedagi r&uuml;nnata.";
$l_att_flee      = "Sihtm&auml;rk lendas eest &auml;ra!";
$l_att_ewd       = "Sihtm&auml;rk kasutas h&auml;daabi varpi!";
$l_att_att       = "R&uuml;ndad ";
$l_att_beams = "Laius Börs";
$l_att_torps = "Torpedo Börs";
$l_att_fighters = "Fighter Börs";
$l_att_lost      = "kaotas";
$l_att_ylost     = "Sa kaotasid";
$l_att_sdown     = " energiakilp on purustatud!";
$l_att_ydown     = "Su energiakilp on purustatud!";
$l_att_shits     = " energiakilp sai vigastada";
$l_att_yhits     = "Su energiakilp sai vigastada";
$l_att_dmg       = "punkti ulatuses";
$l_att_sarm      = " soomus on t&auml;ielikult purustatud!";
$l_att_yarm      = "Su laeva soomus on t&auml;ielikult purustatud!";
$l_att_ashit     = " soomus sai vigastada";
$l_att_ayhit     = "Su soomus sai vigastada";

$l_att_efhit = "&#39;s võitlejad on hävitatud.";
$l_att_yfhit = "Teie võitlejad on hävitatud.";
$l_att_ethit = "&#39;s torpeedod on hävitatud.";
$l_att_ythit = "oma torpeedod on hävitatud.";
$l_att_of = "sellest";
$l_att_lostt = "kaotas kõik torpeedod.";
$l_att_ylostt = "Sa kaotasid kõik torpeedod.";

$l_att_lostf     = "kaotas k&otilde;ik h&auml;vitajad.";
$l_att_ylostf    = "Sa kaotasid k&otilde;ik h&auml;vitajad.";
$l_att_sdest     = " laev on h&auml;vitatud!";
$l_att_espod     = "H&auml;vivast laevast eraldus p&auml;&auml;stekapsel.";
$l_att_ysalv = "Sa päästetud [ship_salvage_rate]% laeva kohta [ship_salvage] krediiti. <BR> Sinu hinnang muutnud [rating_change] punkti.";
$l_att_andused   = "ja kasutasid";
$l_att_stilship  = "Sa ei suutnud purustada [name] laeva.";
$l_att_atyou     = "r&uuml;ndas Sind";
$l_att_and       = "ja";
$l_att_yshiplost = "Su laev on purustatud!";
$l_att_salv = "[name] päästetud [ship_salvage_rate]% laeva kohta [ship_salvage] krediidi";
$l_att_loosepod	 = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";

$l_att_tnobeams = "Õmblused tuleb välja kimbu energiaga.";
$l_att_tnobeamsf = "Õmblused tuleb välja kimbu energia ja seda ei saa rünnata oma elud.";
$l_att_tnobeamst = "Õmblused tuleb välja kimbu energia ja seda ei saa rünnata oma torpeedod.";
$l_att_tfnoattack = "ei saadetaks hävitajaid rünnata oma laeva.";
$l_att_tnotorps = "tundub olevat välja torpeedod.";

$l_att_anobeams = "Sa ammendanud oma laevade kimbu energiaga.";
$l_att_anobeamsf = "Sa ammendanud oma laevade kimbu energia ja seda ei saa rünnata vaenlase hävitajaid.";
$l_att_anobeamst = "Sa ammendanud oma laevade kimbu energia ja seda ei saa rünnata vaenlase torpeedod.";
$l_att_anofighters = "Teie laev on ammendanud kõik availible hävitajaid.";
$l_att_anotorps = "Sa ammendanud oma availible torpeedod.";
$l_att_imtitle = "Laev rünnaku all";
$l_att_imbody = "ründab oma laeva.";

$l_att_luckybeams = "Enemy talad ülekoormuse tekitades";
$l_att_luckyfighters = "Vaenlase hävitajaid teha üllatus kergendada rünnak ja põhjustada";
$l_att_luckytorps = "Enemy torpeedod põhjustada kuhjuvate kahjustuste mõju põhjustab";
$l_att_luckytimes = "korda tavalise kahju!";
?>
