<?php
$l_lrs_title    = "Vaatlus";
$l_lrs_nofull   = "Su skannerid ei v&otilde;imalda t&auml;isvaatlust.";
$l_lrs_noturns  = "Sul peab olema v&auml;hemalt $fullscan_cost k&auml;ik(u), et teostada t&auml;isvaatlust.";
$l_lrs_used     = "Kasutasid";
$l_lrs_turns    = "k&auml;igu";
$l_lrs_left     = "k&auml;iku j&auml;i j&auml;rgi";
$l_lrs_reach    = "Sektorist [sector] saab varpida j&auml;rgmistesse sektoritesse:";
$l_lrs_links    = "Varp-koridorid";
$l_lrs_ships    = "Laevad";
$l_lrs_click    = "Kliki &uuml;hele linkidest, et varpida vastavasse sektorisse.";
$l_lrs_cantscan = "Seda sektorit ei saa siit vaadelda!";
$l_lrs_zero     = "Sektor 1 on liiga t&auml;is, et eristada laevu!";
$l_lrs_moveto   = "et liikuda sektorisse";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet   = "Logiraamat";
$l_lrs_fedjammed = "Föderatsioon on segamise kõik andur skaneerib.";
$l_lrs_imtitle             = "Sector Under Attack";
$l_lrs_imbody             = "is using a Sector Nova on";
$l_lrs_sectormissile_question = "tule sektori rakett.";
$l_log_months = array('jaanuar','veebruar','m&auml;rts','aprill','mai','juuni','juuli','august','september','oktoober','november','detsember');
$l_log_months_short = array('jaan','veebr','m&auml;rts','apr','mai','juuni','juuli','aug','sept','okt','nov','dets');
?>
