<?php
$l_cu_storing = "Ladustamine";
$l_cu_inistored = "<b>Kıik INI v‰‰rtused on edukalt salvestatud.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto Route Sihtkoht";
$l_cu_warps = "Auto Route vaierid";
$l_cu_deleteroute = "Kustuta Marsruut";
$l_cu_info = "Vajuta Start sektori Realspace kınealuse sektori ja alustada koolutamine sihtkohta sektoris.";
$l_cu_delete2 = "Kustuta Marsruudid";
$l_cu_noroutes = "Nr Auto Marsruudid";
$l_cu_createroute = "Loo uus Auto Route";
$l_cu_deleted = "Auto Marsruudid v‰lja.";
$l_cu_return = "Tagasi Auto Route Kliki";
$l_cu_created = "Auto Route on loodud.";
$l_cu_realmove = "Realspace liikuda sektor";
$l_cu_warpmove = "Warp liikuda j‰rgmise sektori";
$l_cu_warpfinal = "Warp liikuda lıpliku sektor";
?>
