<?php
$l_opt_title = "Valige Team Ikoon";
$l_opt_errorsize = "Viga: Sinu pilt ei tohi olla suurem kui 64x64 pikslit suurus.";
$l_opt_errortype = "Viga: Pilt peab olema JPG, GIF või PNG";
$l_opt_errornographic = "Viga: graafika valik.";
$l_opt_currentavatar = "Sinu praegune meeskond Ikoon";
$l_opt_uploadavatar = "Laadi Ikoon";
$l_opt_directory = "Valige Team Ikoon Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Valige Team Ikoon";
$l_opt_noteam = "Te ei ole meeskond.";
$l_opt_notleader = "Ainult meeskonna koordinaator saab muuta Team ikoonil.";
$l_opt_inuse = "Kõik Team ikoone selles kataloogis on kasutusel.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
