<?php
$l_opt_title      = "Seaded";
$l_opt_chpass     = "Muuda parooli";
$l_opt_curpass    = "Praegune parool:";
$l_opt_newpass    = "Uus parool:";
$l_opt_newpagain  = "Uus parool (uuesti):";
$l_opt_userint    = "Kasutajaliides";
$l_opt_usenew     = "Kasuta t&auml;ielikku kasutajaliidest?";
$l_opt_lang       = "Keel";
$l_opt_template = "Mall";
$l_opt_select     = "Vali &uuml;ks:";
$l_opt_enabled    = "Lubatud";
$l_opt_save       = "Salvesta";
$l_opt_teamicon = "Team Ikoon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Kohalikud ja Galaxy Kaart Laius:";
$l_opt_profiletitle = "Profiil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registreeritud andmed Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Kui sa registreerid oma mängija teise serveri malli shoutBox ja uudiste seaded eespool kasutatakse serveris.";
$l_opt_showshoutbox = "Näita Shoutbox:";
$l_opt_shownewscrawl = "Näita Uutisindeksoinnin:";
$l_opt_playername = "Mängija nimi:";
$l_opt_playernamecost = "Föderatsiooni Nimemuutus Fee: [amount] krediidi";
?>
