<?php
$l_footer_one_player_on = "Sisse on loginud 1 m&auml;ngija.";
$l_footer_players_on_1  = "Sisse on loginud";
$l_footer_players_on_2 = "Mängijad online:";
$l_footer_until_update  = "sekundit on j&auml;&auml;nud j&auml;rgmise uuendamiseni.";
$l_footer_no_players_on = "&Uuml;kski m&auml;ngija ei ole sisse loginud.";

$l_footer_news = "Kohalik FNN uudised";
$l_footer_title = "Alien Assault Ettevõtjad";
$l_footer_help = "abi sellest leheküljest.";
$l_footer_click = "Kliki";

$l_footer_open_slots = "Suurim Online:";
$l_footer_onlinereset = "Mängija Online Time Nulli in";
$l_footer_onlinecountdown = "Mängija Online Time Countdown:";
?>
