<?php
$l_profile_title = "Profiil Registreerimine";
$l_profile_notenabled = "Firmade ei võimaldanud selles serveris.";
$l_profile_registered = "See mängija on nüüd registreeritud Master andmed Server.";
$l_profile_nomatch = "Kas ei sobi profiili Master andmed serveri nime ja serveri parool.";
$l_profile_tryagain = "Sisestada mängija profiili nime ja serveri parool uuesti nuppu";
$l_profile_name = "Profiil Mängija nimi";
$l_profile_password = "Profiil Server Parool";
$l_profile_bannedserver = "See server ei ole lubatud esitada profiili teabe Master andmed Server.";
$l_profile_bannedplayer = "Teil on keelatud Master andmed Server ja ei tohi registreerida mängijaid.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "See server <u><b>nõuab</b></u> iga uus mängija on registreeritud profiili. Teil ei ole lubatud luua uut mängijat, kui sul on registreeritud profiili.";
$l_profile_updated = "Teie malli shoutBox ja Uutisindeksoinnin üldised seaded on uuendatud andmed Master Server. Need seaded kasutatakse automaatselt, kui te oma profiili mis tahes mängus.";

?>
