<?php
$l_readm_title       = "Teadete lugemine";
$l_readm_delete      = "Teade kustutatud";
$l_readm_nomessage   = "Sind ei oota &uuml;kski teade...<BR>";
$l_readm_center      = "Teadete keskus";
$l_readm_sender      = "Saatja";
$l_readm_captn       = "Kapten laeval";
$l_readm_del         = "Kustuta";
$l_readm_repl        = "Vasta";
$l_readm_return = "Kliki siia, et naasta peamenüüsse";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Kustuta kõik";
$l_readm_subject = "Teema";
$l_readm_quote = "Tsiteerima";
$l_readm_block = "Blokeeri Saatja";
$l_readm_alert = "System Alert";
$l_readm_alertbody = "Laev Arvuti";
?>
