<?php
$l_news_title		 = "Universumi Uudised";
$l_news_info		 = "FNN on koos galaktika valitsejatega,<br>et vahendada uudiseid ja infot.<br>Me t&ouml;&ouml;tame 24 tundi p&auml;evas ja 7 p&auml;eva n&auml;dalas<br>FNN'i galaktilises peakorteris <br>Proxima Centauril ja b&uuml;roodes &uuml;le terve galaktika!";
$l_news_for		 = "Uudised:";
$l_news_prev		 = "eelmine p&auml;ev";
$l_news_next		 = "j&auml;rgmine p&auml;ev";
$l_news_none		 = "T&auml;na pole &uuml;htegi uudist.";
$l_news_flash		 = "Pealkirjaveerg";
$l_news_end      = "Rohkem uudiseid hetkel pole";
$l_news_bestviewed = "Soovitatav vaadata Opera, Safari ja IE";
$l_news_fedannouncements = "Föderatsiooni Börsiteated";
$l_news_planetarynews = "Planeetide Uudised";
$l_news_planetshipnews = "Planeetide ja Laev Uudised";
$l_news_afteractionnews = "Pärast tegevuskava Combat Uudised";


?>
