<?php
$l_gns_title       = "Mateeriatorpeedo kasutamine";
$l_gns_turn        = "Et kasutada mateeriatorpeedot, peab Sul v&auml;hemalt &uuml;ks k&auml;ik olema.";
$l_gns_onplanet    = "Planeedi pinnal olles ei saa nii v&otilde;imast seadet kasutada.";
$l_gns_full        = "Selle sektori t&auml;hes&uuml;steem on juba t&auml;is.";
$l_gns_planetex    = "Selles sektoris on juba planeet.";
$l_gns_nogenesis   = "Sul ei ole &uuml;htegi mateeriatorpeedot.";
$l_gns_forbid      = "Selles sektoris ei ole lubatud mateeriatorpeedot kasutada.";
$l_gns_bforbid     = "Selle sektori baasid ei lase Sul mateeriatorpeedot kasutada.";
$l_gns_pcreate     = "Planeet loodud!";
$l_sgns_title = "Kasutage Sector Genesis Device";
$l_sgns_pcreate = "Sector [name] on loodud.";
$l_sgns_nogenesis = "Sul ei ole ühtegi sektorit Genesis seadmeid.";
$l_sgns_forbid = "Loomine sektori teke wormhole selles sektoris ei ole lubatud.";
$l_sgns_forbid1 = "Loomine sektori teke wormhole Föderatsiooni sektor ei ole lubatud.";
$l_sgcreate = "Loo uus Sector Genesis sektor";
$l_sgcreatens = "Loo uus Sector Genesis Link tagasi teada space";
$l_sgns_forbid2 = "Rohkem kui [limit] Viited SG-sektorid ei ole lubatud.";
$l_sgns_forbid3 = "Ei saa luua Sector Genesis lõime seost praeguste sektor - mis ületaks maksimaalselt [limit] sektori kohta.";
$l_sgns_nocredits = "Sul ei ole piisavalt krediiti, et luua uus valdkond.";
$l_sgns_shipcredits = "Autorid laeval:";
$l_sgns_createcost = "Kulud luua uusi Valdkond:";
$l_sgns_complete = "Tavaline kosmos Link lõpule";
$l_sgns_sectorname = "Sisestage Sector Nimi:";
$l_gns_max_unbased_planets = "Föderatsioon ei võimalda luua rohkem planeete, kuni teil on vähem kui [max_unbased_planets] unbased planeete.";


?>
