<?php
///SPIES
$l_spy_title = "Spioonimen&uuml;&uuml;";
$l_spy = "Spioonid";
$l_spy_disabled = "Spioonid ei ole kasutatavad!";
$l_spy_noturn = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et spiooni saata.";
$l_spy_notonboard = "Sul ei ole spioone pardal.";
$l_spy_ownplanet = "Spiooni ei saa saata enda planeedile.";
$l_spy_unownedplanet = "Spiooni ei saa saata omanikuta planeedile.";
$l_spy_planetfull = "Sa oled planeedile juba saatnud lubatud [max] spiooni.";
$l_spy_sendtitle = "Spiooni [spyID] saatmine planeedile:<BR>Vali spiooni missioon:";
$l_spy_type1 = " Spioon &uuml;ritab tegutseda vaid planeedil.";
$l_spy_type2 = " Spioon &uuml;ritab minna planeediga kauplevale laevale";
$l_spy_type3 = " Spioon &uuml;ritab minna planeediga kauplevale laevale, ja laevalt teisele planeedile siirduda.";
$l_spy_sendbutton = "Saada planeedile";
$l_spy_sendsuccessful = "Su spioon suutis j&otilde;uda planeedile ja ootab n&uuml;&uuml;d sobivat hetke oma &uuml;lesannete t&auml;itmiseks.";
$l_spy_sendfailed = "Su spioon tabati ja tapeti, kuna Su radarisegaja ei suutnud teda piisavalt varjata.";
$l_spy_noturn2 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et spiooni pardale v&otilde;tta.";
$l_spy_confirm = "Oled Sa kindel, et soovid spiooni [spyID] tagasi kutsuda?";
$l_spy_cleanupplanet = "et teostada planeedil spioonit&otilde;rjet.";
$l_spy_cleanupship = "Kui soovid teha spioonit&otilde;rjet oma laeval, vajuta";
$l_spy_yourspies = "Sinu spioonid sellel planeedil";
$l_spy_sendnew = "Saada uus spioon";

$l_spy_codenumber = "ID";
$l_spy_job = "T&ouml;&ouml;";
$l_spy_percent = "Protsent";
$l_spy_move = "Liikuvus";
$l_spy_action = "Tegevus";
$l_spy_shipowner = "Laeva omanik";
$l_spy_shipname = "Laeva nimi";
$l_spy_shiptype = "Laeva t&uuml;&uuml;p";
$l_spy_shiplocation = "Laeva asukoht";
$l_spy_planetowner = "Planeedi omanik";
$l_spy_planetname = "Planeet";
$l_spy_sector = "Sektor";

$l_spy_moves['none'] = "Ei liigu";
$l_spy_moves['toship'] = "Laevale";
$l_spy_moves['toplanet'] = "Planeedile";

$l_spy_comeback = "Kutsu tagasi";
$l_spy_nospieshere = "Siin planeedil ei ole Sinu spioone";
$l_spy_transferred = "spiooni &uuml;le kantud";
$l_spy_backonship = "Spioon on laevale saabunud.";
$l_spy_backfailed = "Kutsumine eba&otilde;nnestus.";
$l_spy_changetitle = "Spiooni [spyID] omadusete muutmine:";
$l_spy_occupied = "Su spioon [spyID] t&ouml;&ouml;tab planeedil kui [job], protsendiga [percent].";
$l_spy_dismiss = "Lase spioon lahti?";
$l_spy_changebutton = "Muuda";
$l_spy_changejob = "Vahetada töökohta või liikumine";
$l_spy_linkback = "et minna tagasi spioonimen&uuml;&uuml;sse.";
$l_spy_changed1 = "Spiooni liikuvus uuendatud.";
$l_spy_changed2 = "Spioon lahti lastud ja tema liikuvus uuendatud.";
$l_spy_changefailed = "Muutmine eba&otilde;nnestus.";
$l_spy_cleanupplanettitle = "Planeedi puhastamine vastase spioonidest:";
$l_spy_notyourplanet = "See pole sinu planeet.";
$l_spy_cleanuptext[1] = "Kiirpuhastus. Kulutab [creds] raha ja [turns] k&auml;iku.";
$l_spy_cleanuptext[2] = "T&otilde;hus puhastus. Kulutab [creds] raha ja [turns] k&auml;iku.";
$l_spy_cleanuptext[3] = "Parim puhastus. Kulutab [creds] raha ja [turns] k&auml;iku.";
$l_spy_cannotcleanupplanet = "Sul on ainult [credits] raha sellel planeedil ja [turns] k&auml;iku.";
$l_spy_cleanupbutton1 = "Alusta planeedi puhastust";
$l_spy_cleanupplanettitle2 = "Sa l&uuml;litasid oma radarid t&auml;isv&otilde;imsusel t&ouml;&ouml;le, et jahtida spioone sellel planeedil.";
$l_spy_spyfoundonplanet = "Sellelt planeedilt leiti m&auml;ngija [player] spioon [spyID], kes kohe h&auml;vitati!";
$l_spy_spynotfoundonplanet = "Su radarid ei avastanud sellelt planeedilt &uuml;hegi m&auml;ngija spioone.";
$l_spy_notenough = "Sul pole piisavalt raha v&otilde;i k&auml;ike spioonide t&otilde;rjeks.";

$l_spy_cleanupshiptitle = "Laeva puhastamine vastase spioonidest:";
$l_spy_notinspecial = "Sa pead olema sadamas 'Seadmed', et oma laeval spioonit&otilde;rjet teha.";
$l_spy_cleanupshiptext[1] = "Kiirpuhastus. Kulutab [creds] raha ja [turns] k&auml;iku.";
$l_spy_cleanupshiptext[2] = "T&otilde;hus puhastus. Kulutab [creds] raha ja [turns] k&auml;iku.";
$l_spy_cleanupshiptext[3] = "Parim puhastus. Kulutab [creds] raha ja [turns] k&auml;iku.";
$l_spy_cannotcleanupship = "Sul on ainult [credits] raha ja [turns] k&auml;iku.";
$l_spy_cleanupbutton2 = "Alusta laeva puhastust";
$l_spy_cleanupshiptitle2 = "Sa l&uuml;litasid oma radarid t&auml;isv&otilde;imsusel t&ouml;&ouml;le, et jahtida spioone oma laeval.";
$l_spy_spyfoundonship = "Su laevalt leiti m&auml;ngija [player] spioon [spyID], kes kohe h&auml;vitati!";
$l_spy_spynotfoundonship = "Su radarid ei avastanud laevalt &uuml;hegi m&auml;ngija spioone.";

$l_spy_infodeleted = "Teade kustutatud";
$l_spy_infonotyours = "See ei ole Sinu spiooni teade.";
$l_spy_noinfo = "Su spioonid ei ole mingit infot kogunud.";
$l_spy_infotitle = "V&otilde;&otilde;rastel laevadel olevate spioonide kogutud info";
$l_spy_time = "Aeg";
$l_spy_type = "T&uuml;&uuml;p";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planeet";
$l_spy_datatext[1] = "Sektoris [sector] on m&auml;ngija [player] planeet [planet].";
$l_spy_delete = "Kustuta";
$l_spy_messages = "et n&auml;ha spioonide teateid.";
$l_spy_defaulttitle1 = "Spioonid v&otilde;&otilde;rastel laevadel";
$l_spy_defaulttitle2 = "Spioonid v&otilde;&otilde;rastel planeetidel";
$l_spy_defaulttitle3 = "Spioonid oma planeetidel";
$l_spy_defaulttitle4 = "Spioonid oma laeval";

$l_spy_no1 = "Sul ei ole &uuml;htegi spiooni &uuml;helgi v&otilde;&otilde;ral laeval.";
$l_spy_no2 = "Sul ei ole &uuml;htegi spiooni &uuml;helgi v&otilde;&otilde;ral planeedil.";
$l_spy_no3 = "Sul ei ole &uuml;htegi spiooni &uuml;helgi oma planeedil.";
$l_spy_no4 = "Sul ei ole &uuml;htegi spiooni oma laeval.";
$l_spy_nospiesatall = "Sul ei ole &uuml;htegi spiooni.";
$l_spy_notknown = "Ei tea";

$l_spy_trytitle = "Spioon p&uuml;&uuml;ab planeedil olles";

$l_spy_cantsendfeds = "Vabandust, aga Spies ei saa saata Föderatsiooni iseseisev planeet.";
$l_spy_cantsendteam = "Sa ei saa panna Spies kohta meeskonnakaaslased planeedil.";
$l_spy_messagesdeleted = "Kõik sõnumid on kustutatud";
$l_spy_deleteall = "Kustuta kõik";
$l_spy_onplanet = "Spies planeedil";
$l_spy_menu = "tagasi Spy Menüü.";
?>
