<?php
$l_sn_title = "Valdkond Märkused";
$l_sn_pntitle = "Sektorites Isiklikud märkmed";
$l_sn_tntitle = "Sektorites Team Märkused";
$l_sn_psntitle = "Personaalsed Sector Märkused";
$l_sn_tsntitle = "Team Sector Märkused";
$l_sn_editnote = "Muuda Sector Märkus:";
$l_sn_deleteedit = "Kustuta või Muuda:";
$l_sn_addnote = "Lisa Sector Märkus:";
$l_sn_list = "Nimekiri Sektorid Märkused";
$l_sn_listts = "Nimekiri Sektorid, mille meeskond Märkused";
$l_sn_addteam = "Lisa võistkond";
$l_sn_deleteteam = "Kustuta Team";
$l_sn_delete = "Kustutama";
$l_sn_saveteam = "Salvesta Team";
$l_sn_deletepersonal = "Kustuta Isiklik";
$l_sn_addpersonal = "Lisa Isiklik";
$l_sn_savepersonal = "Salvesta isiklik";
$l_sn_editpersonal = "Muuda Isiklik";
$l_sn_editteam = "Muuda meeskonda";

$l_sn_hdsector = "Sektor";
$l_sn_hdtype = "Tüüp";
$l_sn_hdowner = "Omanik / Team";
$l_sn_hdplanets = "Planeedid";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Kaevandus";
$l_sn_hdscanfrom = "Scan Kellelt";
$l_sn_hddetail = "Täpsusta";
$l_sn_hddate = "Date / Time";
$l_sn_hddelete = "Kustutama";
$l_sn_hdteam = "Meeskond";
$l_sn_view = "Vaade";
$l_sn_no = "Ei";
$l_sn_yes = "Jah";
$l_sn_nonotes = "Nr sektoris märgib Leitud";

?>
