<?php
$l_contact_admin_title = "Kontakt Mäng Administraator";
$l_contact_admin_thanks = "Thanks for your comment.";
$l_contact_admin_email_alert = "Palun sisesta kehtiv e-posti aadress.";
$l_contact_admin_name_alert = "Palun sisestage oma nimi.";
$l_contact_admin_comment_alert = "Palun sisestage oma kommentaare.";
$l_contact_admin_name = "Nimi";
$l_contact_admin_email = "E-post";
$l_contact_admin_comment = "Question / Comment";
$l_contact_admin_submit = "Saada Küsimused / Kommentaarid";
$l_contact_admin_close = "Sulge aken";
$l_contact_admin_thanks_comment = "Täname kommentaar või küsimus. Me kõikidele küsimustele ja meilis meie vastuseks.";

?>
