<?php
///SPIES
$l_dig_title = "Aukandja Menüü";
$l_dig = "Aukandjate";
$l_dig_disabled = "Dignataries on keelatud!";
$l_dig_noturn = "Sa vajad vähemalt ühte omakorda saata aukandja et planeedil.";
$l_dig_notonboard = "Sul ei ole aukandja pardal.";
$l_dig_ownplanet = "Sa ei saa postitada aukandja et vaenlase planeeti.";
$l_dig_unownedplanet = "Sa ei saa postitada aukandja et unowned planeedil.";
$l_dig_planetfull = "Juba praegu on lubatud [max] aukandjate sellel planeedil.";
$l_dig_sendtitle = "Saadan aukandja [digID], et planeet: <BR> Valige aukandja missioon:";

$l_dig_codenumber = "Kood";
$l_dig_job = "Töö";
$l_dig_percent = "Protsenti";
$l_dig_move = "Liikumine";
$l_dig_action = "Action";
$l_dig_shipowner = "Laevaomanik";
$l_dig_shipname = "Laeva nimi";
$l_dig_shiptype = "Laev klass";
$l_dig_shiplocation = "Laev Asukoht";
$l_dig_planetowner = "Planet Omanik";
$l_dig_planetname = "Planeet";
$l_dig_sector = "Sektor";

$l_dig_waiting = "Ootan Töö";
$l_dig_max = "Suurim Per Planet";
$l_dig_legend = "Aukandja Legend";
$l_dig_description = "Aukandja kirjeldus";
$l_dig_waiting_description = "Aukandja loob torpeedod ja hävitajaid oodates töö üleandmist.";
$l_dig_changeerror = "Aukandja Töö muutuse aruanne";

$l_dig_nospieshere = "Sul ei ole aukandjate siin planeedil!";
$l_dig_transferred = "aukandjate üle";
$l_dig_backonship = "Aukandja on nüüd oma laeva.";
$l_dig_dismiss = "Visake aukandja?";
$l_dig_changebutton = "Muutma";
$l_dig_notyourplanet = "See ei ole teie planeedil.";

$l_dig_defaulttitle1 = "Aukandjate kohta vaenlase laevade";
$l_dig_defaulttitle2 = "Aukandjate oma planeedid";
$l_dig_defaulttitle3 = "Aukandjate oma planeedid";
$l_dig_defaulttitle4 = "Aukandjate oma laeva";

$l_dig_no1 = "Sul ei ole aukandjate kohta vaenlase laevu.";
$l_dig_no2 = "Sul ei ole aukandjate oma planeedid.";
$l_dig_no3 = "Sul ei ole aukandjate oma planeedid.";
$l_dig_no4 = "Sul ei ole aukandjate oma laeva.";
$l_dig_nodignitaryatall = "Sul ei ole aukandjate.";
$l_dig_notknown = "Unknown";
$l_dig_dismiss = "Loobu";
$l_dig_dismiss2 = "Aukandjate rahuldamata.";
$l_dig_menu = "tagasi aukandja Menüü.";

?>
