<?php
$l_die_title     = "Eneseh&auml;vitus";
$l_die_rusure    = "Kas Sa oled kindel, et tahad oma laeva h&auml;vitada? See eemaldab Su sellest m&auml;ngust.";
$l_die_goodbye   = "H&uuml;vasti, julm galaktika!";
$l_die_check     = "Kas Sa oled ikka p&auml;ris kindel, et Sa soovid sellest m&auml;ngust lahkuda?";
$l_die_nonono    = "EI! EI! EI!";
$l_die_what      = "Mida ma k&uuml;ll m&otilde;tlesin?";
$l_die_count     = "5.. 4.. 3.. 2.. 1.. H&auml;ving!";
$l_die_vapor     = "Su laev aurustus koos meeskonna ja laadungiga.";
$l_die_please1   = "logi v&auml;lja";
$l_die_please2   = "Palun [logout_link]";
$l_die_exploit   = "&Auml;ra m&auml;ngi asjadega, millest Sa aru ei saa.";
?>
