<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: ShoutBoxis::.";
$l_shout_public = "Avalik";
$l_shout_team = "Meeskond";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "muu";
$l_shout_refresh = "Värskenda";
$l_shout_close = "Sulge aken";
$l_shout_saved = "Shout salvestatud!";
$l_shout_return = "Tagasi";
$l_shout_prev = "Eelmine";
$l_shout_next = "Järgmine";
$l_shout_selectpage = "Vali lehekülg";
$l_shout_page = "Leht:";
$l_shout_teamtitle = ".:: MEESKOND ShoutBoxis::.";
?>
