<?php
$l_warp_cantsame   = "Sa ei saa luua varp-koridori, mille algus- ja l&otilde;ppsektor on samad.";
$l_warp_twoerror   = "Kahesuunalise varp-koridori loomine sektoriga [target_sector] ei ole lubatud.";
$l_warp_sectex     = "Ei saa tekitada veel &uuml;hte varp-koridori sellest sektorist - k&otilde;ik lubatud $link_max koridori sektori kohta on juba olemas.";
$l_warp_linked     = "Sihtpunkti (sektor [target_sector]) on siit juba varp-koridor olemas.";
$l_warp_coneway    = "Loodi &uuml;hesuunaline varp-koridor sektorisse";
$l_warp_ctwoway    = "Loodi kahesuunaline varp-koridor sektoriga";
$l_warp_nomoney = "Sul ei ole piisavalt krediiti, et luua lõime seost.";
$l_warp_noenergy = "Sul ei ole piisavalt energiat, et luua lõime seost.";
?>
