<?php
$l_sm_title = "Valdkond raketistardi";
$l_sm_invalid = "Ei ole lõime seost selles sektoris ning sihtkoha sektoris.";
$l_sm_notarg = "Target ei ole selles sektoris.";
$l_sm_noturn = "Sa vajad vähemalt ühte omakorda tule oma Sector rakett.";
$l_sm_nosectormissile = "Sa ei ole kaasas kõiki kõnealuse sektori Raketid.";
$l_sm_noscan = "Andurid ei saa kinnitada seatud!";
$l_sm_flee = "Sihi läbi maneuvered Sector rakettide!";
$l_sm_ewd = "Target tööle erakorralise sulatada seade, kui see avastatakse Sector rakettide!";
$l_sm_imtitle = "Laev rünnaku all";
$l_sm_imbody = "[playername] ründab oma laeva Sektori rakettide!";
$l_sm_sectormissilefail = "Valdkond rakettide malfunctioned kui see tabab vaenlase laevade kilp!";
$l_sm_sectormissilefail2 = "Valdkond rakettide malfunctioned kui see tabab vaenlase laevade armor!";
$l_sm_shieldhit = "[target] &quot;s kilbid löögi eest [amount] kahju!";
$l_sm_shieldsdown = "[target] &quot;s kilbid on maas!";
$l_sm_armorhit = "[target] &quot;s armor on tabanud on [amount] kahju!";
$l_sm_armorbreached = "[target] &quot;s Armor rikkus!";
$l_sm_targetnoenergy = "Vaenlase laev ei ole mingit energiat! Valdkond rakettide ei!";
$l_sm_attacking = "Võitlus [target] pardal [shipname]";
$l_sm_targetok = "Sa ei destory [name] &#39;i laev.";
$l_sm_lost = "[target] Lost [armor] armor punktid ja [energy] energia ühikut.";
$l_sm_destroyed = "[target] &quot;s laev on hävitatud.";
$l_sm_escapepod = "Escape pod algas!";
?>
