<?php
$l_by_title        = "Pearahad";
$l_by_noturn       = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et pearaha v&auml;lja panna v&otilde;i muuta.";
$l_by_amount       = "Pearaha summa";
$l_by_place        = "Pane v&auml;lja";
$l_by_nobounties   = "&Uuml;htegi pearaha ei ole v&auml;lja pandud.";
$l_by_bountyon     = "Kelle eest"; // Leia parem t6lge, kui oskad
$l_by_placedby     = "V&auml;ljapanija";
$l_by_thefeds      = "F&ouml;deratsioon";
$l_by_cancel       = "T&uuml;hista";
$l_by_yourself     = "Sa ei saa enda eest pearaha v&auml;lja panna!";
$l_by_notenough    = "Sul ei ole piisavalt raha, et sellist pearaha v&auml;lja panna.";
$l_by_toomuch      = "Sa ei saa sellist pearaha v&auml;lja panna. Maksimaalne lubatud pearaha suurus on [percent] protsenti Su impeeriumi v&auml;&auml;rtusest";
$l_by_zeroamount   = "Pearaha summa peab olema suurem kui 0.";
$l_by_placed       = "Pearaha v&auml;lja pandud.";
$l_by_nobounty     = "Seda pearaha ei ole enam.";
$l_by_notyours     = "Seda pearaha ei ole Sina v&auml;lja pannud.";
$l_by_canceled     = "Pearaha on t&uuml;histatud.";
$l_by_action       = "Tegevus";
$l_by_placebounty  = "Pane v&auml;lja v&otilde;i vaata pearahasid.";
$l_by_moredetails  = "Kliki nimel, et rohkem teada saada.";
$l_by_fedbounty    = "<font color='red' size='4'><b>Kui Sa seda m&auml;ngijat r&uuml;ndad, paneb F&ouml;deratsioon Su laeva eest pearaha v&auml;lja.</b></font>";
$l_by_fedbounty2   = "<font color='red' size='4'><b>F&ouml;deratsioon ei luba palju v&auml;iksemate laevade r&uuml;ndamist. Su laeva eest pandi pearaha v&auml;lja.</b></font>";
$l_by_notexists    = "Sellist m&auml;ngijat ei ole.";
$l_by_destroyed    = "Sa ei saa panna pearaha v&auml;lja laeva eest, mis on purustatud.";
$l_by_nofedbounty = "Sa ei saa halastus kui te rünnak selle mängijate laeva või planeedile.";
$l_by_fedcollectonly = "Ainult Föderatsiooni koguda Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color='red' size='4'><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color='red' size='4'><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Sa ei saa halastus kui paned spioon selles mängijad planeedil.";
$l_pay_partial = "Tee osalise makse";
$l_pay_button = "Maksa";
$l_by_thealliance = "Alliance";
$l_by_alliancecollectonly = "Ainult alliansi koguda Bounty";
$l_by_bountyscan = "Bounty";
?>
