<?php
$l_opt_title = "Valige Avatar";
$l_opt_errorsize = "Viga: Sinu pilt ei tohi olla suurem kui 64x64 pikslit suurus.";
$l_opt_errortype = "Viga: Pilt peab olema JPG, GIF või PNG";
$l_opt_errornographic = "Viga: graafika valik.";
$l_opt_currentavatar = "Sinu praegune Avatar";
$l_opt_uploadavatar = "Upload Avatar";
$l_opt_directory = "Valige Avatar Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Valige Avatar";
$l_opt_inuse = "Kõik Avatarid selles kataloogis on kasutusel.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
