<?php
$l_zi_title      = "Tsooni info";
$l_zi_nexist     = "Sellist kosmilist sektsiooni ei eksisteeri!";
$l_zi_feds       = "F&ouml;deratsioon";
$l_zi_traders = "Alliance Space";
$l_zi_nobody     = "Keegi";
$l_zi_war        = "Vaenuv&auml;ed";
$l_zi_allow      = "Lubatud";
$l_zi_notallow   = "Keelatud";
$l_zi_limit      = "Lubatud omanikule ja liidule";
$l_zi_ul         = "Piiramatu";
$l_zi_control    = "See sektor on Sinu kontrolli all";
$l_zi_tochange   = "et muuta selle reegleid.";
$l_zi_owner      = "Tsooni omanik";
$l_zi_maxhull    = "Suurim lubatud keskmine tehniline tase";
?>
