<?php
$l_md_title     = "Sektori kaitsed";
$l_md_invalid     = "Ebakorrektne sektori kaitse";
$l_md_nolonger     = "Sektori kaitset ei ole enam siin.";
$l_md_you     = "oled Sina";
$l_md_bmines     = "Sinu laserid purustasid";
$l_md_msgdownerb   = "[name] h&auml;vitas [mines] miini sektoris [sector].";
$l_md_retr     = "Sa v&otilde;tsid tagasi";
$l_md_consist     = "See sektori kaitse koosneb [qty]-st [type], mille omanikuks [owner].";
$l_md_youcan     = "Sa v&otilde;id";
$l_md_retrieve     = "tagasi v&otilde;tta";
$l_md_change     = "h&auml;vitajate olekut muuta";
$l_md_attack     = "R&uuml;nnak";
$l_md_attdef     = "Sa v&otilde;id sektori kaitseid r&uuml;nnata. K&otilde;ik sektori kaitse h&auml;vitajad r&uuml;ndavad Sind.";
$l_md_noturn       = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik.";
$l_md_nothere            = "Sa pead olema sektori kaitsetega samas sektoris.";
$l_md_notyours           = "K&auml;sk t&auml;itmata. Need sektori kaitsed ei kuulu Sulle.";
$l_md_yours              = "Sa ei saa r&uuml;nnata Sinu isiklikke sektori kaitseid.";
?>
