<?php
$l_chm_hehitminesinsector          = "[chm_playerinfo_character_name] p&otilde;rkas vastu [chm_roll] miini sektoris [chm_sector].";
$l_chm_youlostminedeflectors       = "Sa kaotasid [chm_roll] miinit&otilde;rjujat.";
$l_chm_youlostallminedeflectors    = "Sa kaotasid k&otilde;ik oma miinit&otilde;rjujad.";
$l_chm_youhadnominedeflectors      = "Sul polnud &uuml;htegi miinit&otilde;rjujat.";
$l_chm_yourshieldshitforminesdmg   = "Su energiakilp sai [chm_mines_left] punkti ulatuses vigastada.";
$l_chm_yourshieldsaredown          = "Su energiakilp l&uuml;litus v&auml;lja!";
$l_chm_youlostallyourshields       = "Sa kaotasid kogu oma energiakilbi!";
$l_chm_yourarmorhitforminesdmg     = "Su soomus sai [chm_mines_left] punkti ulatuses vigastada.";
$l_chm_yourhullisbreached          = "Kogu Su soomus on purustatud!";
$l_chm_hewasdestroyedbyyourmines   = "Su miinid purustasid m&auml;ngija [chm_playerinfo_character_name] sektoris [chm_sector].";
$l_chm_yourshiphasbeendestroyed    = "<b>Su laev on purustatud!</b>";
$l_chm_luckescapepod               = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";

$l_chm_yourdeflectormalf1 = "Kaevandus Rohusuunaja käivitamise süsteem on malfunctioned.";
$l_chm_yourdeflectormalf2 = "Olete olnud suuteline käivitama";
$l_chm_yourdeflectormalf3 = "protsenti oma kaevanduses deflectors.";
$l_chm_enemytorpfailshields = "ei ole algatatud ühtegi torpeedod vastu teie kilbid.";
$l_chm_enemytorpfailarmor = "ei ole algatatud ühtegi torpeedod vastu oma armor.";

$l_chm_minemalf1 = "Enemy kaevandus on malfunctioned.";
$l_chm_minemalf2 = "Ainult";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines = "Vajutad [chm_roll] kaevandustest välja [total_mines] kaevandused!";
$l_chm_yourdeflectormalf2a = "Olete olnud suuteline käivitama [deflectors] protsenti oma kaevanduses deflectors.";
$l_chm_mines_destroyed = "[number] ja [target] miinid on hävitatud!";
$l_chm_mine_deflectors_left = "Olete [number] kaevanduse deflectors vasakule.";
$l_chm_mines_left = "On [number] kaevanduste vasakule ja need mõjutavad üles oma armor!";
$l_chm_minemalf2a = "Ainult [deflectors] protsenti kaevanduste rünnata leidis oma laeva.";
$l_chm_mines_exhausted = "[player] Kaevanduste Väsinud!";
$l_chm_armor_left = "Olete [number] armor võrra vasakule!";

?>
