<?php
$l_novabomb_turns = "Nova Bomb nõuab atleast [turns] kordamööda tulekahju.";
$l_novabomb_planetsdamaged = "Planeedid vigastada Nova Bomb";
$l_novabomb_planet = "Planet [name] kannatanud kahju Nova pomm.";
$l_novabomb_novaexplode = "Nova Pomm plahvatas kui ta vallandati ja teie laev on kandnud suurt kahju.";
$l_novabomb_novaexplode2 = "Nova pomm plahvatas, nagu see oli töötav ja oma laeva hävis.";
$l_novabomb_notfedsec = "Nova Pomm ei saa kasutada Föderatsiooni omanduses sektorites.";
$l_novabomb_destroyed_planet = "Teie Nova pomm krakitud pinnale planeedi harjutavad arvesse esmaste kui see plahvatas põhjustab planeedi purunema.";
$l_novabomb_wrongclass = "See laev klassi ei tule Nova Bomb seade.";
$l_novabomb_nonova = "Sul ei ole Nova Bomb installitud.";
$l_novabomb_novamiss = "Nova Bomb kitsalt puudu vaid tekitatakse kahju pärast planeedil.";
$l_novabomb_success = "Sektoris [sector] on Nova pommitatakse!";
$l_novabomb_mines = "Hävitada [mines] sektori kaevandus.";
$l_novabomb_fighters = "Hävitada [fighters] sektori Fighters.";
$l_novabomb_shipsdamaged = "Laevad vigastada Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] kannatanud kahju Nova pomm.";
$l_novabomb_ship_survived = "Teie laev oli piisavalt kaugel, kui Nova pomm plahvatas, et vältida kahjustusi.";
?>
