<?php
// New News Items

$l_news_planets = "planeedid";
$l_news_cols = "Miljon kolonistide";
$l_news_p_headline = "[player] &#39;s Empire nüüd on [total] planeedid";
$l_news_c_headline = "[player] &#39;s Empire nüüd on [total] miljonit kolonistide";
$l_news_p_textXX = "Föderatsioon on hoiatused selle kohta, Empire kohta [name]. [name] on kontrolli [total] planeete ning seda tuleks kaaluda väga ohtlik. Kõik majandusharud peaksid suurendama sektori keinojasi kohe.";
$l_news_c_textXX = "X-Fighters [name] on praegu tohutu ülerahvastatus kõigi planeetide üle [total] miljonit kolonistid. Toidupuudus võib põhjustada rahutusi. Kõik majandusharud peaksid olema teadlikud võimalikest agressiivne tegevus [name] tulevikus.";

$l_created_universe = "&quot;Universumi loomine&quot;";
$l_created_universe_full = "&quot;Teadlased uurivad algus Universumis on ühehäälselt otsustanud, et täna on kõige statistiliselt tõenäoline päev Universe Creation toimunuks&quot;";

$l_news_p_text5 = "Tõuseb impeerium [name] on nüüd viis planeete FNN jälgib meetmete [name] tihedamalt tulevikku!";
$l_news_p_text10 = "Kasvav impeerium [name] nüüd kontrollib kümne planeete aruanded FNN öelda, et veelgi laiendada [name] võivad põhjustada sõda!";
$l_news_p_text25 = "Tohutu impeerium [name] koloniseeritud 25 planeeti juba intervjuus, [name] teatas, et ta võiks kaaluda aeglustub tema laienemine tulevikus!";
$l_news_p_text50 = "Tohutu suur impeerium [name], keda esindab 50 planeetide kogu galaktika muutub ähvardav jõud. Üks FNN reporterid teada, et [name] on ümberehitamise oma laeva planeerimise suurt sõda. Intervjuus [name] teatas, et on teinud kaitseministeeriumi eesmärgil ainult!";
$l_news_c_text25 = "Tõuseb impeerium [name] on nüüd 25 miljonit kolonistid, FNN jälgib meetmete [name] tihedamalt tulevikus, kuid tema väga selge, et sündivus on kavatse plahvatada!";
$l_news_c_text100 = "Ambitsioonikaid impeerium [name] on nüüd 100 miljonit kolonistide pärast plahvatuslik iive, [name] kolooniad tundus olevat hea koht peredele elama!";
$l_news_c_text500 = "Suur impeerium [name] on nüüd 500 miljonit kolonistid, [name] ütles intervjuus, et kolonisatsioonile galaktika on just veel alanud";
$l_news_c_text1000 = "Humongous impeerium [name] on nüüd üks miljard kolonistid, FNN reporterid teada, et [name] valduses on mõned veidrad kloonimise süsteem, mis võimaldab tal tõu uue kolonistide suurtes kogustes. Selle summa kolonistid, Majandusalane tugevus impeerium on tohutu, FNN loodab, et [name] ei kuluta oma raha sõjapidamise";

$l_news_indi_short = "FNN Rumor: üle [planets] kuulutada iseseisvuse.";
$l_news_indi = "FNN on see hea asutus, et üle [planets] planeedid on otsustanud, et neil on paremad valitseb iseennast ja muutunud iseseisvaks.";

$l_news_nova_short = "FNN Raport: [name] kasutab Nova pomm.";
$l_news_nova = "FNN on breaking news, et [name] on kasutanud karta Nova Bomb [total] aeg (s) hävitada planeedi ning kõik laeva peal.";
$l_news_nova_m_short = "FNN Raport: [name] kasutab Nova Bomb maha jäänud.";
$l_news_nova_m = "FNN on breaking news, et [name] on kasutanud karta Nova Bomb [total] aeg (s) püüda hävitada planeedilt. Nova Bomb blew väljaspool planeetide atmosfääri ja tekitatud suur kahju planeetide infrastruktuuri.";

$l_news_bounty = "FNN Raport: [name] kohtadest [amount] krediidi halastuse kohta [name2].";

$l_news_attackerpod_p_short = "FNN Raport: [name] &#39;s laev on hävitatud.";
$l_news_attackerpod_P = "[name] &#39;s laev oli hävitatud kui rünnata planeeti. Õnneks [name] oli Escape Pod ja säilinud.";

$l_news_attackerdie_p_short = "FNN Raport: [name] sureb!";
$l_news_attackerdie_p = "[name] &#39;s laeva hävis, samas ründab planeedi ja nad tapeti, kuna nad ei osta Escape Pod.";

$l_news_destroyed_p_short = "FNN Raport: [name] rünnakute ja hävitab planeedi!";
$l_news_destroyed_p = "[name] ründasid [total] planeedi (id) kuulub [owner] ja elanikkonna iga planeedi hävitada planeedi takistada selle löödud!";

$l_news_defeated_p_short = "FNN Raport: [name] rünnakute ja kahjustab planeet!";
$l_news_defeated_p = "[name] ründasid [total] planeedi (id) kuulub [owner] ja võitis planeetide Kaitsejõudude!";

$l_news_notdefeated_p_short = "FNN Raport: [name] rünnakute planeedi ja kaotab!";
$l_news_notdefeated_p = "[name] ründasid [total] planeedi (id) kuulub [owner] ja planeetide keinojasi heita järeleandmatu rünnakud!";

$l_news_targetepod_short = "FNN Raport: [name] rünnakute [owner] ja võidab!";
$l_news_targetepod = "[name] ründasid [owner] &#39;i laeva ja hävitatakse täielikult. Õnneks [owner] oli varustatud oma laeva Escape Pod ning neid ellu.";

$l_news_targetdies_short = "FNN Raport: [name] rünnakute [owner] ja tapab neid!";
$l_news_targetdies = "[name] ründasid [owner] &#39;i laeva ja hävitatakse täielikult. Kahjuks [owner] ei ole varustatud oma laeva Escape Pod ning neid oli aurustunud.";

$l_news_fedcolbounty_short = "FNN Raport: Föderatsiooni praod alla [name]!";
$l_news_fedcolbounty = "Föderatsioon on täna krakitud alla kurikuulsa ruumi piraat [name]! [name], kes süstemaatiliselt rikub mitu ruumi lepingud, oli korraks tööle Föderatsiooni battlecruiser, mis tekitatud [amount] opintopisteen kahju piraat laev. Föderatsiooni ametnike lubadus veel sellised meetmed tulevikus!";

$l_news_alliancecolbounty_short = "FNN Raport: alliansi praod alla [name]!";
$l_news_alliancecolbounty = "Allianss on täna krakitud alla kurikuulsa ruumi piraat [name]! [name], kes süstemaatiliselt rikub mitu ruumi lepingud, oli korraks tööle allianss, mis tekitatud [amount] opintopisteen kahju piraat laev. Alliansi ametnike lubadus veel sellised meetmed tulevikus!";

$l_news_fedcol_pbounty_short = "FNN Raport: Föderatsiooni jahipidamine ette [name]!";
$l_news_fedcol_pbounty = "Föderatsioon on täna krakitud alla kurikuulsa ruumi piraat [name]! [name], kes süstemaatiliselt rikub mitu ruumi lepingud, oli korraks tööle Föderatsiooni battlecruiser, mis konfiskeeritud planeedi [planetname] euro [amount] krediidi valdkonnas [sector]. Föderatsiooni ametnike lubadus veel sellised meetmed tulevikus!";

$l_news_alliancecol_pbounty_short = "FNN Raport: alliansi jahipidamine ette [name]!";
$l_news_alliancecol_pbounty = "Allianss on täna krakitud alla kurikuulsa ruumi piraat [name]! [name], kes süstemaatiliselt rikub mitu ruumi lepingud, oli korraks tööle allianss, mis konfiskeeritud planeedi [planetname] euro [amount] krediidi valdkonnas [sector]. Alliansi ametnike lubadus veel sellised meetmed tulevikus!";

$l_news_fedcol_sbounty_short = "FNN Raport: Föderatsiooni jahipidamine ette [name]!";
$l_news_fedcol_sbounty = "Föderatsioon on täna krakitud alla kurikuulsa ruumi piraat [name]! [name], kes süstemaatiliselt rikub mitu ruumi lepingud, oli korraks tööle Föderatsiooni battlecruiser, mis konfiskeeriti laev ([shiptype]) väärtuses [cost] sektoris [sector]. Föderatsiooni ametnike lubadus veel sellised meetmed tulevikus!";

$l_news_alliancecol_sbounty_short = "FNN Raport: alliansi jahipidamine ette [name]!";
$l_news_alliancecol_sbounty = "Allianss on täna krakitud alla kurikuulsa ruumi piraat [name]! [name], kes süstemaatiliselt rikub mitu ruumi lepingud, oli korraks tööle allianss, mis konfiskeeriti laev [shiptype] euro [cost] sektoris [sector]. Alliansi ametnike lubadus veel sellised meetmed tulevikus!";

$l_killheadline = "[target] hukkus õnnetuses";
$l_news_killed = "[target] tapeti traagilise õnnetuse täna. Kuidas kangelaslik - [target] oli viimane liige pardal oma laeva, kui ta märkas puudus põgeneda pod jätta teda. Võib ta rahus!";

$l_killSDheadline = "[target] tapsid Sector keinojasi.";
$l_news_killedSD = "[target] tapeti suur arv Sector keinojasi omanduses [killer]! Kahjuks laeva ei varustatud escape pod.";

$l_killplanetheadline = "[target] tapeti rünnata planeeti.";
$l_news_killedplanet = "[target] tapeti samal ajal ründab planeedi omanduses [killer] täna. Kahjuks laeva ei varustatud escape pod.";

$l_killshipheadline = "[target] hukkus laev võidelda.";
$l_news_killedship = "[target] tapeti laevadevaheliste võidelda koos [killer] täna. Kapten ilmselt unustasin varustada laeva pääseda pod.";

$l_killsuicideheadline = "[target] sooritanud enesetapu.";
$l_news_killedsuicide = "[target] enesetapu täna. Nad võtsid argpüksid väljapääs, sest nad ei olnud võimalust ega julgust seista kuni surve ülem oma laeva.";

$l_killsofaheadline = "[target] tapeti diivan rünnata planeeti.";
$l_news_killedsofa = "[target] tapeti samas diivan ründab planeedi omanduses [killer] täna. Kahjuks laeva ei varustatud escape pod.";

$l_killnovaheadline = "[target] tapeti ajal Nova rünnak.";
$l_news_killednova = "[target] tappis [killer] ajal Nova pommirünnakus täna. Kahjuks laeva ei varustatud escape pod.";

$l_killnovabackfireheadline = "[target] tapeti alates Nova tagasilöök.";
$l_news_killednovabackfire = "[target] hukkus, kui nende Nova pomm backfired täna. Kahjuks laeva ei varustatud escape pod.";

$l_killsectormissileheadline = "[target] tapeti alates Sector rakett.";
$l_news_killedsectormissile = "[target] tapeti siis, kui sektoril rakettide alates [killer] mõjutanud nende kilbid. Kahjuks laeva ei varustatud escape pod.";

$l_killhunterprobeheadline = "[target] tapeti alates Hunter Probe.";
$l_news_killedhunterprobe = "[target] tapeti kui Hunter Probe alates [killer] mõjutanud nende kilbid. Kahjuks laeva ei varustatud escape pod.";

$l_killtrapprobeheadline = "[target] tapeti alates Sentry Trap Probe.";
$l_news_killedtrapprobe = "[target] tapeti kui Sentry Trap Probe alates [killer] mõjutanud nende kilbid. Kahjuks laeva ei varustatud escape pod.";

//-------------------

$l_killpodheadline = "[target] &quot;s laeva hävis õnnetusjuhtumi";
$l_news_killedpod = "[target] &quot;s laeva hävis traagilise õnnetuse täna. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killSDpodheadline = "[target] &quot;s laeva hävis sektori keinojasi.";
$l_news_killedSDpod = "[target] &quot;s laev oli hävitatud suur arv Sector keinojasi omanduses [killer]! Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killplanetpodheadline = "[target] &quot;s laeva hävis rünnata planeeti.";
$l_news_killedplanetpod = "[target] &quot;s laeva hävis, samas ründab planeedi omanduses [killer] täna. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killshippodheadline = "[target] &quot;s laev oli hävitatud laevade vastu.";
$l_news_killedshippod = "[target] &quot;s laeva hävis laevadevaheliste võidelda koos [killer] täna. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killsofapodheadline = "[target] &quot;s laeva hävis, samas diivan rünnata planeeti.";
$l_news_killedsofapod = "[target] &quot;s laeva hävis, samas diivan ründab planeedi omanduses [killer] täna. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killnovapodheadline = "[target] &quot;s laeva hävis Nova rünnak.";
$l_news_killednovapod = "[target] &quot;s laeva hävis [killer] ajal Nova pommirünnakus täna. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &quot;s laev oli hävitatud Nova tagasilöök.";
$l_news_killednovabackfirepod = "[target] &quot;s laev oli hävitatud kui nende Nova pomm backfired täna. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &quot;s laev oli hävitatud Sector rakett.";
$l_news_killedsectormissilepod = "[target] &quot;s laev oli hävitatud kui Sector rakettide alates [killer] mõjutanud nende kilbid. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &quot;s laev oli hävitatud Hunter Probe.";
$l_news_killedhunterprobepod = "[target] &quot;s laev oli hävitatud kui Hunter Probe alates [killer] mõjutanud nende kilbid. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &quot;s laev oli hävitatud Sentry Trap Probe.";
$l_news_killedtrapprobepod = "[target] &quot;s laev oli hävitatud kui Sentry Trap Probe alates [killer] mõjutanud nende kilbid. Escape Pod transponder oli avastatud Föderatsiooni Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] on edutatud [rank]";
$l_news_promoted = "Föderatsioon on hea meel teatada edendamine [name] on auaste [rank].";

$l_news_demotedheadline = "[name] on demoted et [rank]";
$l_news_demoted = "Föderatsioon kahetseb, et teatada alandus on [name] on auaste [rank].";

$l_news_namechangedheadline = "[oldname] nimeks [newname]";
$l_news_namechanged = "[oldname] kohaldatakse Föderatsiooni Review Board muutma oma nime [newname]. Föderatsioon on antud nime muuta. Alates sellest päevast edasi [oldname] nüüd on tuntud kui [newname]. Kõigil laevadel ja planeete peaks ajakohastama oma andmed viivitamata.";

$l_news_found_planets_short = "Föderatsiooni uuring: [found_planets] uued planeedid asuvad.";
$l_news_found_planets = "Föderatsiooni uuring Skaudid on leitud [found_planets] uusi planeete hiljuti avastatud sektorites.";

$l_news_new_ports_short = "Föderatsiooni uuring: [new_ports] uued sadamad ehitada.";
$l_news_new_ports = "Föderatsiooni insenerid on ehitatud [new_ports] uute sadamate Hiljuti avastas sektorites.";

$l_news_addedsectors_short = "Föderatsiooni uuring: [addedsectors] sektorites avastati.";
$l_news_addedsectors = "Föderatsiooni uuring Skaudid on avastanud, [addedsectors] uutes valdkondades. Ettevaatlik tuleb olla.";

$l_news_artifactheadline = "[playername] täidetud [artifact]";
$l_news_artifact = "[playername] on leidnud kõik tükid [artifact] ning on kõik volitused seda suudab pakkuda.";

$l_news_artifactfoundheadline = "[playername] leitud [artifact] tk";
$l_news_artifactfound = "[playername] on leitud üks tükki [artifact] ja vajaduste [pieces] rohkem [piece].";

?>
