<?php
$l_nav_title     = "Pardakompuuter";
$l_nav_nocomp     = "Pardakompuutrit ei saa kasutada";
$l_nav_query     = "Sisesta sektor, kuhu soovid j&otilde;uda: ";
$l_nav_pathfnd     = "Tee leitud";
$l_nav_answ1     = "Sinna sektorisse j&otilde;udmine v&otilde;tab";
$l_nav_answ2     = "k&auml;iku.";
$l_nav_proper = "Sa pead uuendama oma Fighter Bay tehnoloogia enne oma võitlejaid võib leida lõimest marsruut, et vahemaa.";
$l_nav_autoroutename = "Vabatahtlik Autoroute Nimi:";
$l_nav_manuallist = "Käsitsi Ehitatud WarpLink Autoroute nimekiri";
$l_nav_warplinksleaving = "Warp Viited jätate [sector_name]";
$l_nav_nowarplinksleaving = "Puuduvad warplinks jättes selles sektoris.";
$l_nav_warp_from = "Warp alates";
$l_nav_rs_from = "RSMove alates";
$l_nav_notinlogs = "Andmed puuduvad selles sektoris.";
?>
