<?php
$l_warp_unlinked = "Destinataris ([target_sector]) no té un vincle d&#39;aquest sector.";
$l_warp_forbidtwo = "Mitjançant un editor de Warp per eliminar un enllaç bidireccional per al sector [target_sector] no està permesa.";
$l_warp_removed = "Vincular traslladat a";
$l_warp_removedtwo = "Link eliminat des de i cap";
$l_warp_nomoney = "No té crèdits suficients per a eliminar el vincle de l&#39;ordit.";
$l_warp_noenergy = "Vostè no té l&#39;energia suficient per eliminar el vincle de l&#39;ordit.";
?>
