<?php
// New News Items

$l_news_planets = "planetes";
$l_news_cols = "Milions de colons";
$l_news_p_headline = "[player] &#39;s Imperi té ara [total] planetes";
$l_news_c_headline = "[player] &#39;s Imperi té ara [total] milions de colons";
$l_news_p_textXX = "La Federació ha emès advertències sobre l&#39;Imperi de [name]. [name] té el control de [total] planetes i ha de ser considerat molt perillós. Tots els sectors han d&#39;augmentar les defenses del sector d&#39;immediat.";
$l_news_c_textXX = "L&#39;Imperi de [name] està patint amuntegament massiu en tots els planetes amb més de [total] milions de colons. L&#39;escassetat d&#39;aliments pot provocar disturbis. Tots els sectors han de ser conscients de les possibles accions agressives per [name] en el futur.";

$l_created_universe = "&#39;Creació Universe&#39;";
$l_created_universe_full = "&quot;Els científics que investiguen els orígens de l&#39;Univers s&#39;han decidit per unanimitat que avui és el dia més estadísticament probable per a la creació d&#39;Univers que ha tingut lloc&quot;";

$l_news_p_text5 = "El naixent imperi de [name] té ara cinc planetes, l&#39;FNN vigilarà les accions de [name] més estretament en el futur!";
$l_news_p_text10 = "El creixent imperi de [name], i als controls de deu planetes, els informes de FNN dir que una major expansió de [name] podria conduir a la guerra!";
$l_news_p_text25 = "L&#39;immens imperi de [name] 25 planetes colonitzats ja, en una entrevista, [name] anunciar que es podria considerar alentir la seva expansió en el futur!";
$l_news_p_text50 = "El vast imperi enorme de [name], representat per 50 planetes a la galàxia sencera està rebent una força mortal. Un dels reporters FNN descobrir que [name] és la millora del seu vaixell planejant una gran guerra. En una entrevista [name] anunciar que està fet a propòsit única defensa!";
$l_news_c_text25 = "L&#39;imperi creixent de [name] té ara 25 milions de colons, l&#39;FNN vigilarà les accions de [name] més estretament en el futur, però la seva molt evident que les taxes de natalitat es va a explotar!";
$l_news_c_text100 = "L&#39;imperi dels aspirants a [name], ara té 100 milions de colons, després d&#39;una explosió de les taxes de natalitat, [name] colònies que semblava ser un bon lloc per a les famílies a resoldre!";
$l_news_c_text500 = "El gran imperi de [name] té ara 500 milions de colons, [name] va dir en una entrevista que la colonització de la galàxia ha començat encara";
$l_news_c_text1000 = "L&#39;imperi gegantins de [name] té ara mil milions colons, periodistes FNN descobrir que [name] està en possessió d&#39;algun mecanisme de clonació estrany el que li permet criar nous colons en grans quantitats. Amb aquesta quantitat de colons, la força econmic d&#39;aquest imperi és enorme, FNN espera que [name] no gastar els seus diners en la guerra de";

$l_news_indi_short = "FNN Rumor: més de [planets] declarar la independència.";
$l_news_indi = "FNN ho té de bona tinta que més de [planets] planetes han decidit que és millor governada per si mateixos i s&#39;han convertit en independents.";

$l_news_nova_short = "FNN Informe: [name] utilitza Nova Bomb.";
$l_news_nova = "FNN té notícies que [name] ha utilitzat la temuda Nova Bomb [total] Time (s) per destruir un planeta i tots els vaixells en ell.";
$l_news_nova_m_short = "FNN Informe: [name] utilitza Nova bomba i troba a faltar.";
$l_news_nova_m = "FNN té notícies que [name] ha utilitzat la temuda Nova Bomb [total] Time (s) per tractar de destruir un planeta. La bomba va explotar Nova fora de l&#39;atmosfera dels planetes i va causar enormes danys a la infraestructura planetària.";

$l_news_bounty = "FNN Informe: [name] posa una [amount] abundància de crèdit [name2].";

$l_news_attackerpod_p_short = "FNN Informe: [name] &#39;s vaixell és destruït.";
$l_news_attackerpod_P = "[name] &#39;s nau va ser destruïda mentre que atacar un planeta. Afortunadament [name] hi havia una càpsula d&#39;escapament i han sobreviscut.";

$l_news_attackerdie_p_short = "FNN Informe: [name] mor!";
$l_news_attackerdie_p = "[name] &#39;s nau va ser destruïda mentre que atacar un planeta i que van morir perquè no van poder comprar una càpsula d&#39;escapament.";

$l_news_destroyed_p_short = "FNN Informe: [name] ataca i destrueix un planeta!";
$l_news_destroyed_p = "[name] va atacar [total] planeta (es) de propietat de [owner], i la població de cada planeta destruït el planeta per evitar que sigui capturat?";

$l_news_defeated_p_short = "FNN Informe: [name] els atacs i derrotes d&#39;un planeta!";
$l_news_defeated_p = "[name] va atacar [total] planeta (es) de propietat de [owner], i va derrotar a les forces de defensa planetària!";

$l_news_notdefeated_p_short = "FNN Informe: [name] els atacs d&#39;un planeta i es perd!";
$l_news_notdefeated_p = "[name] va atacar [total] planeta (es) de propietat de [owner], i les defenses planetàries celebrat contra els atacs implacables!";

$l_news_targetepod_short = "FNN Informe: [name] els atacs a [owner] i guanya!";
$l_news_targetepod = "[name] va atacar [owner] &#39;s vaixell i el van destruir completament. Afortunadament [owner] havia equipat la seva nau amb una càpsula d&#39;escapament i sobreviure.";

$l_news_targetdies_short = "FNN Informe: [name] els atacs a [owner] i els mata!";
$l_news_targetdies = "[name] va atacar [owner] &#39;s vaixell i el van destruir completament. Lamentablement [owner] no de la seva nau equipada amb una càpsula d&#39;escapament i s&#39;evapora.";

$l_news_fedcolbounty_short = "FNN Informe: Les esquerdes Federació avall a [name]!";
$l_news_fedcolbounty = "La Federació d&#39;avui ha reprimit el famós pirata espacial [name]! [name], que violen sistemàticament diversos tractats sobre l&#39;espai, va ser breument contractats per la Federació de batalla, que va causar [amount] crèdits per valor dels danys en el vaixell pirata. Funcionaris de la Federació promesa de noves accions en el futur!";

$l_news_alliancecolbounty_short = "FNN Informe: Les esquerdes de l&#39;Aliança pel [name]!";
$l_news_alliancecolbounty = "L&#39;Aliança avui ha reprimit el famós pirata espacial [name]! [name], que violen sistemàticament diversos tractats sobre l&#39;espai, va ser breument compromesa per l&#39;Aliança, que va causar [amount] crèdits per valor dels danys en el vaixell pirata. Responsables de l&#39;Aliança prometen més accions en el futur!";

$l_news_fedcol_pbounty_short = "FNN Informe: La Federació de caçar a [name]!";
$l_news_fedcol_pbounty = "La Federació d&#39;avui ha reprimit el famós pirata espacial [name]! [name], que violen sistemàticament diversos tractats sobre l&#39;espai, va ser breument contractats per la Federació de batalla, que va confiscar el planeta [planetname] planetname valor de [amount] de crèdits al sector [sector]. Funcionaris de la Federació promesa de noves accions en el futur!";

$l_news_alliancecol_pbounty_short = "FNN Informe: L&#39;Aliança persegueix a [name]!";
$l_news_alliancecol_pbounty = "L&#39;Aliança avui ha reprimit el famós pirata espacial [name]! [name], que violen sistemàticament diversos tractats sobre l&#39;espai, va ser breument compromesa per l&#39;Aliança, que va confiscar el planeta [planetname] planetname valor de [amount] de crèdits al sector [sector]. Responsables de l&#39;Aliança prometen més accions en el futur!";

$l_news_fedcol_sbounty_short = "FNN Informe: La Federació de caçar a [name]!";
$l_news_fedcol_sbounty = "La Federació d&#39;avui ha reprimit el famós pirata espacial [name]! [name], que violen sistemàticament diversos tractats sobre l&#39;espai, va ser breument contractats per la Federació de batalla, que va confiscar un vaixell ([shiptype]) per valor de [cost] en el sector [sector]. Funcionaris de la Federació promesa de noves accions en el futur!";

$l_news_alliancecol_sbounty_short = "FNN Informe: L&#39;Aliança persegueix a [name]!";
$l_news_alliancecol_sbounty = "L&#39;Aliança avui ha reprimit el famós pirata espacial [name]! [name], que violen sistemàticament diversos tractats sobre l&#39;espai, va ser breument compromesa per l&#39;Aliança, que va confiscar un vaixell [shiptype] tipus de vaixell valor [cost] en el sector [sector]. Responsables de l&#39;Aliança prometen més accions en el futur!";

$l_killheadline = "[target] va ser mort en un accident";
$l_news_killed = "[target] va ser mort en un tràgic accident en l&#39;actualitat. Com heroica - [target] era l&#39;últim membre a bord del seu vaixell, quan va notar que no hi havia cap càpsula d&#39;escapament a l&#39;esquerra per a ell. Que descansi en pau!";

$l_killSDheadline = "[target] va ser assassinat per les defenses del sector.";
$l_news_killedSD = "[target] va ser assassinat per un nombre aclaparador de les defenses del sector propietat de [killer]! Lamentablement, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killplanetheadline = "[target] va ser assassinat atacar un planeta.";
$l_news_killedplanet = "[target] va ser assassinat mentre ataquen un planeta propietat de [killer] d&#39;avui. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killshipheadline = "[target] va ser assassinat de combat de vaixell.";
$l_news_killedship = "[target] va ser mort en combat vaixell a vaixell amb [killer] d&#39;avui. El capità pel que sembla es va oblidar de donar a la nau amb una càpsula d&#39;escapament.";

$l_killsuicideheadline = "[target] es va suïcidar.";
$l_news_killedsuicide = "[target] es va suïcidar avui en dia. Van prendre la forma covards perquè no tenien la capacitat o el coratge d&#39;enfrontar-se a les pressions de comandament del seu propi vaixell.";

$l_killsofaheadline = "[target] va ser assassinat sofà atacar un planeta.";
$l_news_killedsofa = "[target] va ser assassinat mentre sofà atacar un planeta propietat de [killer] d&#39;avui. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killnovaheadline = "[target] va ser assassinat durant un atac de nova.";
$l_news_killednova = "[target] va ser assassinat per [killer], durant un atac amb bomba nova avui. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killnovabackfireheadline = "[target] va ser assassinat d&#39;una nova contraproduent.";
$l_news_killednovabackfire = "[target] va ser assassinat quan la seva bomba nova fracassar avui. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killsectormissileheadline = "[target] va ser assassinat d&#39;un míssil de Sector.";
$l_news_killedsectormissile = "[target] va ser assassinat quan un míssil del sector a partir de [killer] impactat seus escuts. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killhunterprobeheadline = "[target] va ser assassinat d&#39;una sonda de Hunter.";
$l_news_killedhunterprobe = "[target] va ser mort quan una sonda de Hunter [killer] impactat seus escuts. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

$l_killtrapprobeheadline = "[target] va ser assassinat d&#39;una sonda Trap Sentry.";
$l_news_killedtrapprobe = "[target] va ser mort quan una sonda Sentry parany de [killer] impactat seus escuts. Malauradament, el vaixell no estava equipat amb una càpsula d&#39;escapament.";

//-------------------

$l_killpodheadline = "[target] &#39;s nau va ser destruïda en un accident";
$l_news_killedpod = "[target] &#39;s nau va ser destruïda en un tràgic accident en l&#39;actualitat. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killSDpodheadline = "[target] &#39;s nau va ser destruïda per les defenses del sector.";
$l_news_killedSDpod = "[target] &#39;s nau va ser destruïda per un nombre aclaparador de les defenses del sector propietat de [killer]! Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killplanetpodheadline = "[target] &#39;s nau va ser destruïda atacar un planeta.";
$l_news_killedplanetpod = "[target] &#39;s nau va ser destruïda mentre atacava a un planeta propietat de [killer] d&#39;avui. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killshippodheadline = "[target] &#39;s nau va ser destruïda en el combat del vaixell.";
$l_news_killedshippod = "[target] &#39;s nau va ser destruïda en un vaixell a un altre combat amb [killer] d&#39;avui. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killsofapodheadline = "[target] &#39;s nau va ser destruïda mentre sofà atacar un planeta.";
$l_news_killedsofapod = "[target] &#39;s nau va ser destruïda mentre sofà atacar un planeta propietat de [killer] d&#39;avui. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killnovapodheadline = "[target] &#39;s nau va ser destruïda durant un atac de nova.";
$l_news_killednovapod = "[target] &#39;s nau va ser destruïda per l&#39;[killer], durant un atac amb bomba nova avui. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killnovabackfirepodheadline = "[target] &#39;s nau va ser destruïda d&#39;una nova contraproduent.";
$l_news_killednovabackfirepod = "[target] &#39;s nau va ser destruïda quan el seu bomba nova fracassar avui. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killsectormissilepodheadline = "[target] &#39;s nau va ser destruïda per un míssil de Sector.";
$l_news_killedsectormissilepod = "[target] &#39;s nau va ser destruïda quan un míssil del sector a partir de [killer] impactat seus escuts. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killhunterprobepodheadline = "[target] &#39;s nau va ser destruïda per una sonda de Hunter.";
$l_news_killedhunterprobepod = "[target] &#39;s nau va ser destruïda quan una sonda de Hunter [killer] impactat seus escuts. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

$l_killtrapprobepodheadline = "[target] &#39;s nau va ser destruïda per una sonda Trap Sentry.";
$l_news_killedtrapprobepod = "[target] &#39;s nau va ser destruïda quan una sonda Sentry parany de [killer] impactat seus escuts. Un transpondedor Escape Pod va ser detectat per la Federació de cerca i salvament.";

// --------------------------

$l_news_promotedheadline = "[name], ha estat ascendit a [rank]";
$l_news_promoted = "La Federació es complau d&#39;anunciar la promoció de [name] al rang de [rank].";

$l_news_demotedheadline = "[name], ha estat relegat a [rank]";
$l_news_demoted = "La Federació lamenta haver d&#39;anunciar el descens de categoria de [name] al rang de [rank].";

$l_news_namechangedheadline = "[oldname] canvia el seu nom a [newname]";
$l_news_namechanged = "[oldname] aplicat a la Junta de Revisió de la Federació per canviar el seu nom a [newname]. La Federació ha concedit el canvi de nom. D&#39;avui en endavant [oldname] ara es coneix com [newname]. Tots els vaixells i els planetes han d&#39;actualitzar els seus registres immediatament.";

$l_news_found_planets_short = "Federació de l&#39;Enquesta: [found_planets] nous planetes situats.";
$l_news_found_planets = "Federació de Scouts han situat Enquesta [found_planets] en els sectors nous planetes descoberts recentment.";

$l_news_new_ports_short = "Federació de l&#39;Enquesta: [new_ports] nous ports construïts.";
$l_news_new_ports = "Enginyers de la Federació han construït [new_ports] nous ports en els sectors recentment descobert.";

$l_news_addedsectors_short = "Federació de l&#39;Enquesta: [addedsectors] sectors descoberts.";
$l_news_addedsectors = "Federació de Scouts han descobert Enquesta [addedsectors] nous sectors. Es recomana precaució.";

$l_news_artifactheadline = "[playername] [artifact]";
$l_news_artifact = "[playername] ha trobat totes les peces de l&#39;artefacte [artifact] i té tota la potència que pot proporcionar.";

$l_news_artifactfoundheadline = "[playername] va trobar [artifact] peça";
$l_news_artifactfound = "[playername] ha trobat una de les peces de l&#39;artefacte [artifact] i les necessitats de [pieces] més [piece].";

?>
