<?php
$l_att_title = "Atac contra el vaixell";
$l_att_notarg = "Objectiu no en aquest sector.";
$l_att_noturn = "Vostè necessita com a mínim un cop l&#39;atac.";
$l_att_noatt = "";
$l_att_flee = "Objectiu terme maniobrat vostè!";
$l_att_ewd = "Meta va contractar a un dispositiu d&#39;emergència quan l&#39;ordit atacat!";
$l_att_att = "Atacar";
$l_att_beams = "Manga d&#39;Exchange";
$l_att_torps = "Torpedo d&#39;Exchange";
$l_att_fighters = "Intercanvi de combat";
$l_att_lost = "perdut";
$l_att_ylost = "Has perdut";
$l_att_sdown = "&#39;s escuts estan baix!";
$l_att_ydown = "Els seus escuts estan baix!";
$l_att_shits = "&#39;s escuts són colpejats per";
$l_att_yhits = "Els seus escuts són colpejats per";
$l_att_dmg = "danys";
$l_att_sarm = "&#39;s armadura violada!";
$l_att_yarm = "La seva armadura s&#39;ha trencat!";
$l_att_ashit = "&#39;s armadura és colpejat per";
$l_att_ayhit = "La seva armadura és colpejat per";

$l_att_efhit = "&#39;s són destruïts combatents.";
$l_att_yfhit = "dels seus combatents són destruïts.";
$l_att_ethit = "&#39;s torpedes són destruïts.";
$l_att_ythit = "es destrueixen els seus torpedes.";
$l_att_of = "de";
$l_att_lostt = "perdut tot torpedes.";
$l_att_ylostt = "Heu perdut tots els torpedes.";

$l_att_lostf = "perdut tots els combatents.";
$l_att_ylostf = "Heu perdut tots els combatents.";
$l_att_sdest = "&#39;s vaixell ha estat destruït.";
$l_att_espod = "Una càpsula d&#39;escapament es va posar en marxa!";
$l_att_ysalv = "Vostè va salvar [ship_salvage_rate]% de la nau de [ship_salvage] crèdits. <BR> El teu vot canviat per [rating_change].";
$l_att_andused = "i s&#39;utilitza";
$l_att_stilship = "No destory [name] &#39;s vaixell.";
$l_att_atyou = "atacat";
$l_att_and = "i";
$l_att_yshiplost = "El seu vaixell ha estat destruït!";
$l_att_salv = "[name] salvar [ship_salvage_rate]% de la nau de [ship_salvage] Crèdits";
$l_att_loosepod = "Afortunadament, vostè té una càpsula d&#39;escapament!";

$l_att_tnobeams = "costures a partir de l&#39;energia del feix.";
$l_att_tnobeamsf = "costures a partir de l&#39;energia del feix i no pot atacar als seus combatents.";
$l_att_tnobeamst = "costures a partir de l&#39;energia del feix i no pot atacar als seus torpedes.";
$l_att_tfnoattack = "no envia cap combatents a atacar al seu vaixell.";
$l_att_tnotorps = "sembla estar fora de torpedes.";

$l_att_anobeams = "Ha esgotat els seus vaixells de l&#39;energia del feix.";
$l_att_anobeamsf = "Ha esgotat els seus vaixells d&#39;energia del feix i no poden atacar els combatents enemics.";
$l_att_anobeamst = "Ha esgotat els seus vaixells de l&#39;energia del feix i no pot atacar l&#39;enemic torpedes.";
$l_att_anofighters = "El seu vaixell ha esgotat tots els combatents availible.";
$l_att_anotorps = "Ha esgotat els seus torpedes availible.";
$l_att_imtitle = "Ship Under Attack";
$l_att_imbody = "està atacant al seu vaixell.";

$l_att_luckybeams = "Enemy bigues sobrecàrrega d&#39;infligir";
$l_att_luckyfighters = "Combatents enemics fer una sorpresa alleugeriment atac i causa";
$l_att_luckytorps = "Enemy torpedes induir un efecte en cascada que causa danys";
$l_att_luckytimes = "vegades el dany normal!";
?>
