<?php
$l_sm_title = "Sector de Llançament de Míssils";
$l_sm_invalid = "No hi ha un vincle entre l&#39;ordit d&#39;aquest sector i el de destinació.";
$l_sm_notarg = "Objectiu no en aquest sector.";
$l_sm_noturn = "Vostè necessita com a mínim un cop al foc del seu sector de míssils.";
$l_sm_nosectormissile = "No s&#39;estan portant tots els míssils Sector.";
$l_sm_noscan = "Sensors no poden aconseguir un acord en el blanc!";
$l_sm_flee = "Objectiu a maniobrar de Míssils sector!";
$l_sm_ewd = "Meta va contractar a un dispositiu d&#39;emergència de l&#39;ordit quan es va detectar el Sector de Míssils!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] està atacant a la teva nau amb un míssil del sector!";
$l_sm_sectormissilefail = "El sector dels míssils va fallar quan va tocar l&#39;escut dels vaixells enemics!";
$l_sm_sectormissilefail2 = "El sector dels míssils va fallar quan va arribar a l&#39;armadura dels vaixells enemics!";
$l_sm_shieldhit = "[target] &#39;s escuts són colpejats per [amount] mal!";
$l_sm_shieldsdown = "[target] &#39;s escuts estan baix!";
$l_sm_armorhit = "[target] &#39;s armadura és colpejat per [amount] mal!";
$l_sm_armorbreached = "[target] &#39;s armadura violada!";
$l_sm_targetnoenergy = "El vaixell enemic no té cap tipus d&#39;energia! Sector de míssils no!";
$l_sm_attacking = "Atacar [target] a bord de la [shipname]";
$l_sm_targetok = "No destory [name] &#39;s vaixell.";
$l_sm_lost = "[target] perdut [armor] punts d&#39;armadura i la [energy] unitats d&#39;energia.";
$l_sm_destroyed = "[target] &#39;s vaixell ha estat destruït.";
$l_sm_escapepod = "Una càpsula d&#39;escapament es va posar en marxa!";
?>
