<?php
$l_new_pwis = "La seva contrasenya és";
$l_new_charis = "El seu nom és de caràcter";
$l_new_title2 = "Crear una nova fase Player Dues";
$l_new_blank = "E-mail, nom de la nau, i el nom del personatge no pot estar en blanc.";
$l_new_inuse = "E-mail [username] ja està en ús.";
$l_new_forgotpw = "Has oblidat la teva contrasenya?";
$l_new_inusechar = "Nom del personatge [character], ja està en ús.";
$l_new_similar_inusechar = "Nom del teu personatge sembla massa semblant a la [character], un nom ja en ús.";
$l_new_inuseship = "Nom del vaixell [shipname], ja està en ús.";
$l_new_similar_inuseship = "El seu nom del vaixell sona massa semblant a la [shipname], un nom ja en ús.";
$l_new_pwsent = "La contrasenya ha estat enviada a [username].";
$l_new_err = "Si us plau, torneu-ho de nou";
$l_new_topic = "Alien Assalt operadors Contrasenya";
$l_new_message = "$ Ip Salutacions, \ n \ nSomeone de l&#39;adreça IP demanada que la seva contrasenya per Traders ser enviada a vostè. \ N \ nEl període de contrasenya és: [pass] \ n \ nGracias \ n \ nEl equip d&#39;operadors web.";
$l_new_invalidemail = "Adreça de correu electrònic no vàlida.";
$l_new_tutorial = "Feu clic aquí per llegir el mini-tutorial abans d&#39;ingressar en el joc.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "per anar a la pantalla de login.";

?>
