<?php
$l_ze_title = "Editeu Zona";
$l_ze_notowner = "Vostè no és propietari d&#39;aquesta zona pel que no es pot editar.";
$l_ze_name = "Nom de la zona";
$l_ze_allow = "Permetre";
$l_ze_attacks = "Permetre que atacar a altres vaixells";
$l_ze_genesis = "Permetre la creació de nous planetes";
$l_ze_return = "per tornar a la pàgina d&#39;informació de la zona";
$l_ze_saved = "Els seus canvis s&#39;han desat.";
$l_ze_namematch = "ERROR: El nom de la zona que ens ha facilitat és similar o coincideix amb un Nom de la zona existent.";
?>
