<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Benvingut al Casino, actualment oferim els següents jocs i instal.lacions";
$l_casino_option = "&quot;Habitacions";
$l_casino_detail = "&quot;Descripció";

// Blackjack
$l_bet = "&quot;Aposta";
$l_stand = "&quot;Stand";
$l_hit = "Hit";
$l_firsthand = "&quot;De primera mà";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Segur";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Anar-se&#39;n";
$l_credits = "Crèdits";
$l_yourbet = "&quot;La seva aposta";
$l_nobet = "&quot;La seva aposta ha superat el seu límit de crèdit, per favor, aposta de nou.";
$l_dealerwins = "Guanya Dealer!";
$l_dealerbust = "Bust Dealer!";
$l_dealerloses = "Perd Dealer!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;El jugador guanya!";
$l_playerbust = "&quot;Jugador Bustos!";
$l_playerloses = "&quot;El jugador perd!";
$l_playerblackjack = "&quot;Jugador de Blackjack!";
$l_place_bet = "&quot;Col loqueu la seva aposta";
?>
