<?php
$l_defense_deploy_title = "Desplegar Sector de Mines i Fighters";
$l_defense_deploy_noturn = "Vostè necessita almenys una vegada, per desplegar defenses del sector.";
$l_defense_deploy_nopermit = "Implementació de les mines i combatents en aquest sector no està permès.";
$l_defense_deploy_nodeploy = "No es pot implementar aquí. Un altre vaixell o de l&#39;equip té mines o combatents en aquest sector.";
$l_defense_deploy_info1 = "Vostè està actualment en el sector [sector]. Hi ha [mines] mines i [fighters] combatents d&#39;aquí.";
$l_defense_deploy_info2 = "Té [mines] mines i [fighters] combatents disponibles per desplegar";
$l_defense_deploy_deploy = "Desplegar";
$l_defense_deploy_deployed = "Desplegats";
$l_defense_deploy_att = "Atac";
$l_defense_deploy_notorps = "Vostè no té prou torpedes.";
$l_defense_deploy_nofighters = "No té prou combatents";
$l_defense_deploy_dmines = "Desplegats [mines] de mines.";
$l_defense_deploy_dfighter = "Desplegats [fighters] combatents.";
$l_defense_deploy_max_fighters = "Aquest sector pot admetre un màxim de [amount] combatents.";
$l_defense_deploy_toomanyfighters = "Vostè ha tractat de desplegar més lluitadors que el sector pot donar suport.";
?>
