<?php
$l_nav_title = "La navegació";
$l_nav_nocomp = "La navegació no està disponible";
$l_nav_query = "Introduïu sector per buscar la ruta a:";
$l_nav_pathfnd = "Camí trobat";
$l_nav_answ1 = ", Que li portarà";
$l_nav_answ2 = "torna a arribar a aquest sector.";
$l_nav_proper = "Vostè necessita actualitzar la seva tecnologia de combat abans de la Badia de combatents pot trobar una ruta de l&#39;ordit per a aquesta distància.";
$l_nav_autoroutename = "Nom Autoroute Opcional:";
$l_nav_manuallist = "Construït manualment WarpLink Llista Autoroute";
$l_nav_warplinksleaving = "Warp Enllaços Deixant [sector_name]";
$l_nav_nowarplinksleaving = "No hi ha warplinks deixar aquest sector.";
$l_nav_warp_from = "Ordit de";
$l_nav_rs_from = "RSMove d&#39;";
$l_nav_notinlogs = "No hi ha dades disponibles sobre aquest sector.";
?>
