<?php
$l_opt2_title = "Opcions d&#39;estalvi";
$l_opt2_passunchanged = "Contrasenya va quedar sense canvis. <BR><BR>";
$l_opt2_srcpassfalse = "Original contrasenya incorrecta. Contrasenya va quedar sense canvis. <BR><BR>";
$l_opt2_newpassnomatch = "Els camps Nova contrasenya no coincideixen. Contrasenya va quedar sense canvis. <BR><BR>";
$l_opt2_passchanged = "Contrasenya canviada. <BR><BR>";
$l_opt2_passchangeerr = "S&#39;ha produït un error en canviar la contrasenya <BR><BR>";
$l_opt2_userintup = "Interfície d&#39;usuari configuració actualitzada. <BR><BR>";
$l_opt2_userintfail = "No s&#39;ha pogut actualitzar la interfície de configuració d&#39;usuari. <BR><BR>";
$l_opt2_chlang = "L&#39;idioma ha estat ajustat a [lang]. <p>";
$l_opt2_chtemplate = "Plantilla s&#39;ha establert en [template]. <p>";
$l_opt2_dhtmlup = "HTML dinàmic configuració actualitzada. <BR><BR>";
$l_opt2_dhtmlfail = "No s&#39;ha pogut actualitzar el valor de l&#39;HTML dinàmic. <BR><BR>";
$l_opt2_shipnamechanged = "ShipName canviat a [name]. <BR><BR>";
$l_opt2_playernamechanged = "Nom del jugador ha canviat a [name] i [amount] crèdits deduïdes del vostre compte del vaixell. <BR><BR>";
$l_opt2_mapwidth = "Local i Galaxy Mapa Ample:";
?>
