<?php
$l_login_sclosed = "Servidor Tancat";
$l_login_closed_message = "Servidor tancat fins a nou avís.";
$l_login_title2 = "Nom de la Fase Dos";
$l_login_banned = "<b>Vostè ha estat expulsat d&#39;aquest joc per l&#39;administrador. Ja no ets benvingut a jugar a aquest servidor. La propera vegada, es comporten.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "A causa de la gravetat d&#39;aquest delicte i l&#39;atac viciós contra vostè, la Federació ha tingut l&#39;amabilitat va decidir proporcionar un país lliure de la clonació del seu càrrec es manté. Malauradament, la propietat, fins i tot en aquest dia i edat, nous clons no poden tenir, a més del bàsic per viure. Us apareixerà un vaixell de base i uns quants crèdits per a començar. Esperem que la seva propera vida serà millor.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "No tenia càpsula d&#39;escapament, i degut al seu modest èxit en aquesta vida, la Federació es nega a clonar a vostè. El teu continua sent finalment han de caure en un pou de gravetat, és d&#39;esperar que s&#39;utilitzaran per crear la vida en un altre lloc ... diversos milers de milions d&#39;anys. <BR><BR> Millor sort el pròxim partit ...";
$l_login_4gotpw1 = "La contrasenya introduïda és incorrecta. <BR><BR> Si no recordes la contrasenya,";
$l_login_4gotpw2 = "que disposi el seu correu electrònic a vostè. <BR><BR> En cas contrari,";
$l_login_4gotpw3 = "per tornar a intentar. Intent de registrar amb l&#39;adreça IP de la";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Ha mort en un incident horrible.";
$l_login_blackbox = "Blackbox és la informació que va ser recuperat de les restes del seu enviament.";
$l_new_login = "per anar a la pantalla de login.";
$l_login_playerlimit = "El servidor ha arribat al nombre màxim de jugadors que suporta. Si us plau, intenta accedir a un moment posterior.";
?>
