<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Espai Unchartered";
$l_zname[2] = "Espai de la Federació";
$l_zname[3] = "Espacial de l&#39;Aliança";
$l_zname[4] = "Zona de Guerra";

$l_nova = "Nova";
$l_nova = "Nova bomba";
$l_lssd = "Última visita del vaixell dispositiu";
$l_lss = "Vaixell per darrera vegada en aquest sector";

// Common to : warpedit 1-3.php

$l_warp_title = "Utilitzeu Warp Editor";
$l_warp_turn = "Necessita com a mínim un torn per utilitzar un editor de l&#39;ordit.";
$l_warp_none = "No té cap editors de l&#39;ordit.";
$l_warp_forbid = "Mitjançant un editor de Warp en aquest sector no està permès.";
$l_swarp_forbid = "Mitjançant un editor de Warp o de sectors de SG no està permès.";
$l_warp_nosector = "Sector no existeix.";

// Not yet confirmed common to multiple files:

$l_yes = "Sí";
$l_no = "No";
$l_here = "aquí";
$l_submit = "Enviar";
$l_reset = "He perdut";
$l_all = "Tot";
$l_max = "Max";

$l_trade = "Comerç";
$l_ore = "Ore";
$l_commodity = "Els productes bàsics";
$l_commodities = "Productes bàsics";
$l_organics = "Orgànics";
$l_goods = "Productes";
$l_energy = "Energia";
$l_colonists = "Colonos";
$l_credits = "Crèdits";
$l_units = "unitats de";
$l_special = "Especial";
$l_upgrade_ports = "Actualitzacions";
$l_device_ports = "Analog";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_dig = "Dignataris";
$l_spy = "Spies";

$l_cargo = "Càrrec";
$l_fighters = "Fighters";
$l_mines = "Mines";
$l_torps = "Torpedes";

$l_none = "Cap";
$l_unnamed = "Unnamed";
$l_name = "Nom";
$l_unowned = "Sense amo";
$l_unknown = "Desconegut";
$l_clickme = "Cliqueu aquí";
$l_player = "Player";
$l_ship = "Vaixell";
$l_ships = "Vaixells";
$l_set = "establir";
$l_realspace = "Espai real";
$l_armorpts = "Punts d&#39;armadura";
$l_links = "Enllaços";
$l_login_email = "E-mail:";
$l_add = "Afegir";
$l_teamforum = "Team Fòrum";
$l_teamships = "Equip dels vaixells";
$l_tutorial = "Tutorial / Ajuda";
$l_avatar = "Avatar";
$l_teamicon = "Equip Icon";
$l_debris = "Runes";
$l_localmap = "Mapa Local";
$l_arm_weap = "Armadura i armes";
$l_3dmap = "Mapa 3D Galaxy";

$l_sectormissile = "Sector de míssils";
$l_spacebeacon = "Espai Beacon";
$l_spaceprobes = "Les sondes espacials";
$l_warpeditors = "Editors de Warp";
$l_genesistorps = "Gènesi Torpedo";
$l_sgtorps = "SG Torpedo";
$l_minesfighters = "Mines / Fighters";
$l_ewarp = "Emergència Warp";
$l_reports = "Informes";
$l_ship = "Vaixell";
$l_sectornotes = "Notes del Sector";
$l_maps = "Mapes";
$l_messages = "Missatges";
$l_shiptype = "Tipus de vaixell";
$l_help = "Ajuda";
$l_rank = "Fila";

$l_teamplanets = "Equip de planetes";
$l_teamdefenses = "Les defenses de l&#39;equip";
$l_planetstatus = "Situació del planeta";
$l_planetdefenses = "Defenses Planet";
$l_changeproduction = "Canvi de producció";
$l_galacticarm = "Braç Galàctic";

$l_armor = "Armor";
$l_news_none = "Ho sentim, no hi ha notícies d&#39;avui.";

$l_ranks_good = "Bé";
$l_ranks_evil = "Malvat";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zona és ara una zona de guerra!";
$l_global_nzone = "Zona és una zona neutral.";
$l_global_team = "Zona ara pertany a l&#39;equip de";
$l_global_player = "Zona pertany ara al jugador";
$l_global_nochange = "La propietat de la zona no ha canviat";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "O-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recluta";
$l_insignia_name[1] = "Spaceman Aprenent";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "El sots-oficial de tercera classe";
$l_insignia_name[4] = "El sots-oficial de segona classe";
$l_insignia_name[5] = "El sots-oficial de primera classe";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Tinent d&#39;Fragata Grau";
$l_insignia_name[11] = "Tinent";
$l_insignia_name[12] = "Capità de Corbeta";
$l_insignia_name[13] = "Comandant";
$l_insignia_name[14] = "Capità";
$l_insignia_name[15] = "Contraalmirall (meitat inferior)";
$l_insignia_name[16] = "Contraalmirall (la meitat superior)";
$l_insignia_name[17] = "Vicealmirall";
$l_insignia_name[18] = "Almirall";
$l_insignia_name[19] = "Almirall de la Flota";

$l_main_title = "Menú Principal";
$l_main_warpto = "Warp per";
$l_main_autoroute = "Autopista a";
$l_main_rs_to = "RSMove a";
$l_main_other = "Un altre";
$l_main_shipyard1 = "Astillero";
$l_main_shipyard2 = "Accés a la";
$l_traderoutes = "Rutes Comercials";
$l_trade_control = "De Control del Comerç";
$l_youhave = "Ha";
$l_turns_used = "Activa utilitzats:";
$l_turns_have = "Torns disponibles:";
$l_score = "Puntuació:";
$l_sector = "Sector";
$l_help = "Ajuda";
$l_faq = "Preguntes freqüents";
$l_feedback = "Reacció";
$l_forums = "Fòrums";
$l_logout = "Tancar sessió";
$l_commands = "Comandes";
$l_command_no = "Ordre no disponible.";
$l_devices = "Analog";
$l_planets = "Planetes";
$l_log = "Registrar-se";
$l_sector_def = "Sector de les defenses";
$l_defense = "Defenses";
$l_read_msg = "Llegir missatges";
$l_send_msg = "Enviar missatges";
$l_rankings = "Classificació";
$l_teams = "Equips";
$l_ohno = "Self-Destruct";
$l_options = "Opcions";
$l_navcomp = "Ordinador de navegació";
$l_incompletemove = "Vostè no ha completat el seu moviment anterior.";
$l_clicktocontinue = "Feu clic aquí per continuar";
$l_toplanetmenu = "per anar al menú planeta.";
$l_nonexistant_pl = "En un planeta no existeix???";
$l_abord = ", A bord del";
$l_messages_wait = "Missatges en espera per vostè.";
$l_no_warplink = "No hi ha enllaços l&#39;ordit";
$l_scan = "exploració";
$l_fullscan = "Anàlisi complet";
$l_port = "Port";
$l_tradingport = "Port comercial";
$l_planet_in_sec = "Planetes en el sector";
$l_ships_in_sec = "Altres vaixells en el sector";
$l_sector_0 = "Hi ha molt trànsit a Sol que ni tan sols es pot aïllar d&#39;altres vaixells!";
$l_map = "Mapa";
$l_probe = "Sondes";
$l_autotrade = "Autotrades";
$l_onboard = "a bord d&#39;un";
$l_classship = "vaixell de la classe";
$l_traveled = "va viatjar al sector";
$l_max_planets = "Màxim planetes Habital";
$l_block_msg = "Bloca missatges";
$l_sectorinfo = "Informació del sector";
$l_add_note = "Afegeix una nota";
$l_view_note = "Veure";
$l_notes = "Notes";
$l_global_limitreached = "Heu arribat al límit de la quantitat de temps que se&#39;ls permet estar en línia cada dia. Entrar de nou matí després de la mitjanit.";
$l_onlinetimeleft = "Temps Restant:";
$l_planetmax = "Planetari màxima:";
$l_storedshipreport = "Vaixells emmagatzemats";
$l_global_chat = "Global Xat";
$l_team_chat = "Team Xat";
$l_fedinfo = "Federació d&#39;informació del port";
$l_team_shoutbox = "Equip Shoutbox";
$l_lobby = "Lobby de l&#39;Operador";

$l_common_prev = "Pàgina anterior";
$l_common_next = "Pàgina següent";
$l_common_totalpages = "Total de pàgines";
$l_common_selectpage = "Seleccioneu la pàgina:";
$l_common_page = "Pàgina:";
$l_templatechange = "Us agradaria tenir aquesta plantilla?";

$l_im_fed_bounty = "La Federació ha posat una recompensa per vostè per atacar un jugador classificat baix. La Federació d&#39;atac de la teva nau en forma regular fins que pagar la seva generositat. Vostè pot pagar la seva recompensa en qualsevol port d&#39;actualització o Spacedock.";
$l_im_fed_bounty_title = "Federació va posar una recompensa per tu!";
$l_im_alliance_bounty = "L&#39;Aliança ha posat una recompensa per vostè per atacar un jugador classificat baix. L&#39;Aliança d&#39;atac de la teva nau en forma regular fins que pagar la seva generositat. Vostè pot pagar la seva recompensa en qualsevol port d&#39;actualització o Spacedock.";
$l_im_alliance_bounty_title = "Aliança va posar una recompensa per tu!";
$l_instant_messages_waiting = "Té [count] missatges en espera per vostè.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Cellers plenes:";
$l_hold_space_free = "Manté en buit:";
$l_port_buys = "Port de compra:";

?>
