<?php
$l_news_title = "Notícies de l&#39;Univers";
$l_news_info = "FNN és un dels líders de la galàxia <br> a les notícies i el lliurament d&#39;informació. <br> Personal les 24 hores, set dies a la setmana per un <br> personal dedicat a la seu de la galàxia FNN d&#39; <br> a Proxima Centauri, i en les oficines de galàctic!";
$l_news_for = "Notícies de";
$l_news_prev = "dia anterior";
$l_news_next = "al dia següent";
$l_news_none = "Ho sentim, no hi ha notícies d&#39;avui.";
$l_news_flash = "News Flash";
$l_news_end = "Fi de les notícies";
$l_news_bestviewed = "Millor vist en Opera, Safari i IE";
$l_news_fedannouncements = "Federació d&#39;anuncis";
$l_news_planetarynews = "Planetari Notícies";
$l_news_planetshipnews = "Planetari i vaixells Notícies";
$l_news_afteractionnews = "Després de Combat Action News";
?>
