<?php
$l_sofa = "Sub-orbital caça d&#39;atac";
$l_planet_basenoturn = "Necessita almenys 1 cop a construir una base de";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "La Bomba de Nova estretament perduts, però causa danys al planeta.";
$l_planet_novaturns = "La bomba Nova requereix atleast [turns] es transforma en foc.";
$l_planet_novafed = "La Bomba de Nova no s&#39;encendrà en els sectors de la Federació.";
$l_planet_nonova = "No té una bomba instal Nova.";
$l_planet_firenova = "Nova de Foc de bomba";
$l_planet_novaexplode = "Nova bomba va esclatar quan es va disparar i la seva nau ha sofert un dany massiu.";
$l_planet_novaexplode2 = "Nova bomba va esclatar quan va ser acomiadat i la seva nau va ser destruïda.";
$l_planet_noautotrade = "Auto Comerç ruta no s&#39;estableix per aquest planeta.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] al port [dest_id]";
$l_planet_autotradedelete = "Eliminar Auto Comerç.";
$l_planet_autotradeadd = "Crear Auto Comerç.";
$l_planet_tradedeleted = "Auto Trade Route eliminats.";
$l_planet_tradeadded = "De Comerç de l&#39;Automòbil de Nova Ruta Afegit.";
$l_planet_autotype = "Seleccioneu l&#39;element al comerç";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Vostè necessita comprar un vaixell de càrrega per aquest planeta abans que vostè pot establir una ruta comercial Auto.";
$l_planet_purchasecargo = "Si vostè desitja comprar un vaixell de càrrega";
$l_planet_upgradecargo = "Si voleu actualitzar el seu vaixell de càrrega";

$l_planet_cargocapacity = "Capacitat:";
$l_planet_cargoowned = "Vostè ja té un vaixell de càrrega per aquest planeta.";
$l_planet_cargoshipbuy = "Compra de vaixells de càrrega";
$l_planet_cargoshipupgrade = "Actualització per a vaixell de càrrega";
$l_planet_cargoatmax = "El seu vaixell de càrrega es troba en el nivell d&#39;actualització màxim.";
$l_planet_cargoshipbuyinfo = "Seleccioneu un preajuste de vaixells de càrrega";
$l_planet_cargoshipupgradeinfo = "Actualitzi la seva càrrega dels vaixells de casc.";
$l_planet_cargoshipbuildinfo = "Construir el seu propi vaixell de càrrega";
$l_planet_tradehelp = "1. Vostè pot entrar en un port comercial per a cada tipus de producte. <br> 2. Vostè no pot negociar una mercaderia a un port que ven el mateix producte. <br> De comerç de mercaderies en un port de mercaderies, Ore en un port de minerals, etc. no farà res. <br> 3. Si vostè no desitja que el comerç de certs productes bàsics, simplement introduïu 0 per al sector portuari.";
$l_planet_cargocredits = "Auto Trade crèdits rebuts:";
$l_planet_cargonoown = "Recorda que has de tenir el planeta per crear un Traderoute Auto.";
$l_planet_digtrans = "Transferència de dignatari";
$l_planet_nocredits1 = "No té suficients crèdits per a aquesta transacció. El cost total és de";
$l_planet_nocredits2 = "crèdits i només s&#39;han";
$l_planet_nobase = "Vostè ha de tenir una base per gestionar el planeta els nivells de defensa.";
$l_planet_genesisnoturn = "Necessita com a mínim 1 vegada d&#39;utilitzar un dispositiu Gènesi al planeta.";
$l_planet_nogenesis = "Necessita un dispositiu Gènesi de destruir un planeta.";
$l_planet_wrongclass = "Aquesta classe de vaixells no pot acomiadar a un dispositiu de Nova Bomb.";

$l_planet_combatpreview = "Lluita contra la Preview";
$l_planet_beamfire1 = "El seu atac ha estat detectat. Planetari disparar fas! Augment de Manga Foc com ve en la seva nau molt a prop del planeta per posar en marxa els combatents.";
$l_planet_beamfire2 = "El seu atac ha estat detectat. Planetari disparar fas! Tipus d&#39;incendi de grans proporcions del planeta com bateries Manga bloqueig d&#39;accessos de múltiples!";
$l_planet_beamfire3 = "El seu atac ha estat detectat. Planetari disparar fas! Bateries Manga a tot el planeta són de bloqueig per el foc en diverses massiva! Manga de foc molt més gran del previst!";
$l_planet_beamfire4 = "El seu atac ha estat detectat. Planetari disparar fas! Manga defenses només pot bloquejar durant una passada de tir.";

$l_planet_sofanobeamsshields = "no disparar fas en el teu escut.";
$l_planet_sofanobeamsarmor = "no disparar fas a la teva armadura.";
$l_planet_flauncherfailed1 = "La seva posada en marxa del sistema de combat ha fallat.";
$l_planet_flauncherfailed2 = "Vostè només han estat capaços de llançar";
$l_planet_flauncherfailed3 = "per cent dels seus combatents.";
$l_planet_nodfightertofighter = "no envia cap combatents a atacar els seus combatents.";
$l_planet_nodfightertotorp = "no envia cap combatents a atacar al seu Torps.";
$l_planet_flauncherfailed3 = "per cent dels seus combatents.";
$l_planet_autotradetype = "- [source_type] al port [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "està atacant";
$l_planet_iminsector = "en el sector";
$l_planet_imnova = "està utilitzant un dispositiu de Nova a";
$l_planet_imsofa = "El bombardeig es SOFÀ";
$l_planet_team = "Aquest planeta és propietat d&#39;un company d&#39;equip i vostè no té permís per accedir a la informació per aquest planeta.";
?>
