<?php
$l_zi_title = "Àrea d&#39;informació";
$l_zi_nexist = "Aquesta secció d&#39;espai no existeix!";
$l_zi_feds = "Federació";
$l_zi_traders = "Space Alliance";
$l_zi_nobody = "Ningú";
$l_zi_war = "Espai disputat";
$l_zi_allow = "Permès";
$l_zi_notallow = "No permès";
$l_zi_limit = "Limitada als propietaris i els aliats";
$l_zi_ul = "Il limitat";
$l_zi_control = "Vostè està en control d&#39;aquesta zona";
$l_zi_tochange = "a canviar les seves lleis.";
$l_zi_owner = "Propietari de la zona";
$l_zi_maxhull = "Màxim nivell de tecnologia mitjana permès";
?>
