<?php
$l_scan_title = "Scan de vaixells";
$l_scan_turn = "Vostè necessita com a mínim un cop a l&#39;exploració d&#39;un altre vaixell.";
$l_scan_ron = "Els resultats de l&#39;anàlisi sobre";
$l_scan_capt = "Capitanejat per:";
$l_scan_arma = "Armament:";
$l_scan_carry = "Transport:";
$l_scan_bounty = "Aquesta nau té una recompensa total sobre ella de [amount] crèdits.";
$l_scan_fedbounty = "Aquesta nau té una recompensa per això de la Federació.";
$l_by_nofedbounty = "Atacar aquest jugador <B>no donarà lloc</b> a la Federació de posar una recompensa per vostè.";
?>
