<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] [chm_roll] mines en el sector [chm_sector].";
$l_chm_youlostminedeflectors = "Heu perdut [chm_roll] deflectors de mines.";
$l_chm_youlostallminedeflectors = "Heu perdut totes les seves deflectors de mines.";
$l_chm_youhadnominedeflectors = "No tenia deflectors de mines.";
$l_chm_yourshieldshitforminesdmg = "Els seus escuts són colpejats per [chm_mines_left] mal.";
$l_chm_yourshieldsaredown = "Els seus escuts estan baix!";
$l_chm_youlostallyourshields = "Ha perdut tots els seus escuts!";
$l_chm_yourarmorhitforminesdmg = "La seva armadura és colpejat per [chm_mines_left] mal.";
$l_chm_yourhullisbreached = "El seu casc es trenca!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] va ser destruït per les seves mines en el sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "El seu vaixell ha estat destruït!";
$l_chm_luckescapepod = "Afortunadament, vostè té una càpsula d&#39;escapament!";

$l_chm_yourdeflectormalf1 = "";
$l_chm_yourdeflectormalf2 = "Vostè només han estat capaços de llançar";
$l_chm_yourdeflectormalf3 = "per cent del seu deflectors de mines.";
$l_chm_enemytorpfailshields = "no ha llançat torpedes contra els seus escuts.";
$l_chm_enemytorpfailarmor = "no ha llançat torpedes en contra de la seva armadura.";

$l_chm_minemalf1 = "Les mines enemigues han funcionat correctament.";
$l_chm_minemalf2 = "Només";
$l_chm_minemalf3 = "per cent de les mines d&#39;atacar a trobar el seu vaixell.";

$l_chm_youhitsomemines = "Vostè colpeja [chm_roll] mines de [total_mines] mines!";
$l_chm_yourdeflectormalf2a = "Vostè només han estat capaços de llançar [deflectors] per cent del seu deflectors de mines.";
$l_chm_mines_destroyed = "[number] de [target] mines han estat destruïdes!";
$l_chm_mine_deflectors_left = "Vostè té [number] deflectors de mines a l&#39;esquerra.";
$l_chm_mines_left = "Hi ha [number] de les mines de l&#39;esquerra i que incideixen en la seva armadura!";
$l_chm_minemalf2a = "Només [deflectors] per cent de les mines d&#39;atacar a trobar el seu vaixell.";
$l_chm_mines_exhausted = "[player] mines esgotades!";
$l_chm_armor_left = "Vostè té [number] dels punts d&#39;armadura de l&#39;esquerra!";

?>
