<?php
$l_novabomb_turns = "La bomba Nova requereix atleast [turns] es transforma en foc.";
$l_novabomb_planetsdamaged = "Planetes danyat per la bomba Nova";
$l_novabomb_planet = "Planet [name] van patir danys per la bomba Nova.";
$l_novabomb_novaexplode = "Nova bomba va esclatar quan es va disparar i la seva nau ha sofert un dany massiu.";
$l_novabomb_novaexplode2 = "Nova bomba va esclatar quan va ser acomiadat i la seva nau va ser destruïda.";
$l_novabomb_notfedsec = "Nova bomba no es pot utilitzar en la Federació de propietat dels sectors.";
$l_novabomb_destroyed_planet = "La seva bomba nova esquerdat de la superfície del planeta i perforat al centre on va explotar causant que el planeta miques.";
$l_novabomb_wrongclass = "Aquesta classe de vaixells no pot acomiadar a un dispositiu de Nova Bomb.";
$l_novabomb_nonova = "No té una bomba instal Nova.";
$l_novabomb_novamiss = "La Bomba de Nova estretament perduts, però causa danys al planeta.";
$l_novabomb_success = "Sector [sector], ha estat bombardejada Nova!";
$l_novabomb_mines = "Destruir [mines] El sector de Mines.";
$l_novabomb_fighters = "Destruir [fighters] Combatents sector.";
$l_novabomb_shipsdamaged = "Vaixells danyats per la bomba Nova";
$l_novabomb_ship_damage = "Starship [shipname] sofert danys de la bomba Nova.";
$l_novabomb_ship_survived = "El seu vaixell va ser prou lluny quan la bomba va explotar Nova per evitar qualsevol dany.";
?>
