<?php
$l_pre_title = "Canvi espai real Presets";
$l_pre_exceed = "Preset [preset] excedeix màx univers de [sector_max]. N preajustes guardats. <BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Salvar";
$l_pre_info = "Informació";
$l_pre_invalid = "[sector] és el nom d&#39;un sector no vàlid.";
$l_pre_invalidchange = "[sector] és un sector de Gènesi Sector. El teu vell preestablert no es modifica.";
?>
