<?php
$l_profile_title = "Perfil de registre";
$l_profile_notenabled = "Perfils no estan permeses en aquest servidor.";
$l_profile_registered = "Aquest jugador està registrat al servidor de perfil principal.";
$l_profile_nomatch = "No es pot coincidir amb un perfil en el perfil de servidor principal amb el nom i la contrasenya del servidor d&#39;entrada.";
$l_profile_tryagain = "Per introduir el nom del perfil de jugador i contrasenya del servidor de nou, feu clic a";
$l_profile_name = "Perfil Nom del Jugador";
$l_profile_password = "Perfil de servidor Contrasenya";
$l_profile_bannedserver = "Aquest servidor no està autoritzat a presentar informació sobre el perfil al perfil de servidor mestre.";
$l_profile_bannedplayer = "Vostè ha estat expulsat del perfil de servidor mestre i no es pot inscriure jugadors.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Aquest <u><b>servidor</b></u> requereix cada nou jugador a tenir un perfil registrat. No se li permet crear un nou jugador a menys que vostè té un perfil registrat.";
$l_profile_updated = "La seva plantilla, shoutbox i notícies de rastreig configuració global s&#39;han actualitzat al servidor mestre de perfil. Aquests ajustaments s&#39;utilitzarà automàticament en registrar el seu perfil en qualsevol joc.";

?>
