<?php
$l_contact_admin_title = "Joc de contacte de l&#39;administrador";
$l_contact_admin_thanks = "Gràcies pel teu comentari.";
$l_contact_admin_email_alert = "Si us plau, introduïu una adreça de correu electrònic vàlida.";
$l_contact_admin_name_alert = "";
$l_contact_admin_comment_alert = "Si us plau, introdueixi els seus comentaris.";
$l_contact_admin_name = "Nom";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Pregunta / Comentari";
$l_contact_admin_submit = "Submit Questions / Comments";
$l_contact_admin_close = "Tancar la finestra";
$l_contact_admin_thanks_comment = "Gràcies pel seu comentari o pregunta. Estem disposats a atendre qualsevol pregunta i el correu electrònic amb la nostra resposta.";

?>
