<?php
$l_mail_title = "Mail contrasenya";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "La contrasenya ha estat enviada a";
$l_mail_topic = "Contrasenya $ game_name";
$l_mail_message = "$ Ip Salutacions, \ n \ nSomeone de l&#39;adreça IP demanada que la contrasenya de $ game_name serà enviat \ n \ nEl període de contrasenya és: [pass] \ n \ nGracias \ n \ nEl equip web de $ game_name.";
$l_new_login = "per anar a la pantalla de login.";
$l_mail_failed = "Contrasenya no va poder enviar a";
?>
