<?php
$l_gns_title = "Ús de dispositius Gènesi";
$l_gns_turn = "Necessita com a mínim un torn per utilitzar un dispositiu de gènesi.";
$l_gns_onplanet = "No podeu utilitzar aquest dispositiu, mentre que a la superfície del planeta.";
$l_gns_full = "Aquest sistema solar està ja complet.";
$l_gns_planetex = "Ja existeix un planeta en aquest sector.";
$l_gns_nogenesis = "Vostè no té cap dispositiu gènesi.";
$l_gns_forbid = "Creació d&#39;un planeta en aquest sector no està permès.";
$l_gns_bforbid = "Les bases d&#39;aquest sector estan interferint amb el seu dispositiu Gènesi. La creació de Planeta no és possible.";
$l_gns_pcreate = "Planet creat.";
$l_sgns_title = "Ús de dispositius Sector Gènesi";
$l_sgns_pcreate = "Sector [name] creat.";
$l_sgns_nogenesis = "No té cap sector dels dispositius gènesi.";
$l_sgns_forbid = "Creació d&#39;un forat de cuc gènesi del sector en aquest sector no està permès.";
$l_sgns_forbid1 = "Creació d&#39;un sector de la gènesi d&#39;un Sector de forat de cuc Federació no està permès.";
$l_sgcreate = "Crear un nou sector de Gènesi Sector d&#39;";
$l_sgcreatens = "Crear un nou sector de Gènesi enllaç de tornada a l&#39;espai conegut";
$l_sgns_forbid2 = "Més de [limit] vincles en els sectors SG no estan permesos.";
$l_sgns_forbid3 = "No es pot crear enllaços Sector ordit Gènesi actual del sector - que supera el màxim de [limit] per sector.";
$l_sgns_nocredits = "No té crèdits suficients per crear un nou sector.";
$l_sgns_shipcredits = "Crèdits en el vaixell:";
$l_sgns_createcost = "Cost de creació de nou sector:";
$l_sgns_complete = "Normal Espai enllaç complet";
$l_sgns_sectorname = "Introduïu el Nom de Sector:";
$l_gns_max_unbased_planets = "La Federació no permetrà la creació de més planetes fins que hi hagi menys de [max_unbased_planets] planetes unbased.";

?>
