<?php
$l_sn_title = "Notes del Sector";
$l_sn_pntitle = "Sectors amb notes personals";
$l_sn_tntitle = "Sectors amb les notes de l&#39;equip";
$l_sn_psntitle = "Personal del Sector Notes";
$l_sn_tsntitle = "Equip del sector Notes";
$l_sn_editnote = "Edita Sector Note:";
$l_sn_deleteedit = "Eliminar o editar:";
$l_sn_addnote = "Afegir Nota Sector:";
$l_sn_list = "Notes Llista de Sectors";
$l_sn_listts = "Llista de sectors amb les notes de l&#39;equip";
$l_sn_addteam = "Afegir Team";
$l_sn_deleteteam = "Eliminar equip";
$l_sn_delete = "Esborrar";
$l_sn_saveteam = "Desa Team";
$l_sn_deletepersonal = "Eliminar personals";
$l_sn_addpersonal = "Afegir Personal";
$l_sn_savepersonal = "Desa informació personal";
$l_sn_editpersonal = "Personals";
$l_sn_editteam = "Equip d&#39;edició";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Tipus";
$l_sn_hdowner = "Propietari / Team";
$l_sn_hdplanets = "Planetes";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mines";
$l_sn_hdscanfrom = "Escanejar des";
$l_sn_hddetail = "Detall";
$l_sn_hddate = "Data / hora";
$l_sn_hddelete = "Esborrar";
$l_sn_hdteam = "Equip";
$l_sn_view = "Veure";
$l_sn_no = "No";
$l_sn_yes = "Sí";
$l_sn_nonotes = "Cap sector notes trobades";

?>
