<?php
$l_by_title = "Primes";
$l_by_noturn = "Vostè necessita almenys una vegada per posar o modificar una recompensa.";
$l_by_amount = "Bounty Quantitat";
$l_by_place = "Lloc Bounty";
$l_by_nobounties = "Actualment no hi ha recompenses.";
$l_by_bountyon = "El Bounty";
$l_by_placedby = "Enviat per";
$l_by_thefeds = "La Federació de";
$l_by_cancel = "Cancel";
$l_by_yourself = "Vostè no pot posar una recompensa per el seu acte.";
$l_by_notenough = "No té suficients crèdits per a col.locar una recompensa d&#39;aquesta quantitat.";
$l_by_toomuch = "Vostè no pot posar aquesta generositat. Recompensa màxim permès en un altre jugador és [percent] per cent del seu valor net de";
$l_by_zeroamount = "Les gratificacions han de ser més gran que 0 crèdits.";
$l_by_placed = "La generositat ha estat col.locat.";
$l_by_nobounty = "Que la generositat ja no existeix.";
$l_by_notyours = "Que la generositat no va ser realitzat per vostè.";
$l_by_canceled = "La generositat ha estat cancel.lada.";
$l_by_action = "Acció";
$l_by_placebounty = "Lloc o recompenses de vista.";
$l_by_moredetails = "Feu clic al nom per a més detalls.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "El jugador posarà la recompensa per no existeix.";
$l_by_destroyed = "Vostè no pot posar una recompensa per un jugador amb una nau destruïda.";
$l_by_nofedbounty = "No rebrà una recompensa si l&#39;atac d&#39;aquest vaixell jugadors o planeta.";
$l_by_fedcollectonly = "Només la Federació pot recollir Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "No rebrà una recompensa si es col.loca un espia en aquest planeta jugadors.";
$l_pay_partial = "Fer el pagament parcial";
$l_pay_button = "Pagar";

$l_by_thealliance = "Centre Sociosanitari Palau";
$l_by_alliancecollectonly = "Només l&#39;Aliança pot recollir Bounty";
$l_by_bountyscan = "Bounty";
?>
