<?php
$l_autoroute_missingwarp = "Següent WarpLink falta en aquest sector. Warp moure avortat.";
$l_autoroute_SDabort = "Moure avortades a causa de les defenses del sector en el sector.";
$l_autoroute_turns = "Deduirà [triptime] Activa i es va traslladar a [targetlink]";
$l_autoroute_noturns = "Vostè està de gira.";
$l_autoroute_title = "Rutes Auto";
$l_autoroute_id = "Auto ID Ruta";
$l_autoroute_start = "Auto ruta Inici";
$l_autoroute_destination = "Auto Ruta Destinació";
$l_autoroute_warps = "Auto Route Cabos";
$l_autoroute_deleteroute = "Esborrar ruta";
$l_autoroute_info = "Feu clic a Inicia per al Sector d&#39;espai real a aquest sector i començar a torçar-per al sector de destinació.";
$l_autoroute_delete2 = "Rutes Eliminar";
$l_autoroute_noroutes = "Absència de vies d&#39;Auto";
$l_autoroute_createroute = "Crear un nou Auto Ruta";
$l_autoroute_deleted = "Auto Rutes eliminat.";
$l_autoroute_return = "Tornar al menú del botó Auto Ruta";
$l_autoroute_created = "Auto ruta ha estat creada.";
$l_autoroute_realmove = "Moure espai real per al sector";
$l_autoroute_warpmove = "Warp per moure següent sector";
$l_autoroute_warpfinal = "Warp moure el sector final";
$l_autoroute_editname = "Editar el nom";
?>
