<?php
// port.php port_purchase.php
$l_trade = "Comerç";
$l_title_port = "Port comercial";
$l_title_trade = "Comerç de matèries primeres";
$l_sector_war = "Embargament de la Guerra";
$l_war_info = "La guerra s&#39;està lliurant en aquest sector. No es pot arribar al port a través de totes les forces hostils.";
$l_no_trade = "Comerç prohibit";
$l_no_trade_out = "D&#39;intercanvis comercials en aquest port no està permès per als de fora";
$l_no_trade_info = "D&#39;intercanvis comercials en aquest port no està permès";
$l_buying = "De compres";
$l_selling = "Vendre";
$l_commodity = "Els productes bàsics";
$l_amount = "Quantitat";
$l_price = "Preu";
$l_buy = "Comprar";
$l_sell = "Vendre";
$l_trade_st_info = "Té [free_holds] de càrrega buit es manté, pot portar a [free_power] més unitats d&#39;energia, i tenen [credits] crèdits.";
$l_upgrade_port_title = "Port d&#39;actualització";
$l_device_port_title = "Port de dispositiu";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "No hi ha suficients crèdits";
$l_creds_to_spend = "Té [credits] crèdits per gastar.";
$l_cost = "Cost";
$l_avail = "Disponible";
$l_profit = "Sense ànim de lucre";
$l_current = "Actual";
$l_current_level = "Nivell actual";
$l_current_qty = "Quantitats actuals";
$l_max = "Max";
$l_ifyouneedmore = "Si necessita més pot accedir a [igb]";
$l_ifyouneedplan = "L&#39;accés del planeta";
$l_igb_term = "IGB Banca Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Il limitat";
$l_full = "Ple";
$l_equipped = "Equipada";
$l_n_a = "n / a";
$l_item = "Article";
$l_totalcost = "Cost total";
$l_would_dump = "Si desitja bolcar totes les seves colons aquí, feu clic a";
$l_noport = "No hi ha port aquí!";
$l_trade_turnneed = "Vostè necessita com a mínim un cop al comerç en un port o planeta.";
$l_returnto_port1 = "aquí";
$l_returnto_port2 = "Feu clic a [port_link] per tornar al menú del port.";
$l_notenough_cargo = "Vostè no té prou càrrega lliure és vàlida per als productes que vol comprar.";
$l_notenough_power = "Vostè no té prou capacitat d&#39;emmagatzematge d&#39;energia lliure per a l&#39;energia que vostè vol comprar.";
$l_notenough_credits = "No té crèdits suficients per completar la transacció.";
$l_notenough_turns = "No té prou torns per completar la transacció.";
$l_trade_result = "Resultats d&#39;aquest comerç";
$l_trade_complete = "Comercials acabats";
$l_trade_upgraded = "Elevat al nivell del";
$l_trade_added = "afegit";
$l_trade_installed = "instal lat";
$l_port_bounty = "No es pot tenir accés a un port especial mentre que vostè té una recompensa per la qual va posar per la Federació. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Vostè no té crèdtis suficient per pagar la prima d&#39;[amount] crèdits. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "La IGB ha emès un bloqueig del vostre compte vaixell a causa d&#39;un pagament del préstec tard. No pot comerciar en un port especial fins de pagar el seu préstec.";
$l_port_returntospecial = "per tornar a l&#39;estació de subministrament.";
$l_toprobemenu = "per anar al menú de la sonda.";
$l_ports_shiplimit = "Mínim classe de vaixells per muntar el dispositiu:";
$l_ports_needrepair = "Reparació";

$l_ports_needcredits = "No té suficients crèdits per a aquesta transacció. El cost total és de";
$l_ports_needcredits1 = "crèdits i només s&#39;han";

$l_ports_tradeforbidden = "Comerç prohibit";
$l_ports_nooutsiders = "D&#39;intercanvis comercials en aquest port no està permès per als forasters.";

$l_bought = "Vostè va comprar";
$l_sold = "Vostè va vendre";
$l_notenough_commodity = "Vostè no té prou [commodity] per completar la transacció.";
$l_exceed_commodity = "Número de [commodity] excedeix l&#39;oferta i la demanda.";
$l_port_shiptoolarge = "El seu vaixell és massa gran per al comerç en aquest port.";

$l_port_hold_unit = "Té per unitat";


$l_port_welcome = "Port [sectorname] Benvingut&#39;s [player]";
$l_port_amountforsale = "El port té [amount] unitats de [commodity] a la venda a [credits] crèdits per unitat.";
$l_port_holdsperunit = "[holds] bodegues de càrrega necessària per unitat.";
$l_port_howmanypurchase = "Quantes unitats de [commodity] vols comprar?";
$l_port_unitstobuy = "Unitats de compra";
$l_port_shipcarryingbuy = "El seu vaixell està duent a [shipunits] unitats de [commodity]. Vostè pot comprar [buyunits] unitats d&#39;espai disponible a les bodegues de càrrega.";
$l_port_howmanysell = "[amount] unitats de [commodity] @ [credits] crèdits per unitat.";
$l_port_unitstosell = "Unitats venguin";
$l_port_perform = "Fer transaccions";
$l_port_cargoholds = "Manté la càrrega";

?>
