<?php
$l_cu_storing = "Dipòsit";
$l_cu_inistored = "<b>Tots els valors d&#39;iniciatives s&#39;ha aconseguit emmagatzemar.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto ID Ruta";
$l_cu_start = "Auto ruta Inici";
$l_cu_destination = "Auto Ruta Destinació";
$l_cu_warps = "Auto Route Cabos";
$l_cu_deleteroute = "Esborrar ruta";
$l_cu_info = "Feu clic a Inicia per al Sector d&#39;espai real a aquest sector i començar a torçar-per al sector de destinació.";
$l_cu_delete2 = "Rutes Eliminar";
$l_cu_noroutes = "Absència de vies d&#39;Auto";
$l_cu_createroute = "Crear un nou Auto Ruta";
$l_cu_deleted = "Auto Rutes eliminat.";
$l_cu_return = "Tornar al menú del botó Auto Ruta";
$l_cu_created = "Auto ruta ha estat creada.";
$l_cu_realmove = "Moure espai real per al sector";
$l_cu_warpmove = "Warp per moure següent sector";
$l_cu_warpfinal = "Warp moure el sector final";
?>
