<?php
$l_footer_one_player_on = "Hi ha 1 jugador.";
$l_footer_players_on_1 = "Hi ha";
$l_footer_players_on_2 = "Jugadors connectats:";
$l_footer_until_update = "segons fins que la pròxima actualització.";
$l_footer_no_players_on = "No hi ha jugadors en línia.";

$l_footer_news = "Local FNN Notícies";
$l_footer_title = "Alien operadors Assalt";
$l_footer_help = "ajuda per aquesta pàgina.";
$l_footer_click = "Feu clic a";

$l_footer_open_slots = "Màxim en línia:";
$l_footer_onlinereset = "Player Online Time Restablir";
$l_footer_onlinecountdown = "Reproductor de temps de compte enrere en línia:";
?>
