<?php
$l_opt_title = "Seleccioneu una icona de Equip";
$l_opt_errorsize = "Error: La imatge no ha de ser major de 64x64 píxels de mida.";
$l_opt_errortype = "Error: La imatge ha de ser JPG, GIF o PNG";
$l_opt_errornographic = "Error: no gràfic seleccionat.";
$l_opt_currentavatar = "El seu actual equip Icon";
$l_opt_uploadavatar = "Carregar una icona";
$l_opt_directory = "Seleccioneu Equip icona Directori";
$l_opt_change = "Canviar directori";
$l_opt_select = "Seleccioneu equip Icon";
$l_opt_noteam = "No està en un equip.";
$l_opt_notleader = "Només el coordinador de l&#39;equip pot canviar la icona de l&#39;equip.";
$l_opt_inuse = "Tots els icones de l&#39;equip en aquest directori estan en ús.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
