<?php
$l_lrs_title = "Exploració de Llarg Abast";
$l_lrs_nofull = "La seva escàners no disposen de llarg abast complet escàner.";
$l_lrs_noturns = "Vostè necessita com a mínim $ fullscan_cost torn (s) per executar una anàlisi completa de llarg abast.";
$l_lrs_used = "Usat";
$l_lrs_turns = "al seu torn (s)";
$l_lrs_left = "esquerre";
$l_lrs_reach = "Els següents llocs es pot arribar des del sector [sector]:";
$l_lrs_links = "Enllaços";
$l_lrs_ships = "Vaixells";
$l_lrs_click = "Feu clic en un dels enllaços per anar a aquest sector.";
$l_lrs_cantscan = "No es pot escanejar el sector del sector actual!";
$l_lrs_zero = "Sector 1 està massa ple de gent per buscar vaixells!";
$l_lrs_moveto = "per moure&#39;s al sector";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Veure Log";
$l_lrs_fedjammed = "Federació s&#39;encalla tots sensor d&#39;exploracions.";
$l_lrs_sectormissile_question = "al foc de míssils sector.";
$l_log_months = "array ( &#39;gener&#39;, &#39;Febrer&#39;, &#39;Març&#39;, &#39;Abril&#39;, &#39;maig&#39;, &#39;Juny&#39;, &#39;Juliol&#39;, &#39;August&#39;, &#39;Setembre&#39;, &#39;octubre&#39;, &#39;Novembre&#39;, &#39;Desembre&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;febrer&#39;, &#39;Mar&#39;, &#39;abril&#39;, &#39;maig&#39;, &#39;juny&#39;, &#39;juliol&#39;, &#39;agost&#39;, &#39;setembre&#39;, &#39;octubre&#39;, &#39;novembre&#39;, &#39;desembre&#39;)";
?>
