<?php
$l_opt_title = "Opcions";
$l_opt_chpass = "Canviar contrasenya";
$l_opt_curpass = "Contrasenya actual:";
$l_opt_newpass = "Nova contrasenya:";
$l_opt_newpagain = "Nova contrasenya (de nou):";
$l_opt_userint = "Interfície d&#39;usuari";
$l_opt_usenew = "Utilitza el nou disseny?";
$l_opt_lang = "Idioma";
$l_opt_template = "Plantilla";
$l_opt_select = "Seleccioneu un:";
$l_opt_enabled = "Habilitat";
$l_opt_save = "Salvar";
$l_opt_teamicon = "Equip Icon";
$l_opt_shipname = "ShipName:";
$l_opt_mapwidth = "Local i Galaxy Mapa Ample:";
$l_opt_profiletitle = "Perfil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registrat amb perfil de servidor";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "En registrar el seu reproductor en un altre servidor de la plantilla, fòrum i notícies sobre la configuració s&#39;utilitzarà al servidor.";
$l_opt_showshoutbox = "Mostra Shoutbox:";
$l_opt_shownewscrawl = "Mostra Notícies de rastreig:";
$l_opt_playername = "Nom d&#39;usuari:";
$l_opt_playernamecost = "Federació de Canvi de Nom Càrrec: [amount] Crèdits";
?>
