<?php
$l_artifact_title = "Recuperar Artefacte";
$l_artifact_list_title = "Llista d&#39;artefactes adquirits";
$l_artifact_noscan = "De la seva escàner no va poder trobar l&#39;artefacte.";
$l_artifact_noturn = "No té prou torns per recollir aquest artefacte.";
$l_artifact_classname = "Nom del Artefacte";
$l_artifact_description = "Artefacte Descripció";
$l_artifact_imagename = "Imatge Artefacte";
$l_artifact_incomplete = "Artefacte Pieces";
$l_artifact_process = "Utilitzeu l&#39;artefacte Complet";

?>
