<?php
$l_chf_youretreatback = "Vostè retirar-se a la seva anterior ubicació";
$l_chf_movefailed = "Moure fracassat.";
$l_chf_thefightersdetectyou = "Els combatents detectar vostè!";
$l_chf_therearetotalfightersindest = "Hi ha [chf_total_sector_fighters] combatents en el seu sector de destinació.";
$l_chf_youcanretreat = "<B>Retiro</b> - costarà un torn extra.";
$l_chf_inputfight = "<B>Fight</b> - Vostè ha de derrotar tots els combatents a entrar en el sector.";
$l_chf_inputcloak = "<B>Capa</b> - Utilitza el dispositiu d&#39;invisibilitat i tractar d&#39;evitar els combatents.";
$l_chf_go = "Anar";
$l_chf_inputrun = "<B>Atacar i córrer</b> - Pots fer una volta d&#39;atac llampec i de retir. Però vostè pot prendre algun dany durant la retirada.";
?>
