<?php
$l_md_title = "Sector de les defenses";
$l_md_invalid = "No vàlid de defensa del sector";
$l_md_nolonger = "La defensa del sector seleccionat ja no està allà.";
$l_md_you = "tu";
$l_md_bmines = "El teu fas destruïdes";
$l_md_msgdownerb = "[name] destruïts [mines] de mines en el sector [sector].";
$l_md_retr = "Que va recuperar";
$l_md_consist = "Aquest sector de la defensa consisteix a [qty] [type] propietat de [owner].";
$l_md_youcan = "Pot";
$l_md_retrieve = "Recuperar";
$l_md_attack = "Atac";
$l_md_attdef = "Atac de les defenses del sector. Tots els combatents del sector prendrà represàlies.";
$l_md_noturn = "Vostè necessita com a mínim una vegada.";
$l_md_nothere = "Vostè necessita estar en el mateix sector que les defenses del sector.";
$l_md_notyours = "L&#39;acció no permesa. Els defenses del sector no pertanyen a vostè.";
$l_md_yours = "No es pot atacar les defenses del seu propi sector.";
?>
