<?php
$l_move_title = "Moure";
$l_move_turn = "Vostè necessita com a mínim un cop per moure&#39;s.";
$l_move_failed = "Moure failed!";
$l_rs_title = "Moure espai real";
$l_rs_whichsector = "Què sector li agradaria assolir a través d&#39;espai real?";
$l_rs_insector = "Vostè està actualment en el sector [sector] - i hi ha sectors disponibles a partir de l&#39;1 de [sector_max].";
$l_rs_submit = "Calculeu";
$l_rs_movetime = "Amb els seus motors, es prendrà [triptime] es dirigeix a completar el viatge.";
$l_rs_energy = "Vostè es reunien [energy] unitats d&#39;energia";
$l_rs_noturns = "No té prou voltes a l&#39;esquerra, i no pot embarcar-se en aquest viatge.";
$l_rs_engage_link = "Participar";
$l_rs_engage = "Ha [turns] torns. [engage] motors?";
$l_rs_invalid = "Vostè no pot espai real a aquest sector d&#39;aquí.";
$l_rs_ready = "Vostè està ara en el sector [sector]. Va utilitzar [triptime] es torna, i va guanyar la [energy] unitats d&#39;energia.";
$l_warp_invalid = "No pot deformar a aquest sector d&#39;aquí.";
$l_move_unknown = "Desconegut Movetype";
?>
