<?php
///SPIES
$l_dig_title = "Dignatari Menú";
$l_dig = "Dignataris";
$l_dig_disabled = "Dignataris són discapacitats!";
$l_dig_noturn = "Vostè necessita almenys una vegada, per enviar un dignatari d&#39;un planeta.";
$l_dig_notonboard = "No té cap mandatari a bord.";
$l_dig_ownplanet = "No es pot enviar a un dignatari d&#39;un planeta enemic.";
$l_dig_unownedplanet = "No es pot enviar a un dignatari el planeta sense amo.";
$l_dig_planetfull = "Hi ha ja estan autoritzats [max] dignataris en aquest planeta.";
$l_dig_sendtitle = "Enviament d&#39;un dignatari [digID] el planeta: <BR> Seleccioneu dignatari de la missió:";

$l_dig_codenumber = "Codi";
$l_dig_job = "Treball";
$l_dig_percent = "Percentatge";
$l_dig_move = "Moviment";
$l_dig_action = "Acció";
$l_dig_shipowner = "Propietari del vaixell";
$l_dig_shipname = "Nom del vaixell";
$l_dig_shiptype = "Vaixell de la classe";
$l_dig_shiplocation = "Situació de vaixells";
$l_dig_planetowner = "Planet Propietari";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Per realitzar un treball";
$l_dig_max = "Màxim per Planeta";
$l_dig_legend = "Dignatari Llegenda";
$l_dig_description = "Descripció dignatari";
$l_dig_waiting_description = "Dignatari crearà torpedes i els combatents a l&#39;espera d&#39;una assignació de llocs de treball.";
$l_dig_changeerror = "Dignatari d&#39;Ocupació Informe de Canvi";

$l_dig_nospieshere = "No té cap dignataris en aquest planeta!";
$l_dig_transferred = "dignataris transferits";
$l_dig_backonship = "El mandatari es troba ara en el seu vaixell.";
$l_dig_dismiss = "Desestimi el dignatari?";
$l_dig_changebutton = "Canviar";
$l_dig_notyourplanet = "No és el teu planeta.";

$l_dig_defaulttitle1 = "Dignataris de les naus enemigues";
$l_dig_defaulttitle2 = "Dignataris en els seus planetes";
$l_dig_defaulttitle3 = "Dignataris en els seus planetes";
$l_dig_defaulttitle4 = "Els dignataris del seu vaixell";

$l_dig_no1 = "No té cap dignataris a les naus enemigues.";
$l_dig_no2 = "No té cap dignataris en els seus planetes.";
$l_dig_no3 = "No té cap dignataris en els seus planetes.";
$l_dig_no4 = "No té cap dignataris en el seu vaixell.";
$l_dig_nodignitaryatall = "No té cap dignataris.";
$l_dig_notknown = "Desconegut";
$l_dig_dismiss = "Descartar";
$l_dig_dismiss2 = "Dignataris acomiadats.";
$l_dig_menu = "per tornar al menú dignatari.";

?>
