<?php
$l_opt_title = "Seleccioneu un Avatar";
$l_opt_errorsize = "Error: La imatge no ha de ser major de 64x64 píxels de mida.";
$l_opt_errortype = "Error: La imatge ha de ser JPG, GIF o PNG";
$l_opt_errornographic = "Error: no gràfic seleccionat.";
$l_opt_currentavatar = "El teu avatar actual";
$l_opt_uploadavatar = "Puja un Avatar";
$l_opt_directory = "Seleccioneu Avatar Directori";
$l_opt_change = "Canviar directori";
$l_opt_select = "Seleccionar un Avatar";
$l_opt_inuse = "Tots els avatars en aquest directori estan en ús.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
