<?php
$l_sf_attacking = "Combatents de defensa del sector estan atacant! <BR>";
$l_sf_destfight = "El teu fas destruïts [lost] combatents <BR>";
$l_sf_destfightb = "El teu fas destruïts [lost] combatents <BR>";
$l_sf_torphit = "Torpedes Vistes:";
$l_sf_destfightt = "La seva torpedes destruïts [lost] combatents <BR>";
$l_sf_fighthit = "Avions d&#39;atac:";
$l_sf_destfightall = "Vostè va destruir tots els combatents. <BR>";
$l_sf_destfightt2 = "Vostè destruïts [lost] combatents. <BR>";
$l_sf_lostfight = "Heu perdut tots els combatents. <BR>";
$l_sf_lostfight2 = "Heu perdut [lost] combatents. <BR>";
$l_sf_armorbreach = "La seva armadura es trenca! <BR>";
$l_sf_armorbreach2 = "La seva armadura és colpejat per [lost] mal. <BR>";
$l_sf_sendlog = "[player] destruïts [lost] combatents de defensa del sector en el sector [sector].";
$l_sf_lreport = "Heu perdut [armor] punts d&#39;armadura, [fighters] combatents, i utilitza [torps] torpedes. <BR><BR>";
$l_sf_shipdestroyed = "El seu vaixell ha estat destruït! <BR><BR>";
$l_sf_sendlog2 = "Combatents de defensa del sector destruïts [player] en el sector [sector].";
$l_sf_escape = "Afortunadament, vostè té una càpsula d&#39;escapament! <BR><BR>";

$l_sf_fnoattack = "no envia cap combatents a atacar els seus combatents.";
$l_sf_fnoattackt = "no envia cap combatents a atacar els seus torpedes.";
$l_sf_fnoattacka = "no envia cap combatents a atacar la seva armadura.";
$l_sf_flaunchmalf1 = "La seva posada en marxa del sistema de combat ha fallat.";
$l_sf_flaunchmalf2 = "Vostè només han estat capaços de llançar";
$l_sf_flaunchmalf3 = "per cent dels seus combatents.";
$l_sf_fightertorpexg = "De combat Torpedo / Mines d&#39;Exchange";
$l_sf_torpfighterexg = "Vaixell Torpedo al Sector Fighter Intercanvi";
$l_sf_fighterarmorexg = "Sector de combat a vaixells Armadura d&#39;Exchange";
$l_sf_tlaunchmalf1 = "El seu sistema de llançament de torpedes ha funcionat correctament.";
$l_sf_tlaunchmalf2 = "Vostè només han estat capaços de llançar";
$l_sf_tlaunchmalf3 = "per cent dels seus torpedes.";
$l_sf_bountysd = "Ha atacat a un sector que conté un planeta que li donaria una recompensa si van atacar el planeta. La Federació ha activat una auto-destrucció automàtica en tots els seus combatents i torpedes. No atac a les defenses del sector en aquest sector de nou. Vostè ha estat advertit!";
?>
