<?php
$l_s_yes = "Sí";
$l_s_no = "No";
$l_s_enabled = "Habilitat";
$l_s_disabled = "Les persones de mobilitat reduïda";

$l_s_modules = "Mòduls";
$l_s_modulename = "Nom del mòdul";
$l_s_moduleauthor = "Autor";
$l_s_moduleinfo = "Informació";
$l_s_nomodules = "N els mòduls carregats";

$l_s_gamestatus = "Joc d&#39;Estat";
$l_s_allowpl = "Permetre als jugadors";
$l_s_allownewpl = "Permetre nous jugadors";

$l_s_gameoptions = "Opcions de Joc";
$l_s_allowteamplcreds = "Permetre equip PLANET de Transferència de Crèdits";
$l_s_allowfullscan = "Permetre la plena exploració de llarg abast";
$l_s_sofa = "Permetre Sub-orbital Fighter atacs";
$l_s_showpassword = "Mostra contrasenya en registre";
$l_s_genesisdestroy = "Torps Gènesi pot destruir planetes";
$l_s_igb = "Intergalactic Banc (IGB)";
$l_s_ksm = "Conegut Espai Mapes";
$l_s_navcomp = "La navegació";
$l_s_newbienice = "Newbie Niça";
$l_s_spies = "System Spy";
$l_s_spycapture = "Permetre Spies a la captura dels planetes";

$l_s_gamesettings = "Ajustaments de joc";
$l_s_gameversion = "Versió del joc:";
$l_s_minhullmines = "La mida mínim de casc necessaris per colpejar les mines";
$l_s_averagetechewd = "Nivell Tech amitjanen quan Emergència Warp degrada";
$l_s_numsectors = "Nombre de sectors";
$l_s_maxwarpspersector = "Enllaços màxim per sector";
$l_s_averagetechfed = "Màxim nivell de tecnologia mitjana de Sectors Federació de";
$l_s_igbirateperupdate = "Taxa d&#39;interès IGB per actualització";
$l_s_igblrateperupdate = "taxa de préstec IGB per actualització";
$l_s_techupgradebase = "Tecnologia d&#39;actualització de nivell per a bases de";
$l_s_collimit = "Límit de colons";
$l_s_maxturns = "El nombre màxim de voltes acumulades";
$l_s_maxplanetssector = "Màxim nombre de planetes per sector";
$l_s_maxtraderoutes = "El nombre màxim de traderoutes per jugador";
$l_s_colreprodrate = "Taxa de natalitat de colons";
$l_s_energyperfighter = "Unitat d&#39;energia utilitzada pel sector de combat";
$l_s_secfighterdegrade = "Sector de la degradació de combat tipus de percentatge";
$l_s_planetinterest = "Taxa d&#39;interès Planet";
$l_s_spiesperplanet = "El nombre màxim d&#39;espies per planeta";
$l_s_spysuccessfactor = "Factor d&#39;èxit Spy";
$l_s_spykillfactor = "Spy matar factor d&#39;";
$l_s_colsperfighter = "Els colons necessiten per produir 1 Fighter cada torn";
$l_s_colspertorp = "Els colons necessiten per produir 1 Torpedo cada torn";
$l_s_colsperore = "Els colons necessiten per produir 1 Ore cada torn";
$l_s_colsperorganics = "Els colons necessiten per produir 1 Orgànics cada torn";
$l_s_colspergoods = "Els colons es necessita per produir 1 Mercaderies cada torn";
$l_s_colsperenergy = "Els colons necessiten per produir 1 d&#39;energia cada vegada";
$l_s_colspercreds = "Els colons necessiten per produir 1 crèdits cada vegada";
$l_s_colsper = "Els colons es necessita per produir 1 [commodity] cada vegada";

$l_s_gameschedsettings = "Joc de Programador de Configuració";
$l_s_schedtype = "Programador Tipus";
$l_s_cronbased = "Cron base";
$l_s_playertriggered = "Reproductor disparada";
$l_s_minutes = "minuts";
$l_s_ticksupdate = "Les paparres passen tots els";
$l_s_turnsupdate = "Activa passarà cada";
$l_s_npcupdate = "L&#39;Aliança jugar tots els";
$l_s_igbturnsupdate = "Interessos en els comptes de IGB s&#39;acumularan totes les";
$l_s_newsupdate = "Les notícies es genera cada";
$l_s_planetupdate = "Planetes generarà la producció de cada";
$l_s_spyupdate = "Spies actuarà cada";
$l_s_portsupdate = "Els ports es regeneren cada";
$l_s_towupdate = "Els vaixells seran remolcats dels sectors de menjar tots els";
$l_s_scoreupdate = "Classificació es genera cada";
$l_s_secdefdegrupdate = "Sector de les defenses es degraden cada";
$l_s_apocalypseupdate = "L&#39;apocalipsi planetari es produeixen cada";
$l_s_release_version = "Versió del joc";
$l_s_time_since_reset = "Temps transcorregut des de l&#39;últim reinici";
$l_s_independence = "Planetari de la Independència";
$l_s_dignitaryupdate = "Dignataris actuarà cada";

$l_s_turnsupdate = "converteix a cada";
?>
