<?php
$l_readm_title = "Llegir missatge";
$l_readm_delete = "Missatge eliminat";
$l_readm_nomessage = "Vostè no té missatges en espera per vostè ...";
$l_readm_center = "Centre de recepció de missatges";
$l_readm_sender = "Missatge del remitent";
$l_readm_captn = "Capità de la";
$l_readm_del = "Esborrar";
$l_readm_repl = "Respondre";
$l_readm_return = "Feu clic aquí per tornar al menú principal";
$l_readm_title2 = "Correu Lector";
$l_readm_delete = "Elimina tots";
$l_readm_subject = "Tema";
$l_readm_quote = "Citar";
$l_readm_block = "Bloquejar remitent";
$l_readm_alert = "Sistema d&#39;Alerta de";
$l_readm_alertbody = "Ship Informàtica";
?>
