<?php
$l_beacon_title = "Implementar Espai Beacon";
$l_beacon_notpermitted = "Implementar balises espai en aquest sector no està permès.";
$l_beacon_reads = "Faro Present lectures";
$l_beacon_none = "Existeixen en l&#39;actualitat no és un far en aquest sector.";
$l_beacon_enter = "Introduïu el text de far";
$l_beacon_nowreads = "Beacon ara diu";
$l_beacon_donthave = "Vostè no té un model d&#39;espai.";
?>
