<?php
$l_warp_cantsame = "Vostè no pot crear un enllaç quan la font és la mateixa que la de destinació.";
$l_warp_twoerror = "Mitjançant un editor de Warp per crear una connexió de dues vies per al sector [target_sector] no està permesa.";
$l_warp_sectex = "No es pot crear un enllaç de l&#39;ordit de corrents del sector - que supera el màxim de $ link_max per sector.";
$l_warp_linked = "Destinataris ([target_sector]) ja té un vincle d&#39;aquest sector.";
$l_warp_coneway = "Enllaç creat una via a";
$l_warp_ctwoway = "Vincle creat des de i cap";
$l_warp_nomoney = "No té crèdits suficients per a crear el vincle de l&#39;ordit.";
$l_warp_noenergy = "Vostè no té prou energia per a crear el vincle de l&#39;ordit.";
?>
