<?php
///SPIES
$l_spy_title = "Spy Menú";
$l_spy = "Spies";
$l_spy_disabled = "Els espies són discapacitats!";
$l_spy_noturn = "Vostè necessita almenys una vegada, per enviar un espia a un planeta.";
$l_spy_notonboard = "No té cap espies a bord.";
$l_spy_ownplanet = "No es pot enviar un espia al seu propi planeta.";
$l_spy_unownedplanet = "No es pot enviar un espia al planeta sense amo.";
$l_spy_planetfull = "Hi ha ja estan autoritzats [max] espies en aquest planeta.";
$l_spy_sendtitle = "Enviament d&#39;un espia [spyID] el planeta: <BR> Seleccioneu la missió d&#39;espionatge:";
$l_spy_type1 = "L&#39;espia actua només en aquest planeta.";
$l_spy_type2 = "L&#39;espia tracta d&#39;infiltrar-se en un vaixell que realitza una transferència del planeta.";
$l_spy_type3 = "L&#39;espia tracta d&#39;infiltrar-se en un vaixell que realitza una transferència dels planetes i que després es filtri a un altre planeta.";
$l_spy_sendbutton = "Envia-ho a planeta";
$l_spy_sendsuccessful = "El seu espia s&#39;infiltra al planeta, i espera el moment adequat per iniciar l&#39;acció.";
$l_spy_sendfailed = "Sensors planeta detectat la seva espia, ja que el dispositiu Capa no podia cobrir. El seu espia és assassinat.";
$l_spy_noturn2 = "Vostè necessita com a mínim un cop per tornar a trucar a un espia.";
$l_spy_confirm = "Estàs segur que voleu tornar a trucar al seu espia [spyID]?";
$l_spy_cleanupplanet = "per netejar el planeta dels espies enemics.";
$l_spy_cleanupship = "Si voleu netejar el seu vaixell dels espies de l&#39;enemic, feu clic a";
$l_spy_yourspies = "Els seus espies en aquest planeta";
$l_spy_sendnew = "Enviar un nou espia";

$l_spy_codenumber = "Codi";
$l_spy_job = "Treball";
$l_spy_percent = "Percentatge";
$l_spy_move = "Moviment";
$l_spy_action = "Acció";
$l_spy_shipowner = "Propietari del vaixell";
$l_spy_shipname = "Nom del vaixell";
$l_spy_shiptype = "Vaixell de la classe";
$l_spy_shiplocation = "Situació de vaixells";
$l_spy_planetowner = "Planet Propietari";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "No es mou";
$l_spy_moves['toship'] = "Per enviar";
$l_spy_moves['toplanet'] = "Per planeta";

$l_spy_comeback = "Retornar l&#39;anomenada";
$l_spy_nospieshere = "Vostè no té espies en aquest planeta!";
$l_spy_transferred = "espies transferits";
$l_spy_backonship = "L&#39;espia està ara en el seu vaixell.";
$l_spy_backfailed = "Retornar la trucada va fallar.";
$l_spy_changetitle = "Canvi d&#39;espionatge [spyID] propietats:";
$l_spy_occupied = "El seu espia [spyID] en el treball d&#39;un empleat com a [job], amb cent [percent].";
$l_spy_dismiss = "Desestimi l&#39;espia?";
$l_spy_changebutton = "Canviar";
$l_spy_changejob = "Canviar de treball o el Moviment";
$l_spy_linkback = "per anar al menú d&#39;espionatge.";
$l_spy_changed1 = "Moviment canviat.";
$l_spy_changed2 = "Spy acomiadats i el seu moviment canviat.";
$l_spy_changefailed = "Canviar no.";
$l_spy_cleanupplanettitle = "La neteja del seu planeta dels espies de l&#39;enemic:";
$l_spy_notyourplanet = "No és el teu planeta.";
$l_spy_cleanuptext[1] = "Neteja ràpida. Usos [creds] crèdits i [turns] torns.";
$l_spy_cleanuptext[2] = "Neteja millor. Usos [creds] crèdits i [turns] torns.";
$l_spy_cleanuptext[3] = "La millor neteja. Usos [creds] crèdits i [turns] torns.";
$l_spy_cannotcleanupplanet = "Vostè només ha [credits] crèdits en aquest planeta i [turns] torns.";
$l_spy_cleanupbutton1 = "Comenceu a netejar el planeta";
$l_spy_cleanupplanettitle2 = "Encendre el sensors per trobar espies enemics en aquest planeta.";
$l_spy_spyfoundonplanet = "Heu trobat un [player] &#39;s espia [spyID] al planeta. Has matat a aquest espia.";
$l_spy_spynotfoundonplanet = "No s&#39;ha trobat cap espies enemics en aquest planeta.";
$l_spy_notenough = "No té suficients crèdits o es torna a iniciar la neteja.";

$l_spy_cleanupshiptitle = "La neteja de la teva nau dels espies enemics:";
$l_spy_notinspecial = "Vostè necessita estar en un port de dispositius per netejar el seu vaixell.";
$l_spy_cleanupshiptext[1] = "Neteja ràpida. Usos [creds] crèdits i [turns] torns.";
$l_spy_cleanupshiptext[2] = "Neteja millor. Usos [creds] crèdits i [turns] torns.";
$l_spy_cleanupshiptext[3] = "La millor neteja. Usos [creds] crèdits i [turns] torns.";
$l_spy_cannotcleanupship = "Vostè només ha [credits] crèdits i [turns] torns.";
$l_spy_cleanupbutton2 = "Inicieu la neteja del seu vaixell";
$l_spy_cleanupshiptitle2 = "Encendre el sensors per trobar espies enemics en el seu vaixell.";
$l_spy_spyfoundonship = "Heu trobat un [player] &#39;s espia [spyID] al vaixell. Has matat a aquest espia.";
$l_spy_spynotfoundonship = "No s&#39;ha trobat cap espies enemics en el seu vaixell.";

$l_spy_infodeleted = "Missatge esborrat";
$l_spy_infonotyours = "No és el seu missatge.";
$l_spy_noinfo = "Els seus espies en els vaixells enemics no detectar res.";
$l_spy_infotitle = "Els seus espies han detectat la següent informació";
$l_spy_time = "Temps";
$l_spy_type = "Tipus";
$l_spy_info = "Informació";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "No és un [player] &#39;s planeta [planet] en el sector [sector].";
$l_spy_delete = "Esborrar";
$l_spy_messages = "per veure el que els seus espies han detectat.";
$l_spy_defaulttitle1 = "Espies a les naus enemigues";
$l_spy_defaulttitle2 = "Espies en els planetes de l&#39;enemic";
$l_spy_defaulttitle3 = "Espies en els seus planetes";
$l_spy_defaulttitle4 = "Espies en el seu vaixell";

$l_spy_no1 = "No té espies a les naus enemigues.";
$l_spy_no2 = "Vostè no té espies en els planetes de l&#39;enemic.";
$l_spy_no3 = "No té espies en els seus planetes.";
$l_spy_no4 = "Vostè no té espies en el seu vaixell.";
$l_spy_nospiesatall = "No té espies.";
$l_spy_notknown = "Desconegut";


$l_spy_trytitle = "En el planeta d&#39;aquest espia tractarà de";

$l_spy_cantsendfeds = "Ho sentim, espies no poden ser enviats a la Federació o de Planetes Independents.";
$l_spy_cantsendteam = "No podeu posar espies en un planeta companys d&#39;equip.";
$l_spy_messagesdeleted = "Tots els missatges eliminats";
$l_spy_deleteall = "Elimina tots";
$l_spy_onplanet = "Espies al planeta";
$l_spy_menu = "per tornar al menú Spy.";
?>
