<?php
$l_die_title = "Self-Destruct";
$l_die_rusure = "Està segur de voler destruir la seva nau? Això et traurà de la partida.";
$l_die_goodbye = "Galaxy Goodbye cruel!";
$l_die_check = "Estàs segur que vols esborrar del joc?";
$l_die_nonono = "NO! NO! NO!";
$l_die_what = "Què estava pensant?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Vostè i tots a bord del vaixell s&#39;han evaporat.";
$l_die_please1 = "Tancar sessió";
$l_die_please2 = "Si us plau, [logout_link]";
$l_die_exploit = "No jugueu amb el que no entenc.";
?>
