<?php
$l_ship2_buytitle = "La compra d&#39;un nou vaixell";
$l_ship2_storetitle = "Astillero Storage Facility";
$l_ship2_wrongclass = "La classe de vaixells especificada és incorrecta";
$l_ship2_buying = "Vostè està comprant:";
$l_ship2_tradein = "En el comerç:";
$l_ship2_value = "Actual de vaixells de valor:";
$l_ship2_newvalue = "Nou vaixell de valor:";
$l_ship2_totalcost = "Cost total:";
$l_ship2_nomoney = "No té suficients crèdits per comprar aquesta nau.";
$l_ship2_purchase = "Compra";
$l_ship2_buynstore = "Comprar nou vaixell i un vell magatzem";
$l_ship2_nomoney2 = "No té crèdits suficients per completar aquesta transacció.";
$l_ship2_paystorage = "La seva ha eliminat una nau d&#39;emmagatzematge.";
$l_ship2_turns = "Vostè necessita com a mínim [turns] torna a realitzar aquesta acció";
$l_ship2_error = "Error intern. No es pot trobar la classe de vaixells.";
$l_ship2_owned = "Que ja té aquest model de vaixell.";
$l_ship2_shipbought = "Vostè acaba de comprar un vaixell nou!";

?>
