<?php
$l_shipyard_title = "Astillero";
$l_planet = "Planet";
$l_ship_welcome = "Benvingut a la seva drassana Planetari. Actualment oferim aquests models a la venda.";
$l_ship_class = "Classe";
$l_ship_properties = "Propietats de classe";
$l_ship_current = "Actual";
$l_ship_outstorage = "Fora d&#39;emmagatzematge de";
$l_ship_storagecost = "Cost d&#39;emmagatzematge";
$l_ship_storagewarn = "Una vegada que pren el seu Pioneer d&#39;emmagatzematge que perdrà el que s&#39;expedeixen en el moment de la seva destrucció vaixell inicial.";
$l_ship_levels = "Vaixell Components Nivells";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Preu";
$l_ship_turns = "Torna a construir";
$l_ship_purchase = "Compra";
$l_ship_stored = "Emmagatzemats";
$l_ship_basehull = "Base del casc:";

$l_ship_averagemaxtech = "Tech Mitjana Màxim Nivell:";
$l_ship_averagenormaltech = "Mitjana normal Tech Nivell:";
$l_ship_averagecurrenttech = "Mitjana actual Tech Nivell:";
?>
