<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: Shoutbox::.";
$l_shout_public = "Pública";
$l_shout_team = "Equip";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "una mica més";
$l_shout_refresh = "Actualitzar";
$l_shout_close = "Tancar la finestra";
$l_shout_saved = "Nota fora de perill!";
$l_shout_return = "Tornar a la";
$l_shout_prev = "Anterior";
$l_shout_next = "Següent";
$l_shout_selectpage = "Seleccioneu la pàgina";
$l_shout_page = "Pàgina:";
$l_shout_teamtitle = ".:: ShoutBox TEAM::.";
?>
