<?php
$l_login_title = "Inici de sessió";
$l_login_pw = "Contrasenya:";
$l_login_chooseres = "No es pot determinar la resolució de la pantalla. Si us plau, escolliu la millor opció:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problemes?";
$l_login_emailus = "E-mail";
$l_login_forgot_pw = "Has oblidat la teva contrasenya? Introduïu en blanc i sessió de premsa.";
$l_login_settings = "Ajustaments de joc";
$l_login_change = "Canviar";
$l_login_title2 = "Inici Login per AATraders";
$l_login_reset1 = "He perdut la meva no programats";
$l_login_reset2 = "He perdut la meva programades:";
$l_login_reset3 = "Sched Reset:";
$l_login_notice = "Avís Important:";
$l_login_endadminnews = "Fi de l&#39;administració Notícies";
$l_login_tourney_signup = "Inscripcions Torneig habilitat";

$l_login_profile_only = "Només perfil";
$l_login_newclosed_message = "Nova Inscripcions Tancat";
$l_login_tourneymode = "Córrer Torneig";
$l_login_tourneystarts = "Comença:";
?>
