<?php
$l_autotrade_title = "Auto Traderoute Menú";
$l_autotrade_dismiss2 = "Auto Traderoutes eliminats.";
$l_autotrade_report = "Auto Traderoute Informe";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energia";
$l_autotrade_capacity = "Capacitat";
$l_autotrade_goods = "Productes Preu";
$l_autotrade_ore = "El preu del mineral";
$l_autotrade_organics = "Orgànics de preu";
$l_autotrade_energy = "Preus de l&#39;energia";
$l_autotrade_colonist = "Preu de colons";
$l_autotrade_credits = "Crèdits comercials";
$l_autotrade_delete = "Esborrar <br> Ruta";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "N Ruta";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "crèdits";
$l_autotrade_deletebutton = "Esborrar";
$l_autotrade_noroute2 = "No s&#39;ha configurat cap Traderoutes Auto.";
?>
