<?php
$l_warp_linkto = "Enllaços de plom d&#39;aquest sector a";
$l_warp_nolink = "No hi ha enllaços d&#39;aquest sector.";
$l_warp_query = "Què sector li agradaria crear un vincle a?";
$l_warp_oneway = "En un sol sentit?";
$l_warp_dest = "Alternativament, vostè pot destruir un vincle amb el sector.";
$l_warp_destquery = "Què sector li agradaria eliminar un enllaç a?";
$l_warp_bothway = "Ambdues formes";
$l_warp_create = "Crear un vincle entre l&#39;ordit Sector:";
$l_warp_andsector = "i sector:";
$l_warp_distance = "amb una distància de";
$l_warp_lightyears = "d&#39;anys llum";
$l_warp_delete = "Eliminar vincle entre l&#39;ordit Sector:";
$l_warp_costcreate = "Cost de crear:";
$l_warp_costdelete = "Cost per suprimir:";
$l_warp_costenergy = "Energia que es necessita:";
$l_warp_twoerror = "Mitjançant un editor de Warp per crear una connexió de dues vies per al sector [target_sector] no està permesa.";
?>
