<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Els nivells de la sonda";
$l_probe_engine = "Motor";
$l_probe_sensors = "Sensors";
$l_probe_cloak = "Capa";
$l_probe_title = "Sonda espacial Menú";
$l_probe_none = "No està en el mateix sector que aquesta sonda, pel que no pot interactuar amb ell.";

$l_probe_named = "Benvingut a la Sonda Número [probename], propietat de [name], ubicat al sector [sector].";
$l_probe_orders = "[orders] Sonda per buscar univers";
$l_probe_orders_link = "Programa";
$l_probe_upgrade = "[upgrade] Sensors Sonda / motor / Capa";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] Sonda per a la col.locació posterior";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Actualitzar";

$l_probe_att_link = "Atac";
$l_probe_att = "[attack] a la sonda";
$l_probe_att_sure = "Està vostè segur ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] sonda";

$l_probe_unknown = "Desconegut";
$l_plant_scn_turn = "Vostè necessita almenys una vegada a una sonda d&#39;exploració.";
$l_probe_noscan = "Sensors no poden aconseguir un acord en el blanc!";
$l_probe_logscanA = "[name] intentat explorar un dels seus sondejos en el sector [sector], però va fracassar.";
$l_probe_logscanB = "Un dels seus sondejos en el sector [sector] va ser escanejada per [name].";
$l_probe_scn_report = "Els resultats de l&#39;anàlisi en [name], de propietat de: [owner]";

$l_probe_caplog = "La sonda &#39;[probename]&#39; en el sector [sector] va ser capturat per [name].";
$l_probe_scan = "Explora el sector de la sonda [sector] i es troba:";
$l_probe_destroyprobe = "Destrueix la sonda";
$l_probe_destroyed = "Sonda Destruir!";
$l_probe_warning = "En fer això va a destruir totalment aquesta sonda";
$l_probe_confirm = "Realment volen destruir aquesta sonda?";
$l_gns_turn = "No té prou torns per destruir aquesta sonda";
$l_probe_type = "Tipus de sonda";
$l_probe_type0 = "Sonda estacionari";
$l_probe_type1 = "Sentry Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Sonda espai real";
$l_probe_type4 = "Seqüencial espai real Probe";
$l_probe_target = "Objectiu del sector";
$l_probe_ordered = "Sonda programada i començarà la recerca.";
$l_probe_order2 = "Sonda és un [type] i té com a objectiu sector [target]";
$l_probe_pickedup = "Sonda recollits i posats en actius d&#39;emmagatzematge";
$l_probe_title = "Menú Sonda";
$l_probe_messages = "per veure el que els seus espies han detectat.";

$l_probe_defaulttitle1 = "Sondes actives";
$l_probe_defaulttitle2 = "Sondes que s&#39;han recollit";
$l_probe_defaulttitle3 = "Sondes en els seus planetes";
$l_probe_defaulttitle4 = "Sondes en el seu vaixell";
$l_probe_linkback = "per anar al menú de la sonda.";
$l_probe_no1 = "No té cap sondeig actiu.";
$l_probe_no2 = "No té cap sondeig en l&#39;emmagatzematge.";
$l_probe_no3 = "No té cap sondeig en la seva planetes.";
$l_probe_no4 = "No té cap sondeig en el seu vaixell.";
$l_probe_noprobeatall = "No té cap sondeig.";
$l_probe_notknown = "Desconegut";
$l_probe_launch = "Gota";
$l_probe_detect = "Detectat";
$l_probe_codenumber = "Codi";
$l_probe_job = "Treball";
$l_probe_percent = "Percentatge";
$l_probe_move = "Moviment";
$l_probe_view = "Veure";
$l_probe_action = "Acció";
$l_probe_shipowner = "Propietari del vaixell";
$l_probe_shipname = "Nom del vaixell";
$l_probe_shiptype = "Vaixell de la classe";
$l_probe_shiplocation = "Situació de vaixells";
$l_probe_planetowner = "Planet Propietari";
$l_probe_planetname = "Planet";
$l_probe_sector = "Actual del sector";
$l_probe_tsector = "Objectiu del sector";
$l_probe_type = "Tipus de sonda";
$l_probe_forbid = "No es pot treure les sondes en aquest sector";

$l_probe2_title = "Llançament de sonda espacial";
$l_probe2_turn = "Vostè necessita com a mínim un cop d&#39;utilitzar una sonda espacial.";
$l_probe2_onplanet = "No podeu utilitzar aquest dispositiu, mentre que a la superfície del planeta.";
$l_probe2_noprobe = "No té cap sondes espacials.";
$l_probe2_forbid = "El llançament d&#39;una sonda en aquest sector no està permès.";
$l_probe2_launched = "Sonda espacial llançat!";

$l_probe2_warplink = "WarpLink";
$l_probe2_player = "Player";
$l_probe2_onboarda = "a bord d&#39;un";
$l_probe2_classship = "vaixell de la classe";
$l_probe2_traveled = "va viatjar al sector";
$l_probe2_fedjammed = "Federació s&#39;encalla tots sensor escaneja al Sector 1.";
$l_probe2_lastseen = "Vist últim vaixell";
$l_probe2_portfound = "Port que es troba";
$l_probe2_supports = "Recolza";
$l_probe2_planets = "planetes";
$l_probe2_sectord = "De defensa del sector Detectat";
$l_probe2_mines = "Mines";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Detectat vaixells";
$l_probe2_ships2 = "Detectat vaixell";
$l_probe2_noneowned = "N planetes no són propietat de que s&#39;han detectat.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Res de Detectat";
$l_probe2_nocredits = "No té suficients crèdits per a aquesta transacció. El cost total és de [total] de crèdits i només té [credits] crèdits.";

$l_probe_forbidSG = "Vostè no pot enviar una sonda tipus d&#39;espai real en el sector de Gènesi creat sectors.";
$l_probe_forbidFED = "Vostè no pot enviar una sonda tipus d&#39;espai real en la Federació o Aliança dels sectors de propietat.";
$l_probe_forbidINVALID = "El seu sector de destinació és el nom d&#39;un sector no vàlid.";
?>
