<?php
$l_footer_one_player_on = "Há 1 jogador.";
$l_footer_players_on_1 = "Há";
$l_footer_players_on_2 = "Jogadores online:";
$l_footer_until_update = "segundos, até a próxima atualização.";
$l_footer_no_players_on = "Não existem jogadores online.";

$l_footer_news = "Local FNN News";
$l_footer_title = "Traders Alien Assault";
$l_footer_help = "para ajuda sobre esta página.";
$l_footer_click = "Clique";

$l_footer_open_slots = "Máximo Online:";
$l_footer_onlinereset = "Leitor Online Reset do Tempo em";
$l_footer_onlinecountdown = "Jogador Tempo Online Countdown:";
?>
