<?php
$l_sm_title = "Setor de lançamento de míssil";
$l_sm_invalid = "Não há uma ligação entre este sector da urdidura e do setor de destino.";
$l_sm_notarg = "Meta não neste sector.";
$l_sm_noturn = "Você precisa de pelo menos uma vez ao fogo o Setor de Mísseis.";
$l_sm_nosectormissile = "Você não está carregando nenhum Mísseis Setor.";
$l_sm_noscan = "Sensores não pode obter uma correção no alvo!";
$l_sm_flee = "Target as manobras dos Mísseis Setor!";
$l_sm_ewd = "Alvo de um dispositivo acoplado warp emergência quando detectado o Setor de Mísseis!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] está a atacar o seu navio com um míssil do Setor!";
$l_sm_sectormissilefail = "O Setor de Mísseis avariam quando ele acertar o inimigo escudo navios!";
$l_sm_sectormissilefail2 = "O Setor de Mísseis avariam quando ele acertar o inimigo de armadura navios!";
$l_sm_shieldhit = "[target] &#39;s escudos são atingidos por [amount] dano!";
$l_sm_shieldsdown = "[target] &#39;s escudos estão no chão!";
$l_sm_armorhit = "[target] &#39;s armadura é hit de [amount] dano!";
$l_sm_armorbreached = "[target] &#39;s armadura violado!";
$l_sm_targetnoenergy = "O navio inimigo não possui energia! Setor míssil falhar!";
$l_sm_attacking = "Atacando [target], a bordo do [shipname]";
$l_sm_targetok = "Você não destory [name] &#39;s navio.";
$l_sm_lost = "[target] lost [armor] pontos de armadura e os [energy].";
$l_sm_destroyed = "[target] &#39;s navio foi destruído.";
$l_sm_escapepod = "Um módulo de emergência foi lançada!";
?>
