<?php
$l_ze_title = "Edit Zone";
$l_ze_notowner = "Você não é proprietário da zona, para que você não pode editar.";
$l_ze_name = "Nome da zona";
$l_ze_allow = "Permitir";
$l_ze_attacks = "Permitir a atacar outros navios";
$l_ze_genesis = "Permitir a criação de novos planetas";
$l_ze_return = "para voltar à página de informações sobre a zona";
$l_ze_saved = "Suas alterações foram salvas.";
$l_ze_namematch = "ERRO: O Nome da zona, desde que seja semelhante ou corresponda a um nome de zona existente.";
?>
