<?php
$l_mail_title = "Mail Password";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "A senha foi enviada para";
$l_mail_topic = "Senha $ game_name";
$l_mail_message = "$ Ip cumprimentos, \ n \ nSomeone a partir do endereço IP solicitado que a sua senha em R $ game_name será enviado a você \ n \ nA sua senha é: [pass] \ n \ nObrigado \ n \ nA equipe de web $ game_name.";
$l_new_login = "para ir para a tela de login.";
$l_mail_failed = "Senha não conseguiu enviar para o";
?>
