<?php
$l_nav_title = "Navegação Computador";
$l_nav_nocomp = "Navegação computador não estiver disponível";
$l_nav_query = "Digite sector a encontrar o caminho para:";
$l_nav_pathfnd = "Caminho encontrado";
$l_nav_answ1 = "Irá demorar";
$l_nav_answ2 = "voltas para chegar a este sector.";
$l_nav_proper = "Você precisa atualizar seu Fighter tecnologia Bay antes de seus lutadores podem encontrar uma rota de urdidura para essa distância.";
$l_nav_autoroutename = "Nome Autoroute Opcional:";
$l_nav_manuallist = "Criada manualmente WarpLink Lista Autoroute";
$l_nav_warplinksleaving = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Não há warplinks deixar este sector.";
$l_nav_warp_from = "Warp from";
$l_nav_rs_from = "RSMove de";
$l_nav_notinlogs = "Não há dados disponíveis sobre este sector.";
?>
