<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".: SHOUTBOX:::.";
$l_shout_public = "Público";
$l_shout_team = "Equipe";
$l_shout_smiles = "Carinha de";
$l_shout_else = "diferente";
$l_shout_refresh = "Refresh";
$l_shout_close = "Fechar Janela";
$l_shout_saved = "Shout salvo!";
$l_shout_return = "Voltar à";
$l_shout_prev = "Anterior";
$l_shout_next = "Próximo";
$l_shout_selectpage = "Seleccione a Página";
$l_shout_page = "Página:";
$l_shout_teamtitle = ".:: SHOUTBOX TEAM::.";
?>
