<?php
$l_opt_title = "Selecione um ícone Team";
$l_opt_errorsize = "Erro: A imagem não pode ser maior que 64x64 pixels de tamanho.";
$l_opt_errortype = "Erro: A imagem deve ser JPG, GIF ou PNG";
$l_opt_errornographic = "Erro: nenhum gráfico selecionado.";
$l_opt_currentavatar = "Sua equipe atual Icon";
$l_opt_uploadavatar = "Upload an Icon";
$l_opt_directory = "Select Team Icon Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Select Team Icon";
$l_opt_noteam = "Você não está em uma equipe.";
$l_opt_notleader = "Apenas o Coordenador da equipe podem alterar o símbolo da equipe.";
$l_opt_inuse = "Todos os ícones da equipe neste diretório estão em uso.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
