<?php
$l_sn_title = "Notas Sectoriais";
$l_sn_pntitle = "Setores com notas pessoais";
$l_sn_tntitle = "Setores com Team Notes";
$l_sn_psntitle = "Personal Sector Notas";
$l_sn_tsntitle = "Equipe do Setor Notas";
$l_sn_editnote = "Editar Nota Setor:";
$l_sn_deleteedit = "Excluir ou Editar:";
$l_sn_addnote = "Adicionar Nota Setor:";
$l_sn_list = "Setores de Notas Lista";
$l_sn_listts = "Setores Lista com a Equipe de Notas";
$l_sn_addteam = "Adicionar Team";
$l_sn_deleteteam = "Excluir Team";
$l_sn_delete = "Excluir";
$l_sn_saveteam = "Save Team";
$l_sn_deletepersonal = "Apagar Personal";
$l_sn_addpersonal = "Adicionar pessoais";
$l_sn_savepersonal = "Salve pessoal";
$l_sn_editpersonal = "Edit Personal";
$l_sn_editteam = "Edit Team";

$l_sn_hdsector = "Setor";
$l_sn_hdtype = "Tipo";
$l_sn_hdowner = "Proprietário / Team";
$l_sn_hdplanets = "Planetas";
$l_sn_hdport = "Porto";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Minas";
$l_sn_hdscanfrom = "De Scan";
$l_sn_hddetail = "Detalhes";
$l_sn_hddate = "Data / Hora";
$l_sn_hddelete = "Excluir";
$l_sn_hdteam = "Equipe";
$l_sn_view = "Visualizar";
$l_sn_no = "Não";
$l_sn_yes = "Sim";
$l_sn_nonotes = "No sector Notes Found";

?>
