<?php
$l_login_sclosed = "Server Fechado";
$l_login_closed_message = "Servidor fechado até novo aviso.";
$l_login_title2 = "Entrar Phase Two";
$l_login_banned = "<b>Você foi banido do jogo, o administrador. Você não está mais vindo para jogar neste servidor. Da próxima vez, se comportam.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "Devido à gravidade deste crime e do violento ataque contra você, a Federação tem graciosamente decidiram apresentar uma taxa livre de clonagem de seus restos. Infelizmente, a propriedade, mesmo nos dias de hoje, novos clones não podem possuir, além das noções básicas para fazer uma vida. Você será fornecido com um navio de base e alguns créditos para você começar. Esperemos que a sua próxima vida será melhor.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Você não tinha saídas de emergência e, devido ao seu modesto sucesso na vida, a Federação se recusa a clonar você. Seu permanece deve, eventualmente, cair em um poço gravitacional, esperemos que para ser usado para criar a vida em outro lugar ... vários bilhões de anos. <BR><BR> Melhor sorte do próximo jogo ...";
$l_login_4gotpw1 = "A senha digitada está incorreta. <BR><BR> Se você tiver esquecido sua senha,";
$l_login_4gotpw2 = "para tê-lo por e-mail para você. <BR><BR> De outra maneira,";
$l_login_4gotpw3 = "para tentar novamente. Tentativa registradas com o endereço IP do";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Você tem morrido em um acidente horrível.";
$l_login_blackbox = "blackbox é a informação que foi recuperada a partir do seu destroços de navios.";
$l_new_login = "para ir para a tela de login.";
$l_login_playerlimit = "O servidor atingiu o número máximo de jogadores que ele suporta. Tente fazer login em um momento posterior.";
?>
