<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Bem-vindo ao Casino, que atualmente oferecem os seguintes jogos e Instalações";
$l_casino_option = "&quot;Quartos";
$l_casino_detail = "&quot;Descrição";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "First Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Seguro";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Divisão";
$l_credits = "Créditos";
$l_yourbet = "&quot;Sua Aposta";
$l_nobet = "&quot;Sua aposta ultrapassou seu limite de crédito, por favor, aposta novamente.";
$l_dealerwins = "Ganha Dealer!";
$l_dealerbust = "Bust Dealer!";
$l_dealerloses = "Perde Dealer!";
$l_dealerblackjack = "Dealer!";
$l_push = "PUSH";
$l_playerwins = "&quot;Jogador ganha!";
$l_playerbust = "&quot;O jogador rebenta!";
$l_playerloses = "&quot;Jogador Perde!";
$l_playerblackjack = "&quot;Jogador BlackJack!";
$l_place_bet = "&quot;Faça a sua aposta";
?>
