<?php
$l_opt_title = "Selecione um Avatar";
$l_opt_errorsize = "Erro: A imagem não pode ser maior que 64x64 pixels de tamanho.";
$l_opt_errortype = "Erro: A imagem deve ser JPG, GIF ou PNG";
$l_opt_errornographic = "Erro: nenhum gráfico selecionado.";
$l_opt_currentavatar = "Seu avatar atual";
$l_opt_uploadavatar = "Enviar um Avatar";
$l_opt_directory = "Selecione Avatar Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Selecione Avatar";
$l_opt_inuse = "Todos os avatares neste diretório estão em uso.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
