<?php
///SPIES
$l_spy_title = "Spy Menu";
$l_spy = "Spies";
$l_spy_disabled = "Os espiões são deficientes!";
$l_spy_noturn = "Você precisa de pelo menos uma vez para enviar um espião para um planeta.";
$l_spy_notonboard = "Você não tem nenhum espiões a bordo.";
$l_spy_ownplanet = "Você não pode enviar um espião no seu próprio planeta.";
$l_spy_unownedplanet = "Você não pode enviar um espião para o planeta sem dono.";
$l_spy_planetfull = "Há já permitiu [max] espiões sobre esse planeta.";
$l_spy_sendtitle = "O envio de um espião [spyID] para o planeta: <BR> Selecione missão de espionagem:";
$l_spy_type1 = "O espião atua somente naquele planeta.";
$l_spy_type2 = "O espião tenta se infiltrar em um navio que efectua uma transferência planetária.";
$l_spy_type3 = "O espião tenta se infiltrar em um navio que efectua uma transferência planetária e, em seguida, se infiltrar para outro planeta.";
$l_spy_sendbutton = "Enviar para o planeta";
$l_spy_sendsuccessful = "Seu espião infiltrado no planeta e aguarda o momento certo para iniciar a ação.";
$l_spy_sendfailed = "Sensores do planeta detectado o espião, pois o dispositivo não poderia Manto de cobri-lo. Seu espião é morto.";
$l_spy_noturn2 = "Você precisa de pelo menos uma vez de chamar de volta um espião.";
$l_spy_confirm = "Tem certeza que deseja chamar de volta seu espião [spyID]?";
$l_spy_cleanupplanet = "para limpar o planeta de espiões inimigos.";
$l_spy_cleanupship = "Se você quiser limpar o seu navio de espiões inimigos, clique em";
$l_spy_yourspies = "Seu espiões sobre o planeta";
$l_spy_sendnew = "Enviar um novo espião";

$l_spy_codenumber = "Código";
$l_spy_job = "Trabalho";
$l_spy_percent = "Percentual";
$l_spy_move = "Movimento";
$l_spy_action = "Ação";
$l_spy_shipowner = "Armador";
$l_spy_shipname = "Nome do Navio";
$l_spy_shiptype = "Navios da classe";
$l_spy_shiplocation = "Navio Localização";
$l_spy_planetowner = "Planet Proprietário";
$l_spy_planetname = "Planet";
$l_spy_sector = "Setor";

$l_spy_moves['none'] = "Não move";
$l_spy_moves['toship'] = "Para enviar";
$l_spy_moves['toplanet'] = "Para planeta";

$l_spy_comeback = "Avocação";
$l_spy_nospieshere = "Você não tem espiões em todo o planeta!";
$l_spy_transferred = "espiões transferidos";
$l_spy_backonship = "O espião está agora no seu navio.";
$l_spy_backfailed = "Chamada de volta falha.";
$l_spy_changetitle = "Mudar espião [spyID] propriedades:";
$l_spy_occupied = "Seu espião [spyID] no empregada como um trabalho [job], com cento [percent].";
$l_spy_dismiss = "Dispensar o espião?";
$l_spy_changebutton = "Alterar";
$l_spy_changejob = "Mudança de emprego ou Movimento";
$l_spy_linkback = "para ir para o menu de espionagem.";
$l_spy_changed1 = "Circulação alterada.";
$l_spy_changed2 = "Spy indeferido e seu movimento mudou.";
$l_spy_changefailed = "Mudança falha.";
$l_spy_cleanupplanettitle = "Limpando o seu planeta de espiões inimigos:";
$l_spy_notyourplanet = "Não é o seu planeta.";
$l_spy_cleanuptext[1] = "Limpeza rápida. Usa [creds] e créditos [turns] turnos.";
$l_spy_cleanuptext[2] = "Melhor limpeza. Usa [creds] e créditos [turns] turnos.";
$l_spy_cleanuptext[3] = "A melhor limpeza. Usa [creds] e créditos [turns] turnos.";
$l_spy_cannotcleanupplanet = "Você só tem [credits] créditos nesse planeta e [turns] turnos.";
$l_spy_cleanupbutton1 = "Se limpar o planeta";
$l_spy_cleanupplanettitle2 = "Você ligou o Sensores de encontrar espiões inimigos nesse planeta.";
$l_spy_spyfoundonplanet = "Encontrou um jogador [player] &#39;s espião [spyID] sobre o planeta. Você matou o espião.";
$l_spy_spynotfoundonplanet = "Você não encontramos nenhum espiões inimigos nesse planeta.";
$l_spy_notenough = "Você não tem créditos suficientes ou voltas para iniciar a limpeza.";

$l_spy_cleanupshiptitle = "Limpando o seu navio de espiões do inimigo:";
$l_spy_notinspecial = "Você precisa ser um porto Dispositivos para limpar o seu navio.";
$l_spy_cleanupshiptext[1] = "Limpeza rápida. Usa [creds] e créditos [turns] turnos.";
$l_spy_cleanupshiptext[2] = "Melhor limpeza. Usa [creds] e créditos [turns] turnos.";
$l_spy_cleanupshiptext[3] = "A melhor limpeza. Usa [creds] e créditos [turns] turnos.";
$l_spy_cannotcleanupship = "Você só tem [credits] e créditos [turns] turnos.";
$l_spy_cleanupbutton2 = "Iniciar a limpeza do seu navio";
$l_spy_cleanupshiptitle2 = "Você ligou o Sensores de encontrar espiões inimigos em seu navio.";
$l_spy_spyfoundonship = "Encontrou um jogador [player] &#39;s espião [spyID] no seu navio. Você matou o espião.";
$l_spy_spynotfoundonship = "Você não encontramos nenhum espiões inimigos em seu navio.";

$l_spy_infodeleted = "Mensagem apagada";
$l_spy_infonotyours = "Não é a sua mensagem.";
$l_spy_noinfo = "Seu espiões sobre navios inimigos não detectar nada.";
$l_spy_infotitle = "Seu espiões detectaram as seguintes informações";
$l_spy_time = "Tempo";
$l_spy_type = "Tipo";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Há um jogador [player] &#39;s planeta [planet] no sector [sector].";
$l_spy_delete = "Excluir";
$l_spy_messages = "para ver o que seus espiões detectaram.";
$l_spy_defaulttitle1 = "Espiões em naves inimigas";
$l_spy_defaulttitle2 = "Espiões em planetas inimigos";
$l_spy_defaulttitle3 = "Espiões em seus planetas";
$l_spy_defaulttitle4 = "Espiões em seu navio";

$l_spy_no1 = "Você não tem nenhum espiões sobre navios inimigos.";
$l_spy_no2 = "Você não tem nenhum espiões em planetas inimigo.";
$l_spy_no3 = "Você não tem nenhum espiões em seus planetas.";
$l_spy_no4 = "Você não tem nenhum espiões no seu navio.";
$l_spy_nospiesatall = "Você não tem nenhum espiões.";
$l_spy_notknown = "Desconhecido";


$l_spy_trytitle = "No planeta deste espião que vai tentar";

$l_spy_cantsendfeds = "Spies Desculpe, mas não pode ser enviada para a Federação ou a planetas independentes.";
$l_spy_cantsendteam = "Você não pode colocar espiões em um planeta companheiros de equipe.";
$l_spy_messagesdeleted = "Todas as mensagens apagadas";
$l_spy_deleteall = "Delete All";
$l_spy_onplanet = "Espiões no planeta";
$l_spy_menu = "para retornar ao Menu Spy.";
?>
