<?php
$l_md_title = "Defesas do Setor";
$l_md_invalid = "Invalid defesa do Sector";
$l_md_nolonger = "A defesa do setor selecionado não está mais lá.";
$l_md_you = "você";
$l_md_bmines = "Seu vigas destruídos";
$l_md_msgdownerb = "[name] destruído [mines] minas no sector [sector].";
$l_md_retr = "Está recuperado";
$l_md_consist = "Este setor da defesa consiste em [qty] [type] owned by [owner].";
$l_md_youcan = "Você pode";
$l_md_retrieve = "Recuperar";
$l_md_attack = "Ataque";
$l_md_attdef = "Ataque as defesas do Setor. Todos os lutadores do setor vai retaliar.";
$l_md_noturn = "Você precisa de pelo menos uma vez.";
$l_md_nothere = "Você precisa ser no mesmo sector, como as defesas do setor.";
$l_md_notyours = "Ação não autorizada. Os defesas do sector não lhe pertencem.";
$l_md_yours = "Você não pode atacar suas defesas próprio sector.";
?>
