<?php
$l_shipyard_title = "Estaleiro";
$l_planet = "Planet";
$l_ship_welcome = "Bem vindo ao seu estaleiro Planetário. Atualmente, oferecemos esses modelos para venda.";
$l_ship_class = "Classe";
$l_ship_properties = "Propriedades de Classe";
$l_ship_current = "Atual";
$l_ship_outstorage = "Saia de Armazenamento";
$l_ship_storagecost = "Custo de armazenamento";
$l_ship_storagewarn = "Depois de levar o seu Pioneer de armazenamento que você vai perder aquele que foram emitidas após a sua destruição navio inicial.";
$l_ship_levels = "Navio Componentes Níveis";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Preço";
$l_ship_turns = "Vira-se para construir";
$l_ship_purchase = "Adquirir";
$l_ship_stored = "Armazenado";
$l_ship_basehull = "Base de casco:";

$l_ship_averagemaxtech = "Média Máxima Tech Level:";
$l_ship_averagenormaltech = "Nível Médio Normal Tech:";
$l_ship_averagecurrenttech = "Média atual Tech Level:";
?>
