<?php
$l_profile_title = "Perfil de Inscrição";
$l_profile_notenabled = "Perfis não estão habilitados neste servidor.";
$l_profile_registered = "Este jogador está registrado com o perfil Master Server.";
$l_profile_nomatch = "Não poderia corresponder a um perfil sobre o perfil Master Server com o nome ea senha do servidor inscrito.";
$l_profile_tryagain = "Para introduzir o nome do perfil de jogador e senha do servidor clique novamente";
$l_profile_name = "Perfil Nome do jogador";
$l_profile_password = "Perfil Server Password";
$l_profile_bannedserver = "Este servidor não é permitida a apresentação de informações de perfil para o perfil Master Server.";
$l_profile_bannedplayer = "Você foi banido do perfil Master Server e não pode registrar jogadores.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Este <u><b>servidor</b></u> requer cada novo jogador para ter um perfil cadastrado. Você não terá permissão para criar um novo jogador a menos que você tenha um perfil cadastrado.";
$l_profile_updated = "O modelo, shoutbox e notícias rastrear as configurações globais foram atualizados sobre o perfil do servidor mestre. Estas definições serão automaticamente ser usado quando você registrar o seu perfil em qualquer jogo.";

?>
