<?php
$l_chf_youretreatback = "Você recuar para a sua localização anterior";
$l_chf_movefailed = "Mover falhou.";
$l_chf_thefightersdetectyou = "Os lutadores detectar você!";
$l_chf_therearetotalfightersindest = "Existem [chf_total_sector_fighters] combatentes no seu sector de destino.";
$l_chf_youcanretreat = "<B>Retiro</b> - custará um turno extra.";
$l_chf_inputfight = "<B>Fight</b> - Você deve derrotar todos os lutadores a entrar no setor.";
$l_chf_inputcloak = "<B>Manto</b> - Use o seu dispositivo de camuflagem e tentar evitar os lutadores.";
$l_chf_go = "Ir";
$l_chf_inputrun = "<B>Ataque e Run</b> - Você faz uma corrida de ataque relâmpago e de recuo. Mas você pode tomar algum dano durante o retiro.";
?>
