<?php
$l_warp_unlinked = "Alvo sector (target_sector [target_sector]) não tem uma ligação deste sector.";
$l_warp_forbidtwo = "Usando um editor de Warp para remover uma ligação nos dois sentidos para o setor [target_sector] não é permitida.";
$l_warp_removed = "Link removido para";
$l_warp_removedtwo = "Link removido para e";
$l_warp_nomoney = "Você não tem créditos suficientes para apagar a ligação da urdidura.";
$l_warp_noenergy = "Você não tem energia suficiente para apagar a ligação da urdidura.";
?>
