<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Seu scanners não possuem a longa varredura completa de capacidades.";
$l_lrs_noturns = "Você precisa de pelo menos R $ fullscan_cost turno (s) para executar uma ampla gama longa varredura.";
$l_lrs_used = "Usado";
$l_lrs_turns = "turno (s)";
$l_lrs_left = "esquerdo";
$l_lrs_reach = "As próximas localidades podem ser alcançadas a partir do setor [sector]:";
$l_lrs_links = "Links";
$l_lrs_ships = "Navios";
$l_lrs_click = "Clique em um dos links para mover para o setor.";
$l_lrs_cantscan = "Não é possível digitalizar sector do setor atual!";
$l_lrs_zero = "Setor 1 é muito lotado para digitalizar para navios!";
$l_lrs_moveto = "para mover para o setor";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Ver Log";
$l_lrs_fedjammed = "Federação está emperrando toda sensor varreduras.";
$l_lrs_sectormissile_question = "para disparar mísseis setor.";
$l_log_months = "array ( &#39;Janeiro&#39;, &#39;Fevereiro&#39;, &#39;Março&#39;, &#39;Abril&#39;, &#39;Maio&#39;, &#39;Junho&#39;, &#39;Julho&#39; Agosto &#39;,&#39; Setembro &#39;,&#39; Outubro &#39;,&#39; Novembro &#39;,&#39; Dezembro &#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;Fev&#39;, &#39;Mar&#39;, &#39;Abr&#39;, &#39;Maio&#39;, &#39;Jun&#39;, &#39;Jul&#39;, &#39;Ago&#39;, &#39;Set&#39;, &#39;Out&#39;, &#39;Nov&#39;, &#39;Dez&#39;)";
?>
