<?php
$l_artifact_title = "Recuperar Artefato";
$l_artifact_list_title = "Lista de Artefatos Adquirida";
$l_artifact_noscan = "Seu scanners não conseguiu encontrar o artefato.";
$l_artifact_noturn = "Você não tem o suficiente se vira para pegar este artefato.";
$l_artifact_classname = "Nome do Artefato";
$l_artifact_description = "Artefato Descrição";
$l_artifact_imagename = "Imagem Artefato";
$l_artifact_incomplete = "Artefato Pieces";
$l_artifact_process = "Use o Artefato Completed";

?>
