<?php
$l_warp_linkto = "Links ligação deste sector para";
$l_warp_nolink = "Não existem ligações para fora do sector.";
$l_warp_query = "O setor pretende criar um vínculo para?";
$l_warp_oneway = "One-way?";
$l_warp_dest = "Alternativamente, você pode destruir um link para o sector.";
$l_warp_destquery = "O setor pretende remover um link para?";
$l_warp_bothway = "Ambas as formas";
$l_warp_create = "Criar uma ligação entre a urdidura Sector:";
$l_warp_andsector = "Setor:";
$l_warp_distance = "com uma distância de";
$l_warp_lightyears = "anos-luz";
$l_warp_delete = "Excluir o vínculo entre a urdidura Sector:";
$l_warp_costcreate = "Custo para criar:";
$l_warp_costdelete = "Custo para eliminar:";
$l_warp_costenergy = "Energia necessária:";
$l_warp_twoerror = "Usando um editor de Warp para criar uma ligação nos dois sentidos para o setor [target_sector] não é permitida.";
?>
