<?php
$l_gns_title = "Uso de dispositivo Genesis";
$l_gns_turn = "Você precisa de pelo menos uma vez de usar um dispositivo de gênese.";
$l_gns_onplanet = "Você não pode usar este dispositivo, enquanto na superfície do planeta.";
$l_gns_full = "Esse sistema solar já está cheio.";
$l_gns_planetex = "Já existe um planeta neste setor.";
$l_gns_nogenesis = "Você não tem nenhum dispositivo de gênese.";
$l_gns_forbid = "Criando um planeta neste setor não é permitido.";
$l_gns_bforbid = "As bases deste sector estão a interferir com o seu dispositivo gênese. Criação Planet não é possível.";
$l_gns_pcreate = "Planet criado.";
$l_sgns_title = "Use Setor Genesis Device";
$l_sgns_pcreate = "Setor [name] criado.";
$l_sgns_nogenesis = "Você não tem nenhum dispositivo gênese setor.";
$l_sgns_forbid = "Criando um buraco de minhoca gênese do setor neste setor não é permitido.";
$l_sgns_forbid1 = "Criação de uma gênese do setor wormhole um Sector Federação não é permitido.";
$l_sgcreate = "Criar Nova Gênese Sector Sector";
$l_sgcreatens = "Criar novo Setor Genesis Link volta para o espaço conhecido";
$l_sgns_forbid2 = "Mais de [limit] links em SG Setores não são permitidas.";
$l_sgns_forbid3 = "Não é possível criar link do Sector da urdidura do Genesis da actual sector - que ultrapassar o limite de [limit] por setor.";
$l_sgns_nocredits = "Você não tem créditos suficientes para criar um novo setor.";
$l_sgns_shipcredits = "Créditos a bordo:";
$l_sgns_createcost = "Custo para criar novo setor:";
$l_sgns_complete = "Normal Espacial Completa Link";
$l_sgns_sectorname = "Digite o Nome do Setor:";
$l_gns_max_unbased_planets = "A Federação não vai permitir a criação de mais planetas até que você tenha menos de [max_unbased_planets] planetas sem embasamento norteador.";

?>
