<?php
$l_move_title = "Mover";
$l_move_turn = "Você precisa de pelo menos uma vez de jogar.";
$l_move_failed = "Move failed!";
$l_rs_title = "Realspace Move";
$l_rs_whichsector = "Que setor você gostaria de alcançar, por intermédio Realspace?";
$l_rs_insector = "Você está atualmente no setor [sector] - e há setores disponíveis a partir de 1 de [sector_max].";
$l_rs_submit = "Compute";
$l_rs_movetime = "Com seus motores, vai demorar [triptime] turnos para completar a viagem.";
$l_rs_energy = "Você iria reunir [energy] unidades de energia";
$l_rs_noturns = "Você não tem o suficiente virar à esquerda, e não pode embarcar nesta viagem.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "Você tem [turns] turnos. [engage] motores?";
$l_rs_invalid = "Você não pode Realspace para o setor a partir daqui.";
$l_rs_ready = "Você está agora no sector [sector]. Você usou [triptime] voltas, e ganhou [energy].";
$l_warp_invalid = "Você não pode deformar a este sector a partir daqui.";
$l_move_unknown = "Desconhecido movetype";
?>
