<?php
$l_autoroute_missingwarp = "WarpLink seguinte está em falta no setor. Warp jogada anulada.";
$l_autoroute_SDabort = "Move abortada devido às defesas do Setor no setor.";
$l_autoroute_turns = "Deduzidos triptime [triptime] Liga e se mudou para targetlink [triptime]";
$l_autoroute_noturns = "Está fora de voltas.";
$l_autoroute_title = "Auto Rotas";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Start Rota";
$l_autoroute_destination = "Auto Route Destino";
$l_autoroute_warps = "Auto Route Warps";
$l_autoroute_deleteroute = "Delete Route";
$l_autoroute_info = "Clique em Iniciar para o Setor Realspace para o setor e começar a entortar para o setor de destino.";
$l_autoroute_delete2 = "Excluir Rotas";
$l_autoroute_noroutes = "No Auto Rotas";
$l_autoroute_createroute = "Criar Nova Auto Route";
$l_autoroute_deleted = "Auto Rotas excluída.";
$l_autoroute_return = "Retornar para Auto Route Menu, clique em";
$l_autoroute_created = "Auto Rota foi criada.";
$l_autoroute_realmove = "Realspace mover para o setor";
$l_autoroute_warpmove = "Warp mover para o próximo sector";
$l_autoroute_warpfinal = "Warp mover para o setor final";
$l_autoroute_editname = "Editar Nome";
?>
