<?php
$l_by_title = "Bounties";
$l_by_noturn = "Você precisa de pelo menos uma vez ao lugar ou modificar uma recompensa.";
$l_by_amount = "Bounty Montante";
$l_by_place = "Coloque Bounty";
$l_by_nobounties = "Actualmente não há incentivos.";
$l_by_bountyon = "Na Bounty";
$l_by_placedby = "Colocado por";
$l_by_thefeds = "A Federação";
$l_by_cancel = "Cancelar";
$l_by_yourself = "Você não pode colocar uma recompensa pela sua autodeterminação.";
$l_by_notenough = "Você não tem créditos suficientes para colocar uma recompensa desse montante.";
$l_by_toomuch = "Você não pode colocar esse prémio. Bounty máxima permitida em um outro jogador é [percent] por cento do seu patrimônio líquido";
$l_by_zeroamount = "Bounties deve ser maior que 0 créditos.";
$l_by_placed = "A recompensa foi colocada.";
$l_by_nobounty = "Essa graça não existe mais.";
$l_by_notyours = "Esse prêmio não foi colocado por você.";
$l_by_canceled = "O prémio foi cancelada.";
$l_by_action = "Ação";
$l_by_placebounty = "Coloque ou generosidades vista.";
$l_by_moredetails = "Clique no nome para mais detalhes.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "O jogador que você está colocando a graça de não existir.";
$l_by_destroyed = "Você não pode colocar uma recompensa pela cabeça de um jogador com um navio destruído.";
$l_by_nofedbounty = "Você não receberá uma recompensa se você atacar o navio jogadores ou planeta.";
$l_by_fedcollectonly = "Apenas Federação pode Collect Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Você não receberá uma recompensa se você colocar um espião do planeta jogadores.";
$l_pay_partial = "Fazer o Pagamento Parcial";
$l_pay_button = "Pago";

$l_by_thealliance = "A Aliança";
$l_by_alliancecollectonly = "Só que a Aliança pode Collect Bounty";
$l_by_bountyscan = "Bounty";
?>
