<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] hit chm_roll [chm_roll] minas no sector [chm_sector].";
$l_chm_youlostminedeflectors = "Você perdeu [chm_roll] defletores de minas.";
$l_chm_youlostallminedeflectors = "Você já perdeu todo defletores de sua mina.";
$l_chm_youhadnominedeflectors = "Você não tinha defletores de minas.";
$l_chm_yourshieldshitforminesdmg = "Seu escudos são atingidos por [chm_mines_left] dano.";
$l_chm_yourshieldsaredown = "Seu escudos estão no chão!";
$l_chm_youlostallyourshields = "Você perdeu todos os seus escudos!";
$l_chm_yourarmorhitforminesdmg = "Sua armadura é atingido por [chm_mines_left] dano.";
$l_chm_yourhullisbreached = "Seu casco está quebrado!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name], foi destruída por seu minas no sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Seu navio foi destruído!";
$l_chm_luckescapepod = "Felizmente, você tem um escape pod!";

$l_chm_yourdeflectormalf1 = "Mine Deflector sistema de lançamento não está funcionando corretamente.";
$l_chm_yourdeflectormalf2 = "Você só tem sido capaz de lançar";
$l_chm_yourdeflectormalf3 = "por cento dos defletores de sua mina.";
$l_chm_enemytorpfailshields = "não tem qualquer torpedos lançados contra os escudos.";
$l_chm_enemytorpfailarmor = "não foi lançado qualquer torpedos contra sua armadura.";

$l_chm_minemalf1 = "Minas Enemy avariam.";
$l_chm_minemalf2 = "Somente";
$l_chm_minemalf3 = "por cento das minas encontradas atacando o navio.";

$l_chm_youhitsomemines = "Você bateu [chm_roll] minas de [total_mines] minas!";
$l_chm_yourdeflectormalf2a = "Você só tem sido capaz de lançar [deflectors] por cento dos defletores de sua mina.";
$l_chm_mines_destroyed = "[number] da [target] minas foram destruídas!";
$l_chm_mine_deflectors_left = "Você tem [number] defletores minha esquerda.";
$l_chm_mines_left = "Há [number] minas de esquerda e que estão impactando a sua armadura!";
$l_chm_minemalf2a = "Apenas [deflectors] por cento das minas encontradas atacando o navio.";
$l_chm_mines_exhausted = "[player] minas esgotadas!";
$l_chm_armor_left = "Você tem [number] pontos de armadura esquerda!";

?>
