<?php
$l_novabomb_turns = "The Bomb Nova requer pelo menos [turns] se transforma em fogo.";
$l_novabomb_planetsdamaged = "Planetas danificadas pelo Bomb Nova";
$l_novabomb_planet = "Planet [name] sofreram danos da bomba Nova.";
$l_novabomb_novaexplode = "Nova bomba explodiu em que foi demitido e seu navio sofreu graves danos.";
$l_novabomb_novaexplode2 = "Nova bomba explodiu em que foi demitido e sua nave foi destruída.";
$l_novabomb_notfedsec = "Nova bomba não pode ser usado na Federação propriedade setores.";
$l_novabomb_destroyed_planet = "A sua bomba nova rachado na superfície do planeta e perfurados para o núcleo, onde explodiu causando a abalar o planeta.";
$l_novabomb_wrongclass = "Esta classe de navio não pode disparar um dispositivo Nova Bomb.";
$l_novabomb_nonova = "Você não tem a Bomb Nova instalado.";
$l_novabomb_novamiss = "The Bomb Nova perde por pouco, mas inflige danos sobre o planeta.";
$l_novabomb_success = "Sector [sector] foi bombardeada Nova!";
$l_novabomb_mines = "Destroyed [mines] sector Minas.";
$l_novabomb_fighters = "Destroyed [fighters] Fighters sector.";
$l_novabomb_shipsdamaged = "Navios danificados pela Bomb Nova";
$l_novabomb_ship_damage = "Starship [shipname] sofreram danos da bomba Nova.";
$l_novabomb_ship_survived = "Seu navio estava suficientemente longe quando a bomba explodiu Nova para evitar qualquer dano.";
?>
