<?php
$l_zi_title = "Zona de Informação";
$l_zi_nexist = "Esta seção do espaço não existe!";
$l_zi_feds = "Federação";
$l_zi_traders = "Aliança Space";
$l_zi_nobody = "Ninguém";
$l_zi_war = "Espaço disputado";
$l_zi_allow = "Permitido";
$l_zi_notallow = "Não permitido";
$l_zi_limit = "Limited proprietário e aliados";
$l_zi_ul = "Unlimited";
$l_zi_control = "Você está no controle dessa zona";
$l_zi_tochange = "para mudar suas leis.";
$l_zi_owner = "Proprietário Zone";
$l_zi_maxhull = "Máximo de nível médio técnico autorizado";
?>
