<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Você precisa de pelo menos uma vez para fazer a varredura de um outro navio.";
$l_scan_ron = "Verificar resultados de";
$l_scan_capt = "Capitaneada por:";
$l_scan_arma = "Armamento:";
$l_scan_carry = "Realização:";
$l_scan_bounty = "Este navio tem uma recompensa total é de [amount] créditos.";
$l_scan_fedbounty = "Este navio tem uma recompensa por ele em A Federação.";
$l_by_nofedbounty = "Atacando este jogador <B>não</b> irá resultar em A Federação da colocação de uma recompensa em si.";
?>
