<?php
$l_new_pwis = "Sua senha é";
$l_new_charis = "Seu nome é personagem";
$l_new_title2 = "Criar Nova Fase Player Two";
$l_new_blank = "E-mail, nome do navio, eo nome do personagem não pode estar em branco.";
$l_new_inuse = "E-mail [username] já está em uso.";
$l_new_forgotpw = "Esqueceu sua senha?";
$l_new_inusechar = "O nome do personagem [character], já está em uso.";
$l_new_similar_inusechar = "Seu nome de personagem soa muito semelhante a [character], um nome já em uso.";
$l_new_inuseship = "Ship [shipname], já está em uso.";
$l_new_similar_inuseship = "Seu nome do navio parece muito semelhante ao [shipname], um nome já em uso.";
$l_new_pwsent = "A senha foi enviada para [username].";
$l_new_err = "Por favor, tente novamente";
$l_new_topic = "Alien Assault Traders Senha";
$l_new_message = "$ Ip cumprimentos, \ n \ nSomeone a partir do endereço IP solicitado que a senha para os comerciantes serão enviadas para você. \ N password \ nSeus é: [pass] \ n \ nObrigado \ n \ nA equipe web Traders.";
$l_new_invalidemail = "Endereço de Email inválido.";
$l_new_tutorial = "Clique aqui para ler o Mini-Tutorial antes de se logar em The Game.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "para ir para a tela de login.";

?>
