<?php
$l_ship2_buytitle = "A compra de um novo navio";
$l_ship2_storetitle = "Estaleiro Storage Facility";
$l_ship2_wrongclass = "Navio da classe especificada errada";
$l_ship2_buying = "Você está comprando:";
$l_ship2_tradein = "Trade In:";
$l_ship2_value = "Current Ship Valor:";
$l_ship2_newvalue = "New Ship Valor:";
$l_ship2_totalcost = "Custo Total:";
$l_ship2_nomoney = "Você não tem créditos suficientes para comprar este navio.";
$l_ship2_purchase = "Adquirir";
$l_ship2_buynstore = "Comprar navio novo e uma velha loja";
$l_ship2_nomoney2 = "Você não tem créditos suficientes para completar esta transação.";
$l_ship2_paystorage = "Seu ter removido o seu navio de armazenamento.";
$l_ship2_turns = "Você precisa de pelo menos [turns] volta-se para realizar esta ação";
$l_ship2_error = "Erro interno. Não é possível encontrar a classe do navio.";
$l_ship2_owned = "Você já possui este modelo de navio.";
$l_ship2_shipbought = "Você acabou de comprar um novo navio!";

?>
