<?php
$l_warp_cantsame = "Você não pode criar um link quando a fonte é o mesmo que o destino.";
$l_warp_twoerror = "Usando um editor de Warp para criar uma ligação nos dois sentidos para o setor [target_sector] não é permitida.";
$l_warp_sectex = "Não é possível criar um link urdidura do setor atual - que exceder o valor máximo de US $ link_max por setor.";
$l_warp_linked = "Alvo sector (target_sector [target_sector]) já tem uma ligação deste sector.";
$l_warp_coneway = "Link criado um caminho para";
$l_warp_ctwoway = "Criar link para e";
$l_warp_nomoney = "Você não tem créditos suficientes para criar a ligação da urdidura.";
$l_warp_noenergy = "Você não tem energia suficiente para criar a ligação da urdidura.";
?>
