<?php
$l_readm_title = "Ler Mensagem";
$l_readm_delete = "MENSAGEM DELETED";
$l_readm_nomessage = "Você não tem mensagens esperando por você ...";
$l_readm_center = "Mensagem Receber Center";
$l_readm_sender = "Message Sender";
$l_readm_captn = "Capitão do";
$l_readm_del = "Excluir";
$l_readm_repl = "Responder";
$l_readm_return = "Clique aqui para voltar ao menu principal";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Delete All";
$l_readm_subject = "Assunto";
$l_readm_quote = "Citar";
$l_readm_block = "Bloquear Remetente";
$l_readm_alert = "Sistema de Alerta";
$l_readm_alertbody = "Navio Computador";
?>
