<?php
$l_contact_admin_title = "Fale Game Administrator";
$l_contact_admin_thanks = "Obrigado pelo seu comentário.";
$l_contact_admin_email_alert = "Digite um endereço de e-mail válido.";
$l_contact_admin_name_alert = "Por favor, indique o seu nome.";
$l_contact_admin_comment_alert = "Entre seus comentários.";
$l_contact_admin_name = "Nome";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Pergunta / Comentário";
$l_contact_admin_submit = "Submeter Perguntas / Comentários";
$l_contact_admin_close = "Fechar Janela";
$l_contact_admin_thanks_comment = "Obrigado pelo seu comentário ou pergunta. Iremos colocar questões e-mail com a nossa resposta.";

?>
