<?php
$l_opt2_title = "Salvar opções";
$l_opt2_passunchanged = "Senha permaneceu inalterado. <BR><BR>";
$l_opt2_srcpassfalse = "Original senha incorreta. Senha permaneceu inalterado. <BR><BR>";
$l_opt2_newpassnomatch = "Novos campos de senha não correspondem. Senha permaneceu inalterado. <BR><BR>";
$l_opt2_passchanged = "Senha alterada. <BR><BR>";
$l_opt2_passchangeerr = "Erro alterando senha <BR><BR>";
$l_opt2_userintup = "Interface de usuário configuração atualizada. <BR><BR>";
$l_opt2_userintfail = "Falha ao atualizar configuração de interface de usuário. <BR><BR>";
$l_opt2_chlang = "A linguagem tem sido definido como lang [lang]. <p>";
$l_opt2_chtemplate = "Modelo tem sido definido como [template]. <p>";
$l_opt2_dhtmlup = "Html dinâmico configuração atualizada. <BR><BR>";
$l_opt2_dhtmlfail = "Falha ao atualizar configuração html dinâmico. <BR><BR>";
$l_opt2_shipnamechanged = "ShipName alterado para [name]. <BR><BR>";
$l_opt2_playernamechanged = "Nome do Jogador alterado para [name] e [amount] créditos debitado de sua conta do navio. <BR><BR>";
$l_opt2_mapwidth = "Local e Galaxy Mapa Largura:";
?>
