<?php
$l_autotrade_title = "Auto traderoute Menu";
$l_autotrade_dismiss2 = "Auto Traderoutes Excluídos.";
$l_autotrade_report = "Auto traderoute Report";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energia";
$l_autotrade_capacity = "Capacidade";
$l_autotrade_goods = "Bens de preço";
$l_autotrade_ore = "Preço do Minério";
$l_autotrade_organics = "Organics Preço";
$l_autotrade_energy = "Preço da Energia";
$l_autotrade_colonist = "Preço Colono";
$l_autotrade_credits = "Créditos Comerciais";
$l_autotrade_delete = "Excluir <br> Rota";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "Sem rota";
$l_autotrade_sector = "Setor";
$l_autotrade_credit2 = "créditos";
$l_autotrade_deletebutton = "Excluir";
$l_autotrade_noroute2 = "Você não configurar qualquer Traderoutes Auto.";
?>
