<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Sonda Níveis";
$l_probe_engine = "Motor";
$l_probe_sensors = "Sensores";
$l_probe_cloak = "Capa";
$l_probe_title = "Space Probe Menu";
$l_probe_none = "Você não está no mesmo sector que a esta sonda, para que você não pode interagir com ele.";

$l_probe_named = "Welcome to Probe Número probename [probename], propriedade de [name], localizado no setor [sector].";
$l_probe_orders = "[orders] Probe à pesquisa do universo";
$l_probe_orders_link = "Programa";
$l_probe_upgrade = "[upgrade] Probe Sensores / Motor / Cloak";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] Sonda para posterior colocação";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Atualizar";

$l_probe_att_link = "Ataque";
$l_probe_att = "[attack] a sonda";
$l_probe_att_sure = "Tem certeza que ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] sonda";

$l_probe_unknown = "Desconhecido";
$l_plant_scn_turn = "Você precisa de pelo menos uma vez para fazer a varredura de uma sonda.";
$l_probe_noscan = "Sensores não pode obter uma correção no alvo!";
$l_probe_logscanA = "[name] tentou digitalizar uma de suas sondas no sector [sector], mas não conseguiu.";
$l_probe_logscanB = "Uma de suas sondas no sector sector [sector] foi digitalizada por [name].";
$l_probe_scn_report = "Os resultados do scan em [name], owned by: [owner]";

$l_probe_caplog = "Seu sonda &#39;[probename]&#39; no sector [sector] foi capturado por [name].";
$l_probe_scan = "Sonda varreduras sector [sector] e encontra-se:";
$l_probe_destroyprobe = "Sonda Destroy";
$l_probe_destroyed = "Sonda Destroyed!";
$l_probe_warning = "Fazendo isso irá destruir totalmente esse tipo de sonda";
$l_probe_confirm = "Você realmente quer destruir esta sonda?";
$l_gns_turn = "Você não tem o suficiente para destruir transforma esse tipo de sonda";
$l_probe_type = "Tipo de Sonda";
$l_probe_type0 = "Sonda";
$l_probe_type1 = "Sentry Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sequential Realspace Probe";
$l_probe_target = "Meta do Setor";
$l_probe_ordered = "Sonda programado e vai começar a pesquisa.";
$l_probe_order2 = "Probe é um tipo de [type] e tem como meta sector [target]";
$l_probe_pickedup = "Sonda apanhados e colocados em armazenagem ativos";
$l_probe_title = "Sonda Menu";
$l_probe_messages = "para ver o que seus espiões detectaram.";

$l_probe_defaulttitle1 = "Active Probes";
$l_probe_defaulttitle2 = "Sondas você pegou";
$l_probe_defaulttitle3 = "Sondas de seus planetas";
$l_probe_defaulttitle4 = "Sondas em seu navio";
$l_probe_linkback = "para ir para o menu de sonda.";
$l_probe_no1 = "Você não tem quaisquer testes ativos.";
$l_probe_no2 = "Você não tem quaisquer testes na armazenagem.";
$l_probe_no3 = "Você não tem quaisquer testes em seus planetas.";
$l_probe_no4 = "Você não tem quaisquer testes em seu navio.";
$l_probe_noprobeatall = "Você não tem quaisquer testes.";
$l_probe_notknown = "Desconhecido";
$l_probe_launch = "Gota";
$l_probe_detect = "Detectado";
$l_probe_codenumber = "Código";
$l_probe_job = "Trabalho";
$l_probe_percent = "Percentual";
$l_probe_move = "Movimento";
$l_probe_view = "Visualizar";
$l_probe_action = "Ação";
$l_probe_shipowner = "Armador";
$l_probe_shipname = "Nome do Navio";
$l_probe_shiptype = "Navios da classe";
$l_probe_shiplocation = "Navio Localização";
$l_probe_planetowner = "Planet Proprietário";
$l_probe_planetname = "Planet";
$l_probe_sector = "Atual do Setor";
$l_probe_tsector = "Meta do Setor";
$l_probe_type = "Tipo de Sonda";
$l_probe_forbid = "Você não pode descartar as sondas neste sector";

$l_probe2_title = "Launch Space Probe";
$l_probe2_turn = "Você precisa de pelo menos uma vez de usar uma sonda espacial.";
$l_probe2_onplanet = "Você não pode usar este dispositivo, enquanto na superfície do planeta.";
$l_probe2_noprobe = "Você não possui sondas espaciais.";
$l_probe2_forbid = "O lançamento de uma sonda neste setor não é permitido.";
$l_probe2_launched = "A sonda espacial lançada!";

$l_probe2_warplink = "WarpLink";
$l_probe2_player = "Jogador";
$l_probe2_onboarda = "a bordo de um";
$l_probe2_classship = "navio da classe";
$l_probe2_traveled = "viajou para o setor";
$l_probe2_fedjammed = "Federação está emperrando varreduras para todos os sensores do Setor 1.";
$l_probe2_lastseen = "Navio Última atividade";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Suporta";
$l_probe2_planets = "planetas";
$l_probe2_sectord = "Defesa do Sector Detectado";
$l_probe2_mines = "Minas";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Navios Detectado";
$l_probe2_ships2 = "Navio Detectado";
$l_probe2_noneowned = "No planetas não pertence a você têm sido detectadas.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Nada Detectado";
$l_probe2_nocredits = "Você não tem créditos suficientes para essa operação. O custo total é [total] de créditos e você só tem [credits] créditos.";

$l_probe_forbidSG = "Você não pode enviar uma sonda tipo Realspace no Setor de Gênesis criado setores.";
$l_probe_forbidFED = "Você não pode enviar uma sonda tipo Realspace na Federação ou Aliança sectores de propriedade.";
$l_probe_forbidINVALID = "Seu setor de destino é um nome de setor inválido.";
?>
