<?php
$l_s_yes = "Sim";
$l_s_no = "Não";
$l_s_enabled = "Habilitado";
$l_s_disabled = "Deficientes";

$l_s_modules = "Módulos";
$l_s_modulename = "Nome do Módulo";
$l_s_moduleauthor = "Autor";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "No Loaded Modules";

$l_s_gamestatus = "Estado do Jogo";
$l_s_allowpl = "Permitir Jogadores";
$l_s_allownewpl = "Permitir Novos Jogadores";

$l_s_gameoptions = "Opções do Jogo";
$l_s_allowteamplcreds = "Permitir Equipe Planet Credit Transfer";
$l_s_allowfullscan = "Allow Full Long Range Scan";
$l_s_sofa = "Permitir Ataques de Sub-Orbital Fighter";
$l_s_showpassword = "Display senha no Registro";
$l_s_genesisdestroy = "Torps Genesis pode destruir planetas";
$l_s_igb = "Intergalactic Bank (IGB)";
$l_s_ksm = "Conhecido Space Maps";
$l_s_navcomp = "Navegação Computador";
$l_s_newbienice = "Novato Nice";
$l_s_spies = "Spy System";
$l_s_spycapture = "Permitir espiões para capturar os planetas";

$l_s_gamesettings = "Definições de jogo";
$l_s_gameversion = "Versão do jogo:";
$l_s_minhullmines = "Tamanho mínimo necessário para bater casco minas";
$l_s_averagetechewd = "Ao nível Tech Média de Emergência Warp Degrada";
$l_s_numsectors = "Número de Setores";
$l_s_maxwarpspersector = "Máximo de Ligações por sector";
$l_s_averagetechfed = "Máximo de nível médio para técnico da Federação Setores";
$l_s_igbirateperupdate = "Taxa de juro igb por atualização";
$l_s_igblrateperupdate = "Empréstimo taxa igb por atualização";
$l_s_techupgradebase = "Tech upgrade de Nível de Bases";
$l_s_collimit = "Colonos Limit";
$l_s_maxturns = "O número máximo de voltas acumulado";
$l_s_maxplanetssector = "Máximo número de planetas por sector";
$l_s_maxtraderoutes = "Número máximo de traderoutes por jogador";
$l_s_colreprodrate = "Colono Taxa de natalidade";
$l_s_energyperfighter = "Unidade de energia utilizada por setor de caça";
$l_s_secfighterdegrade = "Lutador Setor taxa de degradação";
$l_s_planetinterest = "Planet taxa de juros";
$l_s_spiesperplanet = "Número máximo de espiões por planeta";
$l_s_spysuccessfactor = "Spy fator de sucesso";
$l_s_spykillfactor = "Espião matar fator";
$l_s_colsperfighter = "Colonos necessários para produzir 1 Fighter cada turno";
$l_s_colspertorp = "Colonos necessários para produzir 1 Torpedo cada turno";
$l_s_colsperore = "Colonos necessários para produzir 1 Minério de cada turno";
$l_s_colsperorganics = "Colonos necessários para produzir 1 Organics cada turno";
$l_s_colspergoods = "Colonos necessários para produzir 1 Mercadorias cada turno";
$l_s_colsperenergy = "Colonos necessários para produzir 1 Energy cada turno";
$l_s_colspercreds = "Colonos necessários para produzir 1 Créditos de cada turno";
$l_s_colsper = "Colonos necessários para produzir 1 [commodity], cada vez";

$l_s_gameschedsettings = "Game Scheduler Settings";
$l_s_schedtype = "Programador Tipo";
$l_s_cronbased = "Cron Based";
$l_s_playertriggered = "Jogador Provocado";
$l_s_minutes = "minutos";
$l_s_ticksupdate = "Carrapatos acontecem todos os";
$l_s_turnsupdate = "Acontece que vai acontecer a cada";
$l_s_npcupdate = "A Aliança irá tocar todos os";
$l_s_igbturnsupdate = "Juros sobre contas igb serão acumulados a cada";
$l_s_newsupdate = "Notícias serão gerados todos os";
$l_s_planetupdate = "Planetas geram uma produção cada";
$l_s_spyupdate = "Spies agirá cada";
$l_s_portsupdate = "Portas vai regenerar a cada";
$l_s_towupdate = "Os navios terão de ser rebocado alimentados todos os setores";
$l_s_scoreupdate = "Ranking será gerado a cada";
$l_s_secdefdegrupdate = "Defesas Setor vai degradar cada";
$l_s_apocalypseupdate = "O apocalipse planetário ocorrerá a cada";
$l_s_release_version = "Jogo versão";
$l_s_time_since_reset = "Tempo desde a última reinicialização";
$l_s_independence = "Planetário da Independência";
$l_s_dignitaryupdate = "Dignitários agirá cada";

$l_s_turnsupdate = "transforma cada";
?>
