<?php
$l_die_title = "Self-Destruct";
$l_die_rusure = "Tem certeza de que querem destruir sua nave? Isto irá retirá-lo de The Game.";
$l_die_goodbye = "Goodbye galáxia cruel!";
$l_die_check = "Tem certeza que pretende remover-se de The Game?";
$l_die_nonono = "NÃO! NÃO! NÃO!";
$l_die_what = "O que eu estava pensando?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Você e todos a bordo do navio foram vaporizados.";
$l_die_please1 = "logout";
$l_die_please2 = "Por favor, logout_link [logout_link]";
$l_die_exploit = "Não brinque com o que você não entende.";
?>
