<?php
$l_sf_attacking = "Caças de defesa do sector estão a atacar você! <BR>";
$l_sf_destfight = "Seu vigas destruídos [lost] combatentes <BR>";
$l_sf_destfightb = "Seu vigas destruídos [lost] combatentes <BR>";
$l_sf_torphit = "Torpedos hit:";
$l_sf_destfightt = "Seu torpedos destruídos [lost] combatentes <BR>";
$l_sf_fighthit = "Fighters Ataque:";
$l_sf_destfightall = "Você destruiu todos os lutadores. <BR>";
$l_sf_destfightt2 = "Você destruiu [lost] combatentes. <BR>";
$l_sf_lostfight = "Você perdeu todos os lutadores. <BR>";
$l_sf_lostfight2 = "Você perdeu [lost] combatentes. <BR>";
$l_sf_armorbreach = "Sua armadura é quebrado! <BR>";
$l_sf_armorbreach2 = "Sua armadura é atingido por [lost] de dano. <BR>";
$l_sf_sendlog = "[player] destruídos [lost] caças de defesa do sector no sector [sector].";
$l_sf_lreport = "Você perdeu [armor] pontos de armadura, [fighters] lutadores, e utilizado [torps] torpedos. <BR><BR>";
$l_sf_shipdestroyed = "Seu navio foi destruído! <BR><BR>";
$l_sf_sendlog2 = "Caças de defesa do Sector destruídos [player] no sector [sector].";
$l_sf_escape = "Felizmente, você tem um escape pod! <BR><BR>";

$l_sf_fnoattack = "não está enviando nenhum combatentes para atacar seus combatentes.";
$l_sf_fnoattackt = "não está enviando nenhum combatentes para atacar seus torpedos.";
$l_sf_fnoattacka = "não está enviando nenhum combatentes para atacar a sua armadura.";
$l_sf_flaunchmalf1 = "Seu lutador sistema de lançamento não está funcionando corretamente.";
$l_sf_flaunchmalf2 = "Você só tem sido capaz de lançar";
$l_sf_flaunchmalf3 = "por cento de seus combatentes.";
$l_sf_fightertorpexg = "Fighter Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Ship Torpedo para o Sector Fighter Exchange";
$l_sf_fighterarmorexg = "Setor Fighter Ship Armor Exchange";
$l_sf_tlaunchmalf1 = "Seu sistema de lançamento de torpedo funcionou mal.";
$l_sf_tlaunchmalf2 = "Você só tem sido capaz de lançar";
$l_sf_tlaunchmalf3 = "por cento de seus torpedos.";
$l_sf_bountysd = "Você atacou um sector que contém um planeta que lhe daria uma recompensa se você atacou o planeta. A Federação tem activado um auto-destruição automática de todos os seus combatentes e torpedos. Não ataque as defesas do setor neste sector novamente. Você foi avisado!";
?>
