<?php
$l_news_title = "Universe News";
$l_news_info = "FNN é um dos líderes da galáxia <br> em notícias e prestação de informações. <br> Funciona 24 horas, sete dias por semana por um <br> dedicados funcionários na sede da galáxia FNN&#39;s <br> em Proxima Centauri e galaxywide departamentos!";
$l_news_for = "Notícias de";
$l_news_prev = "dia anterior";
$l_news_next = "dia seguinte";
$l_news_none = "Desculpe, não houve notícias de hoje.";
$l_news_flash = "Flash de Notícias";
$l_news_end = "Fim de notícias";
$l_news_bestviewed = "Melhor visualizado no Opera, Safari e IE";
$l_news_fedannouncements = "Federação Anúncios";
$l_news_planetarynews = "Planetário Notícias";
$l_news_planetshipnews = "Planetário e Entrega Notícias";
$l_news_afteractionnews = "Depois de Acção de Combate News";
?>
