<?php
$l_login_title = "Fazer logon";
$l_login_pw = "Senha:";
$l_login_chooseres = "Não foi possível determinar a resolução da tela. Por favor, escolha o mais adequado:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problemas?";
$l_login_emailus = "E-mail";
$l_login_forgot_pw = "Esqueceu sua senha? Digite o login em branco e pressione.";
$l_login_settings = "Definições de jogo";
$l_login_change = "Alterar";
$l_login_title2 = "Entrar para o Main AATraders";
$l_login_reset1 = "Não Agendada Reset";
$l_login_reset2 = "Reset agendadas:";
$l_login_reset3 = "Sched Reset:";
$l_login_notice = "Aviso Importante:";
$l_login_endadminnews = "Fim da Admin News";
$l_login_tourney_signup = "Torneio de Cadastros Habilitado";

$l_login_profile_only = "Apenas perfil";
$l_login_newclosed_message = "Novos Cadastros Fechado";
$l_login_tourneymode = "Running Torneio";
$l_login_tourneystarts = "Começa:";
?>
