<?php
$l_att_title = "Attack Ship";
$l_att_notarg = "Meta não neste sector.";
$l_att_noturn = "Você precisa de pelo menos uma vez ao ataque.";
$l_att_noatt = "Atacar alguém neste setor não é permitido.";
$l_att_flee = "Alvo fora manobrado você!";
$l_att_ewd = "Alvo acoplado um dispositivo de emergência, quando a urdidura atacado!";
$l_att_att = "Atacando";
$l_att_beams = "Boca Exchange";
$l_att_torps = "Torpedo Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost = "perdido";
$l_att_ylost = "Você perdeu";
$l_att_sdown = "&#39;s escudos estão no chão!";
$l_att_ydown = "Seu escudos estão no chão!";
$l_att_shits = "&#39;s escudos são para bater";
$l_att_yhits = "Seu escudos são para bater";
$l_att_dmg = "danos";
$l_att_sarm = "&#39;s armadura violado!";
$l_att_yarm = "Sua armadura foi violado!";
$l_att_ashit = "&#39;s armadura é atingida por";
$l_att_ayhit = "Sua armadura é para bater";

$l_att_efhit = "&#39;s lutadores são destruídos.";
$l_att_yfhit = "de seus lutadores sejam destruídas.";
$l_att_ethit = "&#39;s torpedos são destruídos.";
$l_att_ythit = "de seus torpedos são destruídos.";
$l_att_of = "de";
$l_att_lostt = "perdeu todos torpedos.";
$l_att_ylostt = "Você já perdeu todo torpedos.";

$l_att_lostf = "perdeu todos os lutadores.";
$l_att_ylostf = "Você perdeu todos os lutadores.";
$l_att_sdest = "&#39;s navio foi destruído.";
$l_att_espod = "Um módulo de emergência foi lançada!";
$l_att_ysalv = "Você salvou [ship_salvage_rate]% do navio para [ship_salvage] créditos. <BR> Sua classificação alterada por pontos [rating_change].";
$l_att_andused = "e usados";
$l_att_stilship = "Você não destory [name] &#39;s navio.";
$l_att_atyou = "te atacou";
$l_att_and = "e";
$l_att_yshiplost = "Seu navio foi destruído!";
$l_att_salv = "[name] salvado [ship_salvage_rate]% do navio para [ship_salvage] Créditos";
$l_att_loosepod = "Felizmente, você tem um escape pod!";

$l_att_tnobeams = "costuras para estar fora da energia do feixe.";
$l_att_tnobeamsf = "costuras para estar fora da energia do feixe e não pode atacar seus combatentes.";
$l_att_tnobeamst = "costuras para estar fora da energia do feixe e não pode atacar os seus torpedos.";
$l_att_tfnoattack = "não está enviando nenhum combatentes a atacar o seu navio.";
$l_att_tnotorps = "parece estar fora de torpedos.";

$l_att_anobeams = "Você tem esgotado a sua energia do feixe de navios.";
$l_att_anobeamsf = "Você tem esgotado a sua energia do feixe de navios e não podem atacar os combatentes inimigos.";
$l_att_anobeamst = "Você tem esgotado a sua energia do feixe de navios e não pode atacar o inimigo torpedos.";
$l_att_anofighters = "Seu navio tenha esgotado todos os lutadores availible.";
$l_att_anotorps = "Você ter esgotado o seu torpedos availible.";
$l_att_imtitle = "Ship Under Attack";
$l_att_imbody = "está a atacar o seu navio.";

$l_att_luckybeams = "Enemy vigas sobrecarga de infligir";
$l_att_luckyfighters = "Caças inimigos fazer uma surpresa e causar ataque relâmpago";
$l_att_luckytorps = "Enemy torpedos provocar um efeito cascata que causa danos";
$l_att_luckytimes = "vezes o dano normal!";
?>
