<?php
// New News Items

$l_news_planets = "planetas";
$l_news_cols = "Milhões de colonos";
$l_news_p_headline = "[player] &#39;s Empire tem agora [total] planetas";
$l_news_c_headline = "[player] &#39;s Empire tem agora [total] milhões de colonos";
$l_news_p_textXX = "A Federação emitiu um alerta sobre o império de [name]. [name] tem o controle de [total] planetas e deve ser considerado muito perigoso. Todos os setores deveriam aumentar as defesas do setor imediatamente.";
$l_news_c_textXX = "O Império do [name] é de sobrelotação maciça em todos os planetas, com mais de [total] milhões de colonos. A escassez de alimentos pode causar agitação. Todos os setores devem estar conscientes das possíveis ações agressivas por [name] no futuro.";

$l_created_universe = "&#39;Criação Universe&#39;";
$l_created_universe_full = "&quot;Os cientistas pesquisando as origens do Universo, por unanimidade, decidiu que hoje é o dia estatisticamente mais provável para a criação do universo ter tido lugar&quot;";

$l_news_p_text5 = "O império crescente do [name] tem agora cinco planetas, a FNN irá assistir as ações da [name] de forma mais estreita no futuro!";
$l_news_p_text10 = "O império crescente do [name] agora controla dez planetas, os Relatórios de FNN dizer que a expansão do [name] poderia conduzir a guerra!";
$l_news_p_text25 = "O imenso império de [name] 25 planetas já colonizados, em uma entrevista, [name] anunciou que ele pode considerar abrandar a sua expansão no futuro!";
$l_news_p_text50 = "O império enorme gama de [name], representado por 50 planetas na galáxia inteira está começando uma força ameaçadora. Um dos repórteres FNN descobriram que a [name] é atualizar seu barco planejando uma grande guerra. Em uma entrevista [name] anunciou que é feito na finalidade única defesa!";
$l_news_c_text25 = "O império crescente do [name] já tem 25 milhões de colonos, o FNN irá assistir as ações da [name] mais de perto, no futuro, mas sua alta taxa de natalidade é óbvio que vai explodir!";
$l_news_c_text100 = "O império de aspiração de [name] tem agora 100 milhões de colonos, depois de uma explosão das taxas de natalidade, [name] parece ser um bom lugar para as famílias a resolver!";
$l_news_c_text500 = "O vasto império de [name] tem agora 500 milhões de colonos, [name] disse em uma entrevista que a colonização da galáxia acaba de ainda não começou";
$l_news_c_text1000 = "O império humongous de [name] tem agora um bilião colonos, FNN repórteres descobriram que a [name] está na posse de algum mecanismo de clonagem estranho que lhe permita produzir novos colonos em grandes quantidades. Com essa quantidade de colonos, a força ECONOMICOS deste império é enorme, FNN esperanças que o [name] não gasta o seu dinheiro em guerra";

$l_news_indi_short = "FNN Rumor: over [planets] declarar a independência.";
$l_news_indi = "FNN tem autoridade para dizer que mais de [planets] planetas já decidiu que eles são melhores governado por si mesmos e se tornarem independentes.";

$l_news_nova_short = "FNN Relatório: [name] utiliza Nova Bomb.";
$l_news_nova = "FNN tem notícias de que [name] usou o temido Nova Bomb [total] time (s) para destruir um planeta e todos os navios nele.";
$l_news_nova_m_short = "FNN Relatório: [name] utiliza Nova Bomb e erra.";
$l_news_nova_m = "FNN tem notícias de que [name] usou o temido Nova Bomb [total] time (s) para tentar destruir um planeta. A Nova bomba explodiu fora da atmosfera de planetas e causou grandes danos à infra-estrutura planetária.";

$l_news_bounty = "FNN Relatório: [name] coloca uma quantidade [amount] generosidade de crédito [name2].";

$l_news_attackerpod_p_short = "FNN Relatório: [name] &#39;s do navio é destruído.";
$l_news_attackerpod_P = "[name] &#39;s navio foi destruído ao atacar um planeta. Felizmente [name] teve um Escape Pod e sobreviveu.";

$l_news_attackerdie_p_short = "FNN Relatório: [name], morre!";
$l_news_attackerdie_p = "[name] &#39;s navio foi destruído ao atacar um planeta e que eles foram mortos porque eles não conseguiram comprar um Pod Escape.";

$l_news_destroyed_p_short = "FNN Relatório: [name] ataca e destrói o planeta!";
$l_news_destroyed_p = "[name] atacou [total] planeta (s) de propriedade do [owner] e da população de cada planeta foi destruído o planeta para impedi-lo de ser capturado!";

$l_news_defeated_p_short = "FNN Relatório: [name] ataca e derrota o planeta!";
$l_news_defeated_p = "[name] atacou [total] planeta (s) detidas pela [owner] e derrotou as forças de defesa planetária!";

$l_news_notdefeated_p_short = "FNN Relatório: [name] ataca um planeta e perde!";
$l_news_notdefeated_p = "[name] atacou [total] planeta (s) detidas pela [owner] e as defesas planetárias realizada contra os ataques implacáveis!";

$l_news_targetepod_short = "FNN Relatório: [name] ataca um proprietário [owner] e ganha!";
$l_news_targetepod = "[name] atacou [owner] &#39;s do navio e destruíram completamente. Felizmente [owner] teve seu navio equipado com um Escape Pod e eles sobreviveram.";

$l_news_targetdies_short = "FNN Relatório: [name] ataca um proprietário [owner] e mata-los!";
$l_news_targetdies = "[name] atacou [owner] &#39;s do navio e destruíram completamente. Infelizmente [owner], não tem seu navio equipado com um módulo de emergência e foram vaporizados.";

$l_news_fedcolbounty_short = "FNN Relatório: As rachaduras Federação baixo no [name]!";
$l_news_fedcolbounty = "A Federação tem hoje reprimiu o famoso pirata do espaço [name]! [name], que rotineiramente violados tratados espaço diversos, foi rapidamente contratado pela battlecruiser Federação, o que causava [amount] de créditos no valor de danos no navio do pirata. Funcionários da Federação promete novas acções no futuro!";

$l_news_alliancecolbounty_short = "FNN Relatório: As fissuras da Aliança para baixo no [name]!";
$l_news_alliancecolbounty = "A Aliança tem hoje reprimiu o famoso pirata do espaço [name]! [name], que rotineiramente violados tratados espaço diversos, foi rapidamente contratada pela Aliança, o que causava [amount] de créditos no valor de danos no navio do pirata. Aliança funcionários prometem mais ações desse tipo no futuro!";

$l_news_fedcol_pbounty_short = "FNN Report: A Federação acossa [name]!";
$l_news_fedcol_pbounty = "A Federação tem hoje reprimiu o famoso pirata do espaço [name]! [name], que rotineiramente violados tratados espaço diversos, foi rapidamente contratado pela Federação battlecruiser, que confiscou o planeta [planetname] [amount] créditos no sector [sector]. Funcionários da Federação promete novas acções no futuro!";

$l_news_alliancecol_pbounty_short = "FNN Report: A Aliança acossa [name]!";
$l_news_alliancecol_pbounty = "A Aliança tem hoje reprimiu o famoso pirata do espaço [name]! [name], que rotineiramente violados tratados espaço diversos, foi rapidamente contratado pela Aliança, que confiscou o planeta [planetname] [amount] créditos no sector [sector]. Aliança funcionários prometem mais ações desse tipo no futuro!";

$l_news_fedcol_sbounty_short = "FNN Report: A Federação acossa [name]!";
$l_news_fedcol_sbounty = "A Federação tem hoje reprimiu o famoso pirata do espaço [name]! [name], que rotineiramente violados tratados espaço diversos, foi brevemente contratados pelo cruzador de batalha da Federação, que confiscou um navio (tipo de navio [shiptype]) vale [cost] no sector [sector]. Funcionários da Federação promete novas acções no futuro!";

$l_news_alliancecol_sbounty_short = "FNN Report: A Aliança acossa [name]!";
$l_news_alliancecol_sbounty = "A Aliança tem hoje reprimiu o famoso pirata do espaço [name]! [name], que rotineiramente violados tratados espaço diversos, foi rapidamente contratado pela Aliança, que confiscou um navio [shiptype] [cost] no sector [sector]. Aliança funcionários prometem mais ações desse tipo no futuro!";

$l_killheadline = "[target] foi morto em um acidente";
$l_news_killed = "[target] foi morto em um trágico acidente de hoje. Como heróica - [target], foi o último membro a bordo do seu navio, quando ele percebeu que havia nenhum escape pod deixou para ele. Que ele descanse em paz!";

$l_killSDheadline = "[target] foi morto pelas defesas do Setor.";
$l_news_killedSD = "[target] foi morto por um número esmagador de Defesas Setor de propriedade de [killer]! Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killplanetheadline = "[target] foi morto a atacar um planeta.";
$l_news_killedplanet = "[target] foi morto ao atacar um planeta propriedade de [killer] hoje. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killshipheadline = "[target] foi morto combate navio.";
$l_news_killedship = "[target] foi morto em navio para navio de combate com [killer] hoje. O capitão aparentemente esqueceu de equipar o navio com uma cápsula de fuga.";

$l_killsuicideheadline = "[target] cometeu suicídio.";
$l_news_killedsuicide = "[target] suicidou hoje. Eles tomaram a forma como os covardes de fora porque não tinha a capacidade ou coragem para enfrentar as pressões de comandar sua própria nave.";

$l_killsofaheadline = "[target] foi morto sofá atacar um planeta.";
$l_news_killedsofa = "[target] foi morto enquanto sofá atacar um planeta propriedade de [killer] hoje. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killnovaheadline = "[target] foi morto durante um ataque de nova.";
$l_news_killednova = "[target] foi morto por [killer], durante um ataque a bomba nova hoje. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killnovabackfireheadline = "[target] foi morto em uma nova tiro pela culatra.";
$l_news_killednovabackfire = "[target] foi morto quando a bomba nova culatra hoje. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killsectormissileheadline = "[target] foi morto em um míssil Setor.";
$l_news_killedsectormissile = "[target] foi morto quando um míssil do Setor de [killer] impactado seus escudos. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killhunterprobeheadline = "[target] foi morto em uma sonda de Hunter.";
$l_news_killedhunterprobe = "[target], foi morto quando uma sonda de Hunter [killer] impactado seus escudos. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

$l_killtrapprobeheadline = "[target] foi morto em uma armadilha do Sentinela Sonda.";
$l_news_killedtrapprobe = "[target], foi morto quando uma sonda sentinela Armadilha de [killer] impactado seus escudos. Infelizmente, o barco não estava equipada com uma cápsula de fuga.";

//-------------------

$l_killpodheadline = "[target] &#39;s navio foi destruído em um acidente";
$l_news_killedpod = "[target] &#39;s navio foi destruído em um trágico acidente de hoje. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killSDpodheadline = "[target] &#39;s navio foi destruído pelos defesas do Setor.";
$l_news_killedSDpod = "[target] &#39;s navio foi destruído por um número esmagador de Defesas Setor de propriedade de [killer]! Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killplanetpodheadline = "[target] &#39;s navio foi destruído atacar um planeta.";
$l_news_killedplanetpod = "[target] &#39;s navio foi destruído ao atacar um planeta propriedade de [killer] hoje. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killshippodheadline = "[target] &#39;s navio foi destruído em combate do navio.";
$l_news_killedshippod = "[target] &#39;s navio foi destruído no navio para navio de combate com [killer] hoje. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killsofapodheadline = "[target] &#39;s navio foi destruído enquanto sofá atacar um planeta.";
$l_news_killedsofapod = "[target] &#39;s navio foi destruído enquanto sofá atacar um planeta, propriedade de [killer] hoje. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killnovapodheadline = "[target] &#39;s navio foi destruído durante um ataque de nova.";
$l_news_killednovapod = "[target] &#39;s navio foi destruído por [killer], durante um ataque a bomba nova hoje. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killnovabackfirepodheadline = "[target] &#39;s navio foi destruído de uma nova tiro pela culatra.";
$l_news_killednovabackfirepod = "[target] &#39;s navio foi destruído quando a bomba nova culatra hoje. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killsectormissilepodheadline = "[target] &#39;s navio foi destruído por um míssil do Setor.";
$l_news_killedsectormissilepod = "[target] &#39;s navio foi destruído quando um míssil do Setor de [killer] impactado seus escudos. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killhunterprobepodheadline = "[target] &#39;s navio foi destruído por um Teste de Hunter.";
$l_news_killedhunterprobepod = "[target] &#39;s navio foi destruído quando uma sonda de Hunter [killer] impactado seus escudos. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

$l_killtrapprobepodheadline = "[target] &#39;s navio foi destruído por uma armadilha Sentry Sonda.";
$l_news_killedtrapprobepod = "[target] &#39;s navio foi destruído quando um sentinela Probe Armadilha de [killer] impactado seus escudos. Um transponder Escape Pod foi detectado pela Federação de Busca e Salvamento.";

// --------------------------

$l_news_promotedheadline = "[name], foi promovido ao cargo de [rank]";
$l_news_promoted = "A Federação tem o prazer de anunciar a promoção de [name] para a classificação de [rank].";

$l_news_demotedheadline = "[name] foi rebaixada para a posição [rank]";
$l_news_demoted = "A Federação lamenta anunciar o rebaixamento de [name] para a classificação de [rank].";

$l_news_namechangedheadline = "[oldname] nome alterado para newname [newname]";
$l_news_namechanged = "[oldname] aplicada à Federação Review Board para mudar seu nome para [newname]. A Federação tem concedido a mudança de nome. Deste dia em diante [oldname] agora será conhecido como [newname]. Todos os navios e os planetas devem atualizar seus registros imediatamente.";

$l_news_found_planets_short = "Levantamento da Federação: [found_planets] novos planetas localizados.";
$l_news_found_planets = "Federação Inquérito Scouts ter localizado [found_planets] em sectores novos planetas descobertos recentemente.";

$l_news_new_ports_short = "Levantamento da Federação: [new_ports] novos portos construídos.";
$l_news_new_ports = "Federação engenheiros construíram [new_ports] novos portos em sectores recentemente descobertos.";

$l_news_addedsectors_short = "Levantamento da Federação: [addedsectors] setores descobertos.";
$l_news_addedsectors = "Federação Inquérito Scouts descobriram [addedsectors] novos sectores. Aconselha-se precaução.";

$l_news_artifactheadline = "[playername] [artifact]";
$l_news_artifact = "[playername], foi encontrado todas as peças do artefato [artifact] e tem todo o poder que ela pode proporcionar.";

$l_news_artifactfoundheadline = "[playername] found [artifact] piece";
$l_news_artifactfound = "[playername], foi encontrada uma das peças do artefato [artifact] e necessidades [pieces] mais [piece].";

?>
