<?php
$l_opt_title = "Opções";
$l_opt_chpass = "Alterar senha";
$l_opt_curpass = "Senha atual:";
$l_opt_newpass = "Nova senha:";
$l_opt_newpagain = "Nova senha (novamente):";
$l_opt_userint = "Interface de usuário";
$l_opt_usenew = "Use novo layout?";
$l_opt_lang = "Linguagem";
$l_opt_template = "Template";
$l_opt_select = "Select One:";
$l_opt_enabled = "Habilitado";
$l_opt_save = "Salvar";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "ShipName:";
$l_opt_mapwidth = "Local e Galaxy Mapa Largura:";
$l_opt_profiletitle = "Perfil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registrado com perfil de servidor";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Quando você registrar o seu leitor em outro servidor o modelo, shoutbox e configurações notícia acima serão usadas no servidor.";
$l_opt_showshoutbox = "Show Shoutbox:";
$l_opt_shownewscrawl = "Show do rastreamento de notícias:";
$l_opt_playername = "Nome do jogador:";
$l_opt_playernamecost = "Nome da Federação Fee: [amount] de créditos";
?>
