<?php
$l_defense_deploy_title = "Implantar o Setor de Minas e Fighters";
$l_defense_deploy_noturn = "Você precisa de pelo menos uma vez para implantar as defesas do setor.";
$l_defense_deploy_nopermit = "Implantando Minas e Fighters neste setor não é permitido.";
$l_defense_deploy_nodeploy = "Não é possível implantar aqui. Outro navio ou Team tem minas ou combatentes no setor.";
$l_defense_deploy_info1 = "Encontra-se actualmente no sector [sector]. Existem [mines] minas e [fighters] combatentes aqui.";
$l_defense_deploy_info2 = "Você tem [mines] minas e [fighters] combatentes disponíveis para implantar";
$l_defense_deploy_deploy = "Implantar";
$l_defense_deploy_deployed = "Implantadas";
$l_defense_deploy_att = "Ataque";
$l_defense_deploy_notorps = "Você não tem o suficiente torpedos.";
$l_defense_deploy_nofighters = "Você não tem bastante lutadores";
$l_defense_deploy_dmines = "Implantado [mines] minas.";
$l_defense_deploy_dfighter = "Implantado [fighters] combatentes.";
$l_defense_deploy_max_fighters = "Este setor pode suportar um máximo de [amount] combatentes.";
$l_defense_deploy_toomanyfighters = "Você já tentou implantar mais lutadores do que o setor pode suportar.";
?>
