<?php
// port.php port_purchase.php
$l_trade = "Comércio";
$l_title_port = "Port Trading";
$l_title_trade = "Commodities";
$l_sector_war = "Embargo de Guerra";
$l_war_info = "Guerra grassa no sector. Você não pode chegar ao porto, através de todas as forças hostis.";
$l_no_trade = "Comércio proibido";
$l_no_trade_out = "Negociação por essa porta não é permitido para os forasteiros";
$l_no_trade_info = "Negociação por essa porta não é permitido";
$l_buying = "Comprando";
$l_selling = "Vender";
$l_commodity = "Commodity";
$l_amount = "Valor";
$l_price = "Preço";
$l_buy = "Comprar";
$l_sell = "Vender";
$l_trade_st_info = "Você tem [free_holds] tem carga vazio, podem carregar [free_power] unidades mais energia, e têm [credits] créditos.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Port Device";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Créditos não suficiente";
$l_creds_to_spend = "Você tem [credits] créditos para gastar.";
$l_cost = "Custo";
$l_avail = "Disponível";
$l_profit = "Lucro";
$l_current = "Atual";
$l_current_level = "Nível Actual";
$l_current_qty = "Quantidades atual";
$l_max = "Max";
$l_ifyouneedmore = "Se precisar de mais você pode acessar igb este porto [igb]";
$l_ifyouneedplan = "Acesso do planeta";
$l_igb_term = "IGB Banking Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Unlimited";
$l_full = "Cheio";
$l_equipped = "Equipado";
$l_n_a = "n / a";
$l_item = "Item";
$l_totalcost = "Custo total";
$l_would_dump = "Se você gostaria de despejar todos os seus colonos aqui, clique";
$l_noport = "Não existe porta aqui!";
$l_trade_turnneed = "Você precisa de pelo menos uma vez ao comércio em um porto ou planeta.";
$l_returnto_port1 = "aqui";
$l_returnto_port2 = "Clique em [port_link] para voltar ao menu porta.";
$l_notenough_cargo = "Você não tem bastante carga livre é válido para os produtos que deseja comprar.";
$l_notenough_power = "Você não tem o suficiente de armazenamento de energia livre para a energia que você deseja comprar.";
$l_notenough_credits = "Você não tem créditos suficientes para completar a transação.";
$l_notenough_turns = "Você não tem o suficiente voltas para completar a transação.";
$l_trade_result = "Os resultados para este comércio";
$l_trade_complete = "Comércio concluída";
$l_trade_upgraded = "Promovido a nível";
$l_trade_added = "acrescentado";
$l_trade_installed = "instalado";
$l_port_bounty = "Você não pode acessar uma porta especial, quando tiver uma graça a você colocado pela Federação. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Você não tem Credtis suficiente para pagar o prêmio de [amount] créditos. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "O IGB emitiu um bloqueio em sua conta do navio devido a um empréstimo pagamento atrasado. Você não pode negociar um porto especial até você pagar seu empréstimo.";
$l_port_returntospecial = "para retornar ao depósito de suprimentos.";
$l_toprobemenu = "para ir para o menu de sonda.";
$l_ports_shiplimit = "Mínimo de classe de navios para a montagem do dispositivo:";
$l_ports_needrepair = "Reparação";

$l_ports_needcredits = "Você não tem créditos suficientes para essa operação. O custo total é";
$l_ports_needcredits1 = "créditos e você só tem";

$l_ports_tradeforbidden = "Comércio proibido";
$l_ports_nooutsiders = "Negociação por essa porta não é permitido para os forasteiros.";

$l_bought = "Você comprou";
$l_sold = "Você vendeu";
$l_notenough_commodity = "Você não tem o suficiente [commodity] para concluir a transação.";
$l_exceed_commodity = "Número de [commodity] excede a oferta / demanda.";
$l_port_shiptoolarge = "Seu navio é muito grande para o comércio neste porto.";

$l_port_hold_unit = "Mantém Unitário";


$l_port_welcome = "Porto [sectorname] Welcome do jogador [player]";
$l_port_amountforsale = "O porto tem [amount] de unidades de [commodity] para a venda [credits] créditos por unidade.";
$l_port_holdsperunit = "[holds] porões de carga requerida por unidade.";
$l_port_howmanypurchase = "Quantas unidades [commodity] gostaria de comprar?";
$l_port_unitstobuy = "Unidades Comprar";
$l_port_shipcarryingbuy = "Seu navio está levando [shipunits] unidades [commodity]. Você pode compra [buyunits] unidades com espaço disponível nos porões.";
$l_port_howmanysell = "[amount] de unidades de [commodity] @ [credits] créditos por unidade.";
$l_port_unitstosell = "Unidades de Venda";
$l_port_perform = "Realizar transações";
$l_port_cargoholds = "Porões de carga";

?>
