<?php
///SPIES
$l_dig_title = "Dignitário Menu";
$l_dig = "Dignitários";
$l_dig_disabled = "Dignitários estão desativados!";
$l_dig_noturn = "Você precisa de pelo menos uma vez para enviar um dignitário de um planeta.";
$l_dig_notonboard = "Você não tem qualquer dignitário a bordo.";
$l_dig_ownplanet = "Você não pode enviar um dignitário a um planeta inimigo.";
$l_dig_unownedplanet = "Você não pode enviar um dignitário ao planeta sem dono.";
$l_dig_planetfull = "Há já permitiu [max] dignitários naquele planeta.";
$l_dig_sendtitle = "O envio de um dignitário [digID] planeta para: <BR> Selecione missão dignitário:";

$l_dig_codenumber = "Código";
$l_dig_job = "Trabalho";
$l_dig_percent = "Percentual";
$l_dig_move = "Movimento";
$l_dig_action = "Ação";
$l_dig_shipowner = "Armador";
$l_dig_shipname = "Nome do Navio";
$l_dig_shiptype = "Navios da classe";
$l_dig_shiplocation = "Navio Localização";
$l_dig_planetowner = "Planet Proprietário";
$l_dig_planetname = "Planet";
$l_dig_sector = "Setor";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Máximo por planeta";
$l_dig_legend = "Dignitário Legend";
$l_dig_description = "Dignitário Descrição";
$l_dig_waiting_description = "Dignitário criará torpedos e lutadores enquanto aguarda uma indicação de trabalho.";
$l_dig_changeerror = "Dignitário Job Change Report";

$l_dig_nospieshere = "Você não tem qualquer dignitário neste planeta!";
$l_dig_transferred = "dignitários transferidos";
$l_dig_backonship = "O dignitário está agora no seu navio.";
$l_dig_dismiss = "Dispensar o dignitário?";
$l_dig_changebutton = "Alterar";
$l_dig_notyourplanet = "Não é o seu planeta.";

$l_dig_defaulttitle1 = "Dignitários sobre as naves inimigas";
$l_dig_defaulttitle2 = "Dignitários em seus planetas";
$l_dig_defaulttitle3 = "Dignitários em seus planetas";
$l_dig_defaulttitle4 = "Dignitários no seu navio";

$l_dig_no1 = "Você não tem qualquer dignitário em navios inimigos.";
$l_dig_no2 = "Você não tem qualquer dignitário em seus planetas.";
$l_dig_no3 = "Você não tem qualquer dignitário em seus planetas.";
$l_dig_no4 = "Você não tem qualquer dignitário em seu navio.";
$l_dig_nodignitaryatall = "Você não tem nenhum dignitários.";
$l_dig_notknown = "Desconhecido";
$l_dig_dismiss = "Ignorar";
$l_dig_dismiss2 = "Dignitários indeferido.";
$l_dig_menu = "Dignitário para retornar ao Menu.";

?>
