<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Espaço Unchartered";
$l_zname[2] = "Espaço da Federação";
$l_zname[3] = "Espaço da Aliança";
$l_zname[4] = "War Zone";

$l_nova = "Nova";
$l_nova = "Nova Bomb";
$l_lssd = "Última visita navio dispositivo";
$l_lss = "Navio pela última vez neste sector";

// Common to : warpedit 1-3.php

$l_warp_title = "Usar Warp Editor";
$l_warp_turn = "Você precisa de pelo menos uma vez de usar um editor de urdidura.";
$l_warp_none = "Você não tem todos os editores da urdidura.";
$l_warp_forbid = "Usando um editor de Warp neste setor não é permitido.";
$l_swarp_forbid = "Usando um editor de urdidura ou da SG setores não é permitido.";
$l_warp_nosector = "Sector não existe.";

// Not yet confirmed common to multiple files:

$l_yes = "Sim";
$l_no = "Não";
$l_here = "aqui";
$l_submit = "Enviar";
$l_reset = "Reset";
$l_all = "Todos";
$l_max = "Max";

$l_trade = "Comércio";
$l_ore = "Ore";
$l_commodity = "Commodity";
$l_commodities = "Commodities";
$l_organics = "Organics";
$l_goods = "Mercadorias";
$l_energy = "Energia";
$l_colonists = "Colonos";
$l_credits = "Créditos";
$l_units = "unidades de";
$l_special = "Especial";
$l_upgrade_ports = "Upgrades";
$l_device_ports = "Devices";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_dig = "Dignitários";
$l_spy = "Spies";

$l_cargo = "Cargo";
$l_fighters = "Fighters";
$l_mines = "Minas";
$l_torps = "Torpedos";

$l_none = "Nenhum";
$l_unnamed = "Unnamed";
$l_name = "Nome";
$l_unowned = "Unowned";
$l_unknown = "Desconhecido";
$l_clickme = "Clique aqui";
$l_player = "Jogador";
$l_ship = "Navio";
$l_ships = "Navios";
$l_set = "ajustar";
$l_realspace = "Realspace";
$l_armorpts = "Pontos Armor";
$l_links = "Links";
$l_login_email = "E-mail:";
$l_add = "Adicionar";
$l_teamforum = "Equipe do Fórum";
$l_teamships = "Equipe de Navios";
$l_tutorial = "Tutorial / Ajuda";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Debris";
$l_localmap = "Mapa Local";
$l_arm_weap = "Armadura &amp; Armas";
$l_3dmap = "3D Galaxy Mapa";

$l_sectormissile = "Setor de Mísseis";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Sondas";
$l_warpeditors = "Editores Warp";
$l_genesistorps = "Genesis Torpedos";
$l_sgtorps = "SG Torpedoes";
$l_minesfighters = "Minas / Fighters";
$l_ewarp = "Emergência Warp";
$l_reports = "Relatórios";
$l_shipinfo = "Navio Info";
$l_sectornotes = "Notas Sectoriais";
$l_maps = "Mapas";
$l_messages = "Mensagens";
$l_shiptype = "Tipo de Navio";
$l_help = "Ajuda";
$l_rank = "Rank";

$l_teamplanets = "Equipe Planets";
$l_teamdefenses = "Defesas da equipa";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Defesas Planet";
$l_changeproduction = "Variação de Produção";
$l_galacticarm = "Braço Galactic";

$l_armor = "Armor";
$l_news_none = "Desculpe, não houve notícias de hoje.";

$l_ranks_good = "Bom";
$l_ranks_evil = "Mal";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zona é agora uma zona de guerra!";
$l_global_nzone = "Zona é uma zona neutra.";
$l_global_team = "Zona agora pertence à equipa";
$l_global_player = "Zona pertence agora ao leitor";
$l_global_nochange = "Zona de propriedade não se alterou";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Aprendiz";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Suboficial";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Tenente";
$l_insignia_name[11] = "Tenente";
$l_insignia_name[12] = "Tenente Comandante";
$l_insignia_name[13] = "Comandante";
$l_insignia_name[14] = "Capitão";
$l_insignia_name[15] = "Contra-Almirante (metade inferior)";
$l_insignia_name[16] = "Contra-Almirante (metade superior)";
$l_insignia_name[17] = "Vice-Almirante";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Almirante da Frota";

$l_main_title = "Menu Principal";
$l_main_warpto = "Warp para";
$l_main_autoroute = "Autoroute para";
$l_main_rs_to = "RSMove para";
$l_main_other = "Outro";
$l_main_shipyard1 = "Estaleiro";
$l_main_shipyard2 = "Acesse o";
$l_traderoutes = "Rotas de Comércio";
$l_trade_control = "Controle Comercial";
$l_youhave = "Você tem";
$l_turns_used = "Acontece utilizados:";
$l_turns_have = "Acontece disponíveis:";
$l_score = "Placar:";
$l_sector = "Setor";
$l_help = "Ajuda";
$l_faq = "FAQ";
$l_feedback = "Resposta";
$l_forums = "Fóruns";
$l_logout = "Sair";
$l_commands = "Comandos";
$l_command_no = "Comando não disponível.";
$l_devices = "Devices";
$l_planets = "Planetas";
$l_log = "Entrar";
$l_sector_def = "Defesas do Setor";
$l_defense = "Defesas";
$l_read_msg = "Ler Mensagens";
$l_send_msg = "Enviar mensagens";
$l_rankings = "Rankings";
$l_teams = "Equipes";
$l_ohno = "Self-Destruct";
$l_options = "Opções";
$l_navcomp = "Nav Computador";
$l_incompletemove = "Você não completou sua jogada anterior.";
$l_clicktocontinue = "Clique aqui para continuar";
$l_toplanetmenu = "para ir para o menu do planeta.";
$l_nonexistant_pl = "Em um planeta não existente??";
$l_abord = ", A bordo do";
$l_messages_wait = "Mensagens esperando por você.";
$l_no_warplink = "Não há links warp";
$l_scan = "scan";
$l_fullscan = "Varredura completa";
$l_port = "Porto";
$l_tradingport = "Porta Trading";
$l_planet_in_sec = "Planetas no sector";
$l_ships_in_sec = "Outros navios no setor";
$l_sector_0 = "Há muito tráfego no Sol que não se pode isolar ainda outros navios!";
$l_map = "Mapa";
$l_probe = "Sondas";
$l_autotrade = "Autotrades";
$l_onboard = "a bordo de um";
$l_classship = "navio da classe";
$l_traveled = "viajou para o setor";
$l_max_planets = "Planetas máxima habital";
$l_block_msg = "Bloco Mensagens";
$l_sectorinfo = "Setor de Informação";
$l_add_note = "Adicionar nota";
$l_view_note = "Visualizar";
$l_notes = "Notas";
$l_global_limitreached = "Você atingiu o limite para a quantidade de tempo que estão autorizados a estar online todos os dias. Entrar novamente amanhã, depois da meia-noite.";
$l_onlinetimeleft = "Tempo Restante:";
$l_planetmax = "Planetário Máxima:";
$l_storedshipreport = "Navios Armazenados";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federação Porto de Informação";
$l_team_shoutbox = "Equipe Shoutbox";
$l_lobby = "Lobby Trader&#39;s";

$l_common_prev = "Página Anterior";
$l_common_next = "Próxima página";
$l_common_totalpages = "Total Páginas";
$l_common_selectpage = "Selecione página:";
$l_common_page = "Página:";
$l_templatechange = "Você gostaria de manter esse modelo?";

$l_im_fed_bounty = "A Federação tem colocado uma recompensa de você para atacar um jogador tão baixo classificados. A Federação irá atacar o seu navio em uma base regular até que você pague de volta a sua generosidade. Você pode pagar a sua graça, em qualquer porto de upgrade ou Spacedock.";
$l_im_fed_bounty_title = "Federação colocou uma graça em você!";
$l_im_alliance_bounty = "A Aliança tem colocado uma recompensa de você para atacar um jogador tão baixo classificados. A Aliança irá atacar o seu navio em uma base regular, até que você pague de volta a sua generosidade. Você pode pagar a sua graça, em qualquer porto de upgrade ou Spacedock.";
$l_im_alliance_bounty_title = "Aliança ofereceu uma recompensa por você!";
$l_instant_messages_waiting = "Você tem [count] mensagens esperando por você.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Mantém Recheados:";
$l_hold_space_free = "Mantém vazio:";
$l_port_buys = "Port Compra:";

?>
