<?php
$l_cu_storing = "Armazenando";
$l_cu_inistored = "<b>Todos os valores ini foram salvas com sucesso.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Start Rota";
$l_cu_destination = "Auto Route Destino";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Delete Route";
$l_cu_info = "Clique em Iniciar para o Setor Realspace para o setor e começar a entortar para o setor de destino.";
$l_cu_delete2 = "Excluir Rotas";
$l_cu_noroutes = "No Auto Rotas";
$l_cu_createroute = "Criar Nova Auto Route";
$l_cu_deleted = "Auto Rotas excluída.";
$l_cu_return = "Retornar para Auto Route Menu, clique em";
$l_cu_created = "Auto Rota foi criada.";
$l_cu_realmove = "Realspace mover para o setor";
$l_cu_warpmove = "Warp mover para o próximo sector";
$l_cu_warpfinal = "Warp mover para o setor final";
?>
