<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Você precisa de pelo menos 1 vez de construir uma base de";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "A Bomba Nova perde por pouco, mas inflige danos sobre o planeta.";
$l_planet_novaturns = "A Bomba Nova requer pelo menos [turns] se transforma em fogo.";
$l_planet_novafed = "A Bomba Nova não vai poder se nos sectores da Federação.";
$l_planet_nonova = "Você não tem a Bomb Nova instalado.";
$l_planet_firenova = "Fire Nova Bomb";
$l_planet_novaexplode = "Nova bomba explodiu quando ele foi demitido e seu navio sofreu graves danos.";
$l_planet_novaexplode2 = "Nova bomba explodiu quando ele foi demitido e sua nave foi destruída.";
$l_planet_noautotrade = "Auto Comércio Rodovia não definido para este planeta.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- Source_type [source_type] no porto [dest_id]";
$l_planet_autotradedelete = "Excluir Auto Comércio.";
$l_planet_autotradeadd = "Criar Auto Trade.";
$l_planet_tradedeleted = "Auto Comércio Rodovia Excluídos.";
$l_planet_tradeadded = "Nova Auto Comércio Rodovia Added.";
$l_planet_autotype = "Selecione o item para o comércio";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Você precisa adquirir um navio de carga para este planeta antes que você possa definir um Auto Comércio Rota.";
$l_planet_purchasecargo = "Se você gostaria de adquirir um navio de carga";
$l_planet_upgradecargo = "Se você gostaria de atualizar o seu navio de carga";

$l_planet_cargocapacity = "Capacidade:";
$l_planet_cargoowned = "Você já possui um navio de carga para este planeta.";
$l_planet_cargoshipbuy = "Compra navios cargueiros";
$l_planet_cargoshipupgrade = "Upgrade navios cargueiros";
$l_planet_cargoatmax = "Seu navio de carga está no nível máximo de melhoria.";
$l_planet_cargoshipbuyinfo = "Selecione uma predefinição navios cargueiros";
$l_planet_cargoshipupgradeinfo = "Atualize seu Cargo Ships Hull.";
$l_planet_cargoshipbuildinfo = "Construa seu próprio navio de carga";
$l_planet_tradehelp = "1. Você pode entrar em um porto de comércio para cada tipo de mercadoria. <br> 2. Você não pode negociar a mercadoria em uma porta que vende a mesma mercadoria. <br> Comércio de mercadorias em um porto de mercadorias, em um porta Ore Ore, ect. não fará nada. <br> 3. Se você não quiser negociar certas commodities basta digitar 0 para o sector portuário.";
$l_planet_cargocredits = "Auto Comércio créditos recebidos:";
$l_planet_cargonoown = "Você deve possuir o planeta para criar uma traderoute Auto.";
$l_planet_digtrans = "Transferência Dignitário";
$l_planet_nocredits1 = "Você não tem créditos suficientes para essa operação. O custo total é";
$l_planet_nocredits2 = "créditos e você só tem";
$l_planet_nobase = "Você deve ter uma base para gerenciar os níveis de defesa do planeta.";
$l_planet_genesisnoturn = "Você precisa de pelo menos 1 vez de usar dispositivos Genesis no planeta.";
$l_planet_nogenesis = "Você precisa de um dispositivo Genesis para destruir um planeta.";
$l_planet_wrongclass = "Esta classe de navio não pode demitir um dispositivo Nova Bomb.";

$l_planet_combatpreview = "Combate Preview";
$l_planet_beamfire1 = "Seu ataque foi detectado. Planetário disparando feixes! Maior Boca Fogo como o seu navio chega muito perto do planeta para lançamento de caças.";
$l_planet_beamfire2 = "Seu ataque foi detectado. Planetário disparando feixes! Massive taxa de incêndio a partir do planeta como Boca Baterias bloqueio em múltiplos acessos!";
$l_planet_beamfire3 = "Seu ataque foi detectado. Planetário disparando feixes! Boca baterias em todo o planeta estão bloqueando o fogo em vários maciça! Boca de fogo muito superior ao estimado!";
$l_planet_beamfire4 = "Seu ataque foi detectado. Planetário disparando feixes! Defesas Boca só poderá bloquear para uma passagem de fuzilamento.";

$l_planet_sofanobeamsshields = "não é o disparo de feixes de seus escudos.";
$l_planet_sofanobeamsarmor = "não é o disparo de feixes de sua armadura.";
$l_planet_flauncherfailed1 = "Seu lutador sistema de lançamento não está funcionando corretamente.";
$l_planet_flauncherfailed2 = "Você só tem sido capaz de lançar";
$l_planet_flauncherfailed3 = "por cento de seus combatentes.";
$l_planet_nodfightertofighter = "não está enviando nenhum combatentes para atacar seus combatentes.";
$l_planet_nodfightertotorp = "não está enviando nenhum combatentes a atacar o seu Torps.";
$l_planet_flauncherfailed3 = "por cento de seus combatentes.";
$l_planet_autotradetype = "- Source_type [source_type] no porto [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "está a atacar";
$l_planet_iminsector = "no setor";
$l_planet_imnova = "está usando um dispositivo em Nova";
$l_planet_imsofa = "é SOFA Bombing";
$l_planet_team = "Este planeta é propriedade de um companheiro de equipe e você não tem permissão para acessar as informações para este planeta.";
?>
