<?php
$l_novabomb_turns = "Bombë Nova kërkon atleast [turns] kthehet në zjarr.";
$l_novabomb_planetsdamaged = "Planetet dëmtuar nga bombë Nova";
$l_novabomb_planet = "Planet [name] pësuar dëme nga bombë Nova.";
$l_novabomb_novaexplode = "Nova bombë shpërtheu ndërsa ai u shkarkua dhe anija juaj ka pësuar dëme masive.";
$l_novabomb_novaexplode2 = "Nova bombë shpërtheu ndërsa ai u shkarkua dhe anija juaj është shkatërruar.";
$l_novabomb_notfedsec = "Nova bombë nuk mund të përdoret në lidhje me federatën pronë sektorët.";
$l_novabomb_destroyed_planet = "Nova bombë juaj plasaritur sipërfaqen e planetit dhe të shpuar në bazë ku ajo shpërtheu duke shkaktuar planet për të copëtojë.";
$l_novabomb_wrongclass = "Kjo klasë anije nuk mund të zjarrit një bombë Device Nova.";
$l_novabomb_nonova = "Ju nuk keni një bombë Nova instaluar.";
$l_novabomb_novamiss = "Bombë Nova mezi mungon por shkakton dëme mbi planetin.";
$l_novabomb_success = "Sektori [sector] ka qenë Nova ku shpërtheu bomba!";
$l_novabomb_mines = "Shkatërruar [mines] sektorin e Minierave.";
$l_novabomb_fighters = "Shkatërruar [fighters] Luftëtarët e sektorit.";
$l_novabomb_shipsdamaged = "Anijet dëmtuar nga bombë Nova";
$l_novabomb_ship_damage = "Starship [shipname] pësuar dëme nga bombë Nova.";
$l_novabomb_ship_survived = "Anija juaj ishte larg mjaft larg kur Nova bombë shpërtheu për të shmangur ndonjë dëm.";
?>
