<?php
$l_by_title = "Mirat";
$l_by_noturn = "Ju duhet të paktën një të kthehet në vendin ose modifikojë një dhuratë.";
$l_by_amount = "Mirat Shuma";
$l_by_place = "Vendi mirat";
$l_by_nobounties = "Nuk janë aktualisht nuk mirat.";
$l_by_bountyon = "Të mirat";
$l_by_placedby = "Vendosur nga";
$l_by_thefeds = "Federata";
$l_by_cancel = "Anulo";
$l_by_yourself = "Ju nuk mund të vendos një dhuratë nga vetë tuaj.";
$l_by_notenough = "Ju nuk keni kredi të mjaftueshme për të vendosur një dhuratë të shumës.";
$l_by_toomuch = "Ju nuk mund të vendos që mirësitë. Dhuratë maksimale të lejuara në një tjetër lojtar është [percent] për qind të neto vlerë tuaj";
$l_by_zeroamount = "Shpërblimi duhet të jetë më e madhe se 0 kredi.";
$l_by_placed = "Mirësitë ka qenë vendosur.";
$l_by_nobounty = "Kjo dhuratë nuk ekziston më.";
$l_by_notyours = "Se mirësia nuk u vu nga ju.";
$l_by_canceled = "Mirësitë ka qenë i anuluar.";
$l_by_action = "Veprimi";
$l_by_placebounty = "Vendi apo mirat pikëpamje.";
$l_by_moredetails = "Kliko mbi emrin për më shumë detaje.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "Lojtar ju jeni duke mirat e më nuk ekziston.";
$l_by_destroyed = "Ju nuk mund të vendos një dhuratë për një lojtar me një anije të shkatërruara.";
$l_by_nofedbounty = "Ju nuk do të merrni një dhuratë, nëse ju sulmojnë këtë anije lojtarë apo planetin.";
$l_by_fedcollectonly = "Vetëm Federata mund të mbledhim mirat";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Ju nuk do të merrni një dhuratë në qoftë se ju vendosni një spiun në këtë planet lojtarë.";
$l_pay_partial = "Make Pagesa e pjesshme";
$l_pay_button = "Paguhet";

$l_by_thealliance = "Aleanca";
$l_by_alliancecollectonly = "Vetëm Aleanca mund Mblidhni mirat";
$l_by_bountyscan = "Mirat";
?>
