<?php
$l_sm_title = "Sektori i raketave Launch";
$l_sm_invalid = "Nuk ka një lidhje të tërheq me litar në mes të këtij sektori dhe të sektorit të destinacionit.";
$l_sm_notarg = "Synuar jo në këtë sektor.";
$l_sm_noturn = "Ju duhet të paktën një të kthehet në zjarrin e raketave Sektorin tuaj.";
$l_sm_nosectormissile = "Ju nuk mbante ndonjë projektilë sektorit.";
$l_sm_noscan = "Sensore nuk mund të merrni një fix në shenjë!";
$l_sm_flee = "Synuar nga maneuvered raketave Sektori!";
$l_sm_ewd = "Synimi i angazhuar një pajisje prish jashtëzakonshme kur është zbuluar raketave Sektori!";
$l_sm_imtitle = "Anije Sipas Attack";
$l_sm_imbody = "[playername] është sulmuar një anije me Sektorin e raketave!";
$l_sm_sectormissilefail = "Sektori i raketave funksiononin mirë kur ajo goditi mburojën anijet e armikut!";
$l_sm_sectormissilefail2 = "Sektori i raketave funksiononin mirë kur ajo goditi anijet e armikut forca të blinduara!";
$l_sm_shieldhit = "[target] &#39;s mburoja janë goditur për [amount] dëm!";
$l_sm_shieldsdown = "[target] &#39;s mburoja janë të poshtë!";
$l_sm_armorhit = "[target] &#39;s forca të blinduara është goditur për [amount] dëm!";
$l_sm_armorbreached = "[target] &#39;s forca të blinduara thyer!";
$l_sm_targetnoenergy = "Anija armik, nuk ka ndonjë energji! Sektori i raketave nuk!";
$l_sm_attacking = "Sulmuar [target] bordin [shipname]";
$l_sm_targetok = "Ju nuk destory [name] &#39;s anije.";
$l_sm_lost = "[target] humbur [armor] pikat forca të blinduara dhe [energy] njësi të energjisë.";
$l_sm_destroyed = "[target] &#39;s anije ka qenë shkatërruar.";
$l_sm_escapepod = "Një pod ikur u nisën!";
?>
