<?php
// New News Items

$l_news_planets = "planetet";
$l_news_cols = "Milion kolonive";
$l_news_p_headline = "[player] &#39;s Perandorisë tani ka [total] yjeve";
$l_news_c_headline = "[player] &#39;s Perandorisë tani ka [total] milion kolonive";
$l_news_p_textXX = "Federata ka lëshuar paralajmërimet në lidhje me perandorinë e [name]. [name] ka kontroll nga [total] planetet dhe duhet të konsiderohet shumë e rrezikshme. Të gjithë sektorët duhet të rrisin menjëherë sektorit mbrojtëse.";
$l_news_c_textXX = "Perandoria e [name] është përjetuar mbipopullimit masive në të gjitha planetet me mbi [total] milion kolonive. Mungesa e ushqimit mund të shkaktojnë trazira. Të gjithë sektorët duhet të jenë të vetëdijshëm për veprimet e mundshme agresive nga [name] në të ardhmen.";

$l_created_universe = "&#39;Krijimi Universit &quot;";
$l_created_universe_full = "Shkencëtarët &#39;studjon fillimet e Universit kanë vendosur në mënyrë unanime që sot është dita më e statistikisht ka gjasa për krijimin Universi që kanë ndodhur&#39;";

$l_news_p_text5 = "Perandori në rritje e [name] tani ka pesë planetet, do të kujdesem FNN veprimet e [name] më të ngushtë në të ardhmen!";
$l_news_p_text10 = "Perandori në rritje e [name] tani kontrollon dhjetë planete, Raportet e FNN them se zgjerimi i mëtejshëm i [name] mund të çojë në luftë!";
$l_news_p_text25 = "Perandori i madh e [name] kolonizuara 25 planete tashmë, në një intervistë, [name] njoftoi se ai mund të konsiderojë që ngadalësojnë zgjerimin e tij në të ardhmen!";
$l_news_p_text50 = "Perandori e madhe e madhe e [name], i përfaqësuar nga 50 planetet në galaktikë e tërë po bëhet një forcë kërcënuese. Një prej gazetarëve FNN kuptova se [name] është anija e tij përmirësimin e planifikimit të një lufte të madh. Në një intervistë të [name] njoftoi se është bërë me qëllim të mbrojtjes only!";
$l_news_c_text25 = "Perandori në rritje e [name] tani ka rreth 25 milionë kolonistët, FNN do ta shikoj veprimet e [name] më të ngushtë në të ardhmen, por shumë e qartë se birthrates do të shpërthente!";
$l_news_c_text100 = "Perandori që aspirojnë e [name] tani ka 100 milionë kolonistët, pasi një shpërthim të normave të lindjes, [name] koloni duket të jetë një vend i mirë për familjet për të zgjidhur!";
$l_news_c_text500 = "Perandori i madh e [name] ka tani 500 milionë kolonistët, [name] tha në një intervistë se kolonizimin e galaktikë sapo ka filluar ende";
$l_news_c_text1000 = "Perandori humongous e [name] tani ka një miliard kolonistët, FNN gazetarëve kuptova se [name] është në posedim të ndonjë mekanizmi klonimit pazakontë duke e lejuar atë që të ngjall kolonistët të reja në sasi të mëdha. Me këtë sasi e kolonë, forca econmic e kësaj perandorie është i madh, FNN shpreson se [name] nuk do të shpenzojë paratë e tij në luftë";

$l_news_indi_short = "FNN thashetheme: mbi [planets] shpallin pavarësinë.";
$l_news_indi = "FNN ka atë autoritet të mirë se mbi [planets] planeteve kanë vendosur se ata janë të sunduar më mirë me veten dhe të bëhet e pavarur.";

$l_news_nova_short = "FNN Raporti: [name] përdor Nova bombë.";
$l_news_nova = "FNN ka lajme të thyer se [name] e ka përdorur bombë frikë Nova [total] herë (s) për të shkatërruar një planet dhe të gjitha anijet mbi të.";
$l_news_nova_m_short = "FNN Raporti: [name] përdor Nova bombë dhe mungon.";
$l_news_nova_m = "FNN ka lajme të thyer se [name] e ka përdorur bombë frikë Nova [total] herë (a) te provoni dhe shkatërrojnë një planet. Nova bombë shpërtheu jashtë atmosferë planetet dhe shkaktoi dëme masive në infrastrukturë planetare.";

$l_news_bounty = "FNN Raporti: [name] vendos një sasi të [amount] mirësitë e kreditit në [name2].";

$l_news_attackerpod_p_short = "FNN Raporti: [name] &#39;s anijes është shkatërruar.";
$l_news_attackerpod_P = "[name] &#39;s anija ishte shkatërruar ndërsa sulmuar një planet. Për fat të mirë [name] kishte një Pod Escape dhe mbijetuan.";

$l_news_attackerdie_p_short = "FNN Raporti: [name] vdes!";
$l_news_attackerdie_p = "[name] &#39;s anija ishte shkatërruar ndërsa sulmuar një planet dhe ata u vranë për shkak se ata nuk arritën të blerë një Pod Escape.";

$l_news_destroyed_p_short = "FNN Raporti: [name] sulmet dhe shkatërron planet!";
$l_news_destroyed_p = "[name] sulmuar [total] Planeti (s) në pronësi nga [owner] dhe popullata e çdo planetit shkatërruar planet për të parandaluar atë që kapur!";

$l_news_defeated_p_short = "FNN Raporti: [name] sulmet dhe humbjeve një planet!";
$l_news_defeated_p = "[name] sulmuar [total] Planeti (s) në pronësi nga [owner] dhe mundi forcat e mbrojtjes planetar!";

$l_news_notdefeated_p_short = "FNN Raporti: [name] sulmeve të një planet e humb!";
$l_news_notdefeated_p = "[name] sulmuar [total] Planeti (s) në pronësi nga [owner] dhe mbrojtjet planetare mbajtur kundër sulmeve të pamëshirshëm!";

$l_news_targetepod_short = "FNN Raporti: [name] sulmeve të një pronar [owner] dhe fiton!";
$l_news_targetepod = "[name] sulmuar [owner] &#39;s anijes dhe shkatërruar atë plotësisht. Për fat të mirë [owner] kishte pajisur me një anije e tyre Pod Escape dhe ata mbijetuan.";

$l_news_targetdies_short = "FNN Raporti: [name] sulmeve të një pronar [owner] dhe vret ato!";
$l_news_targetdies = "[name] sulmuar [owner] &#39;s anijes dhe shkatërruar atë plotësisht. Mjerisht [owner] nuk e ka pajisur me një anije e tyre Pod Escape dhe ata ishin vaporized.";

$l_news_fedcolbounty_short = "FNN Raporti: çarje Federata poshtë në [name]!";
$l_news_fedcolbounty = "Federata ka sot goditi pirat hapësirë famëkeq [name]! [name], i cili në mënyrë rutinore shkelur disa traktate hapësirë, u angazhuar për pak kohë nga battlecruiser Federatës, e cila shkaktoi [amount] kredi me vlerë të dëmtimit në anije pirate së. Zyrtarët e Federatës premtim më tej veprimet e tilla në të ardhmen!";

$l_news_alliancecolbounty_short = "FNN Raporti: çarje Aleanca poshtë në [name]!";
$l_news_alliancecolbounty = "Aleanca ka sot goditi pirat hapësirë famëkeq [name]! [name], i cili në mënyrë rutinore shkelur disa traktate hapësirë, u angazhuar për pak kohë nga Aleanca, e cila shkaktoi [amount] kredi me vlerë të dëmtimit në anije pirate së. Zyrtarët e Aleancës premtim më tej veprimet e tilla në të ardhmen!";

$l_news_fedcol_pbounty_short = "FNN Raporti: Federata gjuan poshtë [name]!";
$l_news_fedcol_pbounty = "Federata ka sot goditi pirat hapësirë famëkeq [name]! [name], i cili në mënyrë rutinore shkelur disa traktate hapësirë, u angazhuar për pak kohë nga battlecruiser Federatës, i cili konfiskoi planetit [planetname] planetname vlerë [amount] kredive në sektorin [sector]. Zyrtarët e Federatës premtim më tej veprimet e tilla në të ardhmen!";

$l_news_alliancecol_pbounty_short = "FNN Raporti: Aleanca gjuan poshtë [name]!";
$l_news_alliancecol_pbounty = "Aleanca ka sot goditi pirat hapësirë famëkeq [name]! [name], i cili në mënyrë rutinore shkelur disa traktate hapësirë, u angazhuar për pak kohë nga Aleanca, e cila konfiskoi planetit [planetname] planetname vlerë [amount] kredive në sektorin [sector]. Zyrtarët e Aleancës premtim më tej veprimet e tilla në të ardhmen!";

$l_news_fedcol_sbounty_short = "FNN Raporti: Federata gjuan poshtë [name]!";
$l_news_fedcol_sbounty = "Federata ka sot goditi pirat hapësirë famëkeq [name]! [name], i cili në mënyrë rutinore shkelur disa traktate hapësirë, u angazhuar për pak kohë nga battlecruiser Federatës, e cila konfiskoi një anije ([shiptype]) me vlerë [cost] në sektorin [sector]. Zyrtarët e Federatës premtim më tej veprimet e tilla në të ardhmen!";

$l_news_alliancecol_sbounty_short = "FNN Raporti: Aleanca gjuan poshtë [name]!";
$l_news_alliancecol_sbounty = "Aleanca ka sot goditi pirat hapësirë famëkeq [name]! [name], i cili në mënyrë rutinore shkelur disa traktate hapësirë, u angazhuar për pak kohë nga Aleanca, e cila konfiskoi një anije [shiptype] shiptype vlerë [cost] në sektorin [sector]. Zyrtarët e Aleancës premtim më tej veprimet e tilla në të ardhmen!";

$l_killheadline = "[target] u vra në një aksident";
$l_news_killed = "[target] u vra në një aksident tragjik sot. Si heroike - [target] është anëtare e fundit në bordin e anijes së tij, kur e kuptoi që nuk kishte ikur u nisën për në pod e tij. Ai mund të pushoni në paqe!";

$l_killSDheadline = "[target] u vra nga Sektori mbrojtëse.";
$l_news_killedSD = "[target] u vra nga një numër i madhe i Sektorit mbrojtëse në pronësi nga [killer]! Mjerisht, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killplanetheadline = "[target] u vra duke sulmuar një planet.";
$l_news_killedplanet = "[target] u vranë ndërsa sulmuar një planet në pronësi nga [killer] sot. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killshipheadline = "[target] u vra anije luftarake.";
$l_news_killedship = "[target] u vra në anije me anije të luftuar me [killer] sot. Kapiteni harruar me sa duket për të pajisur me një mbulesë anije shpëtojnë.";

$l_killsuicideheadline = "[target] vetëvrasje.";
$l_news_killedsuicide = "[target] vetëvrasje të kryera sot. Ata morën rrugën frikësuar për shkak se ata nuk kishin aftësi apo guxim të qëndrojnë deri në presionet e komanduar anijen e tyre.";

$l_killsofaheadline = "[target] u vra divan sulmuar një planet.";
$l_news_killedsofa = "[target] u vranë ndërsa divan sulmuar një planet në pronësi nga [killer] sot. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killnovaheadline = "[target] është vrarë gjatë një sulmi yll i ri.";
$l_news_killednova = "[target] u vra nga [killer] gjatë një sulm me bombë yll i ri sot. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killnovabackfireheadline = "[target] u vra nga një yll i ri dështonin.";
$l_news_killednovabackfire = "[target] u vra kur bombë yll i ri i tyre backfired sot. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killsectormissileheadline = "[target] u vra nga një predhë e Sektorit.";
$l_news_killedsectormissile = "[target] është vrarë kur një predhë e Sektorit nga [killer] ndikuar mburoja e tyre. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killhunterprobeheadline = "[target] u vra nga një hetim Hunter.";
$l_news_killedhunterprobe = "[target] u vra kur një hetim gjahtari nga [killer] ndikuar mburoja e tyre. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

$l_killtrapprobeheadline = "[target] u vra nga një hetim Trap rojtar.";
$l_news_killedtrapprobe = "[target] u vra kur një hetim Trap rojtar nga [killer] ndikuar mburoja e tyre. Për fat të keq, anija nuk ishte pajisur me një mbulesë shpëtojnë.";

//-------------------

$l_killpodheadline = "[target] &#39;s anija u shkatërrua në një aksident";
$l_news_killedpod = "[target] &#39;s anija u shkatërrua në një aksident tragjik sot. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killSDpodheadline = "[target] &#39;s anija u shkatërrua nga Sektori mbrojtëse.";
$l_news_killedSDpod = "[target] &#39;s anija u shkatërrua nga një numër i madhe i Sektorit mbrojtëse në pronësi nga [killer]! Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killplanetpodheadline = "[target] &#39;s anija u shkatërrua sulmuar një planet.";
$l_news_killedplanetpod = "[target] &#39;s anija ishte shkatërruar ndërsa sulmuar një planet në pronësi nga [killer] sot. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killshippodheadline = "[target] &#39;s u shkatërrua anija në anije luftarake.";
$l_news_killedshippod = "[target] &#39;s u shkatërrua anija në anije me anije të luftuar me [killer] sot. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killsofapodheadline = "[target] &#39;s anija ishte shkatërruar ndërsa divan sulmuar një planet.";
$l_news_killedsofapod = "[target] &#39;s anija ishte shkatërruar ndërsa divan sulmuar një planet në pronësi nga [killer] sot. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killnovapodheadline = "[target] &#39;s anija u shkatërrua gjatë një sulmi yll i ri.";
$l_news_killednovapod = "[target] &#39;s anija u shkatërrua nga [killer] gjatë një sulm me bombë yll i ri sot. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killnovabackfirepodheadline = "[target] &#39;s anija u shkatërrua nga një yll i ri dështonin.";
$l_news_killednovabackfirepod = "[target] &#39;s anije u shkatërruan kur bombë yll i ri i tyre backfired sot. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killsectormissilepodheadline = "[target] &#39;s anija u shkatërrua nga një predhë e Sektorit.";
$l_news_killedsectormissilepod = "[target] &#39;s anije u shkatërruan kur një Sektorin e raketave nga [killer] ndikuar mburoja e tyre. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killhunterprobepodheadline = "[target] &#39;s anija u shkatërrua nga një hetim Hunter.";
$l_news_killedhunterprobepod = "[target] &#39;s anije u shkatërruan kur një hetim gjahtari nga [killer] ndikuar mburoja e tyre. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

$l_killtrapprobepodheadline = "[target] &#39;s anija u shkatërrua nga një hetim Trap rojtar.";
$l_news_killedtrapprobepod = "[target] &#39;s anije u shkatërruan kur një hetim Trap rojtar nga [killer] ndikuar mburoja e tyre. Një transponderin Pod Escape u zbulua nga Federata Kërkoni dhe shpëtim.";

// --------------------------

$l_news_promotedheadline = "[name] ka ngritur në [rank]";
$l_news_promoted = "Federata ka kënaqësinë të njoftojë promovimin e [name] në rangun e [rank].";

$l_news_demotedheadline = "[name] ka qenë larguan të [rank]";
$l_news_demoted = "Federata keqardhje të njoftojë parimisht e [name] në rangun e [rank].";

$l_news_namechangedheadline = "[oldname] emri u ndryshua për [newname]";
$l_news_namechanged = "[oldname] aplikuar për të Bordit të Rishikimit të Federatës për të ndryshuar emrin e tyre të [newname]. Federata ka dhënë ndryshojë emrin. Nga kjo ditë përpara [oldname] do të jetë e njohur tani si [newname]. Të gjitha anijet dhe planetet duhet update shënimet e tyre menjëherë.";

$l_news_found_planets_short = "Federata Sondazh: [found_planets] planete të reja të vendosura.";
$l_news_found_planets = "Federata Anketa Scouts kanë vendosur [found_planets] planete të reja në sektorë të zbuluar kohët e fundit.";

$l_news_new_ports_short = "Federata Sondazh: [new_ports] porteve të reja të ndërtuara.";
$l_news_new_ports = "Federata Inxhinierët kanë ndërtuar [new_ports] porte të reja në sektorë të zbuluar kohët e fundit.";

$l_news_addedsectors_short = "Federata Sondazh: [addedsectors] sektorëve të zbuluar.";
$l_news_addedsectors = "Federata Anketa Scouts kanë zbuluar [addedsectors] sektorëve të reja. Kujdes i këshilluar.";

$l_news_artifactheadline = "[playername] përfundoi [artifact]";
$l_news_artifact = "[playername] ka gjetur të gjitha pjesëve të Objekti [artifact] dhe ka të gjithë pushtetin që mund të sigurojë.";

$l_news_artifactfoundheadline = "[playername] gjetur [artifact] copë";
$l_news_artifactfound = "[playername] ka gjetur një copë Objekti [artifact] dhe ka nevojë për [pieces] më [piece].";

?>
