<?php
$l_artifact_title = "Rifitoj Objekti";
$l_artifact_list_title = "Lista e objekteve të fituara";
$l_artifact_noscan = "Skanera juaj nuk mund të gjeni Objekti.";
$l_artifact_noturn = "Ju nuk keni mjaft të kthehet për të marrë këtë Objekti.";
$l_artifact_classname = "Emri Objekti";
$l_artifact_description = "Objekti Description";
$l_artifact_imagename = "Image Objekti";
$l_artifact_incomplete = "Objekti Copë";
$l_artifact_process = "Përdorimi Objekti i Kompletuar";

?>
