<?php
$l_login_title = "Hyrje";
$l_login_pw = "Fjalëkalimi:";
$l_login_chooseres = "Në pamundësi për të vendosur zgjidhjen tuaj ekran. Ju lutem zgjidhni aftë të mirë:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problemet?";
$l_login_emailus = "E-mail";
$l_login_forgot_pw = "Keni harruar fjalëkalimin tuaj? Enter ai bosh dhe identifikohuni për shtyp.";
$l_login_settings = "Game Settings";
$l_login_change = "Ndryshimi";
$l_login_title2 = "Kryesore Identifikohu për AATraders";
$l_login_reset1 = "Nuk Caktuar Reset";
$l_login_reset2 = "Reset Caktuar:";
$l_login_reset3 = "Sched Reset:";
$l_login_notice = "Njoftim i rendesishem:";
$l_login_endadminnews = "Fundi i Admin Lajme";
$l_login_tourney_signup = "Turneun Signups aktivizuar";

$l_login_profile_only = "Profili i Thjeshtë";
$l_login_newclosed_message = "Re Signups Mbyllur";
$l_login_tourneymode = "Running Tournament";
$l_login_tourneystarts = "Fillon:";
?>
