<?php
$l_ship2_buytitle = "Blerja e një anije të re";
$l_ship2_storetitle = "Kantier detar Storage Facility";
$l_ship2_wrongclass = "Klasa Wrong anije specifikuar";
$l_ship2_buying = "Ju jeni blerë:";
$l_ship2_tradein = "Tregtisë In:";
$l_ship2_value = "Current Ship Vlera:";
$l_ship2_newvalue = "Re Ship Vlera:";
$l_ship2_totalcost = "Kosto totale:";
$l_ship2_nomoney = "Ju nuk keni kredi të mjaftueshme për të blerë këtë anije.";
$l_ship2_purchase = "Blej";
$l_ship2_buynstore = "Blerë anije të reja dhe të vjetra një dyqan";
$l_ship2_nomoney2 = "Ju nuk keni kredi të mjaftueshme për të përfunduar këtë transaksion.";
$l_ship2_paystorage = "Juaj kanë hequr nga anija tuaj magazinimit.";
$l_ship2_turns = "Ju duhet të paktën [turns] kthehet për të kryer këtë veprim";
$l_ship2_error = "Gabim i brendshëm. Nuk mund të gjeni klasës anije.";
$l_ship2_owned = "Ju vetë këtë model tashmë të anijeve.";
$l_ship2_shipbought = "Ju keni blerë vetëm një anije të re!";

?>
