<?php
$l_s_yes = "Po";
$l_s_no = "Jo";
$l_s_enabled = "Enabled";
$l_s_disabled = "Me aftësi të kufizuara";

$l_s_modules = "Modulet";
$l_s_modulename = "Emri Module";
$l_s_moduleauthor = "Autor";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "Nuk Loaded Modulet";

$l_s_gamestatus = "Game Status";
$l_s_allowpl = "Allow Lojtaret";
$l_s_allownewpl = "Allow Re Players";

$l_s_gameoptions = "Game Options";
$l_s_allowteamplcreds = "Lejo Team Planet Credit Transfer";
$l_s_allowfullscan = "Allow Full Long Range Scan";
$l_s_sofa = "Lejo Nen-luftarakë syrit Sulmet";
$l_s_showpassword = "Display Password në Regjistrimi";
$l_s_genesisdestroy = "Torps Zanafilla mund të shkatërrojë yjeve";
$l_s_igb = "Intergalactic Banka (igb)";
$l_s_ksm = "Njohur Hapësirë Harta";
$l_s_navcomp = "Navigation Computer";
$l_s_newbienice = "Newbie Nice";
$l_s_spies = "Sistemi spiun";
$l_s_spycapture = "Lejo Spies për të kapur planetet";

$l_s_gamesettings = "Game Settings";
$l_s_gameversion = "Version i Lojes:";
$l_s_minhullmines = "Madhësia minimale e nevojshme për të goditur byk mina";
$l_s_averagetechewd = "Mesatarisht nivel Teknike Kur degradon e urgjencës Warp";
$l_s_numsectors = "Numri i Sektoret";
$l_s_maxwarpspersector = "Links maksimale per sektorin";
$l_s_averagetechfed = "Nivelin maksimal mesatar për sektorët e teknologjisë së Federatës";
$l_s_igbirateperupdate = "igb Norma e interesit per update";
$l_s_igblrateperupdate = "Norma igb Kredi per update";
$l_s_techupgradebase = "Teknike upgrade Level për Bazat";
$l_s_collimit = "Kolonive Limit";
$l_s_maxturns = "Numri maksimal i kthehet akumuluar";
$l_s_maxplanetssector = "Numri maksimal i planeteve në sektorin";
$l_s_maxtraderoutes = "Numri maksimal i traderoutes per lojtar";
$l_s_colreprodrate = "Kolon lindjes Rate";
$l_s_energyperfighter = "Njësia e Energjisë përdoret për sektorin e luftëtar";
$l_s_secfighterdegrade = "Degradim përqindje Sektori luftëtar normë";
$l_s_planetinterest = "Norma e interesit Planet";
$l_s_spiesperplanet = "Numri maksimal i spiunëve për planetit";
$l_s_spysuccessfactor = "Faktor spiun sukses";
$l_s_spykillfactor = "Spiun vrasin faktor";
$l_s_colsperfighter = "Kolonistët e nevojshme për të prodhuar 1 Fighter secili të kthehet";
$l_s_colspertorp = "Kolonistët e nevojshme për të prodhuar 1 Torpedo secili të kthehet";
$l_s_colsperore = "Kolonistët e nevojshme për të prodhuar 1 Ore secili të kthehet";
$l_s_colsperorganics = "Kolonistët e nevojshme për të prodhuar 1 Organics secili të kthehet";
$l_s_colspergoods = "Kolonistët e nevojshme për të prodhuar 1 Mallrave secili të kthehet";
$l_s_colsperenergy = "Kolonistët e nevojshme për të prodhuar 1 Energjisë secili të kthehet";
$l_s_colspercreds = "Kolonistët e nevojshme për të prodhuar 1 Kreditë secili të kthehet";
$l_s_colsper = "Kolonistët e nevojshme për të prodhuar 1 [commodity] secili të kthehet";

$l_s_gameschedsettings = "Game Scheduler Settings";
$l_s_schedtype = "Lloji Scheduler";
$l_s_cronbased = "Cron Bazuar";
$l_s_playertriggered = "Player Shkaktuar";
$l_s_minutes = "minuta";
$l_s_ticksupdate = "Ticks ndodhin çdo";
$l_s_turnsupdate = "Kthen do të ndodhë çdo";
$l_s_npcupdate = "Aleanca do të luajnë çdo";
$l_s_igbturnsupdate = "Interesat në llogaritë igb do të jenë grumbulluar çdo";
$l_s_newsupdate = "Lajme do të gjenerohet çdo";
$l_s_planetupdate = "Planetet do të gjenerojë prodhim çdo";
$l_s_spyupdate = "Spiunët do të veprojë çdo";
$l_s_portsupdate = "Portet do të rilind çdo";
$l_s_towupdate = "Anijet do të jenë towed nga sektorë të ushqyer çdo";
$l_s_scoreupdate = "Renditjen do të gjenerohet çdo";
$l_s_secdefdegrupdate = "Sektori mbrojtëse do të degraduar çdo";
$l_s_apocalypseupdate = "Apokalips planetare do të ndodhë çdo";
$l_s_release_version = "Version Game release";
$l_s_time_since_reset = "Koha që reset fundit";
$l_s_independence = "Planetar Pavarësia";
$l_s_dignitaryupdate = "Personalitetet do të veprojë çdo";

$l_s_turnsupdate = "kthehet çdo";
?>
