<?php
$l_sofa = "Nen-i syrit luftarakë sulmin";
$l_planet_basenoturn = "Ju duhet të paktën 1 të kthehet për të ndërtuar një bazë të";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "Bombë Nova mezi mungon por shkakton dëme mbi planetin.";
$l_planet_novaturns = "Bombë Nova kërkon atleast [turns] kthehet në zjarr.";
$l_planet_novafed = "Nova bombë nuk do të energjisë në sektorët e Federatës.";
$l_planet_nonova = "Ju nuk keni një bombë Nova instaluar.";
$l_planet_firenova = "Zjarri Nova bombë";
$l_planet_novaexplode = "Nova bombë shpërtheu ndërsa ai u shkarkua dhe anija juaj ka pësuar dëme masive.";
$l_planet_novaexplode2 = "Nova bombë shpërtheu ndërsa ai u shkarkua dhe anija juaj është shkatërruar.";
$l_planet_noautotrade = "Auto Route Tregtisë nuk është caktuar për këtë planet.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] në portin [dest_id]";
$l_planet_autotradedelete = "Fshije Auto Tregtisë.";
$l_planet_autotradeadd = "Krijo Auto Tregtisë.";
$l_planet_tradedeleted = "Auto Trade Route Deleted.";
$l_planet_tradeadded = "Re Tregtare Auto Route Added.";
$l_planet_autotype = "Zgjidhni pika të tregtisë";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Ju duhet të blini një anije e mallrave për këtë planet para se ju mund të vendosni një Tregtare Auto Route.";
$l_planet_purchasecargo = "Nëse dëshironi të blini një anije Cargo";
$l_planet_upgradecargo = "Nëse ju dëshironi të përmirësuar Cargo Ship tuaj";

$l_planet_cargocapacity = "Kapaciteti";
$l_planet_cargoowned = "Ju tashmë vetë një anije mallrash për këtë planet.";
$l_planet_cargoshipbuy = "Blerje Cargo Ship";
$l_planet_cargoshipupgrade = "Upgrade Cargo Ship";
$l_planet_cargoatmax = "Anija e mallrave juaj është në nivelin maksimal upgrade.";
$l_planet_cargoshipbuyinfo = "Zgjidh një paraprakisht Cargo Ship";
$l_planet_cargoshipupgradeinfo = "Upgrade mallrave tuaj Anije Hull.";
$l_planet_cargoshipbuildinfo = "Build Your Own Cargo Ship";
$l_planet_tradehelp = "";
$l_planet_cargocredits = "Auto Trade Credits Received:";
$l_planet_cargonoown = "Ju vetë duhet të planetit për të krijuar një Traderoute Auto.";
$l_planet_digtrans = "Transferimi Dignitary";
$l_planet_nocredits1 = "Ju nuk keni kredi të mjaftueshme për këtë transaksion. Kosto totale është";
$l_planet_nocredits2 = "kredi dhe nuk ke";
$l_planet_nobase = "Ju duhet të ketë një bazë për të menaxhuar planetin nivelet e mbrojtjes.";
$l_planet_genesisnoturn = "Ju duhet të paktën 1 të kthehet për përdorimin e pajisjeve Zanafilla e planetit.";
$l_planet_nogenesis = "Ju duhet një Device Zanafilla për të shkatërruar një planet.";
$l_planet_wrongclass = "Kjo klasë anije nuk mund të zjarrit një bombë Device Nova.";

$l_planet_combatpreview = "Combat Preview";
$l_planet_beamfire1 = "Sulmi juaj është zbuluar. Planetare qitjes Beams! Rritja e Beam zjarrit si anija juaj vjen në shumë afër planetit të nisë luftëtarëve.";
$l_planet_beamfire2 = "Sulmi juaj është zbuluar. Planetare qitjes Beams! Shkalla masive zjarr nga planeti si bateri trare hits bllokua për më shumë!";
$l_planet_beamfire3 = "Sulmi juaj është zbuluar. Planetare qitjes Beams! Rreze Bateritë e gjithë planetit janë mbyllje në zjarr masiv për të shumta! Zjarr Beam shumë më të larta se vlerësohet!";
$l_planet_beamfire4 = "Sulmi juaj është zbuluar. Planetare qitjes Beams! Mbrojtëse Beam mund të bllokohet nga vetëm për një kalojë qitjes.";

$l_planet_sofanobeamsshields = "nuk është e qitjes trarëve në mburoja juaj.";
$l_planet_sofanobeamsarmor = "nuk është e qitjes trarëve në forca të blinduara tuaj.";
$l_planet_flauncherfailed1 = "Luftëtar juaj nisjen e ka funksiononin mirë sistemi.";
$l_planet_flauncherfailed2 = "Ju keni qenë vetëm në gjendje për të nisur";
$l_planet_flauncherfailed3 = "qind e luftëtarëve tuaj.";
$l_planet_nodfightertofighter = "nuk është dërguar ndonjë luftëtarëve për të sulmuar luftëtarët tuaj.";
$l_planet_nodfightertotorp = "nuk është dërguar ndonjë luftëtarëve për të sulmuar torps tuaj.";
$l_planet_flauncherfailed3 = "qind e luftëtarëve tuaj.";
$l_planet_autotradetype = "- [source_type] në portin [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "është sulmuar";
$l_planet_iminsector = "në sektorin";
$l_planet_imnova = "është duke përdorur një Device Nova në";
$l_planet_imsofa = "është SOFA bombardimeve";
$l_planet_team = "Ky planet është në pronësi të një shoku ekip dhe ju nuk keni leje për të hyrë informacion për këtë planet.";
?>
