<?php
$l_opt_title = "Zgjidh një Icon Team";
$l_opt_errorsize = "Error: image juaj nuk duhet të jetë më e madhe se 64x64 piksela në madhësi.";
$l_opt_errortype = "Error: Image duhet të jetë JPG, GIF ose PNG";
$l_opt_errornographic = "Gabim: nuk ka grafik të zgjedhura.";
$l_opt_currentavatar = "Current juaj Team Icon";
$l_opt_uploadavatar = "Upload një Icon";
$l_opt_directory = "Zgjidhni Team Icon Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Zgjidhni Team Icon";
$l_opt_noteam = "Ju nuk janë në një ekip.";
$l_opt_notleader = "Vetëm Koordinatori Ekipi mund të ndryshojë Icon Team.";
$l_opt_inuse = "Gjitha Icons Team në këtë dosje janë në përdorim.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
