<?php
$l_defense_deploy_title = "Sektorin e Minierave dhe të vendosë Fighters";
$l_defense_deploy_noturn = "Ju duhet të paktën një të kthehet për të vendosur sektorin mbrojtëse.";
$l_defense_deploy_nopermit = "Dërgimi i Minierave dhe luftëtarëve në këtë sektor nuk është e lejuar.";
$l_defense_deploy_nodeploy = "Nuk mund të vendoset këtu. Tjetër anijes ose Ekipi ka mina ose UÇK-së në këtë sektor.";
$l_defense_deploy_info1 = "Ju aktualisht në sektorin [sector]. Ka [mines] mina dhe [fighters] luftëtarët këtu.";
$l_defense_deploy_info2 = "Ju keni [mines] mina dhe [fighters] luftëtarët në dispozicion për të vendosur";
$l_defense_deploy_deploy = "Vendosë";
$l_defense_deploy_deployed = "Vendosur";
$l_defense_deploy_att = "Sulmi";
$l_defense_deploy_notorps = "Ju nuk keni mjaft silurët.";
$l_defense_deploy_nofighters = "Ju nuk keni mjaft luftëtarë";
$l_defense_deploy_dmines = "Vendosur [mines] mina.";
$l_defense_deploy_dfighter = "Vendosur [fighters] luftëtarë.";
$l_defense_deploy_max_fighters = "Ky sektor mund të mbështesin një maksimum prej [amount] luftëtarë.";
$l_defense_deploy_toomanyfighters = "Ju keni provuar të vendosin më shumë luftëtarë sesa sektori mund të mbështesim.";
?>
