<?php
$l_readm_title = "Lexo Mesazh";
$l_readm_delete = "MESAZH Deleted";
$l_readm_nomessage = "Ju nuk keni Messages pritur për ju ...";
$l_readm_center = "Mesazh Marrja Center";
$l_readm_sender = "Mesazh Sender";
$l_readm_captn = "Kapiten";
$l_readm_del = "Fshij";
$l_readm_repl = "Përgjigje";
$l_readm_return = "Kliko këtu për t&#39;u kthyer në menunë kryesore";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Fshij gjithë";
$l_readm_subject = "Subjekti";
$l_readm_quote = "Citati";
$l_readm_block = "Block Sender";
$l_readm_alert = "Sistemi Alert";
$l_readm_alertbody = "Anije Computer";
?>
