<?php
$l_news_title = "Universi Lajme";
$l_news_info = "FNN është ndër udhëheqësit galaktikë e <br> në lajme dhe shpërndarjen e informacionit. <br> Me personel 24 orë, shtatë ditë në javë nga një <br> personelit të përkushtuar në selinë e galaktikë FNN&#39;s <br> në Proksima Centauri dhe në galaxywide zyrave!";
$l_news_for = "News for";
$l_news_prev = "ditë më parë";
$l_news_next = "nesërmen";
$l_news_none = "Na vjen keq, sot nuk ka lajme.";
$l_news_flash = "News Flash";
$l_news_end = "Fundi i lajmeve";
$l_news_bestviewed = "Best viewed in Opera, Safari dhe IE";
$l_news_fedannouncements = "Federata Njoftime";
$l_news_planetarynews = "Planetar Lajme";
$l_news_planetshipnews = "Planetare dhe Ship News";
$l_news_afteractionnews = "Pas Action Combat Lajme";
?>
