<?php
$l_shipyard_title = "Kantjerin";
$l_planet = "Planet";
$l_ship_welcome = "Mirë se vini në kantjerin e juaj e Tokës. Ne aktualisht ofrojnë këto modele për shitje.";
$l_ship_class = "Klasa";
$l_ship_properties = "Klasa Prona";
$l_ship_current = "Aktual";
$l_ship_outstorage = "Get out of Storage";
$l_ship_storagecost = "Kosto Storage";
$l_ship_storagewarn = "Pasi merrni tuaj Pioneer nga magazinimit ju do të humb e ju kanë lëshuar mbi shkatërrimin fillestar tuaj anije.";
$l_ship_levels = "Anije Përbërësit Nivelet";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Çmimi";
$l_ship_turns = "Kthehet për të ndërtuar";
$l_ship_purchase = "Blej";
$l_ship_stored = "Ruajtur";
$l_ship_basehull = "Baza Hull:";

$l_ship_averagemaxtech = "Mesatarja maksimale Teknike Niveli:";
$l_ship_averagenormaltech = "Mesatarja Normal Teknike Niveli:";
$l_ship_averagecurrenttech = "Mesatarja aktuale Teknike Niveli:";
?>
