<?php
///SPIES
$l_dig_title = "Dignitary Menu";
$l_dig = "Personalitete";
$l_dig_disabled = "Dignataries janë me aftësi të kufizuara!";
$l_dig_noturn = "Ju duhet të paktën një të kthehet për të dërguar një dignitary në një planet.";
$l_dig_notonboard = "Ju nuk keni asnjë dignitary në bord.";
$l_dig_ownplanet = "Ju nuk mund të dërgoni një dignitary një planetin armik.";
$l_dig_unownedplanet = "Ju nuk mund të dërgoni një dignitary të planetit pa pronar.";
$l_dig_planetfull = "Nuk lejohet tashmë [max] personalitete në këtë planet.";
$l_dig_sendtitle = "Dërgimi i një dignitary [digID] të planetit: <BR> Zgjidhni dignitary e misionit:";

$l_dig_codenumber = "Kodi";
$l_dig_job = "Puna";
$l_dig_percent = "Përqindje";
$l_dig_move = "Lëvizja";
$l_dig_action = "Veprimi";
$l_dig_shipowner = "Anije Owner";
$l_dig_shipname = "Emri anijes";
$l_dig_shiptype = "Anije Klasa";
$l_dig_shiplocation = "Anije Location";
$l_dig_planetowner = "Planet Owner";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sektori";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Maksimale Per Planet";
$l_dig_legend = "Dignitary Legend";
$l_dig_description = "Dignitary Description";
$l_dig_waiting_description = "Dignitary do të krijojë silurët dhe luftëtarëve ndërsa duke pritur për një detyrë punë.";
$l_dig_changeerror = "Raporti i punës Dignitary Ndryshimi";

$l_dig_nospieshere = "Ju nuk keni asnjë personalitete në këtë planet!";
$l_dig_transferred = "personalitete transferuar";
$l_dig_backonship = "Dignitary është tani në anije tuaj.";
$l_dig_dismiss = "Shkarkojë dignitary?";
$l_dig_changebutton = "Ndryshimi";
$l_dig_notyourplanet = "Kjo nuk është planet tuaja.";

$l_dig_defaulttitle1 = "Personalitetet më anijeve armik";
$l_dig_defaulttitle2 = "Personalitetet në planetet tuaj";
$l_dig_defaulttitle3 = "Personalitetet në planetet tuaj";
$l_dig_defaulttitle4 = "Personalitetet më anije tuaj";

$l_dig_no1 = "Ju nuk keni asnjë personalitete të anijeve armik.";
$l_dig_no2 = "Ju nuk keni asnjë personalitete në planetet e juaj.";
$l_dig_no3 = "Ju nuk keni asnjë personalitete në planetet e juaj.";
$l_dig_no4 = "Ju nuk keni asnjë personalitete në anije tuaj.";
$l_dig_nodignitaryatall = "Ju nuk keni asnjë personalitete.";
$l_dig_notknown = "Panjohur";
$l_dig_dismiss = "Shkarkojë";
$l_dig_dismiss2 = "Personalitete pushua nga puna.";
$l_dig_menu = "për t&#39;u kthyer në Dignitary Menu.";

?>
