<?php
$l_contact_admin_title = "Kontakto Game Administrator";
$l_contact_admin_thanks = "Faleminderit për komentin tuaj.";
$l_contact_admin_email_alert = "Ju lutem shkruani një adresë e vlefshme email.";
$l_contact_admin_name_alert = "Ju lutemi shkruani emrin tuaj.";
$l_contact_admin_comment_alert = "Ju lutem shkruani komentet tuaja.";
$l_contact_admin_name = "Emri";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Pyetje / Koment";
$l_contact_admin_submit = "Submit Pyetje / Komente";
$l_contact_admin_close = "Mbylle dritaren";
$l_contact_admin_thanks_comment = "Faleminderit për komentin tuaj ose pyetje. Ne do të trajtojë çdo pyetje dhe ju me email përgjigje tonë.";

?>
