<?php
$l_sf_attacking = "Mbrojtje luftëtarët Sektori janë sulmuar ju! <BR>";
$l_sf_destfight = "Your trarëve shkatërruar [lost] luftëtarët <BR>";
$l_sf_destfightb = "Your trarëve shkatërruar [lost] luftëtarët <BR>";
$l_sf_torphit = "Silurët hit:";
$l_sf_destfightt = "Your silurët shkatërruar [lost] luftëtarët <BR>";
$l_sf_fighthit = "Luftëtarët Sulmi:";
$l_sf_destfightall = "Ju të gjithë luftëtarë të shkatërruar. <BR>";
$l_sf_destfightt2 = "Ju shkatërruar [lost] luftëtarë. <BR>";
$l_sf_lostfight = "Ju ka humbur të gjithë luftëtarët. <BR>";
$l_sf_lostfight2 = "Ju humbur [lost] luftëtarë. <BR>";
$l_sf_armorbreach = "Forca të blinduara juaj është shkelur! <BR>";
$l_sf_armorbreach2 = "Forca të blinduara juaj është goditur për [lost] dëme. <BR>";
$l_sf_sendlog = "[player] shkatërruar [lost] luftëtarët e sektorit të mbrojtjes në sektorin [sector].";
$l_sf_lreport = "Ju humbur [armor] pikë forca të blinduara, [fighters] luftëtarë, dhe përdorur [torps] silurët. <BR><BR>";
$l_sf_shipdestroyed = "Anija juaj është shkatërruar! <BR><BR>";
$l_sf_sendlog2 = "Mbrojtje luftëtarët Sektori i shkatërruar [player] në sektorin [sector].";
$l_sf_escape = "Për fat të mirë ju keni një mbulesë shpëtuar! <BR><BR>";

$l_sf_fnoattack = "nuk është dërguar ndonjë luftëtarëve për të sulmuar luftëtarët tuaj.";
$l_sf_fnoattackt = "nuk është dërguar ndonjë luftëtarëve për të sulmuar silurët tuaj.";
$l_sf_fnoattacka = "nuk është dërguar ndonjë luftëtarëve për të sulmuar forca të blinduara tuaj.";
$l_sf_flaunchmalf1 = "Luftëtar juaj nisjen e ka funksiononin mirë sistemi.";
$l_sf_flaunchmalf2 = "Ju keni qenë vetëm në gjendje për të nisur";
$l_sf_flaunchmalf3 = "qind e luftëtarëve tuaj.";
$l_sf_fightertorpexg = "Luftëtar të Torpedo / Mine Shkëmbim";
$l_sf_torpfighterexg = "Anija Torpedo të Sektorit luftarakë Exchange";
$l_sf_fighterarmorexg = "Sektori luftarakë të anijes Armor Exchange";
$l_sf_tlaunchmalf1 = "Your torpedo nisjen e ka funksiononin mirë sistemi.";
$l_sf_tlaunchmalf2 = "Ju keni qenë vetëm në gjendje për të nisur";
$l_sf_tlaunchmalf3 = "qind e silurët tuaj.";
$l_sf_bountysd = "Ju keni sulmuar një sektor përmban një planet që do t&#39;ju japë një dhuratë nëse sulmuar planetit. Federata ka aktivizuar një vetë-automatike destruct mbi të gjitha luftëtarët tuaj dhe silurët. Mos sulm mbrojtjet e sektorit në këtë sektor përsëri. You have been warned!";
?>
