<?php
$l_new_pwis = "Fjalëkalimi juaj është";
$l_new_charis = "Emri juaj karakter është";
$l_new_title2 = "Create New Player Dy Faza";
$l_new_blank = "E-mail, emrin anije, dhe emri karakter nuk mund të jetë bosh.";
$l_new_inuse = "E-mail [username] është tashmë në përdorim.";
$l_new_forgotpw = "Keni harruar fjalëkalimin tuaj?";
$l_new_inusechar = "Emri Karakteri [character], është tashmë në përdorim.";
$l_new_similar_inusechar = "Emri juaj karakter tingëllon shumë i ngjashëm me [character], një emër tashmë në përdorim.";
$l_new_inuseship = "Emri i anijes [shipname], është tashmë në përdorim.";
$l_new_similar_inuseship = "Emri juaj anije tingëllon shumë i ngjashëm me [shipname], një emër tashmë në përdorim.";
$l_new_pwsent = "Fjalëkalimi ka qenë dërguar për të [username].";
$l_new_err = "Ju lutem provoni përsëri";
$l_new_topic = "Alien Assault Tregtarët Fjalëkalimi";
$l_new_message = "Ip $ Përshëndetje, \ n \ nSomeone nga adresa IP kërkuar që fjalëkalimin tuaj për Tregtarët të dërguar te ju. \ \ N fjalekalimin nYour është: [pass] \ n \ nThank ju \ n \ nThe Tregtarët ekip web.";
$l_new_invalidemail = "Invalid Email Address.";
$l_new_tutorial = "Kliko këtu për të lexuar Mini-tutorial para se prerjet në lojë.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "për të shkuar në ekran login.";

?>
