<?php
$l_cu_storing = "Ruajtjen";
$l_cu_inistored = "<b>Të gjitha vlerat për këtë janë ruajtur me sukses.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto Route Destinacioni";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Fshije Route";
$l_cu_info = "Klikoni në Sektorin Fillim të Realspace për këtë sektor dhe të fillojnë warping në sektorin destinacion.";
$l_cu_delete2 = "Fshije Rrugët";
$l_cu_noroutes = "Nuk Rrugët Auto";
$l_cu_createroute = "Create New Auto Route";
$l_cu_deleted = "Auto Rrugët fshihet.";
$l_cu_return = "Kthehuni tek Auto Route Menu klikoni";
$l_cu_created = "Auto Route është krijuar.";
$l_cu_realmove = "Masa Realspace ndaj sektorit";
$l_cu_warpmove = "Masa Warp në sektorin e ardhshëm";
$l_cu_warpfinal = "Masa Warp në sektorin e fundit";
?>
