<?php
$l_pre_title = "Ndryshimi Realspace Presets";
$l_pre_exceed = "Preset [preset] kalon max universin e [sector_max]. Nuk presets ruajtur. <BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Ruaj";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] është një titull jo i saktë sektor.";
$l_pre_invalidchange = "[sector] është një Zanafilla Sektori Sektori. Vjetër juaj paraprakisht është i pandryshuar.";
?>
