<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Hetim Nivelet";
$l_probe_engine = "Motor";
$l_probe_sensors = "Sensore";
$l_probe_cloak = "Mantel";
$l_probe_title = "Space Probe Menu";
$l_probe_none = "Ju nuk janë në sektorin e njëjtë si ky hetim, kështu që ju nuk mund të ndërveprojnë me të.";

$l_probe_named = "Mirë se vini në hetimin Numri [probename], në pronësi nga [name], të vendosura në sektorin [sector].";
$l_probe_orders = "[orders] hetimin për të kërkuar univers";
$l_probe_orders_link = "Programi";
$l_probe_upgrade = "[upgrade] hetimin Sensore / Motor / perde";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] hetimin për vendosje më vonë";
$l_probe_pickup_link = "Përmirësim";
$l_probe_update = "Përditësimi";

$l_probe_att_link = "Sulmi";
$l_probe_att = "[attack] në hetim";
$l_probe_att_sure = "A jeni i sigurt ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] hetim";

$l_probe_unknown = "Panjohur";
$l_plant_scn_turn = "Ju duhet të paktën një të kthehet për të skanoni një hetim.";
$l_probe_noscan = "Sensore nuk mund të merrni një fix në shenjë!";
$l_probe_logscanA = "[name] përpoq të skanoni një nga hetimet tuaj në sektorin [sector], por nuk arriti.";
$l_probe_logscanB = "Një nga hetimet tuaj në sektorin [sector] ishte skanuar nga [name].";
$l_probe_scn_report = "Rezultatet Scan në [name], në pronësi nga: [owner]";

$l_probe_caplog = "Hetim juaj &#39;[probename]&#39; në sektorin [sector] u pushtua nga [name].";
$l_probe_scan = "Hetim scans sektori [sector] dhe gjen:";
$l_probe_destroyprobe = "Hetim Destroy";
$l_probe_destroyed = "Hetimi i shkatërruar!";
$l_probe_warning = "Të bësh këtë do të shkatërrojë plotësisht këtë hetim";
$l_probe_confirm = "A me të vërtetë duan të shkatërrojnë këtë hetim?";
$l_gns_turn = "Ju nuk keni mjaft të kthehet për të shkatërruar këtë hetim";
$l_probe_type = "Lloji hetim";
$l_probe_type0 = "Stacionare hetimin";
$l_probe_type1 = "Rojë hetimin";
$l_probe_type2 = "Warp hetimin";
$l_probe_type3 = "Realspace hetimin";
$l_probe_type4 = "Sequential Realspace hetimin";
$l_probe_target = "Sektori i synuar";
$l_probe_ordered = "Hetimi i programuar dhe do të fillojë në kërkim.";
$l_probe_order2 = "Hetim është një [type] dhe është i synimeve të dhënësit të sektorit [target]";
$l_probe_pickedup = "Hetimi i zgjedhur dhe vendosur në ruajtje aktiv";
$l_probe_title = "Hetim Menu";
$l_probe_messages = "për të parë se çfarë kanë zbuluar spiunët tuaj.";

$l_probe_defaulttitle1 = "Hetimet Active";
$l_probe_defaulttitle2 = "Hetimet keni kap";
$l_probe_defaulttitle3 = "Hetimet në planetet e juaj";
$l_probe_defaulttitle4 = "Hetimet në anije tuaj";
$l_probe_linkback = "për të shkuar në menynë hetim.";
$l_probe_no1 = "Ju nuk keni asnjë hetime aktive.";
$l_probe_no2 = "Ju nuk keni asnjë hetimet në ruajtje.";
$l_probe_no3 = "Ju nuk keni asnjë hetimet në planetet e juaj.";
$l_probe_no4 = "Ju nuk keni asnjë hetimet mbi anije tuaj.";
$l_probe_noprobeatall = "Ju nuk keni asnjë hetime.";
$l_probe_notknown = "Panjohur";
$l_probe_launch = "Pika";
$l_probe_detect = "Zbulua";
$l_probe_codenumber = "Kodi";
$l_probe_job = "Puna";
$l_probe_percent = "Përqindje";
$l_probe_move = "Lëvizja";
$l_probe_view = "Shikimi";
$l_probe_action = "Veprimi";
$l_probe_shipowner = "Anije Owner";
$l_probe_shipname = "Emri anijes";
$l_probe_shiptype = "Anije Klasa";
$l_probe_shiplocation = "Anije Location";
$l_probe_planetowner = "Planet Owner";
$l_probe_planetname = "Planet";
$l_probe_sector = "Current Sektori";
$l_probe_tsector = "Sektori i synuar";
$l_probe_type = "Lloji hetim";
$l_probe_forbid = "Ju nuk mund të heqë hetimet në këtë sektor";

$l_probe2_title = "Launch Space Probe";
$l_probe2_turn = "Ju duhet të paktën një të kthehet për të përdorur një hetim hapësirë.";
$l_probe2_onplanet = "Ju nuk mund të përdorni këtë pajisje, ndërsa në sipërfaqe planetit.";
$l_probe2_noprobe = "Ju nuk keni asnjë hetimet hapësirë.";
$l_probe2_forbid = "Fillimi i një hetim në këtë sektor nuk është e lejuar.";
$l_probe2_launched = "Hetimi i nisur Space!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Player";
$l_probe2_onboarda = "në bordin e një";
$l_probe2_classship = "anije klasë";
$l_probe2_traveled = "udhëtoi për në sektorin e";
$l_probe2_fedjammed = "Federata është zhurma të gjitha sensor scans në Sektorin 1.";
$l_probe2_lastseen = "Anije Last Seen";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Supports";
$l_probe2_planets = "planetet";
$l_probe2_sectord = "Sektori i mbrojtjes identifikuar";
$l_probe2_mines = "Miniera";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Anije identifikuar";
$l_probe2_ships2 = "Anije identifikuar";
$l_probe2_noneowned = "Jo planetet nuk zotërohet nga ju nuk është zbuluar.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Asgjë identifikuar";
$l_probe2_nocredits = "Ju nuk keni kredi të mjaftueshme për këtë transaksion. Kostoja totale është [total] kredi dhe nuk ke [credits] kredi.";

$l_probe_forbidSG = "Ju nuk mund të dërgoni një hetim lloj Realspace në Sektorin Zanafilla krijuar sektorë.";
$l_probe_forbidFED = "Ju nuk mund të dërgoni një hetim lloj Realspace në Federatën ose sektorë të Aleancës në pronësi.";
$l_probe_forbidINVALID = "Sektori juaj destinacioni është një titull jo i saktë sektor.";
?>
