<?php
$l_login_sclosed = "Server Mbyllur";
$l_login_closed_message = "Serveri i mbyllur deri në një njoftim të mëtejshëm.";
$l_login_title2 = "Identifikohu Dy Faza";
$l_login_banned = "<b>Ju keni qenë ndaluar nga kjo lojë nga administratori. Ju nuk janë më të mirëpritur për të luajtur në këtë server. Herën tjetër, sillen.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "Për shkak të seriozitetit të këtij krimi dhe vicioz sulm kundër jush, Federata ka vendosur që të sigurojë një mirësjellje pa pagesë nga klonimit mbetet tuaj. Mjerisht, prona edhe në këtë ditë dhe moshë, klonet e re nuk mund të zotërojnë, përveç nga bazat për të siguruar jetesën. Ju do të pajiset me një anije dhe një bazë për të marrë disa kredi ju keni filluar. Shpresojmë jetën tuaj të ardhshëm do të jetë më mirë.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Ju nuk kishte pod shpëtojnë, dhe për shkak të suksesit tuaj modest në këtë jetë, Federata rënie të klon ju. Mbetet juaj duhet përfundimisht të bien në një gravitetit mirë, shpresojmë që do të përdoret për të krijuar jetën e gjetiu ... disa miliard vjet nga tani. <BR><BR> Better luck next game ...";
$l_login_4gotpw1 = "Fjalëkalimi që shkruat nuk është korrekt. <BR><BR> Nëse keni harruar fjalëkalimin tuaj,";
$l_login_4gotpw2 = "ta marr e-mail për ju. <BR><BR> Ndryshe,";
$l_login_4gotpw3 = "të provoni përsëri. Përpjekje logged me adresën IP të";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Ju keni vdekur në një incident i tmerrshëm.";
$l_login_blackbox = "është informacion blackbox që ishte marrë nga anijet rrënojat tuaj.";
$l_new_login = "për të shkuar në ekran login.";
$l_login_playerlimit = "Server ka arritur numri maksimal i lojtarëve që mbështet. Ju lutemi provoni më vonë.";
?>
