<?php
$l_autotrade_title = "Auto Traderoute Menu";
$l_autotrade_dismiss2 = "Auto Traderoutes Deleted.";
$l_autotrade_report = "Auto Traderoute Raporti";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energjisë";
$l_autotrade_capacity = "Kapaciteti";
$l_autotrade_goods = "Mallrat Çmimi";
$l_autotrade_ore = "Ore Çmimi";
$l_autotrade_organics = "Organics Çmimi";
$l_autotrade_energy = "Energji Çmimi";
$l_autotrade_colonist = "Kolon Çmimi";
$l_autotrade_credits = "Tregtisë Kredite";
$l_autotrade_delete = "Fshij <br> Route";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "No Route";
$l_autotrade_sector = "Sektori";
$l_autotrade_credit2 = "kredi";
$l_autotrade_deletebutton = "Fshij";
$l_autotrade_noroute2 = "Ju nuk keni asnjë Traderoutes Auto setup.";
?>
