<?php
$l_beacon_title = "Vendosë Hapësirë Beacon";
$l_beacon_notpermitted = "Dërgimi i beacons hapësirë në këtë sektor nuk është e lejuar.";
$l_beacon_reads = "Fener Present lexon";
$l_beacon_none = "Ka aktualisht nuk është një fener në këtë sektor.";
$l_beacon_enter = "Enter your text për fener";
$l_beacon_nowreads = "Fener tani lexon";
$l_beacon_donthave = "Ju nuk mund të ketë një fener hapësirë.";
?>
