<?php
$l_opt_title = "Options";
$l_opt_chpass = "Ndërro fjalëkalimin";
$l_opt_curpass = "Fjalëkalimi i tashëm:";
$l_opt_newpass = "Fjalëkalimi i ri:";
$l_opt_newpagain = "Fjalëkalimi Re (përsëri):";
$l_opt_userint = "User Interface";
$l_opt_usenew = "Layout Përdorimi i ri?";
$l_opt_lang = "Gjuha";
$l_opt_template = "Template";
$l_opt_select = "Zgjidh një:";
$l_opt_enabled = "Enabled";
$l_opt_save = "Ruaj";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Lokale dhe Galaxy Harta Width:";
$l_opt_profiletitle = "Profili";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Regjistruar me Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Kur ju regjistroheni në një tjetër lojtar tuaj server template, lajme shoutbox dhe përcaktimet e mësipërme do të përdoret në server.";
$l_opt_showshoutbox = "Show Shoutbox:";
$l_opt_shownewscrawl = "Show Lajme zvarritje:";
$l_opt_playername = "Emri Player:";
$l_opt_playernamecost = "Federata Emri Ndrysho Pagesa: [amount] credits";
?>
