<?php
$l_die_title = "Self-Destruct";
$l_die_rusure = "A jeni i sigurt që dëshironi të shkatërrojë anije tuaj? Kjo do të ju largojë nga loja.";
$l_die_goodbye = "Galaktikë Mirupafshim mizor!";
$l_die_check = "A jeni pozitiv se ju dëshironi të hiqni veten nga loja?";
$l_die_nonono = "JO! JO! JO!";
$l_die_what = "Cili ishte i të menduarit?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Ju anije dhe të gjitha kanë qenë në bordin vaporized.";
$l_die_please1 = "logout";
$l_die_please2 = "Ju lutem, [logout_link]";
$l_die_exploit = "Mos luaj me atë që ju nuk e kuptoni.";
?>
