<?php
$l_sn_title = "Sektori Shenimet";
$l_sn_pntitle = "Sektoret me Shënimet personale";
$l_sn_tntitle = "Sektoret me Shenimet Team";
$l_sn_psntitle = "Sektori Shënimet personale";
$l_sn_tsntitle = "Team Sektori Shenimet";
$l_sn_editnote = "Edit Note Sektori:";
$l_sn_deleteedit = "Fshij apo Edit:";
$l_sn_addnote = "Shto Shënim Sektori:";
$l_sn_list = "Sektoret Lista Shenimet";
$l_sn_listts = "Sektoret Lista me Shenimet Team";
$l_sn_addteam = "Add Team";
$l_sn_deleteteam = "Fshije Team";
$l_sn_delete = "Fshij";
$l_sn_saveteam = "Save Team";
$l_sn_deletepersonal = "Fshije Personale";
$l_sn_addpersonal = "Add Personale";
$l_sn_savepersonal = "Save personale";
$l_sn_editpersonal = "Artikullin";
$l_sn_editteam = "Edit Team";

$l_sn_hdsector = "Sektori";
$l_sn_hdtype = "Lloji";
$l_sn_hdowner = "Pronari / Team";
$l_sn_hdplanets = "Planetet";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Miniera";
$l_sn_hdscanfrom = "Scan Nga";
$l_sn_hddetail = "Detail";
$l_sn_hddate = "Data / Koha";
$l_sn_hddelete = "Fshij";
$l_sn_hdteam = "Skuadra";
$l_sn_view = "Shikimi";
$l_sn_no = "Jo";
$l_sn_yes = "Po";
$l_sn_nonotes = "Nuk ka sektor Shënime Found";

?>
