<?php
$l_warp_linkto = "Links të çojë nga ky sektor në";
$l_warp_nolink = "Nuk ka lidhje nga ky sektor.";
$l_warp_query = "Çfarë sektori do të dëshironit të krijoni një lidhje për të?";
$l_warp_oneway = "Një kalim?";
$l_warp_dest = "Alternuar, ju mund të shkatërrojë një lidhje të sektorit.";
$l_warp_destquery = "Çfarë sektori do ju dëshironi të hiqni një lidhje për të?";
$l_warp_bothway = "Dy-mënyra";
$l_warp_create = "Krijo një lidhje përkul në mes sektorit:";
$l_warp_andsector = "dhe Sektori:";
$l_warp_distance = "me një distancë prej";
$l_warp_lightyears = "vite dritë";
$l_warp_delete = "Delete Lidhje e prish mes sektorit:";
$l_warp_costcreate = "Kostoja për të krijuar:";
$l_warp_costdelete = "Kosto të fshini:";
$l_warp_costenergy = "Energji e nevojshme:";
$l_warp_twoerror = "Duke përdorur një Editor Warp për të krijuar një lidhje me dy rrugë për të sektorit [target_sector] nuk është i lejuar.";
?>
