<?php
$l_warp_cantsame = "Ju nuk mund të krijoni një lidhje kur burimi është i njëjtë si destinacion.";
$l_warp_twoerror = "Duke përdorur një Editor Warp për të krijuar një lidhje me dy rrugë për të sektorit [target_sector] nuk është i lejuar.";
$l_warp_sectex = "Nuk mund të krijojnë lidhje prish nga sektori i tanishëm - që do të kalojë maksimumin prej $ link_max per sektorin.";
$l_warp_linked = "Sektori i synuar ([target_sector]) tashmë ka një lidhje nga ky sektor.";
$l_warp_coneway = "Lidhje krijoi një mënyrë për të";
$l_warp_ctwoway = "Lidhje e krijuar për të dhe nga";
$l_warp_nomoney = "Ju nuk keni kredi të mjaftueshme për të krijuar lidhje prish.";
$l_warp_noenergy = "Ju nuk keni energji të mjaftueshme për të krijuar lidhje prish.";
?>
