<?php
$l_profile_title = "Profili Regjistrimi";
$l_profile_notenabled = "Profilet nuk janë të aktivizuara në këtë server.";
$l_profile_registered = "Ky lojtar është regjistruar tani me Server Profilin Master.";
$l_profile_nomatch = "Nuk mund të përputhet një profil në Server Profilin Master me emrin dhe fjalëkalimin server hyri.";
$l_profile_tryagain = "Për të futur emrin tuaj profilin lojtar dhe fjalë-kalimin server përsëri klikoni";
$l_profile_name = "Profili Emër Player";
$l_profile_password = "Profili Server Fjalëkalimi";
$l_profile_bannedserver = "Ky server nuk lejohet që të dorëzojë informatat që profilin Server Profilin Master.";
$l_profile_bannedplayer = "Ju keni qenë ndaluar nga Server Profilin Master dhe mund të mos regjistrohen lojtarë.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Ky <u><b>server</b></u> require çdo lojtar të ri të ketë një profil të regjistruar. Ju nuk do të lejohet të krijojë një lojtar të ri nëse ju keni një profil të regjistruar.";
$l_profile_updated = "Your template, shoutbox dhe lajme zvarritje parametrat globale janë përditësuar në Server Master Profil. Këto settings automatikisht do të përdoret kur ju regjistroheni profilin tuaj për çdo lojë.";

?>
