<?php
$l_md_title = "Mbrojtëse Sektori";
$l_md_invalid = "Invalid mbrojtje Sektori";
$l_md_nolonger = "Sektorin e mbrojtjes zgjedhur nuk është më atje.";
$l_md_you = "ju";
$l_md_bmines = "Your trarëve shkatërruar";
$l_md_msgdownerb = "[name] shkatërruar [mines] minave në sektorin [sector].";
$l_md_retr = "Ju retrieved";
$l_md_consist = "Ky sektor mbrojtja përbëhet nga [qty] [type] pronësi nga [owner].";
$l_md_youcan = "Ju mund";
$l_md_retrieve = "Rifitoj";
$l_md_attack = "Sulmi";
$l_md_attdef = "Sulmi mbrojtëse sektorit. Gjitha luftëtarët sektor do të hakmerret.";
$l_md_noturn = "Ju nevojitet të paktën një të kthehet.";
$l_md_nothere = "Ju duhet të jetë në sektorin e njëjtë si mbrojtëse sektor.";
$l_md_notyours = "Veprimi nuk lejohet. Ata mbrojtëse sektor nuk i përkasin juve.";
$l_md_yours = "Ju nuk mund të sulmit mbrojtëse tuaj sektor.";
?>
