<?php
$l_opt2_title = "Save Options";
$l_opt2_passunchanged = "Fjalëkalimi kishte mbetur e pandryshuar. <BR><BR>";
$l_opt2_srcpassfalse = "Original fjalëkalim i gabuar. Fjalëkalimi kishte mbetur e pandryshuar. <BR><BR>";
$l_opt2_newpassnomatch = "Fjalëkalimi fusha të reja nuk përputhen. Fjalëkalimi kishte mbetur e pandryshuar. <BR><BR>";
$l_opt2_passchanged = "Fjalëkalimi u ndryshua. <BR><BR>";
$l_opt2_passchangeerr = "Error fjalekalimin ndryshuar <BR><BR>";
$l_opt2_userintup = "User interface përcaktimit të updated. <BR><BR>";
$l_opt2_userintfail = "Failed to update interface përcaktimit të përdoruesit. <BR><BR>";
$l_opt2_chlang = "Gjuha ka qenë vendosur në [lang]. <p>";
$l_opt2_chtemplate = "Template ka qenë vendosur në [template]. <p>";
$l_opt2_dhtmlup = "Html dinamike përcaktimit të updated. <BR><BR>";
$l_opt2_dhtmlfail = "Failed to update përcaktimit të html dinamike. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname ndryshuar të [name]. <BR><BR>";
$l_opt2_playernamechanged = "Emri Player Changed to [name] dhe [amount] kredite zbritet nga llogaria juaj anije. <BR><BR>";
$l_opt2_mapwidth = "Lokale dhe Galaxy Harta Width:";
?>
