<?php
$l_opt_title = "Zgjidh një Avatar";
$l_opt_errorsize = "Error: image juaj nuk duhet të jetë më e madhe se 64x64 piksela në madhësi.";
$l_opt_errortype = "Error: Image duhet të jetë JPG, GIF ose PNG";
$l_opt_errornographic = "Gabim: nuk ka grafik të zgjedhura.";
$l_opt_currentavatar = "Avatar juaj aktual";
$l_opt_uploadavatar = "Upload an Avatar";
$l_opt_directory = "Zgjidhni Avatar Directory";
$l_opt_change = "Change Directory";
$l_opt_select = "Zgjidhni Avatar";
$l_opt_inuse = "Gjitha Avatars në këtë dosje janë në përdorim.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
