<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Mirë se vini në Kazino, ne aktualisht ofrojnë këto Lojëra dhe objektet";
$l_casino_option = "&quot;Dhomat";
$l_casino_detail = "&quot;Përshkrimi";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;Së pari Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Sigurimet";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobi";
$l_split = "Thyerja";
$l_credits = "Kredite";
$l_yourbet = "&quot;Bet juaj";
$l_nobet = "&quot;Bast juaj ka tejkaluar kufirin e kreditit tuaj, ju lutem bast përsëri.";
$l_dealerwins = "Tregtari i fiton!";
$l_dealerbust = "Bust Dealer!";
$l_dealerloses = "Tregtari humbet!";
$l_dealerblackjack = "Blackjack Dealer!";
$l_push = "Push";
$l_playerwins = "&quot;Lojtari fiton!";
$l_playerbust = "&quot;Shkatërron bandën Player!";
$l_playerloses = "&quot;Player humbet!";
$l_playerblackjack = "&quot;Player BlackJack!";
$l_place_bet = "&quot;Vendi bast tuaj";
?>
