<?php
$l_footer_one_player_on = "Nuk ka 1 miq lojtar.";
$l_footer_players_on_1 = "Ka";
$l_footer_players_on_2 = "Lojtaret online:";
$l_footer_until_update = "sekonda deri update ardhshëm.";
$l_footer_no_players_on = "Nuk ka online lojtarë.";

$l_footer_news = "Local FNN Lajme";
$l_footer_title = "Tregtarët Alien Assault";
$l_footer_help = "për ndihmë në lidhje me këtë faqe.";
$l_footer_click = "Kliko";

$l_footer_open_slots = "Maksimale Online:";
$l_footer_onlinereset = "Player Online Koha Reset në";
$l_footer_onlinecountdown = "Player Online Koha Countdown:";
?>
