<?php
$l_att_title = "Sulmi Ship";
$l_att_notarg = "Synuar jo në këtë sektor.";
$l_att_noturn = "Ju duhet të paktën një të kthehet për të sulmuar.";
$l_att_noatt = "Sulmuar dikë në këtë sektor nuk është e lejuar.";
$l_att_flee = "Synuar nga maneuvered ju!";
$l_att_ewd = "Synimi i angazhuar një pajisje prish jashtëzakonshme kur sulmuan!";
$l_att_att = "Sulmuar";
$l_att_beams = "Rreze Shkëmbim";
$l_att_torps = "Torpedo Shkëmbim";
$l_att_fighters = "Luftëtar Shkëmbim";
$l_att_lost = "i humbur";
$l_att_ylost = "Ju humbur";
$l_att_sdown = "&#39;s mburoja janë poshtë!";
$l_att_ydown = "Mburojat tuaja janë poshtë!";
$l_att_shits = "&#39;s mburoja janë goditur për";
$l_att_yhits = "Mburojat tuaja janë goditur për";
$l_att_dmg = "dëm";
$l_att_sarm = "&#39;s forca të blinduara thyer!";
$l_att_yarm = "Forca të blinduara juaj është thyer!";
$l_att_ashit = "&#39;s forca të blinduara është goditur për";
$l_att_ayhit = "Forca të blinduara juaj është goditur për";

$l_att_efhit = "&#39;s luftëtarë të shkatërruar.";
$l_att_yfhit = "e luftëtarëve tuaj janë shkatërruar.";
$l_att_ethit = "&#39;s silurët janë shkatërruar.";
$l_att_ythit = "e juaj silurët janë shkatërruar.";
$l_att_of = "i";
$l_att_lostt = "humbur të gjitha silurët.";
$l_att_ylostt = "Ju humbur të gjitha silurët.";

$l_att_lostf = "humbur të gjithë luftëtarët.";
$l_att_ylostf = "Ju ka humbur të gjithë luftëtarët.";
$l_att_sdest = "&#39;s anije ka qenë shkatërruar.";
$l_att_espod = "Një pod ikur u nisën!";
$l_att_ysalv = "Ju salvaged [ship_salvage_rate]% të anijes për [ship_salvage] kredi. <BR> Vlerësimi i juaj u ndryshua nga pikat [rating_change].";
$l_att_andused = "dhe përdorur";
$l_att_stilship = "Ju nuk destory [name] &#39;s anije.";
$l_att_atyou = "sulmuar ju";
$l_att_and = "dhe";
$l_att_yshiplost = "Anija juaj është shkatërruar!";
$l_att_salv = "[name] salvaged [ship_salvage_rate]% të anijes për [ship_salvage] credits";
$l_att_loosepod = "Për fat të mirë ju keni një mbulesë shpëtuar!";

$l_att_tnobeams = "seams të jetë nga të energjisë rreze.";
$l_att_tnobeamsf = "seams të jetë jashtë energji dhe rreze nuk mund sulm luftëtarët tuaj.";
$l_att_tnobeamst = "seams të jetë jashtë energji dhe rreze nuk mund sulm silurët tuaj.";
$l_att_tfnoattack = "nuk është dërguar ndonjë luftëtarëve për të sulmuar anijen tuaj.";
$l_att_tnotorps = "duket të jetë nga silurët.";

$l_att_anobeams = "Ju keni konsumuar anijet energjinë rreze.";
$l_att_anobeamsf = "Ju keni konsumuar energji anijet tuaj rreze dhe nuk mund sulm luftëtarët e armikut.";
$l_att_anobeamst = "Ju keni konsumuar energji anijet tuaj rreze dhe nuk mund të sulmit armik silurët.";
$l_att_anofighters = "Anija juaj ka shpenzuar pa sukses të gjitha luftëtarët e availible.";
$l_att_anotorps = "Ju keni lodhur silurët tuaj availible.";
$l_att_imtitle = "Anije Sipas Attack";
$l_att_imbody = "është sulmuar anije tuaj.";

$l_att_luckybeams = "Armik trarëve mbingarkoj inflicting";
$l_att_luckyfighters = "Luftëtarët armik të bëjë një surprizë e ndriçimit dhe të shkaktojë sulm";
$l_att_luckytorps = "Armik silurët shkaktoj një efekt Cascading duke shkaktuar dëm";
$l_att_luckytimes = "herë dëm normale!";
?>
