<?php
$l_ze_title = "Edit Zona";
$l_ze_notowner = "Ju nuk jeni pronar i kësaj zone në mënyrë që ju nuk mund ta redaktojnë.";
$l_ze_name = "Emri Zona";
$l_ze_allow = "Lejoj";
$l_ze_attacks = "Lejo sulmuar anijet e tjera";
$l_ze_genesis = "Të lejojë krijimin e planeteve të reja";
$l_ze_return = "të kthehet në informacion zonë faqe";
$l_ze_saved = "Ndryshimet juaja janë ruajtur.";
$l_ze_namematch = "GABIM: Emri Zona ju ofrohet është e ngjashme ose ndeshjet e një emrin Zona ekzistues.";
?>
