<?php
// port.php port_purchase.php
$l_trade = "Tregti";
$l_title_port = "Port Trading";
$l_title_trade = "Commodities Trading";
$l_sector_war = "Embargo Luftës";
$l_war_info = "Lufta është e ndezur në këtë sektor. Ju nuk mund të arrihet përmes portit të gjitha forcat armiqësore.";
$l_no_trade = "Tregtisë ndaluar";
$l_no_trade_out = "Tregtare në këtë port nuk është e lejuar për të jashtmit";
$l_no_trade_info = "Tregtare në këtë port nuk është e lejuar";
$l_buying = "Blerja";
$l_selling = "Shitja";
$l_commodity = "Commodity";
$l_amount = "Shuma";
$l_price = "Çmimi";
$l_buy = "Blej";
$l_sell = "Shes";
$l_trade_st_info = "Ju keni [free_holds] ngarkesë bosh mban, mund të bartin [free_power] njësi të tjera të energjisë, dhe kanë [credits] credits.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Kredi Jo mjaft";
$l_creds_to_spend = "Ju keni [credits] kredi për të shpenzuar.";
$l_cost = "Kosto";
$l_avail = "I disponueshëm";
$l_profit = "Fitimi";
$l_current = "Aktual";
$l_current_level = "Current Niveli";
$l_current_qty = "Sasitë aktuale";
$l_max = "Max";
$l_ifyouneedmore = "Nëse keni nevojë për më shumë që mund të kenë [igb]";
$l_ifyouneedplan = "Hyrje dhe përdorim i planetit";
$l_igb_term = "IGB Bankar Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Unlimited";
$l_full = "Plot";
$l_equipped = "Pajisur";
$l_n_a = "n / a";
$l_item = "Artikulli";
$l_totalcost = "Kostoja totale";
$l_would_dump = "Nëse ju dëshironi ta linte të gjitha kolonistët tuaj këtu, klikoni";
$l_noport = "Nuk ka asnjë port këtu!";
$l_trade_turnneed = "Ju duhet të paktën një nga ana e të tregtisë në një port ose planet.";
$l_returnto_port1 = "këtu";
$l_returnto_port2 = "Click [port_link] për kthim në menu portit.";
$l_notenough_cargo = "Ju nuk keni mjaft ngarkesë falas mban për mallrat që dëshironi të blini.";
$l_notenough_power = "Ju nuk kanë mjaft pushtet për hapësirë të lirë të energjisë që ju dëshironi të blini.";
$l_notenough_credits = "Ju nuk keni kredi të mjaftueshme për të përfunduar transaksionin.";
$l_notenough_turns = "Ju nuk keni mjaft të kthehet për të përfunduar transaksionin.";
$l_trade_result = "Rezultatet për këtë tregti";
$l_trade_complete = "Tregtisë përfunduar";
$l_trade_upgraded = "Upgraded to nivel";
$l_trade_added = "shtuar";
$l_trade_installed = "instaluar";
$l_port_bounty = "Ju nuk mund të kenë një port të veçantë, ndërsa ju keni një dhuratë për ju vendosur nga Federata. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Ju nuk keni credtis të mjaftueshme për të paguar mirat e [amount] credits. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "IGB ka lëshuar një Lockdown anije në llogarinë tuaj për shkak të një pagese në fund të kredisë. Ju nuk mund të tregtisë në një port të veçantë deri sa ju paguani mbrapa kredisë.";
$l_port_returntospecial = "për t&#39;u kthyer në depo për furnizim.";
$l_toprobemenu = "për të shkuar në menynë hetim.";
$l_ports_shiplimit = "Minimum klasës anijes në malin pajisje:";
$l_ports_needrepair = "Riparimi";

$l_ports_needcredits = "Ju nuk keni kredi të mjaftueshme për këtë transaksion. Kosto totale është";
$l_ports_needcredits1 = "kredi dhe nuk ke";

$l_ports_tradeforbidden = "Tregtisë ndaluar";
$l_ports_nooutsiders = "Tregtare në këtë port nuk është e lejuar për të jashtmit.";

$l_bought = "Ju blerë";
$l_sold = "Ju shitur";
$l_notenough_commodity = "Ju nuk keni mjaft [commodity] për të përfunduar transaksionin.";
$l_exceed_commodity = "Numri i [commodity] tejkalon furnizimin / kërkesën.";
$l_port_shiptoolarge = "Anija juaj është shumë e madhe për të tregtuar në këtë port.";

$l_port_hold_unit = "Mban për njësi";


$l_port_welcome = "Port [sectorname] player [player]";
$l_port_amountforsale = "Port ka [amount] njësitë e [commodity] për shitje në [credits] kredi për njësi.";
$l_port_holdsperunit = "[holds] ngarkesë mban kërkuar për njësi.";
$l_port_howmanypurchase = "Njësi Sa [commodity] dëshironi të blini?";
$l_port_unitstobuy = "Njësi të blini";
$l_port_shipcarryingbuy = "Anija juaj është që transportonte [shipunits] njësitë e [commodity]. Ju mund Blerje [buyunits] njësi me hapësirë të mbajë mallra në dispozicion.";
$l_port_howmanysell = "[amount] njësitë e [commodity] @ [credits] kredi për njësi.";
$l_port_unitstosell = "Njësi të shesë";
$l_port_perform = "Kryen Transaction";
$l_port_cargoholds = "Ngarkesë mban";

?>
