<?php
$l_gns_title = "Use Device Zanafilla";
$l_gns_turn = "Ju duhet të paktën një të kthehet për të përdorur një pajisje gjenezë.";
$l_gns_onplanet = "Ju nuk mund të përdorni këtë pajisje, ndërsa në sipërfaqe planetit.";
$l_gns_full = "Ky sistem diellor është tashmë e plotë.";
$l_gns_planetex = "Nuk është tashmë një planet në këtë sektor.";
$l_gns_nogenesis = "Ju nuk keni asnjë pajisje gjenezë.";
$l_gns_forbid = "Krijimi i një planet në këtë sektor nuk është e lejuar.";
$l_gns_bforbid = "Bazat në këtë sektor janë të ndërhyrë me pajisjen tuaj gjenezë. Krijimin Planeti nuk është e mundshme.";
$l_gns_pcreate = "Planet e krijuar.";
$l_sgns_title = "Përdorimi Sektori Zanafilla Device";
$l_sgns_pcreate = "Sektori [name] e krijuar.";
$l_sgns_nogenesis = "Ju nuk keni asnjë pajisje gjenezë sektor.";
$l_sgns_forbid = "Krijimi i një wormhole gjenezë sektori në këtë sektor nuk është e lejuar.";
$l_sgns_forbid1 = "Krijimi i një gjenezë sektori wormhole një Sektori i Federatës nuk është e lejuar.";
$l_sgcreate = "Create New Sektori Sektori Zanafilla";
$l_sgcreatens = "Create New Sektori Zanafilla Link prapa në hapësirë i njohur";
$l_sgns_forbid2 = "Më shumë se [limit] Lidhje në sektorët e SP nuk janë të lejuara.";
$l_sgns_forbid3 = "Nuk mund të krijojnë lidhje Sektori Zanafilla prish nga sektori i tanishëm - që do të kalojë maksimumin e [limit] për sektor.";
$l_sgns_nocredits = "Ju nuk keni kredi të mjaftueshme për të krijuar një sektor të ri.";
$l_sgns_shipcredits = "Kredi mbi anije:";
$l_sgns_createcost = "Kosto për krijimin e sektorit të ri:";
$l_sgns_complete = "Normale Hapësirë Link Complete";
$l_sgns_sectorname = "Futni emrin Sektori:";
$l_gns_max_unbased_planets = "Federata nuk do të lejojë krijimin e planeteve deri sa të keni më pak se [max_unbased_planets] planeteve unbased.";

?>
