<?php
$l_chf_youretreatback = "Ju tërheqje mbrapa për vendndodhjen tuaj të mëparshëm";
$l_chf_movefailed = "Move dështuar.";
$l_chf_thefightersdetectyou = "Luftëtarëve të zbuluar ju!";
$l_chf_therearetotalfightersindest = "Ka [chf_total_sector_fighters] UÇK-së në sektorin tuaj destinacion.";
$l_chf_youcanretreat = "<B>Tërheqje</b> - A do të kushtojë kthehet ekstra.";
$l_chf_inputfight = "<B>Fight</b> - Ju duhet të mundur të gjithë luftëtarët për të hyrë në sektor.";
$l_chf_inputcloak = "<B>Mantel</b> - Përdorni pajisjen tuaj cloaking dhe të përpiqemi për të shmangur luftëtarëve.";
$l_chf_go = "Shkoj";
$l_chf_inputrun = "<B>Sulmi dhe Run</b> - Ju bëni një sulm drejtuar rrufetë dhe tërheqje. Por ju mund të marrë disa dëme gjatë tërheqje.";
?>
