<?php
$l_warp_unlinked = "Sektori i synuar ([target_sector]) nuk ka një lidhje nga ky sektor.";
$l_warp_forbidtwo = "Duke përdorur një Editor Warp për të hequr një lidhje dy-rrugë për të sektorit [target_sector] nuk është i lejuar.";
$l_warp_removed = "Link hequr të";
$l_warp_removedtwo = "Link hiqen për dhe nga";
$l_warp_nomoney = "Ju nuk keni kredi të mjaftueshme për të fshini Lidhje prish.";
$l_warp_noenergy = "Ju nuk keni energji të mjaftueshme për të fshini Lidhje prish.";
?>
