<?php
$l_autoroute_missingwarp = "Warplink tjetër është humbur në këtë sektor. Masa përkul nd?rpre.";
$l_autoroute_SDabort = "Move Aborted mbrojtëse për shkak të Sektorit në sektor.";
$l_autoroute_turns = "Zbritur [triptime] Kthehet dhe lëvizur të [targetlink]";
$l_autoroute_noturns = "Ju jeni nga të kthehet.";
$l_autoroute_title = "Auto Rrugët";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination = "Auto Route Destinacioni";
$l_autoroute_warps = "Auto Route Warps";
$l_autoroute_deleteroute = "Fshije Route";
$l_autoroute_info = "Klikoni në Sektorin Fillim të Realspace për këtë sektor dhe të fillojnë warping në sektorin destinacion.";
$l_autoroute_delete2 = "Fshije Rrugët";
$l_autoroute_noroutes = "Nuk Rrugët Auto";
$l_autoroute_createroute = "Create New Auto Route";
$l_autoroute_deleted = "Auto Rrugët fshihet.";
$l_autoroute_return = "Kthehuni tek Auto Route Menu klikoni";
$l_autoroute_created = "Auto Route është krijuar.";
$l_autoroute_realmove = "Masa Realspace ndaj sektorit";
$l_autoroute_warpmove = "Masa Warp në sektorin e ardhshëm";
$l_autoroute_warpfinal = "Masa Warp në sektorin e fundit";
$l_autoroute_editname = "Edit Name";
?>
