<?php
///SPIES
$l_spy_title = "Spiun Menu";
$l_spy = "Spiunëve";
$l_spy_disabled = "Spiunë janë të paaftë!";
$l_spy_noturn = "Ju duhet të paktën një të kthehet për të dërguar një spiun në një planet.";
$l_spy_notonboard = "Ju nuk keni asnjë spiunë në bord.";
$l_spy_ownplanet = "Ju nuk mund të dërgoni një spiun për të planetit tuaj.";
$l_spy_unownedplanet = "Ju nuk mund të dërgoni një spiun për të planetit pa pronar.";
$l_spy_planetfull = "Nuk lejohet tashmë [max] spiunëve në këtë planet.";
$l_spy_sendtitle = "Dërgimi i një spiun [spyID] të planetit: <BR> Misionin spiun Zgjidh&#39;s:";
$l_spy_type1 = "Spiun vepron vetëm mbi këtë planet.";
$l_spy_type2 = "Spiun përpiqet të depërtojnë një anije e cila kryen një transferim planetar.";
$l_spy_type3 = "Spiun përpiqet të depërtojnë një anije e cila kryen një transferim planetar dhe pastaj depërtoj në një tjetër planet.";
$l_spy_sendbutton = "Send to planetit";
$l_spy_sendsuccessful = "Spiun juaj infiltrates planetit dhe pret momentin e duhur për të filluar veprime.";
$l_spy_sendfailed = "Sensore Planet e zbuluar spiun tuaj, sepse pajisja mantel juaj nuk mund të mbulojnë atë. Spiun juaj është vrarë.";
$l_spy_noturn2 = "Ju duhet të paktën një të kthehet prapa për të thirrur një spiun.";
$l_spy_confirm = "A jeni i sigurt se doni te telefononi përsëri spiun juaj [spyID]?";
$l_spy_cleanupplanet = "për të pastruar se planetit nga spiunë armik.";
$l_spy_cleanupship = "Nëse ju doni të pastër deri anije nga spiunë armikut tuaj, kliko";
$l_spy_yourspies = "Spiunë juaj në këtë planet";
$l_spy_sendnew = "Dërgo një spiun të ri";

$l_spy_codenumber = "Kodi";
$l_spy_job = "Puna";
$l_spy_percent = "Përqindje";
$l_spy_move = "Lëvizja";
$l_spy_action = "Veprimi";
$l_spy_shipowner = "Anije Owner";
$l_spy_shipname = "Emri anijes";
$l_spy_shiptype = "Anije Klasa";
$l_spy_shiplocation = "Anije Location";
$l_spy_planetowner = "Planet Owner";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sektori";

$l_spy_moves['none'] = "A nuk lëvizin";
$l_spy_moves['toship'] = "Për anije";
$l_spy_moves['toplanet'] = "Për planet";

$l_spy_comeback = "Call mbrapa";
$l_spy_nospieshere = "Ju nuk keni asnjë spiunëve në këtë planet!";
$l_spy_transferred = "spiunë transferuar";
$l_spy_backonship = "Spiuni është tani në anije tuaj.";
$l_spy_backfailed = "Call mbrapa dështuar.";
$l_spy_changetitle = "Ndryshimi spiun [spyID] pronave:";
$l_spy_occupied = "Spiun juaj [spyID] në të punësuar si një punë [job], me qind [percent].";
$l_spy_dismiss = "Shkarkojë spiun?";
$l_spy_changebutton = "Ndryshimi";
$l_spy_changejob = "Ndryshimi i punës ose i Lëvizjes";
$l_spy_linkback = "për të shkuar në menynë spiun.";
$l_spy_changed1 = "Lëvizja ndryshuar.";
$l_spy_changed2 = "Spiun hodhi poshtë dhe lëvizjen e tij ndryshoi.";
$l_spy_changefailed = "Ndryshimi dështuar.";
$l_spy_cleanupplanettitle = "Pastrimi planetit tuaj nga spiunët armikut:";
$l_spy_notyourplanet = "Kjo nuk është planet tuaja.";
$l_spy_cleanuptext[1] = "Cleanup shpejte. Përdor [creds] kredi dhe [turns] kthehet.";
$l_spy_cleanuptext[2] = "Cleanup mirë. Përdor [creds] kredi dhe [turns] kthehet.";
$l_spy_cleanuptext[3] = "Cleanup mirë. Përdor [creds] kredi dhe [turns] kthehet.";
$l_spy_cannotcleanupplanet = "Ju keni vetëm [credits] kredive në këtë planet dhe [turns] kthehet.";
$l_spy_cleanupbutton1 = "Fillimi pastrimin e planetit";
$l_spy_cleanupplanettitle2 = "Ju u kthye në Sensore tuaj për të gjetur spiunët armik në këtë planet.";
$l_spy_spyfoundonplanet = "Ju gjeti një lojtar [player] &#39;s spiun [spyID] në planetin. Ju vranë që spiun.";
$l_spy_spynotfoundonplanet = "Ju nuk gjeni ndonjë armik spiunëve në këtë planet.";
$l_spy_notenough = "Ju nuk keni kredi të mjaftueshme për të filluar ose kthehet cleanup.";

$l_spy_cleanupshiptitle = "Pastrimi anije tuaj nga spiunët armikut:";
$l_spy_notinspecial = "Ju duhet të jetë në një port Pajisje të pastër deri anije tuaj.";
$l_spy_cleanupshiptext[1] = "Cleanup shpejte. Përdor [creds] kredi dhe [turns] kthehet.";
$l_spy_cleanupshiptext[2] = "Cleanup mirë. Përdor [creds] kredi dhe [turns] kthehet.";
$l_spy_cleanupshiptext[3] = "Cleanup mirë. Përdor [creds] kredi dhe [turns] kthehet.";
$l_spy_cannotcleanupship = "Ju keni vetëm [credits] kredi dhe [turns] kthehet.";
$l_spy_cleanupbutton2 = "Fillimi pastrimin anije tuaj";
$l_spy_cleanupshiptitle2 = "Ju u kthye në Sensore tuaj për të gjetur spiunët armik në anije tuaj.";
$l_spy_spyfoundonship = "Ju gjeti një lojtar [player] &#39;s spiun [spyID] në anije tuaj. Ju vranë që spiun.";
$l_spy_spynotfoundonship = "Ju nuk gjeni ndonjë armik spiunëve në anije tuaj.";

$l_spy_infodeleted = "Message deleted";
$l_spy_infonotyours = "Nuk është mesazhi juaj.";
$l_spy_noinfo = "Spiunë juaj mbi anijet e armikut nuk kanë zbuluar asgjë ende.";
$l_spy_infotitle = "Spiunë tuaja kanë zbuluar informacion në vijim";
$l_spy_time = "Koha";
$l_spy_type = "Lloji";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Nuk është një [player] &#39;s planetin [planet] në sektorin [sector].";
$l_spy_delete = "Fshij";
$l_spy_messages = "për të parë se çfarë kanë zbuluar spiunët tuaj.";
$l_spy_defaulttitle1 = "Spiunë të anijeve armik";
$l_spy_defaulttitle2 = "Spiunë në planetet e armikut";
$l_spy_defaulttitle3 = "Spiunë në planetet tuaj";
$l_spy_defaulttitle4 = "Spiunë në anije tuaj";

$l_spy_no1 = "Ju nuk keni asnjë spiunë në anije armik.";
$l_spy_no2 = "Ju nuk keni asnjë spiunëve në planetet e armikut.";
$l_spy_no3 = "Ju nuk keni asnjë spiunëve në planetet e juaj.";
$l_spy_no4 = "Ju nuk keni asnjë spiunëve në anije tuaj.";
$l_spy_nospiesatall = "Ju nuk keni asnjë spiunë.";
$l_spy_notknown = "Panjohur";


$l_spy_trytitle = "Në këtë spiun planetit do të përpiqet të";

$l_spy_cantsendfeds = "Na vjen keq por Spies nuk mund të dërgohen në Federatën ose Pavarur Planets.";
$l_spy_cantsendteam = "Ju nuk mund të vendos Spies në një planet shokët.";
$l_spy_messagesdeleted = "Të gjitha mesazhet fshihen";
$l_spy_deleteall = "Fshij gjithë";
$l_spy_onplanet = "Spiunëve në planet";
$l_spy_menu = "për t&#39;u kthyer në spiun Menu.";
?>
