<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Hapësirë Unchartered";
$l_zname[2] = "Hapësirë Federatës";
$l_zname[3] = "Hapësirë Aleancës";
$l_zname[4] = "Zona e luftës";

$l_nova = "Nova";
$l_nova = "Nova bombë";
$l_lssd = "Anije Last seen pajisje";
$l_lss = "Anije të fundit shihet në këtë sektor";

// Common to : warpedit 1-3.php

$l_warp_title = "Përdorimi Warp Editor";
$l_warp_turn = "Ju duhet të paktën një të kthehet për të përdorur një editor prish.";
$l_warp_none = "Ju nuk keni asnjë redaktorët prish.";
$l_warp_forbid = "Duke përdorur një Editor Warp në këtë sektor nuk është e lejuar.";
$l_swarp_forbid = "Duke përdorur një Editor Warp ose nga SP sektorë nuk është e lejuar.";
$l_warp_nosector = "Sektori nuk ekziston.";

// Not yet confirmed common to multiple files:

$l_yes = "Po";
$l_no = "Jo";
$l_here = "këtu";
$l_submit = "Paraqes";
$l_reset = "Reset";
$l_all = "Të gjithë";
$l_max = "Max";

$l_trade = "Tregti";
$l_ore = "Ore";
$l_commodity = "Commodity";
$l_commodities = "Commodities";
$l_organics = "Organics";
$l_goods = "Mallra";
$l_energy = "Energjisë";
$l_colonists = "Kolonive";
$l_credits = "Kredite";
$l_units = "njësi";
$l_special = "Speciale";
$l_upgrade_ports = "Upgrade";
$l_device_ports = "Pajisjet";
$l_spacedock = "Spacedock";
$l_casino = "Kazino";
$l_dig = "Personalitete";
$l_spy = "Spiunëve";

$l_cargo = "Ngarkesë";
$l_fighters = "Fighters";
$l_mines = "Miniera";
$l_torps = "Silurët";

$l_none = "Asnjë";
$l_unnamed = "Unnamed";
$l_name = "Emri";
$l_unowned = "Pa pronar";
$l_unknown = "Panjohur";
$l_clickme = "Kliko këtu";
$l_player = "Player";
$l_ship = "Anija";
$l_ships = "Ships";
$l_set = "vendos";
$l_realspace = "Realspace";
$l_armorpts = "Pika Armor";
$l_links = "Links";
$l_login_email = "E-mail Address:";
$l_add = "Shtoj";
$l_teamforum = "Team Forum";
$l_teamships = "Team Anije";
$l_tutorial = "Tutorial / Help";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Copëra";
$l_localmap = "Local Map";
$l_arm_weap = "Forca të blinduara dhe Armët";
$l_3dmap = "3D Galaxy Harta";

$l_sectormissile = "Sektori i raketave";
$l_spacebeacon = "Hapësirë Beacon";
$l_spaceprobes = "Hapësirë heton";
$l_warpeditors = "Editors Warp";
$l_genesistorps = "Zanafilla silurët";
$l_sgtorps = "SG silurët";
$l_minesfighters = "Miniera / Fighters";
$l_ewarp = "Urgjencës Warp";
$l_reports = "Raportet";
$l_shipinfo = "Anije Info";
$l_sectornotes = "Sektori Shenimet";
$l_maps = "Maps";
$l_messages = "Messages";
$l_shiptype = "Anije Tipi";
$l_help = "Ndihma";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Mbrojtëse Team";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet mbrojtëse";
$l_changeproduction = "Ndryshimi Prodhimi";
$l_galacticarm = "Krah Galaktik";

$l_armor = "Armor";
$l_news_none = "Na vjen keq, sot nuk ka lajme.";

$l_ranks_good = "Mirë";
$l_ranks_evil = "I keq";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zona është tani një zonë lufte!";
$l_global_nzone = "Zona është një zonë neutrale.";
$l_global_team = "Zona tani i takon të ekipit";
$l_global_player = "Zona tani i takon lojtar";
$l_global_nochange = "Zona e pronësisë nuk ka ndryshim";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Astronaut Rekrutoni";
$l_insignia_name[1] = "Astronaut Apprentice";
$l_insignia_name[2] = "Astronaut";
$l_insignia_name[3] = "Petty Officer Klasa e tretë";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer të klasit të parë";
$l_insignia_name[6] = "Shefi i Petty Officer";
$l_insignia_name[7] = "Shefi i lartë Petty Officer";
$l_insignia_name[8] = "Master Shefi Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Toger Junior Grad";
$l_insignia_name[11] = "Toger";
$l_insignia_name[12] = "Toger Komandanti";
$l_insignia_name[13] = "Komandanti";
$l_insignia_name[14] = "Kapiteni";
$l_insignia_name[15] = "Rear Admiral (gjysma e ulët)";
$l_insignia_name[16] = "Rear Admiral (gjysma e sipërme)";
$l_insignia_name[17] = "Vice Admiral";
$l_insignia_name[18] = "Admirali";
$l_insignia_name[19] = "Admirali i flotës";

$l_main_title = "Menuja";
$l_main_warpto = "Shtrembërim të";
$l_main_autoroute = "Autoroute të";
$l_main_rs_to = "RSMove të";
$l_main_other = "Tjetër";
$l_main_shipyard1 = "Kantjerin";
$l_main_shipyard2 = "Hyrje";
$l_traderoutes = "Rrugët e Tregtisë";
$l_trade_control = "Tregtisë Kontrollit";
$l_youhave = "Keni";
$l_turns_used = "Kthehet të përdorura:";
$l_turns_have = "Kthen në dispozicion:";
$l_score = "Vota:";
$l_sector = "Sektori";
$l_help = "Ndihma";
$l_faq = "FAQ";
$l_feedback = "Reagimi";
$l_forums = "Forume";
$l_logout = "Logout";
$l_commands = "Komandat";
$l_command_no = "Komanda e jo në dispozicion.";
$l_devices = "Pajisjet";
$l_planets = "Planetet";
$l_log = "Identifikohu";
$l_sector_def = "Mbrojtëse Sektori";
$l_defense = "Mbrojtëse";
$l_read_msg = "Lexo Messages";
$l_send_msg = "Dergoni Mesazhe";
$l_rankings = "Rankings";
$l_teams = "Ekipe";
$l_ohno = "Self-Destruct";
$l_options = "Options";
$l_navcomp = "Nav Computer";
$l_incompletemove = "Ju nuk e keni përfunduar veprim tuaj të mëparshëm.";
$l_clicktocontinue = "Kliko këtu për të vazhduar";
$l_toplanetmenu = "për të shkuar në planetin menu.";
$l_nonexistant_pl = "Në një jo-ekzistente planetit?";
$l_abord = ", Bordin";
$l_messages_wait = "Messages duke pritur për ju.";
$l_no_warplink = "Nuk ka lidhje prish";
$l_scan = "skanim";
$l_fullscan = "Full scan";
$l_port = "Port";
$l_tradingport = "Port Trading";
$l_planet_in_sec = "Planeteve në sektorin";
$l_ships_in_sec = "Anije të tjera në sektorin e";
$l_sector_0 = "Nuk ka trafik shumë të Sol se ju nuk mund të izolojnë edhe anije të tjera!";
$l_map = "Harta";
$l_probe = "Hetimet";
$l_autotrade = "Autotrades";
$l_onboard = "një bord";
$l_classship = "anije klasë";
$l_traveled = "udhëtoi për në sektorin e";
$l_max_planets = "Planetet maksimale habital";
$l_block_msg = "Blloku Messages";
$l_sectorinfo = "Sektori Info";
$l_add_note = "Shto Shënim";
$l_view_note = "Shikimi";
$l_notes = "Shenimet";
$l_global_limitreached = "Ju keni arritur limit për sasinë e kohës që ju keni të drejtë të jetë online çdo ditë. Log in përsëri nesër pas mesnate.";
$l_onlinetimeleft = "Time Remaining:";
$l_planetmax = "Planetar Maksimumi:";
$l_storedshipreport = "Anije ruajtur";
$l_global_chat = "Global Chat";
$l_team_chat = "Ekipi Chat";
$l_fedinfo = "Federata Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Lobi tregtari i";

$l_common_prev = "Previous";
$l_common_next = "Next Page";
$l_common_totalpages = "Total Pages";
$l_common_selectpage = "Seleksiono Faqe:";
$l_common_page = "Page:";
$l_templatechange = "Dëshironi të mbani këtë Template?";

$l_im_fed_bounty = "Federata ka vendosur një dhuratë për ju për të sulmuar një lojtar të tillë të ulët rendit. Federata do të sulmojë anije tuaj mbi një bazë të rregullt deri sa ju paguani te mirat e juaj. Ju mund të paguaj mirat tuaj në çdo Port Upgrade ose Spacedock.";
$l_im_fed_bounty_title = "Federata vendosur një dhunti për ju!";
$l_im_alliance_bounty = "Aleanca ka vendosur një dhuratë për ju për të sulmuar një lojtar të tillë të ulët rendit. Aleanca do të sulmojë anije tuaj mbi një bazë të rregullt deri sa ju paguani te mirat e juaj. Ju mund të paguaj mirat tuaj në çdo Port Upgrade ose Spacedock.";
$l_im_alliance_bounty_title = "Aleanca vendosur një dhunti për ju!";
$l_instant_messages_waiting = "Ju keni [count] mesazhe në pritje për ju.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Mban mbushur:";
$l_hold_space_free = "Mban Empty:";
$l_port_buys = "Porti ble:";

?>
