<?php
$l_zi_title = "Zona Informacione";
$l_zi_nexist = "Kjo pjesë e hapësirës nuk ekziston!";
$l_zi_feds = "Federata";
$l_zi_traders = "Aleanca Space";
$l_zi_nobody = "Askush";
$l_zi_war = "Hapësirë Kontestimore";
$l_zi_allow = "Lejuar";
$l_zi_notallow = "Lejohet";
$l_zi_limit = "Kufizuar në pronar dhe aleatët";
$l_zi_ul = "Unlimited";
$l_zi_control = "Ju jeni në kontroll këtë zonë";
$l_zi_tochange = "për të ndryshuar ligjet e saj.";
$l_zi_owner = "Pronar Zona";
$l_zi_maxhull = "Nivelin maksimal mesatar teknologjisë së lejuar";
?>
