<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Skanera juaj nuk posedon spektër të plotë të gjatë scan aftësive.";
$l_lrs_noturns = "Ju duhet të paktën $ fullscan_cost ana (s) për të drejtuar një gamë të plotë të gjatë scan.";
$l_lrs_used = "Used";
$l_lrs_turns = "ana (s)";
$l_lrs_left = "larguar";
$l_lrs_reach = "Vendndodhjet e mëposhtme mund të arrihet nga sektori [sector]:";
$l_lrs_links = "Links";
$l_lrs_ships = "Ships";
$l_lrs_click = "Kliko për një lidhje për të lëvizur në atë sektor.";
$l_lrs_cantscan = "Can&#39;t scan sektori nga sektori i tanishëm!";
$l_lrs_zero = "Sektori 1 është mbushur me njerëz shumë të skanoni për anije!";
$l_lrs_moveto = "për të kaluar në sektorin e";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "View Log";
$l_lrs_fedjammed = "Federata është zhurma të gjitha sensor scans.";
$l_lrs_sectormissile_question = "të zjarrit të raketave sektor.";
$l_log_months = "array ( &#39;,, janar&#39;, &#39;Shkurt&#39;, &#39;Mars&#39;, &#39;Prill&#39;, &#39;Maj&#39;, &#39;Qershor&#39;, &#39;Korrik&#39;, &#39;Gusht&#39;, &#39;Shtatore&#39;, &#39;Tetore&#39;, &#39;Nëntore&#39;, &#39;Dhjetore&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;Shkurt&#39;, &#39;Mars&#39;, &#39;Prill&#39;, &#39;Maj&#39;, &#39;Qershor&#39;, &#39;Korrik&#39;, &#39;Gusht&#39;, &#39;shtator&#39;, &#39;Tetor&#39;, &#39;Nëntor&#39;, &#39;dhjetor&#39;)";
?>
