<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: ShoutBox::.";
$l_shout_public = "Publike";
$l_shout_team = "Skuadra";
$l_shout_smiles = "Smilie së";
$l_shout_else = "tjetër";
$l_shout_refresh = "Refresh";
$l_shout_close = "Mbylle dritaren";
$l_shout_saved = "Shout ruajtur!";
$l_shout_return = "Kthehuni";
$l_shout_prev = "Previous";
$l_shout_next = "Tjetër";
$l_shout_selectpage = "Select Page";
$l_shout_page = "Page:";
$l_shout_teamtitle = ".:: ShoutBox TEAM::.";
?>
