<?php
$l_mail_title = "Nofka Fjalekalimi";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Fjalëkalimi është dërguar";
$l_mail_topic = "Fjalëkalimi $ game_name";
$l_mail_message = "Ip $ Përshëndetje, \ n \ nSomeone nga adresa IP kërkuar që fjalëkalimin tuaj për $ game_name t&#39;ju dërgohet \ n \ fjalekalimin nYour është: [pass] \ n \ nThank ju \ n \ nThe ekip $ game_name web.";
$l_new_login = "për të shkuar në ekran login.";
$l_mail_failed = "Fjalëkalimi dështuar të dërgojë të";
?>
