<?php
$l_move_title = "Lëvizja";
$l_move_turn = "Ju duhet të paktën një të kthehet për të vepruar.";
$l_move_failed = "Leviz dështuar!";
$l_rs_title = "RealSpace Move";
$l_rs_whichsector = "Cili sektori do të dëshironit të arritur përmes RealSpace?";
$l_rs_insector = "Ju aktualisht në sektorin [sector] - dhe ka sektorë në dispozicion nga 1 në [sector_max].";
$l_rs_submit = "Llogaritur";
$l_rs_movetime = "Me motorët tuaj, ajo do të marrë [triptime] kthehet për të përfunduar udhëtimin.";
$l_rs_energy = "Ju do të mblidhen [energy] njësive të energjisë";
$l_rs_noturns = "Ju nuk keni mjaft të kthehet majtas, dhe nuk mund të fillojë në këtë udhëtim.";
$l_rs_engage_link = "Angazhohen";
$l_rs_engage = "Ju keni [turns] kthehet. [engage] motorët?";
$l_rs_invalid = "Ju nuk mund të realspace për këtë sektor nga këtu.";
$l_rs_ready = "Ju jeni tani në sektorin [sector]. Ju përdorur [triptime] kthen, dhe fituar [energy] njësi të energjisë.";
$l_warp_invalid = "Ju nuk mund të tërheq me litar atë sektor nga këtu.";
$l_move_unknown = "Panjohur Movetype";
?>
