<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Ju duhet të paktën një të kthehet për të skanoni një tjetër anije.";
$l_scan_ron = "Rezultatet Scan më";
$l_scan_capt = "Captained nga:";
$l_scan_arma = "Armatim:";
$l_scan_carry = "Vete:";
$l_scan_bounty = "Kjo anije ka një dhuratë totale në të prej [amount] kredi.";
$l_scan_fedbounty = "Kjo anije ka një dhuratë për atë nga Federata.";
$l_by_nofedbounty = "Sulmuar ky lojtar <B>nuk</b> do të rezultojë në Federatën vënë një dhuratë për ju.";
?>
