<?php
$l_nav_title = "Navigation Computer";
$l_nav_nocomp = "Navigation Computer nuk është në dispozicion";
$l_nav_query = "Enter sektori për të gjetur rrugën për të:";
$l_nav_pathfnd = "Rruga gjetur";
$l_nav_answ1 = "Kjo do t&#39;ju";
$l_nav_answ2 = "kthehet për të marrë në këtë sektor.";
$l_nav_proper = "Ju duhet të përmirësojë luftarakë teknologji gjirin tuaj para se luftëtarët e juaj mund të gjeni një rrugë përkul për atë distancë.";
$l_nav_autoroutename = "Fakultativ Autoroute Emri:";
$l_nav_manuallist = "Ndërtuar me dorë WarpLink Lista Autoroute";
$l_nav_warplinksleaving = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Nuk ka warplinks duke e lënë këtë sektor.";
$l_nav_warp_from = "Warp nga";
$l_nav_rs_from = "RSMove nga";
$l_nav_notinlogs = "Nuk ka të dhëna në dispozicion për këtë sektor.";
?>
