<?php
$l_md_title              = "Defensas del Sector";
$l_md_invalid            = "Defensa del Sector no correcta";
$l_md_nolonger           = "La defensa del sector seleccionada ya no está en el sector.";
$l_md_you                = "tú";
$l_md_bmines             = "Tus láseres destruyeron";
$l_md_msgdownerb         = "[name] destruyó [mines] minas en el sector [sector].";
$l_md_retr               = "Recogiste";
$l_md_consist            = "Esta defensa de sector está formada por [qty] [type] propiedad de [owner].";
$l_md_youcan             = "Puedes";
$l_md_retrieve           = "Recoger";
$l_md_change             = "Cambiar modo los cazas";
$l_md_attack             = "Atacar";
$l_md_attdef             = "Atacar las Defensas de Sector. Todos los cazas del sector tomarán represalia.";
$l_md_noturn             = "Necesitas al menos un turno.";
$l_md_nothere            = "Debes estar en el mismo sector que las defensas de sector.";
$l_md_notyours           = "Acción no permitida. Esas defensas de sector no te pertenecen.";
$l_md_yours              = "No puedes atacar tus propias defensas de sector.";
?>
