<?php
$l_autotrade_title = "Auto Traderoute Menú";
$l_autotrade_dismiss2 = "Auto Traderoutes eliminados.";
$l_autotrade_report = "Auto Traderoute Informe";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energía";
$l_autotrade_capacity = "Capacidad";
$l_autotrade_goods = "Productos Precio";
$l_autotrade_ore = "El precio del mineral";
$l_autotrade_organics = "Orgánicos de precio";
$l_autotrade_energy = "Precios de la energía";
$l_autotrade_colonist = "Precio de colonos";
$l_autotrade_credits = "Créditos comerciales";
$l_autotrade_delete = "Borrar <br> Ruta";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "N Ruta";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "créditos";
$l_autotrade_deletebutton = "Borrar";
$l_autotrade_noroute2 = "No se ha configurado ningún Traderoutes Auto.";
?>
