<?php
$l_by_title              = "Recompensas";
$l_by_noturn             = "Necesitas al menos un turno para poner o modificar una recompensa.";
$l_by_amount             = "Cantidad de Recompensa";
$l_by_place              = "Fijar recompensa";
$l_by_nobounties         = "Actualmente no hay recompensas.";
$l_by_bountyon           = "Recompensa sobre";
$l_by_placedby           = "Fijado por";
$l_by_thefeds            = "La Federación";
$l_by_cancel             = "Cancelar";
$l_by_yourself           = "No puedes fijarte a ti mismo una recompensa.";
$l_by_notenough          = "No tienes suficientes créditos  para poner una recompensa de esa cantidad.";
$l_by_toomuch            = "No puedes poner esa recompensa. La máxima recompensa permitida sobre otro jugador es de [percent] de tu valor neto";
$l_by_zeroamount         = "Las recompensas deben ser mayores de 0 créditos.";
$l_by_placed             = "La recompensa ha sido fijada.";
$l_by_nobounty           = "Esa recompensa ya no existe.";
$l_by_notyours           = "Esa recompensa no fue fijada por ti.";
$l_by_canceled           = "La recompensa ha sido cancelada.";
$l_by_action             = "Acción";
$l_by_placebounty        = "Fijar o ver recompensas.";
$l_by_moredetails        = "Haz clic en el nombre para más detalles.";
$l_by_fedbounty          = "<font color='red' size='4'><b>Atacar a este jugador provocaría que La Federación fijara una recompensa sobre ti.</b></font>";
$l_by_fedbounty2         = "<font color='red' size='4'><b>La Federación no aprueba el atacar naves mucho más pequeñas. Ha fijado una recompensa sobre ti.</b></font>";
$l_by_notexists          = "El jugador al que intentas fijar la recompensa no existe.";
$l_by_destroyed          = "No puedes fijar una recompensa sobre un jugador cuya nave ha sido destruida.";
$l_by_nofedbounty = "Usted no recibirá una recompensa si el ataque de este barco jugadores o planeta.";
$l_by_fedcollectonly = "Sólo la Federación puede recoger Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color='red' size='4'><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color='red' size='4'><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "No recibirá una recompensa si se coloca un espía en este planeta jugadores.";
$l_pay_partial = "Efectuar el pago parcial";
$l_pay_button = "Pagar";
$l_by_thealliance = "La Alianza";
$l_by_alliancecollectonly = "Sólo la Alianza puede recoger Bounty";
$l_by_bountyscan = "Bounty";
?>
