<?php
$l_shipyard_title        = "Astillero Espacial";
$l_planet                = "Planeta";
$l_ship_welcome = "Bienvenido a su astillero Planetario. Actualmente ofrecemos estos modelos a la venta.";
$l_ship_class = "Clase";
$l_ship_properties = "Propiedades de clase";
$l_ship_current = "Actual";
$l_ship_outstorage = "¡Fuera de almacenamiento de";
$l_ship_storagecost = "Costo de almacenamiento";
$l_ship_storagewarn = "Una vez que usted toma su Pioneer de almacenamiento que perderá el que se expiden en el momento de su destrucción buque inicial.";
$l_ship_levels = "Buque Componentes Niveles";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Precio";
$l_ship_turns = "Vuelve a construir";
$l_ship_purchase = "Compra";
$l_ship_stored = "Almacenados";
$l_ship_basehull = "Base del casco:";

$l_ship_averagemaxtech = "Tech Media Máximo Nivel:";
$l_ship_averagenormaltech = "Media normal Tech Nivel:";
$l_ship_averagecurrenttech = "Promedio actual Tech Nivel:";
?>
