<?php

// Confirmed common to multiple files:

$game_charset = "ISO-8859-1";

$l_zname[1] 		 = "Espacio desconocido";
$l_zname[2] 		 = "Espacio de la Federación";
$l_zname[3] = "Espacial de la Alianza";
$l_zname[4] 		 = "Zona de Guerra";

$l_nova = "Nova";
$l_nova = "Nueva bomba";
$l_lssd 		 = "Dispositivo de Ultima Nave Avistada";
$l_lss 			 = "Ultima Nave";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Usar Editor de Enlace";
$l_warp_turn		 = "Necesitas al menos un turno para utilizar un Editor de Enlace.";
$l_warp_none		 = "No tienes ningún Editor de Enlace.";
$l_warp_forbid		 = "No está permitido usar un Editor de Enlace en este sector.";
$l_warp_nosector	 = "El sector no existe.";
$l_swarp_forbid = "Mediante un editor de Warp o de sectores de SG no está permitido.";
// Not yet confirmed common to multiple files:

$l_yes 			 = "Sí";
$l_no = "No";
$l_here			 = "aquí";
$l_submit		 = "Enviar";
$l_reset		 = "Borrar";
$l_all			 = "Todo";
$l_max = "Max";

$l_trade = "Comercio";
$l_ore			 = "Minerales ";
$l_commodity = "Los productos básicos";
$l_commodities		 = "Mercancías ";
$l_organics		 = "Alimentos ";
$l_goods		 = "Bienes ";
$l_energy		 = "Energía ";
$l_colonists		 = "Colonos ";
$l_credits 		 = "Créditos";
$l_units		 = "unidades de ";
$l_special		 = "Especial";
$l_upgrade_ports	 = "Mejoras";
$l_device_ports		 = "Dispositivos";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_spy = "Espías ";
$l_dig = "Dignatarios";

$l_cargo		 = "Cargamento ";
$l_fighters		 = "Cazas";
$l_mines		 = "Minas";
$l_torps		 = "Torpedos";

$l_none			 = "Ninguno";
$l_unnamed		 = "Sin Nombre";
$l_name			 = "Nombre";
$l_unowned		 = "Sin dueño";
$l_unknown		 = "Desconocido";
$l_clickme 		 = "Haz clic aquí";
$l_player  		 = "Jugador";
$l_ship			 = "Nave ";
$l_ships		 = "Naves ";
$l_set			 = "Ajustar";
$l_realspace		 = "Hiperespacio";
$l_armorpts		 = "puntos de blindaje";
$l_links		 = "Enlaces";
$l_login_email          = "Dirección de correo electrónico:";
$l_add = "Agregar";
$l_teamforum = "Team Foro";
$l_teamships = "Equipo de los buques";
$l_tutorial = "Tutorial / Ayuda";
$l_avatar = "Avatar";
$l_teamicon = "Equipo Icon";
$l_debris = "Escombros";
$l_localmap = "Mapa Local";
$l_arm_weap = "Armadura y armas";
$l_3dmap = "Mapa 3D Galaxy";

$l_sectormissile = "Sector de misiles";
$l_spacebeacon = "Espacio Beacon";
$l_spaceprobes = "Las sondas espaciales";
$l_warpeditors = "Editores de Warp";
$l_genesistorps = "Génesis Torpedos";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Minas / Fighters";
$l_ewarp = "Emergencia Warp";
$l_reports = "Informes";
$l_ship = "Barco";
$l_sectornotes = "Notas del Sector";
$l_maps = "Mapas";
$l_messages = "Mensajes";
$l_shiptype = "Tipo de buque";
$l_help = "Ayuda";
$l_rank = "Fila";

$l_teamplanets = "Equipo de planetas";
$l_teamdefenses = "Las defensas del equipo";
$l_planetstatus = "Situación del planeta";
$l_planetdefenses = "Defensas Planet";
$l_changeproduction = "Cambio de producción";
$l_galacticarm = "Brazo Galáctico";
$l_armor = "Armor";
$l_news_none             = "Hoy no hay noticias.";

$l_ranks_good = "Bueno";
$l_ranks_evil = "Malvado";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Haz clic <A HREF=main.php>aquí</A> para volver al menú principal.";
$l_global_mlogin         ="Haz clic <A HREF=index.php>aquí</A> para volver a la pantalla de conexión.";
$l_global_needlogin      ="Debes conectarte, haz clic <A HREF=index.php>aquí</A>.";
$l_global_died           ="¡Jugador MUERTO! <a href=log.php>Aquí</a> está lo que ocurrió<BR><BR>¡Que tengas mejor suerte la próxima vez!";
$l_global_warzone        ="¡La zona es ahora Zona de Guerra!";
$l_global_nzone          ="La zona es una zona neutral.";
$l_global_team           ="La zona pertenece ahora al equipo";
$l_global_player         ="La zona pertenece ahora al jugador";
$l_global_nochange       ="El dominio sobre la zona no ha cambiado";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "O-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recluta";
$l_insignia_name[1] = "Spaceman Aprendiz";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "El suboficial de tercera clase";
$l_insignia_name[4] = "El suboficial de segunda clase";
$l_insignia_name[5] = "El suboficial de primera clase";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Teniente de Fragata Grado";
$l_insignia_name[11] = "Teniente";
$l_insignia_name[12] = "Capitán de Corbeta";
$l_insignia_name[13] = "Comandante";
$l_insignia_name[14] = "Capitán";
$l_insignia_name[15] = "Contralmirante (mitad inferior)";
$l_insignia_name[16] = "Contralmirante (la mitad superior)";
$l_insignia_name[17] = "Vicealmirante";
$l_insignia_name[18] = "Almirante";
$l_insignia_name[19] = "Almirante de la Flota";

$l_main_title            = "Menú Principal";
$l_main_warpto           = "Enlace a";
$l_main_autoroute = "Autopista a";
$l_main_rs_to            = "Salto a";
$l_main_other            = "Otro";
$l_main_shipyard1        = "Astillero";
$l_main_shipyard2        = "Accede al ";
$l_traderoutes           = "Rutas Comerciales";
$l_trade_control         = "Centro del Comercio";
$l_youhave               = "Tienes ";
$l_turns_used            = "Turnos usados: ";
$l_turns_have            = "Turnos disponibles: ";
$l_score                 = "Puntuación: ";
$l_sector = "Sector";
$l_help                  = "Ayuda";
$l_faq = "Preguntas frecuentes";
$l_feedback              = "Contáctanos";
$l_forums = "Foros";
$l_logout                = "Desconectar";
$l_commands              = "Acciones";
$l_command_no            = "Acción no disponible.";
$l_devices               = "Dispositivos";
$l_planets               = "Planetas ";
$l_log                   = "Registro";
$l_sector_def            = "Defensas Sector";
$l_defense               = "Defensas";
$l_read_msg              = "Leer Mensajes";
$l_send_msg              = "Enviar Mensajes";
$l_rankings              = "Clasificación";
$l_teams                 = "Equipos";
$l_ohno                  = "Auto-Destruir";
$l_options               = "Opciones";
$l_navcomp               = "Computadora Nav.";
$l_incompletemove        = "No has completado el movimiento anterior.";
$l_clicktocontinue       = "Haz clic aquí para continuar";
$l_toplanetmenu          = "para ir al menú de planetas.";
$l_nonexistant_pl        = "En un planeta no existente???";
$l_abord                 = ", a bordo de ";
$l_messages_wait         = " Mensajes no leídos.";
$l_no_warplink           = "No hay enlaces";
$l_scan                  = "Escanear";
$l_fullscan              = "Scan Completo";
$l_port                  = "Puerto";
$l_tradingport           = "Puerto comercial";
$l_planet_in_sec         = "Planetas en el sector ";
$l_ships_in_sec          = "Otras naves en el sector ";
$l_sector_0              = "¡Hay tanto tráfico en el Sol que no puedes rastrear ninguna nave!";
$l_map                   = "Mapa";
$l_autotrade = "Autotrades";
$l_onboard = "a bordo de un";
$l_classship = "barco de la clase";
$l_traveled = "viajó al sector";
$l_max_planets = "Máximo planetas habital";
$l_block_msg = "Bloquear mensajes";
$l_probe = "Sondas";
$l_sectorinfo = "Información del sector";
$l_add_note = "Añadir nota";
$l_view_note = "Ver";
$l_notes = "Notas";
$l_global_limitreached = "Ha alcanzado el límite de la cantidad de tiempo que se les permite estar en línea cada día. Entrar de nuevo mañana después de la medianoche.";
$l_onlinetimeleft = "Tiempo Restante:";
$l_planetmax = "Planetario máxima:";
$l_storedshipreport = "Buques almacenados";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federación de información del puerto";
$l_team_shoutbox = "Equipo Shoutbox";
$l_lobby = "Lobby del Operador";

$l_common_prev = "Página anterior";
$l_common_next = "Página siguiente";
$l_common_totalpages = "Total de páginas";
$l_common_selectpage = "Seleccione la página:";
$l_common_page = "Página:";
$l_templatechange = "¿Te gustaría tener esta plantilla?";

$l_im_fed_bounty = "La Federación ha puesto una recompensa por usted para atacar a un jugador clasificado bajo. La Federación de ataque de tu nave en forma regular hasta que pagar su generosidad. Usted puede pagar su recompensa en cualquier puerto de actualización o Spacedock.";
$l_im_fed_bounty_title = "Federación puso una recompensa por ti!";
$l_im_alliance_bounty = "La Alianza ha puesto una recompensa por usted para atacar a un jugador clasificado bajo. La Alianza de ataque de tu nave en forma regular hasta que pagar su generosidad. Usted puede pagar su recompensa en cualquier puerto de actualización o Spacedock.";
$l_im_alliance_bounty_title = "Alianza puso una recompensa por ti!";
$l_instant_messages_waiting = "Tiene [count] mensajes en espera para usted.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Bodegas llenas:";
$l_hold_space_free = "Mantiene en vacío:";
$l_port_buys = "Puerto de compra:";

?>
