<?php
$l_beacon_title          = "Desplegar Baliza Espacial";
$l_beacon_notpermitted   = "El despliegue de balizas espaciales no está permitido en este sector.";
$l_beacon_reads          = "La actual baliza muestra";
$l_beacon_none           = "No hay ninguna baliza en este sector.";
$l_beacon_enter          = "Inserta el texto para la baliza";
$l_beacon_nowreads       = "La baliza muestra ahora";
$l_beacon_donthave       = "No tienes balizas espaciales.";
?>
