<?php
// port.php port_purchase.php
$l_trade		 = "Comercio";
$l_title_port		 = "Comercio en Puerto";
$l_title_trade		 = "Comercio de Mercancías";
$l_sector_war		 = "Embargo de guerra";
$l_war_info		 = "Guerra total en el sector. No puedes alcanzar el puerto atravesando las fuerzas hostiles.";
$l_no_trade		 = "Comercio prohibido";
$l_no_trade_out		 = "No está permitido comerciar en este puerto a intrusos";
$l_no_trade_info	 = "No está permitido comerciar en este puerto";
$l_buying		 = "Compra";
$l_selling		 = "Venta";
$l_commodity		 = "Mercancía ";
$l_amount		 = "Cantidad ";
$l_price		 = "Precio ";
$l_buy			 = "Comprar";
$l_sell			 = "Vender ";
$l_trade_st_info	 = "Tienes [free_holds] de espacio de carga vacío, puedes transportar [free_power] unidades más de energía, y tienes [credits] créditos.";
$l_upgrade_port_title	 = "Puerto de Actualización";
$l_device_port_title	 = "Puerto de Dispositivos";
$l_no_credits		 = "No tienes suficientes créditos";
$l_creds_to_spend	 = "Tienes [credits] créditos para gastar.";
$l_cost			 = "Coste ";
$l_avail		 = "Disponible ";
$l_profit		 = "Beneficio ";
$l_current		 = "Actual ";
$l_current_level	 = "Nivel actual";
$l_current_qty		 = "Cantidades actuales";
$l_max			 = "Max ";
$l_ifyouneedmore	 = "Si necesitas más puedes acceder al [igb] de este puerto ";
$l_ifyouneedplan	 = "Acceder a";
$l_igb_term		 = "Terminal Bancaria de IGB";
$l_upgrade		 = "Actualizar";
$l_unlimited		 = "Ilimitado";
$l_full			 = "Completo";
$l_equipped		 = "Equipado";
$l_n_a			 = "n/d";
$l_item			 = "Item ";
$l_totalcost		 = "Coste total";
$l_would_dump	         = "Si quieres descargar todos los colonos, haz clic ";
$l_noport		 = "¡No hay puerto aquí!";
$l_trade_turnneed	 = "Necesitas al menos un turno para comerciar con el puerto o planeta.";
$l_returnto_port1        = " aquí";
$l_returnto_port2        = " Haz clic en [port_link] para volver al menú de puerto.";
$l_notenough_cargo	 = "No tienes suficiente espacio de carga libre para las mercancías que deseas comprar.";
$l_notenough_power	 = "No tienes suficientes baterías para almacenar la energía que deseas comprar.";
$l_notenough_credits	 = "No tienes suficientes créditos para completar la transacción.";
$l_notenough_turns	 = "No tienes suficientes turnos para completar la transacción.";
$l_trade_result		 = "Resultado de la transacción";
$l_trade_complete	 = "Transacción completada";
$l_trade_upgraded 	 = "Actualizado a nivel ";
$l_trade_added 		 = " añadidos";
$l_trade_installed 	 = " instalado";
$l_port_bounty 		 = "No puedes acceder a un puerto especial mientras tengas recompensa fijada sobre ti por parte de la Federación.<BR>";
$l_port_bounty2 	 = "Haz clic <a href=\"port.php?pay=1\">aquí</a> para pagar la recompensa de [amount] créditos.";
$l_port_btynotenough 	 = "No tienes créditos suficientes para pagar la recompensa de [amount] créditos.<BR>";
$l_port_bountypaid 	 = "Has pagado la recompensa. Haz clic <a href=\"port.php\">aquí</a> para continuar.<BR>";
$l_port_loannotrade 	 = "El IGB a emitido una orden de cierre sobre tu cuenta en la nave debido a la demora en el pago del préstamo. No puedes comerciar en los puertos especiales hasta devolver el préstamo.";
$l_port_returntospecial = " para volver al almacén de suministros.";
$l_ports_shiplimit = "Mínimo clase de buques para montar el dispositivo:";
$l_ports_needrepair = "Reparación";
$l_spacedock_port_title = "Spacedock";

$l_ports_needcredits = "Usted no tiene suficientes créditos para esta transacción. El costo total es de";
$l_ports_needcredits1 = "créditos y sólo se han";

$l_no_trade = "Comercio prohibido";
$l_ports_nooutsiders = "De intercambios comerciales en este puerto no está permitido para los forasteros.";
$l_toprobemenu = "para ir al menú de la sonda.";

$l_bought = "Usted compró";
$l_sold = "Usted vendió";
$l_notenough_commodity = "Usted no tiene suficiente [commodity] para completar la transacción.";
$l_exceed_commodity = "Número de [commodity] excede la oferta y la demanda.";
$l_port_shiptoolarge = "Su barco es demasiado grande para el comercio en este puerto.";

$l_port_hold_unit = "Tiene por unidad";

$l_port_welcome = "Puerto [sectorname] Bienvenido&#39;s [player]";
$l_port_amountforsale = "El puerto tiene [amount] unidades de [commodity] a la venta en [credits] créditos por unidad.";
$l_port_holdsperunit = "[holds] bodegas de carga necesaria por unidad.";
$l_port_howmanypurchase = "¿Cuántas unidades de [commodity] quieres comprar?";
$l_port_unitstobuy = "Unidades de compra";
$l_port_shipcarryingbuy = "Su barco está llevando a [shipunits] unidades de [commodity]. Usted puede comprar [buyunits] unidades de espacio disponible en las bodegas de carga.";
$l_port_howmanysell = "[amount] unidades de [commodity] @ [credits] créditos por unidad.";
$l_port_unitstosell = "Unidades vendan";
$l_port_perform = "Realizar transacciones";
$l_port_cargoholds = "Mantiene la carga";

?>
