<?php
$l_sn_title = "Notas del Sector";
$l_sn_pntitle = "Sectores con notas personales";
$l_sn_tntitle = "Sectores con las notas del equipo";
$l_sn_psntitle = "Personal del Sector Notas";
$l_sn_tsntitle = "Equipo del sector Notas";
$l_sn_editnote = "Editar Sector Note:";
$l_sn_deleteedit = "Eliminar o editar:";
$l_sn_addnote = "Añadir Nota Sector:";
$l_sn_list = "Notas Lista de Sectores";
$l_sn_listts = "Lista de sectores con las notas del equipo";
$l_sn_addteam = "Añadir Team";
$l_sn_deleteteam = "Eliminar equipo";
$l_sn_delete = "Borrar";
$l_sn_saveteam = "Guardar Team";
$l_sn_deletepersonal = "Eliminar personales";
$l_sn_addpersonal = "Añadir Personal";
$l_sn_savepersonal = "Guardar información personal";
$l_sn_editpersonal = "Personales";
$l_sn_editteam = "Equipo de edición";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Tipo";
$l_sn_hdowner = "Propietario / Team";
$l_sn_hdplanets = "Planetas";
$l_sn_hdport = "Puerto";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Minas";
$l_sn_hdscanfrom = "Escanear desde";
$l_sn_hddetail = "Detalle";
$l_sn_hddate = "Fecha / hora";
$l_sn_hddelete = "Borrar";
$l_sn_hdteam = "Equipo";
$l_sn_view = "Ver";
$l_sn_no = "No";
$l_sn_yes = "Sí";
$l_sn_nonotes = "Ningún sector notas encontradas";

?>
