<?php
$l_contact_admin_title = "Juego de contacto del administrador";
$l_contact_admin_thanks = "Gracias por tu comentario.";
$l_contact_admin_email_alert = "Por favor, introduzca una dirección de correo electrónico válida.";
$l_contact_admin_name_alert = "Por favor, introduzca su nombre.";
$l_contact_admin_comment_alert = "Por favor, introduzca sus comentarios.";
$l_contact_admin_name = "Nombre";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Pregunta / Comentario";
$l_contact_admin_submit = "Submit Questions / Comments";
$l_contact_admin_close = "Cerrar la ventana";
$l_contact_admin_thanks_comment = "Gracias por su comentario o pregunta. Estamos dispuestos a atender cualquier pregunta y el correo electrónico con nuestra respuesta.";

?>
