<?php
$l_footer_one_player_on	= "Hay 1 jugador en línea.";
$l_footer_players_on_1	= "Hay";
$l_footer_players_on_2 = "Jugadores en línea:";
$l_footer_until_update	= "segundos hasta la siguiente actualización.";
$l_footer_no_players_on = "No hay ningún jugador conectado.";

$l_footer_news = "Local FNN Noticias";
$l_footer_title = "Alien operadores Asalto";
$l_footer_help = "ayuda por esta página.";
$l_footer_click = "Haga clic en";

$l_footer_open_slots = "Máximo en línea:";
$l_footer_onlinereset = "Player Online Time Restablecer";
$l_footer_onlinecountdown = "Reproductor de tiempo de cuenta atrás en línea:";
?>
