<?php
$l_sf_attacking          = "Los cazas de la defensa del sector te están atacando!<BR>";
$l_sf_destfight          = "Tus láseres destruyeron [lost] cazas<BR>";
$l_sf_destfightb         = "Tus láseres destruyeron [lost] cazas<BR>";
$l_sf_torphit            = "Torpedos golpearon objetivo:";
$l_sf_destfightt         = "Tus torpedos destruyeron [lost] cazas<BR>";
$l_sf_fighthit           = "Ataque de Cazas:";
$l_sf_destfightall       = "Destruiste todo los cazas.<BR>";
$l_sf_destfightt2        = "Destruiste [lost] cazas.<BR>";
$l_sf_lostfight          = "Perdiste todos los cazas.<BR>";
$l_sf_lostfight2         = "Perdiste [lost] cazas.<BR>";
$l_sf_armorbreach        = "Tu blindaje ha sido destruido!<BR>";
$l_sf_armorbreach2       = "Tu blindaje ha sido dañado en [lost] puntos.<BR>";
$l_sf_sendlog            = "[player] destruyó [lost] cazas de defensa de sector en el sector [sector].";
$l_sf_lreport            = "Perdiste [armor] puntos de blindaje, [fighters] cazas, y usaste [torps] torpedos.<BR><BR>";
$l_sf_shipdestroyed      = "Tu nave ha sido destruida!<BR><BR>";
$l_sf_sendlog2           = "Cazas de la defensa de sector destruyeron a [player] en el sector [sector].";
$l_sf_escape             = "Afortunadamente tienes una cápsula de escape!<BR><BR>";

$l_sf_fnoattack = "no envía ningún combatientes a atacar a sus combatientes.";
$l_sf_fnoattackt = "no envía ningún combatientes a atacar a sus torpedos.";
$l_sf_fnoattacka = "no envía ningún combatientes a atacar su armadura.";
$l_sf_flaunchmalf1 = "Su puesta en marcha del sistema de combate ha fallado.";
$l_sf_flaunchmalf2 = "Usted sólo han sido capaces de lanzar";
$l_sf_flaunchmalf3 = "por ciento de sus combatientes.";
$l_sf_fightertorpexg = "De combate a Torpedo / Minas de Exchange";
$l_sf_torpfighterexg = "Barco Torpedo al Sector Fighter Intercambio";
$l_sf_fighterarmorexg = "Sector de combate a buques Armadura de Exchange";
$l_sf_tlaunchmalf1 = "Su sistema de lanzamiento de torpedos ha funcionado correctamente.";
$l_sf_tlaunchmalf2 = "Usted sólo han sido capaces de lanzar";
$l_sf_tlaunchmalf3 = "por ciento de sus torpedos.";
$l_sf_bountysd = "Ha atacado a un sector que contiene un planeta que le daría una recompensa si atacaron el planeta. La Federación ha activado una auto-destrucción automática en todos sus combatientes y torpedos. No ataque a las defensas del sector en este sector de nuevo. Usted ha sido advertido!";
?>
