<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Bienvenido al Casino, actualmente ofrecemos los siguientes juegos e instalaciones";
$l_casino_option = "&quot;Habitaciones";
$l_casino_detail = "&quot;Descripción";

// Blackjack
$l_bet = "&quot;Apuesta";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;De primera mano";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Seguro";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Partir";
$l_credits = "Créditos";
$l_yourbet = "&quot;Su apuesta";
$l_nobet = "&quot;Su apuesta ha superado su límite de crédito, por favor, apuesta de nuevo.";
$l_dealerwins = "Gana Dealer!";
$l_dealerbust = "Busto Dealer!";
$l_dealerloses = "Pierde Dealer!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;El jugador gana!";
$l_playerbust = "&quot;Jugador Bustos!";
$l_playerloses = "&quot;El jugador pierde!";
$l_playerblackjack = "&quot;Jugador de Blackjack!";
$l_place_bet = "&quot;Coloque su apuesta";
?>
