<?php
$l_opt_title = "Seleccione un Avatar";
$l_opt_errorsize = "Error: La imagen no debe ser mayor de 64x64 píxeles de tamaño.";
$l_opt_errortype = "Error: La imagen debe ser JPG, GIF o PNG";
$l_opt_errornographic = "Error: no gráfico seleccionado.";
$l_opt_currentavatar = "Tu avatar actual";
$l_opt_uploadavatar = "Subir un Avatar";
$l_opt_directory = "Seleccione Avatar Directorio";
$l_opt_change = "Cambiar directorio";
$l_opt_select = "Seleccionar un Avatar";
$l_opt_inuse = "Todos los avatares en este directorio están en uso.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
