<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] chocó con  [chm_roll] minas en el sector [chm_sector].";
$l_chm_youlostminedeflectors    = "Perdiste [chm_roll] deflectores de minas.";
$l_chm_youlostallminedeflectors = "Perdiste todos tus deflectores de minas.";
$l_chm_youhadnominedeflectors  = "No tienes deflectores de minas.";
$l_chm_yourshieldshitforminesdmg        = "Tus escudos han sido alcanzados en [chm_mines_left] puntos.";
$l_chm_yourshieldsaredown       = "¡Tus escudos están desactivados!";
$l_chm_youlostallyourshields    = "¡Perdiste todos tus escudos!";
$l_chm_yourarmorhitforminesdmg  = "Tu blindaje ha sido alcanzado en [chm_mines_left] puntos.";
$l_chm_yourhullisbreached       = "¡Se ha abierto brecha en tu casco!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] fue destruido por tus minas en el sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "¡Tu nave ha sido destruida!";
$l_chm_luckescapepod     = "¡Afortunadamente tienes una cápsula de escape!";

$l_chm_yourdeflectormalf1 = "De Minas Deflector sistema de lanzamiento no ha funcionado correctamente.";
$l_chm_yourdeflectormalf2 = "Usted sólo han sido capaces de lanzar";
$l_chm_yourdeflectormalf3 = "por ciento de su deflectores de minas.";
$l_chm_enemytorpfailshields = "no ha lanzado torpedos contra sus escudos.";
$l_chm_enemytorpfailarmor = "no ha lanzado torpedos en contra de su armadura.";

$l_chm_minemalf1 = "Las minas enemigas han funcionado correctamente.";
$l_chm_minemalf2 = "Solamente";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines = "Usted golpea [chm_roll] minas de [total_mines] minas!";
$l_chm_yourdeflectormalf2a = "Usted sólo han sido capaces de lanzar [deflectors] por ciento de su deflectores de minas.";
$l_chm_mines_destroyed = "[number] de [target] minas han sido destruidas!";
$l_chm_mine_deflectors_left = "Usted tiene [number] deflectores de minas a la izquierda.";
$l_chm_mines_left = "Hay [number] de las minas de la izquierda y que inciden en su armadura!";
$l_chm_minemalf2a = "Sólo [deflectors] por ciento de las minas de atacar a encontrar su barco.";
$l_chm_mines_exhausted = "[player] minas agotadas!";
$l_chm_armor_left = "Usted tiene [number] de los puntos de armadura de la izquierda!";

?>
