<?php
$l_login_sclosed		= "Servidor Cerrado";
$l_login_closed_message		= "Servidor cerrado hasta más noticia.";
$l_login_title2			= "Fase Dos de la Conexión";
$l_login_banned			= "<b>Has sido vetado de este juego por el administrador del juego. No eres bienvenido en este servidor. La próxima vez, compórtate bien.</b>";
$l_login_died			= "Tu nave fue destruida, pero tu cápsula de escape os salvó a tí y tu gente.  Haz clic <A HREF=main.php>aquí</A> para continuar con una nueva nave.";
$l_login_newbie			= "Debido a la gravedad de este suceso y al virulento ataque en tu contra, la Federación ha decidido de forma clemente clonarte a partir de tus restos.  Pero, incluso hoy en día los nuevos clones no poseen nada, excepto lo indispensable para comenzar de nuevo.  Se te proporcionará una nave básica y unos pocos créditos para volver a empezar.  Sé más próspero en esta nueva vida.";
$l_login_newlife		= "Haz clic <A HREF=main.php>aquí</A> para continuar en una nueva vida.";
$l_login_looser			= "No tienes cápsula de escape, y debido a tu poco éxito en esta vida, la Federación rehusa a clonarte.  Tus restos deberían con el tiempo entrar en algún campo gravitatorio, con la esperanza de ser usados para crear vida en algún lugar... dentro de varios miles de millones de años.<BR><BR> Que tengas más suerte la próxima vez...";
$l_login_4gotpw1		= "La contraseña introducida no es correcta.<BR><BR>  Si olvidaste la contraseña, ";
$l_login_4gotpw2		= "para que te sea enviada.<BR><BR>  Si no,";
$l_login_4gotpw3		= "para intentarlo de nuevo.  Intento registrado con la dirección IP ";
$l_login_noone			= "¡No existe tal jugador! - Crea un nuevo jugador <A HREF=new_player.php>aquí</A>.";
$l_login_diedincident = "Ha muerto en un incidente horrible.";
$l_login_blackbox = "Blackbox es la información que fue recuperado de los restos de su envío.";
$l_new_login = "para ir a la pantalla de login.";
$l_login_playerlimit = "El servidor ha alcanzado el número máximo de jugadores que soporta. Por favor, intenta acceder a un momento posterior.";
?>
