<?php
$l_autoroute_missingwarp = "Siguiente WarpLink falta en este sector. Warp mover abortado.";
$l_autoroute_SDabort = "Mover abortadas debido a las defensas del sector en el sector.";
$l_autoroute_turns = "Deducirá [triptime] Activa y se trasladó a [targetlink]";
$l_autoroute_noturns = "Usted está de gira.";
$l_autoroute_title = "Rutas Auto";
$l_autoroute_id = "Auto ID Ruta";
$l_autoroute_start = "Auto ruta Inicio";
$l_autoroute_destination = "Auto Ruta Destino";
$l_autoroute_warps = "Auto Route Cabos";
$l_autoroute_deleteroute = "Borrar ruta";
$l_autoroute_info = "Haga clic en Iniciar para el Sector de espacio real a este sector y empezar a torcerse para el sector de destino.";
$l_autoroute_delete2 = "Rutas Eliminar";
$l_autoroute_noroutes = "Ausencia de vías de Auto";
$l_autoroute_createroute = "Crear un nuevo Auto Ruta";
$l_autoroute_deleted = "Auto Rutas eliminado.";
$l_autoroute_return = "Volver al menú del botón Auto Ruta";
$l_autoroute_created = "Auto ruta ha sido creada.";
$l_autoroute_realmove = "Mover espacio real para el sector";
$l_autoroute_warpmove = "Warp para mover siguiente sector";
$l_autoroute_warpfinal = "Warp mover al sector final";
$l_autoroute_editname = "Editar nombre";
?>
