<?php
$l_nav_title             = "Computadora de Navegación";
$l_nav_nocomp            = "No está disponible la Computadora de Navegación";
$l_nav_query             = "Introduce el sector hacia el que encontrar una ruta: ";
$l_nav_pathfnd           = "Ruta encontrada";
$l_nav_answ1             = "Te llevará";
$l_nav_answ2             = "turnos llegar al sector.";
$l_nav_proper = "Usted necesita actualizar su tecnología de combate antes de la Bahía de combatientes puede encontrar una ruta de la urdimbre para esa distancia.";
$l_nav_autoroutename = "Nombre Autoroute Opcional:";
$l_nav_manuallist = "Construido manualmente WarpLink Lista Autoroute";
$l_nav_warplinksleaving = "Warp Enlaces Dejando [sector_name]";
$l_nav_nowarplinksleaving = "No hay warplinks dejar este sector.";
$l_nav_warp_from = "Urdimbre de";
$l_nav_rs_from = "RSMove de";
$l_nav_notinlogs = "No hay datos disponibles sobre este sector.";
?>
