<?php
$l_opt_title             = "Opciones";
$l_opt_chpass            = "Cambiar contraseña";
$l_opt_curpass           = "Contraseña actual:";
$l_opt_newpass           = "Nueva contraseña:";
$l_opt_newpagain         = "Nueva contraseña (de nuevo):";
$l_opt_userint           = "Interfaz del usuario";
$l_opt_usenew            = "Usar nuevo esquema de interfaz?";
$l_opt_lang              = "Idioma";
$l_opt_template = "Plantilla";
$l_opt_select            = "Selecciona uno:";
$l_opt_enabled           = "Habilitado";
$l_opt_save              = "Guardar";
$l_opt_teamicon = "Equipo Icon";
$l_opt_shipname = "ShipName:";
$l_opt_mapwidth = "Local y Galaxy Mapa Ancho:";
$l_opt_profiletitle = "Perfil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registrado con perfil de servidor";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Al registrar su reproductor en otro servidor de la plantilla, foro y noticias sobre la configuración se utilizará en el servidor.";
$l_opt_showshoutbox = "Mostrar Shoutbox:";
$l_opt_shownewscrawl = "Mostrar Noticias de rastreo:";
$l_opt_playername = "Nombre de Usuario:";
$l_opt_playernamecost = "Federación de Cambio de Nombre Cargo: [amount] Créditos";
?>
