<?php
$l_att_title             = "Atacar Nave";
$l_att_notarg            = "El objetivo no se encuentra en este sector.";
$l_att_noturn            = "Necesitas al menos un turno para atacar.";
$l_att_noatt             = "No está permitido atacar naves en este sector.";
$l_att_flee              = "¡El objetivo consiguió evitarte!";
$l_att_ewd               = "¡El objetivo utilizó un dispositivo de salto de emergencia al ser atacado!";
$l_att_att               = "Atacando ";
$l_att_beams = "Manga de Exchange";
$l_att_torps = "Torpedo de Exchange";
$l_att_fighters = "Intercambio de combate";
$l_att_lost              = " perdidos";
$l_att_ylost             = "Perdiste ";
$l_att_sdown             = ": ¡Sus escudos no funcionan!";
$l_att_ydown             = "¡Tus escudos no funcionan!";
$l_att_shits             = "Los escudos de [name] han sido alcanzados en ";
$l_att_yhits             = "Tus escudos son alcanzados en ";
$l_att_dmg               = " de daño";
$l_att_sarm              = "¡El blindaje de [name] ha sido destruido!";
$l_att_yarm              = "¡Tu blindaje ha sido alcanzado!";
$l_att_ashit             = "El blindaje de [name] ha sido alcanzado en ";
$l_att_ayhit             = "Tu blindaje ha sido alcanzado en ";

$l_att_efhit = "&#39;s son destruidos combatientes.";
$l_att_yfhit = "de sus combatientes son destruidos.";
$l_att_ethit = "&#39;s torpedos son destruidos.";
$l_att_ythit = "se destruyen sus torpedos.";
$l_att_of = "de";
$l_att_lostt = "perdido todo torpedos.";
$l_att_ylostt = "Has perdido todos los torpedos.";

$l_att_lostf             = " perdió todos los cazas.";
$l_att_ylostf            = "Perdiste todos los cazas.";
$l_att_sdest             = "La nave de [name] ha sido destruida.";
$l_att_espod             = "¡Fue lanzada una cápsula de escape!";
$l_att_ysalv             = "Salvaste [ship_salvage_rate]% de la nave, valorado en [ship_salvage] créditos.<BR> Tu puntuación ha aumentado en [rating_change] puntos.";
$l_att_andused           = " y usó ";
$l_att_stilship          = "No destruiste la nave de [name]";
$l_att_atyou             = " te atacó";
$l_att_and               = " y ";
$l_att_yshiplost         = "¡Tu nave ha sido destruida!";
$l_att_salv              = "[name] salvó [ship_salvage_rate]% de la nave, valorado en [ship_salvage] créditos";
$l_att_loosepod		 	 = "¡Afortunadamente tienes una cápsula de escape!";

$l_att_tnobeams = "costuras a partir de la energía del haz.";
$l_att_tnobeamsf = "costuras a partir de la energía del haz y no puede atacar a sus combatientes.";
$l_att_tnobeamst = "costuras a partir de la energía del haz y no puede atacar a sus torpedos.";
$l_att_tfnoattack = "no envía ningún combatientes a atacar a su barco.";
$l_att_tnotorps = "parece estar fuera de torpedos.";

$l_att_anobeams = "Ha agotado sus buques de la energía del haz.";
$l_att_anobeamsf = "Ha agotado sus buques de energía del haz y no pueden atacar a los combatientes enemigos.";
$l_att_anobeamst = "Ha agotado sus buques de la energía del haz y no puede atacar al enemigo torpedos.";
$l_att_anofighters = "Su barco ha agotado todos los combatientes availible.";
$l_att_anotorps = "Ha agotado sus torpedos availible.";
$l_att_imtitle = "Ship Under Attack";
$l_att_imbody = "está atacando a su barco.";

$l_att_luckybeams = "Enemy vigas sobrecarga de infligir";
$l_att_luckyfighters = "Combatientes enemigos hacer una sorpresa aligeramiento ataque y causa";
$l_att_luckytorps = "Enemy torpedos inducir un efecto en cascada que causa daños";
$l_att_luckytimes = "veces el daño normal!";
?>
