<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: Shoutbox::.";
$l_shout_public = "Pública";
$l_shout_team = "Equipo";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "algo más";
$l_shout_refresh = "Actualizar";
$l_shout_close = "Cerrar la ventana";
$l_shout_saved = "Nota a salvo!";
$l_shout_return = "Volver a la";
$l_shout_prev = "Anterior";
$l_shout_next = "Siguiente";
$l_shout_selectpage = "Seleccione la página";
$l_shout_page = "Página:";
$l_shout_teamtitle = ".:: SHOUTBOX TEAM::.";
?>
