<?php
$l_profile_title = "Perfil de registro";
$l_profile_notenabled = "Perfiles no están permitidas en este servidor.";
$l_profile_registered = "Este jugador está registrado en el servidor de perfil principal.";
$l_profile_nomatch = "No se puede coincidir con un perfil en el perfil de servidor principal con el nombre y la contraseña del servidor de entrada.";
$l_profile_tryagain = "Para introducir el nombre del perfil de jugador y contraseña del servidor de nuevo, haga clic en";
$l_profile_name = "Perfil Nombre del Jugador";
$l_profile_password = "Perfil de servidor Contraseña";
$l_profile_bannedserver = "Este servidor no está autorizado a presentar información sobre el perfil al perfil de servidor maestro.";
$l_profile_bannedplayer = "Usted ha sido expulsado del perfil de servidor maestro y no se puede inscribir jugadores.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Este <u><b>servidor</b></u> requiere cada nuevo jugador a tener un perfil registrado. No se le permite crear un nuevo jugador a menos que usted tiene un perfil registrado.";
$l_profile_updated = "Su plantilla, shoutbox y noticias de rastreo configuración global se han actualizado en el servidor maestro de perfil. Estos ajustes se utilizará automáticamente al registrar su perfil en cualquier juego.";

?>
