<?php
$l_warp_cantsame         = "No puedes crear un enlace en el cual el sector de partida sea igual al de destino.";
$l_warp_twoerror         = "No está permitido usar un Editor de Enlace para crear un enlace de dos sentidos al sector [target_sector].";
$l_warp_sectex           = "No se puede crear el enlace desde el sector actual, ya que se excedería el número máximo de $link_max enlaces permitidos por sector.";
$l_warp_linked           = "El sector destino ([target_sector]) ya tiene un enlace desde este sector.";
$l_warp_coneway          = "Creado enlace de un solo sentido a ";
$l_warp_ctwoway          = "Creado enlace a y desde ";
$l_warp_nomoney = "Usted no tiene créditos suficientes para crear el vínculo de la urdimbre.";
$l_warp_noenergy = "Usted no tiene suficiente energía para crear el vínculo de la urdimbre.";
?>
