<?php
$l_new_pwis              = "Tu contraseña es ";
$l_new_charis            = "El nombre de tu personaje es ";
$l_new_title2            = "Fase Dos de la creación del jugador";
$l_new_blank             = "La dirección de correo electrónico, el nombre de la nave y el nombre del jugador no pueden estar vacíos.";
$l_new_inuse             = "La dirección de correo electrónico [username] ya está registrada.";
$l_new_forgotpw          = "¿Olvidaste la contraseña?";
$l_new_inusechar         = "El nombre de jugador [character] está ya registrado.";
$l_new_similar_inusechar = "Tu nombre de jugador suena demasiado similar a [character], un nombre ya en uso.";
$l_new_inuseship         = "El nombre de nave [shipname] ya está registrado.";
$l_new_similar_inuseship = "El nombre de tu nave suena demasiado similar a [shipname], un nombre ya en uso.";
$l_new_pwsent            = "La contraseña ha sido enviada a [username].";
$l_new_err               = "Por favor inténtalo de nuevo ";
$l_new_topic             = "Contraseña del juego";
$l_new_message           = "Saludos,\n\n Alguien desde la dirección IP $ip solicitó que tu contraseña para el juego te sea enviada.\n\n Tu contraseña es: [pass]\n\nGracias\n\n El administrador del juego.";
$l_new_invalidemail = "Dirección de correo electrónico no válida.";
$l_new_tutorial = "Haga clic aquí para leer el mini-tutorial antes de ingresar en el juego.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "para ir a la pantalla de login.";
?>
