<?php
$l_gns_title             = "Usar Dispositivo Génesis";
$l_gns_turn              = "Necesitas al menos un turno para usar el dispositivo Génesis.";
$l_gns_onplanet          = "No puedes usar este dispositivo mientras estés en la superficie del planeta.";
$l_gns_full              = "Este sistema solar ya está lleno.";
$l_gns_planetex          = "Ya hay un planeta en este sector.";
$l_gns_nogenesis         = "No dispones de dispositivos Génesis.";
$l_gns_forbid            = "Crear un planeta en este sector no está permitido.";
$l_gns_bforbid           = "Las bases en este sector interfieren con tu dispositivo Génesis. No es posible la creación de planetas.";
$l_gns_pcreate           = "Planeta creado.";
$l_sgns_title = "Uso de dispositivos Sector Génesis";
$l_sgns_pcreate = "Sector [name] creado.";
$l_sgns_nogenesis = "Usted no tiene ningún sector de los dispositivos génesis.";
$l_sgns_forbid = "Creación de un agujero de gusano génesis del sector en este sector no está permitido.";
$l_sgns_forbid1 = "Creación de un sector de la génesis de un Sector de agujero de gusano Federación no está permitido.";
$l_sgcreate = "Crear un nuevo sector de Génesis Sector de";
$l_sgcreatens = "Crear un nuevo sector de Génesis enlace de vuelta al espacio conocido";
$l_sgns_forbid2 = "Más de [limit] vínculos en los sectores SG no están permitidos.";
$l_sgns_forbid3 = "No se puede crear enlaces Sector urdimbre Génesis actual del sector - que supera el máximo de [limit] por sector.";
$l_sgns_nocredits = "Usted no tiene créditos suficientes para crear un nuevo sector.";
$l_sgns_shipcredits = "Créditos en el barco:";
$l_sgns_createcost = "Costo de creación de nuevo sector:";
$l_sgns_complete = "Normal Espacio enlace completo";
$l_sgns_sectorname = "Introduzca el Nombre de Sector:";
$l_gns_max_unbased_planets = "La Federación no permitirá la creación de más planetas hasta que haya menos de [max_unbased_planets] planetas unbased.";
?>
