<?php
$l_zi_title              = "Información de Zona";
$l_zi_nexist             = "¡Esta sección del espacio no existe!";
$l_zi_feds               = "Federación";
$l_zi_traders = "Space Alliance";
$l_zi_nobody             = "Nadie";
$l_zi_war                = "Espacio en disputa";
$l_zi_allow              = "Permitido";
$l_zi_notallow           = "Prohibido";
$l_zi_limit              = "Sólo permitido al propietario y a los aliados";
$l_zi_ul                 = "Ilimitado";
$l_zi_control            = "Esta zona está bajo tu control";
$l_zi_tochange           = " para cambiar sus reglas.";
$l_zi_owner              = "Propietario de la zona";
$l_zi_maxhull            = "Máxima media de niveles permitida";
?>
