<?php
$l_opt2_title            = "Guardando Opciones";
$l_opt2_passunchanged    = "No se modificó la contraseña.<BR><BR>";
$l_opt2_srcpassfalse     = "Contraseña anterior incorrecta. La contraseña no fue modificada.<BR><BR>";
$l_opt2_newpassnomatch   = "los campos de la nueva contraseña no concuerdan. La contraseña no fue modificada.<BR><BR>";
$l_opt2_passchanged      = "Contraseña modificada.<BR><BR>";
$l_opt2_passchangeerr    = "Error modificando la contraseña.<BR><BR>";
$l_opt2_userintup        = "Actualizado el ajuste del interfaz de usuario.<BR><BR>";
$l_opt2_userintfail      = "El ajuste de la interfaz del usuario no pudo ser actualizado.<BR><BR>";
$l_opt2_chlang           = "El idioma ha sido cambiado a [lang].<p>";
$l_opt2_chtemplate = "Plantilla se ha establecido en [template]. <p>";
$l_opt2_dhtmlup          = "Actualizado el ajuste de página Html dinámica.<BR><BR>";
$l_opt2_dhtmlfail        = "El ajuste de página Html dinámica no pudo ser actualizado.<BR><BR>";
$l_opt2_shipnamechanged = "ShipName cambiado a [name]. <BR><BR>";
$l_opt2_playernamechanged = "Nombre del jugador ha cambiado a [name] y [amount] créditos deducidos de su cuenta del buque. <BR><BR>";
$l_opt2_mapwidth = "Local y Galaxy Mapa Ancho:";
?>
