<?php
$l_feedback_title        ="Enviar Comentario";
$l_feedback_to           ="A:";
$l_feedback_from         ="DE:";
$l_feedback_topi         ="ASUNTO:";
$l_feedback_feedback     ="Comentario";
$l_feedback_message      ="MENSAJE:";
$l_feedback_messent      ="Mensaje Enviado";
$l_feedback_subj         ="Comentario sobre el juego AATraders";
$l_feedback_info         ="Por favor enviar comentarios solo en inglés";
?>
