<?php
$l_mail_title            ="Recuperar Contraseña";
$l_mail_noplayer         ="¡No existe tal jugador! - Crea un nuevo juagador <a href=new_player.php>aquí</a>.";
$l_mail_sent             ="Contraseña enviada a ";
$l_mail_topic            ="Contraseña de $game_name";
$l_mail_message          ="Saludos,\n\nAlguien desde la dirección IP $ip solicitó que tu contraseña para el juego $game_name te sea enviada\n\nTu contraseña es: [pass]\n\nGracias\n\nEl administrador del juego $game_name.";
$l_new_login       		 = "para ir a la pantalla de conexión.";
$l_mail_failed = "Contraseña no pudo enviar a";
?>
