<?php
$l_lrs_title             = "Scan de Largo Alcance";
$l_lrs_nofull            = "Tus escáneres no tienen la capacidad de hacer Escáneres de Largo Alcance.";
$l_lrs_noturns           = "Necesitas al menos $fullscan_cost turno(s) para hacer un escáner de largo alcance.";
$l_lrs_used              = "Usado";
$l_lrs_turns             = "turno(s)";
$l_lrs_left              = "disponibles";
$l_lrs_reach             = "Desde el sector [sector] se pueden alcanzar los siguientes destinos:";
$l_lrs_links             = "Enlaces ";
$l_lrs_ships             = "Naves ";
$l_lrs_click             = "Haz clic en uno de los enlaces para ir a ese sector.";
$l_lrs_cantscan          = "¡No puedes escanear el sector desde el sector actual!";
$l_lrs_zero              = "¡Hay demasiado tráfico en el sector 1 como para escanear naves!";
$l_lrs_moveto            = " para ir al sector";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet            = "Comprobar Registro";
$l_lrs_fedjammed = "Federación se atasca todos sensor de exploraciones.";
$l_lrs_imtitle             = "Sector Under Attack";
$l_lrs_imbody             = "is using a Sector Nova on";
$l_lrs_sectormissile_question = "al fuego de misiles sector.";
$l_log_months 		 = array('Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre');
$l_log_months_short 	 = array('Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic');
?>
