<?php
$l_opt_title = "Seleccione un icono de Equipo";
$l_opt_errorsize = "Error: La imagen no debe ser mayor de 64x64 píxeles de tamaño.";
$l_opt_errortype = "Error: La imagen debe ser JPG, GIF o PNG";
$l_opt_errornographic = "Error: no gráfico seleccionado.";
$l_opt_currentavatar = "Su actual equipo Icon";
$l_opt_uploadavatar = "Cargar un icono";
$l_opt_directory = "Seleccione Equipo icono Directorio";
$l_opt_change = "Cambiar directorio";
$l_opt_select = "Seleccione equipo Icon";
$l_opt_noteam = "Usted no está en un equipo.";
$l_opt_notleader = "Sólo el coordinador del equipo puede cambiar el icono del equipo.";
$l_opt_inuse = "Todos los iconos del equipo en este directorio están en uso.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
