<?php
$l_ship2_buytitle = "La compra de un nuevo buque";
$l_ship2_storetitle = "Astillero Storage Facility";
$l_ship2_wrongclass = "La clase de buques especificada es incorrecta";
$l_ship2_buying = "Usted está comprando:";
$l_ship2_tradein = "En el comercio:";
$l_ship2_value = "Actual de buques de valor:";
$l_ship2_newvalue = "Nuevo buque de valor:";
$l_ship2_totalcost = "Costo total:";
$l_ship2_nomoney = "Usted no tiene suficientes créditos para comprar esta nave.";
$l_ship2_purchase = "Compra";
$l_ship2_buynstore = "Comprar nuevo buque y uno viejo almacén";
$l_ship2_nomoney2 = "Usted no tiene créditos suficientes para completar esta transacción.";
$l_ship2_paystorage = "Su ha eliminado una nave de almacenamiento.";
$l_ship2_turns = "Usted necesita por lo menos [turns] vuelve a realizar esta acción";
$l_ship2_error = "Error interno. No se puede encontrar la clase de buques.";
$l_ship2_owned = "Que ya posee este modelo de barco.";
$l_ship2_shipbought = "Usted acaba de comprar un barco nuevo!";

?>
