<?php
$l_novabomb_turns = "La bomba Nova requiere atleast [turns] se transforma en fuego.";
$l_novabomb_planetsdamaged = "Planetas dañado por la bomba Nova";
$l_novabomb_planet = "Planet [name] sufrieron daños por la bomba Nova.";
$l_novabomb_novaexplode = "Nueva bomba estalló cuando se disparó y su nave ha sufrido un daño masivo.";
$l_novabomb_novaexplode2 = "Nueva bomba estalló cuando fue despedido y su nave fue destruida.";
$l_novabomb_notfedsec = "Nueva bomba no se puede utilizar en la Federación de propiedad de los sectores.";
$l_novabomb_destroyed_planet = "Su bomba nova agrietado de la superficie del planeta y perforado en el centro donde explotó causando que el planeta añicos.";
$l_novabomb_wrongclass = "Esta clase de buques no puede despedir a un dispositivo de Nova Bomb.";
$l_novabomb_nonova = "Usted no tiene una bomba instalada Nova.";
$l_novabomb_novamiss = "La Bomba de Nova estrechamente perdidos, pero causa daños en el planeta.";
$l_novabomb_success = "Sector [sector], ha sido bombardeada Nova!";
$l_novabomb_mines = "Destruir [mines] El sector de Minas.";
$l_novabomb_fighters = "Destruir [fighters] Combatientes sector.";
$l_novabomb_shipsdamaged = "Barcos dañados por la bomba Nova";
$l_novabomb_ship_damage = "Starship [shipname] sufrido daños de la bomba Nova.";
$l_novabomb_ship_survived = "Su barco fue lo suficientemente lejos cuando la bomba explotó Nova para evitar cualquier daño.";
?>
