<?php
$l_cu_storing = "Almacenamiento";
$l_cu_inistored = "<b>Todos los valores de iniciativas se ha logrado almacenar.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto ID Ruta";
$l_cu_start = "Auto ruta Inicio";
$l_cu_destination = "Auto Ruta Destino";
$l_cu_warps = "Auto Route Cabos";
$l_cu_deleteroute = "Borrar ruta";
$l_cu_info = "Haga clic en Iniciar para el Sector de espacio real a este sector y empezar a torcerse para el sector de destino.";
$l_cu_delete2 = "Rutas Eliminar";
$l_cu_noroutes = "Ausencia de vías de Auto";
$l_cu_createroute = "Crear un nuevo Auto Ruta";
$l_cu_deleted = "Auto Rutas eliminado.";
$l_cu_return = "Volver al menú del botón Auto Ruta";
$l_cu_created = "Auto ruta ha sido creada.";
$l_cu_realmove = "Mover espacio real para el sector";
$l_cu_warpmove = "Warp para mover siguiente sector";
$l_cu_warpfinal = "Warp mover al sector final";
?>
