<?php
///SPIES
$l_dig_title = "Dignatario Menú";
$l_dig = "Dignatarios";
$l_dig_disabled = "Dignatarios son discapacitados!";
$l_dig_noturn = "Usted necesita por lo menos una vez, para enviar un dignatario de un planeta.";
$l_dig_notonboard = "Usted no tiene ningún mandatario a bordo.";
$l_dig_ownplanet = "No se puede enviar a un dignatario de un planeta enemigo.";
$l_dig_unownedplanet = "No se puede enviar a un dignatario al planeta sin dueño.";
$l_dig_planetfull = "Hay ya están autorizados [max] dignatarios en ese planeta.";
$l_dig_sendtitle = "Envío de un dignatario [digID] al planeta: <BR> Seleccione dignatario de la misión:";

$l_dig_codenumber = "Código";
$l_dig_job = "Trabajo";
$l_dig_percent = "Porcentaje";
$l_dig_move = "Movimiento";
$l_dig_action = "Acción";
$l_dig_shipowner = "Propietario del buque";
$l_dig_shipname = "Nombre del buque";
$l_dig_shiptype = "Barco de la clase";
$l_dig_shiplocation = "Situación de buques";
$l_dig_planetowner = "Planet Propietario";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Para realizar un trabajo";
$l_dig_max = "Máximo por Planeta";
$l_dig_legend = "Dignatario Leyenda";
$l_dig_description = "Descripción dignatario";
$l_dig_waiting_description = "Dignatario creará torpedos y los combatientes a la espera de una asignación de puestos de trabajo.";
$l_dig_changeerror = "Dignatario de Empleo Informe de Cambio";

$l_dig_nospieshere = "Usted no tiene ningún dignatarios en este planeta!";
$l_dig_transferred = "dignatarios transferidos";
$l_dig_backonship = "El mandatario se encuentra ahora en su barco.";
$l_dig_dismiss = "Desestime el dignatario?";
$l_dig_changebutton = "Cambiar";
$l_dig_notyourplanet = "No es tu planeta.";

$l_dig_defaulttitle1 = "Dignatarios de las naves enemigas";
$l_dig_defaulttitle2 = "Dignatarios en sus planetas";
$l_dig_defaulttitle3 = "Dignatarios en sus planetas";
$l_dig_defaulttitle4 = "Los dignatarios de su barco";

$l_dig_no1 = "Usted no tiene ningún dignatarios en las naves enemigas.";
$l_dig_no2 = "Usted no tiene ningún dignatarios en sus planetas.";
$l_dig_no3 = "Usted no tiene ningún dignatarios en sus planetas.";
$l_dig_no4 = "Usted no tiene ningún dignatarios en su barco.";
$l_dig_nodignitaryatall = "Usted no tiene ningún dignatarios.";
$l_dig_notknown = "Desconocido";
$l_dig_dismiss = "Descartar";
$l_dig_dismiss2 = "Dignatarios despedidos.";
$l_dig_menu = "para volver al menú dignatario.";

?>
