<?php
// New News Items

$l_news_planets = "planetas";
$l_news_cols = "Millones de colonos";
$l_news_p_headline = "[player] &#39;s Imperio tiene ahora [total] planetas";
$l_news_c_headline 	 = "[player]'s Empire now has [total] Million colonists";
$l_news_p_textXX = "La Federación ha emitido advertencias sobre el Imperio de [name]. [name] tiene el control de [total] planetas y debe ser considerado muy peligroso. Todos los sectores deben aumentar las defensas del sector de inmediato.";
$l_news_c_textXX = "El Imperio de [name] está sufriendo hacinamiento masivo en todos los planetas con más de [total] millones de colonos. La escasez de alimentos puede provocar disturbios. Todos los sectores deben ser conscientes de las posibles acciones agresivas por [name] en el futuro.";

$l_created_universe = "&#39;Creación Universe&#39;";
$l_created_universe_full = "&quot;Los científicos que investigan los orígenes del Universo se han decidido por unanimidad que hoy es el día más estadísticamente probable para la creación de Universo que ha tenido lugar&quot;";

$l_news_p_text5 = "El naciente imperio de [name] tiene ahora cinco planetas, el FNN vigilará las acciones de [name] más estrechamente en el futuro!";
$l_news_p_text10 = "El creciente imperio de [name], ya los controles de diez planetas, los informes de FNN decir que una mayor expansión de [name] podría conducir a la guerra!";
$l_news_p_text25 = "El inmenso imperio de [name] 25 planetas colonizados ya, en una entrevista, [name] anunció que se podría considerar ralentizar su expansión en el futuro!";
$l_news_p_text50 = "El vasto imperio enorme de [name], representado por 50 planetas en la galaxia entera está recibiendo una fuerza mortal. Uno de los reporteros FNN descubrió que [name] es la mejora de su barco planeando una gran guerra. En una entrevista [name] anunció que está hecho a propósito única defensa!";
$l_news_c_text25 = "El imperio creciente de [name] tiene ahora 25 millones de colonos, el FNN vigilará las acciones de [name] más estrechamente en el futuro, pero su muy evidente que las tasas de natalidad se va a explotar!";
$l_news_c_text100 = "El imperio de los aspirantes a [name], ahora tiene 100 millones de colonos, después de una explosión de las tasas de natalidad, [name] colonias que parecía ser un buen lugar para las familias a resolver!";
$l_news_c_text500 = "El gran imperio de [name] tiene ahora 500 millones de colonos, [name] dijo en una entrevista que la colonización de la galaxia ha comenzado todavía";
$l_news_c_text1000 = "El imperio gigantescos de [name] tiene ahora mil millones colonos, periodistas FNN descubrió que [name] está en posesión de algún mecanismo de clonación extraño lo que le permite criar nuevos colonos en grandes cantidades. Con esta cantidad de colonos, la fuerza econmic de este imperio es enorme, FNN espera que [name] no gastar su dinero en la guerra de";

$l_news_indi_short = "FNN Rumor: más de [planets] declarar la independencia.";
$l_news_indi = "FNN lo tiene de buena tinta que más de [planets] planetas han decidido que es mejor gobernada por sí mismos y se han convertido en independientes.";

$l_news_nova_short = "FNN Informe: [name] utiliza Nova Bomb.";
$l_news_nova = "FNN tiene noticias de que [name] ha utilizado la temida Nova Bomb [total] Time (s) para destruir un planeta y todos los buques en él.";
$l_news_nova_m_short = "FNN Informe: [name] utiliza Nova bomba y echa de menos.";
$l_news_nova_m = "FNN tiene noticias de que [name] ha utilizado la temida Nova Bomb [total] Time (s) para tratar de destruir un planeta. La bomba explotó Nova fuera de la atmósfera de los planetas y causó enormes daños a la infraestructura planetaria.";

$l_news_bounty = "FNN Informe: [name] coloca una [amount] abundancia de crédito [name2].";

$l_news_attackerpod_p_short = "FNN Informe: [name] &#39;s barco es destruido.";
$l_news_attackerpod_P = "[name] &#39;s nave fue destruida mientras que atacar a un planeta. Afortunadamente [name] había una cápsula de escape y han sobrevivido.";

$l_news_attackerdie_p_short = "FNN Informe: [name] muere!";
$l_news_attackerdie_p = "[name] &#39;s nave fue destruida mientras que atacar a un planeta y que murieron porque no pudieron comprar una cápsula de escape.";

$l_news_destroyed_p_short = "FNN Informe: [name] ataca y destruye un planeta!";
$l_news_destroyed_p = "[name] atacó [total] planeta (s) de propiedad de [owner], y la población de cada planeta destruido el planeta para evitar que sea capturado?";

$l_news_defeated_p_short = "FNN Informe: [name] los ataques y derrotas de un planeta!";
$l_news_defeated_p = "[name] atacó [total] planeta (s) de propiedad de [owner], y derrotó a las fuerzas de defensa planetaria!";

$l_news_notdefeated_p_short = "FNN Informe: [name] los ataques de un planeta y se pierde!";
$l_news_notdefeated_p = "[name] atacó [total] planeta (s) de propiedad de [owner], y las defensas planetarias celebrado contra los ataques implacables!";

$l_news_targetepod_short = "FNN Informe: [name] los ataques a [owner] y gana!";
$l_news_targetepod = "[name] atacó a [owner] &#39;s barco y lo destruyeron completamente. Afortunadamente [owner] había equipado su nave con una cápsula de escape y sobrevivieron.";

$l_news_targetdies_short = "FNN Informe: [name] los ataques a [owner] y los mata!";
$l_news_targetdies = "[name] atacó a [owner] &#39;s barco y lo destruyeron completamente. Lamentablemente [owner] no de su nave equipada con una cápsula de escape y se evapora.";

$l_news_fedcolbounty_short = "FNN Informe: Las grietas Federación abajo en [name]!";
$l_news_fedcolbounty = "La Federación de hoy ha reprimido el famoso pirata espacial [name]! [name], que violan sistemáticamente varios tratados sobre el espacio, fue brevemente contratados por la Federación de batalla, que causó [amount] créditos por valor de los daños en el barco pirata. Funcionarios de la Federación promesa de nuevas acciones en el futuro!";

$l_news_alliancecolbounty_short = "FNN Informe: Las grietas de la Alianza por el [name]!";
$l_news_alliancecolbounty = "La Alianza hoy ha reprimido el famoso pirata espacial [name]! [name], que rutinariamente violan varios tratados sobre el espacio, fue brevemente comprometida por la Alianza, que causó [amount] créditos por valor de los daños en el barco pirata. Responsables de la Alianza prometen más acciones en el futuro!";

$l_news_fedcol_pbounty_short = "FNN Informe: La Federación de cazar a [name]!";
$l_news_fedcol_pbounty = "La Federación de hoy ha reprimido el famoso pirata espacial [name]! [name], que violan sistemáticamente varios tratados sobre el espacio, fue brevemente contratados por la Federación de batalla, que confiscó el planeta [planetname] planetname valor de [amount] de créditos en el sector [sector]. Funcionarios de la Federación promesa de nuevas acciones en el futuro!";

$l_news_alliancecol_pbounty_short = "FNN Informe: La Alianza persigue a [name]!";
$l_news_alliancecol_pbounty = "La Alianza hoy ha reprimido el famoso pirata espacial [name]! [name], que violan sistemáticamente varios tratados sobre el espacio, fue brevemente comprometida por la Alianza, que confiscó el planeta [planetname] planetname valor de [amount] de créditos en el sector [sector]. Responsables de la Alianza prometen más acciones en el futuro!";

$l_news_fedcol_sbounty_short = "FNN Informe: La Federación de cazar a [name]!";
$l_news_fedcol_sbounty = "La Federación de hoy ha reprimido el famoso pirata espacial [name]! [name], que violan sistemáticamente varios tratados sobre el espacio, fue brevemente contratados por la Federación de batalla, que confiscó un barco ([shiptype]) por valor de [cost] en el sector [sector]. Funcionarios de la Federación promesa de nuevas acciones en el futuro!";

$l_news_alliancecol_sbounty_short = "FNN Informe: La Alianza persigue a [name]!";
$l_news_alliancecol_sbounty = "La Alianza hoy ha reprimido el famoso pirata espacial [name]! [name], que violan sistemáticamente varios tratados sobre el espacio, fue brevemente comprometida por la Alianza, que confiscó un barco [shiptype] tipo de buque valor [cost] en el sector [sector]. Responsables de la Alianza prometen más acciones en el futuro!";

$l_killheadline = "[target] fue muerto en un accidente";
$l_news_killed = "[target] fue muerto en un trágico accidente en la actualidad. ¿Cómo heroica - [target] era el último miembro a bordo de su barco, cuando notó que no había ninguna cápsula de escape a la izquierda para él. Que descanse en paz!";

$l_killSDheadline = "[target] fue asesinado por las defensas del sector.";
$l_news_killedSD = "[target] fue asesinado por un número abrumador de las defensas del sector propiedad de [killer]! Lamentablemente, el barco no estaba equipado con una cápsula de escape.";

$l_killplanetheadline = "[target] fue asesinado atacar a un planeta.";
$l_news_killedplanet = "[target] fue asesinado mientras atacan a un planeta propiedad de [killer] de hoy. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

$l_killshipheadline = "[target] fue asesinado de combate de barco.";
$l_news_killedship = "[target] fue muerto en combate buque a buque con [killer] de hoy. El capitán al parecer se olvidó de dotar a la nave con una cápsula de escape.";

$l_killsuicideheadline = "[target] se suicidó.";
$l_news_killedsuicide = "[target] se suicidó hoy en día. Tomaron la forma cobardes porque no tenían la capacidad o el coraje de enfrentarse a las presiones de mando de su propio barco.";

$l_killsofaheadline = "[target] fue asesinado sofá atacar a un planeta.";
$l_news_killedsofa = "[target] fue asesinado mientras sofá atacar a un planeta propiedad de [killer] de hoy. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

$l_killnovaheadline = "[target] fue asesinado durante un ataque de nova.";
$l_news_killednova = "[target] fue asesinado por [killer], durante un ataque con bomba nueva hoy. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

$l_killnovabackfireheadline = "[target] fue asesinado de una nova contraproducente.";
$l_news_killednovabackfire = "[target] fue asesinado cuando su bomba nueva fracasó hoy. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

$l_killsectormissileheadline = "[target] fue asesinado de un misil de Sector.";
$l_news_killedsectormissile = "[target] fue asesinado cuando un misil del sector a partir de [killer] impactado sus escudos. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

$l_killhunterprobeheadline = "[target] fue asesinado de una sonda de Hunter.";
$l_news_killedhunterprobe = "[target] fue muerto cuando una sonda de Hunter [killer] impactado sus escudos. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

$l_killtrapprobeheadline = "[target] fue asesinado de una sonda Trap Sentry.";
$l_news_killedtrapprobe = "[target] fue muerto cuando una sonda Sentry trampa de [killer] impactado sus escudos. Desafortunadamente, el barco no estaba equipado con una cápsula de escape.";

//-------------------

$l_killpodheadline = "[target] &#39;s nave fue destruida en un accidente";
$l_news_killedpod = "[target] &#39;s nave fue destruida en un trágico accidente en la actualidad. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killSDpodheadline = "[target] &#39;s nave fue destruida por las defensas del sector.";
$l_news_killedSDpod = "[target] &#39;s nave fue destruida por un número abrumador de las defensas del sector propiedad de [killer]! Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killplanetpodheadline = "[target] &#39;s nave fue destruida atacar a un planeta.";
$l_news_killedplanetpod = "[target] &#39;s nave fue destruida mientras atacaba a un planeta propiedad de [killer] de hoy. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killshippodheadline = "[target] &#39;s nave fue destruida en el combate del buque.";
$l_news_killedshippod = "[target] &#39;s nave fue destruida en un buque a otro combate con [killer] de hoy. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killsofapodheadline = "[target] &#39;s nave fue destruida mientras sofá atacar a un planeta.";
$l_news_killedsofapod = "[target] &#39;s nave fue destruida mientras sofá atacar a un planeta propiedad de [killer] de hoy. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killnovapodheadline = "[target] &#39;s nave fue destruida durante un ataque de nova.";
$l_news_killednovapod = "[target] &#39;s nave fue destruida por el [killer], durante un ataque con bomba nueva hoy. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killnovabackfirepodheadline = "[target] &#39;s nave fue destruida de una nova contraproducente.";
$l_news_killednovabackfirepod = "[target] &#39;s nave fue destruida cuando su bomba nueva fracasó hoy. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killsectormissilepodheadline = "[target] &#39;s nave fue destruida por un misil de Sector.";
$l_news_killedsectormissilepod = "[target] &#39;s nave fue destruida cuando un misil del sector a partir de [killer] impactado sus escudos. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killhunterprobepodheadline = "[target] &#39;s nave fue destruida por una sonda de Hunter.";
$l_news_killedhunterprobepod = "[target] &#39;s nave fue destruida cuando una sonda de Hunter [killer] impactado sus escudos. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

$l_killtrapprobepodheadline = "[target] &#39;s nave fue destruida por una sonda Trap Sentry.";
$l_news_killedtrapprobepod = "[target] &#39;s nave fue destruida cuando una sonda Sentry trampa de [killer] impactado sus escudos. Un transpondedor Escape Pod fue detectado por la Federación de búsqueda y salvamento.";

// --------------------------

$l_news_promotedheadline = "[name], ha sido ascendido a [rank]";
$l_news_promoted = "La Federación se complace en anunciar la promoción de [name] al rango de [rank].";

$l_news_demotedheadline = "[name], ha sido relegado a [rank]";
$l_news_demoted = "La Federación lamenta tener que anunciar el descenso de categoría de [name] al rango de [rank].";

$l_news_namechangedheadline = "[oldname] cambia su nombre a [newname]";
$l_news_namechanged = "[oldname] aplicado a la Junta de Revisión de la Federación para cambiar su nombre a [newname]. La Federación ha concedido el cambio de nombre. De hoy en adelante [oldname] ahora se conoce como [newname]. Todos los buques y los planetas deben actualizar sus registros de inmediato.";

$l_news_found_planets_short = "Federación de la Encuesta: [found_planets] nuevos planetas situados.";
$l_news_found_planets = "Federación de Scouts han situado Encuesta [found_planets] en los sectores nuevos planetas descubiertos recientemente.";

$l_news_new_ports_short = "Federación de la Encuesta: [new_ports] nuevos puertos construidos.";
$l_news_new_ports = "Ingenieros de la Federación han construido [new_ports] nuevos puertos en los sectores recientemente descubierto.";

$l_news_addedsectors_short = "Federación de la Encuesta: [addedsectors] sectores descubiertos.";
$l_news_addedsectors = "Federación de Scouts han descubierto Encuesta [addedsectors] nuevos sectores. Se recomienda precaución.";

$l_news_artifactheadline = "[playername] [artifact]";
$l_news_artifact = "[playername] ha encontrado todas las piezas del artefacto [artifact] y tiene toda la potencia que puede proporcionar.";

$l_news_artifactfoundheadline = "[playername] encontró [artifact] pieza";
$l_news_artifactfound = "[playername] ha encontrado una de las piezas del artefacto [artifact] y las necesidades de [pieces] más [piece].";

?>
