<?php
$l_artifact_title = "Recuperar Artefacto";
$l_artifact_list_title = "Lista de artefactos adquiridos";
$l_artifact_noscan = "De su escáner no pudo encontrar el artefacto.";
$l_artifact_noturn = "Usted no tiene suficientes turnos para recoger este artefacto.";
$l_artifact_classname = "Nombre del Artefacto";
$l_artifact_description = "Artefacto Descripción";
$l_artifact_imagename = "Imagen Artefacto";
$l_artifact_incomplete = "Artefacto Pieces";
$l_artifact_process = "Utilice el artefacto Completo";

?>
