<?php
$l_warp_unlinked         = "No existe enlace desde este sector que conduzca al sector destino ([target_sector]).";
$l_warp_forbidtwo        = "No está permitido usar un Editor de Enlace para borrar un enlace de dos sentidos a [target_sector].";
$l_warp_removed          = "Borrado el enlace a ";
$l_warp_removedtwo       = "Enlace borrado a y desde ";
$l_warp_nomoney = "Usted no tiene créditos suficientes para eliminar el vínculo de la urdimbre.";
$l_warp_noenergy = "Usted no tiene la energía suficiente para eliminar el vínculo de la urdimbre.";
?>
