<?php
$l_scan_title            = "Escanear Nave";
$l_scan_turn             = "Necesitas al menos un turno para escanear otra nave.";
$l_scan_ron              = "Resultados del escaner sobre ";
$l_scan_capt             = "Capitaneado por:";
$l_scan_arma             = "Armamento:";
$l_scan_carry            = "Transporta:";
$l_scan_bounty           = "Esta nave tiene una recompensa total sobre ella de [amount] créditos.";
$l_scan_fedbounty        = "Esta nave tiene una recompensa sobre ella por parte de la Federación.";
$l_by_nofedbounty        = "Atacar a este jugador/a <B>NO</B> provocará que la Federación imponga una recompensa sobre ti.";
?>
