<?php
$l_login_title			= "Conectar";
$l_login_pw			= "Contraseña:";
$l_login_chooseres		= "Imposible detectar tu resolución de pantalla. Por favor elige la que mejor se ajuste:";
$l_login_newp			= "Si eres nuevo, haz clic <A HREF=\"new_player.php\">aquí</A>.";
$l_login_prbs			= "Problemas?";
$l_login_emailus		= "Envíanos un email";
$l_login_forgot_pw		= "Olvidaste tu contraseña?  Deja el campo vacío y pulsa Conectar.";
$l_login_settings 		= "Ajustes del Juego";
$l_login_change			= "Cambiar";
$l_login_title2 = "Principal Login para AATraders";
$l_login_reset1 = "Perdí mi no programados";
$l_login_reset2 = "Perdí mi programadas:";
$l_login_reset3 = "Sched Reset:";
$l_login_notice = "Aviso Importante:";
$l_login_endadminnews = "Fin de la administración Noticias";
$l_login_tourney_signup = "Inscripciones Torneo habilitado";

$l_login_profile_only = "Sólo perfil";
$l_login_newclosed_message = "Nueva Inscripciones Cerrado";
$l_login_tourneymode = "Correr Torneo";
$l_login_tourneystarts = "Comienza:";
?>
