<?php
///SPIES
$l_spy_title = "Menú Espías";
$l_spy = "Espías ";
$l_spy_disabled = "¡Espías desactivados!";
$l_spy_noturn = "Necesitas al menos un turno para enviar un espía a un planeta.";
$l_spy_notonboard = "No dispones de espías a bordo.";
$l_spy_ownplanet = "No puedes enviar un espía a tu propio planeta.";
$l_spy_unownedplanet = "No puedes enviar un espía a un planeta sin dueño.";
$l_spy_planetfull = "Ya hay [max] espías permitidos en ese planeta.";
$l_spy_sendtitle = "Enviando al espía [spyID] al planeta:<BR>Selecciona la misión del espía:";
$l_spy_type1 = " El espía sólo actua en el planeta.";
$l_spy_type2 = " El espía intenta infiltrarse en cualquier nave que ejecute una transferencia planetaria.";
$l_spy_type3 = " El espía intenta infiltrarse en cualquier nave que ejecute una transferencia planetaria, y luego se infiltra en otro planeta.";
$l_spy_sendbutton = "Enviar al planeta";
$l_spy_sendsuccessful = "Tu espía se infiltra en el planeta y espera el momento oportuno para ponerse en acción.";
$l_spy_sendfailed = "Sensores del Planeta detectaron tu espía, porque tu dispositivo de Camuflaje no pudo ocultarlo adecuadamente. Tu espía ha sido eliminado.";
$l_spy_noturn2 = "Necesitas al menos un turno para recuperar a tu espía.";
$l_spy_confirm = "Estás seguro de que quieres recuperar a tu espía [spyID]?";
$l_spy_cleanupplanet = "para limpiar el planeta de espías enemigos.";
$l_spy_cleanupship = "Si quieres limpiar tu nave de espías enemigos, haz clic ";
$l_spy_yourspies = "Tus espías en el planeta";
$l_spy_sendnew = "Enviar un nuevo espía";

$l_spy_codenumber = "Código";
$l_spy_job = "Tarea";
$l_spy_percent = "Porcentaje";
$l_spy_move = "Movimiento";
$l_spy_action = "Acción";
$l_spy_shipowner = "Dueño de la Nave";
$l_spy_shipname = "Nombre de la Nave";
$l_spy_shiptype = "Clase de Nave";
$l_spy_shiplocation = "Posición de la Nave";
$l_spy_planetowner = "Dueño del Planeta";
$l_spy_planetname = "Planeta";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "No se mueve";
$l_spy_moves['toship'] = "A nave";
$l_spy_moves['toplanet'] = "A planeta";

$l_spy_comeback = "Recuperar";
$l_spy_nospieshere = "¡No tienes espías en el planeta!";
$l_spy_transferred = "espías transferidos";
$l_spy_backonship = "El espía está ahora en tu nave.";
$l_spy_backfailed = "Recuperación fallida.";
$l_spy_changetitle = "Cambiando el modo del espía [spyID] :";
$l_spy_occupied = "Tu espía [spyID] está dedicado a [job], en un porcentaje de [percent].";
$l_spy_dismiss = "¿Quitar el espía?";
$l_spy_changebutton = "Cambiar";
$l_spy_changejob = "Cambiar de trabajo o el Movimiento";
$l_spy_linkback = "para ir al menú de espías.";
$l_spy_changed1 = "Movimiento cambiado.";
$l_spy_changed2 = "Espía quitado y su movimiento cambiado.";
$l_spy_changefailed = "Cambio fallido.";
$l_spy_cleanupplanettitle = "Limpiando tu planeta de espías enemigos:";
$l_spy_notyourplanet = "No es tu planeta.";
$l_spy_cleanuptext[1] = "Limpieza rápida. Usa [creds] créditos y [turns] turnos.";
$l_spy_cleanuptext[2] = "Buena limpieza. Usa [creds] créditos y [turns] turnos.";
$l_spy_cleanuptext[3] = "La mejor limpieza. Usa [creds] créditos y [turns] turnos.";
$l_spy_cannotcleanupplanet = "Sólo tienes [credits] créditos en el planeta y [turns] turnos.";
$l_spy_cleanupbutton1 = "Empezar limpieza";
$l_spy_cleanupplanettitle2 = "Encendiste tus Sensores para detectar espías enemigos en el planeta.";
$l_spy_spyfoundonplanet = "Encontraste el espía [spyID], de [player], en el planeta. Eliminaste al espía.";
$l_spy_spynotfoundonplanet = "No encontraste espías en el planeta.";
$l_spy_notenough = "No tienes suficientes créditos o turnos para empezar la limpieza.";

$l_spy_cleanupshiptitle = "Limpiando tu planeta de espías enemigos:";
$l_spy_notinspecial = "Necesitas estar en un puerto de Dispositivos para poder limpiar tu nave de espías.";
$l_spy_cleanupshiptext[1] = "Limpieza rápida. Usa [creds] créditos y [turns] turnos.";
$l_spy_cleanupshiptext[2] = "Buena limpieza. Usa [creds] créditos y [turns] turnos.";
$l_spy_cleanupshiptext[3] = "La mejor limpieza. Usa [creds] créditos y [turns] turnos.";
$l_spy_cannotcleanupship = "Sólo tienes [credits] créditos y [turns] turnos.";
$l_spy_cleanupbutton2 = "Empezar la limpieza de la nave";
$l_spy_cleanupshiptitle2 = "Pusiste en marcha tus Sensores para encontra espías enemigos en la nave.";
$l_spy_spyfoundonship = "Encontraste el espía [spyID], de [player], en la nave. Eliminaste al espía.";
$l_spy_spynotfoundonship = "No encontraste espías en la nave.";

$l_spy_infodeleted = "Mensaje borrado";
$l_spy_infonotyours = "No es tu mensaje.";
$l_spy_noinfo = "Tus espías en las naves enemigas no han detectado nada todavía.";
$l_spy_infotitle = "Tus espías han recogido la siguiente información";
$l_spy_time = "Hora";
$l_spy_type = "Tipo";
$l_spy_info = "Info.";
$l_spy_datatype[1] = "Planeta";
$l_spy_datatext[1] = "Hay un planeta llamado [planet], propiedad de [player], en el sector [sector].";
$l_spy_delete = "Borrar";
$l_spy_messages = "para ver qué han detectado tus espías.";
$l_spy_defaulttitle1 = "Espías en naves enemigas";
$l_spy_defaulttitle2 = "Espías en planetas enemigos";
$l_spy_defaulttitle3 = "Espías en tus planetas";
$l_spy_defaulttitle4 = "Espías en tu nave";

$l_spy_no1 = "No tienes ningún espía en naves enemigas.";
$l_spy_no2 = "No tienes ningún espía en planetas enemigos.";
$l_spy_no3 = "No hay espías en tus planetas.";
$l_spy_no4 = "No hay espías en tu nave.";
$l_spy_nospiesatall = "No dispones de ningún espía.";
$l_spy_notknown = "Desconocido";

$l_spy_trytitle = "En el planeta este espía intentará ";

$l_spy_cantsendfeds = "Lo sentimos, espías no pueden ser enviados a la Federación o de Planetas Independientes.";
$l_spy_cantsendteam = "Usted no puede colocar espías en un planeta compañeros de equipo.";
$l_spy_messagesdeleted = "Todos los mensajes eliminados";
$l_spy_deleteall = "Eliminar todos";
$l_spy_onplanet = "Espías en el planeta";
$l_spy_menu = "para volver al menú Spy.";
?>
