<?php
$l_readm_title           = "Leer Mensaje";
$l_readm_delete          = "MENSAJE BORRADO";
$l_readm_nomessage       = "No tienes nuevos mensajes...";
$l_readm_center          = "Centro de Recogida de Mensajes";
$l_readm_sender          = "Remitente";
$l_readm_captn           = "Capitán del";
$l_readm_del             = "Borrar";
$l_readm_repl            = "Responder";
$l_readm_return = "Haga clic aquí para volver al menú principal";
$l_readm_title2 = "Correo Lector";
$l_readm_delete = "Eliminar todos";
$l_readm_subject = "Tema";
$l_readm_quote = "Citar";
$l_readm_block = "Bloquear remitente";
$l_readm_alert = "Sistema de Alerta de";
$l_readm_alertbody = "Ship Informática";
?>
