<?php
$l_die_title             = "Auto-Destruir";
$l_die_rusure            = "Estás seguro de que quieres destruir tu propia nave? Esto te borrará del juego.";
$l_die_goodbye           = "Adiós Galaxia cruel!";
$l_die_check             = "¿Estás completamente seguro de que deseas borrarte del juego?";
$l_die_nonono = "¡NO! ¡NO! ¡NO!";
$l_die_what              = "¿En qué estaría pensando?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor             = "Tu nave y todo su contenido se ha desintegrado.";
$l_die_please1           = "salir";
$l_die_please2           = "Por favor, [logout_link]";
$l_die_exploit           = "No juegues con lo que no entiendes.";
?>
