<?php
$l_warp_linkto           = "El enlace conduce desde este sector a ";
$l_warp_nolink           = "No hay enlaces hacia fuera de este sector.";
$l_warp_query            = "¿Hacia qué sector te gustaría crear un enlace?";
$l_warp_oneway           = "Un sentido";
$l_warp_dest             = "Alternativamente, puedes destruir un enlace a sector.";
$l_warp_destquery        = "¿El enlace correspondiente a qué sector desearías borrar?";
$l_warp_bothway          = "Dos sentidos";
$l_warp_create = "Crear un vínculo entre la urdimbre Sector:";
$l_warp_andsector = "y sector:";
$l_warp_distance = "con una distancia de";
$l_warp_lightyears = "de años luz";
$l_warp_delete = "Eliminar vínculo entre la urdimbre Sector:";
$l_warp_costcreate = "Costo de crear:";
$l_warp_costdelete = "Costo para suprimir:";
$l_warp_costenergy = "Energía que se necesita:";
$l_warp_twoerror         = "No está permitido usar un Editor de Enlace para crear un enlace de dos sentidos al sector [target_sector].";
?>
