<?php
$l_move_title            = "Movimiento";
$l_move_turn             = "Necesitas al menos un turno para moverte.";
$l_move_failed           = "¡Movimiento erróneo!";
$l_rs_title              = "Salto de Hiperespacio";
$l_rs_whichsector        = "A qué sector te gustaría llegar por medio del Hiperespacio?";
$l_rs_insector           = "Actualmente te encuentras en el sector [sector] - y los sectores disponibles son desde 1 a [sector_max].";
$l_rs_submit             = "Computar";
$l_rs_movetime           = "Con tus motores, te llevará [triptime] turno(s) completar el salto.";
$l_rs_energy             = "Acumularías [energy] unidades de energía";
$l_rs_noturns            = "No te quedan turnos disponibles, así que no puedes completar el salto.";
$l_rs_engage_link        = "Encender";
$l_rs_engage             = "Tienes [turns] turnos. ¿ [engage] motores?";
$l_rs_invalid = "Usted no puede espacio real a este sector de aquí.";
$l_rs_ready              = "Ahora estás en el sector [sector]. Usaste [triptime] turno(s), y acumulaste [energy] unidades de energía.";
$l_warp_invalid = "Usted no puede deformar a ese sector de aquí.";
$l_move_unknown = "Desconocido Movetype";
?>
