<?php
$l_sm_title = "Sector de Lanzamiento de Misiles";
$l_sm_invalid = "No hay un vínculo entre la urdimbre de este sector y el de destino.";
$l_sm_notarg = "Objetivo no en este sector.";
$l_sm_noturn = "Usted necesita por lo menos una vez al fuego de su sector de misiles.";
$l_sm_nosectormissile = "No se están llevando todos los misiles Sector.";
$l_sm_noscan = "Sensores no pueden conseguir un arreglo en el blanco!";
$l_sm_flee = "Objetivo a maniobrar de Misiles sector!";
$l_sm_ewd = "Meta contrató a un dispositivo de emergencia de la urdimbre cuando se detectó el Sector de Misiles!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] está atacando a tu nave con un misil del sector!";
$l_sm_sectormissilefail = "El sector de los misiles falló cuando tocó el escudo de los buques enemigos!";
$l_sm_sectormissilefail2 = "El sector de los misiles falló cuando llegó a la armadura de los buques enemigos!";
$l_sm_shieldhit = "[target] &#39;s escudos son golpeados por [amount] daño!";
$l_sm_shieldsdown = "[target] &#39;s escudos están abajo!";
$l_sm_armorhit = "[target] &#39;s armadura es golpeado por [amount] daño!";
$l_sm_armorbreached = "[target] &#39;s armadura violada!";
$l_sm_targetnoenergy = "El barco enemigo no tiene ningún tipo de energía! Sector de misiles no!";
$l_sm_attacking = "Atacar [target] a bordo de la [shipname]";
$l_sm_targetok = "Usted no destory [name] &#39;s barco.";
$l_sm_lost = "[target] perdido [armor] puntos de armadura y la [energy] unidades de energía.";
$l_sm_destroyed = "[target] &#39;s buque ha sido destruido.";
$l_sm_escapepod = "Una cápsula de escape se puso en marcha!";
?>
