<?php
$l_pre_title             = "Cambiar Saltos Prefijados";
$l_pre_exceed            = "El Salto Prefijado [preset] supera el el máximo de la Galaxia de [sector_max] sectores. No se guardó ningún Prefijado.<BR><BR>";
$l_pre_set               = "Salto Prefijado";
$l_pre_save              = "Guardar";
$l_pre_info = "Información";
$l_pre_invalid = "[sector] es el nombre de un sector no válido.";
$l_pre_invalidchange = "[sector] es un sector de Génesis Sector. Tu viejo preestablecido no se modifica.";
?>
