<?php
$l_autotrade_title = "Auto Traderoute Valikko";
$l_autotrade_dismiss2 = "Auto Traderoutes Poistetaan.";
$l_autotrade_report = "Auto Traderoute Raportti";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hullin";
$l_autotrade_energy = "Energiahuollon";
$l_autotrade_capacity = "Kapasiteetti";
$l_autotrade_goods = "Tavaroiden hinta";
$l_autotrade_ore = "Rautamalmin";
$l_autotrade_organics = "Orgaanisilla Hinta";
$l_autotrade_energy = "Energian hinnan";
$l_autotrade_colonist = "Uudisasukas Hinta";
$l_autotrade_credits = "Kauppaluotot";
$l_autotrade_delete = "Poistaa <br> Reitille";
$l_autotrade_unnamed = "Nimeämättömät";
$l_autotrade_noroute = "Reittiä";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "luottoja";
$l_autotrade_deletebutton = "Poistaa";
$l_autotrade_noroute2 = "Et ole setup mitään Auto Traderoutes.";
?>
