<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] osuman [chm_roll] kaivokset alalla [chm_sector].";
$l_chm_youlostminedeflectors = "Olet menettänyt [chm_roll] minun ohjaimet.";
$l_chm_youlostallminedeflectors = "Olet menettänyt kaikki minun ohjaimet.";
$l_chm_youhadnominedeflectors = "Sinulla ei ollut minun ohjaimet.";
$l_chm_yourshieldshitforminesdmg = "Sinun Shields on hitti [chm_mines_left] vahinkoa.";
$l_chm_yourshieldsaredown = "Sinun suojat ovat alhaalla!";
$l_chm_youlostallyourshields = "Olet menettänyt kaikki kilvet!";
$l_chm_yourarmorhitforminesdmg = "Your panssari on hitti [chm_mines_left] vahinkoa.";
$l_chm_yourhullisbreached = "Sinun runko on rikottu!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] tuhoutui teidän kaivokset alalla [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Sinun alus on tuhottu!";
$l_chm_luckescapepod = "Onneksi sinulla paeta pod!";

$l_chm_yourdeflectormalf1 = "Mine DEFLECTOR käynnistää järjestelmä on toimintahäiriö.";
$l_chm_yourdeflectormalf2 = "Olette vain voinut käynnistää";
$l_chm_yourdeflectormalf3 = "prosenttia teidän minun ohjaimet.";
$l_chm_enemytorpfailshields = "ei ole käynnistänyt mitään torpedot vasten kilvet.";
$l_chm_enemytorpfailarmor = "ei ole käynnistänyt mitään torpedot vasten panssari.";

$l_chm_minemalf1 = "Enemy Miinat on toimintahäiriö.";
$l_chm_minemalf2 = "Vain";
$l_chm_minemalf3 = "prosenttia kaivosten hyökkää löytänyt laivan.";

$l_chm_youhitsomemines = "Osut [chm_roll] miinat ulos [total_mines] miinoja!";
$l_chm_yourdeflectormalf2a = "Olette vain voinut käynnistää [deflectors] prosenttia sinun minun ohjaimet.";
$l_chm_mines_destroyed = "[number] on [target] kaivoksia on tuhottu!";
$l_chm_mine_deflectors_left = "Sinulla on [number] minun ohjaimet vasemmalle.";
$l_chm_mines_left = "On [number] kaivoksia jäljellä ja ne vaikuttavat teidän panssari!";
$l_chm_minemalf2a = "Vain [deflectors] prosenttia kaivosten hyökkää löytänyt laivan.";
$l_chm_mines_exhausted = "[player] Mines Chat!";
$l_chm_armor_left = "Sinulla on [number] Armor pisteitä jäljellä!";

?>
