<?php
$l_sm_title = "Alan ohjusten";
$l_sm_invalid = "Ei ole taivuttaa välillä tällä alalla ja määränpää alalla.";
$l_sm_notarg = "Tavoite ei tällä alalla.";
$l_sm_noturn = "Tarvitset ainakin yhden vuoron tulen sinun Sector Missile.";
$l_sm_nosectormissile = "Olet eivät tee mitään alaa ohjukset.";
$l_sm_noscan = "Antureita ei saa asettaa aikataulussa!";
$l_sm_flee = "Target ulos maneuvered Sector Missile!";
$l_sm_ewd = "Target harjoittavat hätätilanteessa taivuttaa laitteesta, kun se havaitaan Sector Missile!";
$l_sm_imtitle = "Aluksen Under Attack";
$l_sm_imbody = "[playername] hyökkää sinun alukselle Sector Missile!";
$l_sm_sectormissilefail = "Ala Missile toimintahäiriö, kun se osuu vihollisen alusten kilpi!";
$l_sm_sectormissilefail2 = "Ala Missile toimintahäiriö, kun se osuu vihollisen alusten panssari!";
$l_sm_shieldhit = "[target] &#39;s kilvet ovat hitti [amount] vahinkoa!";
$l_sm_shieldsdown = "[target] &#39;s suojat ovat alhaalla!";
$l_sm_armorhit = "[target] &#39;s panssari on hitti [amount] vahinkoa!";
$l_sm_armorbreached = "[target] &#39;s panssari rikkonut!";
$l_sm_targetnoenergy = "Vihollinen alus ei ole energiaa! Alan Missile ei!";
$l_sm_attacking = "Hyökkäämällä [target] kyytiin [shipname]";
$l_sm_targetok = "Ette destory [name] laiva.";
$l_sm_lost = "[target] Lost [armor] Armor pistettä ja [energy] energian yksikköä.";
$l_sm_destroyed = "[target] &#39;s alus on tuhoutunut.";
$l_sm_escapepod = "Escape pod on avattu!";
?>
