<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Tervetuloa Kasino, tarjoamme tällä hetkellä seuraavissa peleissä ja palvelut";
$l_casino_option = "&quot;Huoneet";
$l_casino_detail = "&quot;Kuvaus";

// Blackjack
$l_bet = "Panos";
$l_stand = "Stand";
$l_hit = "Hit";
$l_firsthand = "&quot;Ensimmäinen omistaja";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "Vakuutukset";
$l_doubledown = "Tuplaus";
$l_lobby = "Lobby";
$l_split = "Jakaa";
$l_credits = "Hyvityksiä";
$l_yourbet = "&quot;Vetosi";
$l_nobet = "Sinun veto on ylittänyt luottorajan, ole hyvä veto uudelleen.";
$l_dealerwins = "Jakaja voittaa!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer menettää!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Pelaaja voittaa!";
$l_playerbust = "&quot;Pelaaja rintakuvaa!";
$l_playerloses = "&quot;Pelaaja häviää!";
$l_playerblackjack = "&quot;Player Blackjack!";
$l_place_bet = "&quot;Tee veto";
?>
