<?php
// port.php port_purchase.php
$l_trade = "Kauppa";
$l_title_port = "Port Trading";
$l_title_trade = "Trading Commodities";
$l_sector_war = "War embargo";
$l_war_info = "Sota riehuu tällä alalla. Et voi saavuttaa sataman läpi kaikki vihamielisten voimien.";
$l_no_trade = "Kaupan kielletty";
$l_no_trade_out = "Trading tässä satamassa, ei saa ulkopuolisille";
$l_no_trade_info = "Kaupankäyntitunnus tässä satamassa, ei saa";
$l_buying = "Ostaminen";
$l_selling = "Myyvät";
$l_commodity = "Hyödykkeenä";
$l_amount = "Määrä";
$l_price = "Hintojen";
$l_buy = "Ostaa";
$l_sell = "Myydä";
$l_trade_st_info = "Olette [free_holds] tyhjä lastiruumat, voi tehdä [free_power] enemmän energiaa yksikköä, ja on [credits] opintoviikkoa.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Ei riitä ov";
$l_creds_to_spend = "Olette [credits] luottojen käyttää.";
$l_cost = "Kustannuksiin";
$l_avail = "Saatavissa";
$l_profit = "Liikevoitto";
$l_current = "Virta";
$l_current_level = "Nykytasolla";
$l_current_qty = "Tämänhetkinen määrä";
$l_max = "Enint";
$l_ifyouneedmore = "Jos tarvitset lisää voit käyttää tätä sataman [igb]";
$l_ifyouneedplan = "Access maapallon";
$l_igb_term = "IGB Banking Terminal";
$l_upgrade = "Päivityksen";
$l_unlimited = "Rajoittamattomat";
$l_full = "Täysi";
$l_equipped = "Varustettuja";
$l_n_a = "n / a";
$l_item = "Kohde";
$l_totalcost = "Kokonaiskustannukset";
$l_would_dump = "Jos haluat upottaa kaikki siirtolaiset täällä, klikkaa";
$l_noport = "Ei ole satama täällä!";
$l_trade_turnneed = "Tarvitset ainakin yhden vuoron kaupan satamassa tai planeetan.";
$l_returnto_port1 = "tässä";
$l_returnto_port2 = "Napsauta [port_link] palata satamaan valikosta.";
$l_notenough_cargo = "Sinulla ei ole tarpeeksi vapaata lastitilat tavaroihin haluat ostaa.";
$l_notenough_power = "Sinulla ei ole tarpeeksi vapaata valtaa varastointi energia haluat ostaa.";
$l_notenough_credits = "Sinulla ei ole tarpeeksi luottoja tapahtuman suorittamiseen.";
$l_notenough_turns = "Sinulla ei ole tarpeeksi muuttuu tapahtuman suorittamiseen.";
$l_trade_result = "Tulokset tästä kaupasta";
$l_trade_complete = "Kauppa päätökseen";
$l_trade_upgraded = "Upgraded tasoa";
$l_trade_added = "lisättiin";
$l_trade_installed = "asennettu";
$l_port_bounty = "Et voi käyttää erityistä satamaan, kun sinulla on armo teitä asettamat federaatio. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Sinulla ei ole tarpeeksi credtis maksamaan lahjasta [amount] opintoviikkoa. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "";
$l_port_returntospecial = "palata tarjonnan varastoon.";
$l_toprobemenu = "Siirry koetin valikosta.";
$l_ports_shiplimit = "Minimi Laiva luokan asentaa laitteeseen:";
$l_ports_needrepair = "Korjaus";

$l_ports_needcredits = "Sinulla ei ole riittävästi määrärahoja tähän liiketoimeen. Kokonaiskustannukset";
$l_ports_needcredits1 = "opintoviikkoa ja sinä vain";

$l_ports_tradeforbidden = "Kaupan kielletty";
$l_ports_nooutsiders = "Kauppajärjestelmän tässä satamassa, ei saa ulkopuolisille.";

$l_bought = "Ostin";
$l_sold = "Olet myydä";
$l_notenough_commodity = "Sinulla ei ole tarpeeksi [commodity] tapahtuman suorittamiseen.";
$l_exceed_commodity = "Lukumäärä [commodity] ylittää tarjonnan ja kysynnän.";
$l_port_shiptoolarge = "Sinun alus on liian suuri kaupan tässä satamassa.";

$l_port_hold_unit = "Otteet per Unit";


$l_port_welcome = "Port [sectorname] Tervetuloa n [player]";
$l_port_amountforsale = "Satamassa on [amount] yksiköt [commodity] myytäväksi [credits] opintoviikkoa kohden.";
$l_port_holdsperunit = "[holds] lastiruumat yksikköä kohden tarvitaan.";
$l_port_howmanypurchase = "Kuinka monta [commodity] yksiköt haluaisit ostaa?";
$l_port_unitstobuy = "Yksiköitä Osta";
$l_port_shipcarryingbuy = "Sinun aluksella on [shipunits] yksiköt [commodity]. Voit ostaa [buyunits] yksiköiden kanssa käytettävissä lastiruumassa tilaa.";
$l_port_howmanysell = "[amount] yksiköt [commodity] @ [credits] opintoviikkoa kohden.";
$l_port_unitstosell = "Yksiköiden myydä";
$l_port_perform = "Perform Transaction";
$l_port_cargoholds = "Lastiruumat";

?>
