<?php
$l_s_yes = "Kyllä";
$l_s_no = "Ei";
$l_s_enabled = "Mahdollisti";
$l_s_disabled = "Vajaakuntoisten";

$l_s_modules = "Moduuleita";
$l_s_modulename = "Name";
$l_s_moduleauthor = "Laatijan";
$l_s_moduleinfo = "Agentuurin";
$l_s_nomodules = "No moduulit Loaded";

$l_s_gamestatus = "Pelistatuksesi";
$l_s_allowpl = "Salli soittimet";
$l_s_allownewpl = "Jotta uudet soittimet";

$l_s_gameoptions = "Peliasetuksia";
$l_s_allowteamplcreds = "Salli Team Planet Credit Transfer";
$l_s_allowfullscan = "Salli Koko Long Range Scan";
$l_s_sofa = "Salli Sub-Asemapaikka Fighter Attacks";
$l_s_showpassword = "Näytön Salasana on Rekisteröityminen";
$l_s_genesisdestroy = "Genesis torps voi tuhota planeettoja";
$l_s_igb = "Tähtienvälinen Bank (IGB)";
$l_s_ksm = "Tunnetut Space Kartat";
$l_s_navcomp = "Selailuun Computer";
$l_s_newbienice = "Newbie Nice";
$l_s_spies = "Spy System";
$l_s_spycapture = "Salli Spies valtaamaan planeettoja";

$l_s_gamesettings = "Peliasetukset";
$l_s_gameversion = "Game versio:";
$l_s_minhullmines = "Minimi rungon koko tarvitaan osuma kaivosten";
$l_s_averagetechewd = "Keskimäärin Tech tasolla Kun hätä Warp hajoaa";
$l_s_numsectors = "Useilla aloilla";
$l_s_maxwarpspersector = "Suurin linkit aloittain";
$l_s_averagetechfed = "Enintään keskimäärin teknologian tasoa federaation Toimialat";
$l_s_igbirateperupdate = "IGB Korko per päivitys";
$l_s_igblrateperupdate = "IGB Lainan korko per päivitys";
$l_s_techupgradebase = "Teknologian Taso päivityksen Pohjat";
$l_s_collimit = "Siirtokuntalaisten Limit";
$l_s_maxturns = "Maksimimäärä kertyneen kierrosta";
$l_s_maxplanetssector = "Enimmäismäärä planeettoja alaa kohti";
$l_s_maxtraderoutes = "Maksimimäärä traderoutes per pelaaja";
$l_s_colreprodrate = "Uudisasukas Syntyvyys";
$l_s_energyperfighter = "Energian yksikkö käyttää aloittain Fighter";
$l_s_secfighterdegrade = "Alan Fighter hajoaminen prosenttiosuutta";
$l_s_planetinterest = "Planet korko";
$l_s_spiesperplanet = "Enimmäismäärä vakoojien kohti planeetan";
$l_s_spysuccessfactor = "Spy menestystekijä";
$l_s_spykillfactor = "Spy tappaa tekijä";
$l_s_colsperfighter = "Uudisasukkaan tarvitaan tuottamaan 1 Fighter joka puolestaan";
$l_s_colspertorp = "Uudisasukkaan tarvitaan tuottamaan 1 Torpedo joka puolestaan";
$l_s_colsperore = "Siirtokuntien tarvitaan tuottamaan 1 Malmi joka puolestaan";
$l_s_colsperorganics = "Uudisasukkaan tarvitaan tuottamaan 1 Organics joka puolestaan";
$l_s_colspergoods = "Siirtolaiset tarvitaan tuottamaan 1 Tavarat joka puolestaan";
$l_s_colsperenergy = "Siirtolaiset tarvitaan tuottamaan 1 Energia joka puolestaan";
$l_s_colspercreds = "Siirtokuntalaisten tarvitaan tuottamaan 1 ov puolestaan";
$l_s_colsper = "Siirtokuntalaisten tarvitaan tuottamaan 1 [commodity] joka puolestaan";

$l_s_gameschedsettings = "Game Scheduler Settings";
$l_s_schedtype = "Scheduler Tyyppi";
$l_s_cronbased = "Cron perusteella";
$l_s_playertriggered = "Player Liipaistavat";
$l_s_minutes = "pöytäkirjaan";
$l_s_ticksupdate = "Punkki tapahtuu aina";
$l_s_turnsupdate = "Muuttuu tapahtuu aina";
$l_s_npcupdate = "Liittouma on jokaisella";
$l_s_igbturnsupdate = "Korot IGB tilit kerätä kaikki";
$l_s_newsupdate = "Uutiset syntyy aina";
$l_s_planetupdate = "Planeetat tuottaa tuotannon välein";
$l_s_spyupdate = "Spies toimii aina";
$l_s_portsupdate = "Satamia uudistaa kaikki";
$l_s_towupdate = "Alukset on vedetään syöttää alojen joka";
$l_s_scoreupdate = "Rankingissa syntyy aina";
$l_s_secdefdegrupdate = "Alan puolustuksemme ei heikentävät kaikki";
$l_s_apocalypseupdate = "Planeettojen maailmanloppu tapahtuu aina";
$l_s_release_version = "Game version";
$l_s_time_since_reset = "Aika viime reset";
$l_s_independence = "Planetary riippumattomuuden";
$l_s_dignitaryupdate = "Arvohenkilöitä toimii aina";

$l_s_turnsupdate = "tekee jokaisesta";
?>
