<?php
///SPIES
$l_spy_title = "Spy Valikko";
$l_spy = "Vakoilijoita";
$l_spy_disabled = "Spies pois päältä!";
$l_spy_noturn = "Tarvitset ainakin yhden vuoron lähettää vakooja on planeetan.";
$l_spy_notonboard = "Sinulla ei ole mitään vakoojia aluksella.";
$l_spy_ownplanet = "Et voi lähettää vakooja omalle planeetalle.";
$l_spy_unownedplanet = "Et voi lähettää vakooja on unowned planeetalla.";
$l_spy_planetfull = "On jo sallittua [max] vakoojia, että planeetalla.";
$l_spy_sendtitle = "Lähettämistä vakooja [spyID] to Planet: <BR> Valitse Spy: n tehtävä:";
$l_spy_type1 = "Spy toimii vain, että planeetalla.";
$l_spy_type2 = "Spy yrittää tunkeutua aluksen, joka suorittaa planeettojen siirtoa.";
$l_spy_type3 = "Spy yrittää tunkeutua aluksen, joka suorittaa planeettojen siirtoa ja sitten soluttaa toiselle planeetalle.";
$l_spy_sendbutton = "Lähetä Planet";
$l_spy_sendsuccessful = "Sinun Spy ujuttautuu planeetan ja odottaa oikeaa hetkeä aloittaa toiminnan.";
$l_spy_sendfailed = "Maapallon Anturit tunnistanut vakooja, koska teidän Viitta laitetta ei kata häntä. Sinun vakooja kuolee.";
$l_spy_noturn2 = "Tarvitset ainakin yksi vuoro soittaa takaisin vakooja.";
$l_spy_confirm = "Oletko varma, että haluat soittaa, sinun Spy [spyID]?";
$l_spy_cleanupplanet = "puhdistamiseen että planeetan vihollisen vakoojia.";
$l_spy_cleanupship = "Jos haluat siistiä aluksen vihollisen vakoojia, valitse";
$l_spy_yourspies = "Sinun vakoojia, että planeetalla";
$l_spy_sendnew = "Lähetä uusi vakooja";

$l_spy_codenumber = "Koodi";
$l_spy_job = "Työ";
$l_spy_percent = "Prosenttiin";
$l_spy_move = "Movement";
$l_spy_action = "Toimen";
$l_spy_shipowner = "Aluksen omistaja";
$l_spy_shipname = "Aluksella nimi";
$l_spy_shiptype = "Aluksen luokka";
$l_spy_shiplocation = "Laiva Sijainti";
$l_spy_planetowner = "Planet Omistaja";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "Ei liiku";
$l_spy_moves['toship'] = "Aluksen";
$l_spy_moves['toplanet'] = "Voit Planet";

$l_spy_comeback = "Soittaa";
$l_spy_nospieshere = "Sinulla ei ole mitään vakoojia tällä planeetalla!";
$l_spy_transferred = "Spies siirretty";
$l_spy_backonship = "Vakooja on nyt sinun aluksella.";
$l_spy_backfailed = "Soittaa takaisin epäonnistui.";
$l_spy_changetitle = "Muuttaminen Spy [spyID] ominaisuudet:";
$l_spy_occupied = "Your Spy [spyID] on palkattu [job], jossa prosenttia [percent].";
$l_spy_dismiss = "Hylkää vakooja?";
$l_spy_changebutton = "Muuta";
$l_spy_changejob = "Vaihtaa työpaikkaa tai liikkeen";
$l_spy_linkback = "Siirry Spy valikosta.";
$l_spy_changed1 = "Movement muuttunut.";
$l_spy_changed2 = "Vakooja hylätään ja hänen liikkeensä muuttunut.";
$l_spy_changefailed = "Muuta epäonnistui.";
$l_spy_cleanupplanettitle = "Puhdistaminen planeettanne vihollisen vakoojien:";
$l_spy_notyourplanet = "Se ei ole sinun planeetta.";
$l_spy_cleanuptext[1] = "Fast cleanup. Käytössään [creds] luottoja ja [turns] kierrosta.";
$l_spy_cleanuptext[2] = "Parempi cleanup. Käytössään [creds] luottoja ja [turns] kierrosta.";
$l_spy_cleanuptext[3] = "Parhaiten cleanup. Käytössään [creds] luottoja ja [turns] kierrosta.";
$l_spy_cannotcleanupplanet = "Sinulla on vain [credits] hyvitykset, että planeetalla ja [turns] kierrosta.";
$l_spy_cleanupbutton1 = "Aloita puhdistaminen planeetta";
$l_spy_cleanupplanettitle2 = "Otit oman Anturit löytämään vihollisen vakoojia, että planeetalla.";
$l_spy_spyfoundonplanet = "Löysit [player] &#39;s Spy [spyID] planeetalla. Tapoit että vakooja.";
$l_spy_spynotfoundonplanet = "Ette löydä mitään vihollista vakoojia, että planeetalla.";
$l_spy_notenough = "Sinulla ei ole tarpeeksi luottoja tai kääntyy aloittaa uudelleen.";

$l_spy_cleanupshiptitle = "Puhdistaminen sinun aluksen vihollisen vakoojien:";
$l_spy_notinspecial = "Sinun täytyy olla laitteet portti Siivoa alusta.";
$l_spy_cleanupshiptext[1] = "Fast cleanup. Käytössään [creds] luottoja ja [turns] kierrosta.";
$l_spy_cleanupshiptext[2] = "Parempi cleanup. Käytössään [creds] luottoja ja [turns] kierrosta.";
$l_spy_cleanupshiptext[3] = "Parhaiten cleanup. Käytössään [creds] luottoja ja [turns] kierrosta.";
$l_spy_cannotcleanupship = "Sinulla on vain [credits] luottoja ja [turns] kierrosta.";
$l_spy_cleanupbutton2 = "Aloita puhdistaminen alustasi";
$l_spy_cleanupshiptitle2 = "Otit oman Anturit löytämään vihollisen vakoojia sinun aluksen.";
$l_spy_spyfoundonship = "Löysit [player] &#39;s Spy [spyID] sinun aluksella. Tapoit että vakooja.";
$l_spy_spynotfoundonship = "Ette löydä mitään vihollisen vakoojia sinun aluksen.";

$l_spy_infodeleted = "Viesti poistettu";
$l_spy_infonotyours = "Se ei ole viestisi.";
$l_spy_noinfo = "Sinun vakoojia vihollisen aluksia ei tunnista mitään vielä.";
$l_spy_infotitle = "Sinun Spies on havaittu seuraavat tiedot";
$l_spy_time = "Temne";
$l_spy_type = "Tyyppi";
$l_spy_info = "Agentuurin";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "On [player] &#39;s Planet [planet] sektori [sector].";
$l_spy_delete = "Poistaa";
$l_spy_messages = "nähdä, mitä vakoilijoita on havaittu.";
$l_spy_defaulttitle1 = "Vakoojia vihollisen alusten";
$l_spy_defaulttitle2 = "Vakoojia vihollisen planeettoja";
$l_spy_defaulttitle3 = "Spies teidän planeetoilla";
$l_spy_defaulttitle4 = "Spies sinun aluksen";

$l_spy_no1 = "Sinulla ei ole mitään vakoojia vihollisen aluksia.";
$l_spy_no2 = "Sinulla ei ole mitään vakoojia vihollisen planeettoja.";
$l_spy_no3 = "Sinulla ei ole mitään vakoojia sinun planeetoilla.";
$l_spy_no4 = "Sinulla ei ole mitään vakoojia sinun aluksen.";
$l_spy_nospiesatall = "Sinulla ei ole mitään vakoojia.";
$l_spy_notknown = "Tiedetä";


$l_spy_trytitle = "Planeetan tämän Spy yrittää";

$l_spy_cantsendfeds = "Anteeksi mutta Spies ei voida lähettää federaation tai Independent Planeetat.";
$l_spy_cantsendteam = "Et voi siirtää vakoojia joukkuetoverit planeetalla.";
$l_spy_messagesdeleted = "Kaikki viestit poistetaan";
$l_spy_deleteall = "Poista kaikki";
$l_spy_onplanet = "Vakoojia Planet";
$l_spy_menu = "palata Spy Menu.";
?>
