<?php
$l_login_title = "Kirjautuminen";
$l_login_pw = "Salasana:";
$l_login_chooseres = "Voi määrittää näytön tarkkuus. Ole hyvä ja valitse parhaiten:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Ongelmia?";
$l_login_emailus = "E-mail us";
$l_login_forgot_pw = "Unohtuiko salasana? Anna tyhjäksi ja paina login.";
$l_login_settings = "Peliasetukset";
$l_login_change = "Muuta";
$l_login_title2 = "Main Kirjaudu sisään AATraders";
$l_login_reset1 = "O Nollaa Aikataulun";
$l_login_reset2 = "Ajoitetut Reset:";
$l_login_reset3 = "Raken Reset:";
$l_login_notice = "Tärkeää:";
$l_login_endadminnews = "End of Admin Ajankohtaista";
$l_login_tourney_signup = "Turnaus Kirjautumiset käytössä";

$l_login_profile_only = "Profiili Vain";
$l_login_newclosed_message = "New Kirjautumiset Suljettu";
$l_login_tourneymode = "Turnaus menossa";
$l_login_tourneystarts = "Alkaa:";
?>
