<?php
$l_new_pwis = "Salasanasi";
$l_new_charis = "Hahmosi nimi on";
$l_new_title2 = "Luo uusi pelaaja Phase Two";
$l_new_blank = "Sähköposti, laivan nimi, ja merkin nimi ei saa olla tyhjä.";
$l_new_inuse = "Sähköpostiosoite [username] on jo käytössä.";
$l_new_forgotpw = "Unohtuiko salasana?";
$l_new_inusechar = "Luonnetta nimi [character], on jo käytössä.";
$l_new_similar_inusechar = "Hahmosi nimi kuulostaa liian samanlainen kuin [character], nimi on jo käytössä.";
$l_new_inuseship = "Aluksen nimi [shipname], on jo käytössä.";
$l_new_similar_inuseship = "Sinun laivan nimi kuulostaa liian samanlainen kuin [shipname], nimi on jo käytössä.";
$l_new_pwsent = "Salasana on lähetetty [username].";
$l_new_err = "Yritä uudelleen";
$l_new_topic = "Alien Assault Traders Salasana";
$l_new_message = "Tervehdys, \ n \ nSomeone alkaen IP-osoite $ IP pyytänyt salasanasi toimijoiden lähetetään sinulle. \ N \ nYour salasana: [pass] \ n \ nThank sinun \ n \ nThe Traders Web-tiimi.";
$l_new_invalidemail = "Virheellinen sähköpostiosoite.";
$l_new_tutorial = "Klikkaa tästä ja lue Mini-opetusohjelma ennen kirjautumista peliin.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "Siirry kirjautumisnäyttöön.";

?>
