<?php
$l_shipyard_title = "Telakalta";
$l_planet = "Planet";
$l_ship_welcome = "Tervetuloa Planetary telakalle. Tarjoamme tällä hetkellä näiden mallien myyntiin.";
$l_ship_class = "Luokan";
$l_ship_properties = "Luokan ominaisuudet";
$l_ship_current = "Virta";
$l_ship_outstorage = "Get out of Storage";
$l_ship_storagecost = "Varastointikustannukset";
$l_ship_storagewarn = "Kun otat Pioneer pois tallennustilan menettää yhden olit antanut teidän alkuperäinen aluksen hävittämiseen.";
$l_ship_levels = "Aluksen Components Levels";
$l_ship_min = "Minuuttia";
$l_ship_max = "Enint";
$l_ship_price = "Hintojen";
$l_ship_turns = "Kääntyy rakentaa";
$l_ship_purchase = "Ostaa";
$l_ship_stored = "Tallennettu";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Keskimäärin Suurin Tech Taso:";
$l_ship_averagenormaltech = "Keskimäärin Normaali Tech Taso:";
$l_ship_averagecurrenttech = "Keskimääräinen Nykyinen Tech Taso:";
?>
