<?php
$l_die_title = "Itsetuhomekanismia";
$l_die_rusure = "Oletko varma, että haluat tuhota aluksen? Tämän jälkeen sinut poistetaan pelistä.";
$l_die_goodbye = "Hyvästi julma galaksi!";
$l_die_check = "Oletko myönteistä, että haluat poistaa itsesi peliin?";
$l_die_nonono = "EI! EI! EI!";
$l_die_what = "Mitä olin ajatellut?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Lähetät ja kaikki laivaan on höyrystetään.";
$l_die_please1 = "uloskirjautumisen";
$l_die_please2 = "Please, [logout_link]";
$l_die_exploit = "Älä pelaa mitä et ymmärrä.";
?>
