<?php
$l_nav_title = "Selailuun Computer";
$l_nav_nocomp = "Navigointi Tietokone ei ole";
$l_nav_query = "Kirjoita alan löytää polku:";
$l_nav_pathfnd = "Polku löytyi";
$l_nav_answ1 = "Se vie sinut";
$l_nav_answ2 = "muuttuu päästä tällä alalla.";
$l_nav_proper = "Sinun täytyy päivittää Fighter Bay teknologiaa ennen kuin taistelijoita löytyy taivuttaa reitti, että matkan.";
$l_nav_autoroutename = "Valinnainen Autoroute Nimi:";
$l_nav_manuallist = "Manuaalisesti Rakennettu WarpLink Autoroute List";
$l_nav_warplinksleaving = "Warp Linkit Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Ole warplinks lähtevät tällä alalla.";
$l_nav_warp_from = "Warp from";
$l_nav_rs_from = "RSMove from";
$l_nav_notinlogs = "Tietoja ei ole saatavissa tällä alalla.";
?>
