<?php
$l_sn_title = "Alan Notes";
$l_sn_pntitle = "Alojen Omat merkinnät";
$l_sn_tntitle = "Alojen Team Notes";
$l_sn_psntitle = "Henkilökohtainen Ala Notes";
$l_sn_tsntitle = "Team Ala Notes";
$l_sn_editnote = "Edit Sector Huom:";
$l_sn_deleteedit = "Poistaa tai muokata:";
$l_sn_addnote = "Lisää Sector Huom:";
$l_sn_list = "Luettelo Toimialat Notes";
$l_sn_listts = "Luettelo Alat Team Notes";
$l_sn_addteam = "Lisää joukkue";
$l_sn_deleteteam = "Poista Team";
$l_sn_delete = "Poistaa";
$l_sn_saveteam = "Tallenna Team";
$l_sn_deletepersonal = "Poista Personal";
$l_sn_addpersonal = "Lisää henkilökohtainen";
$l_sn_savepersonal = "Tallentaa";
$l_sn_editpersonal = "Muokkaa Personal";
$l_sn_editteam = "Edit Team";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Tyyppi";
$l_sn_hdowner = "Omistaja / Team";
$l_sn_hdplanets = "Planeettoja";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fightersin";
$l_sn_hdmines = "Miinoja";
$l_sn_hdscanfrom = "Scan";
$l_sn_hddetail = "Tiedot";
$l_sn_hddate = "Date / Time";
$l_sn_hddelete = "Poistaa";
$l_sn_hdteam = "Joukkue";
$l_sn_view = "Näytä";
$l_sn_no = "Ei";
$l_sn_yes = "Kyllä";
$l_sn_nonotes = "O alan Notes Found";

?>
