<?php
$l_login_sclosed = "Palvelin sulki";
$l_login_closed_message = "Palvelimeen suljettu toistaiseksi.";
$l_login_title2 = "Login Vaihe kaksi";
$l_login_banned = "<b>Sinulla on kielletty t‰m‰n pelin yll‰pito. Et ole en‰‰ tervetullut pelaamaan t‰ll‰ palvelimella. Seuraavan kerran, k‰ytt‰yty‰.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "Koska vakavuutta t‰m‰n rikollisuuden ja julma isku teit‰ vastaan, liitto on yst‰v‰llisesti p‰‰tt‰nyt antaa maksutta kloonauksen teid‰n edelleen. Ik‰v‰ kyll‰, myˆs nykyp‰iv‰n‰, uusia klooneja ei voi omistaa omaisuutta, erill‰‰n perusasiat ansaita elantonsa. Sinut tarjotaan perus-aluksen ja muutama luottoja, joilla p‰‰set alkuun. Toivottavasti seuraava el‰m‰ paranee.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Sinulla ei ollut escape pod, ja koska teid‰n vaatimattomampi menestys t‰ss‰ el‰m‰ss‰, liitto kielt‰ytyy kloonata sinulle. Sinun edelleen olisi lopulta joutua vakavuuden hyvin, toivottavasti voidaan luoda el‰m‰‰ muualla ... usean miljardin vuoden kuluttua. <BR><BR> Parempaa onnea seuraavassa peliss‰ ...";
$l_login_4gotpw1 = "Salasana on v‰‰r‰. <BR><BR> Jos olet unohtanut salasanasi,";
$l_login_4gotpw2 = "on sen s‰hkˆpostitse sinulle. <BR><BR> Muuten,";
$l_login_4gotpw3 = "Yrit‰ uudelleen. Yritt‰‰ kirjautunut IP-osoite";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Sinulla on kuollut kamala tapaus.";
$l_login_blackbox = "on Blackbox tiedot on haettu sinun alusten hylky‰.";
$l_new_login = "Siirry kirjautumisn‰yttˆˆn.";
$l_login_playerlimit = "Palvelin on saavuttanut pelaajien enimm‰ism‰‰r‰n se tukee. Yrit‰ kirjautua myˆhemmin.";
?>
