<?php
$l_by_title = "Palkkioita";
$l_by_noturn = "Tarvitset ainakin yhden vuoron asettaa tai muuttaa armo.";
$l_by_amount = "Bounty Määrä";
$l_by_place = "Paikka armostaan";
$l_by_nobounties = "Tällä hetkellä ei ole palkkioita.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Avatuista";
$l_by_thefeds = "Federation";
$l_by_cancel = "Peruuta";
$l_by_yourself = "Et voi sijoittaa armo teidän itse.";
$l_by_notenough = "Sinulla ei ole tarpeeksi luottoja asettaa armo tästä määrästä.";
$l_by_toomuch = "Et voi siirtää, että armo. Suurin Bounty sallittuja toista pelaajaa [percent] prosenttia oman nettovarallisuuden";
$l_by_zeroamount = "Palkkioita on oltava suurempi kuin 0 opintoviikkoa.";
$l_by_placed = "Bounty on sijoitettu.";
$l_by_nobounty = "Tämä anteliaisuus ei ole enää olemassa.";
$l_by_notyours = "Tämä anteliaisuus ei ole asetettu teidän.";
$l_by_canceled = "Bounty on peruutettu.";
$l_by_action = "Toimen";
$l_by_placebounty = "Paikka tai tarkastella palkkioita.";
$l_by_moredetails = "Klikkaa nimeä saadaksesi lisätietoja.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "Pelaaja asetatte Bounty siitä ei ole olemassa.";
$l_by_destroyed = "Et voi sijoittaa armo on pelaaja, jolla on tuhottu alus.";
$l_by_nofedbounty = "Et saa armo, jos hyökkäys tämä pelaajia laivan tai planeettaa.";
$l_by_fedcollectonly = "Vain liitto voi kerätä Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Et saa armo, jos paikka vakoilla tätä pelaajia planeetalla.";
$l_pay_partial = "Tee osamaksu";
$l_pay_button = "Maksavat";

$l_by_thealliance = "Alliance";
$l_by_alliancecollectonly = "Vain liiton voi kerätä Bounty";
$l_by_bountyscan = "Runsaudessaan";
?>
