<?php
$l_chf_youretreatback = "Sinua vet‰yty‰ takaisin edelliseen paikkaan";
$l_chf_movefailed = "Siirr‰ ep‰onnistui.";
$l_chf_thefightersdetectyou = "Fighters havaita sinulle!";
$l_chf_therearetotalfightersindest = "On [chf_total_sector_fighters] taistelijoiden kohde alalla.";
$l_chf_youcanretreat = "<B>Retreat</b> - maksaa ylim‰‰r‰ist‰ puolestaan.";
$l_chf_inputfight = "<B>Fight</b> - Sinun t‰ytyy voittaa kaikki taistelijat tulla alalle.";
$l_chf_inputcloak = "<B>Viitta</b> - K‰yt‰ peitt‰mist‰ laite ja yrit‰ v‰ltt‰‰ taistelijoita.";
$l_chf_go = "Menn‰";
$l_chf_inputrun = "<B>Attack and Run</b> - Et vaaleneminen hyˆkk‰ys ajelu ja vet‰yty‰. Mutta voi ottaa hieman vahinkoa aikana per‰‰nty‰.";
?>
