<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: ShoutBox::.";
$l_shout_public = "Julkisia";
$l_shout_team = "Joukkue";
$l_shout_smiles = "Smilie n";
$l_shout_else = "muuten";
$l_shout_refresh = "Elähdyttää";
$l_shout_close = "Sulje ikkuna";
$l_shout_saved = "Shout tallennettu!";
$l_shout_return = "Paluuta";
$l_shout_prev = "Edellinen";
$l_shout_next = "Seuraava";
$l_shout_selectpage = "Valitse sivu";
$l_shout_page = "Sivulle:";
$l_shout_teamtitle = ".:: TEAM ShoutBox::.";
?>
