<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Tarvitset ainakin yksi vuoro skannata toisella aluksella.";
$l_scan_ron = "Scan tulokset";
$l_scan_capt = "Kapteenina:";
$l_scan_arma = "Aseistus";
$l_scan_carry = "Carrying:";
$l_scan_bounty = "Tämä laiva on yhteensä armo sitä on [amount] opintoviikkoa.";
$l_scan_fedbounty = "Tämä laiva on armo on se liitto.";
$l_by_nofedbounty = "Hyökkää tämä soitin <B>ei</b> johda liitto saattaminen armo teitä.";
?>
