<?php
$l_att_title = "Attack Ship";
$l_att_notarg = "Tavoite ei tällä alalla.";
$l_att_noturn = "Tarvitset ainakin yksi vuoro hyökätä.";
$l_att_noatt = "Hyökkää joku tällä alalla ei ole sallittua.";
$l_att_flee = "Target ulos maneuvered sinulle!";
$l_att_ewd = "Target harjoittavat hätätilanteessa taivuttaa laitteen kimppuun!";
$l_att_att = "Hyökkääminen";
$l_att_beams = "Leveys Exchange";
$l_att_torps = "Torpedo Exchangen";
$l_att_fighters = "SPAMfighter Exchange";
$l_att_lost = "menetetty";
$l_att_ylost = "Olet menettänyt";
$l_att_sdown = "n suojat ovat alhaalla!";
$l_att_ydown = "Sinun suojat ovat alhaalla!";
$l_att_shits = "n suojat ovat hitti";
$l_att_yhits = "Sinun Shields on hitti";
$l_att_dmg = "vahinkoja";
$l_att_sarm = "&#39;s panssari rikkonut!";
$l_att_yarm = "Sinun panssari on rikottu!";
$l_att_ashit = "&#39;s panssari on hitti";
$l_att_ayhit = "Your armor on hitti";

$l_att_efhit = "n taistelijat ovat tuhoutuneet.";
$l_att_yfhit = "teidän taistelijoita tuhotaan.";
$l_att_ethit = "&#39;s torpedot tuhotaan.";
$l_att_ythit = "teidän torpedot tuhotaan.";
$l_att_of = "ja";
$l_att_lostt = "menettänyt torpedot.";
$l_att_ylostt = "Menetit kaikki torpedot.";

$l_att_lostf = "menettänyt taistelijoita.";
$l_att_ylostf = "Menetit kaikki taistelijoita.";
$l_att_sdest = "&#39;s alus on tuhoutunut.";
$l_att_espod = "Escape pod on avattu!";
$l_att_ysalv = "Sinulla pelastaa [ship_salvage_rate]% ja aluksen [ship_salvage] opintoviikkoa. <BR> Arvosana muuttaa [rating_change] pistettä.";
$l_att_andused = "ja käyttää";
$l_att_stilship = "Ette destory [name] laiva.";
$l_att_atyou = "hyökkäsi sinulle";
$l_att_and = "ja";
$l_att_yshiplost = "Sinun alus on tuhottu!";
$l_att_salv = "[name] pelastaa [ship_salvage_rate]% ja aluksen [ship_salvage] Laajuus";
$l_att_loosepod = "Onneksi sinulla paeta pod!";

$l_att_tnobeams = "saumat on pois säteen energialla.";
$l_att_tnobeamsf = "saumat on pois säteen energiaa ja voi hyökätä sinun taistelijoita.";
$l_att_tnobeamst = "saumat on pois säteen energiaa ja voi hyökätä sinun torpedot.";
$l_att_tfnoattack = "ei lähetä mitään taistelijat hyökkäävät teidän alusta.";
$l_att_tnotorps = "näyttää olevan pois torpedot.";

$l_att_anobeams = "Olet käyttänyt oman laivojen säteen energiaa.";
$l_att_anobeamsf = "Olet käyttänyt oman aluksia säteen energiaa ja voi hyökätä vihollisen taistelijoita.";
$l_att_anobeamst = "Olet käyttänyt oman aluksia säteen energiaa ja voi hyökätä vihollisen torpedot.";
$l_att_anofighters = "Sinun alus on käyttänyt kaikki availible taistelijoita.";
$l_att_anotorps = "Olet käyttänyt oman availible torpedot.";
$l_att_imtitle = "Aluksen Under Attack";
$l_att_imbody = "hyökkää sinun laiva.";

$l_att_luckybeams = "Enemy palkit ylikuormitus aiheuttamalla";
$l_att_luckyfighters = "Vihollisen taistelijat tekevät yllätys vaaleneminen hyökkäys ja aiheuttaa";
$l_att_luckytorps = "Enemy torpedot aiheuttaa CSS vahinkojen vaikutus aiheuttaa";
$l_att_luckytimes = "kertaa normaalia vahinko!";
?>
