<?php
///SPIES
$l_dig_title = "Arvohenkilö Valikko";
$l_dig = "Arvohenkilöitä";
$l_dig_disabled = "Dignataries pois päältä!";
$l_dig_noturn = "Tarvitset ainakin yhden vuoron lähettää arvohenkilö on planeetan.";
$l_dig_notonboard = "Sinulla ei ole mitään arvohenkilö aluksella.";
$l_dig_ownplanet = "Et voi lähettää arvohenkilö jotta vihollisen planeetalle.";
$l_dig_unownedplanet = "Et voi lähettää arvohenkilö on unowned planeetalla.";
$l_dig_planetfull = "On jo sallittua [max] arvohenkilöitä tällä planeetalla.";
$l_dig_sendtitle = "Lähettämistä arvohenkilö [digID] to Planet: <BR> Valitse arvohenkilö n tehtävä:";

$l_dig_codenumber = "Koodi";
$l_dig_job = "Työ";
$l_dig_percent = "Prosenttiin";
$l_dig_move = "Movement";
$l_dig_action = "Toimen";
$l_dig_shipowner = "Aluksen omistaja";
$l_dig_shipname = "Aluksella nimi";
$l_dig_shiptype = "Aluksen luokka";
$l_dig_shiplocation = "Laiva Sijainti";
$l_dig_planetowner = "Planet Omistaja";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Waiting for a job";
$l_dig_max = "Enimmäismäärän Per Planet";
$l_dig_legend = "Arvohenkilö Legend";
$l_dig_description = "Arvohenkilö Kuvaus";
$l_dig_waiting_description = "Arvohenkilö luo torpedot ja hävittäjiä odotellessa työtä tehtävän.";
$l_dig_changeerror = "Arvohenkilö vaihtaessaan työpaikkaa Raportti";

$l_dig_nospieshere = "Sinulla ei ole mitään arvohenkilöitä tällä planeetalla!";
$l_dig_transferred = "arvohenkilöihin siirretty";
$l_dig_backonship = "Arvohenkilö on nyt sinun aluksella.";
$l_dig_dismiss = "Hylkää arvohenkilö?";
$l_dig_changebutton = "Muuta";
$l_dig_notyourplanet = "Se ei ole sinun planeetta.";

$l_dig_defaulttitle1 = "Arvohenkilöitä on vihollisen alusten";
$l_dig_defaulttitle2 = "Arvohenkilöitä teidän planeetoilla";
$l_dig_defaulttitle3 = "Arvohenkilöitä teidän planeetoilla";
$l_dig_defaulttitle4 = "Arvohenkilöitä teidän aluksen";

$l_dig_no1 = "Sinulla ei ole mitään virkamiehistä annetun vihollisen aluksia.";
$l_dig_no2 = "Sinulla ei ole mitään arvohenkilöitä teidän planeetoilla.";
$l_dig_no3 = "Sinulla ei ole mitään arvohenkilöitä teidän planeetoilla.";
$l_dig_no4 = "Sinulla ei ole mitään arvohenkilöitä teidän aluksella.";
$l_dig_nodignitaryatall = "Sinulla ei ole mitään virkamiehistä.";
$l_dig_notknown = "Tiedetä";
$l_dig_dismiss = "Hylkäämään";
$l_dig_dismiss2 = "Arvohenkilöitä hylätään.";
$l_dig_menu = "palata arvohenkilö Menu.";

?>
