<?php
$l_opt_title = "Valitse Avatar";
$l_opt_errorsize = "Virhe: Kuvasi eivät saa olla suurempi kuin 64x64 pikseliä kooltaan.";
$l_opt_errortype = "Virhe: Kuvan on oltava JPG-, GIF-tai PNG";
$l_opt_errornographic = "Virhe: graafinen valittu.";
$l_opt_currentavatar = "Nykyinen Avatar";
$l_opt_uploadavatar = "Lataa Avatar";
$l_opt_directory = "Valitse Avatar Directory";
$l_opt_change = "Muutos";
$l_opt_select = "Valitse Avatar";
$l_opt_inuse = "Kaikki hahmot tässä hakemistossa ovat käytössä.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
