<?php
$l_move_title = "Siirrä";
$l_move_turn = "Tarvitset ainakin yksi vuoro liikkua.";
$l_move_failed = "Siirrä epäonnistui!";
$l_rs_title = "RealSpace Siirrä";
$l_rs_whichsector = "Joka alalla haluaisit päästä läpi RealSpace?";
$l_rs_insector = "Olet tällä hetkellä sektori [sector] - ja on aloja saatavilla 1 [sector_max].";
$l_rs_submit = "Laskee";
$l_rs_movetime = "With moottorit, se kestää [triptime] kääntyy koko matkan.";
$l_rs_energy = "Voisitte koota [energy] yksikköä energiaa";
$l_rs_noturns = "Sinulla ei ole tarpeeksi kääntyy vasemmalle, eikä voi lähteä tälle matkalle.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "Olette [turns] kierrosta. [engage] moottorit?";
$l_rs_invalid = "Et voi realspace kyseisellä alalla täältä.";
$l_rs_ready = "Olet nyt alalla [sector]. Käytitte [triptime] muuttuu, ja sai [energy] energian yksikköä.";
$l_warp_invalid = "Et voi taivuttaa sen, että alan täältä.";
$l_move_unknown = "Tuntematon Movetype";
?>
