<?php
$l_md_title = "Alan puolustuksemme";
$l_md_invalid = "Virheellinen Sector Defense";
$l_md_nolonger = "Ala puolustus valittu ei enää ole.";
$l_md_you = "sinä";
$l_md_bmines = "Sinun palkit tuhoutui";
$l_md_msgdownerb = "[name] tuhottu [mines] kaivokset alalla [sector].";
$l_md_retr = "Olet Haettu";
$l_md_consist = "Tämän alan puolustus koostuu [qty] [type] omistama [owner].";
$l_md_youcan = "Voidaan";
$l_md_retrieve = "Noutamaan";
$l_md_attack = "Hyökkäystä";
$l_md_attdef = "Hyökätä Sector puolustuksemme. Kaikki alan Fighters aikoo kostaa.";
$l_md_noturn = "Tarvitset ainakin yhden vuoron.";
$l_md_nothere = "Sinun pitää olla samalla alalla kuin alalla puolustuksemme.";
$l_md_notyours = "Toiminta ei ole sallittua. Nämä alan puolustukset eivät kuulu sinulle.";
$l_md_yours = "Et voi hyökätä oman alan puolustuksemme.";
?>
