<?php
$l_autoroute_missingwarp = "Seuraava warplink puuttuu tällä alalla. Loimi liikkua keskeytetty.";
$l_autoroute_SDabort = "Siirrä Aborted koska ala Defenses alalla.";
$l_autoroute_turns = "Vähennetä [triptime] Ottaa ja muutti [targetlink]";
$l_autoroute_noturns = "Olet pois kierrosta.";
$l_autoroute_title = "Auto Reitit";
$l_autoroute_id = "Auto Route tunnus";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination = "Auto reittikohde";
$l_autoroute_warps = "Auto Route vetovaijerit";
$l_autoroute_deleteroute = "Poista reitti";
$l_autoroute_info = "Napsauta Käynnistä-alan Realspace tätä alaa ja aloittaa käyristymisen kohteeseen alalle.";
$l_autoroute_delete2 = "Poista Reitit";
$l_autoroute_noroutes = "O Auto Reitit";
$l_autoroute_createroute = "Luo uusi Auto reitti";
$l_autoroute_deleted = "Auto Reitit poistettu.";
$l_autoroute_return = "Palaa Auto Reitti-valikossa valitse";
$l_autoroute_created = "Auto reitti on luotu.";
$l_autoroute_realmove = "Realspace siirtyä alalle";
$l_autoroute_warpmove = "Warp siirtyä seuraavaan sektoriin";
$l_autoroute_warpfinal = "Warp siirtyä viimeisellä";
$l_autoroute_editname = "Muokkaa nimeä";
?>
