<?php
$l_sf_attacking = "Alan puolustus taistelijat hyˆkk‰‰v‰t sinua! <BR>";
$l_sf_destfight = "Your palkit tuhoutunut [lost] Fighters <BR>";
$l_sf_destfightb = "Your palkit tuhoutunut [lost] Fighters <BR>";
$l_sf_torphit = "Torpedoja hit:";
$l_sf_destfightt = "Your torpedot tuhoutunut [lost] Fighters <BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "Olet tuhonnut kaikki taistelijat. <BR>";
$l_sf_destfightt2 = "Voit tuhota [lost] taistelijoita. <BR>";
$l_sf_lostfight = "Menetit kaikki taistelijoita. <BR>";
$l_sf_lostfight2 = "Olet menett‰nyt [lost] taistelijoita. <BR>";
$l_sf_armorbreach = "Your armor on rikottu! <BR>";
$l_sf_armorbreach2 = "Your panssari on hitti [lost] vahinkoa. <BR>";
$l_sf_sendlog = "[player] tuhoutunut [lost] sektorin puolustus taistelijat alalla [sector].";
$l_sf_lreport = "Olet menett‰nyt [armor] Armor pistett‰, [fighters] taistelijoita, ja k‰ytt‰‰ [torps] torpedot. <BR><BR>";
$l_sf_shipdestroyed = "Sinun alus on tuhottu! <BR><BR>";
$l_sf_sendlog2 = "Sektori puolustus Fighters tuhottu [player] sektori [sector].";
$l_sf_escape = "Onneksi sinulla paeta pod! <BR><BR>";

$l_sf_fnoattack = "ei l‰het‰ mit‰‰n taistelijat hyˆkk‰‰v‰t teid‰n taistelijoita.";
$l_sf_fnoattackt = "ei l‰het‰ mit‰‰n taistelijat hyˆkk‰‰v‰t teid‰n torpedot.";
$l_sf_fnoattacka = "ei l‰het‰ mit‰‰n taistelijat hyˆkk‰‰v‰t teid‰n panssari.";
$l_sf_flaunchmalf1 = "Your Fighter k‰ynnist‰‰ j‰rjestelm‰ on toimintah‰iriˆ.";
$l_sf_flaunchmalf2 = "Olette vain voinut k‰ynnist‰‰";
$l_sf_flaunchmalf3 = "prosenttia your taistelijoita.";
$l_sf_fightertorpexg = "Fighter torpedoida / Mine Exchange";
$l_sf_torpfighterexg = "Laiva Torpedo sektorille SPAMfighter Exchange";
$l_sf_fighterarmorexg = "Alan Fighter aluksen Armor Exchange";
$l_sf_tlaunchmalf1 = "Sinun torpedo k‰ynnist‰‰ j‰rjestelm‰ on toimintah‰iriˆ.";
$l_sf_tlaunchmalf2 = "Olette vain voinut k‰ynnist‰‰";
$l_sf_tlaunchmalf3 = "prosenttia your torpedot.";
$l_sf_bountysd = "Olette hyˆkk‰si ala sis‰lt‰‰ planeetalla, joka antaa sinulle armo, jos hyˆkk‰si planeetalle. Liitto on k‰ytˆss‰ automaattinen itsetuhomekanismia kaikkien teid‰n taistelijoiden ja torpedot. Eiv‰t vahingoita alan puolustusta alan uudelleen. Teit‰ on varoitettu!";
?>
