<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Your skannerit ei ole koko pitkän kantaman scan ominaisuuksia.";
$l_lrs_noturns = "Tarvitset vähintään $ fullscan_cost puolestaan (t) suorittaa koko pitkän kantaman Scan.";
$l_lrs_used = "Käytettiin";
$l_lrs_turns = "puolestaan (s)";
$l_lrs_left = "vasen";
$l_lrs_reach = "Seuraavissa paikoissa pääsee alalla [sector]:";
$l_lrs_links = "Yhteyksiä";
$l_lrs_ships = "Aluksista";
$l_lrs_click = "Valitse jokin linkkejä siirtyä tälle alalle.";
$l_lrs_cantscan = "Voi skannata alan nykyisestä alalla!";
$l_lrs_zero = "Sector 1 on liian ahdasta etsimään alusten!";
$l_lrs_moveto = "siirtyä alalle";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Näytä loki";
$l_lrs_fedjammed = "Federaatio on häirintä kaikki anturi tarkistaa.";
$l_lrs_sectormissile_question = "ampumaan alan ohjus.";
$l_log_months = "array ( &#39;Tammikuu&#39;, &#39;Helmikuu&#39;, &#39;Maaliskuu&#39;, &#39;Huhtikuu&#39;, &#39;Toukokuu&#39;, &#39;Kesäkuu&#39;, &#39;Heinäkuu&#39;, &#39;Elokuu&#39;, &#39;Syyskuu&#39;, &#39;Lokakuu&#39;, &#39;Marraskuu&#39;, &#39;Joulukuu&#39;)";
$l_log_months_short = "array ( &#39;Tammi&#39;, &#39;Helmi&#39;, &#39;Maalis&#39;, &#39;Huhti&#39;, &#39;Toukokuu&#39;, &#39;Kesäkuu&#39;, &#39;Heinäkuu&#39;, &#39;Elokuu&#39;, &#39;Syys&#39;, &#39;Lokakuu&#39;, &#39;Marraskuu&#39;, &#39;Joulukuu&#39;)";
?>
