<?php
$l_cu_storing = "Varastointiin";
$l_cu_inistored = "<b>Kaikki ini arvot on onnistuneesti tallennettu.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route tunnus";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto reittikohde";
$l_cu_warps = "Auto Route vetovaijerit";
$l_cu_deleteroute = "Poista reitti";
$l_cu_info = "Napsauta Käynnistä-alan Realspace tätä alaa ja aloittaa käyristymisen kohteeseen alalle.";
$l_cu_delete2 = "Poista Reitit";
$l_cu_noroutes = "O Auto Reitit";
$l_cu_createroute = "Luo uusi Auto reitti";
$l_cu_deleted = "Auto Reitit poistettu.";
$l_cu_return = "Palaa Auto Reitti-valikossa valitse";
$l_cu_created = "Auto reitti on luotu.";
$l_cu_realmove = "Realspace siirtyä alalle";
$l_cu_warpmove = "Warp siirtyä seuraavaan sektoriin";
$l_cu_warpfinal = "Warp siirtyä viimeisellä";
?>
