<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Tarvitset vähintään 1 puolestaan rakentaa perusta";
$l_planet_upgrade = "Päivityksen";
$l_planet_novamiss = "Nova Bomb suppeasti piti vaan aiheutetaan vahinkoa, kun maapallolla.";
$l_planet_novaturns = "Nova Bomb edellyttää atleast [turns] muuttuu tuleen.";
$l_planet_novafed = "Nova Bomb ei käynnisty vuonna federaation aloilla.";
$l_planet_nonova = "Sinulla ei ole Nova Bomb asennettu.";
$l_planet_firenova = "Fire Nova Bomb";
$l_planet_novaexplode = "Nova räjähti pommi, koska se oli ammuttu ja sinun alus on kärsinyt vakavia vaurioita.";
$l_planet_novaexplode2 = "Nova räjähti pommi, koska se oli ammuttu ja teidän alus tuhoutui.";
$l_planet_noautotrade = "Autokaupan Reitti ei ole asetettu tälle planeetalle.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] satamaan [dest_id]";
$l_planet_autotradedelete = "Poista Autokaupan.";
$l_planet_autotradeadd = "Luo Autokaupan.";
$l_planet_tradedeleted = "Autokaupan Reitti Poistetaan.";
$l_planet_tradeadded = "New Autokaupan Reitti Lisätty.";
$l_planet_autotype = "Valitse kohde kaupan";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Sinun täytyy ostaa lastialuksen tälle planeetalle, ennen kuin voit asettaa Autokaupan reitti.";
$l_planet_purchasecargo = "Jos haluat ostaa Cargo Ship";
$l_planet_upgradecargo = "Jos haluat päivittää Cargo Ship";

$l_planet_cargocapacity = "Kapasiteetti:";
$l_planet_cargoowned = "Omistat jo rahtialuksen tälle planeetalle.";
$l_planet_cargoshipbuy = "Purchase Cargo Ship";
$l_planet_cargoshipupgrade = "Upgrade Cargo Ship";
$l_planet_cargoatmax = "Sinun lastialuksella on suurin päivityksen tasolla.";
$l_planet_cargoshipbuyinfo = "Valitse esiasetus Cargo Ship";
$l_planet_cargoshipupgradeinfo = "Päivitä rahtialukset Hull.";
$l_planet_cargoshipbuildinfo = "Rakenna oma Cargo Ship";
$l_planet_tradehelp = "1. Voit kirjoittaa kaupan satamaan kunkin hyödykkeen. <br> 2. Et voi kauppaa hyödykkeen satamassa, joka myy samaa hyödykettä. <br> Tavarakauppa on Tavarat Port, Ore on Ore Port, ect. tee mitään. <br> 3. Jos et halua kauppaa tiettyjen hyödykkeiden syötä 0 satama-alalla.";
$l_planet_cargocredits = "Autokaupan saadut hyvitykset:";
$l_planet_cargonoown = "Sinun on oma planeettamme luoda Auto Traderoute.";
$l_planet_digtrans = "Siirto arvohenkilö";
$l_planet_nocredits1 = "Sinulla ei ole riittävästi määrärahoja tähän liiketoimeen. Kokonaiskustannukset";
$l_planet_nocredits2 = "opintoviikkoa ja sinä vain";
$l_planet_nobase = "Sinun täytyy olla perusta hallita planeetan puolustuksen tasoa.";
$l_planet_genesisnoturn = "Tarvitset vähintään 1 puolestaan käyttää Genesis laitteeseen planeetalla.";
$l_planet_nogenesis = "Tarvitset Genesis Laitteen tuhota planeetan.";
$l_planet_wrongclass = "Tämä laiva luokkaan ei voida ampua Nova Bomb laite.";

$l_planet_combatpreview = "Combat Esikatselukuva";
$l_planet_beamfire1 = "Sinun hyökkäys on havaittu. Planetary Tangot ampumisen! Lisääntynyt Keila tuleen, koska sinun aluksen tulee liian lähelle planeettaa käynnistää taistelijoita.";
$l_planet_beamfire2 = "Sinun hyökkäys on havaittu. Planetary Tangot ampumisen! Massiivinen tulipalo korolla planeetan Leveys Akut lukko useita osumia!";
$l_planet_beamfire3 = "Sinun hyökkäys on havaittu. Planetary Tangot ampumisen! Keila Akut koko planeetan lukitus päälle massiivinen useita tuleen! Keila tuli paljon enemmän kuin arvioitu!";
$l_planet_beamfire4 = "Sinun hyökkäys on havaittu. Planetary Tangot ampumisen! Keila puolustuksemme vain lukko yhden polton kulkea.";

$l_planet_sofanobeamsshields = "ei polttamalla palkit teidän kilvet.";
$l_planet_sofanobeamsarmor = "ei polttamalla palkit teidän panssari.";
$l_planet_flauncherfailed1 = "Your Fighter käynnistää järjestelmä on toimintahäiriö.";
$l_planet_flauncherfailed2 = "Olette vain voinut käynnistää";
$l_planet_flauncherfailed3 = "prosenttia your taistelijoita.";
$l_planet_nodfightertofighter = "ei lähetä mitään taistelijat hyökkäävät teidän taistelijoita.";
$l_planet_nodfightertotorp = "ei lähetä mitään taistelijat hyökkäävät teidän torps.";
$l_planet_flauncherfailed3 = "prosenttia your taistelijoita.";
$l_planet_autotradetype = "- [source_type] satamaan [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "hyökkää";
$l_planet_iminsector = "sektorissa";
$l_planet_imnova = "käyttää Nova laite";
$l_planet_imsofa = "on SOFA Pommitukset";
$l_planet_team = "Tämä planeetta on omistaa tallikaveri ja sinulla ei ole oikeutta saada tietoja tämän planeetan.";
?>
