<?php
$l_artifact_title = "Hakea Teos";
$l_artifact_list_title = "Luettelo Hankitut Artifacts";
$l_artifact_noscan = "Your skannerit ei löydy artefakti.";
$l_artifact_noturn = "Sinulla ei ole tarpeeksi kääntyy poimia tämän artefakti.";
$l_artifact_classname = "Artefakta Nimi";
$l_artifact_description = "Teos Kuvaus";
$l_artifact_imagename = "Teos kuvaa";
$l_artifact_incomplete = "Teos Pieces";
$l_artifact_process = "Käytä Valmistui Teos";

?>
