<?php
$l_mail_title = "Sähköposti Salasana";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Salasana on lähetetty";
$l_mail_topic = "$ game_name Salasana";
$l_mail_message = "Tervehdys, \ n \ nSomeone alkaen IP-osoite $ IP pyytänyt salasanasi $ game_name lähetetään sinulle \ n \ nYour salasana: [pass] \ n \ nThank sinulle \ n \ nThe $ game_name Web-tiimi.";
$l_new_login = "Siirry kirjautumisnäyttöön.";
$l_mail_failed = "Salasana ei voitu lähettää";
?>
