<?php
$l_warp_linkto = "Linkit johtavat tämän alan";
$l_warp_nolink = "Ei ole yhteyksiä alan ulkopuolelle.";
$l_warp_query = "Mitä alalla haluat luoda linkin?";
$l_warp_oneway = "Yksisuuntainen?";
$l_warp_dest = "Vaihtoehtoisesti voit tuhota linkki alalle.";
$l_warp_destquery = "Mitä alalla haluat poistaa linkin?";
$l_warp_bothway = "Sekä-tapoja";
$l_warp_create = "Luo loimi välillä Ala:";
$l_warp_andsector = "ja Ala:";
$l_warp_distance = "joiden etäisyys";
$l_warp_lightyears = "valovuotta";
$l_warp_delete = "Poista loimi välillä Ala:";
$l_warp_costcreate = "Kustannukset luoda:";
$l_warp_costdelete = "Kustannukset poistaa:";
$l_warp_costenergy = "Energiahuollon tarvitaan:";
$l_warp_twoerror = "Käyttäen Warp Editor luoda kaksisuuntainen linkki alan [target_sector] ei ole sallittua.";
?>
