<?php
$l_zi_title = "Vyöhyketietoja";
$l_zi_nexist = "Tässä osassa tilaa ei löydy!";
$l_zi_feds = "Federaatiosta";
$l_zi_traders = "Alliance Space";
$l_zi_nobody = "Kukaan";
$l_zi_war = "Riidanalainen space";
$l_zi_allow = "Sallittu";
$l_zi_notallow = "Ei sallittu";
$l_zi_limit = "Rajoittaa omistaja ja liittolaiset";
$l_zi_ul = "Rajoittamattomat";
$l_zi_control = "Olet hallitse tämän alueen";
$l_zi_tochange = "muuttamaan lakejaan.";
$l_zi_owner = "Vyöhyke omistaja";
$l_zi_maxhull = "Enintään keskimäärin tech sallittu taso";
?>
