<?php
// New News Items

$l_news_planets = "planeetat";
$l_news_cols = "Euroa uudisasukkaita";
$l_news_p_headline = "[player] &#39;s Empire nyt [total] planeetat";
$l_news_c_headline = "[player] &#39;s Empire nyt [total] euroa valloittajia";
$l_news_p_textXX = "Liitto on antanut varoituksia valtakunta [name]. [name] on määräysvalta [total] planeetat ja olisi harkittava erittäin vaarallista. Kaikilla aloilla on lisättävä alan puolustuksemme välittömästi.";
$l_news_c_textXX = "Empire of [name] on meneillään massiivinen tilanahtauden planeetat yli [total] miljoonaa valloittajia. Elintarvikepula voi aiheuttaa levottomuutta. Kaikilla aloilla tulee olla tietoisia mahdollisista aggressiivisia toimia [name] tulevaisuudessa.";

$l_created_universe = "&quot;Universe Creation&quot;";
$l_created_universe_full = "&quot;Tutkijat tutkivat alkua Universumin ovat yksimielisesti päättäneet, että tänään on kaikkein tilastollisesti todennäköistä päivä Universe perustaminen on tapahtunut&quot;";

$l_news_p_text5 = "Kasvava Empire of [name] on nyt viisi planeettaa, FNN seuraamme toimia [name] tarkemmin tulevaisuudessa!";
$l_news_p_text10 = "Kasvava valtakunta [name] hallitsee nyt kymmenen planeetat, raportit FNN sanoa, että edelleen laajentamista [name] saattaisi johtaa sotaan!";
$l_news_p_text25 = "Valtava imperiumi [name] siirtomaana 25 planeettoja jo haastattelussa, [name] ilmoitti, että hän voisi harkita hidastavat hänen laajentamiseen tulevaisuudessa!";
$l_news_p_text50 = "Valtavan suuri valtakunta [name], jota edustaa 50 planeettaa koko galaksi on saada uhkaa vahvuus. Yksi FNN Toimittajat selville, että [name] on parantamisen hänen aluksen suunnittelun suuri sota. Haastattelussa [name] ilmoitti, että tehdään puolustus tarkoitukseen vain!";
$l_news_c_text25 = "Kasvava Empire of [name] on nyt 25 miljoonaa siirtokuntien FNN seuraamme toimia [name] tarkemmin tulevaisuudessa, mutta erittäin selvää, että syntyvyyden menossa räjähtää!";
$l_news_c_text100 = "Pyrkivä Empire of [name] on nyt 100 miljoonaa siirtolaiset, kun räjähdys syntyvyys, [name] siirtokuntia näytti olevan hyvä paikka perheille ratkaista!";
$l_news_c_text500 = "Suuri imperiumi [name] on nyt 500 miljoonaa siirtolaiset, [name] sanoi haastattelussa, että kolonialismin galaksin juuri vielä alkanut";
$l_news_c_text1000 = "Humongous Empire of [name] on nyt miljardi siirtolaiset, FNN reportterit huomasivat, että [name] on hallussaan outoja kloonauksen mekanismia, jossa hän kasvattaa uusien siirtokuntien valtavia määriä. Tämän määrän siirtokuntien econmic vahvuus imperiumi on valtava, FNN toivoo, että [name] ei ole viettänyt rahaa sodankäynti";

$l_news_indi_short = "FNN Huhu: yli [planets] julistaa itsenäisyyden.";
$l_news_indi = "FNN on se hyvä viranomainen, joka on yli [planets] planeetat ovat päättäneet, että ne ovat paremmin hallitsee itsensä ja ovat riippumattomia.";

$l_news_nova_short = "FNN Mietintö: [name] käyttää Nova Bomb.";
$l_news_nova = "FNN on tuoreita uutisia, että [name] on käyttänyt pelkäsivät Nova Bomb [total] aika (s) tuhota planeetan ja kaikki alukset sitä.";
$l_news_nova_m_short = "FNN Mietintö: [name] käyttää Nova Bomb ja osu.";
$l_news_nova_m = "FNN on tuoreita uutisia, että [name] on käyttänyt pelkäsivät Nova Bomb [total] aika (s) yrittää tuhota planeetan. Nova Pommi räjähti ulkopuolella planeettojen ilmakehässä ja aiheutti valtavia vahinkoja planeettojen infrastruktuuria.";

$l_news_bounty = "FNN Mietintö: [name] saattaa [amount] luoton armo on [name2].";

$l_news_attackerpod_p_short = "FNN Mietintö: [name] alus on tuhoutunut.";
$l_news_attackerpod_P = "[name] alus tuhoutui, kun hyökkää planeetta. Onneksi [name] oli Escape Pod ja selvisi.";

$l_news_attackerdie_p_short = "FNN Mietintö: [name] kuolee!";
$l_news_attackerdie_p = "[name] alus tuhoutui, kun hyökkää planeetta, ja he kuolivat, koska ne eivät ostaa Escape Pod.";

$l_news_destroyed_p_short = "FNN Mietintö: [name] iskut ja tuhoaa planeetan!";
$l_news_destroyed_p = "[name] hyökkäsi [total] Planet (t) omistaa [owner] ja väestön jokaisen planeetan tuhosi planeetan estää sen kiinni!";

$l_news_defeated_p_short = "FNN Mietintö: [name] hyökkäykset ja tappiot planeetta!";
$l_news_defeated_p = "[name] hyökkäsi [total] Planet (t) omistaa [owner] ja voitti planeettojen puolustusvoimat!";

$l_news_notdefeated_p_short = "FNN Mietintö: [name] iskujen Planet ja menettää!";
$l_news_notdefeated_p = "[name] hyökkäsi [total] Planet (t) omistama [owner] ja planeettojen puolustusta vastaan hallussa säälimätön iskut!";

$l_news_targetepod_short = "FNN Mietintö: [name] iskujen [owner] ja voittaa!";
$l_news_targetepod = "[name] hyökkäsi [owner] &#39;s alusta ja tuhosi sen täysin. Onneksi [owner] oli varustettu aluksella on Escape Pod ja he selvisivät.";

$l_news_targetdies_short = "FNN Mietintö: [name] iskujen [owner] ja tappaa heidät!";
$l_news_targetdies = "[name] hyökkäsi [owner] &#39;s alusta ja tuhosi sen täysin. Valitettavasti [owner] ei ole varustettu aluksella on Escape Pod ja ne höyrystetään.";

$l_news_fedcolbounty_short = "FNN Mietintö: Federation halkeamia alas [name]!";
$l_news_fedcolbounty = "Federaatiossa Tänään on säröillä alas kuuluisa Avaruuspiraatin [name]! [name], joka säännöllisesti rikkoneet useita tila perussopimusten oli lyhyesti palkkaamat federaation taisteluristeilijä, joka aiheutti [amount] luottojen arvosta vahinkoa Pirate&#39;s alus. Federation virkamiehet lupaavat edelleen tällaisia toimia tulevaisuudessa!";

$l_news_alliancecolbounty_short = "FNN Mietintö: Alliance halkeamia alas [name]!";
$l_news_alliancecolbounty = "Liittouma tänään säröillä alas kuuluisa Avaruuspiraatin [name]! [name], joka säännöllisesti rikkoneet useita tila perussopimusten oli lyhyesti palkkaamat Alliance, joka aiheutti [amount] luottojen arvosta vahinkoa Pirate&#39;s alus. Alliance virkamiehet lupaavat edelleen tällaisia toimia tulevaisuudessa!";

$l_news_fedcol_pbounty_short = "FNN Mietintö: Federation metsästävät alas [name]!";
$l_news_fedcol_pbounty = "Federaatiossa Tänään on säröillä alas kuuluisa Avaruuspiraatin [name]! [name], joka säännöllisesti rikkoneet useita tila perussopimusten oli lyhyesti palkkaamat federaation taisteluristeilijä, joka takavarikoitiin planeetan [planetname] arvo [amount] hyvitysten alalla [sector]. Federation virkamiehet lupaavat edelleen tällaisia toimia tulevaisuudessa!";

$l_news_alliancecol_pbounty_short = "FNN Mietintö: Alliance metsästävät alas [name]!";
$l_news_alliancecol_pbounty = "Liittouma tänään säröillä alas kuuluisa Avaruuspiraatin [name]! [name], joka säännöllisesti rikkoneet useita tila perussopimusten oli lyhyesti palkkaamat Alliance, joka takavarikoitiin planeetan [planetname] arvo [amount] hyvitysten alalla [sector]. Alliance virkamiehet lupaavat edelleen tällaisia toimia tulevaisuudessa!";

$l_news_fedcol_sbounty_short = "FNN Mietintö: Federation metsästävät alas [name]!";
$l_news_fedcol_sbounty = "Federaatiossa Tänään on säröillä alas kuuluisa Avaruuspiraatin [name]! [name], joka säännöllisesti rikkoneet useita tila perussopimusten oli lyhyesti palkkaamat federaation taisteluristeilijä, joka takavarikoi aluksen ([shiptype]) arvo [cost] sektori [sector]. Federation virkamiehet lupaavat edelleen tällaisia toimia tulevaisuudessa!";

$l_news_alliancecol_sbounty_short = "FNN Mietintö: Alliance metsästävät alas [name]!";
$l_news_alliancecol_sbounty = "Liittouma tänään säröillä alas kuuluisa Avaruuspiraatin [name]! [name], joka säännöllisesti rikkoneet useita tila perussopimusten oli lyhyesti palkkaamat Alliance, joka takavarikoi aluksen [shiptype] arvo [cost] sektori [sector]. Alliance virkamiehet lupaavat edelleen tällaisia toimia tulevaisuudessa!";

$l_killheadline = "[target] kuoli onnettomuudessa";
$l_news_killed = "[target] kuoli traagisessa onnettomuudessa tänään. Miten sankarillinen - [target] oli viimeinen jäsen aluksella hänen aluksen, kun hän huomasi, ettei ollut mitään paeta pod jätti hänelle. Levätköön hän rauhassa!";

$l_killSDheadline = "[target] surmasi Sector puolustuksemme.";
$l_news_killedSD = "[target] surmasi suuri määrä Ala Defenses omistamien [killer]! Surullista kyllä, alusta ei ollut varustettu paeta pod.";

$l_killplanetheadline = "[target] kuoli hyökkää planeetta.";
$l_news_killedplanet = "[target] kuoli, kun hyökkää planeetta omistama [killer] tänään. Valitettavasti alus ei ollut varustettu escape pod.";

$l_killshipheadline = "[target] kuoli aluksen torjumiseksi.";
$l_news_killedship = "[target] kuoli Alusten taisteluun [killer] tänään. Kapteeni ilmeisesti unohtanut varustaa laivan escape pod.";

$l_killsuicideheadline = "[target] teki itsemurhan.";
$l_news_killedsuicide = "[target] teki itsemurhan tänään. He ottivat pelkurit ulos, koska heillä ei ollut kykyä tai rohkeutta ja paineita komentaessaan oman aluksen.";

$l_killsofaheadline = "[target] kuoli sohvalla hyökkää planeetta.";
$l_news_killedsofa = "[target] kuoli, kun sohva hyökkää planeetta omistaa [killer] tänään. Valitettavasti alus ei ollut varustettu escape pod.";

$l_killnovaheadline = "[target] sai surmansa Nova hyökkäyksen.";
$l_news_killednova = "[target] surmasi [killer] aikana Nova pommi-iskun tänään. Valitettavasti alus ei ollut varustettu escape pod.";

$l_killnovabackfireheadline = "[target] kuoli alkaen Nova kostautua.";
$l_news_killednovabackfire = "[target] kuoli, kun heidän Nova pommi kostautui tänään. Valitettavasti alus ei ollut varustettu escape pod.";

$l_killsectormissileheadline = "[target] kuoli peräisin Sector ohjus.";
$l_news_killedsectormissile = "[target] kuoli, kun ala ohjusten alkaen [killer] vaikuttanut heidän kilvet. Valitettavasti alus ei ollut varustettu escape pod.";

$l_killhunterprobeheadline = "[target] kuoli alkaen Hunter Probe.";
$l_news_killedhunterprobe = "[target] kuoli, kun Hunter Probe alkaen [killer] vaikuttanut heidän kilvet. Valitettavasti alus ei ollut varustettu escape pod.";

$l_killtrapprobeheadline = "[target] kuoli alkaen Sentry Trap Probe.";
$l_news_killedtrapprobe = "[target] kuoli, kun Sentry Trap Probe alkaen [killer] vaikuttanut heidän kilvet. Valitettavasti alus ei ollut varustettu escape pod.";

//-------------------

$l_killpodheadline = "[target] &#39;s alus tuhoutui onnettomuudessa";
$l_news_killedpod = "[target] &#39;s alus tuhoutui traagisessa onnettomuudessa tänään. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killSDpodheadline = "[target] &#39;s alus tuhoutui Sector puolustuksemme.";
$l_news_killedSDpod = "[target] &#39;s alus tuhoutui suuri määrä Ala Defenses omistamien [killer]! Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killplanetpodheadline = "[target] &#39;s alus tuhoutui hyökkää planeetta.";
$l_news_killedplanetpod = "[target] &#39;s alus tuhoutui, kun hyökkää planeetta omistaa [killer] tänään. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killshippodheadline = "[target] &#39;s alus tuhoutui aluksen torjumiseksi.";
$l_news_killedshippod = "[target] &#39;s alus tuhoutui Alusten taisteluun [killer] tänään. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killsofapodheadline = "[target] &#39;s alus tuhoutui, kun sohva hyökkää planeetta.";
$l_news_killedsofapod = "[target] &#39;s alus tuhoutui, kun sohva hyökkää planeetta omistaa [killer] tänään. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killnovapodheadline = "[target] &#39;s alus tuhoutui Nova hyökkäyksen.";
$l_news_killednovapod = "[target] &#39;s alus tuhoutui [killer] aikana Nova pommi-iskun tänään. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &#39;s alus tuhoutui peräisin Nova kostautua.";
$l_news_killednovabackfirepod = "[target] &#39;s alus tuhoutui kun heidän Nova pommi kostautui tänään. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &#39;s alus tuhoutui Sector Missile.";
$l_news_killedsectormissilepod = "[target] &#39;s alus tuhoutui, kun ala ohjusten alkaen [killer] vaikuttanut heidän kilpensä. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &#39;s alus tuhoutui Hunter Probe.";
$l_news_killedhunterprobepod = "[target] &#39;s alus tuhoutui, kun Hunter Probe alkaen [killer] vaikuttanut heidän kilpensä. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &#39;s alus tuhoutui Sentry Trap Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s alus tuhoutui, kun Sentry Trap Probe alkaen [killer] vaikuttanut heidän kilvet. Escape Pod mikrosiru on havaittu federaation Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] on ylennetty [rank]";
$l_news_promoted = "Liitto on ilo ilmoittaa edistämiseen [name] sijoitusta [rank].";

$l_news_demotedheadline = "[name] on rappeutua ja [rank]";
$l_news_demoted = "Liitto pahoittelee ilmoittaa alentaminen on [name] sijoitusta [rank].";

$l_news_namechangedheadline = "[oldname] vaihtoi nimensä [newname]";
$l_news_namechanged = "[oldname] sovelletaan liitto Review Board muuttaa nimensä [newname]. Liitto on myöntänyt nimenmuutos. Tästä päivästä eteenpäin [oldname] on nyt kutsutaan [newname]. Kaikki alukset ja planeettojen tulisi päivittää tiedot välittömästi.";

$l_news_found_planets_short = "Federation Survey: [found_planets] uusi planeetat sijaitsee.";
$l_news_found_planets = "Federation Survey Partiolaiset löytänyt [found_planets] uutta planeettaa äskettäin löydetty aloilla.";

$l_news_new_ports_short = "Federation Survey: [new_ports] uusia satamia rakennetaan.";
$l_news_new_ports = "Federation Insinöörit ovat rakentaneet [new_ports] uusien satamien äskettäin löydetty aloilla.";

$l_news_addedsectors_short = "Federation Survey: [addedsectors] aloilla löydetty.";
$l_news_addedsectors = "Federation Survey partiolaiset ovat löytäneet [addedsectors] uusille aloille. Varovaisuutta on noudatettava.";

$l_news_artifactheadline = "[playername] päätökseen [artifact]";
$l_news_artifact = "[playername] on todennut kaikki palat [artifact] ja on kaikki, se voi tarjota.";

$l_news_artifactfoundheadline = "[playername] löytyi [artifact] kpl";
$l_news_artifactfound = "[playername] on todettu yksi kappaletta [artifact] ja tarpeet [pieces] lisää [pieces].";

?>
