<?php
$l_ship2_buytitle = "Ostaa uusi alus";
$l_ship2_storetitle = "Shipyard varastoon";
$l_ship2_wrongclass = "Väärä aluksen luokka määritelty";
$l_ship2_buying = "Olet ostamassa:";
$l_ship2_tradein = "Trade In:";
$l_ship2_value = "Nykyinen Ship Arvo:";
$l_ship2_newvalue = "Uusi alus Arvo:";
$l_ship2_totalcost = "Hinta Yhteensä:";
$l_ship2_nomoney = "Sinulla ei ole tarpeeksi luottoja ostaa tämän laivan.";
$l_ship2_purchase = "Ostaa";
$l_ship2_buynstore = "Osta uusi alus ja säilytä vanha";
$l_ship2_nomoney2 = "Sinulla ei ole tarpeeksi luottoja tapahtuman suorittamiseen.";
$l_ship2_paystorage = "Sinun on poistanut aluksen varastosta.";
$l_ship2_turns = "Tarvitset vähintään [turns] kääntyy tämän toimenpiteen suorittamista";
$l_ship2_error = "Sisäinen virhe. Can&#39;t find aluksen luokka.";
$l_ship2_owned = "Omistat jo tämän mallin aluksen.";
$l_ship2_shipbought = "Olet juuri ostanut uuden aluksen!";

?>
