<?php
$l_profile_title = "Profiili Rekisterˆinti";
$l_profile_notenabled = "Profiilit eiv‰t ole k‰ytˆss‰ t‰ll‰ palvelimella.";
$l_profile_registered = "T‰m‰ pelaaja on nyt rekisterˆity Master Profile Server.";
$l_profile_nomatch = "Voinut Match profiili Master Server-nimen ja palvelimen salasanaa.";
$l_profile_tryagain = "Tehd‰ soittimesi profiilin nimi ja palvelimen salasana uudelleen napsauttamalla";
$l_profile_name = "Profiili Pelaajan nimi";
$l_profile_password = "Profiili Server Salasana";
$l_profile_bannedserver = "T‰m‰ palvelin ei saa toimittaa profiilin tiedot Master Profile Server.";
$l_profile_bannedplayer = "Sinulla on kielletty Master Server-ja saa rekisterˆid‰ pelaajia.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "T‰m‰ palvelin <u><b>edellytt‰‰, ett‰</b></u> jokainen uusi pelaaja on rekisterˆity profiilia. Sinua ei saa luoda uuden soittimen, jos sinulla ei ole rekisterˆity profiilia.";
$l_profile_updated = "Malli, Shoutbox ja Uutisindeksoinnin yleiset asetukset on p‰ivitetty Profile Master Server. N‰it‰ asetuksia k‰ytet‰‰n automaattisesti, kun olet rekisterˆinyt profiilin tahansa peliin.";

?>
