<?php
$l_footer_one_player_on = "On 1 pelaaja online.";
$l_footer_players_on_1 = "Olemassa";
$l_footer_players_on_2 = "Pelaajia linjoilla:";
$l_footer_until_update = "sekunnin ajan, kunnes seuraavassa päivityksessä.";
$l_footer_no_players_on = "Ole pelaajaa linjalla.";

$l_footer_news = "Paikalliset FNN News";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = "apua tästä sivusta.";
$l_footer_click = "Napsauta";

$l_footer_open_slots = "Suurin Online:";
$l_footer_onlinereset = "Pelaaja Online Time tehdasasetusten palautus";
$l_footer_onlinecountdown = "Näköinen Online Time Countdown:";
?>
