<?php
$l_contact_admin_title = "Yhteystiedot Game Administrator";
$l_contact_admin_thanks = "Thanks for your comment.";
$l_contact_admin_email_alert = "Anna voimassa oleva sähköpostiosoite.";
$l_contact_admin_name_alert = "Anna nimesi.";
$l_contact_admin_comment_alert = "Syötä kommentteja.";
$l_contact_admin_name = "Nimi";
$l_contact_admin_email = "Sähköposti";
$l_contact_admin_comment = "Kysymys / Kommentti";
$l_contact_admin_submit = "Esittää kysymyksiä / kommentteja";
$l_contact_admin_close = "Sulje ikkuna";
$l_contact_admin_thanks_comment = "Kiitos kommentti tai kysymys. Teemme kaikkiin kysymyksiin ja lähettää sinulle sähköpostia kanssa vastauksen.";

?>
