<?php
$l_defense_deploy_title = "Käyttöön Sector Mines-Fighters";
$l_defense_deploy_noturn = "Tarvitset ainakin yksi vuoro käyttää alan puolustuksemme.";
$l_defense_deploy_nopermit = "Käyttöönottoon kaivokset ja Fighters tällä alalla ei ole sallittua.";
$l_defense_deploy_nodeploy = "Ei voi käyttää täällä. Toinen alus tai Team on kaivoksia tai taistelijoiden tällä alalla.";
$l_defense_deploy_info1 = "Olet tällä hetkellä sektori [sector]. On [mines] kaivosten ja [fighters] taistelijoita täällä.";
$l_defense_deploy_info2 = "Olette [mines] kaivosten ja [fighters] Fighters käytettävissä käyttöön";
$l_defense_deploy_deploy = "Lähettämään";
$l_defense_deploy_deployed = "Deployed";
$l_defense_deploy_att = "Hyökkäystä";
$l_defense_deploy_notorps = "Sinulla ei ole tarpeeksi torpedot.";
$l_defense_deploy_nofighters = "Sinulla ei ole tarpeeksi Fighters";
$l_defense_deploy_dmines = "Käyttöön [mines] miinoja.";
$l_defense_deploy_dfighter = "Käyttöön [fighters] taistelijoita.";
$l_defense_deploy_max_fighters = "Tämä sektori voi tukea enintään [amount] taistelijoita.";
$l_defense_deploy_toomanyfighters = "Olet yrittänyt käyttää enemmän hävittäjiä kuin sektori voi tukea.";
?>
