<?php
$l_ze_title = "Edit Zone";
$l_ze_notowner = "Et ole omistaja tämän alueen niin et voi muokata sitä.";
$l_ze_name = "Alueen nimi";
$l_ze_allow = "Sallia";
$l_ze_attacks = "Salli hyökkäämään muihin aluksiin";
$l_ze_genesis = "Mahdollistaa uusien planeettojen";
$l_ze_return = "palata alueelle tiedot page";
$l_ze_saved = "Tekemäsi muutokset on tallennettu.";
$l_ze_namematch = "VIRHE: Zone nimen jos on samanlainen tai vastaa nykyisen alueen nimi.";
?>
