<?php
$l_gns_title = "Käytä Genesis Device";
$l_gns_turn = "Tarvitset ainakin yhden vuoron käyttää Genesis laitetta.";
$l_gns_onplanet = "Voi käyttää tätä laitetta, kun planeetan pinnalle.";
$l_gns_full = "Tämä aurinkokunta on jo täynnä.";
$l_gns_planetex = "On jo planeetta tällä alalla.";
$l_gns_nogenesis = "Sinulla ei ole mitään Genesis laitteita.";
$l_gns_forbid = "Luominen Planet tällä alalla ei ole sallittua.";
$l_gns_bforbid = "Perustaa tällä alalla häiritsevät teidän Genesis laitteeseen. Planet luominen ei ole mahdollista.";
$l_gns_pcreate = "Planet luotu.";
$l_sgns_title = "Käytä Sector Genesis Device";
$l_sgns_pcreate = "Alalla [name] luotiin.";
$l_sgns_nogenesis = "Sinulla ei ole mitään alan Genesis laitteita.";
$l_sgns_forbid = "Luominen alan Genesis madonreikä tällä alalla ei ole sallittua.";
$l_sgns_forbid1 = "Luominen alan Genesis madonreikä federaation Ala ei ole sallittua.";
$l_sgcreate = "Luo uusi Ala Genesis Sector";
$l_sgcreatens = "Luo uusi Ala Genesis linkin takaisin tiedossa avaruuteen";
$l_sgns_forbid2 = "Lisää yli [limit] linkkejä SG alat eivät ole sallittuja.";
$l_sgns_forbid3 = "Ei voi luoda Ala Genesis taivuttaa linkki nykyisestä sektorin - joka ylittää enintään [limit] aloittain.";
$l_sgns_nocredits = "Sinulla ei ole tarpeeksi luottoja luoda uutta alaa.";
$l_sgns_shipcredits = "Laajuus laivalla:";
$l_sgns_createcost = "Kustannukset uusien Ala:";
$l_sgns_complete = "Normaali avaruus Link Complete";
$l_sgns_sectorname = "Anna Ala Nimi:";
$l_gns_max_unbased_planets = "Liitto ei ole mahdollista luoda enemmän planeettoja, kunnes olet alle [max_unbased_planets] unbased planeettoja.";

?>
