<?php
$l_novabomb_turns = "Nova Bomb edellyttää atleast [turns] muuttuu tuleen.";
$l_novabomb_planetsdamaged = "Planeetat vahingoittuneiden Nova Bomb";
$l_novabomb_planet = "Planet [name] kärsinyt vahinkoja Nova Bomb.";
$l_novabomb_novaexplode = "Nova räjähti pommi, koska se oli ammuttu ja sinun alus on kärsinyt vakavia vaurioita.";
$l_novabomb_novaexplode2 = "Nova räjähti pommi, koska se oli ammuttu ja teidän alus tuhoutui.";
$l_novabomb_notfedsec = "Nova Bomb ei voida käyttää liiton omistuksessa aloilla.";
$l_novabomb_destroyed_planet = "Sinun Nova pommi säröillä maapallon pinnasta ja porattu ytimeen, jossa se räjähti aiheuttaen maapallon särkyvät.";
$l_novabomb_wrongclass = "Tämä laiva luokkaan ei voida ampua Nova Bomb laite.";
$l_novabomb_nonova = "Sinulla ei ole Nova Bomb asennettu.";
$l_novabomb_novamiss = "Nova Bomb suppeasti piti vaan aiheutetaan vahinkoa, kun maapallolla.";
$l_novabomb_success = "Sector [sector] on Nova Pommitettu!";
$l_novabomb_mines = "Hävitetään [mines] sektorin Mines.";
$l_novabomb_fighters = "Hävitetään [fighters] sektorin Fighters.";
$l_novabomb_shipsdamaged = "Alusten vahingoittuneiden Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] kärsinyt vahinkoja Nova Bomb.";
$l_novabomb_ship_survived = "Voit laiva oli riittävän kaukana, kun Nova räjähti pommi, jotta vältetään vahingot.";
?>
