<?php
$l_warp_cantsame = "Et voi luoda linkin, kun lähde on sama kuin määränpää.";
$l_warp_twoerror = "Käyttäen Warp Editor luoda kaksisuuntainen linkki alan [target_sector] ei ole sallittua.";
$l_warp_sectex = "Voi luoda loimi linkkiä nykyisten alalla - joka ylittää enintään $ link_max alaa kohden.";
$l_warp_linked = "Kohdealaksi ([target_sector]) on jo linkki tällä alalla.";
$l_warp_coneway = "Linkki luotu yksi tapa";
$l_warp_ctwoway = "Linkki luotu ja";
$l_warp_nomoney = "Sinulla ei ole tarpeeksi luottoja luoda loimen linkkiä.";
$l_warp_noenergy = "Sinulla ei ole tarpeeksi energiaa luoda loimen linkkiä.";
?>
