<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Probe tasojen";
$l_probe_engine = "Moottoriin";
$l_probe_sensors = "Anturit";
$l_probe_cloak = "Viitan";
$l_probe_title = "Avaruusluotaimesta Valikko";
$l_probe_none = "Et ole samalla alalla kuin tämä koetin, joten voit olla vuorovaikutuksessa sen kanssa.";

$l_probe_named = "Tervetuloa Probe lukumäärä [probename], jonka omistaa [name], joka sijaitsee alalla [sector].";
$l_probe_orders = "[orders] koetin etsiä universe";
$l_probe_orders_link = "Program";
$l_probe_upgrade = "[upgrade] Probe Anturit / Moottori / Viitta";
$l_probe_upgrade_link = "Päivityksen";
$l_probe_pickup = "[pickup] Probe myöhemmin sijoitus";
$l_probe_pickup_link = "Lukupään";
$l_probe_update = "Päivittää";

$l_probe_att_link = "Hyökkäystä";
$l_probe_att = "[attack] on anturi";
$l_probe_att_sure = "Oletko varma ...";
$l_probe_scn_link = "Skannaa";
$l_probe_scn = "[scan] anturi";

$l_probe_unknown = "Tiedetä";
$l_plant_scn_turn = "Tarvitset ainakin yhden vuoron skannata anturi.";
$l_probe_noscan = "Antureita ei saa asettaa aikataulussa!";
$l_probe_logscanA = "[name] yrittänyt skannaamme kuumatkat sektori [sector], mutta epäonnistui.";
$l_probe_logscanB = "Joku antureista sektori [sector] oli skannata [name].";
$l_probe_scn_report = "Scan tulokset [name], jonka omistaa: [owner]";

$l_probe_caplog = "Your anturi &quot;[probename]&quot; sektori [sector] valtasivat [name].";
$l_probe_scan = "Probe skannaa alalla [sector] ja toteaa:";
$l_probe_destroyprobe = "Destroy anturi";
$l_probe_destroyed = "Probe Destroyed!";
$l_probe_warning = "Näin on tuhota täysin tämän koetin";
$l_probe_confirm = "Haluatko varmasti tuhota tämän koetin?";
$l_gns_turn = "Sinulla ei ole tarpeeksi muuttuu tuhota tämän koetin";
$l_probe_type = "Probe Type";
$l_probe_type0 = "Paikallaan Probe";
$l_probe_type1 = "Sentrylle Probe";
$l_probe_type2 = "Warp silavakiikari";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sarjasäädin Realspace Probe";
$l_probe_target = "Kohdealaksi";
$l_probe_ordered = "Koetin ohjelmoitu ja alkaa hakua.";
$l_probe_order2 = "Koetin on [type] ja kohdentamiseen ala [target]";
$l_probe_pickedup = "Koetin piristyi ja asetetaan aktiiviseen varastoon";
$l_probe_title = "Probe Valikko";
$l_probe_messages = "nähdä, mitä vakoilijoita on havaittu.";

$l_probe_defaulttitle1 = "Aktiivinen Probes";
$l_probe_defaulttitle2 = "Probes olet kyytiin";
$l_probe_defaulttitle3 = "Probes teidän planeetoilla";
$l_probe_defaulttitle4 = "Probes teidän aluksen";
$l_probe_linkback = "Siirry koetin valikosta.";
$l_probe_no1 = "Sinulla ei ole aktiivisia probes.";
$l_probe_no2 = "Sinulla ei ole mitään koettimet varastossa.";
$l_probe_no3 = "Sinulla ei ole mitään koetin teidän planeetoilla.";
$l_probe_no4 = "Sinulla ei ole mitään koetin teidän aluksella.";
$l_probe_noprobeatall = "Sinulla ei ole mitään probes.";
$l_probe_notknown = "Tiedetä";
$l_probe_launch = "Pudottaa";
$l_probe_detect = "Detected";
$l_probe_codenumber = "Koodi";
$l_probe_job = "Työ";
$l_probe_percent = "Prosenttiin";
$l_probe_move = "Movement";
$l_probe_view = "Näytä";
$l_probe_action = "Toimen";
$l_probe_shipowner = "Aluksen omistaja";
$l_probe_shipname = "Aluksella nimi";
$l_probe_shiptype = "Aluksen luokka";
$l_probe_shiplocation = "Laiva Sijainti";
$l_probe_planetowner = "Planet Omistaja";
$l_probe_planetname = "Planet";
$l_probe_sector = "Nykyinen Sector";
$l_probe_tsector = "Kohdealaksi";
$l_probe_type = "Probe Type";
$l_probe_forbid = "Et voi pudota koettimet tällä alalla";

$l_probe2_title = "Launch Space Probe";
$l_probe2_turn = "Tarvitset ainakin yhden vuoron käyttää avaruusluotain.";
$l_probe2_onplanet = "Voi käyttää tätä laitetta, kun planeetan pinnalle.";
$l_probe2_noprobe = "Sinulla ei ole mitään avaruusluotaimet.";
$l_probe2_forbid = "Käynnistäminen anturi tällä alalla ei ole sallittua.";
$l_probe2_launched = "Avaruusluotain avattu!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Playerin";
$l_probe2_onboarda = "aluksella";
$l_probe2_classship = "luokan alus";
$l_probe2_traveled = "matkusti alan";
$l_probe2_fedjammed = "Federaatio on häirintä kaikki anturi skannaa Sector 1.";
$l_probe2_lastseen = "Viimeksi Ship Seen";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Tukevat";
$l_probe2_planets = "planeetat";
$l_probe2_sectord = "Alan puolustus Detected";
$l_probe2_mines = "Miinoja";
$l_probe2_fighters = "Fightersin";
$l_probe2_ships = "Alusten Tunnistettu";
$l_probe2_ships2 = "Laiva Detected";
$l_probe2_noneowned = "O planeetoilla ei omista sinulla on havaittu.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Mikään ei havaittu";
$l_probe2_nocredits = "Sinulla ei ole riittävästi määrärahoja tähän liiketoimeen. Kokonaiskustannukset [total] luottoja ja sinulla on vain [credits] opintoviikkoa.";

$l_probe_forbidSG = "Et voi lähettää Realspace tyyppi mittapää Ala Genesis luotu aloilla.";
$l_probe_forbidFED = "Et voi lähettää Realspace tyyppi mittapää liitto tai liiton omistuksessa aloilla.";
$l_probe_forbidINVALID = "Kohde-ala on virheellinen ala nimi.";
?>
