<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Unchartered space";
$l_zname[2] = "Federation space";
$l_zname[3] = "Alliance space";
$l_zname[4] = "Sotatoimialuetta";

$l_nova = "Novan";
$l_nova = "Novan Bomb";
$l_lssd = "Viimeksi aluksen nähnyt laitteen";
$l_lss = "Viimeksi aluksen nähnyt alalla";

// Common to : warpedit 1-3.php

$l_warp_title = "Käytä Warp Editor";
$l_warp_turn = "Tarvitset ainakin yhden vuoron käyttää loimi editori.";
$l_warp_none = "Sinulla ei ole mitään loimi toimitukselle.";
$l_warp_forbid = "Käyttäen Warp Julkaisija tällä alalla ei ole sallittua.";
$l_swarp_forbid = "Käyttäen Warp Editor tai SG aloilla ei ole sallittua.";
$l_warp_nosector = "Alalla ei ole olemassa.";

// Not yet confirmed common to multiple files:

$l_yes = "Kyllä";
$l_no = "Ei";
$l_here = "tässä";
$l_submit = "Lähettää";
$l_reset = "Nollataan";
$l_all = "Kaikki";
$l_max = "Enint";

$l_trade = "Kauppa";
$l_ore = "Rautamalmin";
$l_commodity = "Hyödykkeenä";
$l_commodities = "Perustuotteet";
$l_organics = "Orgaanisilla";
$l_goods = "Tavarat";
$l_energy = "Energiahuollon";
$l_colonists = "Uudisasukkaan";
$l_credits = "Hyvityksiä";
$l_units = "yksiköissä";
$l_special = "Erityispainos";
$l_upgrade_ports = "Päivityksistä";
$l_device_ports = "Laitteilla";
$l_spacedock = "Spacedock";
$l_casino = "Kasinolla";
$l_dig = "Arvohenkilöitä";
$l_spy = "Vakoilijoita";

$l_cargo = "Lastia";
$l_fighters = "Fightersin";
$l_mines = "Miinoja";
$l_torps = "Torpedoja";

$l_none = "Ei mitään";
$l_unnamed = "Nimeämättömät";
$l_name = "Nimi";
$l_unowned = "Unowned";
$l_unknown = "Tiedetä";
$l_clickme = "Klikkaa";
$l_player = "Playerin";
$l_ship = "Alus";
$l_ships = "Aluksista";
$l_set = "sarja";
$l_realspace = "Realspace";
$l_armorpts = "Armor pistettä";
$l_links = "Yhteyksiä";
$l_login_email = "Sähköposti:";
$l_add = "Lisää";
$l_teamforum = "Team Forum";
$l_teamships = "Team Laivat";
$l_tutorial = "Tutorial / Ohjeet";
$l_avatar = "Avatarisi";
$l_teamicon = "Team Icon";
$l_debris = "Raunioista";
$l_localmap = "Paikallinen kartta";
$l_arm_weap = "Armor &amp; aseita";
$l_3dmap = "3D Galaxy Kartta";

$l_sectormissile = "Alan Missile";
$l_spacebeacon = "Avaruudessa Beaconin";
$l_spaceprobes = "Avaruusluotaimet";
$l_warpeditors = "Warp toimittajien";
$l_genesistorps = "Syntyhistoriaan Torpedot";
$l_sgtorps = "SG Torpedot";
$l_minesfighters = "Mines / Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Raportteja";
$l_shipinfo = "Aluksen listasta";
$l_sectornotes = "Alan Notes";
$l_maps = "Karttoihin";
$l_messages = "Viestien";
$l_shiptype = "Alustyyppi";
$l_help = "Apu";
$l_rank = "Listalla";

$l_teamplanets = "Team Planeetat";
$l_teamdefenses = "Team puolustusta";
$l_planetstatus = "Planet tila";
$l_planetdefenses = "Planet puolustuksemme";
$l_changeproduction = "Muuta Tuotanto";
$l_galacticarm = "Galaktiset Käsien";

$l_armor = "Panssaroinnin";
$l_news_none = "Sorry, no uutisia tänään.";

$l_ranks_good = "Hyvä";
$l_ranks_evil = "Paha";
$l_ranks_neutral = "Neutraaleja";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Alue on nyt War Zone!";
$l_global_nzone = "Alue on neutraali vyöhyke.";
$l_global_team = "Alue kuuluu nyt Team";
$l_global_player = "Alue kuuluu nyt pelaaja";
$l_global_nochange = "Vyöhykkeen omistus ei muuttunut";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "O-1.png";
$l_insignia[5] = "O-2.png";
$l_insignia[6] = "O-3.png";
$l_insignia[7] = "O-4.png";
$l_insignia[8] = "O-5.png";
$l_insignia[9] = "O-6.png";
$l_insignia[10] = "O-7.png";
$l_insignia[11] = "O-8.png";
$l_insignia[12] = "O-9.png";
$l_insignia[13] = "O-10.png";
$l_insignia[14] = "O-11.png";
$l_insignia[15] = "O-12.png";
$l_insignia[16] = "O-13.png";
$l_insignia[17] = "O-14.png";
$l_insignia[18] = "O-15.png";
$l_insignia[19] = "O-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Avaruusmies";
$l_insignia_name[3] = "Kersantti kolmannen luokan";
$l_insignia_name[4] = "Kersantti toinen luokka";
$l_insignia_name[5] = "Kersantti First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Merkkiviirinä";
$l_insignia_name[10] = "Lieutenant Junior Grade";
$l_insignia_name[11] = "Lieutenant";
$l_insignia_name[12] = "Komentajakapteeni";
$l_insignia_name[13] = "Komentaja";
$l_insignia_name[14] = "Kapteeniksi";
$l_insignia_name[15] = "Amiraali (alaosa)";
$l_insignia_name[16] = "Amiraali (yläosa)";
$l_insignia_name[17] = "Vara-amiraali";
$l_insignia_name[18] = "Amiraali";
$l_insignia_name[19] = "Fleet Admiral";

$l_main_title = "Päävalikon";
$l_main_warpto = "Taivutuksen";
$l_main_autoroute = "AutoRoute to";
$l_main_rs_to = "RSMove ja";
$l_main_other = "Muu";
$l_main_shipyard1 = "Telakalta";
$l_main_shipyard2 = "Pääsyä";
$l_traderoutes = "Kauppareitit";
$l_trade_control = "Kaupan valvontaa";
$l_youhave = "Sinulla";
$l_turns_used = "Turns käytetään:";
$l_turns_have = "Turns saatavilla:";
$l_score = "Pisteet:";
$l_sector = "Sector";
$l_help = "Apu";
$l_faq = "UKK";
$l_feedback = "Palaute";
$l_forums = "Foorumien";
$l_logout = "Uloskirjautumista";
$l_commands = "Komentojen";
$l_command_no = "Komento ei ole käytettävissä.";
$l_devices = "Laitteilla";
$l_planets = "Planeettoja";
$l_log = "Lokin";
$l_sector_def = "Alan puolustuksemme";
$l_defense = "Puolustukset";
$l_read_msg = "Lue viestit";
$l_send_msg = "Lähettää viestejä";
$l_rankings = "Sijoituslista";
$l_teams = "Joukkueiden";
$l_ohno = "Itsetuhomekanismia";
$l_options = "Valinnat";
$l_navcomp = "Nav Computer";
$l_incompletemove = "Ettet ole aikaisempia liikkua.";
$l_clicktocontinue = "Klikkaa tästä jatkaaksesi";
$l_toplanetmenu = "Siirry Planet valikosta.";
$l_nonexistant_pl = "Käytössä olematon planeetalla???";
$l_abord = ", Kyytiin";
$l_messages_wait = "Lähettämistä odottavat sinua.";
$l_no_warplink = "O loimi linkkejä";
$l_scan = "skannaa";
$l_fullscan = "Full Scan";
$l_port = "Port";
$l_tradingport = "Kauppasatama";
$l_planet_in_sec = "Planeetat alan";
$l_ships_in_sec = "Muut alukset alan";
$l_sector_0 = "On niin paljon liikennettä Sol, että et voi edes erottaa muita aluksia!";
$l_map = "Karttaa";
$l_probe = "Näytteenottimista";
$l_autotrade = "Autotrades";
$l_onboard = "alukselle";
$l_classship = "luokan alus";
$l_traveled = "matkusti alan";
$l_max_planets = "Suurin habital planeetat";
$l_block_msg = "Estää viestit";
$l_sectorinfo = "Sektorin listasta";
$l_add_note = "Lisää huomautus";
$l_view_note = "Näytä";
$l_notes = "Huomauttaa";
$l_global_limitreached = "Olet saavuttanut rajan määrää, kun saavat olla verkossa joka päivä. Sisään uudelleen huomenna puolenyön jälkeen.";
$l_onlinetimeleft = "Jäljellä oleva aika:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Tallennettu Laivat";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Edellinen sivu";
$l_common_next = "Seuraava sivu";
$l_common_totalpages = "Yhteensä sivuja";
$l_common_selectpage = "Valitse sivu:";
$l_common_page = "Sivulle:";
$l_templatechange = "Haluatko säilyttää tämän mallin?";

$l_im_fed_bounty = "Liitto on asettanut armo teitä varten hyökkää niin alhainen paremmuusjärjestykseen pelaaja. Federaation hyökkäävät teidän aluksen säännöllisesti, kunnes maksat takaisin teidän armo. Voit maksaa pois Bounty milloin tahansa Päivitä Port tai Spacedock.";
$l_im_fed_bounty_title = "Federation saattaa Bounty teille!";
$l_im_alliance_bounty = "Liittouma on asettanut armo teitä varten hyökkää niin alhainen paremmuusjärjestykseen pelaaja. Liittouma hyökkäävät teidän aluksen säännöllisesti, kunnes maksat takaisin teidän armo. Voit maksaa pois Bounty milloin tahansa Päivitä Port tai Spacedock.";
$l_im_alliance_bounty_title = "Alliance sijoitettu Bounty teille!";
$l_instant_messages_waiting = "Sinulla on [count] viestejä odottavat sinua.";

$l_home_planet = "Kotiplaneettansa";

$l_hold_space_used = "Otteet Täytetty:";
$l_hold_space_free = "";
$l_port_buys = "Port Buys:";

?>
