<?php
$l_readm_title = "Lue viesti";
$l_readm_delete = "VIESTIN POISTAMANI";
$l_readm_nomessage = "Sinulla ei ole viestejä waiting for you ...";
$l_readm_center = "Viesti vastaanottaminen Center";
$l_readm_sender = "Viestin lähettäjälle";
$l_readm_captn = "Kapteeni";
$l_readm_del = "Poistaa";
$l_readm_repl = "Vastata";
$l_readm_return = "Klikkaa tästä palataksesi päävalikkoon";
$l_readm_title2 = "Sähköpostiohjelmasi";
$l_readm_delete = "Poista kaikki";
$l_readm_subject = "Aihe";
$l_readm_quote = "Lainaus";
$l_readm_block = "Block Sender";
$l_readm_alert = "System Alert";
$l_readm_alertbody = "Laiva Computer";
?>
