<?php
$l_opt_title = "Valinnat";
$l_opt_chpass = "Vaihda salasana";
$l_opt_curpass = "Nykyinen salasana:";
$l_opt_newpass = "Uusi salasana:";
$l_opt_newpagain = "New password (again):";
$l_opt_userint = "Käyttöliittymään";
$l_opt_usenew = "Käytä uutta ulkoasua?";
$l_opt_lang = "Kieli";
$l_opt_template = "Mallipohjan";
$l_opt_select = "Valitse yksi:";
$l_opt_enabled = "Mahdollisti";
$l_opt_save = "Tallentaa";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Paikalliset ja Galaxy Kartta Leveys:";
$l_opt_profiletitle = "Profiili";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Rekisteröity Server -";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Kun olet rekisteröinyt soittimen toiselle palvelimelle mallin sivustosta ja News-asetukset ennen käytetään palvelimessa.";
$l_opt_showshoutbox = "Näytä Shoutbox:";
$l_opt_shownewscrawl = "Näytä Uutisindeksoinnin:";
$l_opt_playername = "Pelaajan nimi:";
$l_opt_playernamecost = "Federation Nimenmuutos Fee: [amount] Laajuus";
?>
