<?php
$l_opt_title = "Valitse Team Icon";
$l_opt_errorsize = "Virhe: Kuvasi eivät saa olla suurempi kuin 64x64 pikseliä kooltaan.";
$l_opt_errortype = "Virhe: Kuvan on oltava JPG-, GIF-tai PNG";
$l_opt_errornographic = "Virhe: graafinen valittu.";
$l_opt_currentavatar = "Nykyinen Team Icon";
$l_opt_uploadavatar = "Lataa Icon";
$l_opt_directory = "Valitse Team Icon Directory";
$l_opt_change = "Muutos";
$l_opt_select = "Valitse Team Icon";
$l_opt_noteam = "Et ole joukkue.";
$l_opt_notleader = "Ainoastaan koordinaattori voi muuttaa Team Icon.";
$l_opt_inuse = "Kaikki Team kuvakkeet Tässä hakemistossa ovat käytössä.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
