<?php
$l_warp_unlinked = "Kohdealaksi ([target_sector]) ei ole yhteyttä tämän alan.";
$l_warp_forbidtwo = "Käyttäen Warp Editor poistaa kaksisuuntainen linkki alan [target_sector] ei ole sallittua.";
$l_warp_removed = "Linkki poistettu ja";
$l_warp_removedtwo = "Linkki poistettu ja takaisin";
$l_warp_nomoney = "Sinulla ei ole tarpeeksi luottoja poistaa loimen linkkiä.";
$l_warp_noenergy = "Sinulla ei ole tarpeeksi energiaa poistaa loimen linkkiä.";
?>
