<?php
$l_news_title = "Universe Uutiset";
$l_news_info = "FNN on yksi galaksi johtajat <br> uutis-ja tietojen toimittamisesta. <br> Työskentelee 24 tuntia, seitsemän päivää viikossa <br> omistautunut henkilökunta FNN&#39;s Galaxy pääkonttori <br> kohteessa Proxima Centauri ja toimistosihteeri galaxywide!";
$l_news_for = "Uutisia";
$l_news_prev = "eilen";
$l_news_next = "Seuraava päivä";
$l_news_none = "Sorry, no uutisia tänään.";
$l_news_flash = "Uutishälytykset";
$l_news_end = "End of News";
$l_news_bestviewed = "Best viewed in Opera, Safari ja IE";
$l_news_fedannouncements = "Federation Ilmoitukset";
$l_news_planetarynews = "Planeettajärjestelmän Uutiset";
$l_news_planetshipnews = "Planeettojen ja Ship Uutiset";
$l_news_afteractionnews = "Jälkeen Action Combat Uutiset";
?>
