<?php
$l_opt2_title = "Tallennusvaihtoehdot";
$l_opt2_passunchanged = "Salasana jäi ennalleen. <BR><BR>";
$l_opt2_srcpassfalse = "Alkuperäinen salasana virheellinen. Salasana jäi ennalleen. <BR><BR>";
$l_opt2_newpassnomatch = "Uusi salasana kentät eivät täsmää. Salasana jäi ennalleen. <BR><BR>";
$l_opt2_passchanged = "Salasana muuttunut. <BR><BR>";
$l_opt2_passchangeerr = "Virhe muutettaessa salasana <BR><BR>";
$l_opt2_userintup = "Käyttöliittymä, jossa päivitetään. <BR><BR>";
$l_opt2_userintfail = "Päivitys epäonnistui käyttöliittymän asetus. <BR><BR>";
$l_opt2_chlang = "Kieli on asetettu [lang]. <p>";
$l_opt2_chtemplate = "Malli on asetettu [template]. <p>";
$l_opt2_dhtmlup = "Dynaamiset HTML-asetus päivitetty. <BR><BR>";
$l_opt2_dhtmlfail = "Päivitys epäonnistui dynaamisen html-asetus. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname muuttuneet [name]. <BR><BR>";
$l_opt2_playernamechanged = "Pelaajan nimi muuttuu [name] ja [amount] hyvitykset vähennetään oman aluksen tilin. <BR><BR>";
$l_opt2_mapwidth = "Paikalliset ja Galaxy Kartta Leveys:";
?>
