<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Din skannere ikke har full lang rekkevidde skanning evner.";
$l_lrs_noturns = "Du trenger minst $ fullscan_cost tur (er) til å kjøre en full lang rekkevidde scan.";
$l_lrs_used = "Brukt";
$l_lrs_turns = "tur (r)";
$l_lrs_left = "venstre";
$l_lrs_reach = "Følgende steder kan nås fra sektor [sector]:";
$l_lrs_links = "Linker";
$l_lrs_ships = "Skip";
$l_lrs_click = "Klikk på en av linkene for å flytte til at sektoren.";
$l_lrs_cantscan = "Kan ikke skanne sektor fra gjeldende sektor!";
$l_lrs_zero = "Sector 1 er overfylt å avsøke for skip!";
$l_lrs_moveto = "å flytte til sektor";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "Vis logg";
$l_lrs_fedjammed = "Forbundet er jamming alle sensoren skanner.";
$l_lrs_sectormissile_question = "til brann sektor rakett.";
$l_log_months = "array ( &#39;januar&#39;, &#39;Februar&#39;, &#39;Mars&#39;, &#39;April&#39;, &#39;Mai&#39;, &#39;Juni&#39;, &#39;juli&#39;, &#39;August&#39;, &#39;September&#39;, &#39;Oktober&#39;, &#39;november&#39;, &#39;desember&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;Feb&#39;, &#39;Apr&#39;, &#39;Apr&#39;, &#39;Mai&#39;, &#39;Jun&#39;, &#39;Jul&#39;, &#39;Aug&#39;, &#39;Sep&#39;, &#39;Okt&#39;, &#39;Nov&#39;, &#39;Des&#39;)";
?>
