<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Unchartered space";
$l_zname[2] = "Federation space";
$l_zname[3] = "Alliance space";
$l_zname[4] = "War Zone";

$l_nova = "Nova";
$l_nova = "Nova Bomb";
$l_lssd = "Sist skipet sett enhet";
$l_lss = "Sist skipet sett i denne sektoren";

// Common to : warpedit 1-3.php

$l_warp_title = "Bruk Warp Editor";
$l_warp_turn = "Du trenger minst én tur til å bruke et warp redaktør.";
$l_warp_none = "Du har ingen warp redaktører.";
$l_warp_forbid = "Bruke en Warp Editor i denne sektoren er ikke tillatt.";
$l_swarp_forbid = "Bruke en Warp Editor til eller fra SG sektorer er ikke tillatt.";
$l_warp_nosector = "Sector finnes ikke.";

// Not yet confirmed common to multiple files:

$l_yes = "Ja";
$l_no = "Nei";
$l_here = "her";
$l_submit = "Sende inn";
$l_reset = "Nullstill";
$l_all = "Alle";
$l_max = "Max";

$l_trade = "Handel";
$l_ore = "Ore";
$l_commodity = "Vare";
$l_commodities = "Råvarer";
$l_organics = "Organics";
$l_goods = "Goods";
$l_energy = "Energi";
$l_colonists = "Kolonistene";
$l_credits = "Studiepoeng";
$l_units = "enheter";
$l_special = "Spesial";
$l_upgrade_ports = "Oppgraderinger";
$l_device_ports = "Enheter";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_dig = "Myndighetspersoner";
$l_spy = "Spies";

$l_cargo = "Cargo";
$l_fighters = "Fighters";
$l_mines = "Mines";
$l_torps = "Torpedoer";

$l_none = "Ingen";
$l_unnamed = "Unnamed";
$l_name = "Navn";
$l_unowned = "Unowned";
$l_unknown = "Ukjent";
$l_clickme = "Klikk her";
$l_player = "Player";
$l_ship = "Skip";
$l_ships = "Skip";
$l_set = "still inn";
$l_realspace = "Realspace";
$l_armorpts = "Armor poeng";
$l_links = "Linker";
$l_login_email = "E-postadresse:";
$l_add = "Legge til";
$l_teamforum = "Team Forum";
$l_teamships = "Team Ships";
$l_tutorial = "Tutorial / Hjelp";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Rusk";
$l_localmap = "Lokale Kart";
$l_arm_weap = "Rustning og våpen";
$l_3dmap = "3D Galaxy Kart";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Romsonder";
$l_warpeditors = "Warp Redaksjon";
$l_genesistorps = "Genesis Torpedoes";
$l_sgtorps = "SG Torpedoes";
$l_minesfighters = "Mines / Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Rapporter";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Kart";
$l_messages = "Meldinger";
$l_shiptype = "Ship Type";
$l_help = "Hjelp";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Team forsvar";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet forsvar";
$l_changeproduction = "Endre Production";
$l_galacticarm = "Galactic Arm";

$l_armor = "Armor";
$l_news_none = "Beklager, ingen nyheter i dag.";

$l_ranks_good = "Bra";
$l_ranks_evil = "Ond";
$l_ranks_neutral = "Nøytral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Sonen er nå a War Zone!";
$l_global_nzone = "Sonen er en nøytral sone.";
$l_global_team = "Sone tilhører nå to team";
$l_global_player = "Sone tilhører nå til spilleren";
$l_global_nochange = "Sone eierskapet ikke endrer";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "Petty Officer Tredje klasse";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Lieutenant Junior Grade";
$l_insignia_name[11] = "Løytnant";
$l_insignia_name[12] = "Kapteinløytnant";
$l_insignia_name[13] = "Commander";
$l_insignia_name[14] = "Kaptein";
$l_insignia_name[15] = "Kontreadmiral (nedre halvdel)";
$l_insignia_name[16] = "Kontreadmiral (øvre halvdelen)";
$l_insignia_name[17] = "Viseadmiral";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Fleet Admiral";

$l_main_title = "Main Menu";
$l_main_warpto = "Warp til";
$l_main_autoroute = "Autoroute til";
$l_main_rs_to = "RSMove til";
$l_main_other = "Annet";
$l_main_shipyard1 = "Shipyard";
$l_main_shipyard2 = "Åpne";
$l_traderoutes = "Handelsruter";
$l_trade_control = "Trade Control";
$l_youhave = "Du har";
$l_turns_used = "Turns brukt:";
$l_turns_have = "Turns tilgjengelig:";
$l_score = "Poeng:";
$l_sector = "Sector";
$l_help = "Hjelp";
$l_faq = "FAQ";
$l_feedback = "Tilbakemelding";
$l_forums = "Forums";
$l_logout = "Logout";
$l_commands = "Kommandoer";
$l_command_no = "Kommando ikke tilgjengelig.";
$l_devices = "Enheter";
$l_planets = "Planeter";
$l_log = "Logg";
$l_sector_def = "Sector forsvar";
$l_defense = "Forsvar";
$l_read_msg = "Les Meldinger";
$l_send_msg = "Sende meldinger";
$l_rankings = "Rankings";
$l_teams = "Teams";
$l_ohno = "Self-Destruct";
$l_options = "Valg";
$l_navcomp = "Nav Computer";
$l_incompletemove = "Du har ikke fullført den forrige trekk.";
$l_clicktocontinue = "Klikk her for å fortsette";
$l_toplanetmenu = "å gå til planeten menyen.";
$l_nonexistant_pl = "På en ikke-eksisterende planet??";
$l_abord = ", Ombord på";
$l_messages_wait = "Meldinger som venter på deg.";
$l_no_warplink = "Ingen warp linker";
$l_scan = "scan";
$l_fullscan = "Full scan";
$l_port = "Port";
$l_tradingport = "Trading port";
$l_planet_in_sec = "Planetene i sektoren";
$l_ships_in_sec = "Andre skip i sektor";
$l_sector_0 = "Det er så mye trafikk i Sol som du ikke engang kan isolere andre skip!";
$l_map = "Kart";
$l_probe = "Probes";
$l_autotrade = "Autotrades";
$l_onboard = "om bord en";
$l_classship = "klasse skip";
$l_traveled = "reiste til sektor";
$l_max_planets = "Maksimal habital planeter";
$l_block_msg = "Blokkere meldinger";
$l_sectorinfo = "Sector Info";
$l_add_note = "Legg Note";
$l_view_note = "Utsikt";
$l_notes = "Notes";
$l_global_limitreached = "Du har nådd grensen for hvor mye tid du har lov til å være online hver dag. Logg inn igjen i morgen etter midnatt.";
$l_onlinetimeleft = "Gjenværende Tid:";
$l_planetmax = "Planetary Maksimum:";
$l_storedshipreport = "Lagrede Ships";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Forrige Side";
$l_common_next = "Next Page";
$l_common_totalpages = "Total Sider";
$l_common_selectpage = "Velg side:";
$l_common_page = "Side:";
$l_templatechange = "Vil du beholde denne malen?";

$l_im_fed_bounty = "Føderasjonen har plassert en dusør på deg for å angripe et så lavt rangert spiller. Landsorganisasjonen vil angripe skipet ditt med jevne mellomrom til du betale tilbake din gavmildhet. Du kan betale av skuddpremie på noe oppgradering Port eller Spacedock.";
$l_im_fed_bounty_title = "Føderasjonen plassert en premie på deg!";
$l_im_alliance_bounty = "Alliansen har satt en dusør på deg for å angripe et så lavt rangert spiller. Alliansen vil angripe skipet ditt med jevne mellomrom til du betale tilbake din gavmildhet. Du kan betale av skuddpremie på noe oppgradering Port eller Spacedock.";
$l_im_alliance_bounty_title = "Alliansen la en premie på deg!";
$l_instant_messages_waiting = "Du har [count] meldinger som venter på deg.";

$l_home_planet = "Hjem Planet";

$l_hold_space_used = "Holds Fylt:";
$l_hold_space_free = "Holds Tomt:";
$l_port_buys = "Port Buys:";

?>
