<?php
$l_die_title = "Self-Destruct";
$l_die_rusure = "Er du sikker på at du ønsker å ødelegge skipet ditt? Dette vil fjerne deg fra spillet.";
$l_die_goodbye = "Goodbye cruel galakse!";
$l_die_check = "Er du positivt at du ønsker å fjerne deg fra spillet?";
$l_die_nonono = "NO! NO! NO!";
$l_die_what = "Hva jeg tenkte?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Du skipet og alle ombord har vært fordampede.";
$l_die_please1 = "logout";
$l_die_please2 = "Vennligst [logout_link]";
$l_die_exploit = "Ikke lek med det du ikke forstår.";
?>
