<?php
$l_by_title = "Bounties";
$l_by_noturn = "Du trenger minst én tur til å plassere eller endre en dusør.";
$l_by_amount = "Bounty Beløp";
$l_by_place = "Place Bounty";
$l_by_nobounties = "Det er ingen bounties.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Plasseres ved";
$l_by_thefeds = "The Federation";
$l_by_cancel = "Avbryt";
$l_by_yourself = "Du kan ikke plassere en dusør på selv din.";
$l_by_notenough = "Du har ikke nok studiepoeng til å plassere en dusør på dette beløpet.";
$l_by_toomuch = "Du kan ikke sted som gavmildhet. Maksimal tillatt skuddpremie på en annen spiller er [percent] prosent av nettoformue";
$l_by_zeroamount = "Bounties må være større enn 0 studiepoeng.";
$l_by_placed = "Bounty er plassert.";
$l_by_nobounty = "Det skuddpremie eksisterer ikke lenger.";
$l_by_notyours = "Det skuddpremie ikke var plassert av deg.";
$l_by_canceled = "Bounty har blitt kansellert.";
$l_by_action = "Action";
$l_by_placebounty = "Place eller vise bounties.";
$l_by_moredetails = "Klikk på navnet for mer informasjon.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "Spilleren du setter det skuddpremie på finnes ikke.";
$l_by_destroyed = "Du kan ikke plassere en dusør på en spiller med et ødelagt skip.";
$l_by_nofedbounty = "Du vil ikke motta en dusør dersom du angripe dette spillere skip eller planet.";
$l_by_fedcollectonly = "Bare Federation kan Utlevering Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Du vil ikke motta en dusør dersom du plassere en spion på denne planeten spillere.";
$l_pay_partial = "Foreta delbetaling";
$l_pay_button = "Betal";

$l_by_thealliance = "Alliansen";
$l_by_alliancecollectonly = "Bare Alliansen kan Collect Bounty";
$l_by_bountyscan = "Bounty";
?>
