<?php
$l_att_title = "Attack Ship";
$l_att_notarg = "Target ikke i denne sektoren.";
$l_att_noturn = "Du trenger minst én tur til å angripe.";
$l_att_noatt = "Angripe noen i denne sektoren er ikke tillatt.";
$l_att_flee = "Target ut manøvrerte deg!";
$l_att_ewd = "Target engasjert en nødsituasjon deformere enheten når den angrep!";
$l_att_att = "Offensiv";
$l_att_beams = "Beam Exchange";
$l_att_torps = "Torpedo Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost = "tapt";
$l_att_ylost = "Du tapte";
$l_att_sdown = "&#39;s skjoldene er nede!";
$l_att_ydown = "Dine skjoldene er nede!";
$l_att_shits = "&#39;s skjold er truffet for";
$l_att_yhits = "Dine skjold treffes for";
$l_att_dmg = "skade";
$l_att_sarm = "&#39;s rustning brutt!";
$l_att_yarm = "Din rustning er overtrådt!";
$l_att_ashit = "&#39;s rustning er truffet for";
$l_att_ayhit = "Din rustning er truffet for";

$l_att_efhit = "&#39;s krigere er ødelagt.";
$l_att_yfhit = "av jagerfly er ødelagt.";
$l_att_ethit = "&#39;s torpedoer er ødelagt.";
$l_att_ythit = "av torpedoer er ødelagt.";
$l_att_of = "av";
$l_att_lostt = "mistet alle torpedoer.";
$l_att_ylostt = "Du mistet alle torpedoer.";

$l_att_lostf = "mistet alle krigere.";
$l_att_ylostf = "Du mistet alle krigerne.";
$l_att_sdest = "&#39;s skip har blitt ødelagt.";
$l_att_espod = "En lekkasje pod ble lansert!";
$l_att_ysalv = "Du berget [ship_salvage_rate]% av skipet for [ship_salvage] studiepoeng. <BR> Rangeringen endret av [rating_change] poeng.";
$l_att_andused = "og brukt";
$l_att_stilship = "Du har ikke destory [name] s skip.";
$l_att_atyou = "angrepet deg";
$l_att_and = "og";
$l_att_yshiplost = "Skipet ditt har blitt ødelagt!";
$l_att_salv = "[name] berget [ship_salvage_rate]% av skipet for [ship_salvage] credits";
$l_att_loosepod = "Heldigvis har du en flukt pod!";

$l_att_tnobeams = "sømmer for å være ute av bjelke energi.";
$l_att_tnobeamsf = "sømmer for å være ute av strålen energi og kan ikke angripe din jagerfly.";
$l_att_tnobeamst = "sømmer for å være ute av strålen energi og kan ikke angripe din torpedoer.";
$l_att_tfnoattack = "sender ikke noen jagerfly til angrep skipet ditt.";
$l_att_tnotorps = "synes å være ute av torpedoer.";

$l_att_anobeams = "Du har brukt opp dine skip beam energi.";
$l_att_anobeamsf = "Du har brukt opp dine skip strålen energi og kan ikke angripe fienden jagerfly.";
$l_att_anobeamst = "Du har brukt opp dine skip strålen energi og kan ikke angripe fienden torpedoer.";
$l_att_anofighters = "Skipet ditt har uttømt alle availible jagerfly.";
$l_att_anotorps = "Du har brukt opp availible torpedoer.";
$l_att_imtitle = "Ship Under Attack";
$l_att_imbody = "angriper skipet ditt.";

$l_att_luckybeams = "Enemy bjelker overbelastning påføre";
$l_att_luckyfighters = "Fiendtlige krigere lage en overraskelse lightening angrep og føre";
$l_att_luckytorps = "Enemy torpedoer indusere en gjennomgripende skade effekt forårsaker";
$l_att_luckytimes = "ganger normal skade!";
?>
