<?php
$l_opt_title = "Velg en Avatar";
$l_opt_errorsize = "Feil: Bildet må ikke være større enn 64x64 piksler i størrelse.";
$l_opt_errortype = "Feil: Bildet må være JPG, GIF-eller PNG";
$l_opt_errornographic = "Feil: ingen grafiske valgt.";
$l_opt_currentavatar = "Din Current Avatar";
$l_opt_uploadavatar = "Last opp et Avatar";
$l_opt_directory = "Velg Avatar Directory";
$l_opt_change = "Endre Directory";
$l_opt_select = "Velg Avatar";
$l_opt_inuse = "Alle avatarer i denne katalogen er i bruk.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
