<?php
$l_nav_title = "Navigation Computer";
$l_nav_nocomp = "Navigering Datamaskin er ikke tilgjengelig";
$l_nav_query = "Skriv sektor for å finne veien til:";
$l_nav_pathfnd = "Path funnet";
$l_nav_answ1 = "Det vil ta deg";
$l_nav_answ2 = "snur få til denne sektoren.";
$l_nav_proper = "Du må oppgradere din Fighter Bay teknologien før jagerfly kan finne et varp ruten for at avstanden.";
$l_nav_autoroutename = "Valgfritt Autoroute Navn:";
$l_nav_manuallist = "Manuelt Bygget WarpLink Autoroute List";
$l_nav_warplinksleaving = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Det er ingen warplinks forlater denne sektoren.";
$l_nav_warp_from = "Warp fra";
$l_nav_rs_from = "RSMove fra";
$l_nav_notinlogs = "Ingen data tilgjengelig på denne sektoren.";
?>
