<?php
$l_login_title = "Innlogging";
$l_login_pw = "Passord:";
$l_login_chooseres = "Kan ikke fastslå skjermoppløsningen. Velg det passer best:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problemer?";
$l_login_emailus = "E-mail oss";
$l_login_forgot_pw = "Glemt passordet? Tast inn det stå tomt og trykk på logg inn.";
$l_login_settings = "Spillinnstillinger";
$l_login_change = "Endring";
$l_login_title2 = "Main Login for AATraders";
$l_login_reset1 = "Ingen Reset Planlagt";
$l_login_reset2 = "Planlagt Reset:";
$l_login_reset3 = "Sched Reset:";
$l_login_notice = "Viktig merknad:";
$l_login_endadminnews = "End of Admin News";
$l_login_tourney_signup = "Turnering Registreringer Enabled";

$l_login_profile_only = "Profil Only";
$l_login_newclosed_message = "Nye registreringer Stengt";
$l_login_tourneymode = "Turnering Running";
$l_login_tourneystarts = "Starter:";
?>
