<?php
$l_sf_attacking = "Sector forsvaret jagerfly angriper deg! <BR>";
$l_sf_destfight = "Din bjelker ødelagt [lost] jagerfly <BR>";
$l_sf_destfightb = "Din bjelker ødelagt [lost] jagerfly <BR>";
$l_sf_torphit = "Torpedoer hit:";
$l_sf_destfightt = "Din torpedoer ødelagt [lost] jagerfly <BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "Du ødela alle krigerne. <BR>";
$l_sf_destfightt2 = "Du ødela [lost] jagerfly. <BR>";
$l_sf_lostfight = "Du mistet alle krigerne. <BR>";
$l_sf_lostfight2 = "Du mistet [lost] jagerfly. <BR>";
$l_sf_armorbreach = "Din rustning er brutt! <BR>";
$l_sf_armorbreach2 = "Din rustning er truffet for [lost] skade. <BR>";
$l_sf_sendlog = "[player] ødelagt [lost] sektor forsvaret jagerfly i sektor [sector].";
$l_sf_lreport = "Du mistet [armor] rustning poeng, [fighters] jagerfly, og brukte [torps] torpedoer. <BR><BR>";
$l_sf_shipdestroyed = "Skipet ditt har blitt ødelagt! <BR><BR>";
$l_sf_sendlog2 = "Sector forsvaret jagerfly ødela [player] i sektor [sector].";
$l_sf_escape = "Heldigvis har du en flukt pod! <BR><BR>";

$l_sf_fnoattack = "sender ikke noen jagerfly å angripe din jagerfly.";
$l_sf_fnoattackt = "sender ikke noen jagerfly å angripe din torpedoer.";
$l_sf_fnoattacka = "sender ikke noen jagerfly å angripe din rustning.";
$l_sf_flaunchmalf1 = "Din fighter lansere systemet fungerer.";
$l_sf_flaunchmalf2 = "Du har kun vært i stand til å lansere";
$l_sf_flaunchmalf3 = "prosent av jagerfly.";
$l_sf_fightertorpexg = "Fighter til Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Ship Torpedo å Sector Fighter Exchange";
$l_sf_fighterarmorexg = "Sector Fighter til Ship Armor Exchange";
$l_sf_tlaunchmalf1 = "Din torpedo lansere systemet fungerer.";
$l_sf_tlaunchmalf2 = "Du har kun vært i stand til å lansere";
$l_sf_tlaunchmalf3 = "prosent av torpedoer.";
$l_sf_bountysd = "Du har angrepet en sektor som inneholder en planet som vil gi deg en dusør dersom du angrepet planeten. Føderasjonen har aktivert automatisk selvdestrueres på alle dine krigere og torpedoer. Ikke angrep sektoren forsvar i denne sektoren igjen. Du har blitt advart!";
?>
