<?php
// port.php port_purchase.php
$l_trade = "Handel";
$l_title_port = "Port Trading";
$l_title_trade = "Trading Råvarer";
$l_sector_war = "War embargo";
$l_war_info = "Krigen raser i denne sektoren. Du kan ikke komme til porten gjennom alle fiendtlige styrker.";
$l_no_trade = "Trade forbudt";
$l_no_trade_out = "Trading på denne porten er ikke tillatt for utenforstående";
$l_no_trade_info = "Trading på denne porten er ikke tillatt";
$l_buying = "Kjøpe";
$l_selling = "Selge";
$l_commodity = "Vare";
$l_amount = "Beløp";
$l_price = "Pris";
$l_buy = "Kjøpe";
$l_sell = "Selge";
$l_trade_st_info = "Du har [free_holds] tomt lasterom, kan bære [free_power] mer energi enheter, og har [credits] studiepoeng.";
$l_upgrade_port_title = "Oppgrader Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Ikke nok studiepoeng";
$l_creds_to_spend = "Du har [credits] kreditter til forbruk.";
$l_cost = "Kostnad";
$l_avail = "Tilgjengelig";
$l_profit = "Profit";
$l_current = "";
$l_current_level = "Dagens nivå";
$l_current_qty = "Nåværende Mengder";
$l_max = "Max";
$l_ifyouneedmore = "Hvis du trenger mer du kan få tilgang til denne porten&#39;s [igb]";
$l_ifyouneedplan = "Access planetens";
$l_igb_term = "IGB Bank Terminal";
$l_upgrade = "Oppgradering";
$l_unlimited = "Ubegrenset";
$l_full = "Mett";
$l_equipped = "Utstyrt";
$l_n_a = "n / a";
$l_item = "Gjenstand";
$l_totalcost = "Totalkostnad";
$l_would_dump = "Dersom du ønsker å dumpe alle kolonister her, klikk";
$l_noport = "Det er ingen havn her!";
$l_trade_turnneed = "Du trenger minst én tur til å handle på en port eller planet.";
$l_returnto_port1 = "her";
$l_returnto_port2 = "Klikk [port_link] for å gå tilbake til porten menyen.";
$l_notenough_cargo = "Du har ikke nok ledig lasterom for varer du ønsker å kjøpe.";
$l_notenough_power = "Du har ikke nok kraft lagringsplass for energi du vil kjøpe.";
$l_notenough_credits = "Du har ikke nok studiepoeng til å fullføre transaksjonen.";
$l_notenough_turns = "Du har ikke nok blir å fullføre transaksjonen.";
$l_trade_result = "Resultater for denne handelen";
$l_trade_complete = "Trade fullført";
$l_trade_upgraded = "Oppgradert til nivå";
$l_trade_added = "lagt";
$l_trade_installed = "installert";
$l_port_bounty = "Du får ikke tilgang til en spesiell port, mens du har en skuddpremie på du foretatt av The Federation. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Du har ikke nok credtis å betale dusør på [amount] studiepoeng. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "Det IGB har utstedt en lockdown på skipet ditt konto på grunn av en sen lån betaling. Du kan ikke handle på en spesiell port før du betaler tilbake lånet ditt.";
$l_port_returntospecial = "å gå tilbake til tilbudet depot.";
$l_toprobemenu = "å gå til sonden menyen.";
$l_ports_shiplimit = "Minimum Ship klassen å montere enheten:";
$l_ports_needrepair = "Reparasjon";

$l_ports_needcredits = "Du har ikke nok studiepoeng for denne transaksjonen. Den totale kostnaden er";
$l_ports_needcredits1 = "kreditter og du har bare";

$l_ports_tradeforbidden = "Trade forbudt";
$l_ports_nooutsiders = "Trading på denne porten er ikke tillatt for utenforstående.";

$l_bought = "Du har kjøpt";
$l_sold = "Du solgt";
$l_notenough_commodity = "Du har ikke nok [commodity] for å fullføre transaksjonen.";
$l_exceed_commodity = "Antall [commodity] overstiger tilbudet og etterspørsel.";
$l_port_shiptoolarge = "Skipet ditt er for stor til å handle på denne porten.";

$l_port_hold_unit = "Plass per enhet";


$l_port_welcome = "Port [sectorname] Velkommen&#39;s [player]";
$l_port_amountforsale = "Porten har [amount] enheter [commodity] for salg på [credits] studiepoeng per enhet.";
$l_port_holdsperunit = "[holds] lasterom avgift per enhet.";
$l_port_howmanypurchase = "Hvor mange [commodity] enheter ønsker du å kjøpe?";
$l_port_unitstobuy = "Enheter to Buy";
$l_port_shipcarryingbuy = "Ditt skip er balanseført [shipunits] enheter [commodity]. Du kan kjøpe [buyunits] enheter med ledig lasterom plass.";
$l_port_howmanysell = "[amount] enheter [commodity] @ [credits] studiepoeng per enhet.";
$l_port_unitstosell = "Enheter for salg";
$l_port_perform = "Utfør Transaction";
$l_port_cargoholds = "Lasterom";

?>
