<?php
$l_warp_unlinked = "Target sektor ([target_sector]) har ikke en link fra denne sektoren.";
$l_warp_forbidtwo = "Bruke en Warp Editor til å fjerne en toveis link til sektor [target_sector] er ikke tillatt.";
$l_warp_removed = "Link fjernet for å";
$l_warp_removedtwo = "Link fjernet til og fra";
$l_warp_nomoney = "Du har ikke nok studiepoeng til å slette warp linken.";
$l_warp_noenergy = "Du har ikke nok energi til å slette warp linken.";
?>
