<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: ShoutBox::.";
$l_shout_public = "Offentlig";
$l_shout_team = "Team";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "ellers";
$l_shout_refresh = "Oppdater";
$l_shout_close = "Close Window";
$l_shout_saved = "Shout frelst!";
$l_shout_return = "Tilbake til";
$l_shout_prev = "Forrige";
$l_shout_next = "Neste";
$l_shout_selectpage = "Velg side";
$l_shout_page = "Side:";
$l_shout_teamtitle = ".:: TEAM ShoutBox::.";
?>
