<?php
$l_md_title = "Sector forsvar";
$l_md_invalid = "Ugyldig Sector forsvar";
$l_md_nolonger = "Sektoren Forsvaret valgte ikke lenger er der.";
$l_md_you = "du";
$l_md_bmines = "Din bjelker ødelagt";
$l_md_msgdownerb = "[name] ødelagt [mines] gruver i sektor [sector].";
$l_md_retr = "Du funnet";
$l_md_consist = "Denne sektoren forsvaret består av [qty] [type] eid av [owner].";
$l_md_youcan = "Du kan";
$l_md_retrieve = "Hent";
$l_md_attack = "Attack";
$l_md_attdef = "Attack sektoren forsvar. Alle sektor jagerfly vil gjengjelde.";
$l_md_noturn = "Du trenger minst én tur.";
$l_md_nothere = "Du må være i samme sektor som sektoren forsvar.";
$l_md_notyours = "Handlingen er ikke tillatt. De sektor forsvar ikke tilhører deg.";
$l_md_yours = "Du kan ikke angripe din egen sektor forsvar.";
?>
