<?php
$l_s_yes = "Ja";
$l_s_no = "Nei";
$l_s_enabled = "Enabled";
$l_s_disabled = "Disabled";

$l_s_modules = "Moduler";
$l_s_modulename = "Module Name";
$l_s_moduleauthor = "Forfatter";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "Ingen Moduler Loaded";

$l_s_gamestatus = "Game Status";
$l_s_allowpl = "Tillat Spillere";
$l_s_allownewpl = "Tillat nye spillere";

$l_s_gameoptions = "Game Options";
$l_s_allowteamplcreds = "Tillat Team Planet Credit Transfer";
$l_s_allowfullscan = "Tillat Full Long Range Scan";
$l_s_sofa = "Tillat Sub-Orbital Fighter Angrep";
$l_s_showpassword = "Display Passord på Registrere";
$l_s_genesisdestroy = "Genesis Torps kan ødelegge planeter";
$l_s_igb = "Intergalactic Bank (igb)";
$l_s_ksm = "Kjente Space Maps";
$l_s_navcomp = "Navigation Computer";
$l_s_newbienice = "Newbie Nice";
$l_s_spies = "Spy System";
$l_s_spycapture = "Tillat Spies å erobre planeter";

$l_s_gamesettings = "Spillinnstillinger";
$l_s_gameversion = "Game versjon:";
$l_s_minhullmines = "Minimum skrog størrelse er nødvendig for å finne miner";
$l_s_averagetechewd = "Gjennomsnitt Tech nivå Når Emergency Warp forringer";
$l_s_numsectors = "Antall Sectors";
$l_s_maxwarpspersector = "Maksimal Links per sektor";
$l_s_averagetechfed = "Maksimal gjennomsnittlig teknisk nivå for Federation Sectors";
$l_s_igbirateperupdate = "igb Rente per oppdatering";
$l_s_igblrateperupdate = "igb Loan rate per oppdatering";
$l_s_techupgradebase = "Tech Level oppgradering for Bases";
$l_s_collimit = "Kolonistene Limit";
$l_s_maxturns = "Maksimum antall akkumulerte snur";
$l_s_maxplanetssector = "Maksimum antall planeter per sektor";
$l_s_maxtraderoutes = "Maksimum antall traderoutes per spiller";
$l_s_colreprodrate = "Colonist Birth Rate";
$l_s_energyperfighter = "Enhet for energi som brukes per sektor fighter";
$l_s_secfighterdegrade = "Sector fighter degradering prosentsats";
$l_s_planetinterest = "Planet renten";
$l_s_spiesperplanet = "Maksimum antall spioner per planet";
$l_s_spysuccessfactor = "Spy suksessfaktor";
$l_s_spykillfactor = "Spy drepe faktor";
$l_s_colsperfighter = "Kolonister som trengs for å produsere 1 Fighter hver sving";
$l_s_colspertorp = "Kolonister som trengs for å produsere 1 Torpedo hver sving";
$l_s_colsperore = "Kolonister som trengs for å produsere 1 øre hver sving";
$l_s_colsperorganics = "Kolonister som trengs for å produsere 1 Organics hver sving";
$l_s_colspergoods = "Kolonister som trengs for å produsere 1 Goods hver sving";
$l_s_colsperenergy = "Kolonister som trengs for å produsere 1 Energy hver sving";
$l_s_colspercreds = "Kolonister som trengs for å produsere 1 Credits hver sving";
$l_s_colsper = "Kolonister som trengs for å produsere 1 [commodity] hver sving";

$l_s_gameschedsettings = "Game Scheduler Innstillinger";
$l_s_schedtype = "Planlegger Type";
$l_s_cronbased = "Cron Basert";
$l_s_playertriggered = "Spilleren Utløste";
$l_s_minutes = "minutter";
$l_s_ticksupdate = "Ticks skje hver";
$l_s_turnsupdate = "Slår skje vil hver";
$l_s_npcupdate = "Alliansen vil spille hver";
$l_s_igbturnsupdate = "Interesser på igb kontoer vil bli akkumulert hver";
$l_s_newsupdate = "Nyheter vil bli generert hver";
$l_s_planetupdate = "Planetene vil generere produksjonen hver";
$l_s_spyupdate = "Spies vil fungere hver";
$l_s_portsupdate = "Porter vil fornye alle";
$l_s_towupdate = "Skip skal slepes fra matet sektorer hver";
$l_s_scoreupdate = "Rankings vil bli generert hver";
$l_s_secdefdegrupdate = "Sector forsvar vil nedverdige hver";
$l_s_apocalypseupdate = "Den planetariske apocalypse vil skje hver";
$l_s_release_version = "Game versjonen";
$l_s_time_since_reset = "Tid siden siste nullstilling";
$l_s_independence = "Planetary Independence";
$l_s_dignitaryupdate = "Myndighetspersoner vil fungere hver";

$l_s_turnsupdate = "blir hver";
?>
