<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Probe Levels";
$l_probe_engine = "Motor";
$l_probe_sensors = "Sensorer";
$l_probe_cloak = "Cloak";
$l_probe_title = "Space Probe Meny";
$l_probe_none = "Du er ikke i samme sektor som denne sonde, slik at du ikke kan kommunisere med den.";

$l_probe_named = "Velkommen til Probe Antall [probename], eid av [name], som ligger i sektor [sector].";
$l_probe_orders = "[orders] Probe å søke univers";
$l_probe_orders_link = "Program";
$l_probe_upgrade = "[upgrade] Probe Sensorer / motor / Cloak";
$l_probe_upgrade_link = "Oppgradering";
$l_probe_pickup = "[pickup] Probe for senere plassering";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Oppdatering";

$l_probe_att_link = "Attack";
$l_probe_att = "[attack] på sonde";
$l_probe_att_sure = "Er sikker på at du ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] probe";

$l_probe_unknown = "Ukjent";
$l_plant_scn_turn = "Du trenger minst én tur til å skanne en sonde.";
$l_probe_noscan = "Sensorer kan ikke få reparasjonen på mål!";
$l_probe_logscanA = "[name] forsøkte å skanne en av sonder i sektor [sector], men mislyktes.";
$l_probe_logscanB = "En av sonder i sektor [sector] ble skannet av [name].";
$l_probe_scn_report = "Scan resultater på [name], som eies av: [owner]";

$l_probe_caplog = "Din probe &quot;[probename] &#39;i sektor [sector] ble fanget av [name].";
$l_probe_scan = "Probe skanner sektor [sector] og finner:";
$l_probe_destroyprobe = "Destroy probe";
$l_probe_destroyed = "Probe Destroyed!";
$l_probe_warning = "Å gjøre dette vil totalt ødelegge dette probe";
$l_probe_confirm = "Vil du virkelig å ødelegge dette sonde?";
$l_gns_turn = "Du har ikke nok svinger å ødelegge denne probe";
$l_probe_type = "Probe Type";
$l_probe_type0 = "Stasjonære Probe";
$l_probe_type1 = "Sentry Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sekvensiell Realspace Probe";
$l_probe_target = "Target Sector";
$l_probe_ordered = "Probe programmert og vil begynne å søke.";
$l_probe_order2 = "Probe er en [type] og er målrettet sektor [target]";
$l_probe_pickedup = "Probe plukket opp og plassert i aktive lagring";
$l_probe_title = "Probe Meny";
$l_probe_messages = "å se hva din spioner har oppdaget.";

$l_probe_defaulttitle1 = "Aktiv Probes";
$l_probe_defaulttitle2 = "Probes du har plukket opp";
$l_probe_defaulttitle3 = "Probes på planeter";
$l_probe_defaulttitle4 = "Probes på skipet ditt";
$l_probe_linkback = "å gå til sonden menyen.";
$l_probe_no1 = "Du trenger ikke ha noen aktive sonder.";
$l_probe_no2 = "Du har ingen sonder i magasinene.";
$l_probe_no3 = "Du har ingen følere på planeter.";
$l_probe_no4 = "Du har ingen følere på skipet ditt.";
$l_probe_noprobeatall = "Du har ingen sonder.";
$l_probe_notknown = "Ukjent";
$l_probe_launch = "Droppe";
$l_probe_detect = "Detected";
$l_probe_codenumber = "Kode";
$l_probe_job = "Jobb";
$l_probe_percent = "Prosent";
$l_probe_move = "Movement";
$l_probe_view = "Utsikt";
$l_probe_action = "Action";
$l_probe_shipowner = "Skipsreder";
$l_probe_shipname = "Ship Name";
$l_probe_shiptype = "Ship Klassifikasjon";
$l_probe_shiplocation = "Ship Sted";
$l_probe_planetowner = "Planet Eier";
$l_probe_planetname = "Planet";
$l_probe_sector = "Nåværende Sector";
$l_probe_tsector = "Target Sector";
$l_probe_type = "Probe Type";
$l_probe_forbid = "Du kan ikke slippe sonder i denne sektoren";

$l_probe2_title = "Launch Space Probe";
$l_probe2_turn = "Du trenger minst én tur til å bruke en romsonde.";
$l_probe2_onplanet = "Du kan ikke bruke denne enheten når du er på planetens overflate.";
$l_probe2_noprobe = "Du har ingen romsonder.";
$l_probe2_forbid = "Starte en sonde i denne sektoren er ikke tillatt.";
$l_probe2_launched = "Sonden lansert!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Player";
$l_probe2_onboarda = "om bord på et";
$l_probe2_classship = "klasse skip";
$l_probe2_traveled = "reiste til sektor";
$l_probe2_fedjammed = "Forbundet er jamming alle sensoren skanner til Sector 1.";
$l_probe2_lastseen = "Sist Ship Seen";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Støtter";
$l_probe2_planets = "planeter";
$l_probe2_sectord = "Sector forsvar Detected";
$l_probe2_mines = "Mines";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Skip Detected";
$l_probe2_ships2 = "Ship Detected";
$l_probe2_noneowned = "Ingen planeter som ikke eies av deg har blitt oppdaget.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Ingenting Detected";
$l_probe2_nocredits = "Du har ikke nok studiepoeng for denne transaksjonen. Den totale kostnaden er [total] kreditter og du har bare [credits] studiepoeng.";

$l_probe_forbidSG = "Du kan ikke sende en Realspace type sonde i Sector Genesis opprettet sektorer.";
$l_probe_forbidFED = "Du kan ikke sende en Realspace type sonde inn Federation eller Alliance eies sektorer.";
$l_probe_forbidINVALID = "Destinasjonen sektor er en ugyldig sektor navn.";
?>
