<?php
$l_ship2_buytitle = "Kjøpe et nytt skip";
$l_ship2_storetitle = "Shipyard Storage Facility";
$l_ship2_wrongclass = "Feil skip klassen spesifisert";
$l_ship2_buying = "Du kjøper:";
$l_ship2_tradein = "Trade In:";
$l_ship2_value = "Nåværende Ship Verdi:";
$l_ship2_newvalue = "Ny Ship Verdi:";
$l_ship2_totalcost = "Totalkostnad:";
$l_ship2_nomoney = "Du har ikke nok studiepoeng til å kjøpe dette skipet.";
$l_ship2_purchase = "Kjøp";
$l_ship2_buynstore = "Kjøpe nye skip og store gamle";
$l_ship2_nomoney2 = "Du har ikke nok studiepoeng til å fullføre denne transaksjonen.";
$l_ship2_paystorage = "Søket har fjernet et skip fra lagring.";
$l_ship2_turns = "Du trenger minst [turns] svinger for å utføre denne handlingen";
$l_ship2_error = "Intern feil. Kan ikke finne skipet klasse.";
$l_ship2_owned = "Du eier allerede denne modellen av skipet.";
$l_ship2_shipbought = "Du har nettopp kjøpt et nytt skip!";

?>
