<?php
$l_mail_title = "Passord";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Passord er sendt til";
$l_mail_topic = "$ game_name Passord";
$l_mail_message = "Greetings, \ n \ nSomeone fra IP-adressen $ ip bedt om at passordet ditt for $ game_name bli sendt til deg \ n \ nDen passord er: [pass] \ n \ nThank du \ n \ nDe $ game_name webteamet.";
$l_new_login = "å gå til innloggingsbildet.";
$l_mail_failed = "Passord klarte å sende til";
?>
