<?php
$l_zi_title = "Soneinformasjon";
$l_zi_nexist = "Denne delen av rommet eksisterer ikke!";
$l_zi_feds = "Federation";
$l_zi_traders = "Alliance Space";
$l_zi_nobody = "Nobody";
$l_zi_war = "Bestridt space";
$l_zi_allow = "Tillatt";
$l_zi_notallow = "Ikke tillatt";
$l_zi_limit = "Begrenset til eier og allierte";
$l_zi_ul = "Ubegrenset";
$l_zi_control = "Du har kontroll med denne sonen";
$l_zi_tochange = "å endre sine lover.";
$l_zi_owner = "Zone eier";
$l_zi_maxhull = "Maksimal gjennomsnittlig tech nivå lov";
?>
