<?php
///SPIES
$l_dig_title = "Herre Meny";
$l_dig = "Myndighetspersoner";
$l_dig_disabled = "Dignataries er deaktivert!";
$l_dig_noturn = "Du trenger minst én tur til å sende en herre til en planet.";
$l_dig_notonboard = "Du har ingen herre ombord.";
$l_dig_ownplanet = "Du kan ikke sende en herre til en fiende planet.";
$l_dig_unownedplanet = "Du kan ikke sende en herre til unowned planeten.";
$l_dig_planetfull = "Det er allerede tillatt [max] myndighetspersoner på denne planeten.";
$l_dig_sendtitle = "Sende en herre [digID] til planet: <BR> Velg herre oppgave:";

$l_dig_codenumber = "Kode";
$l_dig_job = "Jobb";
$l_dig_percent = "Prosent";
$l_dig_move = "Movement";
$l_dig_action = "Action";
$l_dig_shipowner = "Skipsreder";
$l_dig_shipname = "Ship Name";
$l_dig_shiptype = "Ship Klassifikasjon";
$l_dig_shiplocation = "Ship Sted";
$l_dig_planetowner = "Planet Eier";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Maksimal Per Planet";
$l_dig_legend = "Herre Legend";
$l_dig_description = "Herre Beskrivelse";
$l_dig_waiting_description = "Herre vil skape torpedoer og jagerfly i påvente av en jobb oppdrag.";
$l_dig_changeerror = "Herre jobbskifte Report";

$l_dig_nospieshere = "Du har ingen myndighetspersoner på denne planeten!";
$l_dig_transferred = "myndighetspersoner overføres";
$l_dig_backonship = "Det herre er nå på skipet ditt.";
$l_dig_dismiss = "Avvise herre?";
$l_dig_changebutton = "Endring";
$l_dig_notyourplanet = "Det er ikke din planet.";

$l_dig_defaulttitle1 = "Myndighetspersoner på fiendtlige skip";
$l_dig_defaulttitle2 = "Myndighetspersoner på planeter";
$l_dig_defaulttitle3 = "Myndighetspersoner på planeter";
$l_dig_defaulttitle4 = "Myndighetspersoner på skipet ditt";

$l_dig_no1 = "Du har ingen myndighetspersoner på fiendtlige skip.";
$l_dig_no2 = "Du har ingen myndighetspersoner på planeter.";
$l_dig_no3 = "Du har ingen myndighetspersoner på planeter.";
$l_dig_no4 = "Du har ingen myndighetspersoner på skipet ditt.";
$l_dig_nodignitaryatall = "Du har ingen myndighetspersoner.";
$l_dig_notknown = "Ukjent";
$l_dig_dismiss = "Forkast";
$l_dig_dismiss2 = "";
$l_dig_menu = "å gå tilbake til herre Meny.";

?>
