<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Du trenger minst én tur til å skanne et annet skip.";
$l_scan_ron = "Scan resultater på";
$l_scan_capt = "Kaptein av:";
$l_scan_arma = "Bestykning:";
$l_scan_carry = "Carrying:";
$l_scan_bounty = "Dette skipet har en samlet skuddpremie på den av [amount] studiepoeng.";
$l_scan_fedbounty = "Dette skipet har en skuddpremie på den fra Føderasjonen.";
$l_by_nofedbounty = "Offensiv denne spilleren vil <B>ikke</b> resultere i Føderasjonen plassere en dusør på deg.";
?>
