<?php
$l_chf_youretreatback = "Du trekke seg tilbake til forrige plassering";
$l_chf_movefailed = "Flytt mislyktes.";
$l_chf_thefightersdetectyou = "Jagerflyene registrere deg!";
$l_chf_therearetotalfightersindest = "Det er [chf_total_sector_fighters] krigere i din destinasjon sektor.";
$l_chf_youcanretreat = "<B>Retreat</b> - vil koste en ekstra tur.";
$l_chf_inputfight = "<B>Fight</b> - Du må beseire alle krigerne å gå inn i sektoren.";
$l_chf_inputcloak = "<B>Cloak</b> - Bruk maskering enheten og forsøke å unngå jagerfly.";
$l_chf_go = "Dra";
$l_chf_inputrun = "<B>Attack and Run</b> - Du trenger en lysnende angrep løpe og retreat. Men du kan ta noe skade under retrett.";
?>
