<?php
$l_move_title = "Flytte";
$l_move_turn = "Du trenger minst én tur til å flytte.";
$l_move_failed = "Flytt failed!";
$l_rs_title = "RealSpace Flytt";
$l_rs_whichsector = "Hvilken sektor ønsker du å komme gjennom RealSpace?";
$l_rs_insector = "Du er for øyeblikket i sektor [sector] - og det er sektorer tilgjengelig fra 1 til [sector_max].";
$l_rs_submit = "Compute";
$l_rs_movetime = "Med motorer, vil det ta [triptime] snur å fullføre reisen.";
$l_rs_energy = "Du ville samle [energy] enheter av energi";
$l_rs_noturns = "Du har ikke nok svinger til venstre, og kan ikke legge ut på denne reisen.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "Du har [turns] svinger. [engage] motorer?";
$l_rs_invalid = "Du kan ikke realspace til at sektoren herfra.";
$l_rs_ready = "Du er nå i sektor [sector]. Du brukte [triptime] svinger, og fikk [energy] energi enheter.";
$l_warp_invalid = "Du kan ikke deformere til at sektoren herfra.";
$l_move_unknown = "Ukjent Movetype";
?>
