<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Du trenger minst 1 tur til å bygge en base";
$l_planet_upgrade = "Oppgradering";
$l_planet_novamiss = "Nova Bomb bommer hårfint men påfører skade på planeten.";
$l_planet_novaturns = "Nova Bomb krever atleast [turns] snur seg mot brann.";
$l_planet_novafed = "Nova Bomb vil ikke strøm i Federation sektorer.";
$l_planet_nonova = "Du har ikke en Nova Bomb installert.";
$l_planet_firenova = "Fire Nova Bomb";
$l_planet_novaexplode = "Nova Bomb eksploderte da det ble avfyrt, og skipet ditt har lidd enorm skade.";
$l_planet_novaexplode2 = "Nova Bomb eksploderte da den ble sparket og skipet ble ødelagt.";
$l_planet_noautotrade = "Auto Trade Route ikke satt til denne planeten.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] i havn [dest_id]";
$l_planet_autotradedelete = "Slett Auto Trade.";
$l_planet_autotradeadd = "Lag Auto Trade.";
$l_planet_tradedeleted = "Auto Trade Route Slettet.";
$l_planet_tradeadded = "Ny Auto Trade Route Added.";
$l_planet_autotype = "Velg elementet til å handle";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Du må kjøpe et lasteskip på denne planeten før du kan angi en Auto Trade rute.";
$l_planet_purchasecargo = "Dersom du ønsker å kjøpe et lasteskip";
$l_planet_upgradecargo = "Hvis du ønsker å oppgradere Cargo Ship";

$l_planet_cargocapacity = "Kapasitet:";
$l_planet_cargoowned = "Du eier allerede et lasteskip på denne planeten.";
$l_planet_cargoshipbuy = "Kjøp Cargo Ship";
$l_planet_cargoshipupgrade = "Oppgrader Cargo Ship";
$l_planet_cargoatmax = "Din Lasteskip er på maksimalt oppgradere nivå.";
$l_planet_cargoshipbuyinfo = "Velg en forhåndsinnstilling lasteskip";
$l_planet_cargoshipupgradeinfo = "Oppgrader din lasteskip Hull.";
$l_planet_cargoshipbuildinfo = "Bygg ditt eget Cargo Ship";
$l_planet_tradehelp = "1. Du kan skrive en handel port for hver type vare. <br> 2. Du kan ikke bytte en vare på en port som selger samme vare. <br> Trading Goods på varer Port, Ore på en Ore Port, ect. vil ikke gjøre noe. <br> 3. Hvis du ikke ønsker å handle visse varer bare skriv 0 for porten sektor.";
$l_planet_cargocredits = "Auto Trade Credits Mottatt:";
$l_planet_cargonoown = "Du må selv kloden for å lage en Auto Traderoute.";
$l_planet_digtrans = "Transfer herre";
$l_planet_nocredits1 = "Du har ikke nok studiepoeng for denne transaksjonen. Den totale kostnaden er";
$l_planet_nocredits2 = "kreditter og du har bare";
$l_planet_nobase = "Du må ha en base å administrere planeten forsvaret nivåer.";
$l_planet_genesisnoturn = "Du trenger minst 1 tur til å bruke Genesis enhet på planeten.";
$l_planet_nogenesis = "Du trenger en Genesis Enhet å ødelegge en planet.";
$l_planet_wrongclass = "Dette skipet klassen kan ikke brann a Nova Bomb enhet.";

$l_planet_combatpreview = "Combat Forhåndsvisning";
$l_planet_beamfire1 = "Din angrep har blitt oppdaget. Planetary Beams skyte! Økt bredde Fire som skip kommer i for nær planeten å lansere jagerfly.";
$l_planet_beamfire2 = "Din angrep har blitt oppdaget. Planetary Beams skyte! Massiv brann rate fra planeten som bredde Batterier lås på for flere treff!";
$l_planet_beamfire3 = "Din angrep har blitt oppdaget. Planetary Beams skyte! Beam batterier over hele kloden er låsing på for massiv flere brann! Beam brann mye høyere enn antatt!";
$l_planet_beamfire4 = "Din angrep har blitt oppdaget. Planetary Beams skyte! Beam forsvar kan bare låses opp på for en avfyring pass.";

$l_planet_sofanobeamsshields = "er ikke skjøt bjelker på ditt skjold.";
$l_planet_sofanobeamsarmor = "er ikke skjøt bjelker på rustningen din.";
$l_planet_flauncherfailed1 = "Din fighter lansere systemet fungerer.";
$l_planet_flauncherfailed2 = "Du har kun vært i stand til å lansere";
$l_planet_flauncherfailed3 = "prosent av jagerfly.";
$l_planet_nodfightertofighter = "sender ikke noen jagerfly å angripe din jagerfly.";
$l_planet_nodfightertotorp = "sender ikke noen jagerfly å angripe din Torps.";
$l_planet_flauncherfailed3 = "prosent av jagerfly.";
$l_planet_autotradetype = "- [source_type] i havn [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "angriper";
$l_planet_iminsector = "i sektor";
$l_planet_imnova = "bruker en Nova-enhet på";
$l_planet_imsofa = "er SOFA Bombing";
$l_planet_team = "Denne planeten er eid av en lagkamerat, og du ikke har tilgang til informasjonen på denne planeten.";
?>
