<?php
$l_opt2_title = "Lagre Valg";
$l_opt2_passunchanged = "Passordet ble holdt uendret. <BR><BR>";
$l_opt2_srcpassfalse = "Opprinnelige passordet feil. Passordet ble holdt uendret. <BR><BR>";
$l_opt2_newpassnomatch = "Nytt passord felt stemmer ikke. Passordet ble holdt uendret. <BR><BR>";
$l_opt2_passchanged = "Passord endret. <BR><BR>";
$l_opt2_passchangeerr = "Feil å endre passord <BR><BR>";
$l_opt2_userintup = "Brukergrensesnitt innstilling oppdatert. <BR><BR>";
$l_opt2_userintfail = "Kunne ikke oppdatere brukergrensesnitt innstillingen. <BR><BR>";
$l_opt2_chlang = "Språk er satt til [lang]. <p>";
$l_opt2_chtemplate = "Mal er satt til [template]. <p>";
$l_opt2_dhtmlup = "Dynamisk html innstilling oppdatert. <BR><BR>";
$l_opt2_dhtmlfail = "Kunne ikke oppdatere dynamisk html innstillingen. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname endret til [name]. <BR><BR>";
$l_opt2_playernamechanged = "Spilleren navnet endret til [name] og [amount] kreditt trukket fra skipet ditt konto. <BR><BR>";
$l_opt2_mapwidth = "Lokale og Galaxy Kart Bredde:";
?>
