<?php
$l_cu_storing = "Lagring";
$l_cu_inistored = "<b>Alle ini verdier har blitt lagret.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto Route Destinasjon";
$l_cu_warps = "Auto Route fordreier";
$l_cu_deleteroute = "Slett rute";
$l_cu_info = "Klikk på Start Sector å Realspace til denne sektoren og begynne fordreining til bestemmelsesstedet sektor.";
$l_cu_delete2 = "Slett Ruter";
$l_cu_noroutes = "Ingen Auto Ruter";
$l_cu_createroute = "Opprett ny Auto Route";
$l_cu_deleted = "Auto Ruter slettet.";
$l_cu_return = "Tilbake til Auto Route Meny klikk";
$l_cu_created = "Auto rute har blitt opprettet.";
$l_cu_realmove = "Realspace flytte til sektor";
$l_cu_warpmove = "Warp flytte til neste sektor";
$l_cu_warpfinal = "Warp flytte til finalen sektor";
?>
