<?php
$l_ze_title = "Edit Zone";
$l_ze_notowner = "Du er ikke eieren av denne sonen, slik at du ikke kan redigere den.";
$l_ze_name = "Sonenavnet";
$l_ze_allow = "Tillate";
$l_ze_attacks = "Tillat angripe andre skip";
$l_ze_genesis = "Tillat skape nye planeter";
$l_ze_return = "å gå tilbake til soneinformasjon siden";
$l_ze_saved = "Dine endringer er lagret.";
$l_ze_namematch = "FEIL: sonenavnet du oppgav ligner eller passer en eksisterende sone navn.";
?>
