<?php
$l_pre_title = "Endre Realspace Presets";
$l_pre_exceed = "Preset [preset] overstiger univers max av [sector_max]. Ingen forhåndsinnstillinger lagret. <BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Lagre";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] er en ugyldig sektor navn.";
$l_pre_invalidchange = "[sector] er en sektor Genesis sektor. Din gamle forhåndsinnstillingen er uendret.";
?>
