<?php
$l_login_sclosed = "Server Stengt";
$l_login_closed_message = "Server stengt inntil videre.";
$l_login_title2 = "Login Phase Two";
$l_login_banned = "<b>Du har blitt utestengt fra dette spillet av administratoren. Du er ikke lenger velkommen til å spille på denne serveren. Neste gang, oppføre seg.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "På grunn av alvoret i denne forbrytelsen og den onde angrep mot deg, har forbundet allernådigst besluttet å gi en gratis klone fra restene. Dessverre, selv i denne dag og alder, kan nye kloner ikke egen eiendom, bortsett fra det helt grunnleggende til å leve. Du vil bli utstyrt med en grunnleggende skip og noen få kreditter for å komme i gang. Forhåpentligvis ditt neste liv vil bli bedre.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Du hadde ikke unnlate pod, og på grunn av din beskjeden suksess i dette livet, avslår Landsorganisasjonen å klone deg. Ditt fortsatt skulle til slutt falle i en tyngdekraft godt, forhåpentligvis skal brukes til å skape liv andre steder ... flere milliarder år fra nå. <BR><BR> Bedre lykke neste kamp ...";
$l_login_4gotpw1 = "Passordet du oppgav, er feil. <BR><BR> Hvis du har glemt passordet ditt,";
$l_login_4gotpw2 = "å ha den e-post til deg. <BR><BR> Ellers,";
$l_login_4gotpw3 = "å prøve igjen. Forsøk logges med IP-adresse";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Du har dødd i en forferdelig hendelse.";
$l_login_blackbox = "er i Blackbox informasjon som ble hentet fra skip vraket.";
$l_new_login = "å gå til innloggingsbildet.";
$l_login_playerlimit = "Serveren har nådd maksimalt antall spillere den støtter. Prøv å logge inn på et senere tidspunkt.";
?>
