<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] hit [chm_roll] miner i sektoren [chm_sector].";
$l_chm_youlostminedeflectors = "Du mistet [chm_roll] mine sidevindu.";
$l_chm_youlostallminedeflectors = "Du mistet alle mine sidevindu.";
$l_chm_youhadnominedeflectors = "Du hadde ikke min sidevindu.";
$l_chm_yourshieldshitforminesdmg = "Dine skjold er rammet etter [chm_mines_left] skade.";
$l_chm_yourshieldsaredown = "Dine skjoldene er nede!";
$l_chm_youlostallyourshields = "Du mistet alle skjoldene!";
$l_chm_yourarmorhitforminesdmg = "Din rustning er truffet for [chm_mines_left] skade.";
$l_chm_yourhullisbreached = "Din skrog er brutt!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] ble ødelagt av miner i sektoren [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Skipet ditt har blitt ødelagt!";
$l_chm_luckescapepod = "Heldigvis har du en flukt pod!";

$l_chm_yourdeflectormalf1 = "Mine Deflektor lansere systemet fungerer.";
$l_chm_yourdeflectormalf2 = "Du har kun vært i stand til å lansere";
$l_chm_yourdeflectormalf3 = "prosent av min sidevindu.";
$l_chm_enemytorpfailshields = "har ikke lansert noen torpedoer mot dine skjold.";
$l_chm_enemytorpfailarmor = "har ikke lansert noen torpedoer mot rustningen din.";

$l_chm_minemalf1 = "Enemy Mines har fungerer.";
$l_chm_minemalf2 = "Bare";
$l_chm_minemalf3 = "prosent av gruvene angripende fant skipet ditt.";

$l_chm_youhitsomemines = "Du treffer [chm_roll] miner av [total_mines] miner!";
$l_chm_yourdeflectormalf2a = "Du har bare vært i stand til å lansere [deflectors] prosent av min sidevindu.";
$l_chm_mines_destroyed = "[number] av [target] gruver har blitt ødelagt!";
$l_chm_mine_deflectors_left = "Du har [number] gruven sidevindu venstre.";
$l_chm_mines_left = "Det er [number] miner igjen, og de påvirker på rustningen din!";
$l_chm_minemalf2a = "Bare [deflectors] prosent av gruvene angripende fant skipet ditt.";
$l_chm_mines_exhausted = "[player] Mines rekker!";
$l_chm_armor_left = "Du har [number] rustning punkter igjen!";

?>
