<?php
$l_shipyard_title = "Shipyard";
$l_planet = "Planet";
$l_ship_welcome = "Velkommen til din Planetary verftet. For tiden tilbyr vi disse modellene for salg.";
$l_ship_class = "Klassifikasjon";
$l_ship_properties = "Klasse Egenskaper";
$l_ship_current = "Gjeldende";
$l_ship_outstorage = "Get out of Storage";
$l_ship_storagecost = "Lagring Cost";
$l_ship_storagewarn = "Når du tar din Pioneer ut av lagringsplass vil du miste den du ble utstedt ved den opprinnelige skipet ødeleggelse.";
$l_ship_levels = "Ship Components Levels";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Pris";
$l_ship_turns = "Slår til å bygge";
$l_ship_purchase = "Kjøp";
$l_ship_stored = "Lagrede";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Gjennomsnittlig Maksimal Tech Level:";
$l_ship_averagenormaltech = "Gjennomsnittlig Normal Tech Level:";
$l_ship_averagecurrenttech = "Gjennomsnittlig Current Tech Level:";
?>
