<?php
$l_opt_title = "Velg en Team Icon";
$l_opt_errorsize = "Feil: Bildet må ikke være større enn 64x64 piksler i størrelse.";
$l_opt_errortype = "Feil: Bildet må være JPG, GIF-eller PNG";
$l_opt_errornographic = "Feil: ingen grafiske valgt.";
$l_opt_currentavatar = "Ditt Current Team Icon";
$l_opt_uploadavatar = "Laste opp et ikon";
$l_opt_directory = "Velg Team Icon Directory";
$l_opt_change = "Endre Directory";
$l_opt_select = "Velg Team Icon";
$l_opt_noteam = "Du er ikke på et lag.";
$l_opt_notleader = "Bare Team koordinatoren kan endre Team Icon.";
$l_opt_inuse = "Alle Team Ikoner i denne katalogen er i bruk.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
