<?php
$l_defense_deploy_title = "Deploy Sector Mines &amp; Fighters";
$l_defense_deploy_noturn = "Du trenger minst én tur til å distribuere sektor forsvar.";
$l_defense_deploy_nopermit = "Distribuere Gruver og Fighters i denne sektoren er ikke tillatt.";
$l_defense_deploy_nodeploy = "Kan ikke rulle her. Et annet skip eller Team har gruver eller jagerfly i denne sektoren.";
$l_defense_deploy_info1 = "Du er for øyeblikket i sektor [sector]. Det er [mines] gruver og [fighters] jagerfly her.";
$l_defense_deploy_info2 = "Du har [mines] gruver og [fighters] jagerfly tilgjengelig for å distribuere";
$l_defense_deploy_deploy = "Deploy";
$l_defense_deploy_deployed = "Deployert";
$l_defense_deploy_att = "Attack";
$l_defense_deploy_notorps = "Du har ikke nok torpedoer.";
$l_defense_deploy_nofighters = "Du har ikke nok jagerfly";
$l_defense_deploy_dmines = "Deployert [mines] gruver.";
$l_defense_deploy_dfighter = "Deployert [fighters] jagerfly.";
$l_defense_deploy_max_fighters = "Denne sektoren kan støtte maksimalt [amount] jagerfly.";
$l_defense_deploy_toomanyfighters = "Du har forsøkt å distribuere flere jagerfly enn sektor kan støtte.";
?>
