<?php
$l_autoroute_missingwarp = "Neste warplink mangler i denne sektoren. Warp flytte avbrutt.";
$l_autoroute_SDabort = "Flytt Avbrutt på grunn sektor Defenses i sektoren.";
$l_autoroute_turns = "Trekkes [triptime] Turns og flyttet til [targetlink]";
$l_autoroute_noturns = "Du er ute av svinger.";
$l_autoroute_title = "Auto Ruter";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination = "Auto Route Destinasjon";
$l_autoroute_warps = "Auto Route fordreier";
$l_autoroute_deleteroute = "Slett rute";
$l_autoroute_info = "Klikk på Start Sector å Realspace til denne sektoren og begynne fordreining til bestemmelsesstedet sektor.";
$l_autoroute_delete2 = "Slett Ruter";
$l_autoroute_noroutes = "Ingen Auto Ruter";
$l_autoroute_createroute = "Opprett ny Auto Route";
$l_autoroute_deleted = "Auto Ruter slettet.";
$l_autoroute_return = "Tilbake til Auto Route Meny klikk";
$l_autoroute_created = "Auto rute har blitt opprettet.";
$l_autoroute_realmove = "Realspace flytte til sektor";
$l_autoroute_warpmove = "Warp flytte til neste sektor";
$l_autoroute_warpfinal = "Warp flytte til finalen sektor";
$l_autoroute_editname = "Rediger navn";
?>
