<?php
$l_profile_title = "Profil Registrering";
$l_profile_notenabled = "Profiler er ikke aktivert på denne serveren.";
$l_profile_registered = "Denne spilleren er nå registrert med Master Profile Server.";
$l_profile_nomatch = "Kunne ikke matche en profil på Master Profil Server med navn og server passord inn.";
$l_profile_tryagain = "Slik angir du spiller profil navn og server passord på nytt klikk";
$l_profile_name = "Profil Player Navn";
$l_profile_password = "Profil Server Passord";
$l_profile_bannedserver = "Denne serveren er ikke tillatt å sende inn profilen informasjon til Master profil Server.";
$l_profile_bannedplayer = "Du har blitt utestengt fra Master Profil Server og kan ikke registrere spillere.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Denne <u><b>serveren</b></u> krever hver eneste nye spilleren ha et registrert profil. Du vil ikke få lov til å lage en ny spiller med mindre du har registrert profil.";
$l_profile_updated = "Malen, shoutbox og nyheter gjennomgå globale innstillinger har blitt oppdatert på Profil Master Server. Disse innstillingene vil automatisk bli brukt når du registrerer din profil på hvilket som helst spill.";

?>
