<?php
///SPIES
$l_spy_title = "Spy Meny";
$l_spy = "Spies";
$l_spy_disabled = "Spies er deaktivert!";
$l_spy_noturn = "Du trenger minst én tur til å sende en spion til en planet.";
$l_spy_notonboard = "Du har ingen spioner ombord.";
$l_spy_ownplanet = "Du kan ikke sende en spion til din egen planet.";
$l_spy_unownedplanet = "Du kan ikke sende en spion til unowned planeten.";
$l_spy_planetfull = "Det er allerede tillatt [max] spioner på denne planeten.";
$l_spy_sendtitle = "Sende en spion [spyID] til planet: <BR> Velg spion oppgave:";
$l_spy_type1 = "Spionen virker bare på det planet.";
$l_spy_type2 = "Spionen forsøker å infiltrere et skip som utfører en planetarisk overføring.";
$l_spy_type3 = "Spionen forsøker å infiltrere et skip som utfører en planetarisk overføring og infiltrere til en annen planet.";
$l_spy_sendbutton = "Send til planet";
$l_spy_sendsuccessful = "Din spion infiltrerer planeten og venter på det rette øyeblikk å begynne handling.";
$l_spy_sendfailed = "Planet&#39;s Sensorer oppdaget din spion, fordi kappen enheten ikke kunne dekke ham. Din spion blir drept.";
$l_spy_noturn2 = "Du trenger minst én tur til å kalle tilbake en spion.";
$l_spy_confirm = "Er du sikker på at du vil ringe tilbake din spy [spyID]?";
$l_spy_cleanupplanet = "å rydde opp i at planeten fra fiendens spioner.";
$l_spy_cleanupship = "Hvis du ønsker å rydde opp i skipet fra fiendens spioner, klikk";
$l_spy_yourspies = "Din spioner på at planeten";
$l_spy_sendnew = "Send en ny spion";

$l_spy_codenumber = "Kode";
$l_spy_job = "Jobb";
$l_spy_percent = "Prosent";
$l_spy_move = "Movement";
$l_spy_action = "Action";
$l_spy_shipowner = "Skipsreder";
$l_spy_shipname = "Ship Name";
$l_spy_shiptype = "Ship Klassifikasjon";
$l_spy_shiplocation = "Ship Sted";
$l_spy_planetowner = "Planet Eier";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "Rører seg ikke";
$l_spy_moves['toship'] = "Innen";
$l_spy_moves['toplanet'] = "Hvis planet";

$l_spy_comeback = "Ring tilbake";
$l_spy_nospieshere = "Du har ingen spioner på denne planeten!";
$l_spy_transferred = "spioner overføres";
$l_spy_backonship = "Spionen er nå på skipet ditt.";
$l_spy_backfailed = "Ringe tilbake mislyktes.";
$l_spy_changetitle = "Endre spy [spyID] egenskaper:";
$l_spy_occupied = "Din spy [spyID] i ansatt som [job], med prosent [percent].";
$l_spy_dismiss = "Avvise spion?";
$l_spy_changebutton = "Endring";
$l_spy_changejob = "Bytte jobb eller Movement";
$l_spy_linkback = "å gå til spion-menyen.";
$l_spy_changed1 = "Movement endret.";
$l_spy_changed2 = "Spy avskjediget og hans bevegelse forandret.";
$l_spy_changefailed = "Endre mislyktes.";
$l_spy_cleanupplanettitle = "Rydder opp på planeten fra fiendens spioner:";
$l_spy_notyourplanet = "Det er ikke din planet.";
$l_spy_cleanuptext[1] = "Rask opprydding. Bruker [creds] kreditter og [turns] svinger.";
$l_spy_cleanuptext[2] = "Bedre opprydding. Bruker [creds] kreditter og [turns] svinger.";
$l_spy_cleanuptext[3] = "Den beste opprydding. Bruker [creds] kreditter og [turns] svinger.";
$l_spy_cannotcleanupplanet = "Du har bare [credits] kreditter på denne planeten og [turns] svinger.";
$l_spy_cleanupbutton1 = "Start rydde opp planeten";
$l_spy_cleanupplanettitle2 = "Du slått på sensorer for å finne fienden spioner på denne planeten.";
$l_spy_spyfoundonplanet = "Du har funnet en [player] &#39;s spy [spyID] på planeten. Du drepte som spion.";
$l_spy_spynotfoundonplanet = "Du fant ingen fiende spioner på det planet.";
$l_spy_notenough = "Du har ikke nok studiepoeng eller svinger for å starte opprydding.";

$l_spy_cleanupshiptitle = "Rydder opp skipet ditt av fiendens spioner:";
$l_spy_notinspecial = "Du må være på et Enheter port for å rydde opp i skipet.";
$l_spy_cleanupshiptext[1] = "Rask opprydding. Bruker [creds] kreditter og [turns] svinger.";
$l_spy_cleanupshiptext[2] = "Bedre opprydding. Bruker [creds] kreditter og [turns] svinger.";
$l_spy_cleanupshiptext[3] = "Den beste opprydding. Bruker [creds] kreditter og [turns] svinger.";
$l_spy_cannotcleanupship = "Du har bare [credits] kreditter og [turns] svinger.";
$l_spy_cleanupbutton2 = "Start rydde opp skipet ditt";
$l_spy_cleanupshiptitle2 = "Du slått på sensorer for å finne fiendens spioner på skipet ditt.";
$l_spy_spyfoundonship = "Du har funnet en [player] &#39;s spy [spyID] på skipet ditt. Du drepte som spion.";
$l_spy_spynotfoundonship = "Du fant ingen fiende spioner på skipet ditt.";

$l_spy_infodeleted = "Meldingen er slettet";
$l_spy_infonotyours = "Det er ikke din melding.";
$l_spy_noinfo = "Din spioner på fiendtlige skip har ikke merker noe ennå.";
$l_spy_infotitle = "Din spioner har registrert følgende informasjon";
$l_spy_time = "Tid";
$l_spy_type = "Type";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Det er en [player] &#39;s planet [planet] i sektor [sector].";
$l_spy_delete = "Slette";
$l_spy_messages = "å se hva din spioner har oppdaget.";
$l_spy_defaulttitle1 = "Spioner på fiendtlige skip";
$l_spy_defaulttitle2 = "Spioner på fiendens planeter";
$l_spy_defaulttitle3 = "Spies på planeter";
$l_spy_defaulttitle4 = "Spioner på skipet ditt";

$l_spy_no1 = "Du har ingen spioner på fiendtlige skip.";
$l_spy_no2 = "Du har ingen spioner på fiendtlige planeter.";
$l_spy_no3 = "Du har ingen spioner på planeter.";
$l_spy_no4 = "Du har ingen spioner på skipet ditt.";
$l_spy_nospiesatall = "Du har ingen spioner.";
$l_spy_notknown = "Ukjent";


$l_spy_trytitle = "På planeten denne spionen vil prøve å";

$l_spy_cantsendfeds = "Sorry men Spies kan ikke sendes til Federation eller Independent planeter.";
$l_spy_cantsendteam = "Du kan ikke plassere Spies på en lagkamerater planet.";
$l_spy_messagesdeleted = "Alle meldinger slettet";
$l_spy_deleteall = "Slett alle";
$l_spy_onplanet = "Spies på planeten";
$l_spy_menu = "å gå tilbake til Spy Meny.";
?>
