<?php
$l_gns_title = "Bruk Genesis Device";
$l_gns_turn = "Du trenger minst én tur til å bruke en genesis enhet.";
$l_gns_onplanet = "Du kan ikke bruke denne enheten når du er på planetens overflate.";
$l_gns_full = "Dette solsystemet er allerede full.";
$l_gns_planetex = "Det finnes allerede en planet i denne sektoren.";
$l_gns_nogenesis = "Du har ingen genesis enheter.";
$l_gns_forbid = "Opprette en planet i denne sektoren er ikke tillatt.";
$l_gns_bforbid = "Den baser i denne sektoren er i konflikt med din genesis enheten. Planet etableringen ikke mulig.";
$l_gns_pcreate = "Planet opprettet.";
$l_sgns_title = "Bruk Sector Genesis Device";
$l_sgns_pcreate = "Sector [name] opprettet.";
$l_sgns_nogenesis = "Du har ingen sektor genesis enheter.";
$l_sgns_forbid = "Opprette en sektor genesis ormehull i denne sektoren er ikke tillatt.";
$l_sgns_forbid1 = "Opprette en sektor genesis ormehullet en føderasjon sektor er ikke tillatt.";
$l_sgcreate = "Opprett ny Sector Genesis Sector";
$l_sgcreatens = "Opprett ny Sector Genesis Link tilbake til kjente verdensrommet";
$l_sgns_forbid2 = "Mer enn [limit] koblinger i SG Sektorer er ikke tillatt.";
$l_sgns_forbid3 = "Kan ikke opprette Sector Genesis deformere link fra gjeldende sektor - som ville overstige det høyeste av [limit] per sektor.";
$l_sgns_nocredits = "Du har ikke nok studiepoeng til å opprette en ny sektor.";
$l_sgns_shipcredits = "Studiepoeng på skipet:";
$l_sgns_createcost = "Kostnader til å skape nye Sektor:";
$l_sgns_complete = "Normal Space Link Komplett";
$l_sgns_sectorname = "Skriv Sector Navn:";
$l_gns_max_unbased_planets = "Landsorganisasjonen vil ikke tillate etablering av flere planeter inntil du har mindre enn [max_unbased_planets] unbased planeter.";

?>
