<?php
$l_contact_admin_title = "Kontakt Game Administrator";
$l_contact_admin_thanks = "Takk for din kommentar.";
$l_contact_admin_email_alert = "Skriv inn en gyldig e-postadresse.";
$l_contact_admin_name_alert = "Skriv inn ditt navn.";
$l_contact_admin_comment_alert = "Vennligst skriv dine kommentarer.";
$l_contact_admin_name = "Navn";
$l_contact_admin_email = "E-post";
$l_contact_admin_comment = "Spørsmål / kommentar";
$l_contact_admin_submit = "Send spørsmål / kommentarer";
$l_contact_admin_close = "Close Window";
$l_contact_admin_thanks_comment = "Takk for din kommentar eller spørsmål. Vi vil svare på alle spørsmål og sende deg med svaret vårt.";

?>
