<?php
$l_autotrade_title = "Auto Traderoute Meny";
$l_autotrade_dismiss2 = "Auto Traderoutes Slettet.";
$l_autotrade_report = "Auto Traderoute Report";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energi";
$l_autotrade_capacity = "Kapasitet";
$l_autotrade_goods = "Goods Pris";
$l_autotrade_ore = "Ore Price";
$l_autotrade_organics = "Organics Pris";
$l_autotrade_energy = "Energy Price";
$l_autotrade_colonist = "Colonist Pris";
$l_autotrade_credits = "Trade Credits";
$l_autotrade_delete = "Slette <br> Rute";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "No Route";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "studiepoeng";
$l_autotrade_deletebutton = "Slette";
$l_autotrade_noroute2 = "Du har ikke oppsett noen Auto Traderoutes.";
?>
