<?php
$l_new_pwis = "Passordet er";
$l_new_charis = "Ditt tegnnavn er";
$l_new_title2 = "Opprett ny spiller Phase Two";
$l_new_blank = "E-post, sende navn og karakter navn kan ikke være tomt.";
$l_new_inuse = "E-post adresse [username] er allerede i bruk.";
$l_new_forgotpw = "Glemt passordet?";
$l_new_inusechar = "Tegnnavn [character], er allerede i bruk.";
$l_new_similar_inusechar = "Ditt tegnnavn høres for likt [character], et navn som allerede er i bruk.";
$l_new_inuseship = "Ship navn [shipname], er allerede i bruk.";
$l_new_similar_inuseship = "Skipet ditt navn høres for likt [shipname], et navn som allerede er i bruk.";
$l_new_pwsent = "Passord er sendt til [username].";
$l_new_err = "Please try again";
$l_new_topic = "Alien Assault Traders Passord";
$l_new_message = "Greetings, \ n \ nSomeone fra IP-adressen $ ip anmodet at passordet for Traders bli sendt til deg. \ N \ nDen passord er: [pass] \ n \ nThank du \ n \ nDe Traders webteamet.";
$l_new_invalidemail = "Ugyldig e-postadresse.";
$l_new_tutorial = "Klikk her for å lese Mini-opplæring før du logger deg inn i spillet.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "å gå til innloggingsbildet.";

?>
