<?php
$l_sm_title = "Sector Missile Launch";
$l_sm_invalid = "Det er ikke et varp kobling mellom denne sektoren og reisemålet sektor.";
$l_sm_notarg = "Target ikke i denne sektoren.";
$l_sm_noturn = "Du trenger minst én tur til brann din sektor Missile.";
$l_sm_nosectormissile = "Du er ikke balanseført noen Sector missiler.";
$l_sm_noscan = "Sensorer kan ikke få reparasjonen på mål!";
$l_sm_flee = "Target ut manøvrerte sektoren Missile!";
$l_sm_ewd = "Target engasjert en nødsituasjon deformere enheten når den oppdaget sektoren Missile!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] er å angripe skip med en Sector Missile!";
$l_sm_sectormissilefail = "Sektoren Missile fungerer når den traff fiendens skip skjold!";
$l_sm_sectormissilefail2 = "Sektoren Missile fungerer når den traff fiendens skip rustning!";
$l_sm_shieldhit = "[target] &#39;s skjold er rammet etter [amount] skade!";
$l_sm_shieldsdown = "[target] &#39;s skjoldene er nede!";
$l_sm_armorhit = "[target] &#39;s rustning er truffet for [amount] skade!";
$l_sm_armorbreached = "[target] &#39;s rustning brutt!";
$l_sm_targetnoenergy = "Fiendens skip har ikke noen energi! Sector Missile mislykkes!";
$l_sm_attacking = "Offensiv [target] ombord [shipname]";
$l_sm_targetok = "Du har ikke destory [name] s skip.";
$l_sm_lost = "[target] mistet [armor] rustning poeng og [energy] energi enheter.";
$l_sm_destroyed = "[target] &#39;s skip har blitt ødelagt.";
$l_sm_escapepod = "En lekkasje pod ble lansert!";
?>
