<?php
$l_warp_cantsame = "Du kan ikke opprette en kobling når kilden er den samme som destinasjon.";
$l_warp_twoerror = "Bruke en Warp Editor for å lage en to-veis kobling til sektoren [target_sector] er ikke tillatt.";
$l_warp_sectex = "Kan ikke opprette deformere link fra gjeldende sektor - som ville overstige det maksimale $ link_max per sektor.";
$l_warp_linked = "Target sektor ([target_sector]) har allerede en link fra denne sektoren.";
$l_warp_coneway = "Link opprettet en måte å";
$l_warp_ctwoway = "Link laget til og fra";
$l_warp_nomoney = "Du har ikke nok studiepoeng til å opprette warp linken.";
$l_warp_noenergy = "Du har ikke nok energi til å opprette warp linken.";
?>
