<?php
// New News Items

$l_news_planets = "planeter";
$l_news_cols = "Million kolonistene";
$l_news_p_headline = "[player] &#39;s Empire har nå [total] planeter";
$l_news_c_headline = "[player] &#39;s Empire har nå [total] millioner kolonistene";
$l_news_p_textXX = "Føderasjonen har utstedt advarsler om keiserdømmet [name]. [name] har kontroll over [total] planeter og bør betraktes som svært farlig. Alle sektorer må øke sektor forsvar umiddelbart.";
$l_news_c_textXX = "The Empire of [name] opplever massiv overbefolkning på alle planeter med over [total] millioner kolonister. Matmangel kan føre til uro. Alle sektorer bør være oppmerksom på mulige aggressive handlinger av [name] i fremtiden.";

$l_created_universe = "&#39;Universe Creation&#39;";
$l_created_universe_full = "&quot;Forskere forsker begynnelsen av universet har enstemmig bestemt at i dag er det statistisk sannsynlig dag for universet Creation å ha funnet sted &#39;";

$l_news_p_text5 = "Den stigende imperium av [name] har nå fem planeter, vil FNN se handlingene til [name] tettere i fremtiden!";
$l_news_p_text10 = "Den voksende imperium av [name] kontrollerer nå ti planeter Rapporter om FNN si at ytterligere utvidelse av [name] kan føre til krig!";
$l_news_p_text25 = "Den enorme imperium av [name] kolonisert 25 planeter allerede, i et intervju, [name] annonsert at han kan vurdere å senke farten sin ekspansjon i fremtiden!";
$l_news_p_text50 = "Den enorme enormt imperium av [name], representert med 50 planeter i hele galaksen er å få en truende styrke. En av FNN journalister fant ut at [name] er å oppgradere skipet hans planlegger en stor krig. I et intervju med [name] annonsert som er gjort på forsvar hensikt bare!";
$l_news_c_text25 = "Den stigende imperium av [name] har nå 25 millioner kolonister, vil FNN se handlingene til [name] tettere i fremtiden, men svært tydelig at birthrates kommer til å eksplodere!";
$l_news_c_text100 = "De håper imperium av [name] har nå 100 millioner kolonister, etter en eksplosjon av fødselstall, [name] koloniene så ut til å være et godt sted for familier å avgjøre!";
$l_news_c_text500 = "Den store imperium av [name] har nå 500 millioner kolonister, [name] sa i et intervju at koloniseringen av galaksen har nettopp begynt ennå";
$l_news_c_text1000 = "Den humongous imperium av [name] har nå en milliard kolonister, FNN journalister fant ut at [name] er i besittelse av noen rare kloning mekanisme som tillater ham å avle nye kolonister i store mengder. Med denne mengden kolonister, er econmic styrken i dette enorme riket, FNN håper at [name] ikke bruker ikke pengene sine på krigføring";

$l_news_indi_short = "FNN Rumor: over [planets] erklærer uavhengighet.";
$l_news_indi = "FNN har det på god autoritet at over [planets] planeter har bestemt at de er bedre styrt av seg selv og er blitt selvstendig.";

$l_news_nova_short = "FNN Rapport: [name] bruker Nova Bomb.";
$l_news_nova = "FNN har breaking news at [name] har brukt den fryktede Nova Bomb [total] gang (er) for å ødelegge en planet, og alle skip på det.";
$l_news_nova_m_short = "FNN Rapport: [name] bruker Nova Bomb og bommer.";
$l_news_nova_m = "FNN har breaking news at [name] har brukt den fryktede Nova Bomb [total] gang (er) for å prøve og ødelegge en planet. Nova Bomb sprengte utenfor planetenes atmosfære og forårsaket store skader på planetenes infrastruktur.";

$l_news_bounty = "FNN Rapport: [name] places a [amount] kreditt skuddpremie på [name2].";

$l_news_attackerpod_p_short = "FNN Rapport: [name] s skip blir ødelagt.";
$l_news_attackerpod_P = "[name] s skip ble ødelagt under angrep en planet. Heldigvis [name] hadde en Escape Pod og overlevde.";

$l_news_attackerdie_p_short = "FNN Rapport: [name] dør!";
$l_news_attackerdie_p = "[name] s skip ble ødelagt under angrep en planet, og de ble drept fordi de ikke klarte å kjøpe en Escape Pod.";

$l_news_destroyed_p_short = "FNN Rapport: [name] angriper og ødelegger en planet!";
$l_news_destroyed_p = "[name] angrepet [total] planet (r) som eies av [owner] og befolkningen i hver planet ødelagt planeten for å hindre at det blir fanget!";

$l_news_defeated_p_short = "FNN Rapport: [name] angrep og slår en planet!";
$l_news_defeated_p = "[name] angrepet [total] planet (r) som eies av [owner] og beseiret den planetariske Forsvaret!";

$l_news_notdefeated_p_short = "FNN Rapport: [name] angrep en planet og taper!";
$l_news_notdefeated_p = "[name] angrepet [total] planet (r) som eies av [owner] og planetenes forsvar holdt mot den nådeløse angrep!";

$l_news_targetepod_short = "FNN Rapport: [name] angrep a [owner] og vinn!";
$l_news_targetepod = "[name] angrepet [owner] &#39;s skip og ødela den helt. Heldigvis [owner] hadde utstyrt skipet med en Escape Pod og de overlevde.";

$l_news_targetdies_short = "FNN Rapport: [name] angrep a [owner] og dreper dem!";
$l_news_targetdies = "[name] angrepet [owner] &#39;s skip og ødela den helt. Dessverre [owner] ikke utstyrt skipet med en Escape Pod og de var fordampede.";

$l_news_fedcolbounty_short = "FNN Rapport: Føderasjonen slår ned på [name]!";
$l_news_fedcolbounty = "Føderasjonen har i dag sprakk ned på det beryktede rom pirat [name]! [name], som rutinemessig brutt flere mellomrom traktater, ble kort engasjert av Federation Battlecruiser, noe som påførte [amount] kreditter verdt skade på pirat fartøy. Federation tjenestemenn løftet ytterligere slike handlinger i fremtiden!";

$l_news_alliancecolbounty_short = "FNN Rapport: Alliansen slår ned på [name]!";
$l_news_alliancecolbounty = "Alliansen har i dag sprakk ned på det beryktede rom pirat [name]! [name], som rutinemessig brutt flere mellomrom traktater, ble kort engasjert av Alliansen, som påførte [amount] kreditter verdt skade på pirat fartøy. Alliansen tjenestemenn løftet ytterligere slike handlinger i fremtiden!";

$l_news_fedcol_pbounty_short = "FNN Rapport: Føderasjonen jakter ned [name]!";
$l_news_fedcol_pbounty = "Føderasjonen har i dag sprakk ned på det beryktede rom pirat [name]! [name], som rutinemessig brutt flere mellomrom traktater, ble kort engasjert av Federation Battlecruiser, som konfiskerte planeten [planetname] verdi [amount] vekttall i sektor [sector]. Federation tjenestemenn løftet ytterligere slike handlinger i fremtiden!";

$l_news_alliancecol_pbounty_short = "FNN Rapport: The Alliance jakter ned [name]!";
$l_news_alliancecol_pbounty = "Alliansen har i dag sprakk ned på det beryktede rom pirat [name]! [name], som rutinemessig brutt flere mellomrom traktater, ble kort engasjert av Alliansen, som konfiskerte planeten [planetname] verdi [amount] vekttall i sektor [sector]. Alliansen tjenestemenn løftet ytterligere slike handlinger i fremtiden!";

$l_news_fedcol_sbounty_short = "FNN Rapport: Føderasjonen jakter ned [name]!";
$l_news_fedcol_sbounty = "Føderasjonen har i dag sprakk ned på det beryktede rom pirat [name]! [name], som rutinemessig brutt flere mellomrom traktater, ble kort engasjert av Federation Battlecruiser, som konfiskerte et skip ([shiptype]) verdt [cost] i sektor [sector]. Federation tjenestemenn løftet ytterligere slike handlinger i fremtiden!";

$l_news_alliancecol_sbounty_short = "FNN Rapport: The Alliance jakter ned [name]!";
$l_news_alliancecol_sbounty = "Alliansen har i dag sprakk ned på det beryktede rom pirat [name]! [name], som rutinemessig brutt flere mellomrom traktater, ble kort engasjert av Alliansen, som konfiskerte et skip [shiptype] verdi [cost] i sektor [sector]. Alliansen tjenestemenn løftet ytterligere slike handlinger i fremtiden!";

$l_killheadline = "[target] ble drept i en ulykke";
$l_news_killed = "[target] ble drept i en tragisk ulykke i dag. Hvordan heroiske - [target] var det siste medlemmet ombord på skipet hans, da han la merke til var det ingen escape pod venstre for ham. Kan han hvile i fred!";

$l_killSDheadline = "[target] ble drept av Sector Defenses.";
$l_news_killedSD = "[target] ble drept av et overveldende antall sektor Defenses eid av [killer]! Dessverre ble skipet ikke utstyrt med en flukt pod.";

$l_killplanetheadline = "[target] ble drept angrep en planet.";
$l_news_killedplanet = "[target] ble drept under angrep en planet eid av [killer] dag. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

$l_killshipheadline = "[target] ble drept skip kamp.";
$l_news_killedship = "[target] ble drept i et skip til skip strid med [killer] dag. Kapteinen tilsynelatende glemte å utstyre skipet med en flukt pod.";

$l_killsuicideheadline = "[target] begikk selvmord.";
$l_news_killedsuicide = "[target] begikk selvmord i dag. De tok den feige utvei fordi de manglet evnen og motet til å stå imot presset av kommanderende egne skip.";

$l_killsofaheadline = "[target] ble drept sofaen angrep en planet.";
$l_news_killedsofa = "[target] ble drept mens sofa angrep en planet eid av [killer] dag. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

$l_killnovaheadline = "[target] ble drept under en nova angrep.";
$l_news_killednova = "[target] ble drept av [killer] under en nova bombeangrep i dag. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

$l_killnovabackfireheadline = "[target] ble drept av en nova slå tilbake.";
$l_news_killednovabackfire = "[target] ble drept da deres nova bombe slo tilbake i dag. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

$l_killsectormissileheadline = "[target] ble drept av en sektor Missile.";
$l_news_killedsectormissile = "[target] ble drept da en rakett fra Sector [killer] påvirket deres skjold. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

$l_killhunterprobeheadline = "[target] ble drept av en Hunter Probe.";
$l_news_killedhunterprobe = "[target] ble drept da en Hunter Probe fra [killer] påvirket deres skjold. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

$l_killtrapprobeheadline = "[target] ble drept av en Sentry Trap Probe.";
$l_news_killedtrapprobe = "[target] ble drept da en Sentry Trap Probe fra [killer] påvirket deres skjold. Dessverre ble skipet ikke er utstyrt med en flukt pod.";

//-------------------

$l_killpodheadline = "[target] &#39;s skip ble ødelagt i en ulykke";
$l_news_killedpod = "[target] &#39;s skip ble ødelagt i en tragisk ulykke i dag. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killSDpodheadline = "[target] &#39;s skip ble ødelagt av Sector Defenses.";
$l_news_killedSDpod = "[target] &#39;s skip ble ødelagt av et overveldende antall sektor Defenses eid av [killer]! An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killplanetpodheadline = "[target] &#39;s skip ble ødelagt angrep en planet.";
$l_news_killedplanetpod = "[target] &#39;s skip ble ødelagt under angrep en planet eid av [killer] dag. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killshippodheadline = "[target] &#39;s skip ble ødelagt i skip kamp.";
$l_news_killedshippod = "[target] &#39;s skip ble ødelagt i skip til skip strid med [killer] dag. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killsofapodheadline = "[target] &#39;s skip ble ødelagt mens sofa angrep en planet.";
$l_news_killedsofapod = "[target] &#39;s skip ble ødelagt mens sofa angrep en planet eid av [killer] dag. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killnovapodheadline = "[target] &#39;s skip ble ødelagt under en nova angrep.";
$l_news_killednovapod = "[target] &#39;s skip ble ødelagt av [killer] under en nova bombeangrep i dag. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &#39;s skip ble ødelagt av en nova slå tilbake.";
$l_news_killednovabackfirepod = "[target] &#39;s skip ble ødelagt når deres nova bombe slo tilbake i dag. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &#39;s skip ble ødelagt av en sektor Missile.";
$l_news_killedsectormissilepod = "[target] &#39;s skip ble ødelagt da en Sector Missile fra [killer] påvirket deres skjold. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &#39;s skip ble ødelagt av en Hunter Probe.";
$l_news_killedhunterprobepod = "[target] &#39;s skip ble ødelagt da en Hunter Probe fra [killer] påvirket deres skjold. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &#39;s skip ble ødelagt av en Sentry Trap Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s skip ble ødelagt da en Sentry Trap Probe fra [killer] påvirket deres skjold. An Escape Pod transponder ble oppdaget av Federation Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] har blitt forfremmet til [rank]";
$l_news_promoted = "Føderasjonen er glade for å kunngjøre fremme av [name] til graden [rank].";

$l_news_demotedheadline = "[name] har blitt degradert til [rank]";
$l_news_demoted = "Føderasjonen beklager å meddele at degradering av [name] til graden [rank].";

$l_news_namechangedheadline = "[oldname] skiftet navn til [newname]";
$l_news_namechanged = "[oldname] påføres føderasjonen Review Board å skifte navn til [newname]. Føderasjonen har gitt navnet endres. Fra denne dag frem [oldname] skal nå være kjent som [newname]. Alle skip og planeter bør oppdatere sine poster umiddelbart.";

$l_news_found_planets_short = "Federation Survey: [found_planets] nye planeter befinner seg.";
$l_news_found_planets = "Federation Survey speiderne har funnet [found_planets] nye planeter i nyoppdaget sektorer.";

$l_news_new_ports_short = "Federation Survey: [new_ports] nye porter bygget.";
$l_news_new_ports = "Federation Ingeniørene har konstruert [new_ports] nye porter i nyoppdaget sektorer.";

$l_news_addedsectors_short = "Federation Survey: [addedsectors] sektorer oppdaget.";
$l_news_addedsectors = "Federation Survey speiderne har oppdaget [addedsectors] nye sektorer. Forsiktighet anbefales.";

$l_news_artifactheadline = "[playername] avsluttet [artifact]";
$l_news_artifact = "[playername] har funnet alle bitene av [artifact], og har all den makt det kan gi.";

$l_news_artifactfoundheadline = "[playername] funnet [artifact] brikke";
$l_news_artifactfound = "[playername] har funnet en av bitene i [artifact] og behov [pieces] mer [piece].";

?>
