<?php
$l_opt_title = "Valg";
$l_opt_chpass = "Bytt passord";
$l_opt_curpass = "Nåværende passord:";
$l_opt_newpass = "Nytt passord:";
$l_opt_newpagain = "Nytt passord (igjen):";
$l_opt_userint = "Brukergrensesnitt";
$l_opt_usenew = "Bruk nye oppsettet?";
$l_opt_lang = "Språk";
$l_opt_template = "Mal";
$l_opt_select = "Velg ett:";
$l_opt_enabled = "Enabled";
$l_opt_save = "Lagre";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Lokale og Galaxy Kart Bredde:";
$l_opt_profiletitle = "Profil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registrert med Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Når du registrerer din spiller på en annen server malen, shoutbox og nyheter innstillingene ovenfor vil bli brukt på serveren.";
$l_opt_showshoutbox = "Show Shoutbox:";
$l_opt_shownewscrawl = "Vis Nyheter gjennomgang:";
$l_opt_playername = "Player Name:";
$l_opt_playernamecost = "Federation Navneendring Fee: [amount] kreditter";
?>
