<?php
$l_novabomb_turns = "Nova Bomb krever atleast [turns] snur seg mot brann.";
$l_novabomb_planetsdamaged = "Planeter skadet av Nova Bomb";
$l_novabomb_planet = "Planet [name] påført skader fra Nova Bomb.";
$l_novabomb_novaexplode = "Nova Bomb eksploderte da det ble avfyrt, og skipet ditt har lidd enorm skade.";
$l_novabomb_novaexplode2 = "Nova Bomb eksploderte da den ble sparket og skipet ble ødelagt.";
$l_novabomb_notfedsec = "Nova Bomb kan ikke benyttes på Federation eies sektorer.";
$l_novabomb_destroyed_planet = "Din nova bomben sprakk overflaten av planeten og boret inn i kjernen hvor det eksploderte forårsaker planeten til å knuse.";
$l_novabomb_wrongclass = "Dette skipet klassen kan ikke brann a Nova Bomb enhet.";
$l_novabomb_nonova = "Du har ikke en Nova Bomb installert.";
$l_novabomb_novamiss = "Nova Bomb bommer hårfint men påfører skade på planeten.";
$l_novabomb_success = "Sector [sector] har vært Nova bombet!";
$l_novabomb_mines = "Destroyed [mines] sektor Mines.";
$l_novabomb_fighters = "Destroyed [fighters] sektor Fighters.";
$l_novabomb_shipsdamaged = "Skip skadet av Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] påført skader fra Nova Bomb.";
$l_novabomb_ship_survived = "Din skipet var langt nok unna når Nova bombe eksploderte å unngå skade.";
?>
