<?php
$l_news_title = "Universe News";
$l_news_info = "FNN er blant galaksens ledere <br> på nyheter og informasjon om levering. <br> Bemannet 24 timer, syv dager i uken av en <br> dedikerte ansatte i FNN&#39;s galakse hovedkvarter <br> i Proxima Centauri og byråer galaxywide!";
$l_news_for = "Nyheter for";
$l_news_prev = "igår";
$l_news_next = "neste dag";
$l_news_none = "Beklager, ingen nyheter i dag.";
$l_news_flash = "News Flash";
$l_news_end = "Slutt på nyheter";
$l_news_bestviewed = "Best sett i Opera, Safari og IE";
$l_news_fedannouncements = "Federation Kunngjøringer";
$l_news_planetarynews = "Planetary News";
$l_news_planetshipnews = "Planetary and Ship Nyheter";
$l_news_afteractionnews = "Etter Action Combat Nyheter";
?>
