<?php
$l_warp_linkto = "Linker bly fra denne sektoren til";
$l_warp_nolink = "Det er ingen linker ut av denne sektoren.";
$l_warp_query = "Hva sektor ønsker du å opprette en kobling til?";
$l_warp_oneway = "One-way?";
$l_warp_dest = "Alternativt kan du ødelegge en link til sektor.";
$l_warp_destquery = "Hva sektor ønsker du å fjerne en lenke til?";
$l_warp_bothway = "Begge-veier";
$l_warp_create = "Lag et varp kobling mellom Sektor:";
$l_warp_andsector = "og Sektor:";
$l_warp_distance = "med en avstand på";
$l_warp_lightyears = "lysår";
$l_warp_delete = "Slett warp kobling mellom Sektor:";
$l_warp_costcreate = "Koster å lage:";
$l_warp_costdelete = "Kostnad for å slette:";
$l_warp_costenergy = "Energi trengs:";
$l_warp_twoerror = "Bruke en Warp Editor for å lage en to-veis kobling til sektoren [target_sector] er ikke tillatt.";
?>
