<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Velkommen til Casino, tilbyr vi nå følgende spill og fasiliteter";
$l_casino_option = "&quot;Rom";
$l_casino_detail = "&quot;Beskrivelse";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;First Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "»Forsikring";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Dele";
$l_credits = "Studiepoeng";
$l_yourbet = "&quot;Your Bet";
$l_nobet = "&quot;Din innsats har overskredet kredittgrensen, kan du satse igjen.";
$l_dealerwins = "Dealer Wins!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer taper!";
$l_dealerblackjack = "Giveren Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Spiller vinner!";
$l_playerbust = "&quot;Player Busts!";
$l_playerloses = "&quot;Spilleren taper!";
$l_playerblackjack = "&quot;Player BlackJack!";
$l_place_bet = "&quot;Plasser innsatsen";
?>
