<?php
$l_readm_title = "Les melding";
$l_readm_delete = "Meldingen er slettet";
$l_readm_nomessage = "Du har ingen meldinger som venter på deg ...";
$l_readm_center = "Melding Motta Center";
$l_readm_sender = "Melding Avsender";
$l_readm_captn = "Kaptein av";
$l_readm_del = "Slette";
$l_readm_repl = "Svare";
$l_readm_return = "Klikk her for å gå tilbake til hovedmenyen";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Slett alle";
$l_readm_subject = "Emne";
$l_readm_quote = "Sitat";
$l_readm_block = "Block Avsender";
$l_readm_alert = "System Alert";
$l_readm_alertbody = "Ship Computer";
?>
