<?php
$l_footer_one_player_on = "Det er 1 spiller online.";
$l_footer_players_on_1 = "Det er";
$l_footer_players_on_2 = "Spillere online:";
$l_footer_until_update = "sekunder til neste oppdatering.";
$l_footer_no_players_on = "Det er ingen spillere online.";

$l_footer_news = "Lokale FNN News";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = "for hjelp om denne siden.";
$l_footer_click = "Klikk";

$l_footer_open_slots = "Maximum Online:";
$l_footer_onlinereset = "Player Online Time Reset i";
$l_footer_onlinecountdown = "Player Online Time Countdown:";
?>
