<?php
$l_artifact_title = "Hent Artifact";
$l_artifact_list_title = "Liste over Ervervet Artifacts";
$l_artifact_noscan = "Din skannere fant ikke gjenstand.";
$l_artifact_noturn = "Du har ikke nok blir å plukke opp denne gjenstand.";
$l_artifact_classname = "Gjenstand Navn";
$l_artifact_description = "Gjenstand Beskrivelse";
$l_artifact_imagename = "Gjenstand Bilde";
$l_artifact_incomplete = "Gjenstand Pieces";
$l_artifact_process = "Bruk Fullført Artifact";

?>
