<?php
$l_beacon_title = "Deploy Space Beacon";
$l_beacon_notpermitted = "Distribuere plass beacons i denne sektoren er ikke tillatt.";
$l_beacon_reads = "Present beacon leser";
$l_beacon_none = "Det er for øyeblikket ikke et fyrtårn i denne sektoren.";
$l_beacon_enter = "Skriv inn tekst for beacon";
$l_beacon_nowreads = "Beacon leser nå";
$l_beacon_donthave = "Du har ikke en plass beacon.";
?>
