<?php
$l_chf_youretreatback    = "Sie sind zu Ihrer letzten Position zurückgekehrt";
$l_chf_movefailed        = "Bewegung fehlgeschlagen.";
$l_chf_thefightersdetectyou     = "Die Jäger entdecken dich!";
$l_chf_therearetotalfightersindest      = "Es gibt [chf_total_sector_fighters] Jäger in deinem Zielsektor.";
$l_chf_youcanretreat     = "<B>Rückzug</B> - Kostet einen Extraturn.";
$l_chf_inputfight        = "<B>Kampf</B> - Sie müssen alle Jäger abwehren, die den Sektor betreten möchten.";
$l_chf_inputcloak        = "<B>Tarnung</B> - Benutzten Sie Ihr Tarnungs-Gerät um zu versuchen den Jägern aus dem Weg zu gehen.";
$l_chf_go                = "Los";
$l_chf_inputrun        = "<B>Attacke und Rückzug</B> - Sie machen einen Blitzschlag und Rückzug. Sie werden während des Rückzuges wahrscheinlich beschädigt";
?>
