<?php
$l_beacon_title          = "Setzte Weltraum-Signalposten";
$l_beacon_notpermitted   = "Setzten von Weltraum-Signalposten ist in diesem Sektor nicht erlaubt";
$l_beacon_reads          = "Derzeit aktive Signalposten";
$l_beacon_none           = "Es gibt zur Zeit keinen Signalposten in deisem Sektor.";
$l_beacon_enter          = "Eingabe für Signalposten";
$l_beacon_nowreads       = "Signalposten aktiv";
$l_beacon_donthave       = "Sie haben keinen Signalposten.";
?>
