<?php
$l_opt_title             = "Wähle einen Avatar";
$l_opt_errorsize            = "Error: Ihr Bild darf nicht größer als 64x64 Pixel betragen.";
$l_opt_errortype           = "Error: Bild muss im Format JPG, GIF oder PNG vorliegen";
$l_opt_errornographic           = "Error: Keine Grafik ausgewählt.";
$l_opt_currentavatar         = "Ihr jetztiger Avatar";
$l_opt_uploadavatar           = "Avatar hochladen";
$l_opt_directory            = "Avatar-Verzeichnis auswählen";
$l_opt_change              = "Verzeichnis ändern";
$l_opt_select              = "Avatar auswählen";
$l_opt_inuse              = "Alle Avatare in diesem Verzeichnis sind in gebrauch.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
