<?php
///SPIES
$l_dig_title = "Dignitary Menü";
$l_dig = "Würdenträger";
$l_dig_disabled = "Dignataries deaktiviert!";
$l_dig_noturn = "Sie benötigen mindestens einen Turn um einen dignitary auf einen Planeten zu senden.";
$l_dig_notonboard = "Sie haben keine Dignitaries an Bord.";
$l_dig_ownplanet = "Sie können keinen dignitary auf einen feindlichen Planeten senden.";
$l_dig_unownedplanet = "Sie können keinen dignitary auf einen Besitzerlosen Planeten senden.";
$l_dig_planetfull = "Es gibt bereits [max] dignitaries auf dem Planeten.";
$l_dig_sendtitle = "Sende einen dignitary [digID] auf den Planeten:<BR>Wählen Sie eine Mission aus:";

$l_dig_codenumber = "Code";
$l_dig_job = "Job";
$l_dig_percent = "Prozent";
$l_dig_move = "Bewegung";
$l_dig_action = "Aktion";
$l_dig_shipowner = "Schiffseigentümer";
$l_dig_shipname = "Schiffsname";
$l_dig_shiptype = "Schiffsklasse";
$l_dig_shiplocation = "Schiffsposition";
$l_dig_planetowner = "Planeteneigentümer";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sektor";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Maximum pro Planet";
$l_dig_legend = "Würdenträger Legende";
$l_dig_description = "Würdenträger Beschreibung";
$l_dig_waiting_description = "Würdenträger schafft Torpedos und Kämpfer während des Wartens auf einen Job Abtretung an.";
$l_dig_changeerror = "Würdenträger Job Change Report";

$l_dig_nospieshere = "Sie haben keine dignitaries auf diesem Planeten!";
$l_dig_transferred = "dignitaries übertragen";
$l_dig_backonship = "Der dignitary ist jetzt auf Ihrem Schiff.";
$l_dig_dismiss = "dignitary aufgeben?";
$l_dig_changebutton = "Ändern";
$l_dig_notyourplanet = "Das ist nicht Ihr Planet.";

$l_dig_defaulttitle1 = "Dignitaries auf feindlichen Schiffen";
$l_dig_defaulttitle2 = "Dignitaries auf Ihren Planeten";
$l_dig_defaulttitle3 = "Dignitaries auf Ihren Planeten";
$l_dig_defaulttitle4 = "Dignitaries auf Ihrem Schiff";

$l_dig_no1 = "Sie haben keine dignitaries auf feindlichen Schiffen.";
$l_dig_no2 = "Sie haben keine dignitaries auf Ihren Planeten.";
$l_dig_no3 = "Sie haben keine dignitaries auf Ihren Planeten.";
$l_dig_no4 = "Sie haben keine dignitaries auf Ihrem Schiff.";
$l_dig_nodignitaryatall = "Sie haben keine dignitaries.";
$l_dig_notknown = "Unbekannt";
$l_dig_dismiss = "Aufgeben";
$l_dig_dismiss2 = "aufgegebene dignitaries.";
$l_dig_menu = "um zum Dignitary Menü zurück zukehren.";

?>
