<?php
///SPIES
$l_spy_title = "Spions-Menü";
$l_spy = "Spione";
$l_spy_disabled = "Spione sind deaktiviert!";
$l_spy_noturn = "Sie benötigen mindestens einen Turn um einen Spion zu einem Planeten zu schicken.";
$l_spy_notonboard = "Sie haben keine Spione an Bord.";
$l_spy_ownplanet = "Sie können einen Spion nicht auf Ihrn eigenen Planeten schicken.";
$l_spy_unownedplanet = "Sie können einen Spion nicht auf einen Besitzerlosen Planeten schicken.";
$l_spy_planetfull = "Es sind bereits [max] erlaubte Spione auf diesem Planeten.";
$l_spy_sendtitle = "Sende Spion [spyID] auf den Planeten:<BR>Wählen Sie eine Mission:";
$l_spy_type1 = " Der Spion agiert nur auf diesem Planeten.";
$l_spy_type2 = " Der Spion versucht ein Schiff zu infiltrieren welches einen planetarischen Transfer durchführt";
$l_spy_type3 = " Der Spion versucht ein Schiff zu infiltrieren welches einen planetarischen Transfer durchführt, und wird dann einen anderen Planeten infiltrieren.";
$l_spy_sendbutton = "Auf den Planeten schicken";
$l_spy_sendsuccessful = "Ihr Spion infiltriert den Planeten und wartet auf den richtigen Augenblick, um seine Handlungen zu beginnen.";
$l_spy_sendfailed = "Die Sensoren des Planeten haben Ihren Spion entdeckt, weil Ihr Tarnungsgerät Ihern Spion nicht genügend verstecken konnte. Ihr Spion wurde getötet.";
$l_spy_noturn2 = "Sie benötigen mindestens einen Turn um einen Spion zurück zuholen.";
$l_spy_confirm = "Sind Sie sicher, dass Sie Ihren Spion [spyID] zurück holen möchten?";
$l_spy_cleanupplanet = "um den Planeten von feindlichen Spionen zu befreien.";
$l_spy_cleanupship = "Wenn Sie Ihr Schiff von feindlichen Spionen befreien möchten, klicken Sie ";
$l_spy_yourspies = "Ihre Spione auf diesem Planeten";
$l_spy_sendnew = "Einen neuen Spion senden";

$l_spy_codenumber = "Code";
$l_spy_job = "Job";
$l_spy_percent = "Prozent";
$l_spy_move = "Bewegung";
$l_spy_action = "Aktion";
$l_spy_shipowner = "Schiffseigentümer";
$l_spy_shipname = "Schiffsname";
$l_spy_shiptype = "Schiffsklasse";
$l_spy_shiplocation = "Schiffsposition";
$l_spy_planetowner = "Planeteneigentümer";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sektor";

$l_spy_moves['none'] = "bewegt sich nicht";
$l_spy_moves['toship'] = "aufs Schiff";
$l_spy_moves['toplanet'] = "auf den Planeten";

$l_spy_comeback = "Zurück holen";
$l_spy_nospieshere = "Sie haben keine Spione auf diesem Planeten!";
$l_spy_transferred = "Spion transferiert";
$l_spy_backonship = "Der Spion ist nun auf Ihrem Schiff.";
$l_spy_backfailed = "Rückholaktion fehlgeschlagen.";
$l_spy_changetitle = "Ändere Eigenschaften des Spion [spyID]:";
$l_spy_occupied = "Ihr Spion [spyID] ist mit [percent] Prozent als [job] tätig.";
$l_spy_dismiss = "Den Spion wirklich aufgeben?";
$l_spy_changebutton = "Ändern";
$l_spy_changejob = "Change Job oder Bewegung";
$l_spy_linkback = "um zum Spion-Menü zu gehen.";
$l_spy_changed1 = "Bewegung geändert.";
$l_spy_changed2 = "Spion aufgegeben und Bewegung geändert.";
$l_spy_changefailed = "Änderung fehlgeschlagen.";
$l_spy_cleanupplanettitle = "Säubere Ihren Planeten von feindlichen Spionen:";
$l_spy_notyourplanet = "Das ist nicht Ihr Planet.";
$l_spy_cleanuptext[1] = "Schnelles Säubern. Benötigt [creds] Credits und [turns] Turns.";
$l_spy_cleanuptext[2] = "Mittleres Säubern. Benötigt [creds] Credits und [turns] Turns.";
$l_spy_cleanuptext[3] = "Bestes Säubern. Benötigt [creds] Credits und [turns] Turns.";
$l_spy_cannotcleanupplanet = "Sie haben nur [credits] Credits auf diesem Planeten und [turns] Turns übrig.";
$l_spy_cleanupbutton1 = "Beginne Säuberung des Planeten";
$l_spy_cleanupplanettitle2 = "Sie haben Ihre Sensoren aktiviert um feindliche Spione auf disem Planeten aufzuspüren.";
$l_spy_spyfoundonplanet = "Sie haben [player]'s Spion [spyID] auf diesem Planeten gefunden. Sie haben diesen Spion getötet.";
$l_spy_spynotfoundonplanet = "Sie haben keinen feindlichen Spion auf diesem Planeten gefunden.";
$l_spy_notenough = "Sie haben nicht genügend Credits oder Turns um die Reinigung zu beginnen.";

$l_spy_cleanupshiptitle = "Säubere Ihr Schiff von feindlichen Spionen:";
$l_spy_notinspecial = "Sie müssen an einem Geräte-Port sein, um Ihr Schiff zu säubern.";
$l_spy_cleanupshiptext[1] = "Schnelles Säubern. Benötigt [creds] Credits und [turns] Turns.";
$l_spy_cleanupshiptext[2] = "Mittleres Säubern. Benötigt [creds] Credits und [turns] Turns.";
$l_spy_cleanupshiptext[3] = "Bestes Säubern. Benötigt [creds] Credits und [turns] Turns.";
$l_spy_cannotcleanupship = "Sie haben nur [credits] Credits und [turns] Turns.";
$l_spy_cleanupbutton2 = "Beginne Säuberung des Schiffs";
$l_spy_cleanupshiptitle2 = "Sie haben Ihre Sensoren aktiviert um feindliche Spione auf Ihrem Schiff aufzuspüren.";
$l_spy_spyfoundonship = "Sie haben [player]'s Spion [spyID] auf Ihrem Schiff gefunden. Sie haben diesen Spion getötet.";
$l_spy_spynotfoundonship = "Sie haben keinen feindlichen Spion auf Ihrem Schiff gefunden.";

$l_spy_infodeleted = "Nachricht gelöscht";
$l_spy_infonotyours = "Es ist nicht Ihre Nachricht.";
$l_spy_noinfo = "Ihre Spione auf dem feindlichen Schiff haben bisher nichts entdeckt.";
$l_spy_infotitle = "Ihre Spione haben die folgenden Informationen ausgekundschaftet";
$l_spy_time = "Zeit";
$l_spy_type = "Typ";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Es gibt einen Planeten [planet] von [player] im Sektor [sector].";
$l_spy_delete = "Löschen";
$l_spy_messages = "um zu sehen, was Ihre Spione ausgekundschaftet haben.";
$l_spy_defaulttitle1 = "Spione auf feindlichen Schiffen";
$l_spy_defaulttitle2 = "Spione auf feindlichen Planeten";
$l_spy_defaulttitle3 = "Spione auf Ihren Planeten";
$l_spy_defaulttitle4 = "Spione auf Ihrem Schiff";

$l_spy_no1 = "Sie haben keine Spione auf feindlichen Schiffen.";
$l_spy_no2 = "Sie haben keine Spione auf feindlichen Planeten.";
$l_spy_no3 = "Sie haben keine Spione auf Ihren Planeten.";
$l_spy_no4 = "Sie haben keine Spione auf Ihrem Schiff.";
$l_spy_nospiesatall = "Sie haben keine Spione.";
$l_spy_notknown = "Unbekannt";


$l_spy_trytitle = "Auf dem Planeten versucht der Spion";

$l_spy_cantsendfeds = "Sorry, aber Spione können nicht auf Planeten der Föderation oder unabhängige Planeten geschickt werden.";
$l_spy_cantsendteam = "Sie können keine Spione auf dem Planeten eines Teammitglieds plazieren.";
$l_spy_messagesdeleted = "Alle Nachrichten wurden gelöscht";
$l_spy_deleteall = "Alles löschen";
$l_spy_onplanet = "Spione auf dem Planeten";
$l_spy_menu = "um zum Spion-Menü zurück zukehren.";
?>
