<?php
$l_move_title            = "Bewegung";
$l_move_turn             = "Sie benötigen mindestens 1 Turn, um sich zu bewegen.";
$l_move_failed           = "Bewegung fehlgeschlagen!";
$l_rs_title = "RealSpace Move";
$l_rs_whichsector        = "Welchen Sektor möchten Sie mit RealSpace erreichen?";
$l_rs_insector           = "Sie sind momentan im Sektor [sector] - Und es sind Sektoren von 1 [sector_max] verfügbar.";
$l_rs_submit             = "Berrechnen";
$l_rs_movetime           = "Mit Ihrem Antrieb würde es [triptime] Turn benötigen.";
$l_rs_energy             = "Sie sollten [energy] Einheiten von Energie einsammeln";
$l_rs_noturns            = "Sie haben nicht genügend Turns übrig und können Sich daher nicht auf diese Reise begeben.";
$l_rs_engage_link        = "Aktivieren";
$l_rs_engage             = "Sie haben [turns] Turns. [engage] Antrieb?";
$l_rs_invalid            = "Sie können mit dem RealSpace nicht bis zu diesem Sektor gelangen.";
$l_rs_ready              = "Sie sind momentan im Sektor [sector]. Sie haben [triptime] Turns benutzt und [energy] Energieeinheiten verbraucht.";
$l_warp_invalid = "Sie können keine Kette für diesen Sektor von hier.";
$l_move_unknown = "Unbekannt Movetype";
?>
