<?php
$l_news_title            = "GalaxyNews";
$l_news_info             = "FNN ist unter den galaktischen Leadern<br>für News und Informationszustellung<br>24 Stunden am Tag, 7 Tage die Woche<br> wird auf Proxima Centauri und in Büros im ganzen Weltraum der Stoff für FNN's GalaxyNews geschrieben.!";
$l_news_for              = "News für";
$l_news_prev             = "letzter Tag";
$l_news_next             = "nächster Tag";
$l_news_none             = "Sorry, heut gibts keine News.";
$l_news_flash = "News Flash";
$l_news_end              = "Ende der News";
$l_news_bestviewed = "Best viewed in Opera, Safari und IE";
$l_news_fedannouncements = "Föderation Ankündigungen";
$l_news_planetarynews = "Planetary News";
$l_news_planetshipnews = "Planetary and Ship News";
$l_news_afteractionnews = "After Action Combat News";

?>
