<?php
$l_by_title              = "Prämien";
$l_by_noturn             = "Die benötigen mindestens einen Turn um eine Prämie auszusetzten oder zu verändern.";
$l_by_amount             = "Betrag der Prämie";
$l_by_place              = "Prämie aussetzten";
$l_by_nobounties         = "Es sind im Moment keine Prämien ausgesetzt.";
$l_by_bountyon           = "Prämie auf";
$l_by_placedby           = "ausgesetzt von";
$l_by_thefeds            = "Die Föderation";
$l_by_cancel             = "Abbrechen";
$l_by_yourself           = "Sie können keine Prämie auf sich selbst aussetzten.";
$l_by_notenough          = "Sie haben nicht genügend Credits um eine Prämie mit diesem Betrag auszusetzten.";
$l_by_toomuch            = "Sie können diese Prämie nicht aussetzten. Die Maximal Betrag einer Prämie auf andere Spieler liegt bei [percent] Prozent Ihres Netto-Vermögens";
$l_by_zeroamount         = "Prämien müssen mehr als einen Credit betragen.";
$l_by_placed             = "Die Prämie wurde ausgesetzt.";
$l_by_nobounty           = "Diese Prämie existiert nicht mehr.";
$l_by_notyours           = "Diese Prämie wurde nicht von Ihnen ausgesetzt.";
$l_by_canceled           = "Die Prämie wurde abgebrochen.";
$l_by_action             = "Aktion";
$l_by_placebounty        = "Prämien ansehen oder aussetzten.";
$l_by_moredetails        = "Klicken Sie für mehr Informationen auf den Namen.";
$l_by_fedbounty          = "<font color='red' size='4'><b>Der Angriff auf diesen Spieler würde Prämie auf Sie, ausgesetzt durch die Föderation, nach sich ziehen.</b></font>";
$l_by_fedbounty2         = "<font color='red' size='4'><b>Die Föderation akzeptiert Attacken auf schwächere Spieler nicht. Sie hat eine Prämie auf Sie ausgesetzt.</b></font>";
$l_by_notexists          = "Der Spieler, auf den Sie eine Prämie aussetzten wollen existiert nicht.";
$l_by_destroyed          = "Sie können keine Prämie auf einen Spieler mit einem zerstören Schiff aussetzten.";
$l_by_nofedbounty		 = "Sie werden keine Prämie erhalten, wenn Sie diesen Spieler/ oder Planeten angreifen.";
$l_by_fedcollectonly		 = "Nur die Föderation kann Prämien einsammeln";
$l_gotobounty          ="<A HREF=bounty.php>Hier</A> klicken um zum Prämien-Menü zurück zukehren.";

$l_by_fedbountyspy          = "<font color='red' size='4'><b>Wenn Sie einen Spion auf diesem Planeten aussetzten wird die Föderation eine Prämie auf Sie aussetzten</b></font>";
$l_by_fedbountyspy2         = "<font color='red' size='4'><b>Die Föderation akkzeptiert es nicht, wenn Spione auf Planeten schwächere Spieler eingesetzt werden. Es wurde eine Prämie auf Sie ausgesetzt.</b></font>";
$l_by_nofedbountyspy		 = "Sie werden keine Prämie erhalten, wenn Sie einen Spion auf diesem Planeten einsetzten.";
$l_pay_partial = "Rate bezahlen";
$l_pay_button = "Bezahlen";

$l_by_thealliance = "Das Bündnis";
$l_by_alliancecollectonly = "Nur die Allianz kann Collect Bounty";
$l_by_bountyscan = "Bounty";
?>
