<?php
$l_warp_cantsame         = "Sie können keinen Link erstellen, wenn der Ursprung der gleiche ist, wie das Ziel.";
$l_warp_twoerror         = "Der Gebrauch des Warp-Editors für einen Zweiwegelink zum Sektor [target_sector] ist nicht erlaubt.";
$l_warp_sectex           = "Erstellung des Warplinks vom aktuellen Sektor fehlgeschlagen - Das würde das Maximum von $link_max per sector Links in einem Sektor überschreiten.";
$l_warp_linked           = "Zielsektor ([target_sector]) hat bereits einen Link von diesem Sektora.";
$l_warp_coneway          = "Einweglink erstellt nach";
$l_warp_ctwoway          = "Zweiweglink erstellt von und nach";
$l_warp_nomoney          = "Sie haben nicht genügend Credits um einen Warplink zu erstellen.";
$l_warp_noenergy          = "Sie haben nicht genügend Energie um einen Warplink zu erstellen.";
?>
