<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: Shoutbox::.";
$l_shout_public         = "öffentlich";
$l_shout_team = "Team";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else          = "oder";
$l_shout_refresh = "Aktualisieren";
$l_shout_close          = "Schliesse Fenster";
$l_shout_saved          = "Shout gespeichert!";
$l_shout_return          = "Zurück zur ";
$l_shout_prev = "Zurück";
$l_shout_next = "Nächster";
$l_shout_selectpage = "Wählen Sie &quot;Seite";
$l_shout_page = "Seite:";
$l_shout_teamtitle = ".:: TEAM Shoutbox::.";
?>
