<?php
$l_contact_admin_title = "Kontakt Game Administrator";
$l_contact_admin_thanks = "Vielen Dank für Ihren Kommentar.";
$l_contact_admin_email_alert = "Bitte geben Sie eine gültige E-Mail-Adresse.";
$l_contact_admin_name_alert = "Bitte geben Sie Ihren Namen ein.";
$l_contact_admin_comment_alert = "Bitte geben Sie Ihre Kommentare.";
$l_contact_admin_name = "Name";
$l_contact_admin_email = "E-Mail";
$l_contact_admin_comment = "Frage / Kommentar";
$l_contact_admin_submit = "Submit Fragen / Kommentare";
$l_contact_admin_close = "Fenster schließen";
$l_contact_admin_thanks_comment = "Vielen Dank für Ihre Anregung oder Frage. Wir werden Fragen per E-Mail-Adresse und Sie mit unserer Antwort.";

?>
