<?php
$l_scan_title            = "Scanne Shiff";
$l_scan_turn             = "Sie brauchen mindestens einen Turn um ein anderes Schiff zu scannen.";
$l_scan_ron              = "Scan Resultate von";
$l_scan_capt             = "Kapitän:";
$l_scan_arma             = "Bewaffnung:";
$l_scan_carry            = "Beförderung:";
$l_scan_bounty           = "Auf dieses Schiff ist eine Prämie von insgesamt [amount] Sredits ausgesetzt.";
$l_scan_fedbounty        = "Auf dieses Schiff wurde eine Prämie von der Föderation ausgesetzt.";
$l_by_nofedbounty        = "Der Angriff dieses Spielers wird die Föderation <B>NICHT</B> dazu bringen eine Prämie auf Sie auszusetzten.";
?>
