<?php
$l_autoroute_missingwarp          = "Nächster Warplink im Sektor fehlt. Abbruch.";
$l_autoroute_SDabort = "Move Abbruch aufgrund Sector Defenses in der Branche.";
$l_autoroute_turns          = "[triptime] Turns abgerechnet und nach [targetlink] bewegt";
$l_autoroute_noturns           = "Sie haben keine Turns mehr.";
$l_autoroute_title          = "Auto Route";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Route Start";
$l_autoroute_destination       = "Auto Route Ziel";
$l_autoroute_warps       = "Auto Route Warp";
$l_autoroute_deleteroute       = "Lösche Route";
$l_autoroute_info       = "Klicken Sie auf den Startsektor zum Realspace zu diesem Sektor und starte den Warp zum Zielsektor.";
$l_autoroute_delete2       = "Lösche Routes";
$l_autoroute_noroutes       = "Keine Auto Routes";
$l_autoroute_createroute       = "Erstelle neue Auto Route";
$l_autoroute_deleted       = "Auto Routes gelöscht.";
$l_autoroute_return       = "Zurück zum  Auto Route Menü klick";
$l_autoroute_created       = "Auto Route wurde erstellt.";
$l_autoroute_realmove       = "Realspace zu diesem Sektor";
$l_autoroute_warpmove       = "Warp zum nächsten Sektor";
$l_autoroute_warpfinal       = "Warp zum Endsektor";
$l_autoroute_editname = "Name bearbeiten";
?>
