<?php
$l_warp_unlinked         = "Zielsektor ([target_sector]) hat keinen Link zu diesem Sektor.";
$l_warp_forbidtwo        = "Einen Warpeditor zur entfernung eines Zweiwegelinks zum Sektor [target_sector] ist nicht erlaubt.";
$l_warp_removed          = "Link gelöscht nach";
$l_warp_removedtwo       = "Link gelöscht von und nach";
$l_warp_nomoney          = "Sie haben nicht genügend Credits um den Warp-Link zu löschen.";
$l_warp_noenergy          = "Sie haben nicht genügend Energie um den Warp-Link zu löschen.";
?>
