<?php
$l_zi_title              = "Zonen-Information";
$l_zi_nexist             = "Diese Auswahl an Weltraum existiert nicht!";
$l_zi_feds               = "Föderation";
$l_zi_traders            = "Alleierter Weltraum";
$l_zi_nobody             = "Niemand";
$l_zi_war                = "Umkämpfter Weltraum";
$l_zi_allow              = "erlaubt";
$l_zi_notallow           = "nicht erlaubt";
$l_zi_limit              = "Für Eigentümer und alleierte limitiert";
$l_zi_ul                 = "Unlimitiert";
$l_zi_control            = "Sie kontrollieren diese Zone";
$l_zi_tochange           = "zum ändern der Gesetze.";
$l_zi_owner              = "Zoneneigentümer";
$l_zi_maxhull            = "Maximal erlaubter Durchschnitts-Techlevel";
?>
