<?php
$l_defense_deploy_title           ="Setzte Sektor-Minen und Jäger aus";
$l_defense_deploy_noturn          ="Sie benötigen mindestens einen Turn um die Sektor-Abwehr auszusetzten.";
$l_defense_deploy_nopermit        ="Minen und Jäger sind in diesem Sektor nicht erlaubt.";
$l_defense_deploy_nodeploy        ="Konnten nicht ausgesetzt werden.Ein anderes Schiff hat Minen oder Jäger in diesem Sektor.";
$l_defense_deploy_info1           ="Sie sind momentan im Sektor [sector]. Es gibt hier [mines] Minen und [fighters] Jäger.";
$l_defense_deploy_info2           ="Sie haben [mines] Minen und [fighters] Jäger verfügbar";
$l_defense_deploy_deploy          ="Aussetzten";
$l_defense_deploy_deployed        ="Aussgesetzt";
$l_defense_deploy_att             ="Angriff";
$l_defense_deploy_notorps         ="Sie haben nicht genügend Torpedos.";
$l_defense_deploy_nofighters      ="Sie haben nicht genügend Jäger";
$l_defense_deploy_dmines          ="[mines] Minen ausgesetzt.";
$l_defense_deploy_dfighter        ="[fighters] Jäger ausgesetzt.";
$l_defense_deploy_max_fighters = "Dieser Sektor kann ein Maximum von [amount] unterstützt Kämpfer.";
$l_defense_deploy_toomanyfighters = "Sie haben versucht, mehr Kämpfer bereitstellen als die Branche unterstützen kann.";
?>
