<?php
$l_mail_title            ="Mail-Passwort";
$l_mail_noplayer         ="Kein solcher Spieler! - Erstelle einen neuen Spieler <a href=new_player.php>hier</a>.";
$l_mail_sent             ="Passwort wurde verschickt an";
$l_mail_topic            ="$game_name Passwort";
$l_mail_message          ="Gürüße,\n\nJemand mit der IP-Adresse $ip verlangte, dass Ihr Passwort für $game_name per E-Mail an Sie verschickt wird\n\nIhr Passwort ist: [pass]\n\nDanke\n\nDas $game_name web team.";
$l_new_login             = "um zum Login zu gelangen.";
$l_mail_failed             ="Passwort konnte nicht verschickt werden!";
?>
