<?php
$l_login_sclosed		= "Server geschlossen";
$l_login_closed_message		= "Server wurde bis auf weiteres geschlossen.";
$l_login_title2			= "Login-Phase zwei";
$l_login_banned			= "<b>Sie wurden vom Administrator gebannt. Sie sind auf diesem Server nicht mehr Willkommen. Benehmen Sie sich das nächste Mal anständiger.</b>";
$l_login_died			= "Ihr Schiff wurde zerstört, aber Ihre Retungskapsel hat Sie und Ihre Manschaft gerettet. <A HREF=main.php>Hier</A> klicken um mit einem neuen Schiff weiter zumachen.";
$l_login_newbie			= "Wegen des Ernstes Ihrer Lage und der brutalen Attacke gegen Sie hat die Föderation gnädigerweise entschieden Ihre Reste umsonst zu klonen. Leider haben Klone, selbst in dieser Zeit kein Eigentum, ausser dem Lebenswichtigsten. Sie werden unterstützt mit einem neuen Schiff und einigen Credits, um wieder von vorne zu beginnen. Hoffentlich wird Ihr nächstes Leben erfolgreicher.";
$l_login_newlife		= "<A HREF=main.php>Hier</A> klicken, um ein neues Leben zu beginnen.";
$l_login_looser			= "Sie hatten keine Rettungskapsel. Wegen Ihres bescheidenen Erfolges in diesem Leben hat die Föderation eine Klonung ausgeschlossen. Ihre Überreste werden womöglich in eine Gravitationswelle geraten, wo Sie möglicherweise anderswo wieder Leben schaffen werden. Einige Millionen Jahre entfernt von hier vielleicht.<BR><BR> Mehr Glück im nächsten Spiel...";
$l_login_4gotpw1		= "Das Passwort, das Sie eingegeben haben ist falsch.<BR><BR>  Falls Sie Ihr Passwort vergessen haben, ";
$l_login_4gotpw2		= "um es per E-Mail zu erhalten.<BR><BR>  Andernfalls,";
$l_login_4gotpw3		= "um es nochmal zu versuchen.  Der Versuch wurde geloggt, und kommt von der IP-addresse";
$l_login_noone			= "Dieser Spieler exisitert nicht! - Um einen neuen Spieler zu erstellen klicken Sie bitte <A HREF=new_player.php>hier</A>.";
$l_login_diedincident			= "Sie sind bei einem schrecklichen Zwischenfall gestorben.";
$l_login_blackbox			= " ist die Blackbox-Information, die von Ihrem zerstörten Schiff geborgen werden konnte.";
$l_new_login             = "um zum Login-Screen zu gelangen.";
$l_login_playerlimit		= "Der Server hat die maximale Anzahl von Spielern erreicht, die er unterstützt. Bitte versuchen Sie es später noch einmal.";
?>
