<?php
$l_autotrade_title = "Auto Handelsroute Menü";
$l_autotrade_dismiss2 = "Auto Handelsrouten gelöscht.";
$l_autotrade_report = "Auto Handelsrouten-Bericht";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hülle";
$l_autotrade_energy = "Energie";
$l_autotrade_capacity = "Kapazität";
$l_autotrade_goods = "Güter-Preis";
$l_autotrade_ore = "Erz-Preis";
$l_autotrade_organics = "organisches Material-Preis";
$l_autotrade_energy = "Energie-Preis";
$l_autotrade_colonist = "Colonist Preis";
$l_autotrade_credits = "Handels-Credits";
$l_autotrade_delete = "Lösche<br>Route";
$l_autotrade_unnamed = "Unbenannt";
$l_autotrade_noroute = "Keine Route";
$l_autotrade_sector = "Sektor";
$l_autotrade_credit2 = "Credits";
$l_autotrade_deletebutton = "Lösche";
$l_autotrade_noroute2 = "Sie haben keine Auto Handelsroute eingestellt.";
?>
