<?php
$l_opt_title             = "Wählen Sie ein Team-Icon";
$l_opt_errorsize            = "Error: Ihr Bild muss größer als 64x64 Pixeln sein.";
$l_opt_errortype           = "Error: Ihr Bild muss im Format JPG, GIF oder PNG sein";
$l_opt_errornographic           = "Error: keine Grafik ausgewählt.";
$l_opt_currentavatar         = "Ihr aktuelles Team-Icon";
$l_opt_uploadavatar           = "Icon hochladen";
$l_opt_directory            = "Team-Icon-Verzeichnis auswählen";
$l_opt_change              = "Verzeichnis ändern";
$l_opt_select              = "Team-Icon auswählen";
$l_opt_noteam              = "Sie sind kein Mitglied eines Teams.";
$l_opt_notleader              = "Nur der Team-Koordinator kann das Team-Icon ändern.";
$l_opt_inuse              = "Alle Team-Icons in diesem Verzeichnis werden benutzt.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
