<?php
$l_glxy_title             = "lokale galaktische Karte";
$l_glxy_select             = "Sektoren, die möglicherweise innerhalb von ";
$l_glxy_turns             = " turns erreichbar sind.";
$l_glxy_nonteamed              = " oder Teamlosen Sektor";
$l_glxy_personal              = "Teamlose Sektoren";
$l_glxy_nosectors = "Sie haben nicht gescannt worden sind oder alle Sektoren im ausgewählten Bereich.";

?>
