<?php
$l_s_yes               = "Ja";
$l_s_no                = "Nein";
$l_s_enabled           = "aktiviert";
$l_s_disabled          = "deaktiviert";

$l_s_modules           = "Module";
$l_s_modulename        = "Modul-Name";
$l_s_moduleauthor      = "Autor";
$l_s_moduleinfo = "Info";
$l_s_nomodules         = "Keine Module geladen";

$l_s_gamestatus        = "Spiel-Status";
$l_s_allowpl           = "Allow Spieler";
$l_s_allownewpl        = "Allow neue Spieler";

$l_s_gameoptions       = "Spiel-Einstellungen";
$l_s_allowteamplcreds  = "Erlaube Team-Planeten-Credit-Übertragung";
$l_s_allowfullscan     = "Erlaube kompletten Reichweite-Scan";
$l_s_sofa              = "Erlaube Sub-Orbitale Jägerattacken";
$l_s_showpassword      = "Deaktiviere Passwor bei der Registrierung";
$l_s_genesisdestroy    = "Genesis Torpedos können Planeten zerstören";
$l_s_igb               = "Intergalaktische Bank (igb)";
$l_s_ksm               = "Karte des bekannten Weltraums";
$l_s_navcomp           = "Navigations-Computer";
$l_s_newbienice        = "Anfängerfreundlich";
$l_s_spies             = "Spion-System";
$l_s_spycapture        = "Erlaube Spionen Planeten zu erobern";

$l_s_gamesettings      = "Spiel-Einstellungen";
$l_s_gameversion       = "Spiel-Version:";
$l_s_minhullmines      = "Minimale Hüllengröße, um eine Mine zu treffen";
$l_s_averagetechewd    = "Durchschnittlicher Tech-Level wenn Notwarp fällt";
$l_s_numsectors        = "Anzahl an Sektoren";
$l_s_maxwarpspersector = "Maximale Anzahl an Links pro Sektor";
$l_s_averagetechfed    = "Maximaler durchschnittlicher Tech-Level für den Föderations-Sektor";
$l_s_igbirateperupdate = "igb Verzinsungsrate pro Aktualisierung";
$l_s_igblrateperupdate = "igb Kredietrate pro Aktualisierung";
$l_s_techupgradebase   = "Tech-Level upgrade für Basen";
$l_s_collimit          = "Kolonisten-Limit";
$l_s_maxturns          = "Maximale Anzahl von gespeicerten Turns";
$l_s_maxplanetssector  = "Maximale Anzahl an Planeten pro Sektor";
$l_s_maxtraderoutes    = "Maximale Anzahl an Handelsrouten fro Spieler";
$l_s_colreprodrate     = "koloniale Geburtenrate";
$l_s_energyperfighter  = "Energieeinheiten die für einen Sektor-Jäger benötigt werden";
$l_s_secfighterdegrade = "Sektor-Jäger-Verfall-Rate";
$l_s_planetinterest    = "Planetarische Zinsrate";
$l_s_spiesperplanet    = "Maximale Anzahl von Spionen pro Planet ";
$l_s_spysuccessfactor  = "Spion Erfolgsfaktor";
$l_s_spykillfactor     = "Spion Tötungsfaktor";
$l_s_colsperfighter    = "Kolonisten müssen jede Runde 1 Jäger produzieren";
$l_s_colspertorp       = "Kolonisten müssen jede Runde 1 Torpedo produzieren";
$l_s_colsperore        = "Kolonisten müssen jede Runde 1 Erz produzieren";
$l_s_colsperorganics   = "Kolonisten müssen jede Runde 1 Einheit organischen Materials produzieren";
$l_s_colspergoods      = "Kolonisten müssen jede Runde 1 Güter produzieren";
$l_s_colsperenergy     = "Kolonisten müssen jede Runde 1 Energie produzieren";
$l_s_colsper      = "Kolonisten müssen jede Runde 1 [commodity] produzieren";

$l_s_gameschedsettings = "Spielplaner-Einstellungen";
$l_s_schedtype         = "Typ des Spielplaners";
$l_s_cronbased         = "Cron-basiert";
$l_s_playertriggered   = "Spieler impulsgesteuert";
$l_s_minutes           = " Minuten";
$l_s_ticksupdate       = "Ticks geschehen alle ";
$l_s_turnsupdate       = "Turns geschen alle ";
$l_s_npcupdate       = "Die Allianz wird spielen ";
$l_s_igbturnsupdate    = "Zinsen auf igb-Konten werden verfallen ";
$l_s_newsupdate        = "Nachrichten werden generiert ";
$l_s_planetupdate      = "Planeten werden produzieren ";
$l_s_spyupdate         = "Spione werden handeln";
$l_s_portsupdate       = "Ports werden regeneriert";
$l_s_towupdate         = "Schiffe werden vom föd Sektor geschleppt";
$l_s_scoreupdate       = "Rankings werden neu generiert";
$l_s_secdefdegrupdate  = "Sektor-Verteidigung wird fallen";
$l_s_apocalypseupdate  = "Die planetarische Apokalypse wird auftreten";
$l_s_release_version   = "Spiel-Ausgabe Version";
$l_s_time_since_reset  = "vergangene Zeit seit letztem Reset";
$l_s_independence   = "Planetarische Unabhängigkeit";
$l_s_dignitaryupdate   = "Dignitaries werden handlen";

$l_s_turnsupdate   = "jede Runde";
?>
