<?php
// New News Items

$l_news_planets		 = " Planeten";
$l_news_cols		 = " Millionen Kolonisten";
$l_news_p_headline 	 = "[player]'s Empire hat nun [total] Planeten";
$l_news_c_headline 	 = "[player]'s Empire hat nun [total] Millionen Kolonisten";
$l_news_p_textXX = "Der Bund hat Warnhinweise in Bezug auf das Reich der ausgegebenen [name]. [name] hat die Kontrolle über [total] Planeten und sollten als sehr gefährlich sein. Alle Sektoren sollten Sektor Verteidigung zu erhöhen sofort.";
$l_news_c_textXX = "Das Reich der [name] erlebt massive Überbelegung auf allen Planeten mit über [total] Millionen Kolonisten. Nahrungsmittelknappheit kann Unruhe. Alle Sektoren sollten möglichst aggressiven Handlungen durch [name] in der Zukunft bewusst.";

$l_created_universe             = "Universum erstellt";
$l_created_universe_full        = "Wissenschaftler, die den Beginn des Universums erforschen haben einstimmig entschieden, das heute der wahrscheinlichste Tag ist, an dem die Erstellung eines neuen Universums stattfinden wird";

$l_news_p_text5		 = "Das wachsende Imperium von [name] hat nun fünf Planeten. Die FNN wird seine weiteren Handlungen weiter für Sie im Auge behalten!";
$l_news_p_text10	 = "Das wachsende Imperium von [name] kontroliert nun stolze zehn Planeten. Berichte der FNN sagen, dass ein weiteres Wachstum von [name] zu einem Krieg führen könnte!";
$l_news_p_text25	 = "Das riesige Imperium von [name] hat bereits 25 Planeten kolonisiert. In einem Interview bestätigt [name], dass er in erwägung zieht, ein Wachstum für die Zukunft etwas zu verlangsamen!";
$l_news_p_text50	 = "Das enorm gigantische Imperium von [name], dass durch 50 Planeten in der ganzen Galaxy representiert wird hat eine bedrohliche Macht erreicht. Einer der Reporter von FNN hat herausgefunden, dass [name] sein Schiff aufrüstet und einen großen Krieg plant. In einem Interview mit [name] kündigte er an, dies Geschehe nur für die Verteidigung!";
$l_news_c_text25	 = "Das wachsende Imperium von [name] besitzt nun 25 Millionen Kolonisten. Die FNN wird seine weiteren Handlungen weiter für Sie im Auge behalten, aber es ist höchst wahrscheinlich, dass die Geburtenraten explodieren werden!";
$l_news_c_text100	 = "Das ehrgeizige Imperium von [name] hat nun 100 Million Kolonisten. Nach einer Explosion der Geburtenrate scheint es so, als seien [name]'s Kolonien ein guter Platz um eine Familie zu gründen!";
$l_news_c_text500	 = "Das große Imperium von [name] hat nun 500 million Kolonisten. [name] sagte in einem Interview, dass die Kolonisierung in dieser Galaxy erst am Anfang stehe";
$l_news_c_text1000	 = "Das gigantische Imperium von [name] hat eine Milliarden Kolonisten. FNN Reporter haben herausgefunden, dass [name] im Besitz von bizarren Klonmechanismen ist, die es ihm erlauben eine großer Zahl neuer Kolonisten zu erstellen. Mit dieser Zahl an Kolonisten ist die ökonomische Kraft seines Imperiums enorm. FNN hofft, dass [name] sein Geld nicht für die Kreigsführung verwendet";

$l_news_indi_short	 = "FNN munkelt: über [planets] Planeten erklären Ihre Unabhängigkeit.";
$l_news_indi	 = "FNN hat herausgefunden, dass über [planets] Planeten entschieden haben, dass Sie für sich alleine besser beherrscht werden und wurden unabhängig.";

$l_news_nova_short	 = "FNN Bericht: [name] hat eine Nova Bombe benutzt.";
$l_news_nova	 = "FNN's brandheise Neuigkeiten: Der Spieler [name] hat die gefürchtete Nova Bombe [total] Mal benutzt um einen Planeten und alle Schiffe darauf zu zerstören.";
$l_news_nova_m_short	 = "FNN Bericht: [name] hat eine Nova Bombe benutzt. Sein Ziel wurde aber verfehlt.";
$l_news_nova_m	 = "FNN's brandheise Neuigkeiten: Der Spieler [name] hat die gefürchtete Nova Bomb [total] Mal benutzt un versucht einen Planeten zu zerstören.  Die Nova Bombe explodierte ausserhalb der Atmosphere und verursachte erhebliche infrastrukturelle Schäden.";

$l_news_bounty	 = "FNN Report: [name] setzt eine Prämie von [amount] auf [name2] aus.";

$l_news_attackerpod_p_short	 = "FNN Bericht: [name]'s Schiff wurde zerstört.";
$l_news_attackerpod_P	 = "[name]'s wurde bei einem Angriff auf einen Planeten zerstört. Glücklicherweise hatte [name] eine Rettungskapsel und überlebte.";

$l_news_attackerdie_p_short	 = "FNN Bericht: [name] wurde getötet!";
$l_news_attackerdie_p	 = "[name]'s Schiff wurde bei einem Angriff auf einen Planeten zerstört. Sie sind umgekommen, weil Sie es versäumt hatten eine Rettungskapsel zu kaufen..";

$l_news_destroyed_p_short	 = "FNN Bericht: [name] hat einen Planeten angegriffen und vernichtet!";
$l_news_destroyed_p	 = "[name] hat [total] Planeten von [owner] angegriffen und. Die Bevölkerung jedes Planeten zerstörten ihn, um die Einahme des Planeten zu verhindern!";

$l_news_defeated_p_short	 = "FNN Bericht: [name] attackiert und besiegte einen Planeten!";
$l_news_defeated_p	 = "[name] attackierte [total] Planeten von [owner] und besiegte die planetarische Verteidigung!";

$l_news_notdefeated_p_short	 = "FNN Bericht: [name] hat einen Planeten angegriffen und verloren!";
$l_news_notdefeated_p	 = "[name] hat [total] Planeten von [owner] attackiert und die planetarische Verteidigung hielt gegen die unbarmherzigen Angriffe stand!";

$l_news_targetepod_short	 = "FNN Bericht: [name] attackiert [owner] und gewinnt!";
$l_news_targetepod	 = "[name] attackiert [owner]'s Schiff und zerstörte es restlos. Glücklicherweise hatte [owner] eine eingebaute Rettungskapsel und überlebte das ganze.";

$l_news_targetdies_short	 = "FNN Bericht: [name] attackiert [owner] und tötet ihn!";
$l_news_targetdies	 = "[name] attackiert [owner]'s Schiff und zerstörte es restlos. Schlimmerweise hatte [owner] keine Rettungskapsel und Sie wurden vaporisiert.";

$l_news_fedcolbounty_short = "FNN Bericht: Der Bund greift bei [name]!";
$l_news_fedcolbounty = "Der Verband hat heute auf der berüchtigten Piraten-Raum nach unten geknackt [name]! [name], die routinemäßig verletzt Raum mehrere Verträge, wurde kurz von der Föderation Schlachtkreuzer, die verhängt [amount] Kredite im Umfang von Schäden am Schiff der Piraten. Föderation Beamten versprechen weitere derartige Aktionen in der Zukunft!";

$l_news_alliancecolbounty_short = "FNN Bericht: Die Allianz greift bei [name]!";
$l_news_alliancecolbounty = "Die Allianz hat heute auf der berüchtigten Piraten-Raum nach unten geknackt [name]! [name], die routinemäßig verletzt Raum mehrere Verträge, wurde kurz von der Allianz, die verhängt [amount] Kredite im Umfang von Schäden am Schiff der Piraten beteiligt. Alliance Beamten versprechen weitere derartige Aktionen in der Zukunft!";

$l_news_fedcol_pbounty_short = "FNN Bericht: Die Föderation jagt [name]!";
$l_news_fedcol_pbounty = "Der Verband hat heute auf der berüchtigten Piraten-Raum nach unten geknackt [name]! [name], die routinemäßig verletzt Raum mehrere Verträge, wurde kurz von der Föderation Schlachtkreuzer, die den Planeten beschlagnahmt [planetname] Wert von [amount] Credits im Sektor [sector] engagiert. Föderation Beamten versprechen weitere derartige Aktionen in der Zukunft!";

$l_news_alliancecol_pbounty_short = "FNN Bericht: Die Allianz jagt [name]!";
$l_news_alliancecol_pbounty = "Die Allianz hat heute auf der berüchtigten Piraten-Raum nach unten geknackt [name]! [name], die routinemäßig verletzt Raum mehrere Verträge, wurde kurz von der Allianz, die den Planeten beschlagnahmt [planetname] Wert von [amount] Credits im Sektor [sector] engagiert. Alliance Beamten versprechen weitere derartige Aktionen in der Zukunft!";

$l_news_fedcol_sbounty_short = "FNN Bericht: Die Föderation jagt [name]!";
$l_news_fedcol_sbounty = "Der Verband hat heute auf der berüchtigten Piraten-Raum nach unten geknackt [name]! [name], die routinemäßig verletzt Raum mehrere Verträge, wurde kurz von der Föderation Schlachtkreuzer, die ein Schiff ([shiptype]) im Wert von [cost] im Bereich [sector]. Föderation Beamten versprechen weitere derartige Aktionen in der Zukunft!";

$l_news_alliancecol_sbounty_short = "FNN Bericht: Die Allianz jagt [name]!";
$l_news_alliancecol_sbounty = "Die Allianz hat heute auf der berüchtigten Piraten-Raum nach unten geknackt [name]! [name], die routinemäßig verletzt Raum mehrere Verträge, wurde kurz von der Allianz, das Schiff beschlagnahmt [shiptype] Wert von [cost] im Bereich [sector] engagiert. Alliance Beamten versprechen weitere derartige Aktionen in der Zukunft!";

$l_killheadline		 ="[target] wurde bei einem Unfall getötet";
$l_news_killed 		 = "[target] wurden heute bei einem tragischen Unglück getötet. Wie heroisch - Der Kapitän [target] war der letzte an Bord seines Schiffes, als er bemerkte, dass es keine Rettungskapsel gibt.";

$l_killSDheadline = "[target] wurde von Sector Defenses getötet.";
$l_news_killedSD = "[target] wurde von einer überwältigenden Zahl der Branche Defenses im Besitz von [killer]! Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killplanetheadline = "[target] Angriff getötet wurde ein Planet.";
$l_news_killedplanet = "[target] wurde getötet, als Angriff auf einen Planeten im Besitz von [killer] heute. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killshipheadline = "[target] wurde getötet Schiff zu bekämpfen.";
$l_news_killedship = "[target] wurde im Schiff getötet zu bekämpfen mit Schiff [killer] heute. Der Kapitän offenbar vergessen haben, das Schiff mit einer Rettungskapsel auszustatten.";

$l_killsuicideheadline = "[target] Selbstmord begangen.";
$l_news_killedsuicide = "[target] Selbstmord beging heute. Sie nahmen den Weg aus Feiglinge, weil sie die Fähigkeit oder den Mut, sich dem Druck der beherrschenden ihr eigenes Schiff fehlte.";

$l_killsofaheadline = "[target] getötet wurde Sofa Angriff eines Planeten.";
$l_news_killedsofa = "[target] wurde getötet, während Sofa ein Planet im Besitz von [killer] heute angreifen. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killnovaheadline = "[target] wurde im Rahmen eines nova Angriff getötet.";
$l_news_killednova = "[target] wurde getötet [killer] bei einem Bombenanschlag nova heute. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killnovabackfireheadline = "[target] wurde von einer nova nach hinten losgehen getötet.";
$l_news_killednovabackfire = "[target] wurde getötet, als ihre nova Bombe heute nach hinten losging. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killsectormissileheadline = "[target] wurde von einem Sektor Raketen getötet.";
$l_news_killedsectormissile = "[target] wurde getötet, als ein Sektor Missile von [killer] ihre Schilde beeinflusst. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killhunterprobeheadline = "[target] wurde aus einer Probe Hunter getötet.";
$l_news_killedhunterprobe = "[target] wurde getötet, als ein Jäger Probe von [killer] ihre Schilde beeinflusst. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

$l_killtrapprobeheadline = "[target] wurde aus einer Probe Sentry Trap getötet.";
$l_news_killedtrapprobe = "[target] wurde getötet, als ein Sentry Trap Probe von [killer] ihre Schilde beeinflusst. Leider war das Schiff nicht mit einer Rettungskapsel ausgerüstet.";

//-------------------

$l_killpodheadline = "[target] &#39;s Schiff war in einen Unfall zerstört";
$l_news_killedpod = "[target] &#39;s Schiff war bei einem tragischen Unfall zerstört heute. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killSDpodheadline = "[target] &#39;s Schiff wurde durch Sector Defenses zerstört.";
$l_news_killedSDpod = "[target] &#39;s Schiff wurde von einer überwältigenden Zahl der Branche Defenses im Besitz von [killer]! Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killplanetpodheadline = "[target] &#39;s Schiff zerstört wurde Angriff auf einen Planeten.";
$l_news_killedplanetpod = "[target] &#39;s Schiff wurde zerstört, während Angriff auf einen Planeten im Besitz von [killer] heute. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killshippodheadline = "[target] &#39;s Schiff war in der Schiffs-Bekämpfung zerstört.";
$l_news_killedshippod = "[target] &#39;s Schiff in Schiff zerstört zu bekämpfen mit Schiff [killer] heute. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killsofapodheadline = "[target] &#39;s Schiff wurde zerstört, während ein Sofa Planeten angreifen.";
$l_news_killedsofapod = "[target] &#39;s Schiff wurde zerstört, während Sofa ein Planet im Besitz von [killer] heute angreifen. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killnovapodheadline = "[target] &#39;s Schiff war während einer nova Angriff zerstört.";
$l_news_killednovapod = "[target] &#39;s Schiff wurde von zerstörten [killer] bei einem Bombenanschlag nova heute. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killnovabackfirepodheadline = "[target] &#39;s Schiff wurde von einer nova nach hinten losgehen zerstört.";
$l_news_killednovabackfirepod = "[target] &#39;s Schiff wurde zerstört, als die Bombe nova heute nach hinten losging. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killsectormissilepodheadline = "[target] &#39;s Schiff wurde von einem Sektor Missile zerstört.";
$l_news_killedsectormissilepod = "[target] &#39;s Schiff wurde zerstört, als ein Sektor Missile von [killer] ihre Schilde beeinflusst. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killhunterprobepodheadline = "[target] &#39;s Schiff wurde von einem Jäger Probe zerstört.";
$l_news_killedhunterprobepod = "[target] &#39;s Schiff wurde zerstört, als ein Jäger Probe von [killer] ihre Schilde beeinflusst. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

$l_killtrapprobepodheadline = "[target] &#39;s Schiff wurde von einer Sentry Trap Probe zerstört.";
$l_news_killedtrapprobepod = "[target] &#39;s Schiff wurde zerstört, als ein Sentry Trap Probe von [killer] ihre Schilde beeinflusst. Eine Escape Pod Transponder wurde von Bund Search and Rescue erkannt.";

// --------------------------

$l_news_promotedheadline = "[name] wurde gefördert, um [rank]";
$l_news_promoted = "Der Verband freut sich, die Förderung von [name] in den Rang eines [rank].";

$l_news_demotedheadline = "[name] wurde degradiert zu [rank]";
$l_news_demoted = "Der Verband bedauert die Herabstufung von [name] in den Rang eines [rank].";

$l_news_namechangedheadline = "[oldname] geändert Namen [newname]";
$l_news_namechanged = "[oldname] angewandt auf den Bund Review Board, ihren Namen zu ändern [newname]. Der Bund hat den Namen ändern gewährt. Von diesem Tag an [oldname] wird jetzt als bekannt sein [newname]. Alle Schiffe und Planeten sollten ihre Unterlagen umgehend zu aktualisieren.";

$l_news_found_planets_short = "Föderation Umfrage: [found_planets] neue Planeten befindet.";
$l_news_found_planets = "Föderation Survey Scouts haben sich [found_planets] neuen Planeten im kürzlich entdeckten Sektoren.";

$l_news_new_ports_short = "Föderation Umfrage: [new_ports] neue Häfen gebaut.";
$l_news_new_ports = "Föderation Ingenieure haben gebaut [new_ports] neue Häfen in Bereiche vor kurzem entdeckt.";

$l_news_addedsectors_short = "Föderation Umfrage: [addedsectors] Sektoren entdeckt.";
$l_news_addedsectors = "Föderation Survey Scouts entdeckt haben [addedsectors] neuen Sektoren. Vorsicht ist geboten.";

$l_news_artifactheadline = "[playername] abgeschlossen [artifact]";
$l_news_artifact = "[playername] hat alle Teile des [artifact] und verfügt über alle von der Macht es bieten kann.";

$l_news_artifactfoundheadline = "[playername] gefunden [artifact] Stück";
$l_news_artifactfound = "[playername] ist eines der Stücke des [artifact] und Bedürfnisse [pieces] mehr [piece].";

?>
