<?php
$l_login_title = "Anmeldung";
$l_login_pw			= "Passwort:";
$l_login_chooseres		= "Bildschirmauflösung:";
$l_login_newp			= "Falls Sie ein neuer Spieler sind, dann klicken Sie <A HREF=\"new_player.php\">hier</A>.";
$l_login_prbs			= "Probleme?";
$l_login_emailus		= "E-mail uns";
$l_login_forgot_pw		= "Passwort vergessen? Geben Sie es blank ein und drücken Sie login";
$l_login_settings 		= "Spieleinstellungen";
$l_login_change			= "Änderungen";
$l_login_title2			= "Main Login für AATraders";
$l_login_reset1			= "Kein Reset eingeplant";
$l_login_reset2			= "geplanter Reset: ";
$l_login_reset3			= "gepl. Reset: ";
$l_login_notice			= "wichtige Notiz:";
$l_login_endadminnews			= "Ende der Admin News";
$l_login_tourney_signup = "Turnier Anmeldungen Enabled";

$l_login_profile_only = "Nur anzeigen";
$l_login_newclosed_message = "Neue Anmeldungen geschlossen";
$l_login_tourneymode = "Turnier läuft";
$l_login_tourneystarts = "Starts:";
?>
