<?php
$l_footer_one_player_on	= "Es ist 1 Spieler online.";
$l_footer_players_on_1	= "Es sind";
$l_footer_players_on_2	= "Spieler online: ";
$l_footer_until_update	= "Sekunden bis zum nächsten Update.";
$l_footer_no_players_on = "Es sind keine Spieler online.";

$l_footer_news = "Lokale FNN News";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = " für Hilfe über diese Seite.";
$l_footer_click = "klick";

$l_footer_open_slots = "Maximal Online:";
$l_footer_onlinereset = "Player Online Time Reset in";
$l_footer_onlinecountdown = "Player Online Time Countdown:";
?>
