<?php
$l_opt_title             = "Einstellungen";
$l_opt_chpass            = "Passwort ändern";
$l_opt_curpass           = "Aktuelles Passwort:";
$l_opt_newpass           = "Neues Password:";
$l_opt_newpagain         = "Neues Passwort (nochmal):";
$l_opt_userint           = "Benutzer-Oberfläche";
$l_opt_usenew            = "Neues Layout benutzen?";
$l_opt_lang              = "Sprache";
$l_opt_template = "Template";
$l_opt_select            = "Wählen Sie aus:";
$l_opt_enabled           = "Aktiviert";
$l_opt_save              = "Speichern";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname              = "Schiffsname:";
$l_opt_mapwidth              = "Größe der lokalen und galaktischen Karte:";
$l_opt_profiletitle = "Profil";
$l_opt_profile = "Falls Sie ein Spieler-Profil auf <a href='http://www.aatraders.com'>www.aatraders.com</a> haben, und Sie das Spiel mit diesem Profil registieren wollen, dann klicken Sie bitte ";
$l_opt_profilereg = "Auf dem Profil-Server regisitriert";
$l_opt_profilerereg = "Neuregistrierung eines Spieler-Profils für dieses Spiels auf <a href='http://www.aatraders.com'>www.aatraders.com</a>";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Wenn Sie sich registrieren Sie Ihren Player auf einem anderen Server der Vorlage, Shoutbox und Neuigkeiten obigen Einstellungen werden auf dem Server verwendet werden.";
$l_opt_showshoutbox = "Show Shoutbox:";
$l_opt_shownewscrawl = "Show News Crawl:";
$l_opt_playername = "Player Name:";
$l_opt_playernamecost = "Föderation Name Change Fee: [amount] credits";
?>
