<?php
$l_sm_title = "Sector Missile Launch";
$l_sm_invalid = "Es gibt nicht eine Kette Link zwischen diesem Sektor und die Ziel-Sektor.";
$l_sm_notarg = "Ziel nicht in diesem Sektor.";
$l_sm_noturn = "Sie benötigen mindestens eine Runde, um Feuer für Ihre Branche Missile.";
$l_sm_nosectormissile = "Sie sind nicht die Durchführung einer Branche Missiles.";
$l_sm_noscan = "Sensoren kann nicht ein Update auf Kurs!";
$l_sm_flee = "Target aus manövriert der Branche Missile!";
$l_sm_ewd = "Ziel engagiert Notfall Warp-Gerät erkannt, wenn es der Branche Missile!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] greift Ihr Schiff mit einem Sektor Missile!";
$l_sm_sectormissilefail = "Der Sektor Missile Fehlfunktion, wenn es die feindlichen Schiffe Schild hit!";
$l_sm_sectormissilefail2 = "Der Sektor Missile Fehlfunktion, wenn es die feindlichen Schiffe Rüstung hit!";
$l_sm_shieldhit = "[target] &#39;s Schilde sind für HIT [amount] beschädigen!";
$l_sm_shieldsdown = "[target] &#39;s Schilde sind down!";
$l_sm_armorhit = "[target] &#39;s Rüstung ist für HIT [amount] beschädigen!";
$l_sm_armorbreached = "[target] &#39;s Rüstung durchbrochen!";
$l_sm_targetnoenergy = "Das Schiff hat noch keine Energie! Sector Missile nicht!";
$l_sm_attacking = "Offensiv [target] an Bord der [shipname]";
$l_sm_targetok = "Sie haben nicht destory [name] &#39;s Schiff.";
$l_sm_lost = "[target] verloren [armor] Rüstung Punkte und [energy] Energie-Einheiten.";
$l_sm_destroyed = "[target] &#39;s Schiff zerstört worden ist.";
$l_sm_escapepod = "Eine Rettungskapsel wurde gestartet!";
?>
