<?php
$l_sf_attacking          = "Sektor-Verteidigungs-Jäger greifen Sie an!<BR>";
$l_sf_destfight          = "Ihre Strahlen haben [lost] Jäger zerstört<BR>";
$l_sf_destfightb         = "Ihre Strahlen haben [lost] Jäger zerstört<BR>";
$l_sf_torphit            = "getroffene Torpedos:";
$l_sf_destfightt         = "Ihre Torpedos haben [lost] Jäger zerstört<BR>";
$l_sf_fighthit           = "Angriff der Jäger auf:";
$l_sf_destfightall       = "Sie haben alle Jäger zerstört.<BR>";
$l_sf_destfightt2        = "Sie haben [lost] Jäger zerstört.<BR>";
$l_sf_lostfight          = "Sie haben alle Jäger zerstört.<BR>";
$l_sf_lostfight2         = "Sie haben [lost] Jäger verloren.<BR>";
$l_sf_armorbreach        = "Ihre Ausrüstung wurde zerstört!<BR>";
$l_sf_armorbreach2       = "Ihre Ausrüstung wurde für [lost] beschädigt.<BR>";
$l_sf_sendlog            = "[player] hat [lost] Sektor-Verteidigungs-Jäger im Sektor [sector] zerstört.";
$l_sf_lreport            = "Sie haben [armor] Ausrüstungs-Punkte, [fighters] Jäger verloren, und [torps] Torpedoes abgefeuert.<BR><BR>";
$l_sf_shipdestroyed      = "Ihr Schiff wurde zerstört!<BR><BR>";
$l_sf_sendlog2           = "Sektor-Verteidigungs-Jäger hat [player] im Sektor [sector] zerstört.";
$l_sf_escape             = "Glücklicherweise haben Sie eine Rettungskapsel!<BR><BR>";

$l_sf_fnoattack		 = " sendet keine Jäger um Ihre Jäger anzugreifen.";
$l_sf_fnoattackt	 = " sendet keine Jäger um Ihre Torpedos anzugreifen.";
$l_sf_fnoattacka	 = " sendet keine Jäger um Ihre Ausrüstung anzugreifen.";
$l_sf_flaunchmalf1		 = "Ihre Jäger-Abschuss-Rampe hat versagt.";
$l_sf_flaunchmalf2		 = "Sie waren nur in der Lage ";
$l_sf_flaunchmalf3		 = " Prozent Ihrer Jäger zu starten.";
$l_sf_fightertorpexg		 = "Jäger- und Torpedo/Minen-Schlacht";
$l_sf_torpfighterexg		 = "Schiffstorpedo- und Sektorjäger-Schlacht";
$l_sf_fighterarmorexg		 = "Sektor- und Shiffsausrüstungs-Kampf";
$l_sf_tlaunchmalf1		 = "Ihre Torpedo-Abschuss-Vorrichtung hat versagt.";
$l_sf_tlaunchmalf2		 = "Sie konnten nur ";
$l_sf_tlaunchmalf3		 = " Prozent Ihrer Torpedoes abfeuern.";
$l_sf_bountysd = "Sie haben einen Sektor mit einem Planeten, der Ihnen eine Prämie würde angegriffen, wenn Sie die Planeten angegriffen. Der Verband verfügt über eine automatische Selbstzerstörung auf allen Ihren Kämpfer und Torpedos aktiviert. Greifen Sie nicht den Sektor Verteidigung in diesem Bereich wieder. Sie wurden gewarnt!";
?>
