<?php
$l_artifact_title = "Abrufen Artefakt";
$l_artifact_list_title = "Liste der erworbenen Artefakte";
$l_artifact_noscan = "Ihr Scanner nicht finden konnten, das Artefakt.";
$l_artifact_noturn = "Sie haben nicht genug zu holen sich dieses Artefakt.";
$l_artifact_classname = "Artefakt Name";
$l_artifact_description = "Artefakt Beschreibung";
$l_artifact_imagename = "Artefakt Image";
$l_artifact_incomplete = "Artefakt Pieces";
$l_artifact_process = "Verwenden Sie die Fertiggestellt Artefakt";

?>
