<?php
$l_news_planets		 = " Planeten";
$l_news_cols		 = " Millionen Kolonisten";
$l_news_p_headline 	 = "[player]'s Imperium hat nun ";

$l_killheadline		 =" wurde bei einem Unfall betötet";
$l_news_killed 		 = "[name] wurde heute bei einem tragischen Unglück getötet. Wie heroisch - Kaptiän [name] war das letzte Mitglied der Mannschaft an Bord seines Schiffes, als er bemerkte, dass er keine Rettungskapsel hat!";
$l_news_p_text5		 = "Das wachsende Imperium von [name] hat nun fünf Planeten. Die FNN wird seine weiteren Handlungen weiter für Sie im Auge behalten!";
$l_news_p_text10	 = "Das wachsende Imperium von [name] kontroliert nun stolze zehn Planeten. Berichte der FNN sagen, dass ein weiteres Wachstum von [name] zu einem Krieg führen könnte!";
$l_news_p_text25	 = "Das riesige Imperium von [name] hat bereits 25 Planeten kolonisiert. In einem Interview bestätigt [name], dass er in erwägung zieht, ein Wachstum für die Zukunft etwas zu verlangsamen!";
$l_news_p_text50	 = "Das enorm gigantische Imperium von [name], dass durch 50 Planeten in der ganzen Galaxy representiert wird hat eine bedrohliche Macht erreicht. Einer der Reporter von FNN hat herausgefunden, dass [name] sein Schiff aufrüstet und einen großen Krieg plant. In einem Interview mit [name] kündigte er an, dies Geschehe nur für die Verteidigung!";
$l_news_c_text25	 = "Das wachsende Imperium von [name] besitzt nun 25 Millionen Kolonisten. Die FNN wird seine weiteren Handlungen weiter für Sie im Auge behalten, aber es ist höchst wahrscheinlich, dass die Geburtenraten explodieren werden!";
$l_news_c_text100	 = "Das ehrgeizige Imperium von [name] hat nun 100 Million Kolonisten. Nach einer Explosion der Geburtenrate scheint es so, als seien [name]'s Kolonien ein guter Platz um eine Familie zu gründen!";
$l_news_c_text500	 = "Das große Imperium von [name] hat nun 500 million Kolonisten. [name] sagte in einem Interview, dass die Kolonisierung in dieser Galaxy erst am Anfang stehe";
$l_news_c_text1000	 = "Das gigantische Imperium von [name] hat eine Milliarden Kolonisten. FNN Reporter haben herausgefunden, dass [name] im Besitz von bizarren Klonmechanismen ist, die es ihm erlauben eine großer Zahl neuer Kolonisten zu erstellen. Mit dieser Zahl an Kolonisten ist die ökonomische Kraft seines Imperiums enorm. FNN hofft, dass [name] sein Geld nicht für die Kreigsführung verwendet";

$l_news_indi_short	 = "FNN munkelt: über [planets] Planeten erklären Ihre Unabhängigkeit.";
$l_news_indi	 = "FNN hat herausgefunden, dass über [planets] Planeten entschieden haben, dass Sie für sich alleine besser beherrscht werden und wurden unabhängig.";

$l_news_nova_short	 = "FNN Bericht: [name] hat eine Nova Bombe benutzt.";
$l_news_nova	 = "FNN's brandheise Neuigkeiten: Der Spieler [name] hat die gefürchtete Nova Bombe [total] Mal benutzt um einen Planeten und alle Schiffe darauf zu zerstören.";
$l_news_nova_m_short	 = "FNN Bericht: [name] hat eine Nova Bombe benutzt. Sein Ziel wurde aber verfehlt.";
$l_news_nova_m	 = "FNN's brandheise Neuigkeiten: Der Spieler [name] hat die gefürchtete Nova Bomb [total] Mal benutzt un versucht einen Planeten zu zerstören.  Die Nova Bombe explodierte ausserhalb der Atmosphere und verursachte erhebliche infrastrukturelle Schäden.";

$l_news_bounty	 = "FNN Report: [name] setzt eine Prämie von [amount] auf [name2] aus.";

$l_news_attackerpod_p_short	 = "FNN Bericht: [name]'s Schiff wurde zerstört.";
$l_news_attackerpod_P	 = "[name]'s wurde bei einem Angriff auf einen Planeten zerstört. Glücklicherweise hatte [name] eine Rettungskapsel und überlebte.";

$l_news_attackerdie_p_short	 = "FNN Bericht: [name] wurde getötet";
$l_news_attackerdie_p	 = "[name]'s Schiff wurde bei einem Angriff auf einen Planeten zerstört. Sie sind umgekommen, weil Sie es versäumt hatten eine Rettungskapsel zu kaufen..";

$l_news_destroyed_p_short	 = "FNN Bericht: [name] hat einen Planeten angegriffen und vernichtet!";
$l_news_destroyed_p	 = "[name] hat [total] Planeten von [owner] angegriffen und. Die Bevölkerung jedes Planeten zerstörten ihn, um die Einahme des Planeten zu verhindern!";

$l_news_defeated_p_short	 = "FNN Bericht: [name] attackiert und besiegte einen Planeten!";
$l_news_defeated_p	 = "[name] attackierte [total] Planeten von [owner] und besiegte die planetarische Verteidigung!";

$l_news_notdefeated_p_short	 = "FNN Bericht: [name] hat einen Planeten angegriffen und verloren!";
$l_news_notdefeated_p	 = "[name] hat [total] Planeten von [owner] attackiert und die planetarische Verteidigung hielt gegen die unbarmherzigen Angriffe stand!";

$l_news_targetepod_short	 = "FNN Bericht: [name] attackiert [owner] und gewinnt!";
$l_news_targetepod	 = "[name] attackiert [owner]'s Schiff und zerstörte es restlos. Glücklicherweise hatte [owner] eine eingebaute Rettungskapsel und überlebte das ganze.";

$l_news_targetdies_short	 = "FNN Bericht: [name] attackiert [owner] und tötet ihn!";
$l_news_targetdies	 = "[name] attackiert [owner]'s Schiff und zerstörte es restlos. Schlimmerweise hatte [owner] keine Rettungskapsel und Sie wurden vaporisiert.";

?>
