<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Sonden Levels";
$l_probe_engine = "Antrieb";
$l_probe_sensors = "Sensoren";
$l_probe_cloak = "Tarnung";
$l_probe_title		 = "Sondne-Menü";
$l_probe_none		 = "Sie sind nicht im selben Sektor wie diese Sonde. Sie können nicht mit ihr interagieren.";

$l_probe_named		 = "Willkommen bei der Sonde Nummer [probename] von [name] im Sektor [sector].";
$l_probe_orders	 = "[orders] Sonde in den Weltraum schicken";
$l_probe_orders_link= "Suchprogramm";
$l_probe_upgrade	 = "[upgrade] Sensoren/Antrieb/Tarnung aufrüsten";
$l_probe_upgrade_link	 = "Aufrüsten";
$l_probe_pickup	 = "[pickup] Sonde für spätere Benutzung wieder aufnehmen";
$l_probe_pickup_link	 = "Aufnehmen";
$l_probe_update = "Aktualisieren";

$l_probe_att_link	 = "Attacke";
$l_probe_att		 = "[attack] auf Sonde";
$l_probe_att_sure	 = "Sind Sie SICHER...";
$l_probe_scn_link	 = "Scannen";
$l_probe_scn		 = "Sonde [scan]";

$l_probe_unknown		 = "Unbekannt";
$l_plant_scn_turn	 = "Sie benötigen mindestens einen Turn um eine Sonde zu scannen.";
$l_probe_noscan	 = "Die Sensoren können Ihr Ziel nicht fixieren!";
$l_probe_logscanA	 = "[name] hat versucht eine Ihrer Sensoren im Sektor [sector] zu scannen, scheiterte aber.";
$l_probe_logscanB	 = "Eine Ihrer Sonden im Sektor [sector] wurde von [name] gescannt.";
$l_probe_scn_report	 = "Scan-Ergebnisse von [name] (Besitzer: [owner])";

$l_probe_caplog	 = "Ihre Sonde '[probename]' im Sektor [sector] wurde von [name] eingenommen.";
$l_probe_scan  = "Die Sonde hat den Sektor [sector] gescannt und hat folgendes gefunden:";
$l_probe_destroyprobe  = "Sonde zerstören";
$l_probe_destroyed= "Sonde wurde zerstört!!";
$l_probe_warning 	 = "Wenn Sie dies tun, dann wird die Sonde komplett zerstört";
$l_probe_confirm 	 = "Wollen Sie die Sonde wirklich zerstören?";
$l_gns_turn ="Sie haben nicht genügend Turns um die Sonde zu zerstören";
$l_probe_type="Sonden-Typ";
$l_probe_type0="Stationäre Sonde";
$l_probe_type1="Wachposten";
$l_probe_type2="Warp-Sonde";
$l_probe_type3="Realspace-Sonde";
$l_probe_type4="sequenzielle Realspace-Sonde";
$l_probe_target="Ziel-Sector";
$l_probe_ordered="Die Sonde wurde programmiert und wird Ihre Suche beginnen.";
$l_probe_order2="Die Sone ist vom Typ: [type] und wird zum Ziel-Sektor [target] fliegen";
$l_probe_pickedup="Die Sonde wurde aufgenommen und eingelagert";
$l_probe_title="Sonden-Menü";
$l_probe_messages = "um zu sehen, was Ihre Spione entdeckt haben.";

$l_probe_defaulttitle1 = "Aktive Sonden";
$l_probe_defaulttitle2 = "Sonden, die Sie aufgenommen haben";
$l_probe_defaulttitle3 = "Sonden auf Ihrem Planeten";
$l_probe_defaulttitle4 = "Sonden auf Ihrem Schiff";
$l_probe_linkback="um zum Sonden-Menü zu gehen.";
$l_probe_no1 = "Sie haben keine aktiven Sonden.";
$l_probe_no2 = "Sie haben keine Sonden eingelagert.";
$l_probe_no3 = "Sie haben keine Sonden auf Ihrem Planeten.";
$l_probe_no4 = "Sie haben keine Sonden auf Ihrem Schiff.";
$l_probe_noprobeatall = "Sie haben keine Sonden.";
$l_probe_notknown = "Unbekannt";
$l_probe_launch="Fallen lassen";
$l_probe_detect="Entdeckt";
$l_probe_codenumber = "Code";
$l_probe_job = "Job";
$l_probe_percent = "Prozent";
$l_probe_move = "Bewegung";
$l_probe_view= "Ansehen";
$l_probe_action = "Action";
$l_probe_shipowner = "Schiffs-Eigentümer";
$l_probe_shipname = "Schiffs-Name";
$l_probe_shiptype = "Schiffs-Klasse";
$l_probe_shiplocation = "Schiffs-Ort";
$l_probe_planetowner = "Planeten-Besitzer";
$l_probe_planetname = "Planet";
$l_probe_sector = "aktueller Sektor";
$l_probe_tsector = "Ziel Sektor";
$l_probe_type="Sonden-Typ";
$l_probe_forbid="Sie können in diesem Sektor keine Sonden aussetzten";

$l_probe2_title             = "Starte Weltraum-Sonde";
$l_probe2_turn              = "Sie benötigen mindestens einen Turn, um eine Weltraum-Sonde einzusetzten.";
$l_probe2_onplanet          = "Sie können dieses Gerät nicht einsetzten, solange Sie sich auf der Oberfläche des Planeten befinden.";
$l_probe2_noprobe         = "Sie haben keine Weltraum-Sonden.";
$l_probe2_forbid            = "Eine Sonde in diesem Sektor zu starten ist nicht gestattet.";
$l_probe2_launched           = "Weltraum-Sonde wurde gestartet!";

$l_probe2_warplink = "Warplink";
$l_probe2_player           = "Spieler";
$l_probe2_onboarda           = "an Bord eines";
$l_probe2_classship           = "Schiffs-Klasse";
$l_probe2_traveled           = "ist zu weitergereist zu Sektor";
$l_probe2_fedjammed           = "Die Föderation störtt alle Sensoren-Scanns im Sektor 1.";
$l_probe2_lastseen           = "Letztes Schiff";
$l_probe2_portfound           = "Port gefunden";
$l_probe2_supports           = "unterstützt";
$l_probe2_planets           = "Planeten";
$l_probe2_sectord           = "Sektor-Verteidigung entdeckt";
$l_probe2_mines           = "Minen";
$l_probe2_fighters           = "Jäger";
$l_probe2_ships           = "Schiffe entdeckt";
$l_probe2_ships2           = "Schiff entdeckt";
$l_probe2_noneowned           = "Es wurde keiner Ihrer Planeten entdeckt.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing           = "Es wurde nichts entdeckt";
$l_probe2_nocredits = "Sie haben nicht genug Credits für diese Transaktion. Die Gesamtkosten belaufen sich auf [total] Credits und Sie müssen nur [credits] Credits.";

$l_probe_forbidSG = "Sie können nicht senden Realspace Art Sonde in Sektor Genesis erstellt Sektoren.";
$l_probe_forbidFED = "Sie können nicht senden Sie eine Art Sonde in Realspace Föderation oder Allianz-Sektoren.";
$l_probe_forbidINVALID = "Ihr Ziel-Sektor ist ein Sektor ungültige Namen.";
?>
