<?php
$l_pre_title             = "Ändere Realspace Presets";
$l_pre_exceed            = "Preset [preset] überschreitet das Maximum von [sector_max]. Keine presets gespeichert.<BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Sichern";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] ist eine ungültige Sektor Namen.";
$l_pre_invalidchange = "[sector] ist ein Sektor Genesis Sektor. Ihre alte Preset bleibt unverändert.";
?>
