<?php
$l_readm_title           = "Lese Nachricht";
$l_readm_delete          = "NACHRICHT GELÖSCHT";
$l_readm_nomessage       = "Sie habe keine neuen Nachrichten.";
$l_readm_center          = "Nachrichten Empfangszentrale";
$l_readm_sender          = "Nachrichten Sender";
$l_readm_captn           = "Kapitän von";
$l_readm_del             = "Löschen";
$l_readm_repl            = "Antworten";
$l_readm_return            = "Hier klicken um zum Hauptmenü zurück zu kehren";
$l_readm_title2 = "Mail Reader";
$l_readm_delete            = "Lösche Alle";
$l_readm_subject            = "Betreff";
$l_readm_quote            = "Zitat";
$l_readm_block = "Absender blockieren";
$l_readm_alert            = "System Alarm";
$l_readm_alertbody            = "Shiffscomputer";
?>
