<?php
$l_sn_title          = "Sektor-Notizen für Sektor";
$l_sn_pntitle = "Sektoren mit Personal Notes";
$l_sn_tntitle          = "Sektoren mit Team-Notizen";
$l_sn_psntitle          = "Persönliche Sektor-Notizen";
$l_sn_tsntitle          = "Team-Sektor-Notizen";
$l_sn_editnote          = "Editiere Sektor-Notizen:";
$l_sn_deleteedit          = "Lösche oder ändere:";
$l_sn_addnote          = "Sektor-Notizen hinzufügen:";
$l_sn_list          = "Sektoren mit persönlichen Notizen auflisten";
$l_sn_listts          = "Sektoren mit Team-Notizen auflisten";
$l_sn_addteam          = "Team hinzufügen";
$l_sn_deleteteam          = "team löschen";
$l_sn_delete = "Löschen";
$l_sn_saveteam          = "Team speichern";
$l_sn_deletepersonal          = "persönliche löschen";
$l_sn_addpersonal          = "Hinzufügen persönlicher Notizen";
$l_sn_savepersonal          = "persönliche speichern";
$l_sn_editpersonal          = "persönliche ändern";
$l_sn_editteam          = "Team ändern";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Typ";
$l_sn_hdowner = "Inhaber / Team";
$l_sn_hdplanets = "Planets";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mines";
$l_sn_hdscanfrom = "Vom Scan";
$l_sn_hddetail = "Detail";
$l_sn_hddate = "Datum / Zeit";
$l_sn_hddelete = "Löschen";
$l_sn_hdteam = "Team";
$l_sn_view = "Anzeigen";
$l_sn_no = "Nein";
$l_sn_yes = "Ja";
$l_sn_nonotes = "Kein Sektor Hinweise gefunden";
?>
