<?php
$l_sofa                  = "Sub-Orbitale Jäger-Attacke";
$l_planet_basenoturn	 = "Sie benötigen mindestens einen Turn um eine Basis aufzubauen";
$l_planet_upgrade   ="Aufrüsten";
$l_planet_novamiss   ="Die Nova Bombe hat Ihr Ziel haarscharf verfehlt. Sie hat aber großen Schaden auf dem Planeten angerichtet.";
$l_planet_novaturns   ="Die Nova Bombe benötogt mindestens [turns] Turns für den Abschuss.";
$l_planet_novafed   ="Die Nova Bombe wird in Sektoren der Föderation nicht detonieren.";
$l_planet_nonova   ="Sie haben keine Nova Bombe installiert.";
$l_planet_firenova   ="Nova Bomb feuern";
$l_planet_novaexplode   ="Die Nova Bomb explodierte beim Abschuß und hat massiven Schaden an Ihrem Schiff hinterlassen.";
$l_planet_novaexplode2   ="Die Nova Bomb explodierte beim Abschuß und hat Ihr Schiff zersört.";
$l_planet_noautotrade   ="Auto-Handels-Route für diesen Planeten nicht gesetzt.";
$l_planet_autotrade   ="<font size='1'>Auto-Handel";
$l_planet_autotradetype = "- [source_type] am Port [dest_id] ";
$l_planet_autotradedelete   ="Auto-Handel löschen.";
$l_planet_autotradeadd   ="Auto-Handel erstellen.";
$l_planet_tradedeleted   ="Auto-Handels-Route gelöscht.";
$l_planet_tradeadded   ="Neue Auto-Handels-Route erstellt.";
$l_planet_autotype = "Wählen Sie die Ware, mit der Sie handeln möchten";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Sie müssen ein Handels-Schiff für diesen Planeten kaufen, bevor Sie eine Auto-Handels-Route erstellen können.";
$l_planet_purchasecargo = "Falls Sie ein Handels-Schiff kaufen möchten";
$l_planet_upgradecargo = "Falls Sie Ihr Handels-Schiff aufrüsten möchten";

$l_planet_cargocapacity = "Kapazität: ";
$l_planet_cargoowned = "Sie besitzen bereits ein Handels-Schiff für diesen Planeten.";
$l_planet_cargoshipbuy = "Handels-Schiff kaufen";
$l_planet_cargoshipupgrade = "Handels-Schiff aufrüsten";
$l_planet_cargoatmax = "Ihr Handels-Schiff hat den maximalen Aufrüstungslevel erreicht.";
$l_planet_cargoshipbuyinfo = "Wählen Sie ein Handels-Schiff";
$l_planet_cargoshipupgradeinfo = "Rüsten Sie die Hülle Ihres Handels-Schiffes auf.";
$l_planet_cargoshipbuildinfo = "Bauen Sie Ihr eigenes Handels-Schiff";
$l_planet_tradehelp = "1. Sie können einen Handels-Port für jeden Typ Ware eingeben.<br>2. Sie können nicht mit einem Port handeln, der die selben Waren verkauft.<br>&nbsp;&nbsp;&nbsp;Handle Güter an Güter-Ports, Erz an Erz-Ports.<br>3. Falls Sie bestimmte Waren nicht handeln möchten, geben Sie einfach 0 für den Port-Sektor ein.";
$l_planet_cargocredits = "Auto-Handels-Credits erhalten:";
$l_planet_cargonoown = "Sie müssen den Planeten besitzten um eine Auto-Handels-Route zu erstellen.";
$l_planet_digtrans = "Dignitary übertragen";
$l_planet_nocredits1 = "Sie haben nicht genügend Credits für diese Transaktion. Die Gesamtkosten belaufen sich auf ";
$l_planet_nocredits2 = " Credits, und Sie haben nur ";
$l_planet_nobase = "Sie müssen eine Basis haben, um die Verteidigungs-Levels Ihres Planeten zu managen.";
$l_planet_genesisnoturn	 = "Sie benötigen mindestens einen Turn, um ein Genesis-Device zu nutzen.";
$l_planet_nogenesis	 = "Sie benötigen eine Genesis-Device um einen Planeten zu zerstören.";
$l_planet_wrongclass	 = "Diese Schiffs-Klasse kann keine Nova Bombe abfeuern.";

$l_planet_combatpreview	 = "Kampf-Vorschau";
$l_planet_beamfire1	 = "Ihr Angriff wurde entdeckt. Planetarische Strahlen feuern! Strahlenfeuer wurde erhöht, als Sie dem Planeten so nahe kommen, dass Jäger gestartet werden können.";
$l_planet_beamfire2	 = "Ihr Angriff wurde entdeckt. Planetarische Strahlen feuern! Massives Gegenfeuer vom Planeten als die Strahlen-Batterie für mehrfache Treffer anvisiert!";
$l_planet_beamfire3	 = "Ihr Angriff wurde entdeckt. Planetarische Strahlen feuern! Sämtliche Strahlen-Kanonen des Planeten zielen für ein massives Feuer! Strahlen-Kraft viel höher als eingeschätzt!";
$l_planet_beamfire4	 = "Ihr Angriff wurde entdeckt. Planetarische Strahlen feuern! Die Strahlen-Verteidigung kann das Ziel nur einmal anvisieren.";

$l_planet_sofanobeamsshields	 = " feuert keine Strahlen auf Ihre Schilde.";
$l_planet_sofanobeamsarmor	 = " feuert keine Strahlen auf Ihre Ausrüstung.";
$l_planet_flauncherfailed1	 = "Ihre Jäger-Start-Rampe hat versagt.";
$l_planet_flauncherfailed2	 = "Sie waren nur in der Lage ";
$l_planet_flauncherfailed3	 = " Prozent Ihrer Jäger zu starten.";
$l_planet_nodfightertofighter	 = " schickt keine Jäger um Ihre Jäger anzugreifen.";
$l_planet_nodfightertotorp	 = " schickt keine Jäger um Ihre Torps anzugreifen.";
$l_planet_flauncherfailed3	 = " Prozent Ihrer Jäger.";
$l_planet_autotradetype = "- [source_type] am port [dest_id] ";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "attackiert";
$l_planet_iminsector = "im sektor";
$l_planet_imnova = "benutzt ein Nova-Device für";
$l_planet_imsofa = "bombardiert";
$l_planet_team = "Dieser Planet ist von einem Teamkollegen im Besitz und Sie haben keine Erlaubnis, die Informationen für diesen Planeten zugreifen.";
?>
