<?php
$l_ship2_buytitle        = "Neues Schiff kaufen";
$l_ship2_storetitle        = "Werft Zwischenlager";
$l_ship2_wrongclass        = "Falsche Schiffsklasse angegeben";
$l_ship2_buying        = "Sie kaufen:";
$l_ship2_tradein        = "Handeln In:";
$l_ship2_value        = "Aktueller Schiffswert:";
$l_ship2_newvalue        = "Neuer Schiffswert:";
$l_ship2_totalcost        = "Gesamtkosten:";
$l_ship2_nomoney        = "Sie haben nicht genügend Credits, dieses Schiff zu kaufen.";
$l_ship2_purchase        = "Kaufen";
$l_ship2_buynstore        = "Neues Schiff kaufen und altes einlagern";
$l_ship2_nomoney2        = "Sie haben nicht genügend Credits, diese Transaktion durch zuführen.";
$l_ship2_paystorage = "Ihr haben Ihr Schiff aus dem Lager entfernt.";
$l_ship2_turns        = "Sie benötigen mindestens [turns] Turns um diese Aktion durch zuführen";
$l_ship2_error        = "Interner Error. Schiffsklasse konnte nicht gefunden werden.";
$l_ship2_owned        = "YSie besitzen diesen Schiffstyp bereits.";
$l_ship2_shipbought        = "Sie haben gerade ein neues Schiff gekauft!";

?>
