<?php
$l_novabomb_turns = "Die Nova Bomb erfordert atleast [turns] wendet sich an Feuer.";
$l_novabomb_planetsdamaged = "Planeten beschädigt durch die Nova Bomb";
$l_novabomb_planet = "Planet [name] zu Schaden von der Nova-Bombe.";
$l_novabomb_novaexplode = "Nova Bombe explodierte, als er entlassen wurde und Ihr Schiff hat massive Schäden erlitten.";
$l_novabomb_novaexplode2 = "Nova Bombe explodierte, als er entlassen wurde und Ihr Schiff zerstört wurde.";
$l_novabomb_notfedsec = "Nova Bomb kann nicht auf Föderation Besitz Sektoren genutzt werden können.";
$l_novabomb_destroyed_planet = "Ihr nova Bombe knallte mit der Oberfläche des Planeten und in den Kern gebohrt, wo sie verursachen den Planeten zu zerstören explodierte.";
$l_novabomb_wrongclass = "Dieses Schiff Klasse kann nicht einen Nova Bomb Device.";
$l_novabomb_nonova = "Sie haben noch keine Nova Bomb installiert.";
$l_novabomb_novamiss = "Die Nova Bomb knapp verfehlt, aber ein Schaden auf dem Planeten.";
$l_novabomb_success = "Sector [sector] wurde Nova bombardiert!";
$l_novabomb_mines = "Zerstört [mines] Sektor Mines.";
$l_novabomb_fighters = "Zerstört [fighters] Sektor Fighters.";
$l_novabomb_shipsdamaged = "Schiffe beschädigt durch die Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] Schaden erlitten von der Nova-Bombe.";
$l_novabomb_ship_survived = "Ihr Schiff war weit genug weg, wenn der Nova-Bombe explodierte, um mögliche Schäden zu vermeiden.";
?>
