<?php
$l_att_title             = "attakiere Schiff";
$l_att_notarg            = "Ziel befindet sich nicht in diesem Sektor";
$l_att_noturn            = "Sie benötigen mind. 1 Turn um anzugreifen.";
$l_att_noatt             = "Jemanden in diesem Sektor anzugreifen ist nicht erlaubt.";
$l_att_flee              = "Das Ziel hat sie abgehängt!";
$l_att_ewd               = "Das Ziel hat während dem Angriff einen Not-Warp-Generator aktiviert!";
$l_att_att               = "Angriff auf ";
$l_att_beams             = "Strahlen-Austausch";
$l_att_torps             = "Torpedo-Austausch";
$l_att_fighters          = "Jäger-Austausch";
$l_att_lost              = "verloren";
$l_att_ylost             = "Sie haben verloren";
$l_att_sdown             = "'s Schilde sind deaktiviert!";
$l_att_ydown             = "Ihre Schilde sind deaktiviert!";
$l_att_shits             = "'s Schilde sind getroffen für";
$l_att_yhits             = "Ihre Schilde sind getroffen für";
$l_att_dmg               = "Schaden";
$l_att_sarm              = "'s Ausrüstung zerstört!";
$l_att_yarm              = "Ihre Ausrüstung wurde zerstört!";
$l_att_ashit             = "'s Ausrüstung wurde getroffen für";
$l_att_ayhit             = "Ihre Ausrüstung wurde getroffen für";

$l_att_efhit             = "'s Jäger wurden zerstört";
$l_att_yfhit             = "ihrer Jäger wurden zerstört.";
$l_att_ethit             = "'s Torpedos wurden zerstört.";
$l_att_ythit             = "ihrer Torpedos wurden zerstört.";
$l_att_of             = "von";
$l_att_lostt             = "hat alle Torpedos verloren.";
$l_att_ylostt            = "Sie haben alle Torpedos verloren.";

$l_att_lostf             = "Hat alle Jäger verloren.";
$l_att_ylostf            = "Sie haben alle Jäger verloren.";
$l_att_sdest             = "'s Shiff wurde zerstört.";
$l_att_espod             = "Eine Rettungskapsel wurde gestartet!";
$l_att_ysalv             = "Sie retteten [ship_salvage_rate]% Ihres Schiffes im Wert von [ship_salvage] Credits.<BR>Ihre Bewertung änderte sich um [rating_change] Punkt.";
$l_att_andused           = "und benutzt";
$l_att_stilship          = "Sie haben [name]'s Schiff nicht zerstört.";
$l_att_atyou             = "griff Sie an";
$l_att_and               = "und";
$l_att_yshiplost         = "Ihr Schiff wurde zerstört.";
$l_att_salv              = "[name] rettete [ship_salvage_rate]% seines Schiffs im Wert von [ship_salvage] Credits";
$l_att_loosepod		 = "Glücklicherweise haben Sie eine Rettungskapsel";

$l_att_tnobeams		 = " scheint keine Energie für beams mehr zu haben.";
$l_att_tnobeamsf		 = " scheint keine Energie für beams mehr zu haben und kann Ihre Jäger nicht angreifen.";
$l_att_tnobeamst		 = " scheint keine Energie für beams mehr zu haben und kann Ihre Torpedos nicht angreifen.";
$l_att_tfnoattack		 = " sendet keine Jäger um Ihr Schiff zu attackieren.";
$l_att_tnotorps		 = " scheint keine Torpedos mehr zu haben.";

$l_att_anobeams		 = "Sie haben Ihre Schiffsenergie für beams aufgebraucht.";
$l_att_anobeamsf		 = "Sie haben Ihre Schiffsenergie für beams aufgebraucht und können keine gegnerischen Jäger angreifen.";
$l_att_anobeamst		 = "Sie haben Ihre Schiffsenergie für beams aufgebraucht und können keine gegnerischen Torpedos angreifen.";
$l_att_anofighters		 = "Ihr Schiff hat alle verfügbaren Jäger aufgebraucht.";
$l_att_anotorps		 = "Sie haben Ihre verfügbaren Torpedos aufgebraucht.";
$l_att_imtitle		 = "Shiff wird angegriffen";
$l_att_imbody		 = "greift Ihr Schiff an.";

$l_att_luckybeams		 = "Der Gegner hat einen beam-overload hervorgerufen";
$l_att_luckyfighters	 = "gegnerische Jäger machen eine überraschende Blitzattacke und verursachen";
$l_att_luckytorps		 = "Gegnerische Torpedos fügen weniger schaden zu, und verursachen";
$l_att_luckytimes		 = "timet den normalen Schaden!";
?>
