<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] hat [chm_roll] Minen im Sektor [chm_sector] erwischt.";
$l_chm_youlostminedeflectors    = "Sie haben [chm_roll] Minen-Deflektoren verloren.";
$l_chm_youlostallminedeflectors = "Sie haben alle Minen-Deflektoren verloren.";
$l_chm_youhadnominedeflectors  = "Sie hatten keine Minen-Deflektoren.";
$l_chm_yourshieldshitforminesdmg        = "Ihre Schilde wurden um [chm_mines_left] beschädigt.";
$l_chm_yourshieldsaredown       = "Ihre Schilde sind ausgefallen!";
$l_chm_youlostallyourshields    = "Sie haben Ihre kompletten Schilde verloren!";
$l_chm_yourarmorhitforminesdmg  = "Ihre Ausrüstung wurde um [chm_mines_left] beschädigt.";
$l_chm_yourhullisbreached       = "Ihre Hülle ist gebrochen!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] wurde von Ihren Minen im Sektor [chm_sector] zerstört.";
$l_chm_yourshiphasbeendestroyed = "Ihr Schiff wurde zerstört!";
$l_chm_luckescapepod     = "Glücklicherweise haben Sie eine Rettungskapsel";

$l_chm_yourdeflectormalf1		 = "Minen-Deflektoren-Abschuß-Rampen haben versagt.";
$l_chm_yourdeflectormalf2		 = "Sie waren nur in der Lage ";
$l_chm_yourdeflectormalf3		 = " Prozent Ihrer Minen-Deflektoren zu starten.";
$l_chm_enemytorpfailshields     = " hat keine Torpedos gegen Ihre Schilde gestartet.";
$l_chm_enemytorpfailarmor     = " hat keine Torpedos gegen Ihre Ausrüstung gestartet.";

$l_chm_minemalf1		 = "Gegnerische Minen haben versagt.";
$l_chm_minemalf2		 = "Nur ";
$l_chm_minemalf3		 = " Prozent der angreifenden Minen haben Ihr Schiff gefunden.";

$l_chm_youhitsomemines = "Du schlägst [chm_roll] Minen von [total_mines] Minen!";
$l_chm_yourdeflectormalf2a = "Sie haben nur in der Lage, [deflectors] Prozent Ihrer Mine Deflektoren starten.";
$l_chm_mines_destroyed = "[number] vom [target] Minen wurden vernichtet!";
$l_chm_mine_deflectors_left = "Sie haben [number] Mine Abweiser links.";
$l_chm_mines_left = "Es gibt [number] Minen links und sie sind Auswirkungen auf Ihre Rüstung!";
$l_chm_minemalf2a = "Nur [deflectors] Prozent der Bergwerke Angriff gefunden Ihres Schiffes.";
$l_chm_mines_exhausted = "[player] Mines erschöpft!";
$l_chm_armor_left = "Sie haben [number] Rüstung Punkte übrig!";

?>
