<?php
$l_die_title             = "Selbstzerstörung";
$l_die_rusure            = "Sind Sie sicher, dass Sie Ihr Schiff wirklich zersören möchten?? Diese Aktion wird Sie aus dem Spiel entfernen.";
$l_die_goodbye           = "Auf wiedersehen schreckliche Galaxy";
$l_die_check             = "Haben Sie sich entschieden, dass Sie sich aus dem Spiel entfernen möchten?";
$l_die_nonono            = "NEIN! NEEIN! NEEEIN!";
$l_die_what              = "Worüber habe Ich nachgedacht?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor             = "Ihr Schiff und alles was Sie an Bord hatten wurde zerstört.";
$l_die_please1           = "ausloggen";
$l_die_please2           = "Bitte, [logout_link]";
$l_die_exploit           = "Spiele nichts, was Du nicht verstehst.";
?>
