<?php
$l_new_pwis              = "Ihr Passwort ist";
$l_new_charis            = "Ihr Character-Name ist";
$l_new_title2            = "Neuen Spieler erstellen Phase zwei";
$l_new_blank             = "E-mail, Schiffsname, und Character-Name dürfen nicht leer sein.";
$l_new_inuse             = "E-mail-addresse von [username] wird bereits benutzt.";
$l_new_forgotpw          = "Passwort vergessen?";
$l_new_inusechar         = "Character-Name [character] wird bereits benutzt.";
$l_new_similar_inusechar = "Ihr Character-Name klingt ähnlich wie [character] (wird bereits benutzt)";
$l_new_inuseship         = "Schiffsname [shipname] wird bereits benutzt.";
$l_new_similar_inuseship = "Ihr Schiffs-Name klingt ähnlich wie [shipname] (wird bereits benutzt).";
$l_new_pwsent            = "Das Passwort wurde an [username] geschickt.";
$l_new_err               = "Bitte nochmal versuchen";
$l_new_topic             = "Alien Assault Traders Passwort";
$l_new_message           = "Hi,\n\nJemande mit der IP-Adresse $ip hat verlangt, dass das Passwort für Traders an Sie gesendet wird.\n\nIhr Passwort lautet: [pass]\n\nVielen Dank\n\nDas Traders web team.";
$l_new_invalidemail             = "Falsche Email-Addresse.";
$l_new_tutorial = "Klicken Sie hier um ein Mini-Tutorial zu lesen, bevor Sie sich am Spiel beteiligen.";
$l_new_profile = "Falls Sie ein Spieler-Profil auf <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>haben, können Sie diesen Spieler in den <b>Einstellungen</b> anmelden. ";
$l_new_login             = "um zum Login-Screen zurück zukehren.";

?>
