<?php
$l_cu_storing = "Speichern";
$l_cu_inistored = "<b>Alle ini-Werte wurden erfolgreich gespeichert.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto Route Destination";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Route löschen";
$l_cu_info = "Klicken Sie auf das Start-Sektor zu Realspace zu diesem Sektor und Anfang, der verzerrt, um das Ziel Sektor.";
$l_cu_delete2 = "Routen löschen";
$l_cu_noroutes = "Kein Auto Routen";
$l_cu_createroute = "Neues Auto Route";
$l_cu_deleted = "Auto-Routen gestrichen.";
$l_cu_return = "Zurück zu Auto-Route Klicken Sie im Menü";
$l_cu_created = "Auto Route erstellt wurde.";
$l_cu_realmove = "Realspace Umzug nach Sektor";
$l_cu_warpmove = "Warp Übergang zu nächsten Sektor";
$l_cu_warpfinal = "Warp zu bewegen letzten Sektor";
?>
