<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] 		 = "Unbekannter Weltraum";
$l_zname[2] 		 = "Föderations-Weltraum";
$l_zname[3] 		 = "Allianz-Weltraum";
$l_zname[4] 		 = "Kriegszone";

$l_nova = "Nova";
$l_nova 		 = "Nova Bombe";
$l_lssd 		 = "Letztes gesehene Shiffs-Gerät";
$l_lss 			 = "Letztes gesehene Schiff";
$l_log_text[LOG_TOW] 	 = "Ihr Schiff wurde vom Sektor [sector] zum Sektor [newsector] geschleppt, weil Ihr durchnschnittlicher Tech-Level den Wert der Hülle von [hull] überschritten hat, oder Sie ein anderes Schiff belagert haben.";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Warp-Editor verwenden";
$l_warp_turn		 = "Sie benötigen mindestens einen Turn, um einen Warp-Editor zu benutzten.";
$l_warp_none		 = "Sie haben keine Warp-Editoren";
$l_warp_forbid		 = "Sie dürfen in diesem Sektor keinen Warpm-Editor verwenden.";
$l_swarp_forbid		 = "Einen Warp-Editor von oder in einen SG Sektor ist nicht gestattet.";
$l_warp_nosector	 = "Dieser Sektor existiert nicht.";

// Not yet confirmed common to multiple files:

$l_yes 			 = "Ja";
$l_no			 = "Nein";
$l_here			 = "hier";
$l_submit		 = "Abschicken";
$l_reset = "Reset";
$l_all			 = "Alle";
$l_max = "Max";

$l_trade = "Handel";
$l_ore			 = "Erz";
$l_commodity = "Commodity";
$l_commodities		 = "Waren";
$l_organics		 = "organisches Material";
$l_goods		 = "Güter";
$l_energy		 = "Energie";
$l_colonists		 = "Kolonisten";
$l_credits = "Credits";
$l_units		 = "Einheiten von ";
$l_special		 = "Spezial";
$l_upgrade_ports = "Upgrades";
$l_device_ports		 = "Geräte";
$l_spacedock = "Raumdock";
$l_casino		 = "Kasino";
$l_dig = "Würdenträger";
$l_spy = "Spies";

$l_cargo		 = "Fracht";
$l_fighters		 = "Jäger";
$l_mines		 = "Minen";
$l_torps		 = "Torpedos";

$l_none = "Keine";
$l_unnamed = "Unbenannt";
$l_name = "Name";
$l_unowned		 = "Besitzerlos";
$l_unknown		 = "Unbekannt";
$l_clickme 		 = "hier klicken";
$l_player  		 = "Spieler";
$l_ship			 = "Schiff";
$l_ships		 = "Schiffe";
$l_set			 = "setzte";
$l_realspace = "Realspace";
$l_armorpts		 = "Ausrüstung";
$l_links = "Links";
$l_login_email          = "E-mail-Addresse:";
$l_add			 = "Hinzufügen";
$l_teamforum = "Team Forum";
$l_teamships			 = "Team Schiff";
$l_tutorial			 = "Tutorial/Hilfe";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris			 = "Trümmer";
$l_localmap			 = "Locale Karte";
$l_arm_weap              = "Rüstung & Waffen";
$l_3dmap			 = "3D Galaxie Karte";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Signalposten";
$l_spaceprobes = "Weltraumsonde";
$l_warpeditors = "Warp-Editoren";
$l_genesistorps = "Genesis Torpedos";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Minen/Jäger";
$l_ewarp = "Notwarp";
$l_reports = "Berichte";
$l_shipinfo = "Shiffs-Info";
$l_sectornotes = "Sektor-Notizen";
$l_maps = "Karten";
$l_messages = "Nachrichten";
$l_shiptype = "Schiffstyp";
$l_help = "Hilfe";
$l_rank = "Rang";

$l_teamplanets = "Team Planeten";
$l_teamdefenses = "Team Abwehr";
$l_planetstatus = "Planeten-Status";
$l_planetdefenses = "Planet-Abwehr";
$l_changeproduction = "Produktion ändern";
$l_galacticarm = "galaktischer Arm";

$l_armor		 = "Ausrüstung";
$l_news_none = "Sorry, heute keine Nachricht.";

$l_ranks_good = "Gut";
$l_ranks_evil = "Böse";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Klicken Sie <A HREF=main.php>hier</A> um zum Hauptmenü zurück zukehren.";
$l_global_mlogin         ="Klicken Sie <A HREF=index.php>hier</A> um zum Login-Bildschirm zurückzukehren.";
$l_global_needlogin      ="Sie müssen sich <A HREF=index.php>hier</A> einloggen.";
$l_global_died           ="Der Spieler ist TOD! <a href=log.php>Hier</a> können Sie erfahren, was passiert ist<BR><BR>Mehr Glück nächstes Mal!";
$l_global_warzone        ="Die Zone ist jetzt eine Kriegs-Zone!";
$l_global_nzone          ="Die Zone ist eine neutrale Zone.";
$l_global_team           ="Die Zone gehört nun zum Team";
$l_global_player         ="Die Zone gehört nun zum Spieler";
$l_global_nochange       ="Die Besitzverhältnisse der Zone haben sich nicht geändert";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "Petty Officer Third Class";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Leutnant zur See";
$l_insignia_name[10] = "Lieutenant Junior Grade";
$l_insignia_name[11] = "Lieutenant";
$l_insignia_name[12] = "Korvettenkapitän";
$l_insignia_name[13] = "Commander";
$l_insignia_name[14] = "Captain";
$l_insignia_name[15] = "Rear Admiral (untere Hälfte)";
$l_insignia_name[16] = "Rear Admiral (obere Hälfte)";
$l_insignia_name[17] = "Vizeadmiral";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Fleet Admiral";

$l_main_title            = "Hauptmenü";
$l_main_warpto           = "Warp nach";
$l_main_autoroute        = "Autoroute nach";
$l_main_rs_to            = "RSM nach";
$l_main_other            = "Andere";
$l_main_shipyard1        = "Werft";
$l_main_shipyard2        = "Betrette Werft ";
$l_traderoutes           = "Routenhandel";
$l_trade_control         = "Handelsrouten";
$l_youhave               = "Sie haben ";
$l_turns_used            = "benutze Turns: ";
$l_turns_have            = "verfügbare Turns: ";
$l_score                 = "Punkte: ";
$l_sector                = "Sektor";
$l_help                  = "Hilfe";
$l_faq = "";
$l_feedback = "Rückmeldung";
$l_forums                = "Forum";
$l_logout = "Logout";
$l_commands              = "Commandos";
$l_command_no            = "Commando nicht verfügbar.";
$l_devices               = "Geräte";
$l_planets               = "Planeten";
$l_log = "Anmelden";
$l_sector_def            = "Sektor-Verteidigung";
$l_defense               = "Verteidigung";
$l_read_msg              = "Lese Nachrichten";
$l_send_msg              = "Sende Nachrichten";
$l_rankings = "Rankings";
$l_teams = "Teams";
$l_ohno                  = "Selbstzerstörung";
$l_options               = "Optionen";
$l_navcomp = "Nav Computer";
$l_incompletemove        = "Sie haben Ihre vorherige Bewegung nicht beendet.";
$l_clicktocontinue       = "Hier klicken um vortzufahren";
$l_toplanetmenu          = "um zum Planeten-Menu zu gelangen.";
$l_nonexistant_pl        = "Auf einem nicht existierenden Planeten???";
$l_abord                 = ", brich ab ";
$l_messages_wait         = " neue Nachrichten.";
$l_no_warplink           = "Keine Warp-links";
$l_scan                  = "scannen";
$l_fullscan              = "komplett Scannen";
$l_port                  = "Posten";
$l_tradingport           = "Handelsposten";
$l_planet_in_sec         = "Planeten im Sektor ";
$l_ships_in_sec          = "Andere Schiffe im sektor ";
$l_sector_0              = "Es ist so viel Verkehr im Sol dass du andere Schiffe nicht einfach isolieren kannst.!";
$l_map                   = "Karte";
$l_probe				 = "Sonden";
$l_autotrade				 = "automatisches Handeln";
$l_onboard				 = "Anbord a";
$l_classship = "Schiffskasse";
$l_traveled = "wanderte zum Sektor";
$l_max_planets = "Maximal bewohnbare planeten";
$l_block_msg              = "Block Nachrichten";
$l_sectorinfo = "Sector Info";
$l_add_note = "Anmerkung hinzufügen";
$l_view_note = "Anzeigen";
$l_notes = "Notes";
$l_global_limitreached = "Sie haben das Limit für die Höhe der Zeit dürfen Sie sich im Internet jeden Tag erreicht. Melden Sie sich morgen wieder nach Mitternacht.";
$l_onlinetimeleft = "Verbleibende Zeit:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Gespeicherte Versand";
$l_global_chat = "Global Chat";
$l_team_chat = "Team-Chat";
$l_fedinfo = "Föderation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Vorhergehende Seite";
$l_common_next = "Nächste Seite";
$l_common_totalpages = "Summe Seiten";
$l_common_selectpage = "Wählen Sie die Seite:";
$l_common_page = "Seite:";
$l_templatechange = "Möchten Sie diese Vorlage zu halten?";

$l_im_fed_bounty = "Der Bund hat ein Kopfgeld auf Sie für den Angriff auf einem so niedrigen Rang Spieler platziert. Die Föderation wird Ihr Schiff auf einer regelmäßigen Basis angreifen, bis Sie wieder Ihre Prämie zu zahlen. Sie können zahlen Sie Ihre Prämie an jedem Port Upgrade oder Raumdock.";
$l_im_fed_bounty_title = "Föderation hat ein Kopfgeld auf Sie!";
$l_im_alliance_bounty = "Das Bündnis hat ein Kopfgeld auf Sie für den Angriff auf einem so niedrigen Rang Spieler platziert. Das Bündnis wird Ihr Schiff auf einer regelmäßigen Basis angreifen, bis Sie wieder Ihre Prämie zu zahlen. Sie können zahlen Sie Ihre Prämie an jedem Port Upgrade oder Raumdock.";
$l_im_alliance_bounty_title = "Allianz platziert ein Kopfgeld auf Sie!";
$l_instant_messages_waiting = "Sie haben [count] Nachrichten warten auf Sie.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Hält gefüllt:";
$l_hold_space_free = "Hält Leer:";
$l_port_buys = "Port Buys:";

?>
