<?php
$l_opt2_title            = "Einstellungen speichern";
$l_opt2_passunchanged    = "Das Passwort wurde nicht verändert.<BR><BR>";
$l_opt2_srcpassfalse     = "Das Originalpasswort ist falsch. Das Passwort wurde nicht verändert.<BR><BR>";
$l_opt2_newpassnomatch   = "Neue Passwortfelder stimmen nicht überein. Das Passwort wurde nicht verändert.<BR><BR>";
$l_opt2_passchanged      = "Das Passwort wurde geändert.<BR><BR>";
$l_opt2_passchangeerr    = "Fehler beim Ändern des Passworts<BR><BR>";
$l_opt2_userintup        = "Oberflächen-Einstellung wurde aktualisiert.<BR><BR>";
$l_opt2_userintfail      = "Oberflächen-Einstellung konnte nicht geändert werden.<BR><BR>";
$l_opt2_chlang           = "Es wurde die Sprache [lang] gewählt.<p>";
$l_opt2_chtemplate           = "Template wurde in [template] geändert.<p>";
$l_opt2_dhtmlup          = "Dynamische html-Einstellung wurde aktualisiert.<BR><BR>";
$l_opt2_dhtmlfail        = "Dynamische html-Einstellung konnen nicht aktualisiert werden.<BR><BR>";
$l_opt2_shipnamechanged = "ShipName geändert [name]. <BR><BR>";
$l_opt2_playernamechanged = "Player Name änderte sich zu [name] und [amount] Credits von Ihrem Schiff Konto abgezogen. <BR><BR>";
$l_opt2_mapwidth        = "Größe der lokalen und galaktischen Karte: ";
?>
