<?php
// port.php port_purchase.php
$l_trade		 = "Handeln";
$l_title_port		 = "Handels-Port";
$l_title_trade		 = "Waren-Handel";
$l_sector_war		 = "Kriegsblockade";
$l_war_info		 = "Krieg wütet in diesem Sektor. Sie können all die feindlichen Kräfte nicht überwinden, um zum Port zu gelangen.";
$l_no_trade		 = "Handel verboten";
$l_no_trade_out		 = "Handel ist an diesem Port für Aussenstehende nicht erlaubt";
$l_no_trade_info	 = "Handel ist an diesem Port nicht erlaubt";
$l_buying		 = "kaufe";
$l_selling		 = "verkaufe";
$l_commodity		 = "Ware";
$l_amount		 = "Menge";
$l_price		 = "Preis";
$l_buy			 = "Kaufen";
$l_sell			 = "Verkaufen";
$l_trade_st_info	 = "Sie haben [free_holds] freien Lagerraum. Sie können [free_power] Einheiten Energie einladen und sind im Besitz von [credits] Credits.";
$l_upgrade_port_title	 = "Aufrüst-Port";
$l_device_port_title	 = "Geräte-Port";
$l_spacedock_port_title	 = "Weltraum-Dock";
$l_no_credits		 = "Nicht genügend Credits";
$l_creds_to_spend	 = "Sie können [credits] Credits augeben.";
$l_cost			 = "Kosten";
$l_avail		 = "Verfügbar";
$l_profit = "Profit";
$l_current		 = "Derzeitig";
$l_current_level	 = "aktueller Level";
$l_current_qty		 = "aktuelle Quantität";
$l_max = "Max";
$l_ifyouneedmore	 = "Falls Sie mehr benötigen können Sie auch die [igb] des Ports benutzen";
$l_ifyouneedplan	 = "Zugriff auf das planetarische";
$l_igb_term		 = "IGB Bank-Terminal";
$l_upgrade		 = "aufrüsten";
$l_unlimited		 = "Unlimitiert";
$l_full			 = "Voll";
$l_equipped		 = "Ausgerüstet";
$l_n_a = "n / a";
$l_item = "Element";
$l_totalcost		 = "Gesamtkosten";
$l_would_dump	         = "Falls Sie all Ihre Kolonisten abladen möchten klicken Sie hier ";
$l_noport		 = "Es gibt hier keinen Port!";
$l_trade_turnneed	 = "Sie benötigen mindestens einen Turn um an einem Port oder Planeten zu handeln.";
$l_returnto_port1        = "hier";
$l_returnto_port2        = " [port_link] klicken um zum Port-Menü zu gelangen.";
$l_notenough_cargo	 = "Sie haben nicht genügend freien Laderaum für die Waren, die Sie kaufen möchten.";
$l_notenough_power	 = "Sie haben nicht genügend freien Platz für Energie, die Sie kaufen möchten.";
$l_notenough_credits	 = "Sie haben nicht genügend Credits um diese Transaktion zu beenden.";
$l_notenough_turns	 = "Sie haben nicht genügend Turns um diese Transaktion zu beenden.";
$l_trade_result		 = "Resultate für diesen Handel";
$l_trade_complete	 = "Handel abgeschlossen";
$l_trade_upgraded 	 = "Aufgerüstet auf Level ";
$l_trade_added 		 = "hinzugefügt";
$l_trade_installed 	 = "eingebaut";
$l_port_bounty 		 = "Sie können keinen Spezial-Port betreten, wenn eine Belohnung von der Föderation auf Sie ausgesetzt wurde.<BR>";
$l_port_bounty2 	 = "<a href=\"port.php?pay=1\">Hier</a> klicken um die Belohnung von [amount] Credits zu bezahlen.";
$l_port_btynotenough 	 = "Sie haben nicht genügend Credits um sie Prämie von [amount] Credits bezahlen zu können.<BR>";
$l_port_bountypaid 	 = "Sie haben die Prämie bezahlt. <a href=\"port.php\">Hier</a> klicken um fortzufahren.<BR>";
$l_port_loannotrade 	 = "Die IGB hat Ihr Schiffskonto wegen einem nicht bezahlten Kredit gesperrt. Sie können nicht an einem Spezial-Port handeln, bis Sie Ihren Kredit beglichen haben.";
$l_port_returntospecial = "um zum Depot zurück zukehren.";
$l_toprobemenu          = "um zum Sonden-Menü zu gelangen.";
$l_ports_shiplimit = "Min. Schiffsklasse in das ein Gerät integriert werden kann: ";
$l_ports_needrepair = "Reparieren";

$l_ports_needcredits = "Sie haben nicht genügend Credits für diese Transaktion. Die Gesamtkosten betragen";
$l_ports_needcredits1 = "Credits. Sie haben aber nur";

$l_ports_tradeforbidden = "Handel verboten";
$l_ports_nooutsiders = "Der Handel an diesem Port ist für Aussenstehende nicht gestattet.";

$l_bought = "Sie kauften";
$l_sold = "Sie verkauften";
$l_notenough_commodity = "Sie haben nicht genug [commodity], um die Transaktion abzuschließen.";
$l_exceed_commodity = "Anzahl der [commodity] übersteigt das Angebot / Nachfrage.";
$l_port_shiptoolarge = "Das Schiff ist zu groß, um in diesem Hafen den Handel.";

$l_port_hold_unit = "Enthält pro Einheit";

$l_port_welcome = "Port [sectorname] Welcome&#39;s [player]";
$l_port_amountforsale = "Der Hafen hat [amount] Einheiten [commodity] zum Verkauf an [credits] Credits pro Einheit.";
$l_port_holdsperunit = "[holds] Laderäumen pro Einheit erforderlich.";
$l_port_howmanypurchase = "Wie viele [commodity] Stück möchten Sie kaufen?";
$l_port_unitstobuy = "Einheiten kaufen zu";
$l_port_shipcarryingbuy = "Das Schiff trägt [shipunits] Einheiten [commodity]. Sie können Einkaufsbedingungen [buyunits] Einheiten mit den verfügbaren Laderaum Platz.";
$l_port_howmanysell = "[amount] Einheiten [commodity] @ [credits] Credits pro Einheit.";
$l_port_unitstosell = "Einheiten zu verkaufen";
$l_port_perform = "Führen Transaction";
$l_port_cargoholds = "Laderäume";

?>
