<?php
$l_md_title              = "Sektor-Verteidigung";
$l_md_invalid            = "Fehlerhafte Sektor-Verteidigung";
$l_md_nolonger           = "Die ausgewählte Sektor-Verteidigung exisitert nicht mehr.";
$l_md_you                = "dir";
$l_md_bmines             = "Ihr Strahlen wurden zerstört";
$l_md_msgdownerb         = "[name] hat [mines] Minen im Sektor [sector] zerstört.";
$l_md_retr               = "Sie haben erneuert";
$l_md_consist            = "Diese Sektor-Verteidigung besteht aus [qty] [type] im Besitz von [owner].";
$l_md_youcan             = "Sie können";
$l_md_retrieve           = "Erneuern";
$l_md_attack             = "Angreifen";
$l_md_attdef             = "Greife die Sektor-Verteidigung an. Alle Sktor-Jäger werden Vergeltung ausüben.";
$l_md_noturn             = "Sie benötigen mindestens einen Turn.";
$l_md_nothere            = "Sie müssen sich im selben Sektor wie die Sektor-Verteidigung befinden.";
$l_md_notyours           = "Aktion nicht erlaubt. Diese Sektor-Verteidigung gehört Ihnen nicht.";
$l_md_yours              = "Sie können Ihre eigene Sektor-Verteidigung nicht angreifen.";
?>
