<?php
$l_shipyard_title        = "Werft";
$l_planet = "Planet";
$l_ship_welcome = "Willkommen in der Werft der Planetary. Wir bieten zur Zeit diese Modelle zum Verkauf an.";
$l_ship_class = "Klasse";
$l_ship_properties = "Klassen-Eigenschaften";
$l_ship_current = "aktuell";
$l_ship_outstorage = "ausverkauft";
$l_ship_storagecost = "Lagerkosten";
///////////////////////////////////////
$l_ship_storagewarn = "Wenn nehmen Sie Ihren Pioneer aus der Lagerung verlieren Sie die von Ihnen waren auf Ihre erste Schiff Verwertungsnachweis ausgestellt.";
///////////////////////////////////////
$l_ship_levels = "Schiffsteile Levels";
$l_ship_min = "Min.";
$l_ship_max = "Max";
$l_ship_price = "Preis";
$l_ship_turns = "Turns für den Bau";
$l_ship_purchase = "Kaufen";
$l_ship_stored = "Gespeicherte";
$l_ship_basehull = "Base Rumpf:";

$l_ship_averagemaxtech = "Durchschnitt Maximum Tech Level:";
$l_ship_averagenormaltech = "Durchschnittliche Normal Tech Level:";
$l_ship_averagecurrenttech = "Durchschnittliche Aktuelle Tech Level:";

?>
