<?php
$l_dump_title            = "Kolonisten ausladen";
$l_dump_turn             = "Sie benötigen mind. 1 Turn um die Kolonisten auszuladen.";
$l_dump_nocol            = "Sie haben keine Kolonisten auf Ihrem Schiff, mit denen man beginnen könnte.";
$l_dump_dumped           = "Der Bedarf an Kolonisten wird am Depot ausgeladen.";
$l_dump_nono             = "Sie müssen an einem Bedarfs-Depot sein, um dies zu tun.";
?>
