<?php
$l_ze_title              = "Editiere Zone";
$l_ze_notowner           = "Sie sind nicht der Besitzer dieser Zone, also können Sie sie auch nicht editieren.";
$l_ze_name               = "Zonenname";
$l_ze_allow              = "Erlaube";
$l_ze_attacks            = "Erlaube den Angriff anderer Schiffe";
$l_ze_genesis            = "Erlaube Erstellung neuer Planeten";
$l_ze_return             = "Um zur Zonen-Informationsseite zurückzukehren";
$l_ze_saved              = "Änderungen wurden gespeichert.";
$l_ze_namematch = "ERROR: Der Zonenname, den Sie gewählt haben ist ähnlich oder gleicht einer bereits existierenden Zone.";
?>
