<?php
$l_pre_title             = "Change Realspace Presets";
$l_pre_exceed            = "Preset [preset] exceeds universe max of [sector_max]. No presets saved.<BR><BR>";
$l_pre_set               = "Preset";
$l_pre_save              = "Save";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
