<?php
$l_nav_title             = "Navigation Computer";
$l_nav_nocomp            = "Navigation Computer is not available";
$l_nav_query             = "Enter sector to find path to: ";
$l_nav_pathfnd           = "Path found";
$l_nav_answ1             = "It will take you";
$l_nav_answ2             = "turns to get to this sector.";
$l_nav_proper            = "You need to upgrade your Fighter Bay technology before your fighters can find a warp route for that distance.";
$l_nav_autoroutename     = "Optional Autoroute Name: ";
$l_nav_manuallist        = "Manually Built WarpLink Autoroute List";
$l_nav_warplinksleaving     = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving     = "There are no warplinks leaving this sector.";
$l_nav_warp_from           = "Warp from";
$l_nav_rs_from            = "RSMove from";
$l_nav_notinlogs            = "No data available on this sector.";
?>
