<?php
$l_scan_title            = "Scan Ship";
$l_scan_turn             = "You need at least one turn to scan another ship.";
$l_scan_ron              = "Scan results on";
$l_scan_capt             = "Captained by:";
$l_scan_arma             = "Armament:";
$l_scan_carry            = "Carrying:";
$l_scan_bounty           = "This ship has a total bounty on it of [amount] credits.";
$l_scan_fedbounty        = "This ship has a bounty on it from The Federation.";
$l_by_nofedbounty        = "Attacking this player will <B>NOT</B> result in The Federation placing a bounty on you.";
?>
