<?php
$l_sf_attacking          = "Sector defense fighters are attacking you!<BR>";
$l_sf_destfight          = "Your beams destroyed [lost] fighters<BR>";
$l_sf_destfightb         = "Your beams destroyed [lost] fighters<BR>";
$l_sf_torphit            = "Torpedoes hit:";
$l_sf_destfightt         = "Your torpedoes destroyed [lost] fighters<BR>";
$l_sf_fighthit           = "Fighters Attack:";
$l_sf_destfightall       = "You destroyed all the fighters.<BR>";
$l_sf_destfightt2        = "You destroyed [lost] fighters.<BR>";
$l_sf_lostfight          = "You lost all fighters.<BR>";
$l_sf_lostfight2         = "You lost [lost] fighters.<BR>";
$l_sf_armorbreach        = "Your armor is breached!<BR>";
$l_sf_armorbreach2       = "Your armor is hit for [lost] damage.<BR>";
$l_sf_sendlog            = "[player] destroyed [lost] sector defense fighters in sector [sector].";
$l_sf_lreport            = "You lost [armor] armor points, [fighters] fighters, and used [torps] torpedoes.<BR><BR>";
$l_sf_shipdestroyed      = "Your ship has been destroyed!<BR><BR>";
$l_sf_sendlog2           = "Sector defense fighters destroyed [player] in sector [sector].";
$l_sf_escape             = "Luckily you have an escape pod!<BR><BR>";

$l_sf_fnoattack		 = " isn't sending any fighters to attack your fighters.";
$l_sf_fnoattackt	 = " isn't sending any fighters to attack your torpedoes.";
$l_sf_fnoattacka	 = " isn't sending any fighters to attack your armor.";
$l_sf_flaunchmalf1		 = "Your fighter launching system has malfunctioned.";
$l_sf_flaunchmalf2		 = "You have only been able to launch ";
$l_sf_flaunchmalf3		 = " percent of your fighters.";
$l_sf_fightertorpexg		 = "Fighter to Torpedo/Mine Exchange";
$l_sf_torpfighterexg		 = "Ship Torpedo to Sector Fighter Exchange";
$l_sf_fighterarmorexg		 = "Sector Fighter to Ship Armor Exchange";
$l_sf_tlaunchmalf1		 = "Your torpedo launching system has malfunctioned.";
$l_sf_tlaunchmalf2		 = "You have only been able to launch ";
$l_sf_tlaunchmalf3		 = " percent of your torpedoes.";
$l_sf_bountysd		 = "You have attacked a sector containing a planet that would give you a bounty if you attacked the planet.  The Federation has activated an automatic self-destruct on all of your fighters and torpedoes. Do not attack the sector defenses in this sector again.  You have been warned!";
?>
