<?php
$l_sofa                  = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn	 = "You need at least 1 turn to build a base";
$l_planet_upgrade   ="Upgrade";
$l_planet_novamiss   ="The Nova Bomb narrowly misses but inflicts damage upon the planet.";
$l_planet_novaturns   ="The Nova Bomb requires atleast [turns] turns to fire.";
$l_planet_novafed   ="The Nova Bomb will not power up in Federation sectors.";
$l_planet_nonova   ="You do not have a Nova Bomb installed.";
$l_planet_firenova   ="Fire Nova Bomb";
$l_planet_novaexplode   ="Nova Bomb exploded as it was fired and your ship has suffered massive damage.";
$l_planet_novaexplode2   ="Nova Bomb exploded as it was fired and your ship was destroyed.";
$l_planet_noautotrade   ="Auto Trade Route not set for this planet.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] at port [dest_id] ";
$l_planet_autotradedelete   ="Delete Auto Trade.";
$l_planet_autotradeadd   ="Create Auto Trade.";
$l_planet_tradedeleted   ="Auto Trade Route Deleted.";
$l_planet_tradeadded   ="New Auto Trade Route Added.";
$l_planet_autotype = "Select the item to trade";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "You need to purchase a Cargo Ship for this planet before you can set an Auto Trade Route.";
$l_planet_purchasecargo = "If you would like to purchase a Cargo Ship";
$l_planet_upgradecargo = "If you would like to upgrade your Cargo Ship";

$l_planet_cargocapacity = "Capacity: ";
$l_planet_cargoowned = "You already own a cargo ship for this planet.";
$l_planet_cargoshipbuy = "Purchase Cargo Ship";
$l_planet_cargoshipupgrade = "Upgrade Cargo Ship";
$l_planet_cargoatmax = "Your Cargo ship is at the maximum upgrade level.";
$l_planet_cargoshipbuyinfo = "Select a preset Cargo Ship";
$l_planet_cargoshipupgradeinfo = "Upgrade your Cargo Ships Hull.";
$l_planet_cargoshipbuildinfo = "Build your Own Cargo Ship";
$l_planet_tradehelp = "1. You can enter a trade port for each type of commodity.<br>2. You cannot trade a commodity at a port that sells the same commodity.<br>&nbsp;&nbsp;&nbsp;Trading Goods at a Goods Port, Ore at an Ore Port, ect. will do nothing.<br>3. If you do not want to trade certain commodities just enter 0 for the port sector.";
$l_planet_cargocredits = "Auto Trade Credits Received:";
$l_planet_cargonoown = "You must own the planet to create an Auto Traderoute.";
$l_planet_digtrans = "Transfer Dignitary";
$l_planet_nocredits1 = "You do not have enough credits for this transaction.  The total cost is ";
$l_planet_nocredits2 = " credits and you only have ";
$l_planet_nobase = "You must have a base to manage the planet defense levels.";
$l_planet_genesisnoturn	 = "You need at least 1 turn to use Genesis Device on planet.";
$l_planet_nogenesis	 = "You need a Genesis Device to destroy a planet.";
$l_planet_wrongclass	 = "This ship class cannot fire a Nova Bomb Device.";

$l_planet_combatpreview	 = "Combat Preview";
$l_planet_beamfire1	 = "Your attack has been detected.  Planetary Beams firing!  Increased Beam Fire as your ship comes in too close to the planet to launch fighters.";
$l_planet_beamfire2	 = "Your attack has been detected.  Planetary Beams firing!  Massive fire rate from the planet as Beam Batteries lock on for multiple hits!";
$l_planet_beamfire3	 = "Your attack has been detected.  Planetary Beams firing!  Beam Batteries all over the planet are locking on for massive multiple fire!  Beam fire much higher than estimated!";
$l_planet_beamfire4	 = "Your attack has been detected.  Planetary Beams firing!  Beam defenses can only lock on for one firing pass.";

$l_planet_sofanobeamsshields	 = " isn't firing beams at your shields.";
$l_planet_sofanobeamsarmor	 = " isn't firing beams at your armor.";
$l_planet_flauncherfailed1	 = "Your fighter launching system has malfunctioned.";
$l_planet_flauncherfailed2	 = "You have only been able to launch ";
$l_planet_flauncherfailed3	 = " percent of your fighters.";
$l_planet_nodfightertofighter	 = " isn't sending any fighters to attack your fighters.";
$l_planet_nodfightertotorp	 = " isn't sending any fighters to attack your torps.";
$l_planet_flauncherfailed3	 = " percent of your fighters.";
$l_planet_autotradetype = "- [source_type] at port [dest_id] ";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "is attacking";
$l_planet_iminsector = "in sector";
$l_planet_imnova = "is using a Nova Device on";
$l_planet_imsofa = "is SOFA Bombing";
$l_planet_team = "This planet is owned by a team mate and you do not have permission to access the information for this planet.";
?>
