<?php
$l_warp_cantsame         = "You can't create a link when the source is the same as the destination.";
$l_warp_twoerror         = "Using a Warp Editor to create a two-way link to sector [target_sector] is not permitted.";
$l_warp_sectex           = "Cannot create warp link from current sector - that would exceed the maximum of $link_max per sector.";
$l_warp_linked           = "Target sector ([target_sector]) already has a link from this sector.";
$l_warp_coneway          = "Link created one-way to";
$l_warp_ctwoway          = "Link created to and from";
$l_warp_nomoney          = "You do not have enough credits to create the warp link.";
$l_warp_noenergy          = "You do not have enough energy to create the warp link.";
?>
