<?php
$l_autotrade_title = "Auto Traderoute Menu";
$l_autotrade_dismiss2 = "Auto Traderoutes Deleted.";
$l_autotrade_report = "Auto Traderoute Report";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energy";
$l_autotrade_capacity = "Capacity";
$l_autotrade_goods = "Goods Price";
$l_autotrade_ore = "Ore Price";
$l_autotrade_organics = "Organics Price";
$l_autotrade_energy = "Energy Price";
$l_autotrade_colonist = "Colonist Price";
$l_autotrade_credits = "Trade Credits";
$l_autotrade_delete = "Delete<br>Route";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "No Route";
$l_autotrade_sector = "Sector";
$l_autotrade_credit2 = "credits";
$l_autotrade_deletebutton = "Delete";
$l_autotrade_noroute2 = "You have not setup any Auto Traderoutes.";
?>
