<?php
$l_new_pwis              = "Your password is";
$l_new_charis            = "Your character name is";
$l_new_title2            = "Create New Player Phase Two";
$l_new_blank             = "E-mail, ship name, and character name may not be blank.";
$l_new_inuse             = "E-mail address [username] is already in use.";
$l_new_forgotpw          = "Forgot your password?";
$l_new_inusechar         = "Character name [character], is already in use.";
$l_new_similar_inusechar = "Your character name sounds too similar to [character], a name already in use.";
$l_new_inuseship         = "Ship name [shipname], is already in use.";
$l_new_similar_inuseship = "Your ship name sounds too similar to [shipname], a name already in use.";
$l_new_pwsent            = "Password has been sent to [username].";
$l_new_err               = "Please try again";
$l_new_topic             = "Alien Assault Traders Password";
$l_new_message           = "Greetings,\n\nSomeone from the IP address $ip requested that your password for Traders be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe Traders web team.";
$l_new_invalidemail             = "Invalid Email Address.";
$l_new_tutorial = "Click here to read the Mini-Tutorial before logging into the game.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login             = "to go to the login screen.";

?>
