<?php
$l_readm_title           = "Read Message";
$l_readm_delete          = "MESSAGE DELETED";
$l_readm_nomessage       = "You have no Messages waiting for you...";
$l_readm_center          = "Message Receiving Center";
$l_readm_sender          = "Message Sender";
$l_readm_captn           = "Captain of the";
$l_readm_del             = "Delete";
$l_readm_repl            = "Reply";
$l_readm_return            = "Click here to return to the main menu";
$l_readm_title2            = "Mail Reader";
$l_readm_delete            = "Delete All";
$l_readm_subject            = "Subject";
$l_readm_quote            = "Quote";
$l_readm_block            = "Block Sender";
$l_readm_alert            = "System Alert";
$l_readm_alertbody            = "Ship Computer";
?>
