<?php
$l_profile_title = "Profile Registration";
$l_profile_notenabled = "Profiles are not enabled on this server.";
$l_profile_registered = "This player is now registered with the Master Profile Server.";
$l_profile_nomatch = "Could not match a profile on the Master Profile Server with the name and server password entered.";
$l_profile_tryagain = "To enter your player profile name and server password again click ";
$l_profile_name = "Profile Player Name";
$l_profile_password = "Profile Server Password";
$l_profile_bannedserver = "This server is not allowed to submit profile information to the Master Profile Server.";
$l_profile_bannedplayer = "You have been banned from the Master Profile Server and may not register players.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "This server <b><u>REQUIRES</u></b> every new player to have a registered profile.  You will not be allowed to create a new player unless you do have a registered profile.";
$l_profile_updated = "Your template, shoutbox and news crawl global settings have been updated on the Profile Master Server.  These settings will automatically be used when you register your profile on any game.";

?>