<?php
$l_sm_title = "Sector Missile Launch";
$l_sm_invalid = "There isn't a warp link between this sector and the destination sector.";
$l_sm_notarg = "Target not in this sector.";
$l_sm_noturn = "You need at least one turn to fire your Sector Missile.";
$l_sm_nosectormissile = "You are not carrying any Sector Missiles.";
$l_sm_noscan = "Sensors cannot get a fix on target!";
$l_sm_flee = "Target out maneuvered the Sector Missile!";
$l_sm_ewd = "Target engaged an emergency warp device when it detected the Sector Missile!";
$l_sm_imtitle = "Ship Under Attack";
$l_sm_imbody = "[playername] is attacking your ship with a Sector Missile!";
$l_sm_sectormissilefail = "The Sector Missile malfunctioned when it hit the enemy ships shield!";
$l_sm_sectormissilefail2 = "The Sector Missile malfunctioned when it hit the enemy ships armor!";
$l_sm_shieldhit = "[target]'s shields are hit for [amount] damage!";
$l_sm_shieldsdown = "[target]'s shields are down!";
$l_sm_armorhit = "[target]'s armor is hit for [amount] damage!";
$l_sm_armorbreached = "[target]'s armor breached!";
$l_sm_targetnoenergy = "The enemy ship doesn't have any energy!  Sector Missile fails!";
$l_sm_attacking = "Attacking [target] aboard the [shipname]";
$l_sm_targetok = "You did not destory [name]'s ship.";
$l_sm_lost = "[target] lost [armor] armor points and [energy] energy units.";
$l_sm_destroyed = "[target]'s ship has been destroyed.";
$l_sm_escapepod = "An escape pod was launched!";
?>
