<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] 		 = "Unchartered space";
$l_zname[2] 		 = "Federation space";
$l_zname[3] 		 = "Alliance space";
$l_zname[4] 		 = "War Zone";

$l_nova 		 = "Nova";
$l_nova 		 = "Nova Bomb";
$l_lssd 		 = "Last ship seen device";
$l_lss 			 = "Last ship seen in this sector";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Use Warp Editor";
$l_warp_turn		 = "You need at least one turn to use a warp editor.";
$l_warp_none		 = "You do not have any warp editors.";
$l_warp_forbid		 = "Using a Warp Editor in this sector is not permitted.";
$l_swarp_forbid		 = "Using a Warp Editor to or from SG sectors is not permitted.";
$l_warp_nosector	 = "Sector does not exist.";

// Not yet confirmed common to multiple files:

$l_yes 			 = "Yes";
$l_no			 = "No";
$l_here			 = "here";
$l_submit		 = "Submit";
$l_reset		 = "Reset";
$l_all			 = "All";
$l_max			 = "Max";

$l_trade		 = "Trade";
$l_ore			 = "Ore";
$l_commodity		 = "Commodity";
$l_commodities		 = "Commodities";
$l_organics		 = "Organics";
$l_goods		 = "Goods";
$l_energy		 = "Energy";
$l_colonists		 = "Colonists";
$l_credits 		 = "Credits";
$l_units		 = "units of ";
$l_special		 = "Special";
$l_upgrade_ports	 = "Upgrades";
$l_device_ports		 = "Devices";
$l_spacedock		 = "Spacedock";
$l_casino		 = "Casino";
$l_dig = "Dignitaries";
$l_spy = "Spies";

$l_cargo		 = "Cargo";
$l_fighters		 = "Fighters";
$l_mines		 = "Mines";
$l_torps		 = "Torpedoes";

$l_none			 = "None";
$l_unnamed		 = "Unnamed";
$l_name			 = "Name";
$l_unowned		 = "Unowned";
$l_unknown		 = "Unknown";
$l_clickme 		 = "Click here";
$l_player  		 = "Player";
$l_ship			 = "Ship";
$l_ships		 = "Ships";
$l_set			 = "set";
$l_realspace		 = "Realspace";
$l_armorpts		 = "Armor points";
$l_links		 = "Links";
$l_login_email          = "E-mail Address:";
$l_add			 = "Add";
$l_teamforum			 = "Team Forum";
$l_teamships			 = "Team Ships";
$l_tutorial			 = "Tutorial/Help";
$l_avatar			 = "Avatar";
$l_teamicon			 = "Team Icon";
$l_debris			 = "Debris";
$l_localmap			 = "Local Map";
$l_arm_weap              = "Armor & Weapons";
$l_3dmap			 = "3D Galaxy Map";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Space Probes";
$l_warpeditors = "Warp Editors";
$l_genesistorps = "Genesis Torpedoes";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Mines/Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Reports";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Maps";
$l_messages = "Messages";
$l_shiptype = "Ship Type";
$l_help = "Help";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Team defenses";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet defenses";
$l_changeproduction = "Change Production";
$l_galacticarm = "Galactic Arm";

$l_armor		 = "Armor";
$l_news_none             = "Sorry, no news today.";

$l_ranks_good            = "Good";
$l_ranks_evil            = "Evil";
$l_ranks_neutral       = "Neutral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone        ="Zone is now a War Zone!";
$l_global_nzone          ="Zone is a neutral zone.";
$l_global_team           ="Zone now belongs to team";
$l_global_player         ="Zone now belongs to player";
$l_global_nochange       ="Zone ownership didn't change";
$l_insignia[0]           = "1c.png";
$l_insignia[1]           = "2c.png";
$l_insignia[2]           = "3c.png";
$l_insignia[3]           = "4c.png";
$l_insignia[4]           = "o-1.png";
$l_insignia[5]           = "o-2.png";
$l_insignia[6]           = "o-3.png";
$l_insignia[7]           = "o-4.png";
$l_insignia[8]           = "o-5.png";
$l_insignia[9]           = "o-6.png";
$l_insignia[10]          = "o-7.png";
$l_insignia[11]          = "o-8.png";
$l_insignia[12]          = "o-9.png";
$l_insignia[13]          = "o-10.png";
$l_insignia[14]          = "o-11.png";
$l_insignia[15]          = "o-12.png";
$l_insignia[16]          = "o-13.png";
$l_insignia[17]          = "o-14.png";
$l_insignia[18]          = "o-15.png";
$l_insignia[19]          = "o-16.png";

$l_insignia_name[0]           = "Spaceman Recruit";
$l_insignia_name[1]           = "Spaceman Apprentice";
$l_insignia_name[2]           = "Spaceman";
$l_insignia_name[3]           = "Petty Officer Third Class";
$l_insignia_name[4]           = "Petty Officer Second Class";
$l_insignia_name[5]           = "Petty Officer First Class";
$l_insignia_name[6]           = "Chief Petty Officer";
$l_insignia_name[7]           = "Senior Chief Petty Officer";
$l_insignia_name[8]           = "Master Chief Petty Officer";
$l_insignia_name[9]           = "Ensign";
$l_insignia_name[10]          = "Lieutenant Junior Grade";
$l_insignia_name[11]          = "Lieutenant";
$l_insignia_name[12]          = "Lieutenant Commander";
$l_insignia_name[13]          = "Commander";
$l_insignia_name[14]          = "Captain";
$l_insignia_name[15]          = "Rear Admiral (lower half)";
$l_insignia_name[16]          = "Rear Admiral (upper half)";
$l_insignia_name[17]          = "Vice Admiral";
$l_insignia_name[18]          = "Admiral";
$l_insignia_name[19]          = "Fleet Admiral";

$l_main_title            = "Main Menu";
$l_main_warpto           = "Warp to";
$l_main_autoroute        = "Autoroute to";
$l_main_rs_to            = "RSMove to";
$l_main_other            = "Other";
$l_main_shipyard1        = "Shipyard";
$l_main_shipyard2        = "Access the ";
$l_traderoutes           = "Trade Routes";
$l_trade_control         = "Trade Control";
$l_youhave               = "You have ";
$l_turns_used            = "Turns used: ";
$l_turns_have            = "Turns available: ";
$l_score                 = "Score: ";
$l_sector                = "Sector";
$l_help                  = "Help";
$l_faq                   = "FAQ";
$l_feedback              = "Feedback";
$l_forums                = "Forums";
$l_logout                = "Logout";
$l_commands              = "Commands";
$l_command_no            = "Command not available.";
$l_devices               = "Devices";
$l_planets               = "Planets";
$l_log                   = "Log";
$l_sector_def            = "Sector defenses";
$l_defense               = "Defenses";
$l_read_msg              = "Read Messages";
$l_send_msg              = "Send Messages";
$l_rankings              = "Rankings";
$l_teams                 = "Teams";
$l_ohno                  = "Self-Destruct";
$l_options               = "Options";
$l_navcomp               = "Nav Computer";
$l_incompletemove        = "You haven't completed your previous move.";
$l_clicktocontinue       = "Click Here to continue";
$l_toplanetmenu          = "to go to the planet menu.";
$l_nonexistant_pl        = "On a non-existent planet???";
$l_abord                 = ", aboard the ";
$l_messages_wait         = " Messages waiting for you.";
$l_no_warplink           = "No warp links";
$l_scan                  = "scan";
$l_fullscan              = "Full scan";
$l_port                  = "Port";
$l_tradingport           = "Trading port";
$l_planet_in_sec         = "Planets in sector ";
$l_ships_in_sec          = "Other ships in sector ";
$l_sector_0              = "There is so much traffic in Sol that you cannot even isolate other ships!";
$l_map                   = "Map";
$l_probe				 = "Probes";
$l_autotrade				 = "Autotrades";
$l_onboard				 = "onboard a";
$l_classship = "class ship";
$l_traveled = "traveled to sector";
$l_max_planets = "Maximum habital planets";
$l_block_msg              = "Block Messages";
$l_sectorinfo               = "Sector Info";
$l_add_note="Add Note";
$l_view_note="View";
$l_notes="Notes";
$l_global_limitreached="You have reached the limit for the amount of time you are allowed to be online each day.  Log in again tomorrow after midnight.";
$l_onlinetimeleft = "Remaining Time:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Stored Ships";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader's Lobby";

$l_common_prev="Previous Page";
$l_common_next="Next Page";
$l_common_totalpages="Total Pages";
$l_common_selectpage="Select Page: ";
$l_common_page="Page: ";
$l_templatechange = "Would you like to keep this Template?";

$l_im_fed_bounty = "The Federation has placed a bounty on you for attacking such a low ranked player.  The Federation will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_fed_bounty_title = "Federation placed a Bounty on you!";
$l_im_alliance_bounty = "The Alliance has placed a bounty on you for attacking such a low ranked player.  The Alliance will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_alliance_bounty_title = "Alliance placed a Bounty on you!";
$l_instant_messages_waiting = "You have [count] messages waiting for you.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds Filled: ";
$l_hold_space_free = "Holds Empty: ";
$l_port_buys = "Port Buys: ";

?>
