<?php
$l_att_title             = "Attack Ship";
$l_att_notarg            = "Target not in this sector.";
$l_att_noturn            = "You need at least one turn to attack.";
$l_att_noatt             = "Attacking someone in this sector is not permitted.";
$l_att_flee              = "Target out maneuvered you!";
$l_att_ewd               = "Target engaged an emergency warp device when attacked!";
$l_att_att               = "Attacking ";
$l_att_beams             = "Beam Exchange";
$l_att_torps             = "Torpedo Exchange";
$l_att_fighters          = "Fighter Exchange";
$l_att_lost              = "lost";
$l_att_ylost             = "You lost";
$l_att_sdown             = "'s shields are down!";
$l_att_ydown             = "Your shields are down!";
$l_att_shits             = "'s shields are hit for";
$l_att_yhits             = "Your shields are hit for";
$l_att_dmg               = "damage";
$l_att_sarm              = "'s armor breached!";
$l_att_yarm              = "Your armor has been breached!";
$l_att_ashit             = "'s armor is hit for";
$l_att_ayhit             = "Your armor is hit for";

$l_att_efhit             = "'s fighters are destroyed.";
$l_att_yfhit             = "of your fighters are destroyed.";
$l_att_ethit             = "'s torpedoes are destroyed.";
$l_att_ythit             = "of your torpedoes are destroyed.";
$l_att_of             = "of";
$l_att_lostt             = "lost all torpedoes.";
$l_att_ylostt            = "You lost all torpedoes.";

$l_att_lostf             = "lost all fighters.";
$l_att_ylostf            = "You lost all fighters.";
$l_att_sdest             = "'s ship has been destroyed.";
$l_att_espod             = "An escape pod was launched!";
$l_att_ysalv             = "You salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits.<BR>Your rating changed by [rating_change] points.";
$l_att_andused           = "and used";
$l_att_stilship          = "You did not destory [name]'s ship.";
$l_att_atyou             = "attacked you";
$l_att_and               = "and";
$l_att_yshiplost         = "Your ship has been destroyed!";
$l_att_salv              = "[name] salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits";
$l_att_loosepod		 = "Luckily you have an escape pod!";

$l_att_tnobeams		 = " seams to be out of beam energy.";
$l_att_tnobeamsf		 = " seams to be out of beam energy and cannot attack your fighters.";
$l_att_tnobeamst		 = " seams to be out of beam energy and cannot attack your torpedoes.";
$l_att_tfnoattack		 = " isn't sending any fighters to attack your ship.";
$l_att_tnotorps		 = " seems to be out of torpedoes.";

$l_att_anobeams		 = "You have exhausted your ships beam energy.";
$l_att_anobeamsf		 = "You have exhausted your ships beam energy and cannot attack the enemy fighters.";
$l_att_anobeamst		 = "You have exhausted your ships beam energy and cannot attack the enemy torpedoes.";
$l_att_anofighters		 = "Your ship has exhausted all availible fighters.";
$l_att_anotorps		 = "You have exhausted your availible torpedoes.";
$l_att_imtitle		 = "Ship Under Attack";
$l_att_imbody		 = "is attacking your ship.";

$l_att_luckybeams		 = "Enemy beams overload inflicting";
$l_att_luckyfighters	 = "Enemy fighters make a surprise lightening attack and cause";
$l_att_luckytorps		 = "Enemy torpedoes induce a cascading damage effect causing";
$l_att_luckytimes		 = "times the normal damage!";
?>
