<?php
$l_contact_admin_title          = "Contact Game Administrator";
$l_contact_admin_thanks       = "Thanks for your comment.";
$l_contact_admin_email_alert       = "Please enter a valid email address.";
$l_contact_admin_name_alert       = "Please enter your name.";
$l_contact_admin_comment_alert       = "Please enter your comments.";
$l_contact_admin_name       = "Name";
$l_contact_admin_email       = "E-mail";
$l_contact_admin_comment       = "Question/Comment";
$l_contact_admin_submit       = "Submit Questions/Comments";
$l_contact_admin_close       = "Close Window";
$l_contact_admin_thanks_comment       = "Thanks for your comment or question.  We will address any questions and email you with our response.";

?>
