<?php
$l_footer_one_player_on	= "There is 1 player online.";
$l_footer_players_on_1	= "There are";  
$l_footer_players_on_2	= "Players online: ";
$l_footer_until_update	= "seconds until next update.";
$l_footer_no_players_on = "There are no players online.";

$l_footer_news = "Local FNN News";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = " for help about this page.";
$l_footer_click = "Click";

$l_footer_open_slots = "Maximum Online: ";
$l_footer_onlinereset = "Player Online Time Reset in ";
$l_footer_onlinecountdown = "Player Online Time Countdown: ";
?>
