<?php
$l_md_title              = "Sector defenses";
$l_md_invalid            = "Invalid Sector defense";
$l_md_nolonger           = "The sector defense selected is no longer there.";
$l_md_you                = "you";
$l_md_bmines             = "Your beams destroyed";
$l_md_msgdownerb         = "[name] destroyed [mines] mines in sector [sector].";
$l_md_retr               = "You retrieved";
$l_md_consist            = "This sector defense consists of [qty] [type] owned by [owner].";
$l_md_youcan             = "You can";
$l_md_retrieve           = "Retrieve";
$l_md_attack             = "Attack";
$l_md_attdef             = "Attack the Sector defenses. All sector fighters will retaliate.";
$l_md_noturn             = "You need at least one turn.";
$l_md_nothere            = "You need to be in the same sector as the sector defenses.";
$l_md_notyours           = "Action not permitted. Those sector defenses do not belong to you.";
$l_md_yours              = "You can not attack your own sector defenses.";
?>
