<?php
$l_warp_linkto           = "Links lead from this sector to";
$l_warp_nolink           = "There are no links out of this sector.";
$l_warp_query            = "What sector would you like to create a link to?";
$l_warp_oneway           = "One-way?";            
$l_warp_dest             = "Alternately, you may destroy a link to sector.";
$l_warp_destquery        = "What sector would you like to remove a link to?";
$l_warp_bothway          = "Both-ways";
$l_warp_create          = "Create a warp link between Sector: ";
$l_warp_andsector          = " and Sector: ";
$l_warp_distance          = " with a distance of ";
$l_warp_lightyears          = " lightyears";
$l_warp_delete          = "Delete warp link between Sector: ";
$l_warp_costcreate          = "Cost to create:";
$l_warp_costdelete          = "Cost to delete:";
$l_warp_costenergy          = "Energy needed: ";
$l_warp_twoerror         = "Using a Warp Editor to create a two-way link to sector [target_sector] is not permitted.";
?>