<?php
$l_news_title            = "Universe News";
$l_news_info             = "FNN is among the galaxy's leaders<br>in news and information delivery.<br>Staffed 24 hours, seven days a week by a <br>dedicated staff in FNN's galaxy headquarters <br>in Proxima Centauri and in bureaus galaxywide!";
$l_news_for              = "News for";
$l_news_prev             = "previous day";
$l_news_next             = "next day";
$l_news_none             = "Sorry, no news today.";
$l_news_flash            = "News Flash";
$l_news_end              = "End of news";
$l_news_bestviewed              = "Best viewed in Opera, Safari and IE";
$l_news_fedannouncements              = "Federation Announcements";
$l_news_planetarynews              = "Planetary News";
$l_news_planetshipnews              = "Planetary and Ship News";
$l_news_afteractionnews              = "After Action Combat News";
?>
