<?php
$l_s_yes               = "Yes";
$l_s_no                = "No";
$l_s_enabled           = "Enabled";
$l_s_disabled          = "Disabled";

$l_s_modules           = "Modules";
$l_s_modulename        = "Module Name";
$l_s_moduleauthor      = "Author";
$l_s_moduleinfo        = "Info";
$l_s_nomodules         = "No Modules Loaded";

$l_s_gamestatus        = "Game Status";
$l_s_allowpl           = "Allow Players";
$l_s_allownewpl        = "Allow New Players";

$l_s_gameoptions       = "Game Options";
$l_s_allowteamplcreds  = "Allow Team Planet Credit Transfer";
$l_s_allowfullscan     = "Allow Full Long Range Scan";
$l_s_sofa              = "Allow Sub-Orbital Fighter Attacks";
$l_s_showpassword      = "Display Password on Registering";
$l_s_genesisdestroy    = "Genesis torps can destroy planets";
$l_s_igb               = "Intergalactic Bank (igb)";
$l_s_ksm               = "Known Space Maps";
$l_s_navcomp           = "Navigation Computer";
$l_s_newbienice        = "Newbie Nice";
$l_s_spies             = "Spy System";
$l_s_spycapture        = "Allow Spies to capture planets";

$l_s_gamesettings      = "Game Settings";
$l_s_gameversion       = "Game version:";
$l_s_minhullmines      = "Minimum hull size needed to hit mines";
$l_s_averagetechewd    = "Averaged Tech level When Emergency Warp Degrades";
$l_s_numsectors        = "Number of Sectors";
$l_s_maxwarpspersector = "Maximum Links per sector";
$l_s_averagetechfed    = "Maximum average tech level for Federation Sectors";
$l_s_igbirateperupdate = "igb Interest rate per update";
$l_s_igblrateperupdate = "igb Loan rate per update";
$l_s_techupgradebase   = "Tech Level upgrade for Bases";
$l_s_collimit          = "Colonists Limit";
$l_s_maxturns          = "Maximum number of accumulated turns";
$l_s_maxplanetssector  = "Maximum number of planets per sector";
$l_s_maxtraderoutes    = "Maximum number of traderoutes per player";
$l_s_colreprodrate     = "Colonist Birth Rate";
$l_s_energyperfighter  = "Unit of Energy used per sector fighter";
$l_s_secfighterdegrade = "Sector fighter degradation percentage rate";
$l_s_planetinterest    = "Planet interest rate";
$l_s_spiesperplanet    = "Maximum number of spies per planet ";
$l_s_spysuccessfactor  = "Spy success factor";
$l_s_spykillfactor     = "Spy kill factor";
$l_s_colsperfighter    = "Colonists needed to produce 1 Fighter each turn";
$l_s_colspertorp       = "Colonists needed to produce 1 Torpedo each turn";
$l_s_colsperore        = "Colonists needed to produce 1 Ore each turn";
$l_s_colsperorganics   = "Colonists needed to produce 1 Organics each turn";
$l_s_colspergoods      = "Colonists needed to produce 1 Goods each turn";
$l_s_colsperenergy     = "Colonists needed to produce 1 Energy each turn";
$l_s_colspercreds      = "Colonists needed to produce 1 Credits each turn";
$l_s_colsper      = "Colonists needed to produce 1 [commodity] each turn";

$l_s_gameschedsettings = "Game Scheduler Settings";
$l_s_schedtype         = "Scheduler Type";
$l_s_cronbased         = "Cron Based";
$l_s_playertriggered   = "Player Triggered";
$l_s_minutes           = " minutes";
$l_s_ticksupdate       = "Ticks happen every";
$l_s_turnsupdate       = "Turns will happen every";
$l_s_npcupdate       = "The Alliance will play every";
$l_s_igbturnsupdate    = "Interests on igb accounts will be accumulated every ";
$l_s_newsupdate        = "News will be generated every";
$l_s_planetupdate      = "Planets will generate production every";
$l_s_spyupdate         = "Spies will act every";
$l_s_portsupdate       = "Ports will regenerate every";
$l_s_towupdate         = "Ships will be towed from fed sectors every";
$l_s_scoreupdate       = "Rankings will be generated every";
$l_s_secdefdegrupdate  = "Sector defenses will degrade every";
$l_s_apocalypseupdate  = "The planetary apocalypse will occur every";
$l_s_release_version   = "Game release version";
$l_s_time_since_reset  = "Time since last reset";
$l_s_independence   = "Planetary Independance";
$l_s_dignitaryupdate   = "Dignitaries will act every";

$l_s_turnsupdate   = "turns every";
?>
