<?php
$l_opt2_title            = "Save Options";
$l_opt2_passunchanged    = "Password was left unchanged.<BR><BR>";
$l_opt2_srcpassfalse     = "Original password incorrect. Password was left unchanged.<BR><BR>";
$l_opt2_newpassnomatch   = "New password fields do not match. Password was left unchanged.<BR><BR>";
$l_opt2_passchanged      = "Password changed.<BR><BR>";
$l_opt2_passchangeerr    = "Error changing password<BR><BR>";
$l_opt2_userintup        = "User interface setting updated.<BR><BR>";
$l_opt2_userintfail      = "Failed to update user interface setting.<BR><BR>";
$l_opt2_chlang           = "Language has been set to [lang].<p>";
$l_opt2_chtemplate           = "Template has been set to [template].<p>";
$l_opt2_dhtmlup          = "Dynamic html setting updated.<BR><BR>";
$l_opt2_dhtmlfail        = "Failed to update dynamic html setting.<BR><BR>";
$l_opt2_shipnamechanged        = "Shipname changed to [name].<BR><BR>";
$l_opt2_playernamechanged        = "Player Name Changed to [name] and [amount] credits deducted from your ship account.<BR><BR>";
$l_opt2_mapwidth        = "Local and Galaxy Map Width: ";
?>
