<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] hit [chm_roll] mines in sector [chm_sector].";         
$l_chm_youlostminedeflectors    = "You lost [chm_roll] mine deflectors.";
$l_chm_youlostallminedeflectors = "You lost all your mine deflectors.";
$l_chm_youhadnominedeflectors  = "You had no mine deflectors.";
$l_chm_yourshieldshitforminesdmg        = "Your shields are hit for [chm_mines_left] damage.";
$l_chm_yourshieldsaredown       = "Your shields are down!";
$l_chm_youlostallyourshields    = "You lost all your shields!";
$l_chm_yourarmorhitforminesdmg  = "Your armor is hit for [chm_mines_left] damage.";
$l_chm_yourhullisbreached       = "Your hull is breached!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] was destroyed by your mines in sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Your ship has been destroyed!";
$l_chm_luckescapepod     = "Luckily you have an escape pod!";

$l_chm_yourdeflectormalf1		 = "Mine Deflector launching system has malfunctioned.";
$l_chm_yourdeflectormalf2		 = "You have only been able to launch ";
$l_chm_yourdeflectormalf3		 = " percent of your mine deflectors.";
$l_chm_enemytorpfailshields     = " hasn't launched any torpedoes against your shields.";
$l_chm_enemytorpfailarmor     = " hasn't launched any torpedoes against your armor.";

$l_chm_minemalf1		 = "Enemy Mines have malfunctioned.";
$l_chm_minemalf2		 = "Only ";
$l_chm_minemalf3		 = " percent of the mines attacking found your ship.";

$l_chm_youhitsomemines   = "You hit [chm_roll] mines out of [total_mines] mines!";
$l_chm_yourdeflectormalf2a		 = "You have only been able to launch [deflectors] percent of your mine deflectors.";
$l_chm_mines_destroyed		 = "[number] of [target] mines have been destroyed!";
$l_chm_mine_deflectors_left		 = "You have [number] mine deflectors left.";
$l_chm_mines_left		 = "There are [number] mines left and they are impacting upon your armor!";
$l_chm_minemalf2a		 = "Only [deflectors] percent of the mines attacking found your ship.";
$l_chm_mines_exhausted		 = "[player] Mines Exhausted!";
$l_chm_armor_left		 = "You have [number] armor points left!";

?>
