<?php
$l_opt_title             = "Select an Avatar";
$l_opt_errorsize            = "Error: Your image must not be larger than 64x64 pixels in size.";
$l_opt_errortype           = "Error: Image must be JPG, GIF or PNG";
$l_opt_errornographic           = "Error: no graphic selected.";
$l_opt_currentavatar         = "Your Current Avatar";
$l_opt_uploadavatar           = "Upload an Avatar";
$l_opt_directory            = "Select Avatar Directory";
$l_opt_change              = "Change Directory";
$l_opt_select              = "Select Avatar";
$l_opt_inuse              = "All Avatars in this directory are in use.";
$l_opt_uploadtypes           = "(GIF, JPG, PNG)";
?>
