<?php
$l_ze_title              = "Edit Zone";
$l_ze_notowner           = "You are not owner of this zone so you can't edit it.";
$l_ze_name               = "Zone name";
$l_ze_allow              = "Allow";
$l_ze_attacks            = "Allow attacking other ships";
$l_ze_genesis            = "Allow creating new planets";
$l_ze_return             = "to return to the zone information page";
$l_ze_saved              = "Your changes have been saved.";
$l_ze_namematch = "ERROR: The Zone Name you provided is similar or matches an existing Zone Name.";
?>
