<?php
$l_casino_title	=	"Casino";
$l_casino_welcome	=	"Welcome to the Casino, we currently offer the following Games and Facilities";
$l_casino_option	=	"Rooms";
$l_casino_detail	=	"Description";

// Blackjack
$l_bet		=	"Bet";
$l_stand	=	"Stand";
$l_hit		=	"Hit";
$l_firsthand		=	"First Hand";
$l_secondhand		=	"Second Hand";
$l_insurance = 	"Insurance";
$l_doubledown = "Double Down";
$l_lobby	=	"Lobby";
$l_split 	=   "Split";
$l_credits  =   "Credits";
$l_yourbet	=	"Your Bet";
$l_nobet	=	"Your bet has exceeded your credit limit, please bet again.";
$l_dealerwins = "Dealer Wins!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer Loses!";
$l_dealerblackjack ="Dealer Blackjack!";
$l_push		= "PUSH";
$l_playerwins	=	"Player Wins!";
$l_playerbust	=	"Player Busts!";
$l_playerloses	=	"Player Loses!";
$l_playerblackjack	=	"Player BlackJack!";
$l_place_bet	=	"Place your bet";
?>