<?php
$l_chf_youretreatback    = "You retreat back to your previous location";
$l_chf_movefailed        = "Move failed.";
$l_chf_thefightersdetectyou     = "The fighters detect you!";
$l_chf_therearetotalfightersindest      = "There are [chf_total_sector_fighters] fighters in your destination sector.";
$l_chf_youcanretreat     = "<B>Retreat</B> - Will cost an extra turn.";
$l_chf_inputfight        = "<B>Fight</B> - You must defeat all the fighters to enter the sector.";
$l_chf_inputcloak        = "<B>Cloak</B> - Use your cloaking device and try to avoid the fighters.";
$l_chf_go                = "Go";
$l_chf_inputrun        = "<B>Attack and Run</B> - You do a lightening attack run and retreat.  But you MAY take some damage during retreat.";
?>
