<?php
$l_sn_title          = "Sector Notes";
$l_sn_pntitle          = "Sectors with Personal Notes";
$l_sn_tntitle          = "Sectors with Team Notes";
$l_sn_psntitle          = "Personal Sector Notes";
$l_sn_tsntitle          = "Team Sector Notes";
$l_sn_editnote          = "Edit Sector Note:";
$l_sn_deleteedit          = "Delete or Edit:";
$l_sn_addnote          = "Add Sector Note:";
$l_sn_list          = "List Sectors Notes";
$l_sn_listts          = "List Sectors with Team Notes";
$l_sn_addteam          = "Add Team";
$l_sn_deleteteam          = "Delete Team";
$l_sn_delete          = "Delete";
$l_sn_saveteam          = "Save Team";
$l_sn_deletepersonal          = "Delete Personal";
$l_sn_addpersonal          = "Add Personal";
$l_sn_savepersonal          = "Save Personal";
$l_sn_editpersonal          = "Edit Personal";
$l_sn_editteam          = "Edit Team";

$l_sn_hdsector			= "Sector";
$l_sn_hdtype			= "Type";
$l_sn_hdowner			= "Owner/Team";
$l_sn_hdplanets			= "Planets";
$l_sn_hdport			="Port";
$l_sn_hdfighters		= "Fighters";
$l_sn_hdmines			= "Mines";
$l_sn_hdscanfrom		= "Scan From";
$l_sn_hddetail			= "Detail";
$l_sn_hddate			="Date/Time";
$l_sn_hddelete			="Delete";
$l_sn_hdteam			="Team";
$l_sn_view				="View";
$l_sn_no				="No";
$l_sn_yes				="Yes";
$l_sn_nonotes			= "No sector Notes Found";

?>
