<?php
$l_sendm_title           = "Send Message";
$l_sendm_to              = "To";
$l_sendm_from            = "From";
$l_sendm_ally            = "Team:";
$l_sendm_subj            = "Subject";
$l_sendm_mess            = "Message";
$l_sendm_send            = "Send";
$l_sendm_sent            = "Message Sent";
$l_sendm_blocked            = " has blocked you from sending messages.";
$l_sendm_blockmanager            = "Message Block Manager";
?>
