<?php
$l_novabomb_turns            = "The Nova Bomb requires atleast [turns] turns to fire.";
$l_novabomb_planetsdamaged            = "Planets damaged by the Nova Bomb";
$l_novabomb_planet            = "Planet [name] suffered damage from the Nova Bomb.";
$l_novabomb_novaexplode   ="Nova Bomb exploded as it was fired and your ship has suffered massive damage.";
$l_novabomb_novaexplode2   ="Nova Bomb exploded as it was fired and your ship was destroyed.";
$l_novabomb_notfedsec   ="Nova Bomb cannot be used on Federation owned sectors.";
$l_novabomb_destroyed_planet = "Your nova bomb cracked the surface of the planet and drilled into the core where it exploded causing the planet to shatter.";
$l_novabomb_wrongclass	 = "This ship class cannot fire a Nova Bomb Device.";
$l_novabomb_nonova   ="You do not have a Nova Bomb installed.";
$l_novabomb_novamiss   ="The Nova Bomb narrowly misses but inflicts damage upon the planet.";
$l_novabomb_success             = "Sector [sector] has been Nova Bombed!";
$l_novabomb_mines            = "Destroyed [mines] sector Mines.";
$l_novabomb_fighters            = "Destroyed [fighters] sector Fighters.";
$l_novabomb_shipsdamaged            = "Ships damaged by the Nova Bomb";
$l_novabomb_ship_damage            = "Starship [shipname] suffered damage from the Nova Bomb.";
$l_novabomb_ship_survived            = "Your ship was far enough away when the Nova Bomb exploded to avoid any damage.";
?>
