<?php
$l_cu_storing   = "Storing ";
$l_cu_inistored          = "<b>All ini values have been successfully stored.</b><p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id       = "Auto Route ID";
$l_cu_start       = "Auto Route Start";
$l_cu_destination       = "Auto Route Destination";
$l_cu_warps       = "Auto Route Warps";
$l_cu_deleteroute       = "Delete Route";
$l_cu_info       = "Click on the Start Sector to Realspace to that sector and start warping to the destination sector.";
$l_cu_delete2       = "Delete Routes";
$l_cu_noroutes       = "No Auto Routes";
$l_cu_createroute       = "Create New Auto Route";
$l_cu_deleted       = "Auto Routes deleted.";
$l_cu_return       = "Return to Auto Route Menu click";
$l_cu_created       = "Auto Route has been created.";
$l_cu_realmove       = "Realspace move to sector";
$l_cu_warpmove       = "Warp move to next sector";
$l_cu_warpfinal       = "Warp move to final sector";
?>
