<?php
$l_warp_unlinked         = "Target sector ([target_sector]) does not have a link from this sector.";
$l_warp_forbidtwo        = "Using a Warp Editor to remove a two-way link to sector [target_sector] is not permitted.";
$l_warp_removed          = "Link removed to";
$l_warp_removedtwo       = "Link removed to and from";
$l_warp_nomoney          = "You do not have enough credits to delete the warp link.";
$l_warp_noenergy          = "You do not have enough energy to delete the warp link.";
?>
