<?php
$l_login_title			= "Login";
$l_login_pw			= "Password:";
$l_login_chooseres		= "Unable to determine your screen resolution. Please choose the best fit:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs			= "Problems?";   
$l_login_emailus		= "E-mail us";
$l_login_forgot_pw		= "Forgot your password?  Enter it blank and press login.";
$l_login_settings 		= "Game Settings";
$l_login_change			= "Change";
$l_login_title2			= "Main Login for AATraders";
$l_login_reset1			= "No Reset Scheduled";
$l_login_reset2			= "Scheduled Reset: ";
$l_login_reset3			= "Sched Reset: ";
$l_login_notice			= "Important Notice:";
$l_login_endadminnews			= "End of Admin News";
$l_login_tourney_signup = "Tournament Signups Enabled";

$l_login_profile_only		= "Profile Only";       
$l_login_newclosed_message		= "New Signups Closed";                
$l_login_tourneymode		= "Tournament Running";                
$l_login_tourneystarts		= "Starts: ";                
?>
