<?php
$l_by_title              = "Bounties";
$l_by_noturn             = "You need at least one turn to place or modify a bounty.";
$l_by_amount             = "Bounty Amount";
$l_by_place              = "Place Bounty";
$l_by_nobounties         = "There are currently no bounties.";
$l_by_bountyon           = "Bounty On";
$l_by_placedby           = "Placed by";
$l_by_thefeds            = "The Federation";
$l_by_cancel             = "Cancel";
$l_by_yourself           = "You can not place a bounty on your self.";
$l_by_notenough          = "You do not have enough credits to place a bounty of that amount.";
$l_by_toomuch            = "You can not place that bounty. Maximum bounty allowed on another player is [percent] percent of your net worth";
$l_by_zeroamount         = "Bounties must be greater than 0 credits.";
$l_by_placed             = "The bounty has been placed.";
$l_by_nobounty           = "That bounty no longer exists.";
$l_by_notyours           = "That bounty was not placed by you.";
$l_by_canceled           = "The bounty has been canceled.";
$l_by_action             = "Action";
$l_by_placebounty        = "Place or view bounties.";
$l_by_moredetails        = "Click on the name for more details.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists          = "The player you are putting the bounty on does not exist.";
$l_by_destroyed          = "You can not place a bounty on a player with a destroyed ship.";
$l_by_nofedbounty		 = "You will not receive a bounty if you attack this players ship or planet.";
$l_by_fedcollectonly		 = "Only Federation can Collect Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy		 = "You will not receive a bounty if you place a spy on this players planet.";
$l_pay_partial = "Make Partial Payment";
$l_pay_button = "Pay";

$l_by_thealliance            = "The Alliance";
$l_by_alliancecollectonly		 = "Only the Alliance can Collect Bounty";
$l_by_bountyscan          = "Bounty";
?>
