<?php
// New News Items

$l_news_planets		 = " planets";
$l_news_cols		 = " Million colonists";
$l_news_p_headline 	 = "[player]'s Empire now has [total] planets";
$l_news_c_headline 	 = "[player]'s Empire now has [total] million colonists";
$l_news_p_textXX	 = "The Federation has issued warnings concerning the Empire of [name].  [name] has control of [total] planets and should be considered very dangerous.  All sectors should increase sector defenses immediately.";
$l_news_c_textXX	 = "The Empire of [name] is experiencing massive overcrowding on all planets with over [total] million colonists.  Food shortages may cause unrest.  All sectors should be aware of possible aggressive actions by [name] in the future.";

$l_created_universe             = 'Universe Creation';
$l_created_universe_full        = 'Scientists researching the beginnings of the Universe have unanimously decided that today is the  most statistically likely day for Universe Creation to have taken place';

$l_news_p_text5		 = "The rising empire of [name] now has five planets, the FNN will watch the actions of [name] more closely in the future!";
$l_news_p_text10	 = "The growing empire of [name] now controls ten planets, Reports of FNN say that further expansion of [name] might lead to war!";
$l_news_p_text25	 = "The huge empire of [name] colonized 25 planets already, in an interview, [name] announced that he might consider slowing down his expansion in the future!";
$l_news_p_text50	 = "The enormous vast empire of [name], represented by 50 planets in the whole galaxy is getting a threatening strength. One of the FNN reporters found out that [name] is upgrading his ship planning a major war. In an interview [name] announced that is done on defense purpose only!";
$l_news_c_text25	 = "The rising empire of [name] now has 25 million colonists, the FNN will watch the actions of [name] more closely in the future, but its highly obvious that birthrates are going to explode!";
$l_news_c_text100	 = "The aspiring empire of [name] now has 100 million colonists, after an explosion of birth rates, [name] colonies seemed to be a good place for families to settle!";
$l_news_c_text500	 = "The large empire of [name] now has 500 million colonists, [name] said in an interview that colonization of the galaxy has just yet begun";
$l_news_c_text1000	 = "The humongous empire of [name] now has one billion colonists, FNN reporters found out that [name] is in possesion of some weird cloning mechanism allowing him to breed new colonists in huge amounts. With this amount of colonists, the econmic strength of this empire is enormous, FNN hopes that [name] does not spend his money on warfare";

$l_news_indi_short	 = "FNN Rumor: over [planets] declare independance.";
$l_news_indi	 = "FNN has it on good authority that over [planets] planets have decided that they are better ruled by themselves and have become independant.";

$l_news_nova_short	 = "FNN Report: [name] uses Nova Bomb.";
$l_news_nova	 = "FNN has breaking news that [name] has used the feared Nova Bomb [total] time(s) to destroy a planet and all ships on it.";
$l_news_nova_m_short	 = "FNN Report: [name] uses Nova Bomb and misses.";
$l_news_nova_m	 = "FNN has breaking news that [name] has used the feared Nova Bomb [total] time(s) to try and destroy a planet.  The Nova Bomb blew up outside the planets atmosphere and caused massive damage to the planetary infrastructure.";

$l_news_bounty	 = "FNN Report: [name] places a [amount] credit bounty on [name2].";

$l_news_attackerpod_p_short	 = "FNN Report: [name]'s ship is destroyed.";
$l_news_attackerpod_P	 = "[name]'s ship was destroyed while attacking a planet.  Fortunately [name] had an Escape Pod and survived.";

$l_news_attackerdie_p_short	 = "FNN Report: [name] dies!";
$l_news_attackerdie_p	 = "[name]'s ship was destroyed while attacking a planet and they were killed because they failed to purchase an Escape Pod.";

$l_news_destroyed_p_short	 = "FNN Report: [name] attacks and destroys a planet!";
$l_news_destroyed_p	 = "[name] attacked [total] planet(s) owned by [owner] and the population of each planet destroyed the planet to prevent it being captured!";

$l_news_defeated_p_short	 = "FNN Report: [name] attacks and defeats a planet!";
$l_news_defeated_p	 = "[name] attacked [total] planet(s) owned by [owner] and defeated the planetary defense forces!";

$l_news_notdefeated_p_short	 = "FNN Report: [name] attacks a planet and loses!";
$l_news_notdefeated_p	 = "[name] attacked [total] planet(s) owned by [owner] and the planetary defenses held against the relentless attacks!";

$l_news_targetepod_short	 = "FNN Report: [name] attacks a [owner] and wins!";
$l_news_targetepod	 = "[name] attacked [owner]'s ship and destroyed it completely.  Fortunately [owner] had equiped their ship with an Escape Pod and they survived.";

$l_news_targetdies_short	 = "FNN Report: [name] attacks a [owner] and kills them!";
$l_news_targetdies	 = "[name] attacked [owner]'s ship and destroyed it completely.  Sadly [owner] didn't equiped their ship with an Escape Pod and they were vaporized.";

$l_news_fedcolbounty_short	 = "FNN Report: The Federation cracks down on [name]!";
$l_news_fedcolbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which inflicted [amount] credits worth of damage on the pirate's vessel.  Federation officials promise further such actions in the future!";

$l_news_alliancecolbounty_short	 = "FNN Report: The Alliance cracks down on [name]!";
$l_news_alliancecolbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which inflicted [amount] credits worth of damage on the pirate's vessel.  Alliance officials promise further such actions in the future!";

$l_news_fedcol_pbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_pbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_pbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_pbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Alliance officials promise further such actions in the future!";

$l_news_fedcol_sbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_sbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated a ship ([shiptype]) worth [cost] in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_sbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_sbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated a ship [shiptype] worth [cost] in sector [sector].  Alliance officials promise further such actions in the future!";

$l_killheadline		 ="[target] was killed in an accident";
$l_news_killed 		 = "[target] was killed in a tragic accident today. How heroic - [target] was the last member on board of his ship, when he noticed there was no escape pod left for him. May he rest in peace!";

$l_killSDheadline		 ="[target] was killed by Sector Defenses.";
$l_news_killedSD 		 = "[target] was killed by an overwhelming number of Sector Defenses owned by [killer]! Sadly, the ship was not equipped with an escape pod.";

$l_killplanetheadline		 ="[target] was killed attacking a planet.";
$l_news_killedplanet 		 = "[target] was killed while attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killshipheadline		 ="[target] was killed ship combat.";
$l_news_killedship 		 = "[target] was killed in ship to ship combat with [killer] today. The captain apparently forgot to equip the ship with an escape pod.";

$l_killsuicideheadline		 ="[target] commited suicide.";
$l_news_killedsuicide 		 = "[target] committed suicide today.  They took the cowards way out because they lacked the ability or courage to stand up to the pressures of commanding their own ship.";

$l_killsofaheadline		 ="[target] was killed sofa attacking a planet.";
$l_news_killedsofa 		 = "[target] was killed while sofa attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovaheadline		 ="[target] was killed during a nova attack.";
$l_news_killednova 		 = "[target] was killed by [killer] during a nova bomb attack today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovabackfireheadline		 ="[target] was killed from a nova backfire.";
$l_news_killednovabackfire 		 = "[target] was killed when their nova bomb backfired today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killsectormissileheadline		 ="[target] was killed from a Sector Missile.";
$l_news_killedsectormissile 		 = "[target] was killed when a Sector Missile from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killhunterprobeheadline		 ="[target] was killed from a Hunter Probe.";
$l_news_killedhunterprobe 		 = "[target] was killed when a Hunter Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killtrapprobeheadline		 ="[target] was killed from a Sentry Trap Probe.";
$l_news_killedtrapprobe 		 = "[target] was killed when a Sentry Trap Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

//-------------------

$l_killpodheadline		 ="[target]'s ship was destroyed in an accident";
$l_news_killedpod 		 = "[target]'s ship was destroyed in a tragic accident today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killSDpodheadline		 ="[target]'s ship was destroyed by Sector Defenses.";
$l_news_killedSDpod  		 = "[target]'s ship was destroyed by an overwhelming number of Sector Defenses owned by [killer]! An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killplanetpodheadline		 ="[target]'s ship was destroyed attacking a planet.";
$l_news_killedplanetpod  		 = "[target]'s ship was destroyed while attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killshippodheadline		 ="[target]'s ship was destroyed in ship combat.";
$l_news_killedshippod  		 = "[target]'s ship was destroyed in ship to ship combat with [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsofapodheadline		 ="[target]'s ship was destroyed while sofa attacking a planet.";
$l_news_killedsofapod  		 = "[target]'s ship was destroyed while sofa attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovapodheadline		 ="[target]'s ship was destroyed during a nova attack.";
$l_news_killednovapod  		 = "[target]'s ship was destroyed by [killer] during a nova bomb attack today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovabackfirepodheadline		 ="[target]'s ship was destroyed from a nova backfire.";
$l_news_killednovabackfirepod  		 = "[target]'s ship was destroyed when their nova bomb backfired today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsectormissilepodheadline		 ="[target]'s ship was destroyed by a Sector Missile.";
$l_news_killedsectormissilepod 		 = "[target]'s ship was destroyed when a Sector Missile from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killhunterprobepodheadline		 ="[target]'s ship was destroyed by a Hunter Probe.";
$l_news_killedhunterprobepod 		 = "[target]'s ship was destroyed when a Hunter Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killtrapprobepodheadline		 ="[target]'s ship was destroyed by a Sentry Trap Probe.";
$l_news_killedtrapprobepod 		 = "[target]'s ship was destroyed when a Sentry Trap Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

// --------------------------

$l_news_promotedheadline		 ="[name] has been promoted to [rank]";
$l_news_promoted 		 = "The Federation is pleased to announce the promotion of [name] to the rank of [rank].";

$l_news_demotedheadline		 ="[name] has been demoted to [rank]";
$l_news_demoted 		 = "The Federation regrets to announce the demotion of [name] to the rank of [rank].";

$l_news_namechangedheadline		 ="[oldname] changed name to [newname]";
$l_news_namechanged 		 = "[oldname] applied to the Federation Review Board to change their name to [newname].  The Federation has granted the name change.  From this day forward [oldname] shall now be known as [newname].  All ships and planets should update their records immediately.";

$l_news_found_planets_short	 = "Federation Survey: [found_planets] new planets located.";
$l_news_found_planets	 = "Federation Survey Scouts have located [found_planets] new planets in recently discovered sectors.";

$l_news_new_ports_short	 = "Federation Survey: [new_ports] new ports constructed.";
$l_news_new_ports	 = "Federation Engineers have constructed [new_ports] new ports in recently discovered sectors.";

$l_news_addedsectors_short	 = "Federation Survey: [addedsectors] sectors discovered.";
$l_news_addedsectors	 = "Federation Survey Scouts have discovered [addedsectors] new sectors.  Caution is advised.";

$l_news_artifactheadline		 ="[playername] completed [artifact]";
$l_news_artifact 		 = "[playername] has found all of the pieces of the [artifact] and has all of the power it can provide.";

$l_news_artifactfoundheadline		 ="[playername] found [artifact] piece";
$l_news_artifactfound 		 = "[playername] has found one of the pieces of the [artifact] and needs [pieces] more [piece].";

?>