<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Probe Levels";
$l_probe_engine = "Engine";
$l_probe_sensors = "Sensors";
$l_probe_cloak = "Cloak";
$l_probe_title		 = "Space Probe Menu";
$l_probe_none		 = "You are not in the same sector as this probe, so you can't interact with it.";

$l_probe_named		 = "Welcome to Probe Number [probename], owned by [name], located in sector [sector].";
$l_probe_orders	 = "[orders] Probe to search universe";
$l_probe_orders_link= "Program";
$l_probe_upgrade	 = "[upgrade] Probe Sensors/Engine/Cloak";
$l_probe_upgrade_link	 = "Upgrade";
$l_probe_pickup	 = "[pickup] Probe for later placement";
$l_probe_pickup_link	 = "Pickup";
$l_probe_update	 = "Update";

$l_probe_att_link	 = "Attack";
$l_probe_att		 = "[attack] on probe";
$l_probe_att_sure	 = "Are you SURE...";
$l_probe_scn_link	 = "Scan";
$l_probe_scn		 = "[scan] probe";

$l_probe_unknown		 = "Unknown";
$l_plant_scn_turn	 = "You need at least one turn to scan a probe.";
$l_probe_noscan	 = "Sensors cannot get a fix on target!";
$l_probe_logscanA	 = "[name] attempted to scan one of your probes in sector [sector], but failed.";
$l_probe_logscanB	 = "One of your probes in sector [sector] was scanned by [name].";
$l_probe_scn_report	 = "Scan results on [name], owned by:  [owner]";

$l_probe_caplog	 = "Your probe '[probename]' in sector [sector] was captured by [name].";
$l_probe_scan  = "Probe scans sector [sector] and finds:";
$l_probe_destroyprobe  = "Destroy probe";
$l_probe_destroyed= "Probe Destroyed!!";
$l_probe_warning 	 = "Doing this will totally destroy this probe";
$l_probe_confirm 	 = "Do you really want to destroy this probe?";
$l_gns_turn ="You do not have enough turns to destroy this probe";
$l_probe_type="Probe Type";
$l_probe_type0="Stationary Probe";
$l_probe_type1="Sentry Probe";
$l_probe_type2="Warp Probe";
$l_probe_type3="Realspace Probe";
$l_probe_type4="Sequential Realspace Probe";
$l_probe_target="Target Sector";
$l_probe_ordered="Probe programmed and will begin searching.";
$l_probe_order2="Probe is a [type] and is targeting sector [target]";
$l_probe_pickedup="Probe picked up and placed in active storage";
$l_probe_title="Probe Menu";
$l_probe_messages = "to see what your spies have detected.";

$l_probe_defaulttitle1 = "Active Probes";
$l_probe_defaulttitle2 = "Probes you have picked up";
$l_probe_defaulttitle3 = "Probes on your planets";
$l_probe_defaulttitle4 = "Probes on your ship";
$l_probe_linkback="to go to the probe menu.";
$l_probe_no1 = "You don't have any active probes.";
$l_probe_no2 = "You don't have any probes in storage.";
$l_probe_no3 = "You don't have any probes on your planets.";
$l_probe_no4 = "You don't have any probes on your ship.";
$l_probe_noprobeatall = "You don't have any probes.";
$l_probe_notknown = "Unknown";
$l_probe_launch="Drop";
$l_probe_detect="Detected";
$l_probe_codenumber = "Code";
$l_probe_job = "Job";
$l_probe_percent = "Percent";
$l_probe_move = "Movement";
$l_probe_view= "View";
$l_probe_action = "Action";
$l_probe_shipowner = "Ship Owner";
$l_probe_shipname = "Ship Name";
$l_probe_shiptype = "Ship Class";
$l_probe_shiplocation = "Ship Location";
$l_probe_planetowner = "Planet Owner";
$l_probe_planetname = "Planet";
$l_probe_sector = "Current Sector";
$l_probe_tsector = "Target Sector";
$l_probe_type="Probe Type";
$l_probe_forbid="You can not drop probes in this sector";

$l_probe2_title             = "Launch Space Probe";
$l_probe2_turn              = "You need at least one turn to use a space probe.";
$l_probe2_onplanet          = "You can't use this device while on the planet surface.";
$l_probe2_noprobe         = "You do not have any space probes.";
$l_probe2_forbid            = "Launching a probe in this sector is not permitted.";
$l_probe2_launched           = "Space probe launched!";

$l_probe2_warplink           = "Warplink";
$l_probe2_player           = "Player";
$l_probe2_onboarda           = "on board a";
$l_probe2_classship           = "class ship";
$l_probe2_traveled           = "traveled to sector";
$l_probe2_fedjammed           = "Federation is jamming all sensor scans to Sector 1.";
$l_probe2_lastseen           = "Last Ship Seen";
$l_probe2_portfound           = "Port Found";
$l_probe2_supports           = "Supports";
$l_probe2_planets           = "planets";
$l_probe2_sectord           = "Sector defense Detected";
$l_probe2_mines           = "Mines";
$l_probe2_fighters           = "Fighters";
$l_probe2_ships           = "Ships Detected";
$l_probe2_ships2           = "Ship Detected";
$l_probe2_noneowned           = "No planets not owned by you have been detected.";
$l_probe2_warplinks           = "Warplinks";
$l_probe2_nothing           = "Nothing Detected";
$l_probe2_nocredits           = "You do not have enough credits for this transaction.  The total cost is [total] credits and you only have [credits] credits.";

$l_probe_forbidSG = "You cannot send a Realspace type probe into Sector Genesis created sectors.";
$l_probe_forbidFED = "You cannot send a Realspace type probe into Federation or Alliance owned sectors.";
$l_probe_forbidINVALID = "Your destination sector is an invalid sector name.";
?>
