<?php
$l_die_title             = "Self-Destruct";
$l_die_rusure            = "Are you sure you wish to destroy your ship? This will remove you from the game.";
$l_die_goodbye           = "Goodbye cruel galaxy!";
$l_die_check             = "Are you positive that you wish to remove yourself from the game?";
$l_die_nonono            = "NO! NO! NO!";
$l_die_what              = "What was I thinking?";
$l_die_count             = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor             = "You ship and all aboard have been vaporized.";
$l_die_please1           = "logout";
$l_die_please2           = "Please, [logout_link]";
$l_die_exploit           = "Don't play with what you don't understand.";
?>
