<?php
$l_defense_deploy_title           ="Deploy Sector Mines & Fighters";
$l_defense_deploy_noturn          ="You need at least one turn to deploy sector defenses.";
$l_defense_deploy_nopermit        ="Deploying Mines and Fighters in this sector is not permitted.";
$l_defense_deploy_nodeploy        ="Can not deploy here. Another Ship or Team has mines or fighters in this sector.";
$l_defense_deploy_info1           ="You are presently in sector [sector]. There are [mines] mines and [fighters] fighters here.";
$l_defense_deploy_info2           ="You have [mines] mines and [fighters] fighters available to deploy";
$l_defense_deploy_deploy          ="Deploy";
$l_defense_deploy_deployed        ="Deployed";
$l_defense_deploy_att             ="Attack";
$l_defense_deploy_notorps         ="You do not have enough torpedos.";
$l_defense_deploy_nofighters      ="You do not have enough fighters";
$l_defense_deploy_dmines          ="Deployed [mines] mines.";
$l_defense_deploy_dfighter        ="Deployed [fighters] fighters.";
$l_defense_deploy_max_fighters    ="This sector can support a maximum of [amount] fighters.";
$l_defense_deploy_toomanyfighters ="You have tried to deploy more fighters than the sector can support.";
?>
