<?php
$l_mail_title            ="Mail Password";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent             ="Password has been sent to";
$l_mail_topic            ="$game_name Password";
$l_mail_message          ="Greetings,\n\nSomeone from the IP address $ip requested that your password for $game_name be sent to you\n\nYour password is: [pass]\n\nThank you\n\nThe $game_name web team.";
$l_new_login             = "to go to the login screen.";
$l_mail_failed             ="Password failed to send to";
?>
