<?php
$l_zi_title              = "Zone Information";
$l_zi_nexist             = "This section of space does not exist!";
$l_zi_feds               = "Federation";
$l_zi_traders            = "Alliance Space";
$l_zi_nobody             = "Nobody";
$l_zi_war                = "Contested space";
$l_zi_allow              = "Allowed";
$l_zi_notallow           = "Not allowed";
$l_zi_limit              = "Limited to owner and allies";
$l_zi_ul                 = "Unlimited";
$l_zi_control            = "You are in control of this zone";
$l_zi_tochange           = "to change its laws.";
$l_zi_owner              = "Zone owner";
$l_zi_maxhull            = "Maximum average tech level allowed";
?>
