<?php
$l_artifact_title          = "Retrieve Artifact";
$l_artifact_list_title          = "List of Aquired Artifacts";
$l_artifact_noscan   = "Your scanners could not find the artifact.";
$l_artifact_noturn          = "You do not have enough turns to pick up this artifact.";
$l_artifact_classname          = "Artifact Name";
$l_artifact_description          = "Artifact Description";
$l_artifact_imagename          = "Artifact Image";
$l_artifact_incomplete          = "Artifact Pieces";
$l_artifact_process          = "Use the Completed Artifact";

?>
