<?php
$l_beacon_title          = "Deploy Space Beacon";
$l_beacon_notpermitted   = "Deploying space beacons in this sector is not permitted.";
$l_beacon_reads          = "Present beacon reads";
$l_beacon_none           = "There presently isn't a beacon in this sector.";
$l_beacon_enter          = "Enter text for beacon";
$l_beacon_nowreads       = "Beacon now reads";
$l_beacon_donthave       = "You do not have a space beacon.";
?>
