<?php
///SPIES
$l_dig_title = "Dignitary Menu";
$l_dig = "Dignitaries";
$l_dig_disabled = "Dignataries are disabled!";
$l_dig_noturn = "You need at least one turn to send a dignitary to a planet.";
$l_dig_notonboard = "You do not have any dignitary on board.";
$l_dig_ownplanet = "You cannot send a dignitary to an enemy planet.";
$l_dig_unownedplanet = "You cannot send a dignitary to unowned planet.";
$l_dig_planetfull = "There are already allowed [max] dignitaries on that planet.";
$l_dig_sendtitle = "Sending a dignitary [digID] to planet:<BR>Select dignitary's mission:";

$l_dig_codenumber = "Code";
$l_dig_job = "Job";
$l_dig_percent = "Percent";
$l_dig_move = "Movement";
$l_dig_action = "Action";
$l_dig_shipowner = "Ship Owner";
$l_dig_shipname = "Ship Name";
$l_dig_shiptype = "Ship Class";
$l_dig_shiplocation = "Ship Location";
$l_dig_planetowner = "Planet Owner";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sector";

$l_dig_waiting = "Waiting for a Job";
$l_dig_max = "Maximum Per Planet";
$l_dig_legend = "Dignitary Legend";
$l_dig_description = "Dignitary Description";
$l_dig_waiting_description = "Dignitary will create torpedoes and fighters while waiting for a job assignment.";
$l_dig_changeerror = "Dignitary Job Change Report";

$l_dig_nospieshere = "You do not have any dignitaries on this planet!";
$l_dig_transferred = "dignitaries transferred";
$l_dig_backonship = "The dignitary is now on your ship.";
$l_dig_dismiss = "Dismiss the dignitary?";
$l_dig_changebutton = "Change";
$l_dig_notyourplanet = "It is not your planet.";

$l_dig_defaulttitle1 = "Dignitaries on enemy ships";
$l_dig_defaulttitle2 = "Dignitaries on your planets";
$l_dig_defaulttitle3 = "Dignitaries on your planets";
$l_dig_defaulttitle4 = "Dignitaries on your ship";

$l_dig_no1 = "You don't have any dignitaries on enemy ships.";
$l_dig_no2 = "You don't have any dignitaries on your planets.";
$l_dig_no3 = "You don't have any dignitaries on your planets.";
$l_dig_no4 = "You don't have any dignitaries on your ship.";
$l_dig_nodignitaryatall = "You don't have any dignitaries.";
$l_dig_notknown = "Unknown";
$l_dig_dismiss = "Dismiss";
$l_dig_dismiss2 = "Dignitaries dismissed.";
$l_dig_menu = "to return to Dignitary Menu.";

?>
