<?php
///SPIES
$l_spy_title = "Spy Menu";
$l_spy = "Spies";
$l_spy_disabled = "Spies are disabled!";
$l_spy_noturn = "You need at least one turn to send a spy to a planet.";
$l_spy_notonboard = "You do not have any spies on board.";
$l_spy_ownplanet = "You cannot send a spy to your own planet.";
$l_spy_unownedplanet = "You cannot send a spy to unowned planet.";
$l_spy_planetfull = "There are already allowed [max] spies on that planet.";
$l_spy_sendtitle = "Sending a spy [spyID] to planet:<BR>Select spy's mission:";
$l_spy_type1 = " The spy acts only on that planet.";
$l_spy_type2 = " The spy tries to infiltrate a ship which performs a planetary transfer.";
$l_spy_type3 = " The spy tries to infiltrate a ship which performs a planetary transfer and then infiltrate to another planet.";
$l_spy_sendbutton = "Send to planet";
$l_spy_sendsuccessful = "Your spy infiltrates the planet and waits for the right moment to start action.";
$l_spy_sendfailed = "Planet's Sensors detected your spy, because your Cloak device couldn't cover him. Your spy is killed.";
$l_spy_noturn2 = "You need at least one turn to call back a spy.";
$l_spy_confirm = "Are you sure you want to call back your spy [spyID]?";
$l_spy_cleanupplanet = "to clean up that planet from enemy spies.";
$l_spy_cleanupship = "If you want to clean up your ship from enemy spies, click";
$l_spy_yourspies = "Your spies on that planet";
$l_spy_sendnew = "Send a new spy";

$l_spy_codenumber = "Code";
$l_spy_job = "Job";
$l_spy_percent = "Percent";
$l_spy_move = "Movement";
$l_spy_action = "Action";
$l_spy_shipowner = "Ship Owner";
$l_spy_shipname = "Ship Name";
$l_spy_shiptype = "Ship Class";
$l_spy_shiplocation = "Ship Location";
$l_spy_planetowner = "Planet Owner";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sector";

$l_spy_moves['none'] = "Doesn't move";
$l_spy_moves['toship'] = "To ship";
$l_spy_moves['toplanet'] = "To planet";

$l_spy_comeback = "Call back";
$l_spy_nospieshere = "You do not have any spies on this planet!";
$l_spy_transferred = "spies transferred";
$l_spy_backonship = "The spy is now on your ship.";
$l_spy_backfailed = "Call back failed.";
$l_spy_changetitle = "Changing spy [spyID] properties:";
$l_spy_occupied = "Your spy [spyID] in employed as a [job], with percent [percent].";
$l_spy_dismiss = "Dismiss the spy?";
$l_spy_changebutton = "Change";
$l_spy_changejob = "Change Job or Movement";
$l_spy_linkback = "to go to the spy menu.";
$l_spy_changed1 = "Movement changed.";
$l_spy_changed2 = "Spy dismissed and his movement changed.";
$l_spy_changefailed = "Change failed.";
$l_spy_cleanupplanettitle = "Cleaning up your planet from enemy spies:";
$l_spy_notyourplanet = "It is not your planet.";
$l_spy_cleanuptext[1] = "Fast cleanup. Uses [creds] credits and [turns] turns.";
$l_spy_cleanuptext[2] = "Better cleanup. Uses [creds] credits and [turns] turns.";
$l_spy_cleanuptext[3] = "The best cleanup. Uses [creds] credits and [turns] turns.";
$l_spy_cannotcleanupplanet = "You have only [credits] credits on that planet and [turns] turns.";
$l_spy_cleanupbutton1 = "Start cleaning up the planet";
$l_spy_cleanupplanettitle2 = "You turned on your Sensors to find enemy spies on that planet.";
$l_spy_spyfoundonplanet = "You found a [player]'s spy [spyID] on the planet. You killed that spy.";
$l_spy_spynotfoundonplanet = "You didn't find any enemy spies on that planet.";
$l_spy_notenough = "You don't have enough credits or turns to start cleanup.";

$l_spy_cleanupshiptitle = "Cleaning up your ship from enemy spies:";
$l_spy_notinspecial = "You need to be at a Devices port to clean up your ship.";
$l_spy_cleanupshiptext[1] = "Fast cleanup. Uses [creds] credits and [turns] turns.";
$l_spy_cleanupshiptext[2] = "Better cleanup. Uses [creds] credits and [turns] turns.";
$l_spy_cleanupshiptext[3] = "The best cleanup. Uses [creds] credits and [turns] turns.";
$l_spy_cannotcleanupship = "You have only [credits] credits and [turns] turns.";
$l_spy_cleanupbutton2 = "Start cleaning up your ship";
$l_spy_cleanupshiptitle2 = "You turned on your Sensors to find enemy spies on your ship.";
$l_spy_spyfoundonship = "You found a [player]'s spy [spyID] on your ship. You killed that spy.";
$l_spy_spynotfoundonship = "You didn't find any enemy spies on your ship.";

$l_spy_infodeleted = "Message deleted";
$l_spy_infonotyours = "It is not your message.";
$l_spy_noinfo = "Your spies on enemy ships haven't detect anything yet.";
$l_spy_infotitle = "Your spies have detected the following information";
$l_spy_time = "Time";
$l_spy_type = "Type";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "There is a [player]'s planet [planet] in sector [sector].";
$l_spy_delete = "Delete";
$l_spy_messages = "to see what your spies have detected.";
$l_spy_defaulttitle1 = "Spies on enemy ships";
$l_spy_defaulttitle2 = "Spies on enemy planets";
$l_spy_defaulttitle3 = "Spies on your planets";
$l_spy_defaulttitle4 = "Spies on your ship";

$l_spy_no1 = "You don't have any spies on enemy ships.";
$l_spy_no2 = "You don't have any spies on enemy planets.";
$l_spy_no3 = "You don't have any spies on your planets.";
$l_spy_no4 = "You don't have any spies on your ship.";
$l_spy_nospiesatall = "You don't have any spies.";
$l_spy_notknown = "Unknown";


$l_spy_trytitle = "On the planet this spy will try to";

$l_spy_cantsendfeds = "Sorry but Spies cannot be sent to Federation or Independant Planets.";
$l_spy_cantsendteam = "You cannot place Spies on a teammates planet.";
$l_spy_messagesdeleted = "All messages deleted";
$l_spy_deleteall = "Delete All";
$l_spy_onplanet = "Spies on planet";
$l_spy_menu = "to return to Spy Menu.";
?>
