<?php
$l_opt_title             = "Select a Team Icon";
$l_opt_errorsize            = "Error: Your image must not be larger than 64x64 pixels in size.";
$l_opt_errortype           = "Error: Image must be JPG, GIF or PNG";
$l_opt_errornographic           = "Error: no graphic selected.";
$l_opt_currentavatar         = "Your Current Team Icon";
$l_opt_uploadavatar           = "Upload an Icon";
$l_opt_directory            = "Select Team Icon Directory";
$l_opt_change              = "Change Directory";
$l_opt_select              = "Select Team Icon";
$l_opt_noteam              = "You are not on a team.";
$l_opt_notleader              = "Only the Team Coordinator can change the Team Icon.";
$l_opt_inuse              = "All Team Icons in this directory are in use.";
$l_opt_uploadtypes           = "(GIF, JPG, PNG)";
?>
