<?php
$l_gns_title             = "Use Genesis Device";
$l_gns_turn              = "You need at least one turn to use a genesis device.";
$l_gns_onplanet          = "You can't use this device while on the planet surface.";
$l_gns_full              = "This solar system is already full.";
$l_gns_planetex          = "There is already a planet in this sector.";
$l_gns_nogenesis         = "You do not have any genesis devices.";
$l_gns_forbid            = "Creating a planet in this sector is not permitted.";
$l_gns_bforbid           = "The bases in this sector are interfering with your genesis device. Planet creation not possible.";
$l_gns_pcreate           = "Planet created.";
$l_sgns_title             = "Use Sector Genesis Device";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "You do not have any sector genesis devices.";
$l_sgns_forbid            = "Creating a sector genesis wormhole in this sector is not permitted.";
$l_sgns_forbid1            = "Creating a sector genesis wormhole a Federation Sector is not permitted.";
$l_sgcreate				= "Create New Sector Genesis Sector";
$l_sgcreatens				= "Create New Sector Genesis Link back to known space";
$l_sgns_forbid2            = "More than [limit] links in SG Sectors are not permitted.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "You do not have enough credits to create a new sector.";
$l_sgns_shipcredits            = "Credits on ship:";
$l_sgns_createcost            = "Cost to create new Sector:";
$l_sgns_complete            = "Normal Space Link Complete";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";

?>
