<?php
$l_move_title            = "Move";
$l_move_turn             = "You need at least one turn to move.";
$l_move_failed           = "Move failed!";
$l_rs_title              = "RealSpace Move";
$l_rs_whichsector        = "Which sector would you like to reach through RealSpace?";
$l_rs_insector           = "You are presently in sector [sector] - and there are sectors available from 1 to [sector_max].";
$l_rs_submit             = "Compute";
$l_rs_movetime           = "With your engines, it will take [triptime] turns to complete the journey.";
$l_rs_energy             = "You would gather [energy] units of energy";
$l_rs_noturns            = "You do not have enough turns left, and cannot embark on this journey.";
$l_rs_engage_link        = "Engage";
$l_rs_engage             = "You have [turns] turns. [engage] engines?";
$l_rs_invalid            = "You cannot realspace to that sector from here.";
$l_rs_ready              = "You are now in sector [sector]. You used [triptime] turns, and gained [energy] energy units.";
$l_warp_invalid            = "You cannot warp to that sector from here.";
$l_move_unknown = "Unknown Movetype";
?>
