<?php
$l_lrs_title             = "Long Range Scan";
$l_lrs_nofull            = "Your scanners do not possess full long range scan capabilities.";
$l_lrs_noturns           = "You need at least $fullscan_cost turn(s) to run a full long range scan.";
$l_lrs_used              = "Used";
$l_lrs_turns             = "turn(s)";
$l_lrs_left              = "left";
$l_lrs_reach             = "The following locations can be reached from sector [sector]:";
$l_lrs_links             = "Links";
$l_lrs_ships             = "Ships";
$l_lrs_click             = "Click one of the links to move to that sector.";
$l_lrs_cantscan          = "Can't scan sector from current sector!";
$l_lrs_zero              = "Sector 1 is too crowded to scan for ships!";
$l_lrs_moveto            = "to move to sector";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet            = "View Log";
$l_lrs_fedjammed           = "Federation is jamming all sensor scans.";
$l_lrs_sectormissile_question             = " to fire sector missile.";
$l_log_months 		 = array('January','February','March','April','May','June','July','August','September','October','November','December');
$l_log_months_short 	 = array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
?>
