<?php
$l_shipyard_title        = "Shipyard";
$l_planet                = "Planet";
$l_ship_welcome = "Welcome to your Planetary shipyard. We currently offer these models for sale.";
$l_ship_class = "Class";
$l_ship_properties = "Class Properties";
$l_ship_current = "Current";
$l_ship_outstorage = "Get out of Storage";
$l_ship_storagecost = "Storage Cost";
$l_ship_storagewarn = "Once you take your Pioneer out of storage you will loose the one you were issued upon your initial ship destruction.";
$l_ship_levels = "Ship Components Levels";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Price";
$l_ship_turns = "Turns to build";
$l_ship_purchase = "Purchase";
$l_ship_stored = "Stored";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Average Maximum Tech Level:";
$l_ship_averagenormaltech = "Average Normal Tech Level:";
$l_ship_averagecurrenttech = "Average Current Tech Level:";
?>
