<?php
// port.php port_purchase.php
$l_trade		 = "Trade";
$l_title_port		 = "Port Trading";
$l_title_trade		 = "Trading Commodities";
$l_sector_war		 = "War embargo";
$l_war_info		 = "War is raging in this sector. You can't reach the port through all the hostile forces.";
$l_no_trade		 = "Trade forbidden";
$l_no_trade_out		 = "Trading at this port is not allowed for outsiders";
$l_no_trade_info	 = "Trading at this port is not allowed";
$l_buying		 = "Buying";
$l_selling		 = "Selling";
$l_commodity		 = "Commodity";
$l_amount		 = "Amount";
$l_price		 = "Price";
$l_buy			 = "Buy";
$l_sell			 = "Sell";
$l_trade_st_info	 = "You have [free_holds] empty cargo holds, can carry [free_power] more energy units, and have [credits] credits.";
$l_upgrade_port_title	 = "Upgrade Port";
$l_device_port_title	 = "Device Port";
$l_spacedock_port_title	 = "Spacedock";
$l_no_credits		 = "Not enough credits";
$l_creds_to_spend	 = "You have [credits] credits to spend.";
$l_cost			 = "Cost";
$l_avail		 = "Available";
$l_profit		 = "Profit";
$l_current		 = "Current";
$l_current_level	 = "Current Level";
$l_current_qty		 = "Current Quantities";
$l_max			 = "Max";
$l_ifyouneedmore	 = "If you need more you may access this port's [igb] ";
$l_ifyouneedplan	 = "Access the planet's";
$l_igb_term		 = "IGB Banking Terminal";
$l_upgrade		 = "Upgrade";
$l_unlimited		 = "Unlimited";
$l_full			 = "Full";
$l_equipped		 = "Equipped";
$l_n_a			 = "n/a";
$l_item			 = "Item";
$l_totalcost		 = "Total cost";
$l_would_dump	         = "If you would like to dump all your colonists here, click ";
$l_noport		 = "There is no port here!";
$l_trade_turnneed	 = "You need at least one turn to trade at a port or planet.";
$l_returnto_port1        = "here";
$l_returnto_port2        = " Click [port_link] to return to the port menu.";
$l_notenough_cargo	 = "You do not have enough free cargo holds for the commodities you wish to purchase.";
$l_notenough_power	 = "You do not have enough free power storage for the energy you wish to purchase.";
$l_notenough_credits	 = "You do not have enough credits to complete the transaction.";
$l_notenough_turns	 = "You do not have enough turns to complete the transaction.";
$l_trade_result		 = "Results for this trade";
$l_trade_complete	 = "Trade completed";
$l_trade_upgraded 	 = "Upgraded to level ";
$l_trade_added 		 = "added";
$l_trade_installed 	 = "installed";
$l_port_bounty 		 = "You can not access a special port while you have a bounty on you placed by The Federation.<BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough 	 = "You do not have enough credtis to pay the bounty of [amount] credits.<BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade 	 = "The IGB has issued a lockdown on your ship account due to a late loan payment. You cannot trade at a special port until you pay back your loan.";
$l_port_returntospecial = "to return to the supply depot.";
$l_toprobemenu          = "to go to the probe menu.";
$l_ports_shiplimit = "Minimum Ship class to mount device: ";
$l_ports_needrepair = "Repair";

$l_ports_needcredits = "You do not have enough credits for this transaction.	The total cost is";
$l_ports_needcredits1 = "credits and you only have";

$l_ports_tradeforbidden = "Trade forbidden";
$l_ports_nooutsiders = "Trading at this port is not allowed for outsiders.";

$l_bought		 = "You bought";
$l_sold		 = "You sold";
$l_notenough_commodity	 = "You do not have enough [commodity] to complete the transaction.";
$l_exceed_commodity	 = "Number of [commodity] exceeds the supply/demand.  ";
$l_port_shiptoolarge = "Your ship is too large to trade at this port.";

$l_port_hold_unit= "Holds per Unit";


$l_port_welcome = "Port [sectorname] Welcome's [player]";
$l_port_amountforsale = "The port has [amount] units of [commodity] for sale at [credits] credits per unit.";
$l_port_holdsperunit = "[holds] cargo holds required per unit.";
$l_port_howmanypurchase = "How many [commodity] units would you like to purchase?";
$l_port_unitstobuy = "Units to Buy";
$l_port_shipcarryingbuy = "Your ship is carrying [shipunits] units of [commodity]. You can Purchase [buyunits] units with available cargo hold space.";
$l_port_howmanysell = "[amount] units of [commodity] @ [credits] credits per unit.";
$l_port_unitstosell = "Units to Sell";
$l_port_perform = "Perform Transaction";
$l_port_cargoholds = "Cargo Holds";

?>
