<?php
$l_login_sclosed		= "Server Closed";       
$l_login_closed_message		= "Server closed until further notice.";                
$l_login_title2			= "Login Phase Two";
$l_login_banned			= "<b>You have been banned from this game by the administrator. You are no longer welcome to play on this server. Next time, behave.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie			= "Due to the seriousness of this crime and the vicious attack against you, the Federation has graciously decided to provide a free of charge cloning from your remains.  Sadly, even in this day and age, new clones can not own property, aside from the basics to make a living.  You will be provided with a basic ship and a few credits to get you started.  Hopefully your next life will be better.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser			= "You had no escape pod, and due to your modest success in this life, the Federation declines to clone you.  Your remains should eventually fall into a gravity well, hopefully to be used to create life elsewhere... several billion years from now.<BR><BR> Better luck next game...";
$l_login_4gotpw1		= "The password you entered is incorrect.<BR><BR>  If you have forgotten your password, ";
$l_login_4gotpw2		= "to have it e-mailed to you.<BR><BR>  Otherwise,";     
$l_login_4gotpw3		= "to try again.  Attempt logged with IP address of";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident			= "You have died in a horrible incident.";
$l_login_blackbox			= " is the blackbox information that was retrieved from your ships wreckage.";
$l_new_login             = "to go to the login screen.";
$l_login_playerlimit		= "The server has reached the maximum number of players it supports.  Please try logging in at a later time.";                
?>
