<?php
$l_autoroute_missingwarp         = "Next warplink is missing in this sector.  Warp move aborted.";
$l_autoroute_SDabort   = "Move Aborted due to Sector Defenses in the sector.";
$l_autoroute_turns          = "Deducted [triptime] Turns and moved to [targetlink]";
$l_autoroute_noturns           = "You are out of turns.";
$l_autoroute_title          = "Auto Routes";
$l_autoroute_id       = "Auto Route ID";
$l_autoroute_start       = "Auto Route Start";
$l_autoroute_destination       = "Auto Route Destination";
$l_autoroute_warps       = "Auto Route Warps";
$l_autoroute_deleteroute       = "Delete Route";
$l_autoroute_info       = "Click on the Start Sector to Realspace to that sector and start warping to the destination sector.";
$l_autoroute_delete2       = "Delete Routes";
$l_autoroute_noroutes       = "No Auto Routes";
$l_autoroute_createroute       = "Create New Auto Route";
$l_autoroute_deleted       = "Auto Routes deleted.";
$l_autoroute_return       = "Return to Auto Route Menu click";
$l_autoroute_created       = "Auto Route has been created.";
$l_autoroute_realmove       = "Realspace move to sector";
$l_autoroute_warpmove       = "Warp move to next sector";
$l_autoroute_warpfinal       = "Warp move to final sector";
$l_autoroute_editname       = "Edit Name";
?>
