<?php
$l_feedback_title        ="Send Feedback";
$l_feedback_to           ="TO:";
$l_feedback_from         ="FROM:";
$l_feedback_topi         ="SUBJECT:";
$l_feedback_feedback     ="Feedback";
$l_feedback_message      ="MESSAGE:";
$l_feedback_messent      ="Message Sent";
$l_feedback_subj         ="AATraders In-Game Feedback"; 
$l_feedback_info         ="Please send feedback in english only";
?>
