<?php
$l_ship2_buytitle        = "Buying a new ship";
$l_ship2_storetitle        = "Shipyard Storage Facility";
$l_ship2_wrongclass        = "Wrong ship class specified";
$l_ship2_buying        = "You are buying:";
$l_ship2_tradein        = "Trade In:";
$l_ship2_value        = "Current Ship Value:";
$l_ship2_newvalue        = "New Ship Value:";
$l_ship2_totalcost        = "Total Cost:";
$l_ship2_nomoney        = "You do not have enough credits to buy this ship.";
$l_ship2_purchase        = "Purchase";
$l_ship2_buynstore        = "Buy New ship and store old one";
$l_ship2_nomoney2        = "You do not have enough credits to complete this transaction.";
$l_ship2_paystorage        = "Your have removed your ship from storage.";
$l_ship2_turns        = "You need at least [turns] turns to perform this action";
$l_ship2_error        = "Internal error. Cannot find ship class.";
$l_ship2_owned        = "You already own this model of ship.";
$l_ship2_shipbought        = "You have just bought a new ship!";

?>
