<?php
$l_login_title = "Login";
$l_login_pw = "Password:";
$l_login_chooseres = "Dapat menentukan resolusi layar Anda. Silakan pilih paling cocok:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Masalah?";
$l_login_emailus = "E-mail us";
$l_login_forgot_pw = "Lupa password Anda? Masukkan kosong dan tekan login.";
$l_login_settings = "Pengaturan permainan";
$l_login_change = "Mengubah";
$l_login_title2 = "Utama Login for AATraders";
$l_login_reset1 = "Tidak Reset Terjadwal";
$l_login_reset2 = "Dijadwalkan Reset:";
$l_login_reset3 = "Sched Reset:";
$l_login_notice = "Pemberitahuan penting:";
$l_login_endadminnews = "Akhir dari Admin News";
$l_login_tourney_signup = "Pendaftaran Turnamen Diaktifkan";

$l_login_profile_only = "Profil Hanya";
$l_login_newclosed_message = "Pendaftaran baru Ditutup";
$l_login_tourneymode = "Turnamen Menjalankan";
$l_login_tourneystarts = "Starts:";
?>
