<?php
$l_opt2_title = "Simpan Pilihan";
$l_opt2_passunchanged = "Password yang tersisa tidak berubah. <BR><BR>";
$l_opt2_srcpassfalse = "Asli sandi salah. Password yang tersisa tidak berubah. <BR><BR>";
$l_opt2_newpassnomatch = "New password tidak cocok. Password yang tersisa tidak berubah. <BR><BR>";
$l_opt2_passchanged = "Password berubah. <BR><BR>";
$l_opt2_passchangeerr = "Kesalahan mengubah sandi <BR><BR>";
$l_opt2_userintup = "User interface pengaturan diperbarui. <BR><BR>";
$l_opt2_userintfail = "Gagal untuk memperbarui pengaturan antarmuka pengguna. <BR><BR>";
$l_opt2_chlang = "Bahasa ini telah diatur untuk [lang]. <p>";
$l_opt2_chtemplate = "Template telah diatur untuk [template]. <p>";
$l_opt2_dhtmlup = "Html dinamis pengaturan diperbarui. <BR><BR>";
$l_opt2_dhtmlfail = "Gagal untuk memperbarui pengaturan html dinamis. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname berubah menjadi [name]. <BR><BR>";
$l_opt2_playernamechanged = "Nama pemain Berubah untuk [name] dan [amount] kredit dipotong dari account kapal Anda. <BR><BR>";
$l_opt2_mapwidth = "Lokal dan Peta Galaxy Lebar:";
?>
