<?php
// New News Items

$l_news_planets = "planet";
$l_news_cols = "Juta koloni";
$l_news_p_headline = "[player] &#39;s Kekaisaran sekarang memiliki [total] planet";
$l_news_c_headline = "[player] &#39;s Kekaisaran sekarang memiliki [total] juta koloni";
$l_news_p_textXX = "Federasi telah mengeluarkan peringatan mengenai Kekaisaran [name]. [name] telah menguasai [total] planet dan harus dianggap sangat berbahaya. Semua sektor harus meningkatkan pertahanan sektor segera.";
$l_news_c_textXX = "Kekaisaran [name] adalah besar mengalami kepadatan pada semua planet dengan lebih dari [total] juta koloni. Kekurangan pangan dapat menimbulkan kerusuhan. Semua sektor harus menyadari kemungkinan tindakan agresif oleh [name] di masa depan.";

$l_created_universe = "&#39;Universe Creation&#39;";
$l_created_universe_full = "&quot;Para ilmuwan meneliti awal Semesta dengan suara bulat memutuskan bahwa hari ini adalah yang paling mungkin secara statistik hari untuk Semesta Penciptaan telah terjadi &#39;";

$l_news_p_text5 = "Meningkatnya kerajaan [name] sekarang memiliki lima planet, yang FNN akan menonton tindakan [name] lebih erat di masa depan!";
$l_news_p_text10 = "Semakin kerajaan [name] sekarang mengontrol sepuluh planet, Laporan FNN mengatakan bahwa perluasan lebih lanjut [name] mungkin mengakibatkan perang!";
$l_news_p_text25 = "Kerajaan besar dari [name] 25 planet sudah terjajah, dalam sebuah wawancara, [name] mengumumkan bahwa ia akan mempertimbangkan perlambatan ekspansi nya di masa depan!";
$l_news_p_text50 = "Besar yang sangat besar kerajaan [name], yang diwakili oleh 50 planet di seluruh galaksi semakin mengancam kekuatan. Salah satu wartawan FNN menemukan bahwa [name] adalah meng-upgrade kapalnya merencanakan perang besar. Dalam sebuah wawancara [name] mengumumkan bahwa yang dilakukan pada tujuan pertahanan saja!";
$l_news_c_text25 = "Meningkatnya kerajaan dari [name] sekarang memiliki 25 juta koloni, yang FNN akan mengawasi tindakan-tindakan [name] lebih erat di masa depan, tetapi sangat jelas bahwa angka kelahiran akan meledak!";
$l_news_c_text100 = "Kerajaan yang bercita-cita tinggi [name] kini memiliki 100 juta penduduk setempat, setelah ledakan tingkat kelahiran, [name] koloni tampaknya menjadi tempat yang baik bagi keluarga untuk menyelesaikan!";
$l_news_c_text500 = "Kerajaan besar dari [name] kini memiliki 500 juta kolonis, [name] mengatakan dalam sebuah wawancara bahwa kolonisasi dari galaksi baru saja belum dimulai";
$l_news_c_text1000 = "The humongous kerajaan dari [name] sekarang memiliki satu miliar kolonis, FNN wartawan menemukan bahwa [name] adalah memiliki beberapa mekanisme kloning aneh memungkinkan dia untuk berkembang biak pendatang baru dalam jumlah besar. Dengan jumlah koloni, maka kekuatan econmic kerajaan ini sangat besar, FNN berharap bahwa [name] tidak menghabiskan uang untuk perang";

$l_news_indi_short = "FNN Rumor: lebih [planets] menyatakan kemerdekaan.";
$l_news_indi = "Di FNN memiliki otoritas baik yang di atas [planets] planet telah memutuskan bahwa mereka lebih baik diperintah oleh diri mereka sendiri dan menjadi mandiri.";

$l_news_nova_short = "FNN Laporan: [name] menggunakan Nova Bomb.";
$l_news_nova = "FNN memiliki berita bahwa [name] telah menggunakan Nova takut Bom [total] waktu (s) untuk menghancurkan sebuah planet dan semua kapal di atasnya.";
$l_news_nova_m_short = "FNN Laporan: [name] menggunakan Nova Bom dan merindukan.";
$l_news_nova_m = "FNN memiliki berita bahwa [name] telah menggunakan Nova takut Bom [total] waktu (s) untuk mencoba dan menghancurkan planet. Nova Bom meledak di luar atmosfer planet-planet dan menyebabkan kerusakan besar infrastruktur planet.";

$l_news_bounty = "FNN Laporan: [name] tempat yang [amount] kredit karunia pada [name2].";

$l_news_attackerpod_p_short = "FNN Laporan: [name] &#39;s kapal hancur.";
$l_news_attackerpod_P = "[name] &#39;s kapal hancur ketika menyerang sebuah planet. Untungnya [name] memiliki Escape Pod dan selamat.";

$l_news_attackerdie_p_short = "FNN Laporan: [name] mati!";
$l_news_attackerdie_p = "[name] &#39;s kapal hancur ketika menyerang sebuah planet dan mereka dibunuh karena mereka gagal untuk membeli sebuah Escape Pod.";

$l_news_destroyed_p_short = "FNN Laporan: [name] serangan dan menghancurkan planet ini!";
$l_news_destroyed_p = "[name] menyerang [total] planet (s) yang dimiliki oleh [owner] dan penduduk hancur setiap planet planet mau untuk mencegah tertangkap!";

$l_news_defeated_p_short = "FNN Laporan: [name] serangan dan kekalahan sebuah planet!";
$l_news_defeated_p = "[name] menyerang [total] planet (s) yang dimiliki oleh [owner] dan mengalahkan pasukan pertahanan planet!";

$l_news_notdefeated_p_short = "FNN Laporan: [name] serangan sebuah planet dan kehilangan!";
$l_news_notdefeated_p = "[name] menyerang [total] planet (s) yang dimiliki oleh [owner] dan pertahanan planet diadakan terhadap serangan tanpa henti!";

$l_news_targetepod_short = "FNN Laporan: [name] menyerang [owner] dan menang!";
$l_news_targetepod = "[name] menyerang [owner] &#39;s kapal dan menghancurkan sama sekali. Untungnya [owner] kapal mereka telah dilengkapi dengan Escape Pod dan mereka selamat.";

$l_news_targetdies_short = "FNN Laporan: [name] menyerang [owner] dan membunuh mereka!";
$l_news_targetdies = "[name] menyerang [owner] &#39;s kapal dan menghancurkan sama sekali. Sayangnya [owner] tidak dilengkapi kapal mereka dengan Escape Pod dan mereka menguap.";

$l_news_fedcolbounty_short = "FNN Laporan: Federasi celah bawah pada [name]!";
$l_news_fedcolbounty = "Federasi hari ini telah retak di atas ruang terkenal bajak laut [name]! [name], yang secara rutin melanggar perjanjian beberapa ruang, sebentar terlibat oleh Federasi battlecruiser, yang diakibatkan [amount] kredit senilai kerusakan pada kapal bajak laut. Janji pejabat federasi lebih lanjut tindakan semacam itu di masa depan!";

$l_news_alliancecolbounty_short = "FNN Laporan: Aliansi celah bawah pada [name]!";
$l_news_alliancecolbounty = "Aliansi saat ini telah retak bawah pada ruang terkenal bajak laut [name]! [name], yang secara rutin melanggar perjanjian beberapa ruang, terlibat secara singkat oleh Aliansi, yang diakibatkan [amount] kredit senilai kerusakan pada kapal bajak laut. Janji pejabat aliansi lebih lanjut tindakan semacam itu di masa depan!";

$l_news_fedcol_pbounty_short = "FNN Laporan: Federasi perburuan turun [name]!";
$l_news_fedcol_pbounty = "Federasi hari ini telah retak di atas ruang terkenal bajak laut [name]! [name], yang secara rutin melanggar perjanjian beberapa ruang, sebentar terlibat oleh Federasi battlecruiser, yang disita planet [planetname] senilai [amount] kredit di sektor [sector]. Janji pejabat federasi lebih lanjut tindakan semacam itu di masa depan!";

$l_news_alliancecol_pbounty_short = "FNN Laporan: Aliansi perburuan turun [name]!";
$l_news_alliancecol_pbounty = "Aliansi saat ini telah retak bawah pada ruang terkenal bajak laut [name]! [name], yang secara rutin melanggar perjanjian beberapa ruang, terlibat secara singkat oleh Aliansi, yang disita planet [planetname] senilai [amount] kredit di sektor [sector]. Janji pejabat aliansi lebih lanjut tindakan semacam itu di masa depan!";

$l_news_fedcol_sbounty_short = "FNN Laporan: Federasi perburuan turun [name]!";
$l_news_fedcol_sbounty = "Federasi hari ini telah retak di atas ruang terkenal bajak laut [name]! [name], yang secara rutin melanggar perjanjian beberapa ruang, sebentar terlibat oleh Federasi battlecruiser, yang menyita sebuah kapal ([shiptype]) senilai [cost] dalam sektor [sector]. Janji pejabat federasi lebih lanjut tindakan semacam itu di masa depan!";

$l_news_alliancecol_sbounty_short = "FNN Laporan: Aliansi perburuan turun [name]!";
$l_news_alliancecol_sbounty = "Aliansi saat ini telah retak bawah pada ruang terkenal bajak laut [name]! [name], yang secara rutin melanggar perjanjian beberapa ruang, terlibat secara singkat oleh Alliance, yang menyita sebuah kapal [shiptype] pantas [cost] dalam sektor [sector]. Janji pejabat aliansi lebih lanjut tindakan semacam itu di masa depan!";

$l_killheadline = "[target] tewas dalam sebuah kecelakaan";
$l_news_killed = "[target] tewas dalam kecelakaan tragis hari ini. Bagaimana heroik - [target] adalah anggota terakhir pada dewan kapalnya, ketika ia melihat tidak ada melarikan diri pod tersisa baginya. Semoga ia beristirahat dalam damai!";

$l_killSDheadline = "[target] dibunuh oleh Sektor Pertahanan.";
$l_news_killedSD = "[target] dibunuh oleh jumlah yang sangat besar Sektor Pertahanan yang dimiliki oleh [killer]! Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killplanetheadline = "[target] tewas menyerang sebuah planet.";
$l_news_killedplanet = "[target] tewas ketika menyerang sebuah planet yang dimiliki oleh [killer] hari ini. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killshipheadline = "[target] tewas kapal tempur.";
$l_news_killedship = "[target] tewas dalam pertempuran kapal ke kapal dengan [killer] hari ini. Kapten rupanya lupa untuk melengkapi kapal dengan pod pelarian.";

$l_killsuicideheadline = "[target] bunuh diri.";
$l_news_killedsuicide = "[target] bunuh diri hari ini. Mereka mengambil jalan keluar yang pengecut karena mereka tidak memiliki kemampuan atau keberanian untuk menghadapi tekanan komandan kapal mereka sendiri.";

$l_killsofaheadline = "[target] tewas sofa menyerang sebuah planet.";
$l_news_killedsofa = "[target] tewas ketika menyerang sebuah planet sofa dimiliki oleh [killer] hari ini. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killnovaheadline = "[target] terbunuh dalam serangan nova.";
$l_news_killednova = "[target] dibunuh oleh [killer] selama nova serangan bom hari ini. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killnovabackfireheadline = "[target] tewas dari nova menjadi bumerang.";
$l_news_killednovabackfire = "[target] tewas ketika bom mereka menjadi bumerang nova hari ini. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killsectormissileheadline = "[target] tewas dari Sektor Missile.";
$l_news_killedsectormissile = "[target] tewas ketika sebuah rudal Sektor dari [killer] berdampak perisai mereka. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killhunterprobeheadline = "[target] tewas dari Hunter Probe.";
$l_news_killedhunterprobe = "[target] tewas ketika sebuah Hunter Probe dari [killer] berdampak perisai mereka. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

$l_killtrapprobeheadline = "[target] tewas dari Trap Sentry Probe.";
$l_news_killedtrapprobe = "[target] tewas ketika sebuah Trap Sentry Probe dari [killer] berdampak perisai mereka. Sayangnya, kapal itu tidak dilengkapi dengan pod pelarian.";

//-------------------

$l_killpodheadline = "[target] &#39;s kapal itu hancur dalam sebuah kecelakaan";
$l_news_killedpod = "[target] &#39;s kapal itu hancur dalam sebuah kecelakaan tragis hari ini. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killSDpodheadline = "[target] &#39;s kapal ini dihancurkan oleh Sektor Pertahanan.";
$l_news_killedSDpod = "[target] &#39;s kapal ini dihancurkan oleh jumlah yang sangat besar Sektor Pertahanan yang dimiliki oleh [killer]! An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killplanetpodheadline = "[target] &#39;s kapal hancur menyerang sebuah planet.";
$l_news_killedplanetpod = "[target] &#39;s kapal hancur ketika menyerang sebuah planet yang dimiliki oleh [killer] hari ini. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killshippodheadline = "[target] &#39;s kapal kapal hancur dalam pertempuran.";
$l_news_killedshippod = "[target] &#39;s kapal hancur dalam pertempuran kapal ke kapal dengan [killer] hari ini. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killsofapodheadline = "[target] &#39;s kapal hancur sementara sofa menyerang sebuah planet.";
$l_news_killedsofapod = "[target] &#39;s kapal hancur sementara sofa menyerang sebuah planet yang dimiliki oleh [killer] hari ini. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killnovapodheadline = "[target] &#39;s kapal dihancurkan selama serangan nova.";
$l_news_killednovapod = "[target] &#39;s kapal ini dihancurkan oleh [killer] selama nova serangan bom hari ini. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &#39;s kapal hancur dari nova menjadi bumerang.";
$l_news_killednovabackfirepod = "[target] &#39;s kapal itu hancur ketika mereka menjadi bumerang nova bom hari ini. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &#39;s kapal dihancurkan oleh Sektor Missile.";
$l_news_killedsectormissilepod = "[target] &#39;s kapal hancur ketika seorang Sektor rudal dari [killer] berdampak perisai mereka. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &#39;s kapal dihancurkan oleh Hunter Probe.";
$l_news_killedhunterprobepod = "[target] &#39;s kapal hancur ketika seorang Hunter Probe dari [killer] berdampak perisai mereka. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &#39;s kapal dihancurkan oleh Trap Sentry Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s kapal hancur ketika seorang Trap Sentry Probe dari [killer] berdampak perisai mereka. An Escape Pod transponder terdeteksi oleh Federasi Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] telah dipromosikan menjadi [rank]";
$l_news_promoted = "Federasi senang untuk mengumumkan promosi [name] ke pangkat [rank].";

$l_news_demotedheadline = "[name] telah diturunkan ke [rank]";
$l_news_demoted = "Federasi penyesalan untuk mengumumkan penurunan pangkat dari [name] ke pangkat [rank].";

$l_news_namechangedheadline = "[oldname] berubah nama menjadi [newname]";
$l_news_namechanged = "[oldname] diterapkan pada Review Federasi Dewan untuk mengubah nama mereka untuk [newname]. Federasi telah memberikan perubahan nama. Mulai hari ini [oldname] akan sekarang dikenal sebagai [newname]. Semua kapal dan planet-planet harus memperbarui catatan mereka segera.";

$l_news_found_planets_short = "Federasi Survey: [found_planets] planet baru terletak.";
$l_news_found_planets = "Federasi Survey Pramuka sudah bisa menemukan [found_planets] baru baru-baru ini ditemukan planet di sektor.";

$l_news_new_ports_short = "Federasi Survey: [new_ports] port baru dibangun.";
$l_news_new_ports = "Federasi Insinyur telah dibangun [new_ports] pelabuhan baru di sektor ditemukan baru-baru ini.";

$l_news_addedsectors_short = "Federasi Survey: [addedsectors] sektor ditemukan.";
$l_news_addedsectors = "Federasi Survey Pramuka telah menemukan [addedsectors] sektor baru. Perhatian dianjurkan.";

$l_news_artifactheadline = "[playername] selesai [artifact]";
$l_news_artifact = "[playername] telah menemukan semua potongan [artifact] dan memiliki semua kekuatan dapat menyediakan.";

$l_news_artifactfoundheadline = "[playername] menemukan [artifact] potongan";
$l_news_artifactfound = "[playername] telah menemukan salah satu potongan dari [artifact] dan kebutuhan [pieces] lebih [piece].";

?>
