<?php
$l_autoroute_missingwarp = "Next warplink yang hilang dalam sektor ini. Warp bergerak dibatalkan.";
$l_autoroute_SDabort = "Pindahkan Dibatalkan karena Sektor Pertahanan di sektor ini.";
$l_autoroute_turns = "Dipotong [triptime] Ternyata dan pindah ke [targetlink]";
$l_autoroute_noturns = "Anda berada di luar berubah.";
$l_autoroute_title = "Auto Rute";
$l_autoroute_id = "Auto Route ID";
$l_autoroute_start = "Auto Route Mulai";
$l_autoroute_destination = "Auto Route Tujuan";
$l_autoroute_warps = "Auto Route Warps";
$l_autoroute_deleteroute = "Hapus Route";
$l_autoroute_info = "Klik Start Realspace Sektor untuk sektor itu dan mulai warping ke sektor tujuan.";
$l_autoroute_delete2 = "Hapus Rute";
$l_autoroute_noroutes = "Tidak Auto Rute";
$l_autoroute_createroute = "Buat Rute Oto Baru";
$l_autoroute_deleted = "Auto Rute dihapus.";
$l_autoroute_return = "Kembali ke Auto Route Menu klik";
$l_autoroute_created = "Rute auto telah dibuat.";
$l_autoroute_realmove = "Realspace pindah ke sektor";
$l_autoroute_warpmove = "Warp pindah ke sektor berikutnya";
$l_autoroute_warpfinal = "Warp pindah ke sektor terakhir";
$l_autoroute_editname = "Edit Nama";
?>
