<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Selamat datang di Casino, saat ini kami menawarkan Permainan berikut dan Fasilitas";
$l_casino_option = "&quot;Kamar";
$l_casino_detail = "&quot;Keterangan";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "&quot;Berdiri";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;Pertama Hand";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Asuransi";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Membelah";
$l_credits = "Credits";
$l_yourbet = "&quot;Your Bet";
$l_nobet = "&quot;Anda yakin telah melampaui batas kredit Anda, silakan bertaruh lagi.";
$l_dealerwins = "Dealer Menang!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer Kehilangan!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Player Wins!";
$l_playerbust = "&quot;Player patung!";
$l_playerloses = "&quot;Player Kehilangan!";
$l_playerblackjack = "&quot;Player BlackJack!";
$l_place_bet = "&quot;Tempat taruhan";
?>
