<?php
$l_sn_title = "Catatan Sektor";
$l_sn_pntitle = "Sektor dengan Personal Notes";
$l_sn_tntitle = "Tim sektor dengan Catatan";
$l_sn_psntitle = "Sektor Catatan pribadi";
$l_sn_tsntitle = "Catatan Sektor Team";
$l_sn_editnote = "Edit Sektor Catatan:";
$l_sn_deleteedit = "Hapus atau Edit:";
$l_sn_addnote = "Tambahkan Sektor Catatan:";
$l_sn_list = "Daftar Sektor Catatan";
$l_sn_listts = "Daftar Sektor dengan Tim Catatan";
$l_sn_addteam = "Tambahkan Team";
$l_sn_deleteteam = "Hapus Team";
$l_sn_delete = "Menghapus";
$l_sn_saveteam = "Simpan Team";
$l_sn_deletepersonal = "Hapus Pribadi";
$l_sn_addpersonal = "";
$l_sn_savepersonal = "Simpan Pribadi";
$l_sn_editpersonal = "Edit pribadi";
$l_sn_editteam = "Edit Tim";

$l_sn_hdsector = "Sektor";
$l_sn_hdtype = "Tipe";
$l_sn_hdowner = "Pemilik / Tim";
$l_sn_hdplanets = "Planet";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Tambang";
$l_sn_hdscanfrom = "Scan Dari";
$l_sn_hddetail = "Detail";
$l_sn_hddate = "Date / Time";
$l_sn_hddelete = "Menghapus";
$l_sn_hdteam = "Tim";
$l_sn_view = "Melihat";
$l_sn_no = "Tidak";
$l_sn_yes = "Ya";
$l_sn_nonotes = "Catatan sektor Tidak Ditemukan";

?>
