<?php
$l_beacon_title = "Menyebarkan Space Beacon";
$l_beacon_notpermitted = "Ruang menggelar beacon dalam sektor ini tidak diijinkan.";
$l_beacon_reads = "Sekarang suar reads";
$l_beacon_none = "Saat tidak ada sebuah mercusuar di sektor ini.";
$l_beacon_enter = "Masukkan teks untuk suar";
$l_beacon_nowreads = "Berbiinji Beacon";
$l_beacon_donthave = "Anda tidak memiliki ruang suar.";
?>
