<?php
$l_die_title = "Merusak diri";
$l_die_rusure = "Apakah Anda yakin ingin menghancurkan kapal anda? Ini akan menghapus Anda dari permainan.";
$l_die_goodbye = "Goodbye kejam galaksi!";
$l_die_check = "Apakah Anda yakin bahwa Anda ingin menghapus diri sendiri dari game?";
$l_die_nonono = "NO! NO! NO!";
$l_die_what = "Apa yang kupikirkan?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Anda kapal dan semua penumpang telah menguap.";
$l_die_please1 = "logout";
$l_die_please2 = "Tolong, [logout_link]";
$l_die_exploit = "Jangan bermain dengan apa yang Anda tidak mengerti.";
?>
