<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: SHOUTBOX::.";
$l_shout_public = "Publik";
$l_shout_team = "Tim";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "lain";
$l_shout_refresh = "Refresh";
$l_shout_close = "Close Window";
$l_shout_saved = "Shout disimpan!";
$l_shout_return = "Kembali ke";
$l_shout_prev = "Sebelumnya";
$l_shout_next = "Berikutnya";
$l_shout_selectpage = "Pilih Halaman";
$l_shout_page = "Halaman:";
$l_shout_teamtitle = ".:: TIM SHOUTBOX::.";
?>
