<?php
$l_sm_title = "Peluncuran rudal Sektor";
$l_sm_invalid = "Tidak ada warp hubungan antara sektor ini dan sektor tujuan.";
$l_sm_notarg = "Target tidak di sektor ini.";
$l_sm_noturn = "Anda memerlukan setidaknya satu giliran untuk memecat Sektor Missile Anda.";
$l_sm_nosectormissile = "Anda tidak membawa apapun Sektor Missiles.";
$l_sm_noscan = "Sensor tidak bisa mendapatkan perbaikan pada sasaran!";
$l_sm_flee = "Target keluar mengemudikan Sektor Missile!";
$l_sm_ewd = "Target terlibat warp darurat perangkat ketika mendeteksi Sektor Missile!";
$l_sm_imtitle = "Kapal Under Attack";
$l_sm_imbody = "[playername] adalah menyerang kapal anda dengan Sektor Missile!";
$l_sm_sectormissilefail = "Missile Sektor berfungsi ketika menghantam kapal-kapal musuh perisai!";
$l_sm_sectormissilefail2 = "Missile Sektor berfungsi ketika itu menghantam baju besi kapal-kapal musuh!";
$l_sm_shieldhit = "[target] &#39;s perisai yang hit untuk [amount] kerusakan!";
$l_sm_shieldsdown = "[target] &#39;s perisai yang turun!";
$l_sm_armorhit = "[target] &#39;s baju besi terkena untuk [amount] kerusakan!";
$l_sm_armorbreached = "[target] &#39;s zirah dilanggar!";
$l_sm_targetnoenergy = "Kapal musuh tidak memiliki energi! Sektor Missile gagal!";
$l_sm_attacking = "Menyerang [target] di atas kapal [shipname]";
$l_sm_targetok = "Anda tidak Hancurkan [name] &#39;s kapal.";
$l_sm_lost = "[target] hilang [armor] zirah poin dan [energy] unit energi.";
$l_sm_destroyed = "[target] &#39;s kapal telah dihancurkan.";
$l_sm_escapepod = "Pod pelarian diluncurkan!";
?>
