<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Anda memerlukan setidaknya 1 gilirannya untuk membangun basis";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "Bom Nova rindu sempit tapi menimbulkan kerusakan pada planet ini.";
$l_planet_novaturns = "Bom Nova membutuhkan atleast [turns] berubah menjadi api.";
$l_planet_novafed = "Bom Nova tidak akan kekuatan di sektor Federasi.";
$l_planet_nonova = "Anda tidak memiliki Bomb Nova diinstal.";
$l_planet_firenova = "Nova Fire Bomb";
$l_planet_novaexplode = "Nova Bom itu meledak ketika dipecat dan kapal Anda telah menderita kerusakan besar.";
$l_planet_novaexplode2 = "Nova Bom itu meledak ketika dipecat dan kapal anda hancur.";
$l_planet_noautotrade = "Rute Perdagangan auto tidak ditetapkan untuk planet ini.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] di pelabuhan [dest_id]";
$l_planet_autotradedelete = "Hapus Auto Perdagangan.";
$l_planet_autotradeadd = "Buat Auto Perdagangan.";
$l_planet_tradedeleted = "Rute Perdagangan auto Dihapus.";
$l_planet_tradeadded = "Rute Perdagangan Oto Baru Added.";
$l_planet_autotype = "Pilih item untuk perdagangan";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Anda perlu membeli Kapal Kargo untuk planet ini sebelum Anda dapat mengatur Auto Rute Perdagangan.";
$l_planet_purchasecargo = "Jika Anda ingin membeli Kapal Kargo";
$l_planet_upgradecargo = "Jika Anda ingin meng-upgrade Kapal Kargo";

$l_planet_cargocapacity = "Kapasitas";
$l_planet_cargoowned = "Anda sudah memiliki kapal kargo untuk planet ini.";
$l_planet_cargoshipbuy = "Pembelian Kapal Cargo";
$l_planet_cargoshipupgrade = "Upgrade Kapal Kargo";
$l_planet_cargoatmax = "Kapal barang Anda adalah di tingkat upgrade maksimum.";
$l_planet_cargoshipbuyinfo = "Pilih preset Kapal Kargo";
$l_planet_cargoshipupgradeinfo = "Upgrade Cargo Ships Anda Hull.";
$l_planet_cargoshipbuildinfo = "Build your Own Kargo Kapal";
$l_planet_tradehelp = "";
$l_planet_cargocredits = "Kredit Perdagangan auto Received:";
$l_planet_cargonoown = "Anda harus memiliki planet untuk menciptakan Auto Traderoute.";
$l_planet_digtrans = "Transfer pembesar";
$l_planet_nocredits1 = "Anda tidak memiliki cukup kredit untuk transaksi ini. Biaya total";
$l_planet_nocredits2 = "kredit dan Anda hanya";
$l_planet_nobase = "Anda harus memiliki dasar untuk mengelola planet tingkat pertahanan.";
$l_planet_genesisnoturn = "Anda memerlukan setidaknya 1 giliran untuk menggunakan Device Kejadian di planet.";
$l_planet_nogenesis = "Anda memerlukan Kejadian Device untuk menghancurkan sebuah planet.";
$l_planet_wrongclass = "Kelas kapal ini tidak dapat memecat seorang Bomb Nova Device.";

$l_planet_combatpreview = "Combat Preview";
$l_planet_beamfire1 = "Serangan Anda telah terdeteksi. Planet Beams tembak! Peningkatan Beam Api sebagai kapal datang terlalu dekat ke planet untuk memulai pejuang.";
$l_planet_beamfire2 = "Serangan Anda telah terdeteksi. Planet Beams tembak! Bunga api besar-besaran dari planet sebagai Baterai Beam kunci untuk beberapa hits!";
$l_planet_beamfire3 = "Serangan Anda telah terdeteksi. Planet Beams tembak! Baterai Beam di seluruh planet penguncian selama beberapa kebakaran besar! Beam kebakaran jauh lebih tinggi dari perkiraan!";
$l_planet_beamfire4 = "Serangan Anda telah terdeteksi. Planet Beams tembak! Beam pertahanan hanya dapat mengunci aktif selama satu menembak lulus.";

$l_planet_sofanobeamsshields = "tidak menembak tersenyum pada perisai Anda.";
$l_planet_sofanobeamsarmor = "tidak menembak balok di baju besi Anda.";
$l_planet_flauncherfailed1 = "Sistem peluncuran pesawat tempur anda telah berfungsi.";
$l_planet_flauncherfailed2 = "Anda hanya dapat memulai";
$l_planet_flauncherfailed3 = "persen dari pejuang.";
$l_planet_nodfightertofighter = "tidak mengirimkan apapun untuk menyerang pejuang pejuang Anda.";
$l_planet_nodfightertotorp = "Anda tidak mengirimkan apapun untuk menyerang pejuang torps Anda.";
$l_planet_flauncherfailed3 = "persen dari pejuang.";
$l_planet_autotradetype = "- [source_type] di pelabuhan [dest_id]";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "menyerang";
$l_planet_iminsector = "di sektor";
$l_planet_imnova = "adalah menggunakan Nova Device di";
$l_planet_imsofa = "adalah SOFA Pengeboman";
$l_planet_team = "Planet ini dimiliki oleh tim pasangan dan Anda tidak memiliki izin untuk mengakses informasi untuk planet ini.";
?>
