<?php
$l_warp_cantsame = "Anda tidak dapat membuat sebuah link ketika sumber adalah sama sebagai tujuan.";
$l_warp_twoerror = "Menggunakan Warp Editor untuk membuat dua arah link ke sektor [target_sector] tidak diizinkan.";
$l_warp_sectex = "Tidak dapat membuat warp link dari sektor saat ini - yang akan melebihi jumlah maksimum $ link_max per sektor.";
$l_warp_linked = "Target sektor ([target_sector]) sudah memiliki link dari sektor ini.";
$l_warp_coneway = "Link menciptakan satu cara untuk";
$l_warp_ctwoway = "Link dibuat untuk dan dari";
$l_warp_nomoney = "Anda tidak memiliki cukup kredit untuk menciptakan link lungsin.";
$l_warp_noenergy = "Anda tidak memiliki energi yang cukup untuk menciptakan link lungsin.";
?>
