<?php
$l_autotrade_title = "Auto Traderoute Menu";
$l_autotrade_dismiss2 = "Auto Traderoutes Dihapus.";
$l_autotrade_report = "Auto Traderoute Laporan";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energi";
$l_autotrade_capacity = "Kapasitas";
$l_autotrade_goods = "Harga Barang";
$l_autotrade_ore = "Bijih Harga";
$l_autotrade_organics = "Organik Harga";
$l_autotrade_energy = "Harga Energi";
$l_autotrade_colonist = "Penjajah Harga";
$l_autotrade_credits = "Trade Credits";
$l_autotrade_delete = "Menghapus <br> Route";
$l_autotrade_unnamed = "Unnamed";
$l_autotrade_noroute = "Tidak Route";
$l_autotrade_sector = "Sektor";
$l_autotrade_credit2 = "kredit";
$l_autotrade_deletebutton = "Menghapus";
$l_autotrade_noroute2 = "Anda belum setup Auto Traderoutes apapun.";
?>
