<?php
$l_contact_admin_title = "Kontak Game Administrator";
$l_contact_admin_thanks = "Terima kasih atas komentar Anda.";
$l_contact_admin_email_alert = "Silakan masukkan alamat email yang valid.";
$l_contact_admin_name_alert = "Silahkan masukkan nama Anda.";
$l_contact_admin_comment_alert = "Silakan masukkan komentar Anda.";
$l_contact_admin_name = "Nama";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Pertanyaan / Komentar";
$l_contact_admin_submit = "Kirim Pertanyaan / Komentar";
$l_contact_admin_close = "Close Window";
$l_contact_admin_thanks_comment = "Terima kasih atas komentar atau pertanyaan Anda. Kami akan menjawab pertanyaan dan email Anda dengan tanggapan kita.";

?>
