<?php
///SPIES
$l_spy_title = "Spy Menu";
$l_spy = "Spies";
$l_spy_disabled = "Spies dinonaktifkan!";
$l_spy_noturn = "Anda memerlukan setidaknya satu giliran untuk mengirim mata-mata untuk sebuah planet.";
$l_spy_notonboard = "Anda tidak memiliki mata-mata di atas kapal.";
$l_spy_ownplanet = "Anda tidak dapat mengirim mata-mata untuk planet anda sendiri.";
$l_spy_unownedplanet = "Anda tidak dapat mengirim mata-mata untuk unowned planet.";
$l_spy_planetfull = "Sudah ada diperbolehkan [max] mata-mata di planet itu.";
$l_spy_sendtitle = "Mengirimkan mata-mata [spyID] untuk planet: <BR> Pilih mata-mata misi:";
$l_spy_type1 = "Mata-mata hanya bertindak atas planet itu.";
$l_spy_type2 = "Mata-mata mencoba menyusup sebuah kapal yang melakukan transfer planet.";
$l_spy_type3 = "Mata-mata mencoba menyusup sebuah kapal yang melakukan transfer planet dan kemudian menyusup ke planet lain.";
$l_spy_sendbutton = "Kirim ke planet";
$l_spy_sendsuccessful = "Mata-mata Anda infiltrat planet ini dan menunggu saat yang tepat untuk memulai tindakan.";
$l_spy_sendfailed = "Sensor planet terdeteksi mata-mata Anda, karena perangkat Jubah Anda tidak bisa menutupi dirinya. Mata-mata Anda terbunuh.";
$l_spy_noturn2 = "Anda memerlukan setidaknya satu giliran menelepon kembali mata-mata.";
$l_spy_confirm = "Apakah Anda yakin ingin menelepon kembali mata-mata Anda [spyID]?";
$l_spy_cleanupplanet = "untuk membersihkan planet itu dari mata-mata musuh.";
$l_spy_cleanupship = "Jika Anda ingin membersihkan kapal Anda dari mata-mata musuh, klik";
$l_spy_yourspies = "Mata-mata Anda di planet itu";
$l_spy_sendnew = "Mengirim mata-mata baru";

$l_spy_codenumber = "Kode";
$l_spy_job = "Pekerjaan";
$l_spy_percent = "Persen";
$l_spy_move = "Gerakan";
$l_spy_action = "Aksi";
$l_spy_shipowner = "Pemilik kapal";
$l_spy_shipname = "Nama Kapal";
$l_spy_shiptype = "Kelas Kapal";
$l_spy_shiplocation = "Kapal Lokasi";
$l_spy_planetowner = "Planet Pemilik";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sektor";

$l_spy_moves['none'] = "Tidak bergerak";
$l_spy_moves['toship'] = "Untuk kapal";
$l_spy_moves['toplanet'] = "Untuk planet";

$l_spy_comeback = "Menelepon kembali";
$l_spy_nospieshere = "Anda tidak memiliki mata-mata di planet ini!";
$l_spy_transferred = "mata-mata ditransfer";
$l_spy_backonship = "Sekarang mata-mata pada kapal.";
$l_spy_backfailed = "Menelepon kembali gagal.";
$l_spy_changetitle = "Mengubah mata-mata [spyID] sifat:";
$l_spy_occupied = "Mata-mata Anda [spyID] dalam dipekerjakan sebagai [job], dengan persen [percent].";
$l_spy_dismiss = "Mengabaikan mata-mata?";
$l_spy_changebutton = "Mengubah";
$l_spy_changejob = "Ubah Ayub atau Gerakan";
$l_spy_linkback = "untuk pergi ke menu mata-mata.";
$l_spy_changed1 = "Gerakan berubah.";
$l_spy_changed2 = "Spy dipecat dan gerakannya berubah.";
$l_spy_changefailed = "Ubah gagal.";
$l_spy_cleanupplanettitle = "Membersihkan planet Anda dari mata-mata musuh:";
$l_spy_notyourplanet = "Itu bukan planet.";
$l_spy_cleanuptext[1] = "Fast cleanup. Menggunakan [creds] kredit dan [turns] berubah.";
$l_spy_cleanuptext[2] = "Baik cleanup. Menggunakan [creds] kredit dan [turns] berubah.";
$l_spy_cleanuptext[3] = "Pembersihan yang terbaik. Menggunakan [creds] kredit dan [turns] berubah.";
$l_spy_cannotcleanupplanet = "Anda hanya memiliki [credits] kredit pada planet itu dan [turns] berubah.";
$l_spy_cleanupbutton1 = "Buat membersihkan planet";
$l_spy_cleanupplanettitle2 = "Anda menyalakan Sensor Anda untuk menemukan mata-mata musuh di planet itu.";
$l_spy_spyfoundonplanet = "Anda menemukan sebuah [player] &#39;s mata-mata [spyID] di planet ini. Anda membunuh mata-mata.";
$l_spy_spynotfoundonplanet = "Anda tidak menemukan mata-mata musuh di planet itu.";
$l_spy_notenough = "Anda tidak memiliki cukup kredit atau berubah untuk memulai pembersihan.";

$l_spy_cleanupshiptitle = "Membersihkan kapal Anda dari mata-mata musuh:";
$l_spy_notinspecial = "Anda harus berada pada port Device untuk membersihkan kapal Anda.";
$l_spy_cleanupshiptext[1] = "Fast cleanup. Menggunakan [creds] kredit dan [turns] berubah.";
$l_spy_cleanupshiptext[2] = "Baik cleanup. Menggunakan [creds] kredit dan [turns] berubah.";
$l_spy_cleanupshiptext[3] = "Pembersihan yang terbaik. Menggunakan [creds] kredit dan [turns] berubah.";
$l_spy_cannotcleanupship = "Anda hanya memiliki [credits] kredit dan [turns] berubah.";
$l_spy_cleanupbutton2 = "Mulai membersihkan kapal Anda";
$l_spy_cleanupshiptitle2 = "Anda menyalakan Sensor Anda untuk menemukan mata-mata musuh di kapal Anda.";
$l_spy_spyfoundonship = "Anda menemukan sebuah [player] &#39;s mata-mata [spyID] pada kapal Anda. Anda membunuh mata-mata.";
$l_spy_spynotfoundonship = "Anda tidak menemukan mata-mata musuh di kapal Anda.";

$l_spy_infodeleted = "Pesan dihapus";
$l_spy_infonotyours = "Ini bukan pesan Anda.";
$l_spy_noinfo = "Anda mata-mata pada kapal musuh tidak mendeteksi apa-apa.";
$l_spy_infotitle = "Mata-mata Anda telah mendeteksi informasi berikut";
$l_spy_time = "Waktu";
$l_spy_type = "Tipe";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Ada [player] &#39;s planet [planet] di sektor [sector].";
$l_spy_delete = "Menghapus";
$l_spy_messages = "untuk melihat apa yang mata-mata Anda telah terdeteksi.";
$l_spy_defaulttitle1 = "Mata-mata pada kapal-kapal musuh";
$l_spy_defaulttitle2 = "Mata-mata di planet musuh";
$l_spy_defaulttitle3 = "Mata-mata pada planet";
$l_spy_defaulttitle4 = "Mata-mata pada kapal";

$l_spy_no1 = "Anda tidak memiliki mata-mata pada kapal-kapal musuh.";
$l_spy_no2 = "Anda tidak memiliki musuh mata-mata di planet.";
$l_spy_no3 = "Anda tidak memiliki mata-mata pada planet.";
$l_spy_no4 = "Anda tidak memiliki mata-mata pada kapal.";
$l_spy_nospiesatall = "Anda tidak memiliki mata-mata.";
$l_spy_notknown = "Unknown";


$l_spy_trytitle = "Di planet mata-mata ini akan mencoba";

$l_spy_cantsendfeds = "Maaf, Spies tidak dapat dikirim ke Federasi atau Independent Planet.";
$l_spy_cantsendteam = "Anda tidak dapat menempatkan Spies di planet rekan.";
$l_spy_messagesdeleted = "Semua pesan dihapus";
$l_spy_deleteall = "Hapus Semua";
$l_spy_onplanet = "Spies di planet";
$l_spy_menu = "untuk kembali ke Spy Menu.";
?>
