<?php
$l_news_title = "Universe News";
$l_news_info = "FNN adalah di antara pemimpin galaksi <br> dalam berita dan informasi pengiriman. <br> Staf 24 jam, tujuh hari seminggu oleh seorang <br> staf yang berdedikasi di FNN&#39;s galaksi markas <br> dalam Proxima Centauri dan di biro galaxywide!";
$l_news_for = "Berita";
$l_news_prev = "kemarin";
$l_news_next = "hari berikutnya";
$l_news_none = "Maaf, tidak ada berita hari ini.";
$l_news_flash = "News Flash";
$l_news_end = "Akhir berita";
$l_news_bestviewed = "Best viewed in Opera, Safari dan IE";
$l_news_fedannouncements = "Federasi Pengumuman";
$l_news_planetarynews = "Planet Berita";
$l_news_planetshipnews = "Planet dan Kapal News";
$l_news_afteractionnews = "Setelah Aksi Combat Berita";
?>
