<?php
$l_opt_title = "Pilihan";
$l_opt_chpass = "Ubah password";
$l_opt_curpass = "Password:";
$l_opt_newpass = "New password:";
$l_opt_newpagain = "New password (lagi):";
$l_opt_userint = "User interface";
$l_opt_usenew = "Gunakan layout baru?";
$l_opt_lang = "Bahasa";
$l_opt_template = "Template";
$l_opt_select = "Pilih Satu:";
$l_opt_enabled = "Diaktifkan";
$l_opt_save = "Simpan";
$l_opt_teamicon = "Tim Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Lokal dan Peta Galaxy Lebar:";
$l_opt_profiletitle = "Profil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Terdaftar dengan Profil Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Bila Anda mendaftar pemutar Anda pada server lainnya template, shoutbox dan pengaturan berita di atas akan digunakan pada server.";
$l_opt_showshoutbox = "Tampilkan Shoutbox:";
$l_opt_shownewscrawl = "Tampilkan Berita Crawl:";
$l_opt_playername = "Player Nama:";
$l_opt_playernamecost = "Ubah Nama Federasi Fee: [amount] kredit";
?>
