<?php
// port.php port_purchase.php
$l_trade = "Perdagangan";
$l_title_port = "Port Trading";
$l_title_trade = "Trading Komoditas";
$l_sector_war = "Perang embargo";
$l_war_info = "Perang berkecamuk di sektor ini. Anda tidak dapat mencapai pelabuhan melalui semua kekuatan yang bermusuhan.";
$l_no_trade = "Perdagangan dilarang";
$l_no_trade_out = "Perdagangan di pelabuhan ini tidak dibolehkan untuk orang luar";
$l_no_trade_info = "Perdagangan di pelabuhan ini tidak diperbolehkan";
$l_buying = "Membeli";
$l_selling = "Menjual";
$l_commodity = "Komoditi";
$l_amount = "Jumlah";
$l_price = "Harga";
$l_buy = "Membeli";
$l_sell = "Menjual";
$l_trade_st_info = "Anda telah [free_holds] kargo kosong berlaku, dapat membawa [free_power] lebih banyak energi unit, dan telah [credits] kredit.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Tidak cukup kredit";
$l_creds_to_spend = "Anda telah [credits] kredit untuk dibelanjakan.";
$l_cost = "Biaya";
$l_avail = "Tersedia";
$l_profit = "Laba";
$l_current = "Saat ini";
$l_current_level = "Current Level";
$l_current_qty = "Current Kuantitas";
$l_max = "Max";
$l_ifyouneedmore = "Jika Anda membutuhkan lebih banyak Anda dapat mengakses pelabuhan ini [igb]";
$l_ifyouneedplan = "Akses planet";
$l_igb_term = "Perbankan IGB Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Unlimited";
$l_full = "Penuh";
$l_equipped = "Dilengkapi";
$l_n_a = "n / a";
$l_item = "Item";
$l_totalcost = "Total biaya";
$l_would_dump = "Jika Anda ingin membuang semua koloni Anda di sini, klik";
$l_noport = "Ada port di sini!";
$l_trade_turnneed = "Anda memerlukan setidaknya satu giliran perdagangan di pelabuhan atau planet.";
$l_returnto_port1 = "di sini";
$l_returnto_port2 = "Klik [port_link] untuk kembali ke menu pelabuhan.";
$l_notenough_cargo = "Anda tidak memiliki cukup kargo berlaku untuk komoditas yang ingin Anda beli.";
$l_notenough_power = "Anda tidak memiliki cukup kekuatan untuk penyimpanan energi yang Anda ingin untuk membeli.";
$l_notenough_credits = "Anda tidak memiliki cukup kredit untuk menyelesaikan transaksi.";
$l_notenough_turns = "Anda tidak memiliki cukup berubah untuk menyelesaikan transaksi.";
$l_trade_result = "Hasil untuk perdagangan ini";
$l_trade_complete = "Perdagangan selesai";
$l_trade_upgraded = "Upgrade ke tingkat";
$l_trade_added = "ditambahkan";
$l_trade_installed = "diinstal";
$l_port_bounty = "Anda tidak dapat mengakses port khusus saat Anda memiliki karunia pada Anda ditempatkan oleh Federasi. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Anda tidak memiliki cukup untuk membayar credtis karunia [amount] kredit. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "The IGB telah mengeluarkan pengurungan pada account kapal Anda karena keterlambatan pembayaran pinjaman. Anda tidak dapat perdagangan di pelabuhan khusus sampai Anda membayar kembali pinjaman Anda.";
$l_port_returntospecial = "untuk kembali ke depot pasokan.";
$l_toprobemenu = "untuk pergi ke menu probe.";
$l_ports_shiplimit = "Kapal minimum kelas untuk me-mount perangkat:";
$l_ports_needrepair = "Perbaikan";

$l_ports_needcredits = "Anda tidak memiliki cukup kredit untuk transaksi ini. Biaya total";
$l_ports_needcredits1 = "kredit dan Anda hanya";

$l_ports_tradeforbidden = "Perdagangan dilarang";
$l_ports_nooutsiders = "Perdagangan di pelabuhan ini tidak dibolehkan untuk orang luar.";

$l_bought = "Anda membeli";
$l_sold = "Anda menjual";
$l_notenough_commodity = "Anda tidak memiliki cukup [commodity] untuk menyelesaikan transaksi.";
$l_exceed_commodity = "Jumlah [commodity] melebihi penawaran / permintaan.";
$l_port_shiptoolarge = "Kapal Anda terlalu besar untuk perdagangan di pelabuhan ini.";

$l_port_hold_unit = "Holds per Unit";


$l_port_welcome = "Port [sectorname] Selamat datang&#39;s [player]";
$l_port_amountforsale = "Pelabuhan telah [amount] unit [commodity] untuk dijual di [credits] kredit per unit.";
$l_port_holdsperunit = "[holds] kargo memegang dibutuhkan per unit.";
$l_port_howmanypurchase = "Berapa banyak [commodity] unit yang ingin Anda membeli?";
$l_port_unitstobuy = "Unit to Buy";
$l_port_shipcarryingbuy = "Kapal Anda membawa [shipunits] unit [commodity]. Anda dapat Pembelian [buyunits] unit dengan ruang kargo yang tersedia.";
$l_port_howmanysell = "[amount] unit [commodity] @ [credits] kredit per unit.";
$l_port_unitstosell = "Unit Jual";
$l_port_perform = "Lakukan Transaksi";
$l_port_cargoholds = "Cargo Holds";

?>
