<?php
$l_footer_one_player_on = "Terdapat 1 pemain online.";
$l_footer_players_on_1 = "Ada";
$l_footer_players_on_2 = "Pemain online:";
$l_footer_until_update = "detik sampai update berikutnya.";
$l_footer_no_players_on = "Tidak ada pemain online.";

$l_footer_news = "FNN Berita Lokal";
$l_footer_title = "Alien Assault Trader";
$l_footer_help = "bantuan tentang halaman ini.";
$l_footer_click = "Klik";

$l_footer_open_slots = "Maximum Online:";
$l_footer_onlinereset = "Pemain Online Time Reset di";
$l_footer_onlinecountdown = "Pemain Online Time Countdown:";
?>
