<?php
$l_readm_title = "Baca Pesan";
$l_readm_delete = "Pesan dihapus";
$l_readm_nomessage = "Anda tidak memiliki Pesan yang menunggu untuk Anda ...";
$l_readm_center = "Pusat Menerima pesan";
$l_readm_sender = "Pesan Pengirim";
$l_readm_captn = "Kapten";
$l_readm_del = "Menghapus";
$l_readm_repl = "Menjawab";
$l_readm_return = "Klik di sini untuk kembali ke menu utama";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Hapus Semua";
$l_readm_subject = "Subyek";
$l_readm_quote = "Mengutip";
$l_readm_block = "Block Sender";
$l_readm_alert = "Alert System";
$l_readm_alertbody = "Kapal Komputer";
?>
