<?php
$l_artifact_title = "Ambil artifak";
$l_artifact_list_title = "Daftar Acquired Artifacts";
$l_artifact_noscan = "Scanner Anda tidak bisa menemukan artefak.";
$l_artifact_noturn = "Anda tidak memiliki cukup berubah untuk mengambil artifak ini.";
$l_artifact_classname = "Artifak Nama";
$l_artifact_description = "Artifak Deskripsi";
$l_artifact_imagename = "Artifak Image";
$l_artifact_incomplete = "Artifak Pieces";
$l_artifact_process = "Gunakan artifak Selesai";

?>
