<?php
$l_opt_title = "Pilih Tim Icon";
$l_opt_errorsize = "Error: Gambar Anda tidak boleh lebih besar dari ukuran 64x64 piksel.";
$l_opt_errortype = "Error: gambar harus JPG, GIF, atau PNG";
$l_opt_errornographic = "Kesalahan: tidak ada grafis dipilih.";
$l_opt_currentavatar = "Tim ini Anda Icon";
$l_opt_uploadavatar = "Upload Icon";
$l_opt_directory = "Pilih Team Icon Directory";
$l_opt_change = "Ubah Directory";
$l_opt_select = "Pilih Team Icon";
$l_opt_noteam = "Anda tidak berada di tim.";
$l_opt_notleader = "Hanya Koordinator Tim Tim dapat mengubah Icon.";
$l_opt_inuse = "Semua Tim Ikon dalam direktori ini sedang digunakan.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
