<?php
$l_sf_attacking = "Sektor pertahanan pejuang yang menyerang Anda! <BR>";
$l_sf_destfight = "Balok Anda hancur [lost] pejuang <BR>";
$l_sf_destfightb = "Balok Anda hancur [lost] pejuang <BR>";
$l_sf_torphit = "Torpedo hit:";
$l_sf_destfightt = "Torpedo Anda hancur [lost] pejuang <BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "Kau menghancurkan semua pejuang. <BR>";
$l_sf_destfightt2 = "Anda hancur [lost] pejuang. <BR>";
$l_sf_lostfight = "Anda kehilangan semua pejuang. <BR>";
$l_sf_lostfight2 = "Kau kehilangan [lost] pejuang. <BR>";
$l_sf_armorbreach = "Armor Anda dilanggar! <BR>";
$l_sf_armorbreach2 = "Anda terkena baju besi untuk [lost] kerusakan. <BR>";
$l_sf_sendlog = "[player] hancur [lost] sektor pertahanan pejuang di sektor [sector].";
$l_sf_lreport = "Kau kehilangan [armor] perisai poin, [fighters] pejuang, dan digunakan [torps] torpedo. <BR><BR>";
$l_sf_shipdestroyed = "Kapal Anda telah dihancurkan! <BR><BR>";
$l_sf_sendlog2 = "Sektor pertahanan pejuang hancur [player] dalam sektor [sector].";
$l_sf_escape = "Untungnya Anda memiliki pod pelarian! <BR><BR>";

$l_sf_fnoattack = "tidak mengirimkan apapun untuk menyerang pejuang pejuang Anda.";
$l_sf_fnoattackt = "tidak mengirimkan apapun untuk menyerang pejuang torpedo Anda.";
$l_sf_fnoattacka = "Anda tidak mengirimkan apapun untuk menyerang pejuang baju besi Anda.";
$l_sf_flaunchmalf1 = "Sistem peluncuran pesawat tempur anda telah berfungsi.";
$l_sf_flaunchmalf2 = "Anda hanya dapat memulai";
$l_sf_flaunchmalf3 = "persen dari pejuang.";
$l_sf_fightertorpexg = "Tempur untuk Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Kapal Torpedo untuk Sektor Fighter Exchange";
$l_sf_fighterarmorexg = "Sektor Fighter untuk Kapal Armor Exchange";
$l_sf_tlaunchmalf1 = "Sistem meluncurkan torpedo anda telah berfungsi.";
$l_sf_tlaunchmalf2 = "Anda hanya dapat memulai";
$l_sf_tlaunchmalf3 = "persen dari torpedo Anda.";
$l_sf_bountysd = "Anda telah menyerang sebuah sektor yang berisi sebuah planet yang akan memberi Anda karunia jika Anda menyerang planet. Federasi telah mengaktifkan otomatis merusak diri sendiri pada setiap pejuang dan torpedo. Jangan menyerang sektor pertahanan di sektor ini lagi. Anda telah diperingatkan!";
?>
