<?php
$l_cu_storing = "Menyimpan";
$l_cu_inistored = "<b>Semua nilai-nilai ini telah berhasil disimpan.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Mulai";
$l_cu_destination = "Auto Route Tujuan";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Hapus Route";
$l_cu_info = "Klik Start Realspace Sektor untuk sektor itu dan mulai warping ke sektor tujuan.";
$l_cu_delete2 = "Hapus Rute";
$l_cu_noroutes = "Tidak Auto Rute";
$l_cu_createroute = "Buat Rute Oto Baru";
$l_cu_deleted = "Auto Rute dihapus.";
$l_cu_return = "Kembali ke Auto Route Menu klik";
$l_cu_created = "Rute auto telah dibuat.";
$l_cu_realmove = "Realspace pindah ke sektor";
$l_cu_warpmove = "Warp pindah ke sektor berikutnya";
$l_cu_warpfinal = "Warp pindah ke sektor terakhir";
?>
