<?php
$l_move_title = "Pindah";
$l_move_turn = "Anda memerlukan setidaknya satu giliran untuk bergerak.";
$l_move_failed = "Pindahkan gagal!";
$l_rs_title = "RealSpace Pindah";
$l_rs_whichsector = "Sektor yang ingin Anda mencapai melalui RealSpace?";
$l_rs_insector = "Anda saat ini di sektor [sector] - dan ada sektor tersedia dari 1 sampai [sector_max].";
$l_rs_submit = "Hitunglah";
$l_rs_movetime = "Dengan mesin Anda, itu akan mengambil [triptime] berubah untuk menyelesaikan perjalanan.";
$l_rs_energy = "Anda akan berkumpul [energy] satuan energi";
$l_rs_noturns = "Anda tidak memiliki cukup bergantian kiri, dan tidak dapat memulai perjalanan ini.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "Anda telah [turns] berubah. [engage] mesin?";
$l_rs_invalid = "Anda tidak dapat realspace untuk sektor tersebut dari sini.";
$l_rs_ready = "Anda sekarang di sektor [sector]. Anda menggunakan [triptime] berubah, dan memperoleh [energy] unit energi.";
$l_warp_invalid = "Anda tidak dapat warp untuk sektor tersebut dari sini.";
$l_move_unknown = "Unknown Movetype";
?>
