<?php
$l_md_title = "Sektor pertahanan";
$l_md_invalid = "Sektor pertahanan tidak valid";
$l_md_nolonger = "Dipilih sektor pertahanan tidak lagi di sana.";
$l_md_you = "kamu";
$l_md_bmines = "Anda berseri-seri hancur";
$l_md_msgdownerb = "[name] hancur [mines] di sektor tambang [sector].";
$l_md_retr = "Anda retrieved";
$l_md_consist = "Pertahanan sektor ini terdiri dari [qty] [type] yang dimiliki oleh [owner].";
$l_md_youcan = "Anda dapat";
$l_md_retrieve = "Ambil";
$l_md_attack = "Serangan";
$l_md_attdef = "Sektor pertahanan menyerang. Semua sektor pejuang akan membalas.";
$l_md_noturn = "Anda memerlukan setidaknya satu giliran.";
$l_md_nothere = "Anda perlu berada dalam sektor yang sama seperti sektor pertahanan.";
$l_md_notyours = "Aksi tidak diizinkan. Sektor pertahanan mereka bukan milik Anda.";
$l_md_yours = "Anda tidak dapat menyerang sektor pertahanan Anda sendiri.";
?>
