<?php
$l_scan_title = "Scan Kapal";
$l_scan_turn = "Anda memerlukan setidaknya satu putaran untuk memindai kapal lain.";
$l_scan_ron = "Hasil scan";
$l_scan_capt = "Dikapteni oleh:";
$l_scan_arma = "Persenjataan:";
$l_scan_carry = "Carrying:";
$l_scan_bounty = "Kapal ini memiliki total karunia di atasnya [amount] kredit.";
$l_scan_fedbounty = "Kapal ini memiliki karunia di atasnya dari Federasi.";
$l_by_nofedbounty = "Menyerang pemain ini <B>TIDAK</b> akan mengakibatkan Federasi menempatkan karunia pada Anda.";
?>
