<?php
$l_profile_title = "Profil Pendaftaran";
$l_profile_notenabled = "Profil tidak diaktifkan pada server ini.";
$l_profile_registered = "Pemain ini sekarang terdaftar dengan Profil Master Server.";
$l_profile_nomatch = "Bisa tidak cocok dengan profil pada Profil Master Server dengan server nama dan sandi yang Anda masukkan.";
$l_profile_tryagain = "Untuk memasukkan nama profil pemain dan server sandi lagi klik";
$l_profile_name = "Profil Player Nama";
$l_profile_password = "Profil Server Password";
$l_profile_bannedserver = "Server ini tidak diperbolehkan untuk mengirimkan informasi profil Profil Master Server.";
$l_profile_bannedplayer = "Anda telah dilarang dari Master Profil Server dan mungkin tidak mendaftarkan pemain.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "<u><b>MEMBUTUHKAN</b></u> server ini setiap pemain baru untuk memiliki profil terdaftar. Anda tidak akan diizinkan untuk menciptakan pemain baru kecuali jika Anda memiliki profil terdaftar.";
$l_profile_updated = "Template Anda, shoutbox dan berita merangkak pengaturan global telah diperbarui pada Profil Master Server. Pengaturan ini secara otomatis akan digunakan ketika Anda mendaftar pada profil Anda pada setiap permainan.";

?>
