<?php
$l_att_title = "Menyerang Kapal";
$l_att_notarg = "Target tidak di sektor ini.";
$l_att_noturn = "Anda memerlukan setidaknya satu giliran untuk menyerang.";
$l_att_noatt = "Menyerang seseorang di sektor ini tidak diijinkan.";
$l_att_flee = "Target keluar bermanuver Anda!";
$l_att_ewd = "Target terlibat perangkat warp darurat ketika diserang!";
$l_att_att = "Menyerang";
$l_att_beams = "Beam Exchange";
$l_att_torps = "Torpedo Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost = "hilang";
$l_att_ylost = "Kau kehilangan";
$l_att_sdown = "&#39;s perisai yang turun!";
$l_att_ydown = "Perisai Anda menurun!";
$l_att_shits = "&#39;s perisai yang hit untuk";
$l_att_yhits = "Perisai Anda dipukul untuk";
$l_att_dmg = "kerusakan";
$l_att_sarm = "&#39;s baja dilanggar!";
$l_att_yarm = "Baju besi Anda telah dilanggar!";
$l_att_ashit = "&#39;s baja terkena untuk";
$l_att_ayhit = "Baja Anda terkena untuk";

$l_att_efhit = "&#39;s pejuang dihancurkan.";
$l_att_yfhit = "pejuang Anda dihancurkan.";
$l_att_ethit = "&#39;s torpedo dihancurkan.";
$l_att_ythit = "torpedo Anda dihancurkan.";
$l_att_of = "dari";
$l_att_lostt = "kehilangan semua torpedo.";
$l_att_ylostt = "Anda kehilangan semua torpedo.";

$l_att_lostf = "kehilangan semua pejuang.";
$l_att_ylostf = "Anda kehilangan semua pejuang.";
$l_att_sdest = "&#39;s kapal telah dihancurkan.";
$l_att_espod = "Pod pelarian diluncurkan!";
$l_att_ysalv = "Anda diselamatkan [ship_salvage_rate]% dari kapal untuk [ship_salvage] kredit. <BR> Your rating diubah oleh [rating_change] poin.";
$l_att_andused = "dan digunakan";
$l_att_stilship = "Anda tidak Hancurkan [name] &#39;s kapal.";
$l_att_atyou = "menyerangmu";
$l_att_and = "dan";
$l_att_yshiplost = "Kapal Anda telah dihancurkan!";
$l_att_salv = "[name] diselamatkan [ship_salvage_rate]% dari kapal untuk [ship_salvage] kredit";
$l_att_loosepod = "Untungnya Anda memiliki pod pelarian!";

$l_att_tnobeams = "jahitan untuk keluar dari energi berkas.";
$l_att_tnobeamsf = "jahitan untuk keluar dari energi berkas dan tidak bisa menyerang pejuang Anda.";
$l_att_tnobeamst = "jahitan untuk keluar dari energi berkas dan tidak bisa menyerang torpedo Anda.";
$l_att_tfnoattack = "Anda tidak mengirimkan apapun pejuang untuk menyerang kapal Anda.";
$l_att_tnotorps = "tampaknya keluar dari torpedo.";

$l_att_anobeams = "Anda telah kehabisan energi sinar kapal Anda.";
$l_att_anobeamsf = "Anda telah kehabisan energi berkas kapal Anda dan tidak dapat menyerang musuh pejuang.";
$l_att_anobeamst = "Anda telah kehabisan energi berkas kapal Anda dan tidak dapat menyerang musuh torpedo.";
$l_att_anofighters = "Kapal anda telah habis semua availible pejuang.";
$l_att_anotorps = "Anda telah kehabisan torpedo availible Anda.";
$l_att_imtitle = "Kapal Under Attack";
$l_att_imbody = "menyerang kapal Anda.";

$l_att_luckybeams = "Balok musuh menimbulkan overload";
$l_att_luckyfighters = "Musuh pejuang membuat kejutan dan menyebabkan serangan keringanan";
$l_att_luckytorps = "Torpedo musuh menimbulkan efek cascading menyebabkan kerusakan";
$l_att_luckytimes = "kali kerusakan normal!";
?>
