<?php
$l_pre_title = "Mengubah preset Realspace";
$l_pre_exceed = "Preset [preset] alam semesta melebihi maks dari [sector_max]. Tidak ada preset disimpan. <BR><BR>";
$l_pre_set = "Preset";
$l_pre_save = "Simpan";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] adalah nama sektor yang tidak valid.";
$l_pre_invalidchange = "[sector] adalah Kejadian Sektor Sektor. Preset lama Anda tidak berubah.";
?>
