<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] hit [chm_roll] di sektor tambang [chm_sector].";
$l_chm_youlostminedeflectors = "Kau kehilangan [chm_roll] deflectors tambang.";
$l_chm_youlostallminedeflectors = "Anda kehilangan semua milikku deflectors Anda.";
$l_chm_youhadnominedeflectors = "Anda tidak memiliki tambang deflectors.";
$l_chm_yourshieldshitforminesdmg = "Perisai Anda dipukul untuk [chm_mines_left] kerusakan.";
$l_chm_yourshieldsaredown = "Perisai Anda menurun!";
$l_chm_youlostallyourshields = "Anda kehilangan semua perisai!";
$l_chm_yourarmorhitforminesdmg = "Anda terkena baju besi untuk [chm_mines_left] kerusakan.";
$l_chm_yourhullisbreached = "Hull Anda dilanggar!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] dihancurkan oleh Anda di sektor tambang [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Kapal Anda telah dihancurkan!";
$l_chm_luckescapepod = "Untungnya Anda memiliki pod pelarian!";

$l_chm_yourdeflectormalf1 = "Mine deflektor sistem meluncurkan berfungsi.";
$l_chm_yourdeflectormalf2 = "Anda hanya dapat memulai";
$l_chm_yourdeflectormalf3 = "persen saya deflectors Anda.";
$l_chm_enemytorpfailshields = "tidak meluncurkan torpedo apapun terhadap perisai Anda.";
$l_chm_enemytorpfailarmor = "tidak meluncurkan torpedo apapun terhadap baju besi Anda.";

$l_chm_minemalf1 = "Pertambangan musuh telah berfungsi.";
$l_chm_minemalf2 = "Hanya";
$l_chm_minemalf3 = "persen menyerang ditemukan tambang kapal Anda.";

$l_chm_youhitsomemines = "Anda menekan [chm_roll] tambang keluar dari [total_mines] tambang!";
$l_chm_yourdeflectormalf2a = "Anda hanya bisa memulai [deflectors] persen dari saya deflectors Anda.";
$l_chm_mines_destroyed = "[number] dari [target] ranjau telah dihancurkan!";
$l_chm_mine_deflectors_left = "Anda telah [number] tambang deflectors kiri.";
$l_chm_mines_left = "Ada [number] tambang kiri dan mereka yang berdampak pada baju besi Anda!";
$l_chm_minemalf2a = "Hanya [deflectors] persen dari tambang menyerang menemukan kapal Anda.";
$l_chm_mines_exhausted = "[player] Pertambangan Lelah!";
$l_chm_armor_left = "Anda telah [number] zirah poin kiri!";

?>
