<?php
$l_gns_title = "Gunakan Kejadian Device";
$l_gns_turn = "Anda memerlukan setidaknya satu giliran untuk menggunakan perangkat genesis.";
$l_gns_onplanet = "Anda tidak dapat menggunakan perangkat ini saat berada di permukaan planet.";
$l_gns_full = "Tata surya ini sudah penuh.";
$l_gns_planetex = "Sudah ada planet di sektor ini.";
$l_gns_nogenesis = "Anda tidak memiliki perangkat genesis.";
$l_gns_forbid = "Menciptakan sebuah planet di sektor ini tidak diijinkan.";
$l_gns_bforbid = "Base di sektor ini mengganggu perangkat asal Anda. Penciptaan planet tidak mungkin.";
$l_gns_pcreate = "Planet diciptakan.";
$l_sgns_title = "Gunakan Kejadian Sektor Device";
$l_sgns_pcreate = "Sektor [name] diciptakan.";
$l_sgns_nogenesis = "Anda tidak memiliki asal-usul sektor perangkat.";
$l_sgns_forbid = "Membuat lubang cacing asal sektor di sektor ini tidak diijinkan.";
$l_sgns_forbid1 = "Membuat lubang cacing asal sektor Sektor Federasi tidak diijinkan.";
$l_sgcreate = "Buat Sektor Kejadian Sektor";
$l_sgcreatens = "Buat Sektor Kejadian Link kembali ke ruang dikenal";
$l_sgns_forbid2 = "Lebih dari [limit] link di Sektor SG tidak diijinkan.";
$l_sgns_forbid3 = "Tidak dapat menciptakan warp Kejadian Sektor link dari sektor saat ini - yang akan melebihi maksimum [limit] per sektor.";
$l_sgns_nocredits = "Anda tidak memiliki cukup kredit untuk menciptakan sektor baru.";
$l_sgns_shipcredits = "Kredit di kapal:";
$l_sgns_createcost = "Biaya untuk menciptakan Sektor:";
$l_sgns_complete = "Normal Space Link Lengkap";
$l_sgns_sectorname = "Sektor Masukkan Nama:";
$l_gns_max_unbased_planets = "Federasi tidak akan membiarkan anda menciptakan lebih planet sampai Anda memiliki kurang dari [max_unbased_planets] unbased planet.";

?>
