<?php
$l_chf_youretreatback = "Anda mundur kembali ke lokasi sebelumnya";
$l_chf_movefailed = "Pindah gagal.";
$l_chf_thefightersdetectyou = "Pejuang mendeteksi Anda!";
$l_chf_therearetotalfightersindest = "Ada [chf_total_sector_fighters] pejuang di sektor tujuan Anda.";
$l_chf_youcanretreat = "<B>Retreat</b> - Apakah biaya ekstra giliran.";
$l_chf_inputfight = "<B>Fight</b> - Anda harus mengalahkan semua pejuang untuk memasuki sektor.";
$l_chf_inputcloak = "<B>Jubah</b> - Gunakan perangkat cloaking Anda dan mencoba untuk menghindari para pejuang.";
$l_chf_go = "Pergi";
$l_chf_inputrun = "<B>Serangan dan Run</b> - Anda melakukan serangan keringanan berlari dan mundur. Tapi Anda MUNGKIN mengambil beberapa kerusakan selama retret.";
?>
