<?php
$l_novabomb_turns = "Bom Nova membutuhkan atleast [turns] berubah menjadi api.";
$l_novabomb_planetsdamaged = "Planet rusak oleh Nova Bomb";
$l_novabomb_planet = "Planet [name] menderita kerusakan dari Nova Bomb.";
$l_novabomb_novaexplode = "Nova Bom itu meledak ketika dipecat dan kapal Anda telah menderita kerusakan besar.";
$l_novabomb_novaexplode2 = "Nova Bom itu meledak ketika dipecat dan kapal anda hancur.";
$l_novabomb_notfedsec = "Nova Bom tidak dapat digunakan pada sektor milik Federasi.";
$l_novabomb_destroyed_planet = "Nova Anda bom retak permukaan planet dan dilatihkan ke dalam inti tempat itu meledak menyebabkan planet hancur.";
$l_novabomb_wrongclass = "Kelas kapal ini tidak dapat memecat seorang Bomb Nova Device.";
$l_novabomb_nonova = "Anda tidak memiliki Bomb Nova diinstal.";
$l_novabomb_novamiss = "Bom Nova rindu sempit tapi menimbulkan kerusakan pada planet ini.";
$l_novabomb_success = "Sektor [sector] telah Nova Dibom!";
$l_novabomb_mines = "Hancur [mines] sektor Pertambangan.";
$l_novabomb_fighters = "Hancur [fighters] sektor Fighters.";
$l_novabomb_shipsdamaged = "Kapal rusak oleh Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] menderita kerusakan dari Nova Bomb.";
$l_novabomb_ship_survived = "Kapal anda cukup jauh ketika bom meledak Nova untuk menghindari kerusakan.";
?>
