<?php
$l_ship2_buytitle = "Membeli kapal baru";
$l_ship2_storetitle = "Kapal Fasilitas Penyimpanan";
$l_ship2_wrongclass = "Salah kelas kapal ditentukan";
$l_ship2_buying = "Anda membeli:";
$l_ship2_tradein = "Perdagangan Dalam:";
$l_ship2_value = "Kapal saat ini Nilai:";
$l_ship2_newvalue = "Kapal Baru Nilai:";
$l_ship2_totalcost = "Total Biaya:";
$l_ship2_nomoney = "Anda tidak memiliki cukup kredit untuk membeli kapal ini.";
$l_ship2_purchase = "Membeli";
$l_ship2_buynstore = "Buy New kapal dan menyimpan lama";
$l_ship2_nomoney2 = "Anda tidak memiliki cukup kredit untuk menyelesaikan transaksi ini.";
$l_ship2_paystorage = "Anda telah menghapus Anda dari penyimpanan kapal.";
$l_ship2_turns = "Anda memerlukan paling sedikit [turns] bergantian untuk melakukan tindakan ini";
$l_ship2_error = "Kesalahan internal. Tidak dapat menemukan kapal kelas.";
$l_ship2_owned = "Anda telah memiliki kapal model ini.";
$l_ship2_shipbought = "Anda baru saja membeli sebuah kapal baru!";

?>
