<?php
$l_warp_linkto = "Link memimpin dari sektor ini untuk";
$l_warp_nolink = "Tidak ada link keluar dari sektor ini.";
$l_warp_query = "Sektor apa yang akan Anda ingin membuat link ke?";
$l_warp_oneway = "Satu arah?";
$l_warp_dest = "Bergantian, Anda mungkin menghancurkan link ke sektor.";
$l_warp_destquery = "Sektor apa yang ingin Anda menghapus link ke?";
$l_warp_bothway = "Kedua-cara";
$l_warp_create = "Buat warp antara Sektor:";
$l_warp_andsector = "dan Sektor:";
$l_warp_distance = "dengan jarak";
$l_warp_lightyears = "tahun cahaya";
$l_warp_delete = "Warp menghapus link antara Sektor:";
$l_warp_costcreate = "Biaya untuk membuat:";
$l_warp_costdelete = "Biaya untuk menghapus:";
$l_warp_costenergy = "Energi yang diperlukan:";
$l_warp_twoerror = "Menggunakan Warp Editor untuk membuat dua arah link ke sektor [target_sector] tidak diizinkan.";
?>
