<?php
$l_opt_title = "Pilih salah satu Avatar";
$l_opt_errorsize = "Error: Gambar Anda tidak boleh lebih besar dari ukuran 64x64 piksel.";
$l_opt_errortype = "Error: gambar harus JPG, GIF, atau PNG";
$l_opt_errornographic = "Kesalahan: tidak ada grafis dipilih.";
$l_opt_currentavatar = "Anda Avatar";
$l_opt_uploadavatar = "Meng-upload Avatar";
$l_opt_directory = "Pilih Avatar Directory";
$l_opt_change = "Ubah Directory";
$l_opt_select = "Pilih Avatar";
$l_opt_inuse = "Semua Avatars dalam direktori ini sedang digunakan.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
