<?php
$l_shipyard_title = "Galangan";
$l_planet = "Planet";
$l_ship_welcome = "Selamat Datang Planetary Anda galangan kapal. Saat ini kami menawarkan model-model ini untuk dijual.";
$l_ship_class = "Kelas";
$l_ship_properties = "Kelas Properties";
$l_ship_current = "Saat ini";
$l_ship_outstorage = "Keluar dari Storage";
$l_ship_storagecost = "Biaya penyimpanan";
$l_ship_storagewarn = "Setelah Anda mengambil Pioneer Anda dari gudang Anda akan longgar yang anda dikeluarkan atas kapal awal Anda kehancuran.";
$l_ship_levels = "Tingkat Komponen Kapal";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Harga";
$l_ship_turns = "Berubah untuk membangun";
$l_ship_purchase = "Membeli";
$l_ship_stored = "Disimpan";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Maksimum rata-rata Tech Level:";
$l_ship_averagenormaltech = "Normal rata Tech Level:";
$l_ship_averagecurrenttech = "Rata-rata Current Tech Level:";
?>
