<?php
$l_login_sclosed = "Server Ditutup";
$l_login_closed_message = "Server ditutup sampai pemberitahuan lebih lanjut.";
$l_login_title2 = "Login Tahap Dua";
$l_login_banned = "<b>Anda telah dilarang dari permainan ini oleh administrator. Anda tidak lagi diterima untuk bermain di server ini. Lain kali, berperilaku.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "Karena seriusnya kejahatan ini dan serangan keji terhadap Anda, Federasi telah berbaik hati memutuskan untuk menyediakan gratis kloning dari tetap Anda. Sayangnya, bahkan di zaman ini, klon baru tidak dapat memiliki harta, selain dari dasar-dasar untuk mencari nafkah. Anda akan diberikan dengan kapal dasar dan beberapa kredit untuk Anda mulai. Mudah-mudahan kehidupan berikutnya Anda akan lebih baik.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Kau tidak melarikan diri polong, dan karena sederhana Anda kesuksesan dalam hidup ini, Federasi menurun untuk mengkloning Anda. Anda tetap harus akhirnya jatuh ke dalam gravitasi baik, mudah-mudahan akan digunakan untuk menciptakan kehidupan di tempat lain ... beberapa milyar tahun dari sekarang. <BR><BR> Lebih beruntung pertandingan berikutnya ...";
$l_login_4gotpw1 = "Sandi yang Anda masukkan salah. <BR><BR> Jika Anda lupa sandi,";
$l_login_4gotpw2 = "memilikinya e-mail kepada Anda. <BR><BR> Jika tidak,";
$l_login_4gotpw3 = "untuk mencoba lagi. Usaha login dengan alamat IP";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Anda telah tewas dalam insiden mengerikan.";
$l_login_blackbox = "BlackBox adalah informasi yang diambil dari reruntuhan kapal Anda.";
$l_new_login = "untuk pergi ke layar login.";
$l_login_playerlimit = "Server telah mencapai jumlah maksimum pemain mendukung. Silakan coba log in di lain waktu.";
?>
