<?php
$l_nav_title = "Navigasi Komputer";
$l_nav_nocomp = "Komputer navigasi tidak tersedia";
$l_nav_query = "Masukkan sektor untuk menemukan jalan ke:";
$l_nav_pathfnd = "Path ditemukan";
$l_nav_answ1 = "Ini akan membawa Anda";
$l_nav_answ2 = "berubah untuk sampai ke sektor ini.";
$l_nav_proper = "Anda perlu meng-upgrade teknologi Teluk Fighter Anda sebelum pejuang Anda dapat menemukan rute warp untuk jarak.";
$l_nav_autoroutename = "Opsional Autoroute Nama:";
$l_nav_manuallist = "Dibangun manual WarpLink Autoroute Daftar";
$l_nav_warplinksleaving = "Link warp Meninggalkan [sector_name]";
$l_nav_nowarplinksleaving = "Tidak ada warplinks meninggalkan sektor ini.";
$l_nav_warp_from = "Warp dari";
$l_nav_rs_from = "RSMove dari";
$l_nav_notinlogs = "Tidak ada data yang tersedia di sektor ini.";
?>
