<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Tingkat Probe";
$l_probe_engine = "Mesin";
$l_probe_sensors = "Sensor";
$l_probe_cloak = "Jubah";
$l_probe_title = "Space Probe Menu";
$l_probe_none = "Anda tidak berada dalam sektor yang sama probe ini, sehingga Anda tidak dapat berinteraksi dengannya.";

$l_probe_named = "Welcome to Probe Nomor [probename], yang dimiliki oleh [name], yang terletak di sektor [sector].";
$l_probe_orders = "[orders] Probe untuk mencari alam semesta";
$l_probe_orders_link = "Program";
$l_probe_upgrade = "[upgrade] Probe Sensor / Engine / Jubah";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] Probe untuk nanti penempatan";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Pembaruan";

$l_probe_att_link = "Serangan";
$l_probe_att = "[attack] pada probe";
$l_probe_att_sure = "Apakah Anda YAKIN ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] probe";

$l_probe_unknown = "Unknown";
$l_plant_scn_turn = "Anda memerlukan setidaknya satu giliran untuk memindai probe.";
$l_probe_noscan = "Sensor tidak bisa mendapatkan perbaikan pada sasaran!";
$l_probe_logscanA = "[name] berusaha untuk memindai salah satu probe di sektor [sector], tapi gagal.";
$l_probe_logscanB = "Salah satu probe di sektor [sector] telah discan oleh [name].";
$l_probe_scn_report = "Hasil scan pada [name], yang dimiliki oleh: [owner]";

$l_probe_caplog = "Anda probe &#39;[probename]&#39; di sektor [sector] ditangkap oleh [name].";
$l_probe_scan = "Probe sektor scan [sector] dan mendapatkan:";
$l_probe_destroyprobe = "Hancurkan probe";
$l_probe_destroyed = "Probe Rusak!!";
$l_probe_warning = "Melakukan hal ini akan benar-benar menghancurkan probe ini";
$l_probe_confirm = "Apakah Anda benar-benar ingin menghancurkan probe ini?";
$l_gns_turn = "Anda tidak memiliki cukup berubah untuk menghancurkan probe ini";
$l_probe_type = "Probe Type";
$l_probe_type0 = "Stationary Probe";
$l_probe_type1 = "Penjaga Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sequential Realspace Probe";
$l_probe_target = "Target Sektor";
$l_probe_ordered = "Probe diprogram dan akan mulai mencari.";
$l_probe_order2 = "Probe adalah [type] dan sektor menargetkan [target]";
$l_probe_pickedup = "Probe memungut dan ditempatkan dalam penyimpanan aktif";
$l_probe_title = "Probe Menu";
$l_probe_messages = "untuk melihat apa yang mata-mata Anda telah terdeteksi.";

$l_probe_defaulttitle1 = "Aktif Probe";
$l_probe_defaulttitle2 = "Probe Anda telah memilih";
$l_probe_defaulttitle3 = "Probe di planet";
$l_probe_defaulttitle4 = "Probe di kapal";
$l_probe_linkback = "untuk pergi ke menu probe.";
$l_probe_no1 = "Anda tidak memiliki probe aktif.";
$l_probe_no2 = "Anda tidak memiliki probe di gudang.";
$l_probe_no3 = "Anda tidak memiliki probe di planet.";
$l_probe_no4 = "Anda tidak memiliki probe di kapal Anda.";
$l_probe_noprobeatall = "Anda tidak memiliki probe.";
$l_probe_notknown = "Unknown";
$l_probe_launch = "Jatuh";
$l_probe_detect = "Terdeteksi";
$l_probe_codenumber = "Kode";
$l_probe_job = "Pekerjaan";
$l_probe_percent = "Persen";
$l_probe_move = "Gerakan";
$l_probe_view = "Melihat";
$l_probe_action = "Aksi";
$l_probe_shipowner = "Pemilik kapal";
$l_probe_shipname = "Nama Kapal";
$l_probe_shiptype = "Kelas Kapal";
$l_probe_shiplocation = "Kapal Lokasi";
$l_probe_planetowner = "Planet Pemilik";
$l_probe_planetname = "Planet";
$l_probe_sector = "Current Sektor";
$l_probe_tsector = "Target Sektor";
$l_probe_type = "Probe Type";
$l_probe_forbid = "Anda tidak bisa drop probe di sektor ini";

$l_probe2_title = "Memulai Space Probe";
$l_probe2_turn = "Anda memerlukan setidaknya satu giliran untuk menggunakan ruang pemeriksaan.";
$l_probe2_onplanet = "Anda tidak dapat menggunakan perangkat ini saat berada di permukaan planet.";
$l_probe2_noprobe = "Anda tidak memiliki ruang probe.";
$l_probe2_forbid = "Meluncurkan probe di sektor ini tidak diijinkan.";
$l_probe2_launched = "Space probe diluncurkan!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Player";
$l_probe2_onboarda = "pada naik";
$l_probe2_classship = "kelas kapal";
$l_probe2_traveled = "bepergian ke sektor";
$l_probe2_fedjammed = "Federasi jamming semua sensor scan untuk Sektor 1.";
$l_probe2_lastseen = "Kapal Last Seen";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Mendukung";
$l_probe2_planets = "planet";
$l_probe2_sectord = "Sektor pertahanan Terdeteksi";
$l_probe2_mines = "Tambang";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Kapal Terdeteksi";
$l_probe2_ships2 = "Kapal Terdeteksi";
$l_probe2_noneowned = "Tidak ada planet yang tidak dimiliki oleh Anda telah terdeteksi.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Tidak ada yang Terdeteksi";
$l_probe2_nocredits = "Anda tidak memiliki cukup kredit untuk transaksi ini. Biaya total [total] kredit dan Anda hanya memiliki [credits] kredit.";

$l_probe_forbidSG = "Anda tidak dapat mengirim jenis Realspace penyelidikan Sektor Kejadian diciptakan sektor.";
$l_probe_forbidFED = "Anda tidak dapat mengirim jenis Realspace penyelidikan Federasi atau dimiliki Aliansi sektor.";
$l_probe_forbidINVALID = "Sektor tujuan Anda adalah nama sektor yang tidak valid.";
?>
