<?php
$l_s_yes = "Ya";
$l_s_no = "Tidak";
$l_s_enabled = "Diaktifkan";
$l_s_disabled = "Cacat";

$l_s_modules = "Modul";
$l_s_modulename = "Nama Modul";
$l_s_moduleauthor = "Author";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "Tidak Modul Loaded";

$l_s_gamestatus = "Game Status";
$l_s_allowpl = "Izinkan Pemain";
$l_s_allownewpl = "Izinkan Pemain Baru";

$l_s_gameoptions = "Game Pilihan";
$l_s_allowteamplcreds = "Biarkan Tim Planet Credit Transfer";
$l_s_allowfullscan = "Biarkan Kendali Long Range Scan";
$l_s_sofa = "Izinkan Sub-Orbital Fighter Attacks";
$l_s_showpassword = "Tampilan Password pada Mendaftarkan";
$l_s_genesisdestroy = "Kejadian torps dapat menghancurkan planet";
$l_s_igb = "Intergalaksi Bank (igb)";
$l_s_ksm = "Dikenal Space Maps";
$l_s_navcomp = "Navigasi Komputer";
$l_s_newbienice = "Newbie Nice";
$l_s_spies = "Sistem spy";
$l_s_spycapture = "Biarkan Spies untuk menangkap planet";

$l_s_gamesettings = "Pengaturan permainan";
$l_s_gameversion = "Game versi:";
$l_s_minhullmines = "Ukuran lunas minimum yang diperlukan untuk memukul tambang";
$l_s_averagetechewd = "Tek rata-rata tingkat degradasi Ketika Warp Darurat";
$l_s_numsectors = "Jumlah Sektor";
$l_s_maxwarpspersector = "Link maksimum per sektor";
$l_s_averagetechfed = "Maksimum rata-rata tingkat teknologi untuk Federasi Sektor";
$l_s_igbirateperupdate = "Suku bunga per igb update";
$l_s_igblrateperupdate = "Pinjaman bunga per igb update";
$l_s_techupgradebase = "Tingkat tech upgrade untuk Bases";
$l_s_collimit = "Koloni Batas";
$l_s_maxturns = "Jumlah maksimum akumulasi berubah";
$l_s_maxplanetssector = "Jumlah maksimum per sektor planet";
$l_s_maxtraderoutes = "Jumlah maksimum per pemain traderoutes";
$l_s_colreprodrate = "Kelahiran penjajah Rate";
$l_s_energyperfighter = "Satuan Energi yang digunakan per sektor tempur";
$l_s_secfighterdegrade = "Sektor tempur degradasi tingkat persentase";
$l_s_planetinterest = "Bunga Planet";
$l_s_spiesperplanet = "Mata-mata jumlah maksimum per planet";
$l_s_spysuccessfactor = "Mata-mata faktor sukses";
$l_s_spykillfactor = "Membunuh mata-mata faktor";
$l_s_colsperfighter = "Koloni diperlukan untuk menghasilkan 1 Fighter setiap giliran";
$l_s_colspertorp = "Koloni diperlukan untuk menghasilkan 1 Torpedo setiap giliran";
$l_s_colsperore = "Koloni diperlukan untuk menghasilkan 1 Bijih setiap giliran";
$l_s_colsperorganics = "Koloni diperlukan untuk menghasilkan 1 Organik setiap giliran";
$l_s_colspergoods = "Koloni diperlukan untuk menghasilkan 1 Barang setiap giliran";
$l_s_colsperenergy = "Koloni diperlukan untuk menghasilkan 1 Energi setiap giliran";
$l_s_colspercreds = "Koloni diperlukan untuk menghasilkan 1 Credits setiap giliran";
$l_s_colsper = "Koloni diperlukan untuk menghasilkan 1 [commodity] setiap giliran";

$l_s_gameschedsettings = "Penjadwal Pengaturan permainan";
$l_s_schedtype = "Jenis scheduler";
$l_s_cronbased = "Cron Berdasarkan";
$l_s_playertriggered = "Pemain Dipicu";
$l_s_minutes = "menit";
$l_s_ticksupdate = "Ticks terjadi setiap";
$l_s_turnsupdate = "Ternyata akan terjadi setiap";
$l_s_npcupdate = "Aliansi akan memainkan setiap";
$l_s_igbturnsupdate = "Kepentingan pada account igb akan terakumulasi setiap";
$l_s_newsupdate = "Berita akan dihasilkan setiap";
$l_s_planetupdate = "Planet akan menghasilkan produksi setiap";
$l_s_spyupdate = "Spies akan bertindak setiap";
$l_s_portsupdate = "Ports akan diperbarui setiap";
$l_s_towupdate = "Kapal akan diderek dari sektor makan setiap";
$l_s_scoreupdate = "Peringkat akan dihasilkan setiap";
$l_s_secdefdegrupdate = "Sektor pertahanan akan menurunkan setiap";
$l_s_apocalypseupdate = "Planet kiamat akan terjadi setiap";
$l_s_release_version = "Game versi rilis";
$l_s_time_since_reset = "Sisa sejak terakhir reset";
$l_s_independence = "Planet Kemerdekaan";
$l_s_dignitaryupdate = "Pejabat akan bertindak setiap";

$l_s_turnsupdate = "berubah setiap";
?>
