<?php
$l_defense_deploy_title = "Menyebarkan Sektor Pertambangan &amp; Fighters";
$l_defense_deploy_noturn = "Anda memerlukan setidaknya satu giliran untuk menyebarkan sektor pertahanan.";
$l_defense_deploy_nopermit = "Menggelar Pertambangan dan Fighters di sektor ini tidak diijinkan.";
$l_defense_deploy_nodeploy = "Tidak dapat menyebarkan di sini. Kapal lain atau Tim ranjau atau pejuang di sektor ini.";
$l_defense_deploy_info1 = "Anda saat ini di sektor [sector]. Ada [mines] tambang dan [fighters] pejuang di sini.";
$l_defense_deploy_info2 = "Anda telah [mines] tambang dan [fighters] pejuang yang tersedia untuk menempatkan";
$l_defense_deploy_deploy = "Menyebarkan";
$l_defense_deploy_deployed = "Dikerahkan";
$l_defense_deploy_att = "Serangan";
$l_defense_deploy_notorps = "Anda tidak memiliki cukup torpedo.";
$l_defense_deploy_nofighters = "Anda tidak memiliki cukup pejuang";
$l_defense_deploy_dmines = "Ditugaskan [mines] tambang.";
$l_defense_deploy_dfighter = "Ditugaskan [fighters] pejuang.";
$l_defense_deploy_max_fighters = "Sektor ini dapat mendukung maksimum [amount] pejuang.";
$l_defense_deploy_toomanyfighters = "Anda telah mencoba mengerahkan lebih banyak pesawat tempur daripada sektor dapat mendukung.";
?>
