<?php
$l_by_title = "Karunia";
$l_by_noturn = "Anda memerlukan setidaknya satu giliran tempat atau memodifikasi karunia.";
$l_by_amount = "Bounty Jumlah";
$l_by_place = "Tempat Bounty";
$l_by_nobounties = "Saat ini tidak ada karunia.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Ditempatkan oleh";
$l_by_thefeds = "Federasi";
$l_by_cancel = "Batal";
$l_by_yourself = "Anda tidak dapat menempatkan sebuah hadiah pada diri Anda.";
$l_by_notenough = "Anda tidak memiliki cukup kredit untuk menempatkan suatu karunia dari jumlah itu.";
$l_by_toomuch = "Anda tidak dapat tempat yang karunia. Maksimum hadiah diijinkan pada pemain lain adalah [percent] persen dari kekayaan bersih Anda";
$l_by_zeroamount = "Karunia harus lebih besar dari 0 kredit.";
$l_by_placed = "Karunia telah ditempatkan.";
$l_by_nobounty = "Bahwa karunia tidak ada lagi.";
$l_by_notyours = "Itulah karunia tidak ditempatkan oleh Anda.";
$l_by_canceled = "Karunia telah dibatalkan.";
$l_by_action = "Aksi";
$l_by_placebounty = "Tempat atau melihat karunia.";
$l_by_moredetails = "Klik pada nama untuk rincian lebih lanjut.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "Pemain Anda menempatkan karunia pada tidak ada.";
$l_by_destroyed = "Anda tidak dapat menempatkan sebuah hadiah pada pemain dengan kapal yang rusak.";
$l_by_nofedbounty = "Anda tidak akan menerima hadiah jika Anda menyerang pemain ini kapal atau planet.";
$l_by_fedcollectonly = "Hanya Federasi dapat Kumpulkan Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Anda tidak akan menerima hadiah jika Anda menempatkan memata-matai pemain ini planet ini.";
$l_pay_partial = "Lakukan Pembayaran Partial";
$l_pay_button = "Bayar";

$l_by_thealliance = "Aliansi";
$l_by_alliancecollectonly = "Hanya Aliansi dapat Kumpulkan Bounty";
$l_by_bountyscan = "Bounty";
?>
