<?php
$l_ze_title = "Edit Zone";
$l_ze_notowner = "Anda tidak pemilik zona ini sehingga Anda tidak dapat mengeditnya.";
$l_ze_name = "Nama Zona";
$l_ze_allow = "Mengizinkan";
$l_ze_attacks = "Izinkan menyerang kapal-kapal lain";
$l_ze_genesis = "Memungkinkan menciptakan planet baru";
$l_ze_return = "untuk kembali ke halaman informasi zona";
$l_ze_saved = "Perubahan Anda telah disimpan.";
$l_ze_namematch = "ERROR: The Zone Nama yang Anda berikan yang mirip atau cocok dengan Nama Zona yang ada.";
?>
