<?php
$l_mail_title = "Password";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Password telah dikirim ke";
$l_mail_topic = "$ game_name Password";
$l_mail_message = "Salam, \ n \ nSomeone dari alamat IP $ ip meminta sandi Anda untuk $ game_name dapat dikirim kepada Anda \ n \ nYour password: [pass] \ n \ nThank Anda \ n \ nThe $ game_name tim Web.";
$l_new_login = "untuk pergi ke layar login.";
$l_mail_failed = "Password gagal untuk mengirim ke";
?>
