<?php
///SPIES
$l_dig_title = "Pembesar Menu";
$l_dig = "Tokoh";
$l_dig_disabled = "Dignataries dinon-aktifkan!";
$l_dig_noturn = "Anda memerlukan setidaknya satu giliran untuk mengirim pembesar ke planet.";
$l_dig_notonboard = "Anda tidak memiliki pembesar di kapal.";
$l_dig_ownplanet = "Anda tidak dapat mengirim pembesar ke planet musuh.";
$l_dig_unownedplanet = "Anda tidak dapat mengirim pembesar untuk unowned planet.";
$l_dig_planetfull = "Sudah ada diperbolehkan [max] pejabat di planet itu.";
$l_dig_sendtitle = "Mengirim pembesar [digID] untuk planet: <BR> Pilih pembesar misi:";

$l_dig_codenumber = "Kode";
$l_dig_job = "Pekerjaan";
$l_dig_percent = "Persen";
$l_dig_move = "Gerakan";
$l_dig_action = "Aksi";
$l_dig_shipowner = "Pemilik kapal";
$l_dig_shipname = "Nama Kapal";
$l_dig_shiptype = "Kelas Kapal";
$l_dig_shiplocation = "Kapal Lokasi";
$l_dig_planetowner = "Planet Pemilik";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sektor";

$l_dig_waiting = "Menunggu Job";
$l_dig_max = "Maksimum Per Planet";
$l_dig_legend = "Pembesar Legend";
$l_dig_description = "Pembesar Deskripsi";
$l_dig_waiting_description = "Pembesar akan menciptakan torpedo dan pejuang sambil menunggu tugas pekerjaan.";
$l_dig_changeerror = "Pembesar Job Change Report";

$l_dig_nospieshere = "Anda tidak memiliki kehormatan di planet ini!";
$l_dig_transferred = "tokoh ditransfer";
$l_dig_backonship = "Pembesar sekarang di kapal.";
$l_dig_dismiss = "Hilangkan Pembesar?";
$l_dig_changebutton = "Mengubah";
$l_dig_notyourplanet = "Itu bukan planet.";

$l_dig_defaulttitle1 = "Pejabat pada kapal musuh";
$l_dig_defaulttitle2 = "Tokoh di planet";
$l_dig_defaulttitle3 = "Tokoh di planet";
$l_dig_defaulttitle4 = "Pejabat di kapal";

$l_dig_no1 = "Anda tidak memiliki pejabat pada kapal musuh.";
$l_dig_no2 = "Anda tidak memiliki kehormatan di planet.";
$l_dig_no3 = "Anda tidak memiliki kehormatan di planet.";
$l_dig_no4 = "Anda tidak memiliki kehormatan di kapal Anda.";
$l_dig_nodignitaryatall = "Anda tidak memiliki kehormatan.";
$l_dig_notknown = "Unknown";
$l_dig_dismiss = "Hilangkan";
$l_dig_dismiss2 = "Pejabat dipecat.";
$l_dig_menu = "untuk kembali ke Menu berkedudukan tinggi.";

?>
