<?php
$l_zi_title = "Zona Informasi";
$l_zi_nexist = "Bagian ini ruang tidak ada!";
$l_zi_feds = "Federasi";
$l_zi_traders = "Aliansi Space";
$l_zi_nobody = "Tidak ada";
$l_zi_war = "Ruang diperebutkan";
$l_zi_allow = "Diizinkan";
$l_zi_notallow = "Tidak boleh";
$l_zi_limit = "Terbatas pada pemilik dan sekutu";
$l_zi_ul = "Unlimited";
$l_zi_control = "Anda memegang kendali zona ini";
$l_zi_tochange = "untuk mengubah undang-undang.";
$l_zi_owner = "Zona pemilik";
$l_zi_maxhull = "Maksimum rata-rata tingkat tech diperbolehkan";
?>
