<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Scanner Anda tidak memiliki rentang panjang penuh memindai kemampuan.";
$l_lrs_noturns = "Anda memerlukan setidaknya $ fullscan_cost gilirannya (s) untuk menjalankan scan penuh jangka panjang.";
$l_lrs_used = "Digunakan";
$l_lrs_turns = "gilirannya (s)";
$l_lrs_left = "kiri";
$l_lrs_reach = "Lokasi-lokasi berikut dapat dicapai dari sektor [sector]:";
$l_lrs_links = "Link";
$l_lrs_ships = "Kapal";
$l_lrs_click = "Klik salah satu link untuk pindah ke sektor tersebut.";
$l_lrs_cantscan = "Tidak dapat memindai sektor dari sektor saat ini!";
$l_lrs_zero = "Sektor 1 terlalu ramai untuk memindai kapal!";
$l_lrs_moveto = "pindah ke sektor";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "View Log";
$l_lrs_fedjammed = "Federasi jamming semua sensor scan.";
$l_lrs_sectormissile_question = "untuk sektor api rudal.";
$l_log_months = "array ( &#39;Januari&#39;, &#39;Februari&#39;, &#39;Februari&#39;, &#39;April&#39;, &#39;Maret&#39;, &#39;Juni&#39;, &#39;Juli&#39;, &#39;Agustus&#39;, &#39;September&#39;, &#39;Oktober&#39;, &#39;Nopember&#39;, &#39;Desember&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;Peb&#39;, &#39;Mar&#39;, &#39;Apr&#39;, &#39;Mei&#39;, &#39;Jun&#39;, &#39;Jul&#39;, &#39;Agustus&#39;, &#39;Sep&#39;, &#39;Okt&#39;, &#39;Nop&#39;, &#39;Des&#39;)";
?>
