<?php
$l_new_pwis = "Sandi Anda";
$l_new_charis = "Nama karakter";
$l_new_title2 = "Create New Player Tahap Dua";
$l_new_blank = "E-mail, nama kapal, dan nama karakter tidak boleh kosong.";
$l_new_inuse = "E-mail [username] yang telah digunakan.";
$l_new_forgotpw = "Lupa password Anda?";
$l_new_inusechar = "Nama karakter [character], sudah digunakan.";
$l_new_similar_inusechar = "Nama karakter Anda terdengar terlalu mirip untuk [character], sebuah nama yang sudah digunakan.";
$l_new_inuseship = "Nama kapal [shipname], sudah digunakan.";
$l_new_similar_inuseship = "Nama kapal Anda terdengar terlalu mirip dengan [shipname], sebuah nama yang sudah digunakan.";
$l_new_pwsent = "Password telah dikirim ke [username].";
$l_new_err = "Silakan coba lagi";
$l_new_topic = "Alien Assault Trader Password";
$l_new_message = "Salam, \ n \ nSomeone dari alamat IP $ ip meminta sandi Anda untuk Pedagang dikirimkan kepada Anda. \ N \ nYour password: [pass] \ n \ nThank Anda \ n \ nThe Pedagang tim Web.";
$l_new_invalidemail = "Alamat Email tidak valid.";
$l_new_tutorial = "Klik di sini untuk membaca Mini-Tutorial sebelum masuk ke permainan.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "untuk pergi ke layar login.";

?>
