<?php
$l_warp_unlinked = "Target sektor ([target_sector]) tidak memiliki link dari sektor ini.";
$l_warp_forbidtwo = "Menggunakan Warp Editor untuk menghapus link dua arah sektor [target_sector] tidak diizinkan.";
$l_warp_removed = "Link dihapus untuk";
$l_warp_removedtwo = "Link dihapus ke dan dari";
$l_warp_nomoney = "Anda tidak memiliki cukup kredit untuk menghapus link lungsin.";
$l_warp_noenergy = "Anda tidak memiliki energi yang cukup untuk menghapus link lungsin.";
?>
