<?php
///SPIES
$l_dig_title = "Menu Dignitari";
$l_dig = "Dignitari";
$l_dig_disabled = "Dignitari disabilitati!";
$l_dig_noturn = "Ti occorre almeno un turno per inviare un dignitario su un pianeta.";
$l_dig_notonboard = "Non hai alcun dignitario a bordo.";
$l_dig_ownplanet = "Non puoi inviare un dignitario su un pianeta nemico.";
$l_dig_unownedplanet = "Non puoi inviare un dignitario ad un pianeta di nessuno.";
$l_dig_planetfull = "Ci sono già [max] dignitari su questo pianeta.";
$l_dig_sendtitle = "Invio del degnitario [digID] al pianeta:<BR>Seleziona il suo incarico:";

$l_dig_codenumber = "Codice";
$l_dig_job = "Incarico";
$l_dig_percent = "Percento";
$l_dig_move = "Movimento";
$l_dig_action = "Azione";
$l_dig_shipowner = "Proprietario nave";
$l_dig_shipname = "Nome nave";
$l_dig_shiptype = "Classe nave";
$l_dig_shiplocation = "Posizione nave";
$l_dig_planetowner = "Proprietario pianeta";
$l_dig_planetname = "Pianeta";
$l_dig_sector = "Settore";

$l_dig_waiting = "In attesa di un lavoro";
$l_dig_max = "Massimo per Planet";
$l_dig_legend = "Dignitario Legend";
$l_dig_description = "Dignitario Descrizione";
$l_dig_waiting_description = "Dignitario creerà siluri e combattenti in attesa di una assegnazione di posti di lavoro.";
$l_dig_changeerror = "Dignitario Cambiare lavoro Report";

$l_dig_nospieshere = "Non hai dignitari su questo pianeta!";
$l_dig_transferred = "dignitari trasferiti";
$l_dig_backonship = "Il dignitario è ora sulla tua nave.";
$l_dig_dismiss = "Licenziare il dignitario?";
$l_dig_changebutton = "Cambia";
$l_dig_notyourplanet = "Non è il tuo pianeta.";

$l_dig_defaulttitle1 = "Dignitari su navi nemiche";
$l_dig_defaulttitle2 = "Dignitari sui tuoi pianeti";
$l_dig_defaulttitle3 = "Dignitari sui tuoi pianeti";
$l_dig_defaulttitle4 = "Dignitari sulla tua nave";

$l_dig_no1 = "Non hai dignitari su navi nemiche.";
$l_dig_no2 = "Non hai dignitari sui tuoi pianeti.";
$l_dig_no3 = "Non hai dignitari sui tuoi pianeti.";
$l_dig_no4 = "Non hai dignitari sulla tua nave";
$l_dig_nodignitaryatall = "Non hai dignitari.";
$l_dig_notknown = "Sconosciuto";
$l_dig_dismiss = "Licenzia";
$l_dig_dismiss2 = "Dignitari licenziati.";
$l_dig_menu = "per tornare al menu dei dignitari.";

?>
