<?php
$l_novabomb_turns = "The Bomb Nova richiede atleast [turns] si trasforma in fuoco.";
$l_novabomb_planetsdamaged = "Pianeti danneggiata dalla bomba Nova";
$l_novabomb_planet = "Planet [name] subito danni dalla bomba Nova.";
$l_novabomb_novaexplode = "Nova bomba è esplosa come è stato licenziato e la tua nave ha subito danni enormi.";
$l_novabomb_novaexplode2 = "Nova bomba è esplosa come è stato licenziato e la tua nave è stata distrutta.";
$l_novabomb_notfedsec = "Nova bomba non può essere utilizzato su Federazione di proprietà settori.";
$l_novabomb_destroyed_planet = "La tua bomba nova cracking la superficie del pianeta e forato nel nucleo, dove è esplosa causando il pianeta per distruggere.";
$l_novabomb_wrongclass = "Questa classe della nave non può sparare un dispositivo Nova Bomb.";
$l_novabomb_nonova = "Tu non avere una bomba Nova installato.";
$l_novabomb_novamiss = "The Bomb Nova manca in maniera restrittiva, ma danneggia sul pianeta.";
$l_novabomb_success = "Settore [sector], è stato Nova Bombed!";
$l_novabomb_mines = "Distrutti [mines] settore delle miniere.";
$l_novabomb_fighters = "Distrutti [fighters] Fighters settore.";
$l_novabomb_shipsdamaged = "Navi danneggiate dalla bomba Nova";
$l_novabomb_ship_damage = "Starship [shipname] subito danni dalla bomba Nova.";
?>
