<?php
$l_contact_admin_title = "Contatti Game Administrator";
$l_contact_admin_thanks = "Grazie per il tuo commento.";
$l_contact_admin_email_alert = "Si prega di inserire un indirizzo email valido.";
$l_contact_admin_name_alert = "Inserisci il tuo nome.";
$l_contact_admin_comment_alert = "Si prega di inserire i tuoi commenti.";
$l_contact_admin_name = "Nome";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Domanda / Commento";
$l_contact_admin_submit = "Invia Domande / Commenti";
$l_contact_admin_close = "Chiudi finestra";
$l_contact_admin_thanks_comment = "Grazie per il tuo commento o domanda. Ci saranno tutte le domande e indirizzo e-mail con la nostra risposta.";

?>
