<?php
$l_casino_title	=	"Casinò";
$l_casino_welcome	=	"Benvenuti al Casinò, attualmente sono disponibili i seguenti Giochi e Locali";
$l_casino_option	=	"Stanze";
$l_casino_detail	=	"Dettagli";

// Blackjack
$l_bet		=	"Punta";
$l_stand	=	"Stai";
$l_hit		=	"Nuova Carta";
$l_firsthand		=	"Prima Mano";
$l_secondhand		=	"Seconda Mano";
$l_insurance = 	"Assicurazione";
$l_doubledown = "Raddoppia la posta";
$l_lobby	=	"Sala per il pubblico";
$l_split 	=   "Dividi";
$l_credits  =   "Crediti";
$l_yourbet	=	"Tua Puntata";
$l_nobet	=	"La tua Puntata ha superato il tuo limite di crediti, sei pregato di puntare di nuovo.";
$l_dealerwins = "Vince il Mazziere!";
$l_dealerbust = "Il Mazziere Sballa!";
$l_dealerloses = "Il Mazziere Perde!";
$l_dealerblackjack ="Il Mazziere fa Blackjack!";
$l_push = "PUSH";
$l_playerwins	=	"Vince il Giocatore!";
$l_playerbust	=	"Il Giocatore Sballa!";
$l_playerloses	=	"Il Giocatore Perde!";
$l_playerblackjack	=	"Il Giocatore fa BlackJack!";
$l_place_bet	=	"Piazza la tua Puntata";
?>
