<?php
$l_ze_title              = "Edita Zona";
$l_ze_notowner           = "Non sei il proprietario di questa zona, e non puoi editarla.";
$l_ze_name               = "Nome Zona";
$l_ze_allow              = "Permesso";
$l_ze_attacks            = "Permesso attaccare altre navi";
$l_ze_genesis            = "Permesso creare nuovi pianeti";
$l_ze_return             = "per tornare alla pagina informazioni sulla Zona";
$l_ze_saved              = "Le variazioni sono state salvate.";
$l_ze_namematch = "ERRORE: Il Nome della Zona che hai fornito è simile o uguale ad un altro nome, già in uso.";
?>
