<?php
$l_news_title = "Universe News";
$l_news_info             = "FNN è tra le maggiori agenzie per la<br>diffusione di notizie e bollettini.<br>Al lavoro 24 ore al giorno, sette giorni<br>la settimana, nel quartier generale situato<br>in Proxima Centauri e filiali in ogni galassia!";
$l_news_for              = "Notizie per";
$l_news_prev             = "giorno precedente";
$l_news_next             = "prossimo giorno";
$l_news_none             = "Spiacente, nessuna notizia oggi.";
$l_news_flash            = "Notizie flash";
$l_news_end              = "fine delle notizie";
$l_news_bestviewed = "Best viewed in Opera, Safari e Internet Explorer";
$l_news_fedannouncements = "Federazione Annunci";
$l_news_planetarynews = "Planetary News";
$l_news_planetshipnews = "Planetary and Ship News";
$l_news_afteractionnews = "Dopo l&#39;azione di combattimento News";

?>
