<?php
$l_ship2_buytitle        = "Acquisto Nuova Nave";
$l_ship2_storetitle = "Cantiere Storage Facility";
$l_ship2_wrongclass        = "Errata classe di nave specificata";
$l_ship2_buying        = "Stai per comprare:";
$l_ship2_tradein        = "Vendi la vecchia nave:";
$l_ship2_value        = "Valore attuale della nave:";
$l_ship2_newvalue        = "Nuovo valore della nave:";
$l_ship2_totalcost        = "Costo totale:";
$l_ship2_nomoney        = "Non hai abbastanza crediti per comprare questa nave.";
$l_ship2_purchase        = "Acquista";
$l_ship2_buynstore        = "Compra una nuova nave, e metti in deposito quella vecchia";
$l_ship2_nomoney2        = "Non hai abbastanza crediti per completare quest'operazione.";
$l_ship2_paystorage = "Il tuo stato rimosso la vostra nave da deposito.";
$l_ship2_turns        = "Ti occorrono almeno [turns] turni per attuare questa operazione";
$l_ship2_error        = "Errore interno. Impossibile trovare la classe della nave.";
$l_ship2_owned        = "Già possiedi questo modello di nave.";
$l_ship2_shipbought        = "Hai appena acquistato una nuova nave!";

?>
