<?php
$l_zi_title              = "Informationi Zona";
$l_zi_nexist             = "Questa seziopne di spazio non esiste!";
$l_zi_feds               = "Federatione";
$l_zi_traders            = "Spazio della Alliance";
$l_zi_nobody             = "Nessuno";
$l_zi_war                = "Spazio contestato";
$l_zi_allow              = "Permesso";
$l_zi_notallow           = "Non permesso";
$l_zi_limit              = "Limitato a proprietario ed alleati";
$l_zi_ul                 = "Illimitato";
$l_zi_control            = "Tu controlli questa Zona";
$l_zi_tochange           = "per cambiare le sue leggi.";
$l_zi_owner              = "proprietario Zona";
$l_zi_maxhull            = "Massimo livello tecnologico medio permesso";
?>
