<?php
$l_readm_title           = "Leggi Messaggio";
$l_readm_delete          = "MESSAGGIO CANCELLATO";
$l_readm_nomessage       = "Non hai Messaggi in arrivo...";
$l_readm_center          = "Centro Ricezione Messaggi";
$l_readm_sender          = "Mittente Messaggio";
$l_readm_captn           = "Capitano della nave";
$l_readm_del             = "Elimina";
$l_readm_repl            = "Rispondi";
$l_readm_return            = "Clicca qui per tornare al Menu principale";
$l_readm_title2            = "Lettura Messaggi";
$l_readm_delete            = "Elimina tutti";
$l_readm_subject            = "Oggetto";
$l_readm_quote            = "Quota";
$l_readm_block            = "Blocca mittente";
$l_readm_alert = "Sistema di allerta";
$l_readm_alertbody = "Nave Computer";
?>
