<?php
$l_s_yes               = "Si";
$l_s_no = "No";
$l_s_enabled           = "Abilitato";
$l_s_disabled          = "Disabilitato";

$l_s_modules           = "Moduli";
$l_s_modulename        = "Nome modulo";
$l_s_moduleauthor      = "Autore";
$l_s_moduleinfo = "Info";
$l_s_nomodules         = "Nessun modulo caricato";

$l_s_gamestatus        = "Stato del gioco";
$l_s_allowpl           = "Permette il gioco";
$l_s_allownewpl        = "Permette nuovi giocatori";

$l_s_gameoptions       = "Opzioni gioco";
$l_s_allowteamplcreds  = "Permetti Trasferimento crediti tra pianeti della Squadra";
$l_s_allowfullscan     = "Permetti la scannerizzazione completa";
$l_s_sofa              = "Permetti l'attacco suborbitale con i Droni";
$l_s_showpassword      = "Mostra la password durante la registrazione";
$l_s_genesisdestroy    = "Siluri Genesis possono distruggere i pianeti";
$l_s_igb               = "Banca InterGalattica (igb)";
$l_s_ksm               = "Mappa spazio conosciuto";
$l_s_navcomp           = "Computer di navigazione";
$l_s_newbienice        = "Protezione Newbie";
$l_s_spies             = "Sistema di spie";
$l_s_spycapture        = "Permetti alle spie di catturare i pianeti";

$l_s_gamesettings      = "Settaggi di gioco";
$l_s_gameversion       = "Versione gioco:";
$l_s_minhullmines      = "Minima dimensione Stiva per colpire le mine";
$l_s_averagetechewd    = "Livello tecnologico medio al quale il dispositivo Warp d'emergenza malfunziona";
$l_s_numsectors        = "Numero di settori";
$l_s_maxwarpspersector = "Massimo numero di rotte per settore";
$l_s_averagetechfed    = "Massimo livello tecnologico medio per i settori della Federazione";
$l_s_igbirateperupdate = "Interessi IGB per ogni aggiornamento";
$l_s_igblrateperupdate = "Interessi IGB sui prestiti per ogni aggiornamento";
$l_s_techupgradebase   = "Incremento livello tecnologico dato dalle basi";
$l_s_collimit          = "Limite di base coloni (a liv.tecn. zero)";
$l_s_maxturns          = "Max numero di turni accumulabili";
$l_s_maxplanetssector  = "Max numero di pianeti per settore";
$l_s_maxtraderoutes    = "Max numero di rotte commerciali per giocatore";
$l_s_colreprodrate     = "Tasso di natalità dei coloni";
$l_s_energyperfighter  = "Unità di Energia usata per ciascun Drone di difesa settore";
$l_s_secfighterdegrade = "Percentuale di perdita Droni di settore";
$l_s_planetinterest    = "Tasso di interessi del pianeta";
$l_s_spiesperplanet    = "Max numero di spie per pianeta";
$l_s_spysuccessfactor  = "Fattore di successo per le spie";
$l_s_spykillfactor     = "Fattore di uccisione delel spie";
$l_s_colsperfighter    = "Coloni necessari per produrre 1 Drone ciascun turno";
$l_s_colspertorp       = "Coloni necessari per produrre 1 siluro ciascun turno";
$l_s_colsperore        = "Coloni necessari per produrre 1 unità di metallo ciascun turno";
$l_s_colsperorganics   = "Coloni necessari per produrre 1 unità di organici ciascun turno";
$l_s_colspergoods      = "Coloni necessari per produrre 1 unità di prodotti ciascun turno";
$l_s_colsperenergy     = "Coloni necessari per produrre 1 unità di energia ciascun turno";
$l_s_colspercreds      = "Coloni necessari per produrre 1 credito ciascun turno";
$l_s_colsper      = "Coloni necessari per produrre 1 [commodity] ciascun turno";

$l_s_gameschedsettings = "Settaggi di programmazione delle fasi del gioco";
$l_s_schedtype         = "Tipo di programmazione";
$l_s_cronbased         = "Basato sul tempo";
$l_s_playertriggered   = "Basato sulle attività dal giocatore";
$l_s_minutes           = " minuti";
$l_s_ticksupdate       = "I Ticks occorrono ogni";
$l_s_turnsupdate       = "I turni vengono incrementati ogni";
$l_s_npcupdate       = "La Alliance giocherà ogni";
$l_s_igbturnsupdate    = "Gli interessi sui conti IGB saranno accreditati ogni ";
$l_s_newsupdate        = "Le News saranno generate ogni";
$l_s_planetupdate      = "I pianeti genereranno produzione ogni";
$l_s_spyupdate         = "Le spie agiranno ogni";
$l_s_portsupdate       = "I porti rigenereranno ogni";
$l_s_towupdate         = "Le navi saranno cacciate dai settori della Federazione ogni";
$l_s_scoreupdate       = "La classifica sarà generata ogni";
$l_s_secdefdegrupdate  = "Le difese del settore degraderanno ogni";
$l_s_apocalypseupdate  = "Le apocalissi planetarie succederanno ogni";
$l_s_release_version   = "Versione del gioco rilasciato";
$l_s_time_since_reset  = "Tempo dall'ultimo reset";
$l_s_independence   = "I pianeti potranno diventare Indipendenti ogni";
$l_s_dignitaryupdate   = "I Dignitari agiranno ogni";

$l_s_turnsupdate   = "turni ogni";
?>
