<?php
$l_new_pwis              = "La tua password è";
$l_new_charis            = "Il nome del tuo personaggio è";
$l_new_title2            = "Creazione Nuovo Giocatore Fase Due";
$l_new_blank             = "I campi E-mail, nome della nave e del giocatore non possono essere lasciati vuoti.";
$l_new_inuse             = "L'indirizzo E-mail [username], è già utilizzato.";
$l_new_forgotpw          = "Hai dimenticato la password?";
$l_new_inusechar         = "Il nome [character], è già utilizzato.";
$l_new_similar_inusechar = "Il nome del tuo carattere è troppo simile a [character], un nome già in uso.";
$l_new_inuseship         = "Il nome della nave [shipname], è già utilizzato.";
$l_new_similar_inuseship = "Il nome della nave è troppo simile a [shipname], un nome già in uso.";
$l_new_pwsent            = "La Password è stata inviata a [username].";
$l_new_err               = "Riprova ancora";
$l_new_topic             = "Password per Alien Assault Traders";
$l_new_message           = "Salve,\n\nQualcuno dall'indirizzo ip $ip ha richiesto che la password  di Traders fosse inviata al tuo indirizzo mail. \n\nLa tua password è: [pass]\n\nGrazie\n\nIl web team di Traders.";
$l_new_invalidemail             = "Indirizzo Email non valido.";
$l_new_tutorial = "Clicca qui per leggere il Mini-Tutorial prima di loggarti nel gioco.";
$l_new_profile = "Se hai un profilo giocatore, all'indirizzo <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, puoi registrare questo personaggio nelle <b>Opzioni di gioco</b>. ";
$l_new_login = "per andare alla scermata di Login.";
?>
