<?php
$l_warp_linkto           = "Le Rotte portano da questo settore verso";
$l_warp_nolink           = "Non ci sono Rotte da questo settore verso altri.";
$l_warp_query            = "Verso quale settore vuoi creare una Rotta?";
$l_warp_oneway           = "Senso unico?";
$l_warp_dest             = "Altrimenti, puoi distruggere una Rotta.";
$l_warp_destquery        = "Verso quale settore vuoi distruggere la Rotta?";
$l_warp_bothway          = "Entrambe le direzioni";
$l_warp_create          = "Creazione di una Rotta Warp tra il settore: ";
$l_warp_andsector          = " ed il settore: ";
$l_warp_distance          = " con una distanza di ";
$l_warp_lightyears          = " anniluce";
$l_warp_delete          = "Elimina la Rotta tra il settore: ";
$l_warp_costcreate          = "Costo per la creazione:";
$l_warp_costdelete          = "Costo per la cancellazione:";
$l_warp_costenergy          = "Energia necessaria: ";
$l_warp_twoerror         = "Usare un editor warp per creare una Rotta bidirezionale verso il settore [target_sector] non è permesso.";
?>
