<?php
$l_sn_title = "Settore Note";
$l_sn_pntitle = "I settori in cui le note personali";
$l_sn_tntitle = "I settori con le note Team";
$l_sn_psntitle = "Note personali Settore";
$l_sn_tsntitle = "Note team del settore";
$l_sn_editnote = "Modifica nota Settore:";
$l_sn_deleteedit = "Eliminare o modificare:";
$l_sn_addnote = "Aggiungi nota Settore:";
$l_sn_list = "Note Elenco Settori";
$l_sn_listts = "Elenco settori con note Team";
$l_sn_addteam = "Aggiungere un contatto";
$l_sn_deleteteam = "Elimina Team";
$l_sn_delete = "Eliminare";
$l_sn_saveteam = "Salva Team";
$l_sn_deletepersonal = "Elimina personali";
$l_sn_addpersonal = "Aggiungi personali";
$l_sn_savepersonal = "Salva dati personali";
$l_sn_editpersonal = "Modifica dati personali";
$l_sn_editteam = "Modifica Team";

$l_sn_hdsector = "Settore";
$l_sn_hdtype = "Tipo + + digitare";
$l_sn_hdowner = "Proprietario / Team";
$l_sn_hdplanets = "Pianeti";
$l_sn_hdport = "Porto";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Miniere";
$l_sn_hdscanfrom = "Da Scan";
$l_sn_hddetail = "Dettaglio";
$l_sn_hddate = "Data / Ora";
$l_sn_hddelete = "Eliminare";
$l_sn_hdteam = "Squadra";
$l_sn_view = "Vista";
$l_sn_no = "No";
$l_sn_yes = "Sì";
$l_sn_nonotes = "Nessun settore note trovate";

?>
