<?php
$l_sf_attacking          = "Droni di difesa del settore ti stanno attaccando!<BR>";
$l_sf_destfight          = "I tuoi Laser hanno distrutto [lost] Droni<BR>";
$l_sf_destfightb         = "I tuoi Laser hanno distrutto [lost] Droni<BR>";
$l_sf_torphit            = "I siluri hanno colpito:";
$l_sf_destfightt         = "I tuoi Siluri hanno distrutto [lost] Droni<BR>";
$l_sf_fighthit           = "Attacco dei Droni:";
$l_sf_destfightall       = "Hai distrutto tutti i Droni di difesa.<BR>";
$l_sf_destfightt2        = "Hai distrutto [lost] Droni di difesa.<BR>";
$l_sf_lostfight          = "Hai esaurito i tuoi Droni.<BR>";
$l_sf_lostfight2         = "Hai perso [lost] dei tuoi Droni.<BR>";
$l_sf_armorbreach        = "La tua armatura è stata penetrata!<BR>";
$l_sf_armorbreach2       = "La tua armatura ha subito [lost] danni.<BR>";
$l_sf_sendlog            = "[player] ha distrutto [lost] Droni di difesa nel settore [sector].";
$l_sf_lreport            = "Hai perso [armor] punti armatura, [fighters] Droni, e hai usato [torps] Siluri.<BR><BR>";
$l_sf_shipdestroyed      = "La tua nave è stata distrutta!<BR><BR>";
$l_sf_sendlog2           = "Le difese del settore hanno distrutto il giocatore [player] nel settore [sector].";
$l_sf_escape             = "Fortunatamente avevi una capsula di salvataggio!<BR><BR>";

$l_sf_fnoattack		 = " non sta inviando i suoi Droni per attaccare i tuoi.";
$l_sf_fnoattackt	 = " non sta inviando i suoi Droni per attaccare i tuoi siluri.";
$l_sf_fnoattacka	 = " non sta inviando i suoi Droni per attaccare la tua armatura.";
$l_sf_flaunchmalf1		 = "Il sistema di lancio dei tuoi Droni ha malfunzionato.";
$l_sf_flaunchmalf2		 = "Sei riuscito ad inviare solo il ";
$l_sf_flaunchmalf3		 = " percento dei tuoi Droni.";
$l_sf_fightertorpexg		 = "Fase Droni contro Siluri/Mine";
$l_sf_torpfighterexg		 = "Fase Siluri della nave contro Droni del settore";
$l_sf_fighterarmorexg		 = "Fase Droni del settore contro Armatura della navee";
$l_sf_tlaunchmalf1		 = "Il sistema di lancio dei Siluri ha malfunzionato.";
$l_sf_tlaunchmalf2		 = "Sei riuscito a lanciare solo il ";
$l_sf_tlaunchmalf3		 = " percento dei tuoi SIluri.";
$l_sf_bountysd = "Hai attaccato un settore che contiene un pianeta che potrebbe darvi una taglia se hai attaccato il pianeta. La Federazione ha attivato un self-destruct automatico su tutti i combattenti e siluri. Non attaccare le difese del settore in questo nuovo settore. Siete stati avvertiti!";
?>
