<?php
$l_att_title             = "Nave attaccante";
$l_att_notarg            = "Il tuo bersaglio non è più in questo settore.";
$l_att_noturn            = "Hai bisogno di almeno un turno per attaccare.";
$l_att_noatt             = "In questo settore non è permesso attaccare.";
$l_att_flee              = "Il bersaglio ha evaso il tuo attacco!";
$l_att_ewd               = "Il bersaglio ha attivato il Dispositivo Warp d'Emergenza!";
$l_att_att               = "Attacco contro ";
$l_att_beams             = "Attacco con i laser";
$l_att_torps             = "Attacco con i siluri";
$l_att_fighters          = "Attacco con i droni";
$l_att_lost              = "perso";
$l_att_ylost             = "Hai perso";
$l_att_sdown             = " ha perso gli scudi!";
$l_att_ydown             = "I tuoi scudi sono abbassati!";
$l_att_shits             = " ha subito agli scudi";
$l_att_yhits             = "Hai subito agli scudi";
$l_att_dmg               = "danni";
$l_att_sarm              = " ha subito un colpo diretto allo scafo!";
$l_att_yarm              = "Hai subito un colpo diretto allo scafo!";
$l_att_ashit             = " ha subito allo scafo";
$l_att_ayhit             = "Il tuo scafo è stato colpito e ha subito";

$l_att_efhit             = " ha perso i droni.";
$l_att_yfhit             = "dei tuoi droni sono stati distrutti.";
$l_att_ethit             = " ha perso i siluri.";
$l_att_ythit             = "dei tuoi siluri sono stati distrutti.";
$l_att_of             = "dei";
$l_att_lostt             = "ha perso tutti i siluri.";
$l_att_ylostt            = "Hai perso tutti i siluri.";

$l_att_lostf             = "ha perso tutti i droni.";
$l_att_ylostf            = "Hai perso tutti i droni.";
$l_att_sdest             = " ha perso la sua nave.";
$l_att_espod             = "Una capsula di salvataggio è stata lanciata!";
$l_att_ysalv             = "Dai rottami hai recuperato e il [ship_salvage_rate]% dei rest della nave, ricavando [ship_salvage] crediti.<BR>Il tuo punteggio è  variato di [rating_change] punti.";
$l_att_andused           = "e usato";
$l_att_stilship          = "Non sei riuscito a distruggere la nave di [name].";
$l_att_atyou             = "ti ha attaccato";
$l_att_and               = "e";
$l_att_yshiplost         = "La tua nave è stata distrutta!";
$l_att_salv              = "[name] ha recuperato e il [ship_salvage_rate]% dei rest della nave, ricavando [ship_salvage] crediti";
$l_att_loosepod		 = "Fortunatamente avevi una capsula di salvataggio!";

$l_att_tnobeams		 = " non ha più energia ai laser.";
$l_att_tnobeamsf		 = " non ha più energia ai laser, e non può attaccare i tuoi droni.";
$l_att_tnobeamst		 = " non ha più energia ai laser, e non può attaccare i tuoi siluri.";
$l_att_tfnoattack		 = " non sta inviando droni ad attaccare la tua nave.";
$l_att_tnotorps		 = " ha esaurito i siluri.";

$l_att_anobeams		 = "Hai esaurito l'energia dei laser.";
$l_att_anobeamsf		 = "Non hai più energia ai laser per attaccare i droni nemici.";
$l_att_anobeamst		 = "Non hai più energia ai laser per attaccare i siluri nemici.";
$l_att_anofighters		 = "La tua nave ha esaurito tutti i droni.";
$l_att_anotorps		 = "La tua nave ha esaurito tutti i siluri.";
$l_att_imtitle = "Nave Under Attack";
$l_att_imbody = "sta attaccando la vostra nave.";

$l_att_luckybeams = "Enemy travi sovraccarico infliggendo";
$l_att_luckyfighters = "Combattenti nemici effettuare un attacco a sorpresa di alleggerimento e la causa";
$l_att_luckytorps = "Siluri indurre un effetto a catena che causa danni Enemy";
$l_att_luckytimes = "volte il danno normale!";
?>
