<?php
$l_artifact_title = "Recupera Artefatto";
$l_artifact_list_title = "Elenco degli artefatti acquisiti";
$l_artifact_noscan = "Il vostro scanner non riusciva a trovare il manufatto.";
$l_artifact_noturn = "Tu non hanno abbastanza giri per raccogliere questo artefatto.";
$l_artifact_classname = "Artefatto Nome";
$l_artifact_description = "Artefatto Descrizione";
$l_artifact_imagename = "Artefatto Immagine";
$l_artifact_incomplete = "Artefatto Pieces";
$l_artifact_process = "Utilizzare l&#39;artefatto Completato";

?>
