<?php
$l_opt2_title            = "Salva Opzioni";
$l_opt2_passunchanged    = "La password non è stata cambiata.<BR><BR>";
$l_opt2_srcpassfalse     = "Password originale non corretta. La password è stata lasciata invariata.<BR><BR>";
$l_opt2_newpassnomatch   = "I campi password e nuova password non combaciano.. La password è stata lasciata invariata.<BR><BR>";
$l_opt2_passchanged      = "La password è cambiata.<BR><BR>";
$l_opt2_passchangeerr    = "Errore nel cambiare la password<BR><BR>";
$l_opt2_userintup        = "Aggiornate le impostazioni dell'interfaccia utente.<BR><BR>";
$l_opt2_userintfail      = "Erroe nel cambiare le impostazioni dell'interfaccia utente.<BR><BR>";
$l_opt2_chlang           = "La lingua è stata cambiata, ora quella attiva è l'[lang].<p>";
$l_opt2_chtemplate           = "La maschera è stata cambiata in [template].<p>";
$l_opt2_dhtmlup          = "Aggiornate le impostazioni dell'html dinamico.<BR><BR>";
$l_opt2_dhtmlfail        = "Errore nell'aggiornare le impostazioni dell'html dinamico.<BR><BR>";
$l_opt2_shipnamechanged = "NomeDestinatario cambiato a [name]. <BR><BR>";
$l_opt2_playernamechanged = "Cambiato il nome del giocatore a [name] e [amount] credito dedotto dal tuo account nave. <BR><BR>";
$l_opt2_mapwidth        = "Larghezza Mappa locale e della galassia: ";
?>
