<?php
$l_footer_one_player_on	= "C'è 1 giocatore online.";
$l_footer_players_on_1	= "Ci sono";
$l_footer_players_on_2	= "Giocatori online: ";
$l_footer_until_update	= "secondi al prossimo aggiornamento.";
$l_footer_no_players_on = "Non ci sono giocatori online.";

$l_footer_news = "News Locali per AATrade";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = " per un aiuto su questa pagina.";
$l_footer_click = "Clicca";

$l_footer_open_slots = "Maximum Online:";
$l_footer_onlinereset = "Giocatori online tempo di azzeramento nella";
$l_footer_onlinecountdown = "Giocatori Online conto alla rovescia:";
?>
