<?php
$l_autoroute_missingwarp          = "Non esiste la rotta warp successiva. Mossa interrotta.";
$l_autoroute_SDabort = "Sposta interrotta a causa di difese del settore nel settore.";
$l_autoroute_turns          = "Usando [triptime] turni sei andato nel settore  [targetlink]";
$l_autoroute_noturns           = "Hai esaurito i turni.";
$l_autoroute_title          = "Auto-Rotte";
$l_autoroute_id       = "ID Auto-Rotta";
$l_autoroute_start       = "Inizio Auto-Rotta";
$l_autoroute_destination       = "Destinazione Auto-Rotta";
$l_autoroute_warps       = "Warp Auto-Rotta";
$l_autoroute_deleteroute       = "Elimina Rotta";
$l_autoroute_info       = "Clicca sul settore iniziale per andare in quel settore e cominciare a viaggiare verso il settore di destinazione.";
$l_autoroute_delete2       = "Elimina le Rotte";
$l_autoroute_noroutes       = "Nessuna Auto-Rotta";
$l_autoroute_createroute       = "Crea una nuova Auto-Rotta";
$l_autoroute_deleted       = "Le Auto-Rotte sono state eliminate.";
$l_autoroute_return       = "Per tornare al menu delle Auto-Rotte, clicca";
$l_autoroute_created       = "L'Auto-Rotta è stata creata.";
$l_autoroute_realmove       = "Movimento nello spazio reale verso il settore";
$l_autoroute_warpmove       = "Movimento warp verso il prossimo settore";
$l_autoroute_warpfinal       = "Movimento warp verso l'ultimo settore";
$l_autoroute_editname = "Modifica nome";
?>
