<?php
$l_by_title              = "Taglie";
$l_by_noturn             = "Hai bisogno di almeno un turno per piazzare o modificare taglie.";
$l_by_amount             = "Ammontare della taglia";
$l_by_place              = "Piazza taglia";
$l_by_nobounties         = "Non ci sono taglie, al momento.";
$l_by_bountyon           = "Taglia su";
$l_by_placedby           = "Piazzata da";
$l_by_thefeds            = "La Federazione";
$l_by_cancel             = "Annulla";
$l_by_yourself           = "Non puoi piazzare una taglia su te stesso!";
$l_by_notenough          = "Non hai abbastanza crediti per piazzare una taglia di quel valore.";
$l_by_toomuch            = "Nonpuoi piazzare la taglia: Il massimo valore consentito è pari al [percent] percento del tuo patrimonio";
$l_by_zeroamount         = "Le taglie devono essere maggiori di 0 crediti.";
$l_by_placed             = "La taglia è stata piazzata.";
$l_by_nobounty           = "La taglia non esiste più.";
$l_by_notyours           = "Non sei stato tu a piazzare quella taglia.";
$l_by_canceled           = "La taglia è stata cancellata.";
$l_by_action             = "Azione";
$l_by_placebounty        = "Piazza o vedi taglie.";
$l_by_moredetails        = "Clicca sul nome per conoscere altri dettagli.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Se attacchi questo giocatore la Federazione metterà una taglia su di te.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>La Federazione non approva chi attacca giocatori molto inferiori quindi ha piazzato una taglia su di te.</b></font>";
$l_by_notexists          = "Il giocatore sul quale stai piazzando una taglia non esiste.";
$l_by_destroyed          = "Non puoi piazzare una taglia su un giocatore la cui nave sia stata distrutta.";
$l_by_nofedbounty		 = "Non saranno piazzate taglie su di te, se attacchi il pianeta o la nave di questo giocatore.";
$l_by_fedcollectonly		 = "Solo la Federazione può collezionare taglie";
$l_gotobounty          ="Clicca <A HREF=bounty.php>qui</A> per tornare al menu delle taglie.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>La Federazione metterà una taglia su di te se piazzerai una spia su questo pianeta.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>La Federazione non approva chi mette spie su pianeti di giocatori molto inferiori, quindi ha messo una taglia su di te.</b></font>";
$l_by_nofedbountyspy		 = "Non saranno piazzate taglie su di te se metterai una spia su questo pianeta.";
$l_pay_partial = "Fai di pagamento parziale";
$l_pay_button = "Pay";
$l_by_thealliance = "L&#39;Alleanza";
$l_by_alliancecollectonly = "Solo l&#39;Alleanza in grado di raccogliere Bounty";
$l_by_bountyscan = "Bounty";
?>
