<?php
$l_die_title             = "Auto Distruzione";
$l_die_rusure            = "Sicuro di voler distruggere la tua nave? questo ti rimuoverà dal gioco.";
$l_die_goodbye           = "Addio galassia crudele!";
$l_die_check             = "Yup davvero vuoi rimuoverti dal gioco?!";
$l_die_nonono = "NO! NO! NO!";
$l_die_what              = "Ma cosa stavo pensando di fare?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor             = "La tua nave e tutto ciò che era a bordo è stato vaporizzato.";
$l_die_please1           = "esci";
$l_die_please2           = "ora, [logout_link] dal gioco";
$l_die_exploit           = "Non giocare con ciò che non capisci!";
?>
