<?php
$l_opt_title             = "Opzioni";
$l_opt_chpass            = "Cambia password";
$l_opt_curpass           = "Password attuale:";
$l_opt_newpass           = "Nuova password:";
$l_opt_newpagain         = "Nuova password (ancora):";
$l_opt_userint           = "Interfaccia utente";
$l_opt_usenew            = "Vuoi usare un nuovo layout?";
$l_opt_lang              = "Lingua";
$l_opt_template              = "Maschera";
$l_opt_select            = "Selezionane una:";
$l_opt_enabled           = "Abilitato";
$l_opt_save              = "Salva";
$l_opt_teamicon              = "Icona della Squadra";
$l_opt_shipname              = "Nome nave:";
$l_opt_mapwidth              = "Ampiezza Mappe Locali e dcella Galassia:";
$l_opt_profiletitle = "Profilo";
$l_opt_profile = "Se hai un Profilo Giocatore all'indirizzo <a href='http://www.aatraders.com'>www.aatraders.com</a> e vuoi registrare questo gioco su quel profilo, clicca ";
$l_opt_profilereg = "Registrato col Profilo del Server";
$l_opt_profilerereg = "Ri-registra il Profilo Giocatore per questo gioco all'indirizzo <a href='http://www.aatraders.com'>www.aatraders.com</a> cliccando ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Quando si registra il lettore su un altro server del modello, shoutbox e le impostazioni di notizie di cui sopra sarà utilizzato sul server.";
$l_opt_showshoutbox = "Mostra Shoutbox:";
$l_opt_shownewscrawl = "Mostra News scansione:";
$l_opt_playername = "Nome giocatore:";
$l_opt_playernamecost = "Tassa Federazione Cambia nome: [amount] crediti";
?>
