<?php
$l_opt_title             = "Seleziona Icona Squadra";
$l_opt_errorsize            = "Errore: La tua immagine non può essere più grande di 64x64 pixel.";
$l_opt_errortype           = "Errore: L'immagine deve essere JPG, GIF o PNG";
$l_opt_errornographic           = "Errore: nessuna immagine selezionata.";
$l_opt_currentavatar         = "Tua attuale Icona Squadra";
$l_opt_uploadavatar           = "Carica un'Icona";
$l_opt_directory            = "Seleziona Directory per Icona Squadra";
$l_opt_change              = "Cambia Directory";
$l_opt_select              = "Seleziona Icona Squadra";
$l_opt_noteam              = "Non sei in una Squadra.";
$l_opt_notleader              = "Solo il Coordinatore può cambiare l'Icona della Squadra.";
$l_opt_inuse              = "Tutte le Icone Squadra di questa Directory sono state usate.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
