<?php
$l_warp_unlinked         = "Non c'è una Rotta da questo settore verso il settore ([target_sector]).";
$l_warp_forbidtwo        = "Non è permesso usare un editor warp per rimuovere una Rotta bidirezionale verso il settore [target_sector].";
$l_warp_removed          = "Rotta rimossa verso il settore";
$l_warp_removedtwo       = "Rotta rimossa da e per il settore";
$l_warp_nomoney          = "Non hai abbastanza crediti per rimuovere la Rotta warp.";
$l_warp_noenergy          = "Non hai abbastanza energia per rimuovere la Rotta warp.";
?>
