<?php
$l_opt_title             = "Seleziona un Avatar";
$l_opt_errorsize            = "Errore: La tua immagine non può essere più grande di 64x64 pixel.";
$l_opt_errortype           = "Errore: L'immagine deve essere JPG, GIF o PNG";
$l_opt_errornographic           = "Errore: nessuna immagine selezionata.";
$l_opt_currentavatar         = "Il tuo attuale Avatar";
$l_opt_uploadavatar           = "Carica un Avatar";
$l_opt_directory            = "Seleziona Directory Avatar";
$l_opt_change              = "Cambia Directory";
$l_opt_select              = "Seleziona un Avatar";
$l_opt_inuse              = "Tuuti gli Avatars in questa directory sono stati usati.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
