<?php
// New News Items

$l_news_planets		 = " pianeti";
$l_news_cols		 = " milioni di coloni";
$l_news_p_headline 	 = "L'impero di [player] ha ora [total] pianeti";
$l_news_c_headline 	 = "L'impero di [player] ha ora [total] milioni di coloni";
$l_news_p_textXX = "La Federazione ha rilasciato le avvertenze concernenti l&#39;impero di [name]. [name] ha il controllo di [total] pianeti e deve essere considerato molto pericoloso. Tutti i settori dovrebbero aumentare le difese del settore immediatamente.";
$l_news_c_textXX = "L&#39;impero di [name] sta vivendo il sovraffollamento di massa su tutti i pianeti, con oltre [total] milioni di coloni. La carenza di cibo può causare disordini. Tutti i settori devono essere consapevoli delle possibili azioni aggressive da [name] per il futuro.";

$l_created_universe             = "Creazione dell'universo";
$l_created_universe_full        = "Scienzati che studiano l'inizio della vita dell'universo, hanno deciso all'unanimità che oggi è statisticamente il giorno più probabile in cui potrebbe essere avvenuta la Creazione dell'Universo";

$l_news_p_text5		 = "Il nascente impero di [name] ora è costituito da cinque pianeti, la FNN osserverà le azioni di [name] più attentamente in futuro!";
$l_news_p_text10	 = "Il crescente impero di [name] ora controlla dieci pianeti. I rapporti della FNN riferiscono che un'ulteriore espansione di [name] potrebbe causare guerre!";
$l_news_p_text25	 = "Il vasto impero di [name] possiede 25 pianeti colonizzati. In un'intervista [name] ha annunciato che potrebbe decidere di ridurre il tasso di espansione in futuro!";
$l_news_p_text50	 = "Il gigantesco impero di [name], costituito da 50 pianeti nella galassia, rappresenta una forza considerevole. Un reporter della FNN ha scoperto che [name] sta potenziando la propria nave pianificando battaglie di conquista. In un'intervista [name] ha annunciato che lo fa per soli scopi difensivi!";
$l_news_c_text25	 = "Del nascente impero di [name] fanno parte 25 millioni di coloni, la FNN osserverà le azioni di [name] più attentamente in futuro, ma è ovvio che i tassi di natalità stanno per esplodere!";
$l_news_c_text100	 = "Il futuro impero di [name] ora ha 100milioni di coloni; dopo un'esplosione dei tassi di natalità, le colonie di [name] sembrano un buon posto dove le famiglie possono insediarsi!";
$l_news_c_text500	 = "Il grande impero di [name] è abitato da 500 milioni di  coloni; [name] ha detto in un'intervista che la colonizzazione della galassia è appena cominciata!";
$l_news_c_text1000	 = "L'affollato impero di [name] è ora costituito da un miliardo di coloni. Reporter della FNN hanno scoperto che [name] è in possesso di qualche esotico dispositivo di clonazione che gli permette di sfamare i numerosi nuovi coloni. Con questo numero di abitanti, la potenza economica dell'impero è enorme. La FNN spera che [name] non spenda i suoi soldi in armamenti bellici";

$l_news_indi_short	 = "FNN - Soffiata: oltre [planets] si dichiarano indipendenti.";
$l_news_indi	 = "Fonti della FNN riferiscono che oltre [planets] pianeti hanno deciso che preferisono governarsi da soli, e si sono dichiarati indipendenti.";

$l_news_nova_short	 = "FNN - Rapporto: [name] usa una Bomba Nova.";
$l_news_nova	 = "Fonti della FNN riportano che [name] ha usato una Bomba Nova [total] volta/e per distruggere un pianeta e tutte le navi su di esso.";
$l_news_nova_m_short	 = "FNN - Rapporto: [name] usa una Bomba Nova, ma manca il bersaglio.";
$l_news_nova_m	 = "Fonti della FNN riportano che [name] ha cercato di usare una Bomba Nova [total] volta/e per distruggere un pianeta , ma questa è esplosa fuori dall'atmosfera, causando ingenti danno alle infrastrutture del pianeta.";

$l_news_bounty	 = "FNN - Rapporto: [name] piazza una taglia di [amount] crediti su [name2].";

$l_news_attackerpod_p_short	 = "FNN - Rapporto: [name] ha perso la nave.";
$l_news_attackerpod_P	 = "La nave di [name] è stata distrutta mentre attaccava un pianeta. Fortunatamente [name] aveva una capsula di salvataggio ed è sopravvissuto.";

$l_news_attackerdie_p_short	 = "FNN - Rapporto: [name] è morto!";
$l_news_attackerdie_p	 = "La nave di [name] è stata distrutta mentre attaccava un pianeta, e non avendo una capsula di salvataggio è rimasto ucciso.";

$l_news_destroyed_p_short	 = "FNN - Rapporto: [name] attacca e distrugge un pianeta!";
$l_news_destroyed_p	 = "[name] ha attaccato [total] volte un pianeta di [owner], infine sconfiggendolo; gli abitanti hanno deciso di distruggere le loro case, piuttosto che vederle catturate da [name]!";

$l_news_defeated_p_short	 = "FNN - Rapporto: [name] attacca e sconfigge un pianeta!";
$l_news_defeated_p	 = "[name] ha attaccato [total] volte un pianeta di [owner] e alla fine ha sconfitto le difese planetarie!";

$l_news_notdefeated_p_short	 = "FNN - Rapporto: [name] attacca un pianeta e perde!";
$l_news_notdefeated_p	 = "[name] ha attaccato [total] volte un pianeta di [owner] e le difese planetarie hanno resistito e sconfitto l'attaccante!";

$l_news_targetepod_short	 = "FNN - Rapporto: [name] attacca la nave di [owner] e vince!";
$l_news_targetepod	 = "[name] ha attaccato la nave di [owner] e l'ha distrutta completamente.  Fortunatamente [owner] aveva una capsula di salvataggio ed è sopravvissuto.";

$l_news_targetdies_short	 = "FNN - Rapporto: [name] attacca la nave di [owner] e la distrugge!";
$l_news_targetdies	 = "[name] ha attaccato la nave di [owner] e l'ha distrutta completamente. Sfortunatamente [owner] mom aveva una capsula di salvataggio ed è stato vaporizzato nello spazio.";

$l_news_fedcolbounty_short = "FNN Relazione: Le crepe Federazione verso il basso [name]!";
$l_news_fedcolbounty = "La Federazione oggi ha represso il famigerato pirata spaziale [name]! [name], che ha sistematicamente violato i trattati più spazio, avuto una breve relazione con l&#39;incrociatore da battaglia della Federazione, che ha inflitto [amount] crediti del valore del danno sulla nave del pirata. I funzionari di federazione promettere ulteriori azioni di questo tipo in futuro!";

$l_news_alliancecolbounty_short = "FNN Relazione: Le crepe Alleanza verso il basso [name]!";
$l_news_alliancecolbounty = "L&#39;Alleanza oggi ha represso il famigerato pirata spaziale [name]! [name], che ha sistematicamente violato i trattati più spazio, avuto una breve relazione con l&#39;Alleanza, che ha inflitto [amount] crediti del valore del danno sulla nave del pirata. Funzionari di Alleanza promessa ulteriori azioni di questo tipo in futuro!";

$l_news_fedcol_pbounty_short = "FNN Relazione: La Federazione dà la caccia [name]!";
$l_news_fedcol_pbounty = "La Federazione oggi ha represso il famigerato pirata spaziale [name]! [name], che ha sistematicamente violato i trattati più spazio, avuto una breve relazione con l&#39;incrociatore da battaglia della Federazione, che ha sequestrato il pianeta [planetname] planetname [amount] crediti nel settore [sector]. I funzionari di federazione promettere ulteriori azioni di questo tipo in futuro!";

$l_news_alliancecol_pbounty_short = "FNN Report: The Alliance dà la caccia [name]!";
$l_news_alliancecol_pbounty = "L&#39;Alleanza oggi ha represso il famigerato pirata spaziale [name]! [name], che ha sistematicamente violato i trattati più spazio, avuto una breve relazione con l&#39;Alleanza, che ha sequestrato il pianeta [planetname] planetname [amount] crediti nel settore [sector]. Funzionari di Alleanza promessa ulteriori azioni di questo tipo in futuro!";

$l_news_fedcol_sbounty_short = "FNN Relazione: La Federazione dà la caccia [name]!";
$l_news_fedcol_sbounty = "La Federazione oggi ha represso il famigerato pirata spaziale [name]! [name], che ha sistematicamente violato i trattati più spazio, avuto una breve relazione con l&#39;incrociatore da battaglia della Federazione, che ha sequestrato una nave ([shiptype]) per un valore [cost] nel settore [sector]. I funzionari di federazione promettere ulteriori azioni di questo tipo in futuro!";

$l_news_alliancecol_sbounty_short = "FNN Report: The Alliance dà la caccia [name]!";
$l_news_alliancecol_sbounty = "L&#39;Alleanza oggi ha represso il famigerato pirata spaziale [name]! [name], che ha sistematicamente violato i trattati più spazio, avuto una breve relazione con l&#39;Alleanza, che ha sequestrato una nave [shiptype] tipo di nave [cost] nel settore [sector]. Funzionari di Alleanza promessa ulteriori azioni di questo tipo in futuro!";

$l_killheadline		 ="[target] è stato ucciso in un incidente";
$l_news_killed 		 = "[target] è stato ucciso in un tragico incidente. Eroicamente il capitano [target] ha aspettato che tutto l'equipaggio lasciasse la nave, quando ha notato che non c'era una scialuppa di salvataggio anche per lui. Possa riposare in pace!";

$l_killSDheadline = "[target] è stato ucciso dalle difese del settore.";
$l_news_killedSD = "[target] è stato ucciso da un numero enorme di difese Settore di proprietà di [killer]! Purtroppo, la nave non era dotata di una scialuppa di salvataggio.";

$l_killplanetheadline = "[target] è stato ucciso attaccare un pianeta.";
$l_news_killedplanet = "[target] è stato ucciso mentre attacca un pianeta di proprietà di [killer] oggi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

$l_killshipheadline = "[target] è stato ucciso Combat Ship.";
$l_news_killedship = "[target] è stato ucciso in combattimento da nave a nave con [killer] oggi. Il capitano apparentemente dimenticato di equipaggiare la nave con una scialuppa di salvataggio.";

$l_killsuicideheadline = "[target] si è suicidato.";
$l_news_killedsuicide = "[target] si è suicidato oggi. Hanno preso il via da vigliacchi, perché non aveva la capacità o il coraggio di resistere alle pressioni del loro comandante della nave stessa.";

$l_killsofaheadline = "[target] è stato ucciso divano attaccare un pianeta.";
$l_news_killedsofa = "[target] è stato ucciso mentre divano attaccare un pianeta di proprietà di [killer] oggi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

$l_killnovaheadline = "[target] è stato ucciso durante un attacco di Nova.";
$l_news_killednova = "[target] è stato ucciso da [killer] nel corso di un attentato dinamitardo nova oggi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

$l_killnovabackfireheadline = "[target] è stato ucciso da un ritorno di fiamma Nova.";
$l_news_killednovabackfire = "[target] è stato ucciso quando la bomba Nova fallì oggi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

$l_killsectormissileheadline = "[target] è stato ucciso da un missile settore.";
$l_news_killedsectormissile = "[target] è stato ucciso quando un missile settore da [killer] influenzato i loro scudi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

$l_killhunterprobeheadline = "[target] è stato ucciso da una sonda Hunter.";
$l_news_killedhunterprobe = "[target] è stato ucciso quando una sonda da Hunter [killer] influenzato i loro scudi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

$l_killtrapprobeheadline = "[target] è stato ucciso da una sentinella Trap Probe.";
$l_news_killedtrapprobe = "[target] è stato ucciso quando una sonda Sentry trappola da [killer] influenzato i loro scudi. Sfortunatamente, la nave non era dotata di una scialuppa di salvataggio.";

//-------------------

$l_killpodheadline = "[target] &#39;s nave venne distrutta in un incidente";
$l_news_killedpod = "[target] &#39;s nave venne distrutta in un tragico incidente di oggi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killSDpodheadline = "[target] &#39;s nave è stata distrutta dalle difese del settore.";
$l_news_killedSDpod = "[target] &#39;s nave venne distrutta da un numero enorme di difese Settore di proprietà di [killer]! Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killplanetpodheadline = "[target] &#39;s nave venne distrutta attaccare un pianeta.";
$l_news_killedplanetpod = "[target] &#39;s nave venne distrutta mentre attacca un pianeta di proprietà di [killer] oggi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killshippodheadline = "[target] &#39;s nave venne distrutta in un combattimento navale.";
$l_news_killedshippod = "[target] &#39;s nave venne distrutta da nave a nave a combattere con [killer] oggi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killsofapodheadline = "[target] &#39;s nave venne distrutta mentre divano attaccare un pianeta.";
$l_news_killedsofapod = "[target] &#39;s nave venne distrutta mentre divano attaccare un pianeta di proprietà di [killer] oggi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killnovapodheadline = "[target] &#39;s nave venne distrutta durante un attacco di Nova.";
$l_news_killednovapod = "[target] &#39;s nave venne distrutta da [killer] nel corso di un attentato dinamitardo nova oggi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killnovabackfirepodheadline = "[target] &#39;s nave venne distrutta da un ritorno di fiamma Nova.";
$l_news_killednovabackfirepod = "[target] &#39;s nave venne distrutta quando la loro bomba Nova fallì oggi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killsectormissilepodheadline = "[target] &#39;s nave venne distrutta da un missile settore.";
$l_news_killedsectormissilepod = "[target] &#39;s nave venne distrutta quando un missile settore da [killer] influenzato i loro scudi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killhunterprobepodheadline = "[target] &#39;s nave venne distrutta da una sonda Hunter.";
$l_news_killedhunterprobepod = "[target] &#39;s nave venne distrutta quando una sonda da Hunter [killer] influenzato i loro scudi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

$l_killtrapprobepodheadline = "[target] &#39;s nave venne distrutta da una sentinella Trap Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s nave venne distrutta quando una sonda Sentry trappola da [killer] influenzato i loro scudi. Un transponder Escape Pod è stato rilevato dalla Federazione di ricerca e salvataggio.";

// --------------------------

$l_news_promotedheadline = "[name] è stato promosso a [rank]";
$l_news_promoted = "La Federazione è lieta di annunciare la promozione di [name] al rango di [rank].";

$l_news_demotedheadline = "[name], è stato retrocesso a [rank]";
$l_news_demoted = "La Federazione si rammarica per annunciare la retrocessione di [name] al rango di [rank].";

$l_news_namechangedheadline = "[oldname] nome cambiato in [newname]";
$l_news_namechanged = "[oldname] applicata alla Federazione Review Board di cambiare il loro nome a [newname]. La Federazione ha concesso il cambio di nome. Da questo giorno in avanti [oldname] è ora noto come [newname]. Tutte le navi e pianeti dovrebbero aggiornare i propri record immediatamente.";

$l_news_found_planets_short = "Federazione Sondaggio: [found_planets] nuovi pianeti situati.";
$l_news_found_planets = "Federazione Scout Survey hanno individuato [found_planets] nuovi pianeti nei settori recentemente scoperti.";

$l_news_new_ports_short = "Federazione Sondaggio: [new_ports] porte di nuova costruzione.";
$l_news_new_ports = "Gli ingegneri hanno costruito Federazione [new_ports] nuove porte in settori recentemente scoperti.";

$l_news_addedsectors_short = "Federazione Sondaggio: [addedsectors] settori scoperti.";
$l_news_addedsectors = "Federazione Scout Survey hanno scoperto [addedsectors] nuovi settori. Si consiglia cautela.";

$l_news_artifactheadline = "[playername] completato [artifact]";
$l_news_artifact = "[playername] ha trovato tutti i pezzi della figura del [artifact] e ha tutto il potere che essa può fornire.";

$l_news_artifactfoundheadline = "[playername] trovato [artifact] pezzo";
$l_news_artifactfound = "[playername] ha trovato uno dei pezzi del manufatto [artifact] e le esigenze [pieces] altro [piece].";

?>
