<?php
$l_scan_title            = "Scan della Nave";
$l_scan_turn             = "Ti occorre almeno un turno per lo scan di una nave.";
$l_scan_ron              = "Risultati Scan su";
$l_scan_capt             = "Capitanata da:";
$l_scan_arma             = "Armamento:";
$l_scan_carry            = "Trasporta:";
$l_scan_bounty           = "Questa nave ha un taglia di [amount] crediti.";
$l_scan_fedbounty        = "Questa nave ha una taglia piazzata dalla Federazione.";
$l_by_nofedbounty        = "La Federazione <B>NOT</B> piazzerà una taglia su di te se attacchi questo giocatore.";
?>
