<?php
// port.php port_purchase.php
$l_trade		 = "Commercio";
$l_title_port		 = "Commercio al porto";
$l_title_trade		 = "Vendita delle merci";
$l_sector_war		 = "embargo causa guerra";
$l_war_info		 = "Una guerra sta infuriando in questo settore. Non riesci a raggiungere il porto attraverso tutte le forze ostili che si danno battaglia.";
$l_no_trade		 = "Commercio vietato";
$l_no_trade_out		 = "Il Commercio in questo porto non è permesso per esterni";
$l_no_trade_info	 = "Il Commercio in questo porto non è permesso";
$l_buying		 = "Acquista";
$l_selling		 = "Vende";
$l_commodity		 = "Merce";
$l_amount		 = "Ammontare";
$l_price		 = "Prezzo";
$l_buy			 = "Compra";
$l_sell			 = "Vendi";
$l_trade_st_info	 = "Hai [free_holds] unità di carico disponibili, puoi aggiungere [free_power] unità di energia addizionali e hai [credits] crediti.";
$l_upgrade_port_title	 = "Porto Potenziamenti";
$l_device_port_title	 = "Porto Dispositivi";
$l_spacedock_port_title	 = "Spazioporto";
$l_no_credits		 = "Crediti insufficienti";
$l_creds_to_spend	 = "Hai [credits] crediti da spendere.";
$l_cost			 = "Costo";
$l_avail		 = "Disponibili";
$l_profit		 = "Profitto";
$l_current		 = "Attuale";
$l_current_level	 = "Livello attuale";
$l_current_qty		 = "Quantità attuali";
$l_max = "Max";
$l_ifyouneedmore	 = "Se te ne servono altri, puoi accedere al [igb] di questo porto";
$l_ifyouneedplan	 = "Accedi da questo pianeta al";
$l_igb_term		 = "Terminale Bancario IGB";
$l_upgrade		 = "Potenzia";
$l_unlimited		 = "Illimitati";
$l_full			 = "Pieno";
$l_equipped		 = "Equipaggiato";
$l_n_a = "n / a";
$l_item			 = "Oggetto";
$l_totalcost		 = "Costo totale";
$l_would_dump	         = "Se vuoi scaricare tutti i tuoi coloni, clicca ";
$l_noport		 = "Non c'è alcun porto qui!";
$l_trade_turnneed	 = "Hai bisogno di almeno un turno per commerciare ad un porto o ad un pianeta.";
$l_returnto_port1        = "qui";
$l_returnto_port2        = " Clicca [port_link] per tornare al menu del porto.";
$l_notenough_cargo	 = "Non possiedi abbastanza unità di carico libere per le merci che vuoi acquistare.";
$l_notenough_power	 = "Non possiedi abbastanza capacità per la quantità di unità d'energia che desideri acquistare.";
$l_notenough_credits	 = "Non possiedi abbastanza crediti per completare l'operazione.";
$l_notenough_turns	 = "Non possiedi abbastanza turni per completare l'operazione.";
$l_trade_result		 = "Risultati di questa transazione";
$l_trade_complete	 = "Commercio completato";
$l_trade_upgraded 	 = "Potenziato al livello ";
$l_trade_added 		 = "aggiunti";
$l_trade_installed 	 = "installati";
$l_port_bounty 		 = "Non puoi accedere ad un porto speciale mentre hai una taglia su di te piazzata dalla Federazione.<BR>";
$l_port_bounty2 	 = "Clicca <a href=\"port.php?pay=1\">qui</a> per pagare la taglia di [amount] crediti.";
$l_port_btynotenough 	 = "Non hai abbastanza crediti per pagare la taglia. Te ne servono [amount].<BR>";
$l_port_bountypaid 	 = "Hai pagato la taglia. Clicca <a href=\"port.php\">qui</a> per continuare.<BR>";
$l_port_loannotrade 	 = "La IGB ha bloccato il conto della tua nave, a causa di un ritardo nella restituzione di un prestito. Non puoi commerciare ai porti speciali finchè non salderai il tuo debito.";
$l_port_returntospecial = "per tornare al magazzino del porto.";
$l_toprobemenu          = "per tornare al menu della sonda.";
$l_ports_shiplimit = "Minima classe della nave per montare il dispositivo: ";
$l_ports_needrepair = "Ripara";

$l_ports_needcredits = "Non hai abbastanza crediti per questa operazione. Il costo totale è di";
$l_ports_needcredits1 = "crediti, mentre tu ne hai solo ";

$l_ports_tradeforbidden = "Commercio vietato";
$l_ports_nooutsiders = "Il Commercio in questo porto non è permesso per esterni";

$l_bought = "Hai comprato";
$l_sold = "Hai venduto";
$l_notenough_commodity = "Non hai abbastanza [commodity] per completare la transazione.";
$l_exceed_commodity = "Numero di [commodity] supera la domanda / offerta.";
$l_port_shiptoolarge = "La tua nave è troppo grande per il commercio in questo porto.";

$l_port_hold_unit = "Contiene per Unità";

$l_port_welcome = "Port [sectorname] Welcome&#39;s [player]";
$l_port_amountforsale = "Il porto è [amount] unità di [commodity] in vendita su [credits] crediti per unità.";
$l_port_holdsperunit = "[holds] stive di carico richiesto per unità.";
$l_port_howmanypurchase = "Quante unità [commodity] vorresti acquistare?";
$l_port_unitstobuy = "Unità di acquistare";
$l_port_shipcarryingbuy = "La tua nave sta effettuando [shipunits] unità di [commodity]. È possibile acquistare [buyunits] unità, con spazio di presa di carico a disposizione.";
$l_port_howmanysell = "[amount] unità di [commodity] @ [credits] crediti per unità.";
$l_port_unitstosell = "Unità di vendere";
$l_port_perform = "Eseguire la transazione";
$l_port_cargoholds = "Stive di carico";

?>
