<?php
$l_pre_title             = "Cambia Rotte Spazioreale presettate";
$l_pre_exceed            = "La Rotta SR [preset] eccede il massimo dell'universo di [sector_max]. Non verrà salvata.<BR><BR>";
$l_pre_set               = "Presetta";
$l_pre_save              = "Salva";
$l_pre_info = "Info";
$l_pre_invalid = "[sector] è un nome valido settore.";
$l_pre_invalidchange = "[sector] è un settore Genesi settore. Il tuo vecchio preset è invariato.";
?>
