<?php
$l_autotrade_title = "Menu Auto-Rotte Commerciali";
$l_autotrade_dismiss2 = "Le Auto-Rotte Commerciali sono state cancellate.";
$l_autotrade_report = "Rapporto Auto-Rotte Commerciali";
$l_autotrade_planet = "Pianeta";
$l_autotrade_hull = "Stiva";
$l_autotrade_energy = "Energia";
$l_autotrade_capacity = "Capacità";
$l_autotrade_goods = "Prezzo dei prodotti";
$l_autotrade_ore = "Prezzo del metallo";
$l_autotrade_organics = "Prezzo degli organici";
$l_autotrade_energy = "Prezzo dell'energia";
$l_autotrade_colonist = "Prezzo colono";
$l_autotrade_credits = "Crediti dal commercio";
$l_autotrade_delete = "Elimina<br>Rotta";
$l_autotrade_unnamed = "Senza Nome";
$l_autotrade_noroute = "Nessuna Rotta";
$l_autotrade_sector = "Settore";
$l_autotrade_credit2 = "crediti";
$l_autotrade_deletebutton = "Elimina";
$l_autotrade_noroute2 = "Non hai settato alcuna Auto-Rotta Commerciale.";
?>
