<?php
$l_feedback_title        ="Invia Feedback";
$l_feedback_to           ="A:";
$l_feedback_from         ="DA:";
$l_feedback_topi         ="OGGETTO:";
$l_feedback_feedback = "Feedback";
$l_feedback_message      ="MESSAGGIO:";
$l_feedback_messent      ="Messaggio Inviato";
$l_feedback_subj = "AATraders In-Game feedback";
$l_feedback_info         ="Please send feedback in english only - Per cortesia, invia i feedback solo in inglese";
?>
