<?php
$l_dump_title            = "Scaricamento Coloni";
$l_dump_turn             = "Ti occorre almeno un turno per scaricare i tuoi colonis.";
$l_dump_nocol            = "Non hai COloni sulla nave da scaricare.";
$l_dump_dumped           = "Coloni scaricati al magazzino merci.";
$l_dump_nono             = "Ti occorre essere ad un magazzino merci (in un porto Potenziamenti) per scaricare i tuoi coloni.";
?>
