<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] 		 = "Spazio non mappato";
$l_zname[2] 		 = "Spazio della Federazione";
$l_zname[3] 		 = "Spazio della Alliance";
$l_zname[4] 		 = "Zona di guerra";

$l_nova = "Nova";
$l_nova 		 = "Bomba Nova";
$l_lssd 		 = "Dispositivo Ultima Nave Avvistata";
$l_lss 			 = "Ultima nave vista in questo settore";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Editor Warp";
$l_warp_turn		 = "Hai bisogno di almeno un turno per utilizzare un Editor Warp.";
$l_warp_none		 = "Non hai alcun Editor Warp.";
$l_warp_forbid		 = "In questo settore non è permesso utilizzare Editor Warp.";
$l_swarp_forbid		 = "Non è permesso utilizzare Editor Warp verso o da settori SG.";
$l_warp_nosector	 = "Il settore indicato non esiste.";

// Not yet confirmed common to multiple files:

$l_yes 			 = "Si";
$l_no = "No";
$l_here			 = "qui";
$l_submit		 = "Invia";
$l_reset		 = "Azzera";
$l_all			 = "Tutti";

$l_trade = "Commercio";
$l_ore			 = "Metallo";
$l_commodity = "Commodity";
$l_commodities		 = "Merci";
$l_organics		 = "Organici";
$l_goods		 = "Prodotti";
$l_energy		 = "Energia";
$l_colonists		 = "Coloni";
$l_credits 		 = "Crediti";
$l_units		 = "unità di ";
$l_special		 = "Speciale";
$l_upgrade_ports	 = "Potenziamenti";
$l_device_ports		 = "Dispositivi";
$l_spacedock		 = "Spazioporto";
$l_casino = "Casinò";
$l_spy = "Spie";
$l_dig = "Dignitari";

$l_cargo = "Cargo";
$l_fighters		 = "Droni ";
$l_mines		 = "Mine ";
$l_torps		 = "Siluri";

$l_none			 = "Nessuno";
$l_unnamed		 = "senza nome";
$l_name			 = "Nome";
$l_unowned		 = "di nessuno";
$l_unknown		 = "sconosciuto";
$l_clickme 		 = "Clicca qui";
$l_player  		 = "Giocatore";
$l_ship			 = "Nave";
$l_ships		 = "Navi";
$l_set = "insieme";
$l_realspace		 = "Spazio Reale";
$l_armorpts		 = "Punti armatura";
$l_links		 = "Rotte";
$l_login_email          = "Indirizzo E-mail:";
$l_add			 = "Aggiungi";
$l_teamforum			 = "Forum della Squadra";
$l_teamships			 = "Navi della Squadra";
$l_tutorial			 = "Tutorial/Aiuto";
$l_avatar = "Avatar";
$l_teamicon			 = "Icona della Squadra";
$l_debris			 = "Rottami";
$l_localmap			 = "Mappa locale";
$l_arm_weap              = "Armatura & Armi";
$l_3dmap			 = "Mappa 3D della galassia";

$l_max = "Max";
$l_casino = "Casino";

$l_sectormissile = "Settore Missile";
$l_spacebeacon = "Boa Spaziale";
$l_spaceprobes = "Sonde Spaziali";
$l_warpeditors = "Editor Warp";
$l_genesistorps = "Siluri Genesis";
$l_sgtorps = "Siluri SG";
$l_minesfighters = "Mine/Droni";
$l_ewarp = "Dispositivo d'emergenza Warp";
$l_reports = "Rapporti";
$l_shipinfo = "Info Nave";
$l_sectornotes = "Note di Settore";
$l_maps = "Mappe";
$l_messages = "Messaggi";
$l_shiptype = "Tipo Nave";
$l_help = "Aiuto";
$l_rank = "Rango";
$l_teamplanets = "Pianeti della Squadra";
$l_teamdefenses = "Difese della Squadra";
$l_planetstatus = "Stato Pianeti";
$l_planetdefenses = "Difese Planetarie";
$l_changeproduction = "Cambia Produzione";
$l_galacticarm = "Braccio Galattico";
$l_armor = "Armatura";
$l_news_none             = "Spiacente, nessuna notizia oggi.";

$l_ranks_good = "Buono";
$l_ranks_evil = "Male";
$l_ranks_neutral = "Neutro";

$l_global_mmenu          ="Clicca <A HREF=main.php>qui</A> per tornare al Menu Principale.";
$l_global_mlogin         ="Clicca <A HREF=index.php>qui</A> per tornare alla schermata di Login.";
$l_global_needlogin      ="Devi loggarti, clicca <A HREF=index.php>qui</A>.";
$l_global_died           ="Il personaggio è morto! Ecco <a href=log.php>qui</a> cosa è successo<BR><BR>Avrai più fortuna la prossima volta!";
$l_global_warzone        ="La Zona è ora una Zona di Guerra!";
$l_global_nzone          ="La Zona è ora neutrale.";
$l_global_team           ="La Zona appartiene ora al team";
$l_global_player         ="La Zona appartiene ora al giocatore";
$l_global_nochange       ="La proprietà della Zona non è cambiatax";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "O-1.png";
$l_insignia[5] = "O-2.png";
$l_insignia[6] = "O-3.png";
$l_insignia[7] = "O-4.png";
$l_insignia[8] = "O-5.png";
$l_insignia[9] = "O-6.png";
$l_insignia[10] = "O-7.png";
$l_insignia[11] = "O-8.png";
$l_insignia[12] = "O-9.png";
$l_insignia[13] = "O-10.png";
$l_insignia[14] = "O-11.png";
$l_insignia[15] = "O-12.png";
$l_insignia[16] = "O-13.png";
$l_insignia[17] = "O-14.png";
$l_insignia[18] = "O-15.png";
$l_insignia[19] = "O-16.png";

$l_insignia_name[0] = "Astronauta Recruit";
$l_insignia_name[1] = "Astronauta Apprendista";
$l_insignia_name[2] = "Astronauta";
$l_insignia_name[3] = "Petty Officer terza classe";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Tenente Junior Grade";
$l_insignia_name[11] = "Tenente";
$l_insignia_name[12] = "Capitano di Corvetta";
$l_insignia_name[13] = "Commander";
$l_insignia_name[14] = "Capitano";
$l_insignia_name[15] = "Rear Admiral (metà inferiore)";
$l_insignia_name[16] = "Rear Admiral (metà superiore)";
$l_insignia_name[17] = "Ammiraglio di Squadra";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Ammiraglio";

$l_main_title            = "Menu Principale";
$l_main_warpto           = "Rotta Warp verso";
$l_main_autoroute        = "Auto-Rotta verso";
$l_main_rs_to            = "Spazioreale verso";
$l_main_other            = "Altri";
$l_main_shipyard1        = "Hangar Spaziale";
$l_main_shipyard2        = "Accedi all' ";
$l_traderoutes           = "Rotte Commerciali";
$l_trade_control         = "Gestione Rotte";
$l_youhave               = "Hai ";
$l_turns_used            = "Turni usati: ";
$l_turns_have            = "Turni a disposizione: ";
$l_score                 = "Punteggio: ";
$l_sector                = "Settore";
$l_help                  = "Aiuto";
$l_faq = "FAQ";
$l_feedback = "Feedback";
$l_forums                = "Forum";
$l_logout                = "Esci";
$l_commands              = "Comandi";
$l_command_no            = "Comando non disponibile.";
$l_devices               = "Dispositivi";
$l_planets               = "Pianeti";
$l_log                   = "Diario";
$l_sector_def            = "Difese del settore";
$l_defense               = "Difese";
$l_read_msg              = "Leggi messaggi";
$l_send_msg              = "Invia messaggi";
$l_rankings              = "Classifica";
$l_teams                 = "Squadre";
$l_ohno                  = "Autodistruzione";
$l_options               = "Opzioni";
$l_navcomp               = "Computer di navigazione";
$l_incompletemove        = "Non hai completato la mossa precedente.";
$l_clicktocontinue       = "Clicca qui per continuare";
$l_toplanetmenu          = "per andare al menu del pianeta.";
$l_nonexistant_pl        = "Su un pianeta che non esiste?!?";
$l_abord                 = ", a bordo della nave ";
$l_messages_wait         = " messaggi non letti.";
$l_no_warplink           = "Nessuna rotta warp";
$l_scan = "scan";
$l_fullscan              = "Scan completo";
$l_port                  = "Porto";
$l_tradingport           = "Porto commerciale";
$l_planet_in_sec         = "Pianeti nel settore ";
$l_ships_in_sec          = "Altre navi nel settore ";
$l_sector_0              = "C'è così tanto traffico in Sol che non riesci nemmeno a distinguere le altre navi!";
$l_map                   = "Mappa";
$l_probe				 = "Sonde";
$l_autotrade				 = "Auto-Rotte";
$l_onboard				 = "a bordo di una nave classe";
$l_classship = ".";
$l_traveled = "ha viaggiato verso il settore";
$l_max_planets = "Massimo numero di pianeti abitabili";
$l_block_msg              = "Blocca i messaggi";
$l_sectorinfo = "Settore Info";
$l_add_note = "Aggiungi nota";
$l_view_note = "Vista";
$l_notes = "Note";
$l_global_limitreached = "Hai raggiunto il limite per la quantità di tempo che si è permesso di essere on-line ogni giorno. Entra di nuovo domani, dopo la mezzanotte.";
$l_onlinetimeleft = "Tempo restante:";
$l_planetmax = "Planetary massima:";
$l_storedshipreport = "Stored Navi";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federazione le informazioni sulla porta";
$l_team_shoutbox = "Shoutbox Team";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Pagina precedente";
$l_common_next = "Pagina successiva";
$l_common_totalpages = "Totale Pagine";
$l_common_selectpage = "Seleziona pagina:";
$l_common_page = "Pagina:";
$l_templatechange = "Vuoi mantenere questo modello?";

$l_im_fed_bounty = "La Federazione ha messo una taglia su di lei per l&#39;attacco ad un giocatore di basso rango. La Federazione attacco la vostra nave a intervalli regolari fino a quando non restituire il bottino. È possibile pagare il Bounty in qualsiasi porto o l&#39;aggiornamento Spacedock.";
$l_im_fed_bounty_title = "Federazione messo una taglia su di voi!";
$l_im_alliance_bounty = "L&#39;Alleanza ha messo una taglia su di lei per l&#39;attacco ad un giocatore di basso rango. L&#39;Alleanza attacco la vostra nave a intervalli regolari fino a quando non restituire il bottino. È possibile pagare il Bounty in qualsiasi porto o l&#39;aggiornamento Spacedock.";
$l_im_alliance_bounty_title = "Alleanza messo una taglia su di voi!";
$l_instant_messages_waiting = "Hai [count] messaggi in attesa per voi.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Contiene ripieni:";
$l_hold_space_free = "Contiene Vuoto:";
$l_port_buys = "Porto Buys:";

?>
