<?php
$l_lrs_title             = "Scan a lungo raggio";
$l_lrs_nofull            = "I tuoi scanner non hanno la funzionalità a lungo raggio.";
$l_lrs_noturns           = "Ti occorre almeno $fullscan_cost turnoper attivare lo scan a lungo raggio.";
$l_lrs_used              = "Usato/i";
$l_lrs_turns             = "turno/i";
$l_lrs_left              = "rimangono";
$l_lrs_reach             = "Dal settore [sector] puoi andare nei seguenti:";
$l_lrs_links             = "Rotte";
$l_lrs_ships             = "Navi";
$l_lrs_click             = "Clicca una delle rotte per andare nel corrispondente settore.";
$l_lrs_cantscan          = "Non è possibile fare lo scan del settore dalla posizione attuale!";
$l_lrs_zero              = "Il Settore 1 è troppo affollato per permettere uno scan!";
$l_lrs_moveto            = "per andare nel settore";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Taglia</b></font>";
$l_log_titlet            = "Vedi Diario";
$l_lrs_fedjammed           = "La Federazione sta disturbando tutti gli scan.";
$l_lrs_imtitle             = "Sector Under Attack";
$l_lrs_imbody             = "is using a Sector Nova on";
$l_lrs_sectormissile_question = "al fuoco dei missili del settore.";
$l_log_months 		 = array('Gennaio','Febbraio','Marzo','Aprile','Maggio','Gugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre');
$l_log_months_short 	 = array('Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic');
$?>
