<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Tecnologia della Sonda";
$l_probe_engine = "Motori";
$l_probe_sensors = "Sensori";
$l_probe_cloak = "Occultamento";
$l_probe_title		 = "Menu Sonda Spaziale";
$l_probe_none		 = "Non sei nello stesso settore della sonda, quindi non puoi interagire con essa.";

$l_probe_named		 = "Sonda numero [probename], posseduta da [name], situata nel settore [sector].";
$l_probe_orders	 = "[orders] la sonda per esplorare l'universo";
$l_probe_orders_link= "Programma";
$l_probe_upgrade	 = "[upgrade] Motori, Sensori e/o Occultamento della sonda";
$l_probe_upgrade_link	 = "Potenzia";
$l_probe_pickup	 = "[pickup] la sonda per lanciarla di nuovo successivamente";
$l_probe_pickup_link	 = "Raccogli";
$l_probe_update	 = "Aggiorna";

$l_probe_att_link	 = "Attacca";
$l_probe_att		 = "[attack] la sonda";
$l_probe_att_sure	 = "Sei SICURO...";
$l_probe_scn_link	 = "Scannerizza";
$l_probe_scn		 = "[scan] la sonda";

$l_probe_unknown		 = "Sconosciuto";
$l_plant_scn_turn	 = "Ti occorre almeno un turno per scannerizzare la sonda.";
$l_probe_noscan	 = "I sensori non riescono a fissare un bersaglio!";
$l_probe_logscanA	 = "[name] ha cercato di scannerizzare una delle tue sonde nel settore [sector], ma ha fallito.";
$l_probe_logscanB	 = "Una delle tue sonde nel settore [sector] è stata scannerizzata da [name].";
$l_probe_scn_report	 = "Risultati della scannerizzazione su [name], posseduto da:  [owner]";

$l_probe_caplog	 = "La tua sonda '[probename]' nel settore [sector] è stata catturata da [name].";
$l_probe_scan  = "La sonda scannerizza il settore [sector] e scopre:";
$l_probe_destroyprobe  = "Distruggi sonda";
$l_probe_destroyed= "Sonda distrutta!!";
$l_probe_warning 	 = "Facendo questo distruggerai completamente questa sonda";
$l_probe_confirm 	 = "Vuoi veramente distruggere questa sonda?";
$l_gns_turn ="Non hai abbastanza turni per distruggere questa sonda";
$l_probe_type="Tipo di sonda";
$l_probe_type0="Sonda stazionaria";
$l_probe_type1="Sonda di avvistamento";
$l_probe_type2="Sonda Warp";
$l_probe_type3="Sonda in Spazioreale";
$l_probe_type4="Sonda sequenziale in Spazioreale";
$l_probe_target="Settore di destinazione";
$l_probe_ordered="Sonda programmata e pronta ad esplorare.";
$l_probe_order2="Questa è una [type] e ha come obiettivo il settore [target]";
$l_probe_pickedup="Sonda raccolta e messa nel magazzino attivo";
$l_probe_title="Menu Sonda";
$l_probe_messages = "per vedere cosa le tue spie hanno scoperto.";

$l_probe_defaulttitle1 = "Sonde attive";
$l_probe_defaulttitle2 = "Sonde che hai raccolto";
$l_probe_defaulttitle3 = "Sonde sui tuoi pianeti";
$l_probe_defaulttitle4 = "Sonde sulla tua nave";
$l_probe_linkback="per tornare al menu della sonda.";
$l_probe_no1 = "Non hai alcuna sonda attiva.";
$l_probe_no2 = "Non hai alcuna sonda in magazzino.";
$l_probe_no3 = "Non hai alcuna sonda sui tuoi pianeti.";
$l_probe_no4 = "Non hai alcuna sonda sulla tua nave.";
$l_probe_noprobeatall = "Non hai alcuna sonda.";
$l_probe_notknown = "Sconosciuto";
$l_probe_launch="Lancia";
$l_probe_detect="Individuato";
$l_probe_codenumber = "Codice";
$l_probe_job = "Incarico";
$l_probe_percent = "Percento";
$l_probe_move = "Movimento";
$l_probe_view= "Vedi";
$l_probe_action = "Azione";
$l_probe_shipowner = "Possessore delal nave";
$l_probe_shipname = "Nome della nave";
$l_probe_shiptype = "Classe della nave";
$l_probe_shiplocation = "Posizione della nave";
$l_probe_planetowner = "Possessore del pianeta";
$l_probe_planetname = "Pianeta";
$l_probe_sector = "Settore attuale";
$l_probe_tsector = "Settore obiettivo";
$l_probe_type="Tipo di sonda";
$l_probe_forbid="Non puoi lanciare sonde in questo settore";

$l_probe2_title             = "Lancia sonda spaziale";
$l_probe2_turn              = "Ti occorre almeno un turno per usare una sonda spaziale.";
$l_probe2_onplanet          = "Non puoi usare questo dispositivo mentre sei sulla superficie del pianeta.";
$l_probe2_noprobe         = "Non hai alcuna sonda spaziale.";
$l_probe2_forbid            = "Non è permesso usare sonde spaziali in questo settore.";
$l_probe2_launched           = "Sonda spaziale lanciata!";

$l_probe2_warplink           = "Rotta Warp";
$l_probe2_player           = "Giocatore";
$l_probe2_onboarda           = "a bordo di una";
$l_probe2_classship           = "classe della nave";
$l_probe2_traveled           = "ha viaggiato verso il settore";
$l_probe2_fedjammed           = "La Federazione sta disturbando tutte le scannerizzazioni verso il settore 1.";
$l_probe2_lastseen           = "Ultima Nave Vista";
$l_probe2_portfound           = "Porto trovato";
$l_probe2_supports           = "Supporta";
$l_probe2_planets           = "pianeti";
$l_probe2_sectord           = "Individuate difese del settore";
$l_probe2_mines           = "Mine";
$l_probe2_fighters           = "Droni";
$l_probe2_ships           = "Nave individuata";
$l_probe2_ships2           = "Nave individuata";
$l_probe2_noneowned           = "Nessun pianeta non posseduto da te è stato individuato.";
$l_probe2_warplinks           = "Rotte Warp";
$l_probe2_nothing           = "Non è stato individuato niente";
$l_probe2_nocredits = "Non hai abbastanza crediti per questa transazione. Il costo totale è di [total] crediti e hai solo [credits] crediti.";

$l_probe_forbidSG = "Non è possibile inviare una sonda tipo di mondo fisico nel settore Genesi creata settori.";
$l_probe_forbidFED = "Non è possibile inviare una sonda tipo di mondo fisico in Federazione o Alleanza settori di proprietà.";
$l_probe_forbidINVALID = "Il vostro settore di destinazione è un nome non valido settore.";
?>
