<?php
$l_shipyard_title        = "Hangar";
$l_planet                = "Pianeta";
$l_ship_welcome = "Benvenuti a questo Hangar della Planetary. Attualmente abbiamo queste navi disponibili per la vendita.";
$l_ship_class = "Classe";
$l_ship_properties = "Proprietà Classe";
$l_ship_current = "Attuale";
$l_ship_outstorage = "Ritira dal Deposito";
$l_ship_storagecost = "Costo Deposito";
$l_ship_storagewarn = "Una volta che ritiri la tua Pioneer dal Deposito, perderai quella che ti era stata data dopo la distruzione della tua nave.";
$l_ship_levels = "Livello Sistemi Nave";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Prezzo";
$l_ship_turns = "Turni per costruirla";
$l_ship_purchase = "Acquista";
$l_ship_stored = "Stored";
$l_ship_basehull = "Base dello scafo:";

$l_ship_averagemaxtech = "Media Massimo Tech Level:";
$l_ship_averagenormaltech = "Media normale Tech Level:";
$l_ship_averagecurrenttech = "Media attuale Tech Level:";

?>
