<?php
$l_beacon_title          = "Rilascia Boa Spaziale";
$l_beacon_notpermitted   = "In questo settore non è permesso rilasciare Boe Spaziali.";
$l_beacon_reads          = "La Boa attiva in questo momento mostra il messaggio";
$l_beacon_none           = "Non c'è alcuna Boa attiva in questo settore.";
$l_beacon_enter          = "Inserisci il messaggio per la Boa Spaziale";
$l_beacon_nowreads       = "La Boa Spaziale del settore ora mostra il messaggio";
$l_beacon_donthave       = "Non hai Boe Spaziali da rilasciare.";
?>
