<?php
$l_sofa                  = "Attacco suboorbitale coi droni (SOFA)";
$l_planet_basenoturn	 = "Ti occorre almeno un turno per costruire una base";
$l_planet_upgrade   ="Potenzia";
$l_planet_novamiss   ="La Bomba Nova manca il bersaglio di poco, ma causa danni al pianeta.";
$l_planet_novaturns   ="La Bomba Nova richiede almeno [turns] turni per essere lanciata.";
$l_planet_novafed   ="La Bomba Nova non funzionerà in settori della Federazione.";
$l_planet_nonova   ="Non hai una Bomba Nova installata.";
$l_planet_firenova   ="Lancia Bomba Nova";
$l_planet_novaexplode   ="La Bomba Nova esplode non appena è stata lanciata, danneggiando gravemente la tua nave.";
$l_planet_novaexplode2   ="La Bomba Nova esplode non appena viene lanciata, distruggendo la tua nave.";
$l_planet_noautotrade   ="AutoRotta Commerciale non settata per questo pianeta.";
$l_planet_autotrade   ="<font size='1'>Commercio automatico";
$l_planet_autotradetype = "- [source_type] al porto [dest_id] ";
$l_planet_autotradedelete   ="Cancella Auto-Rotta.";
$l_planet_autotradeadd   ="Crea Auto-Rotta.";
$l_planet_tradedeleted   ="Auto-Rotta eliminata.";
$l_planet_tradeadded   ="Nuova Auto-Rotta aggiunta.";
$l_planet_autotype = "Seleziona la merce da commerciare";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>con base</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Devi acquistare una nave cargo per questo pianeta prima di poter creare un'Auto-Rotta.";
$l_planet_purchasecargo = "Se vuoi comprare una nave cargo";
$l_planet_upgradecargo = "se vuoi potenziare la tua nave cargo";

$l_planet_cargocapacity = "Capacità: ";
$l_planet_cargoowned = "Possiedi già una nave cargo per questo pianeta.";
$l_planet_cargoshipbuy = "Compra nave cargo";
$l_planet_cargoshipupgrade = "Potenzia nave cargo";
$l_planet_cargoatmax = "La tua nave cargo è al livello massimo di potenziamento.";
$l_planet_cargoshipbuyinfo = "Seleziona una nave cargo prefissata";
$l_planet_cargoshipupgradeinfo = "Potenzia la stiva della tua nave cargo.";
$l_planet_cargoshipbuildinfo = "Costruisci la tua nave cargo personalizzata";
$l_planet_tradehelp = "1. Puoi inserire un porto commerciale per ciascuna merce.<br>2. Non puoi commerciare una merce ad un porto che vende lo stesso tipo di merce.<br>&nbsp;&nbsp;&nbsp;Per esempio, commerciare prodotti ad un porto di prodotti, o metallo ad un porto di vende metallo non darà alcun profitto.<br>3. Se non vuoi commerciare alcune merci, inserisci zero come porto di destinazione.";
$l_planet_cargocredits = "Crediti ricevuti dall'Auto-Rotta:";
$l_planet_cargonoown = "Devi possedere il pianeta per creare un'Auto-Rotta.";
$l_planet_digtrans = "Trasferisci Dignitario";
$l_planet_nocredits1 = "Non hai abbastanza crediti per questa operazione.  Il costo totale è di ";
$l_planet_nocredits2 = " crediti, mentre tu ne hai solo ";
$l_planet_nobase = "DEvi avevre una base per poter gestire i livelli di tecnologia del pianeta.";
$l_planet_genesisnoturn	 = "Ti occorre almeno un turno per usare il dispositivo Genesis sul pianeta.";
$l_planet_nogenesis	 = "Ti serve un dispositivo Genesis per distruggere il pianeta.";
$l_planet_wrongclass	 = "Questa classe di nave non può sparare una Bomba Nova.";

$l_planet_combatpreview	 = "Anteprima del combattimento";
$l_planet_beamfire1	 = "Il tuo attacco è stato scoperto!  I Laser planetari fanno fuoco!  Il fuoco dei Laser è aumentato, mentre la tua nave si avvicina troppo al pianeta per poter lanciare i droni.";
$l_planet_beamfire2	 = "Il tuo attacco è stato scoperto!  I Laser planetari fanno fuoco!  Le batterie Laser del pianeta si preparano a fare fuoco sulla tua nave in più punti, da almeno un intero continente!";
$l_planet_beamfire3	 = "Il tuo attacco è stato scoperto!  I Laser planetari fanno fuoco!  Tutte le batterie di Laser del pianeta stanno agganciando la posizione della tua nave, e si preparano a fare fuoco tutte insieme! La potenza dei Laser del pianeta sarà molto maggiore delle stime dei sensori!";
$l_planet_beamfire4	 = "Il tuo attacco è stato scoperto!  I Laser planetari fanno fuoco!  I Laser del pianeta riescono ad agganciarti solo per una tornata di fuoco.";

$l_planet_sofanobeamsshields	 = " non sta facendo fuoco coi Laser sui tuoi scudi.";
$l_planet_sofanobeamsarmor	 = " non sta facendo fuoco coi Laser sulla tua armatura.";
$l_planet_flauncherfailed1	 = "Il tuo sistema di lancio dei Droni ha malfunzionato.";
$l_planet_flauncherfailed2	 = "Sei riuscito a lanciare solo il ";
$l_planet_flauncherfailed3	 = " percento dei tuoi Droni.";
$l_planet_nodfightertofighter	 = " non sta inviando alcun Drone per attaccare i tuoi Droni.";
$l_planet_nodfightertotorp	 = " non sta inviando alcun Drone per attaccare i tuoi siluri.";
$l_planet_flauncherfailed3	 = " percento dei tuoi Droni.";

$l_planet_imtitleattack = "Planet Under Attack";
$l_planet_imisattacking = "attacca";
$l_planet_iminsector = "nel settore delle";
$l_planet_imnova = "sta utilizzando un dispositivo di Nova";
$l_planet_imsofa = "è SOFA Bombing";
$l_planet_team = "Questo pianeta è di proprietà di un compagno di squadra e non hai il permesso di accedere alle informazioni di questo pianeta.";
?>
