<?php
$l_cu_storing = "Memorizzazione";
$l_cu_inistored = "<b>Tutti i valori ini sono stati conservati correttamente.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Route ID";
$l_cu_start = "Auto Route Start";
$l_cu_destination = "Auto Route Destinazione";
$l_cu_warps = "Auto Route Warps";
$l_cu_deleteroute = "Elimina percorso";
$l_cu_info = "Fare clic su Start per il Settore mondo fisico a quello del settore e iniziare a curvare per il settore di destinazione.";
$l_cu_delete2 = "Elimina rotta";
$l_cu_noroutes = "Nessuna rotta Auto";
$l_cu_createroute = "Crea un nuovo Auto Route";
$l_cu_deleted = "Auto Itinerari soppresso.";
$l_cu_return = "Torna a Auto Route fare clic sul menu";
$l_cu_created = "Auto Route è stato creato.";
$l_cu_realmove = "Spostare mondo fisico al settore";
$l_cu_warpmove = "Warp passare al settore successivo";
$l_cu_warpfinal = "Warp passare al settore finale";
?>
