<?php
$l_sendm_title           = "Invia Messaggio";
$l_sendm_to              = "A";
$l_sendm_from            = "Da";
$l_sendm_ally            = "Squadra:";
$l_sendm_subj            = "Oggetto";
$l_sendm_mess            = "Messaggio";
$l_sendm_send            = "Invia";
$l_sendm_sent            = "Messaggio Inviato";
$l_sendm_blocked            = " ha bloccato i tuoi messaggi.";
$l_sendm_blockmanager            = "Gestore Blocco Messaggi";
?>
