<?php
$l_move_title            = "Mossa";
$l_move_turn             = "Ti occorre almeno un turno per muovere.";
$l_move_failed           = "Mossa falita!";
$l_rs_title              = "Mossa Spazioreale";
$l_rs_whichsector        = "Quale settore vorresti raggiungere tramite lo Spazioreale?";
$l_rs_insector           = "Sei attualmente nel settore [sector] - e i settori disponibili vanno dal numero 1 al numero [sector_max].";
$l_rs_submit             = "Calcola";
$l_rs_movetime           = "Con i tuoi motori consumerai [triptime] turno/i per completare il viaggio.";
$l_rs_energy             = "Con il viaggio otterresti [energy] unità di energia";
$l_rs_noturns            = "Non hai abbastanza turni a disposizione, e non puoi permetterti questo viaggio.";
$l_rs_engage_link        = "Attivare";
$l_rs_engage             = "Hai ancora [turns] turni. [engage] i motori?";
$l_rs_invalid            = "Non puoi viaggiare tramite lo Spazioreale verso quel settore da qui.";
$l_rs_ready              = "Sei ora nel settore [sector]. Hai usato [triptime] turno/i, e guadagnato [energy] unità di energia.";
$l_warp_invalid = "Non si può deformare a tale settore da qui.";
$l_move_unknown = "Sconosciuto Movetype";
?>
