<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] ha colpito [chm_roll] mine nel settore [chm_sector].";
$l_chm_youlostminedeflectors    = "Hai perso [chm_roll] deflettori di mine.";
$l_chm_youlostallminedeflectors = "Hai perso tutti i tuoi deflettori di mine.";
$l_chm_youhadnominedeflectors  = "Non hai deflettori di mine.";
$l_chm_yourshieldshitforminesdmg        = "I tuoi scudi hanno subito [chm_mines_left] danni.";
$l_chm_yourshieldsaredown       = "I tuoi scudi sono a zero!";
$l_chm_youlostallyourshields    = "Hai perso gli scudi!";
$l_chm_yourarmorhitforminesdmg  = "La tua armatura ha subito [chm_mines_left] danni.";
$l_chm_yourhullisbreached       = "Lo scafo della tua nave è stato penetrato!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] è stato distrutto dalle tue mine nel settore [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "La tua nave è stata distrutta!";
$l_chm_luckescapepod     = "Fortunatamente avevi una capsula di salvataggio!";

$l_chm_yourdeflectormalf1 = "Mine Deflettore sistema di lancio ha presentato un malfunzionamento.";
$l_chm_yourdeflectormalf2 = "Sei sono stati solo in grado di lanciare";
$l_chm_yourdeflectormalf3 = "deflettori per cento del mio.";
$l_chm_enemytorpfailshields = "non ha avviato alcuna siluri contro gli scudi.";
$l_chm_enemytorpfailarmor = "non ha avviato alcuna siluri contro la tua armatura.";

$l_chm_minemalf1 = "Miniere nemico cattivo funzionamento.";
$l_chm_minemalf2 = "Solo";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines = "Hai colpito [chm_roll] miniere di [total_mines] mine!";
$l_chm_yourdeflectormalf2a = "Sei sono stati solo in grado di lanciare [deflectors] per cento del mio deflettori.";
$l_chm_mines_destroyed = "[number] della [target] mine sono state distrutte!";
$l_chm_mine_deflectors_left = "Hai [number] deflettori mia sinistra.";
$l_chm_mines_left = "Ci sono [number] miniere di sinistra e sono un impatto sulle vostre armi!";
$l_chm_minemalf2a = "Solo [deflectors] per cento delle miniere di attaccare trovato la tua nave.";
$l_chm_mines_exhausted = "[player] miniere esaurite!";
$l_chm_armor_left = "Hai [number] punti armatura a sinistra!";

?>
