<?php
$l_md_title              = "Difese del settore";
$l_md_invalid            = "Difese del settore non valide";
$l_md_nolonger           = "La difesa del settore selezionata non è più presente.";
$l_md_you                = "tu";
$l_md_bmines             = "I tuoi laser hanno distrutto";
$l_md_msgdownerb         = "[name] ha distrutto [mines] mine nel settore [sector].";
$l_md_retr               = "Hai ritirato";
$l_md_consist            = "Le difese di questo settore consistono in [qty] [type] di proprietà di [owner].";
$l_md_youcan             = "Puoi";
$l_md_retrieve           = "Ritirare";
$l_md_attack             = "Attacca";
$l_md_attdef             = "Attacca le difese del settore. Tutti i droni di pattuglia contrattaccheranno.";
$l_md_noturn             = "Ti occorre almeno un turno.";
$l_md_nothere            = "Devi essere nello stesso settore delle difese del settore.";
$l_md_notyours           = "Azione non permessa: quelle difese del settore non sono di tua proprietà.";
$l_md_yours              = "Non puoi attaccare le difese del settore di tua proprietà.";
?>
