<?php
$l_sm_title = "Settore di lancio dei missili";
$l_sm_invalid = "Non c&#39;è un nesso tra la trama di questo settore e il settore di destinazione.";
$l_sm_notarg = "Obiettivi non in questo settore.";
$l_sm_noturn = "Hai bisogno di almeno un turno al fuoco del vostro settore missilistico.";
$l_sm_nosectormissile = "Tu non esercitino alcun Missili Settore.";
$l_sm_noscan = "I sensori non è possibile ottenere una correzione sul bersaglio!";
$l_sm_flee = "Destinazione al di fuori manovrato il missile settore!";
$l_sm_ewd = "Target è impegnato in una curvatura dispositivo di emergenza quando ha rilevato il missile settore!";
$l_sm_imtitle = "Nave Under Attack";
$l_sm_imbody = "[playername] è attaccare la nave con un missile settore!";
$l_sm_sectormissilefail = "Il cattivo funzionamento del settore dei missili, quando ha colpito lo scudo navi nemiche!";
$l_sm_sectormissilefail2 = "Il cattivo funzionamento del settore dei missili, quando ha colpito l&#39;armatura navi nemiche!";
$l_sm_shieldhit = "[target] &#39;s scudi sono stati colpiti per [amount] danni!";
$l_sm_shieldsdown = "[target] &#39;s scudi sono giù!";
$l_sm_armorhit = "[target] &#39;s armatura è successo per [amount] danni!";
$l_sm_armorbreached = "[target] &#39;s armatura violato!";
$l_sm_targetnoenergy = "La nave nemica non ha alcuna energia! Settore Missile fallisce!";
$l_sm_attacking = "Attaccare [target] a bordo della [shipname]";
$l_sm_targetok = "Non hai destory [name] &#39;s nave.";
$l_sm_lost = "[target] perso [armor] punti di armatura e [energy] unità di energia.";
$l_sm_destroyed = "[target] &#39;s nave è stata distrutta.";
$l_sm_escapepod = "Una scialuppa di salvataggio è stata lanciata!";
?>
