<?php
$l_defense_deploy_title           ="Deposita Mine e Droni di Settore";
$l_defense_deploy_noturn          ="Ti occorre almeno un turno per depositare difese di settore.";
$l_defense_deploy_nopermit        ="Non è permesso depositare difese di settore qui.";
$l_defense_deploy_nodeploy        ="Non è permesso depositare difese di settore qui. Un'altra nave o squadra ha già posizionato le sue.";
$l_defense_deploy_info1           ="Sei attualmente nel settore [sector]. Ci sono [mines] mine e [fighters] Droni qui.";
$l_defense_deploy_info2           ="Hai [mines] mine e [fighters] Droni disponibili da depositare";
$l_defense_deploy_deploy          ="Deposita";
$l_defense_deploy_deployed        ="Depositati";
$l_defense_deploy_att             ="Attacca";
$l_defense_deploy_notorps         ="Non hai abbastanza Siluri.";
$l_defense_deploy_nofighters      ="Non hai ababstanza Droni";
$l_defense_deploy_dmines          ="Depositate [mines] mine.";
$l_defense_deploy_dfighter        ="Depositati [fighters] droni.";
$l_defense_deploy_max_fighters = "Questo settore può supportare un massimo di [amount] combattenti.";
$l_defense_deploy_toomanyfighters = "Si è tentato di distribuire i combattenti più in grado di supportare il settore.";
?>
