<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: ShoutBox::.";
$l_shout_public         = "Pubblico";
$l_shout_team             = "Squadra";
$l_shout_smiles            = "Smiles";
$l_shout_else          = "altrimenti";
$l_shout_refresh          = "Aggiorna";
$l_shout_close          = "Chiudi finestra";
$l_shout_saved          = "Shout salvato!";
$l_shout_return          = "Ritorna al ";
$l_shout_prev = "Precedente";
$l_shout_next = "Successivo";
$l_shout_selectpage = "Seleziona pagina";
$l_shout_page = "Pagina:";
$l_shout_teamtitle = ".:: SHOUTBOX TEAM::.";
?>
