<?php
$l_warp_cantsame         = "Non puoi creare una Rotta quando Origine e Destinazione sono le stesse.";
$l_warp_twoerror         = "Usare un editor warp per creare una Rotta bidirezionale verso il settore [target_sector] non è permesso.";
$l_warp_sectex           = "Impossibile creare una Rotta dal settore attuale - ciò farebbe superare il limite di $link_max Rotte massimo per ciascun settore.";
$l_warp_linked           = "Il settore di destinazione ([target_sector]) ha già una Rotta verso questo settore.";
$l_warp_coneway          = "Rotta a senso unico creata verso";
$l_warp_ctwoway          = "Rotta creata da e verso il settore";
$l_warp_nomoney          = "Non hai abbastanza crediti per creare la Rotta warp.";
$l_warp_noenergy          = "Non hai abbastanza energia per creare la Rotta warp.";
?>
