<?php
$l_login_sclosed		= "Server Chiuso";
$l_login_closed_message		= "Server chiuso fino a successiva indicazione.";
$l_login_title2			= "Login fase due";
$l_login_banned			= "<b>Sei stato bannato da questo gioco dall'amministratore. Non sei più il benvenuto a giocare su questo server. Addio.</b>";
$l_login_died			= "La tua nave è stata distrutta, ma la capsula di salvataggio ha salvato te e il tuo equipaggio.  Clicca <A HREF=main.php>qui</A> per continuare con una nuova nave.";
$l_login_newbie			= "A causa della serietà di questo crimine, e del malvagio attacco contro di te, la Federatione ha deciso di clonarti, sfruttando i tuoi resti. Purtroppo però, anche in quest'epoca, i nuovi cloni non possono possedere proprietà, eccettuate quelle minime per sopravvivere. Ti sarà fornita una nave di classe minima e pochi crediti per poter ricominciare una vita. Che la tua prossima vita sia migliore di quella passata.";
$l_login_newlife		= "Clicca <A HREF=main.php>qui</A> per continuare in una nuova vita.";
$l_login_looser			= "Non avevi capsula di salvataggio, e a causa del tuo modesto successo, la Federazione decide di non clonarti. I tuoi resti infine spariranno in qualche sorgente di gravità, forse per far di nuovo parte del ciclo vitale.... parecchi miliardi di anni nel futuro.<BR><BR> Avrai più fortuna nel prossimo gioco....";
$l_login_4gotpw1		= "La password che hai inserito non è corretta.<BR><BR>  Se hai dimenticato la password, ";
$l_login_4gotpw2		= "perchè ti venga inviata via mail.<BR><BR>  Altrimenti,";
$l_login_4gotpw3		= "per riprovare.  Il tentativo di Login fallito è avvenuto dall'indirizzo ip ";
$l_login_noone			= "Non esiste tale giocatore! - Crea un unovo giocatore <A HREF=new_player.php>qui</A>.";
$l_login_diedincident			= "Sei morto in un orribile incidente.";
$l_login_blackbox			= " è ciò che è stato rilevato dalla scatola nera della tua nave ritrovata tra i rottami spaziali di quella che un volta era il tuo orgoglio.";
$l_new_login = "per andare alla scermata di Login.";
$l_login_playerlimit = "Il server ha raggiunto il numero massimo di giocatori che supporta. Prova ad accedere in un secondo momento.";
?>
