<?php
$l_mail_title = "Mail Password";
$l_mail_noplayer         ="Non esiste il giocatore! - Crea un nuovo giocatore <a href=new_player.php>qui</a>.";
$l_mail_sent             ="La Password + stata inviata a";
$l_mail_topic            ="Password $game_name";
$l_mail_message          ="Salve,\n\nQualcuno dall'indirizzo IP $ip ha richiesto che ti venisse inviata la password per il gioco $game_name \n\nLa tua password è: [pass]\n\nGrazie\n\nIl web team di $game_name.";
$l_new_login             = "per andare alla schermata di login.";
$l_mail_failed             ="Invio della password fallito all'indirizzo";
?>
