<?php
///SPIES
$l_spy_title = "Menu Spie";
$l_spy = "Spie";
$l_spy_disabled = "Le Spie sono disabilitate!";
$l_spy_noturn = "Hai bisogno di almeno un turno per inviare un spia su un pianeta.";
$l_spy_notonboard = "Non hai spie a bordo.";
$l_spy_ownplanet = "Non puoi inviare una spia su un tuo pianeta.";
$l_spy_unownedplanet = "YNon puoi inviare una spia su un pianeta di nessuno.";
$l_spy_planetfull = "Il numero massimo di spie permesso, pari a [max], è già stato raggiunto per questo pianeta.";
$l_spy_sendtitle = "Invio della spia [spyID] asul pianeta:<BR>Seleziona la missione della spia:";
$l_spy_type1 = " La spia agisce solo su questo pianeta.";
$l_spy_type2 = " La spia tenta di infiltrare una nave che avvia un trasferimento planetario.";
$l_spy_type3 = " La spia tenta di infiltrare una nave che avvia un trasferimento planetario, e in seguito di infiltrarsi su un altro pianeta.";
$l_spy_sendbutton = "Invia al pianeta";
$l_spy_sendsuccessful = "La tua spia ha infiltrato il pianeta e aspetta il momento giusto per agire.";
$l_spy_sendfailed = "I sensori del pianeta hanno individuato la tua spia poichè il tuo occultamento non è riuscito a mascherarla. La tua spia è stata uccisa.";
$l_spy_noturn2 = "Hai bisogno di almeno un turno per richiamare indietro la tua spia.";
$l_spy_confirm = "Sicuro di voler richiamare la tua spia [spyID]?";
$l_spy_cleanupplanet = "per ripulire il pianeta da spie nemiche.";
$l_spy_cleanupship = "Se vuoi ripulire il pianeta da spie nemiche, clicca";
$l_spy_yourspies = "Le tua spie sul pianeta";
$l_spy_sendnew = "Invia una nuova spia";

$l_spy_codenumber = "Codice";
$l_spy_job = "Missione";
$l_spy_percent = "Percento";
$l_spy_move = "Movimento";
$l_spy_action = "Azione";
$l_spy_shipowner = "Possessore Nave";
$l_spy_shipname = "Nome Nave";
$l_spy_shiptype = "Classe Nave";
$l_spy_shiplocation = "Posizione Nave";
$l_spy_planetowner = "Possessore Pianeta";
$l_spy_planetname = "Pianeta";
$l_spy_sector = "Settore";

$l_spy_moves['none'] = "Non si muove";
$l_spy_moves['toship'] = "Alla nave";
$l_spy_moves['toplanet'] = "Al pianeta";

$l_spy_comeback = "Richiama";
$l_spy_nospieshere = "Non hai spie su questo pianeta!";
$l_spy_transferred = "spie trasferite";
$l_spy_backonship = "La spia è ora sulla tua nave.";
$l_spy_backfailed = "Richiamo fallito.";
$l_spy_changetitle = "Variazione proprietà della spia [spyID].";
$l_spy_occupied = "La tua spia [spyID] è impiegata come [job], con una percentuale di [percent].";
$l_spy_dismiss = "Congedare la spia?";
$l_spy_changebutton = "Cambia";
$l_spy_changejob = "Cambiare lavoro o Movimento";
$l_spy_linkback = "per andare al menu spie.";
$l_spy_changed1 = "Movimento cambiato.";
$l_spy_changed2 = "Spia congedata e movimento cambiato.";
$l_spy_changefailed = "Cambio fallito.";
$l_spy_cleanupplanettitle = "Eliminazione spie sul tuo pianeta:";
$l_spy_notyourplanet = "Non è il tuo pianeta.";
$l_spy_cleanuptext[1] = "Ricerca veloce. Costa [creds] crediti e [turns] turni.";
$l_spy_cleanuptext[2] = "Ricerca più precisa. Costa [creds] crediti e [turns] turni.";
$l_spy_cleanuptext[3] = "Ricerca migliore. Costa [creds] crediti e [turns] turni.";
$l_spy_cannotcleanupplanet = "Hai solo [credits] crediti sul pianeta e [turns] turni.";
$l_spy_cleanupbutton1 = "Inizio ricerca sul pianeta.";
$l_spy_cleanupplanettitle2 = "Hai attivato i tuoi sensori planetari per trovare spie nemiche sul pianeta.";
$l_spy_spyfoundonplanet = "Hai individuato la spia [spyID] del giocatore [player] sul tuo pianeta. Hai ucciso quella spia.";
$l_spy_spynotfoundonplanet = "Non hai trovato alcuna spia nemica sul tuo pianeta.";
$l_spy_notenough = "Non hai abbastanza crediti o turni per avviare una Ricerca.";

$l_spy_cleanupshiptitle = "Inizio Ricerca spie sulla tua nave:";
$l_spy_notinspecial = "Devi essere ad un porto Dispositivi per ripulire la tua nave.";
$l_spy_cleanupshiptext[1] = "Ricerca veloce. Costa [creds] crediti e [turns] turni.";
$l_spy_cleanupshiptext[2] = "Ricerca più precisa. Costa [creds] crediti e [turns] turni.";
$l_spy_cleanupshiptext[3] = "Ricerca migliore. Costa [creds] crediti e [turns] turni.";
$l_spy_cannotcleanupship = "Hai solo [credits] crediti e [turns] turni.";
$l_spy_cleanupbutton2 = "Inizio ricerca sulla tua nave";
$l_spy_cleanupshiptitle2 = "Hai attivato i tuoi sensori per trovare spie nemiche sulla tua nave.";
$l_spy_spyfoundonship = "Hai individuato la spia [spyID] del giocatore [player] sulla tua nave, e l'hai uccisa.";
$l_spy_spynotfoundonship = "Non hai trovato alcuna spia nemica sulla tua nave.";

$l_spy_infodeleted = "Messaggio cancellato";
$l_spy_infonotyours = "Non è il tuo messaggio.";
$l_spy_noinfo = "Le tue spie sulle navi nemiche non hanno individuato ancora nulla.";
$l_spy_infotitle = "Le tue spie hanno individuato le seguenti informazioni:";
$l_spy_time = "Ora";
$l_spy_type = "Tipo";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Pianeta";
$l_spy_datatext[1] = "C'è il pianeta [planet] del giocatore [player] nel settore [sector].";
$l_spy_delete = "Elimina";
$l_spy_messages = "per vedere cosa le tue spie hanno scoperto.";
$l_spy_defaulttitle1 = "Spie su navi nemiche";
$l_spy_defaulttitle2 = "Spie su pianeti nemici";
$l_spy_defaulttitle3 = "Spie sui tuoi pianeti";
$l_spy_defaulttitle4 = "Spie sulla tua nave";

$l_spy_no1 = "Non hai spie su navi nemiche.";
$l_spy_no2 = "Non hai spie su pianeti nemici.";
$l_spy_no3 = "Non hai spie sui tuoi pianeti.";
$l_spy_no4 = "Non hai spie sulla tua nave.";
$l_spy_nospiesatall = "Non hai spie.";
$l_spy_notknown = "Sconosciuto";


$l_spy_trytitle = "Sul pianeta questa spia tenterà di";

$l_spy_cantsendfeds = "Spiacente, ma le spie non possono essere inviate a pianeti della Federazione o Indipendenti.";
$l_spy_cantsendteam = "Non puoi inviare spie a pianeti dei tuoi compagni di squadra.";
$l_spy_messagesdeleted = "Tutti i messaggi cancellati";
$l_spy_deleteall = "Elimina tutti";
$l_spy_onplanet = "Spie sul pianeta";
$l_spy_menu = "per tornare al menu spie.";
?>
