<?php
$l_nav_title             = "Computer di Navigazione";
$l_nav_nocomp            = "Il Computer di Navigazione non è disponibile";
$l_nav_query             = "Inserisci il settore per il quale si deve trovare il percorso: ";
$l_nav_pathfnd           = "Percorso trovato";
$l_nav_answ1             = "Ti costerà";
$l_nav_answ2             = "turni per andare in tale settore.";
$l_nav_proper            = "La tecnologia del tuo computer è troppo primitiva per calcolare un percorso di Rotte warp verso tale settore.";
$l_nav_autoroutename = "Nome Autostrada Opzionale:";
$l_nav_manuallist = "Costruito manualmente WarpLink Lista Autoroute";
$l_nav_warplinksleaving = "Warp Links Lasciando [sector_name]";
$l_nav_nowarplinksleaving = "Non ci sono warplinks lasciare questo settore.";
$l_nav_warp_from = "Warp";
$l_nav_rs_from = "RSMove da";
$l_nav_notinlogs = "Nessun dato disponibile su questo settore.";
?>
