<?php
$l_casino_title = "&quot;Casino";
$l_casino_welcome = "&quot;Velkommen til Casino, vi tilbyder i øjeblikket følgende Spil og Faciliteter";
$l_casino_option = "&quot;Rooms";
$l_casino_detail = "&quot;Beskrivelse";

// Blackjack
$l_bet = "&quot;Bet";
$l_stand = "&quot;Stand";
$l_hit = "&quot;Hit";
$l_firsthand = "&quot;Førstehånd";
$l_secondhand = "&quot;Second Hand";
$l_insurance = "&quot;Forsikring";
$l_doubledown = "Double Down";
$l_lobby = "&quot;Lobby";
$l_split = "Dele";
$l_credits = "Credits";
$l_yourbet = "&quot;Din Bet";
$l_nobet = "&quot;Din indsats har overskredet din kreditgrænse, bedes bet igen.";
$l_dealerwins = "Dealeren vinder!";
$l_dealerbust = "Dealer Bust!";
$l_dealerloses = "Dealer taber!";
$l_dealerblackjack = "Dealer Blackjack!";
$l_push = "PUSH";
$l_playerwins = "&quot;Vinder!";
$l_playerbust = "&quot;Player buster!";
$l_playerloses = "&quot;Taber spilleren!";
$l_playerblackjack = "&quot;Player Blackjack!";
$l_place_bet = "&quot;Placer din indsats";
?>
