<?php
$l_contact_admin_title = "Kontakt Game Administrator";
$l_contact_admin_thanks = "Tak for din kommentar.";
$l_contact_admin_email_alert = "Angiv en gyldig email-adresse.";
$l_contact_admin_name_alert = "Indtast dit navn.";
$l_contact_admin_comment_alert = "Indtast dine kommentarer.";
$l_contact_admin_name = "Navn";
$l_contact_admin_email = "E-mail";
$l_contact_admin_comment = "Spørgsmål / Kommentar";
$l_contact_admin_submit = "Indsend Spørgsmål / kommentarer";
$l_contact_admin_close = "Luk vinduet";
$l_contact_admin_thanks_comment = "Tak for din kommentar eller et spørgsmål. Vi vil behandle alle spørgsmål og e-mail med vores svar.";

?>
