<?php
$l_sm_title = "Sektor missilaffyring";
$l_sm_invalid = "Der er ikke et skud forbindelse mellem denne sektor og destination sektor.";
$l_sm_notarg = "Målet ikke i denne sektor.";
$l_sm_noturn = "Du skal have mindst en tur til brand din sektor Missile.";
$l_sm_nosectormissile = "Du er ikke fører nogen Sector Missiler.";
$l_sm_noscan = "Sensorer kan ikke få en rettelse på mål!";
$l_sm_flee = "Target ud manøvrerede de Sektor Missile!";
$l_sm_ewd = "Målret udøver en nødsituation warp enheden, når det opdages de Sektor Missile!";
$l_sm_imtitle = "Skib under angreb";
$l_sm_imbody = "[playername] er at angribe dit skib med en sektor Missile!";
$l_sm_sectormissilefail = "Sektoraftalen Missile fungerer korrekt, når den ramte fjendtlige skibe skjoldet!";
$l_sm_sectormissilefail2 = "Sektoraftalen Missile fungerer korrekt, når den ramte fjendtlige skibe rustning!";
$l_sm_shieldhit = "[target] &#39;s skjolde er ramt for [amount] skade!";
$l_sm_shieldsdown = "[target] &#39;s skjolde er nede!";
$l_sm_armorhit = "[target] &#39;s panser er ramt for [amount] skade!";
$l_sm_armorbreached = "[target] &#39;s panser overtrådt!";
$l_sm_targetnoenergy = "Fjendens skibe har ingen energi! Sektor Missile ikke!";
$l_sm_attacking = "Offensiv [target] med [shipname]";
$l_sm_targetok = "Du har ikke destory [name] &#39;s skib.";
$l_sm_lost = "[target] mistet [armor] rustning point og [energy] energi enheder.";
$l_sm_destroyed = "[target] &#39;s skib er blevet ødelagt.";
$l_sm_escapepod = "En flugt pod blev lanceret!";
?>
