<?php
$l_chf_youretreatback = "Du trække sig tilbage til dit tidligere placering";
$l_chf_movefailed = "Flyt mislykkedes.";
$l_chf_thefightersdetectyou = "Krigere registrere dig!";
$l_chf_therearetotalfightersindest = "Der er [chf_total_sector_fighters] krigere i din destination sektor.";
$l_chf_youcanretreat = "<B>Retreat</b> - vil koste en ekstra tur.";
$l_chf_inputfight = "<B>Fight</b> - Du skal besejre alle de krigere til at komme ind i sektoren.";
$l_chf_inputcloak = "<B>Kappe</b> - Brug din tilsløring enheden og forsøge at undgå at krigere.";
$l_chf_go = "Start";
$l_chf_inputrun = "<B>Angreb og Run</b> - Du har en lettelse angreb køre og trække sig tilbage. Men du kan tage nogle skader under tilbagetog.";
?>
