<?php
$l_beacon_title = "Deploy Space Beacon";
$l_beacon_notpermitted = "Deploying plads beacons i denne sektor er ikke tilladt.";
$l_beacon_reads = "Nuværende fyrtårn læser";
$l_beacon_none = "Der i øjeblikket ikke er en ledestjerne i denne sektor.";
$l_beacon_enter = "Indtast tekst til fyrtårn";
$l_beacon_nowreads = "Beacon nu læser";
$l_beacon_donthave = "Du behøver ikke have en plads fyrtårn.";
?>
