<?php
$l_login_sclosed = "Server Lukket";
$l_login_closed_message = "Server lukket indtil videre.";
$l_login_title2 = "Login Phase Two";
$l_login_banned = "<b>Du er blevet udelukket fra dette spil som administrator. Du er ikke længere velkommen til at spille på denne server. Næste gang, opfører sig.</b>";
$l_login_died			= "Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie = "På grund af alvoren af denne forbrydelse, og den onde angreb imod dig, har Føderation allernådigst har besluttet at give en gratis kloning fra din tilbage. Desværre, selv i dag og alder, kan nye kloner ikke eje fast ejendom, bortset fra det grundlæggende til at leve. Du vil blive forsynet med en grundlæggende skib og et par kreditter til at få dig i gang. Forhåbentlig dit næste liv vil blive bedre.";
$l_login_newlife		= "Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser = "Du havde ingen undslippe pod, og på grund af dit beskedne succes i dette liv, Federation nægter at klone dig. Din fortsat bør i sidste ende falde i en tyngdekraft godt, forhåbentlig til at blive brugt til at skabe liv et andet sted ... flere milliarder år fra nu. <BR><BR> Bedre held næste spil ...";
$l_login_4gotpw1 = "Den adgangskode, du indtastede, er forkert. <BR><BR> Hvis du har glemt din adgangskode,";
$l_login_4gotpw2 = "at få den e-mailet til dig. <BR><BR> Ellers,";
$l_login_4gotpw3 = "at prøve igen. Forsøg logges med IP-adressen";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new_player.php>here</A>.";
$l_login_diedincident = "Du er døde i en forfærdelig hændelse.";
$l_login_blackbox = "er Blackbox oplysninger, der var hentet fra dine skibe vraggods.";
$l_new_login = "at gå til login-skærmen.";
$l_login_playerlimit = "Serveren har nået det maksimale antal spillere støtter. Prøv at logge ind på et senere tidspunkt.";
?>
