<?php
$l_scan_title = "Scan Ship";
$l_scan_turn = "Du skal have mindst en tur til at scanne et andet skib.";
$l_scan_ron = "Scan resultater på";
$l_scan_capt = "Kaptajn ved:";
$l_scan_arma = "Bevæbning:";
$l_scan_carry = "Carrying:";
$l_scan_bounty = "Dette skib har en samlet dusør på det af [amount] kreditter.";
$l_scan_fedbounty = "Dette skib har en dusør på det fra The Federation.";
$l_by_nofedbounty = "Angribende denne afspiller vil <B>ikke</b> resultere i Føderation placere en dusør på dig.";
?>
