<?php
$l_sn_title = "Sektor Noter";
$l_sn_pntitle = "Sektorer med Personlige noter";
$l_sn_tntitle = "Sektorer Notes med Team";
$l_sn_psntitle = "Personlig Sektor Noter";
$l_sn_tsntitle = "Team Sektor Noter";
$l_sn_editnote = "Edit Sector Bemærk:";
$l_sn_deleteedit = "Slette eller redigere:";
$l_sn_addnote = "Tilføj Sector Bemærk:";
$l_sn_list = "Liste Sektorer Noter";
$l_sn_listts = "Liste Sektorer med Team Notes";
$l_sn_addteam = "Tilføj Team";
$l_sn_deleteteam = "Slet Team";
$l_sn_delete = "Slet";
$l_sn_saveteam = "Gem Team";
$l_sn_deletepersonal = "Slet Personlig";
$l_sn_addpersonal = "Tilføj personlige";
$l_sn_savepersonal = "Gem personlige";
$l_sn_editpersonal = "Rediger personlige";
$l_sn_editteam = "Rediger Team";

$l_sn_hdsector = "Sektor";
$l_sn_hdtype = "Type";
$l_sn_hdowner = "Ejer / Team";
$l_sn_hdplanets = "Planeter";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mines";
$l_sn_hdscanfrom = "Scan Fra";
$l_sn_hddetail = "Detail";
$l_sn_hddate = "Date / Time";
$l_sn_hddelete = "Slet";
$l_sn_hdteam = "Team";
$l_sn_view = "Se";
$l_sn_no = "Nej";
$l_sn_yes = "Ja";
$l_sn_nonotes = "Ingen sektor Noter Found";

?>
