<?php
$l_news_title = "Universe Nyheder";
$l_news_info = "FNN er blandt galaksens ledere <br> i nyheder og information levering. <br> Bemandet 24 timer, syv dage om ugen med en <br> dedikeret personale i FNN&#39;s galakse hovedkvarter <br> i Proxima Centauri og etater galaxywide!";
$l_news_for = "Nyheder til";
$l_news_prev = "foregående dag";
$l_news_next = "næste dag";
$l_news_none = "Beklager, ingen nyheder i dag.";
$l_news_flash = "News Flash";
$l_news_end = "Slutningen af nyheder";
$l_news_bestviewed = "Ses bedst i Opera, Safari og IE";
$l_news_fedannouncements = "Federation Announcements";
$l_news_planetarynews = "Planetary News";
$l_news_planetshipnews = "Planetary and Ship Nyheder";
$l_news_afteractionnews = "Efter Action Combat Nyheder";
?>
