<?php
$l_zi_title = "Zone Information";
$l_zi_nexist = "Denne del af rummet eksisterer ikke!";
$l_zi_feds = "Federation";
$l_zi_traders = "Alliance Space";
$l_zi_nobody = "Ingen";
$l_zi_war = "Stridigheder";
$l_zi_allow = "Tilladt";
$l_zi_notallow = "Ikke tilladt";
$l_zi_limit = "Begrænset til ejer og allierede";
$l_zi_ul = "Ubegrænset";
$l_zi_control = "Du er i kontrol af denne zone";
$l_zi_tochange = "at ændre sin lovgivning.";
$l_zi_owner = "Zone ejer";
$l_zi_maxhull = "Maksimale gennemsnitlige tech niveau tilladt";
?>
