<?php
$l_artifact_title = "Hent Artifact";
$l_artifact_list_title = "Liste over Erhvervet Fejl";
$l_artifact_noscan = "Din scannere kunne ikke finde den genstand.";
$l_artifact_noturn = "Du har ikke nok skiftes til at hente denne artefakt.";
$l_artifact_classname = "Artifact Navn";
$l_artifact_description = "Artifact Beskrivelse";
$l_artifact_imagename = "Artifact Image";
$l_artifact_incomplete = "Artifact Pieces";
$l_artifact_process = "Brug Completed Artifact";

?>
