<?php
$l_defense_deploy_title = "Implementer Sector Mines &amp; Fighters";
$l_defense_deploy_noturn = "Du skal have mindst en tur til at indsætte sektor forsvarsværker.";
$l_defense_deploy_nopermit = "Deploying Mines og Fighters i denne sektor er ikke tilladt.";
$l_defense_deploy_nodeploy = "Kan ikke anvende her. Et andet skib eller hold har miner eller krigere i denne sektor.";
$l_defense_deploy_info1 = "Du er i øjeblikket i sektor [sector]. Der er [mines] miner og [fighters] krigere her.";
$l_defense_deploy_info2 = "Du har [mines] miner og [fighters] krigere til rådighed til at indsætte";
$l_defense_deploy_deploy = "Implementer";
$l_defense_deploy_deployed = "Indsat";
$l_defense_deploy_att = "Attack";
$l_defense_deploy_notorps = "Du har ikke nok torpedoer.";
$l_defense_deploy_nofighters = "Du har ikke nok kæmpere";
$l_defense_deploy_dmines = "Indsat [mines] miner.";
$l_defense_deploy_dfighter = "Deployeret [fighters] krigere.";
$l_defense_deploy_max_fighters = "Denne sektor kan støtte højst [amount] krigere.";
$l_defense_deploy_toomanyfighters = "Du har forsøgt at installere flere krigere end sektoren kan støtte.";
?>
