<?php
$l_autotrade_title = "Auto Traderoute Menu";
$l_autotrade_dismiss2 = "Auto Traderoutes udgår.";
$l_autotrade_report = "Auto Traderoute Report";
$l_autotrade_planet = "Planet";
$l_autotrade_hull = "Hull";
$l_autotrade_energy = "Energi";
$l_autotrade_capacity = "Kapacitet";
$l_autotrade_goods = "Varer Pris";
$l_autotrade_ore = "Ore Pris";
$l_autotrade_organics = "Organics Pris";
$l_autotrade_energy = "Energy Price";
$l_autotrade_colonist = "Kolonist Pris";
$l_autotrade_credits = "Handel Credits";
$l_autotrade_delete = "Slet <br> Rute";
$l_autotrade_unnamed = "Unavngiven";
$l_autotrade_noroute = "Nr. Rute";
$l_autotrade_sector = "Sektor";
$l_autotrade_credit2 = "kreditter";
$l_autotrade_deletebutton = "Slet";
$l_autotrade_noroute2 = "Du har ikke nogen opsætning Auto Traderoutes.";
?>
