<?php
$l_footer_one_player_on = "Der er 1 spiller online.";
$l_footer_players_on_1 = "Der er";
$l_footer_players_on_2 = "Spillere online:";
$l_footer_until_update = "sekunder, indtil næste opdatering.";
$l_footer_no_players_on = "Der er ingen spillere online.";

$l_footer_news = "Local FNN News";
$l_footer_title = "Alien Assault Traders";
$l_footer_help = "for hjælp om denne side.";
$l_footer_click = "Klik";

$l_footer_open_slots = "Maksimal Online:";
$l_footer_onlinereset = "Spiller Online Time Reset i";
$l_footer_onlinecountdown = "Spiller Online Time Countdown:";
?>
