<?php
$l_warp_unlinked = "Target sektor ([target_sector]) ikke har et link fra denne sektor.";
$l_warp_forbidtwo = "Brug af en Warp Editor til at fjerne en to-vejs link til sektor [target_sector] er ikke tilladt.";
$l_warp_removed = "Link fjernet til";
$l_warp_removedtwo = "Link fjernet til og fra";
$l_warp_nomoney = "Du har ikke nok kredit for at slette warp linket.";
$l_warp_noenergy = "Du har ikke nok energi til at slette warp linket.";
?>
