<?php
$l_shipyard_title = "Værft";
$l_planet = "Planet";
$l_ship_welcome = "Velkommen til din Planetary værft. Vi tilbyder i øjeblikket disse modeller til salg.";
$l_ship_class = "Klasse";
$l_ship_properties = "Klasse Egenskaber";
$l_ship_current = "Nuværende";
$l_ship_outstorage = "Kom ud af Storage";
$l_ship_storagecost = "Lageromkostninger";
$l_ship_storagewarn = "Når du tager din Pioneer ud af lagerplads du vil miste den, du er udstedt efter din første skib ødelæggelse.";
$l_ship_levels = "Ship Komponenter Niveauer";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Pris";
$l_ship_turns = "Skiftedes til at bygge";
$l_ship_purchase = "Købe";
$l_ship_stored = "Lagrede";
$l_ship_basehull = "Base Hull:";

$l_ship_averagemaxtech = "Gennemsnit Maksimum Tech Niveau:";
$l_ship_averagenormaltech = "Gennemsnitlig Normal Tech Niveau:";
$l_ship_averagecurrenttech = "Gennemsnitlig Current Tech Level:";
?>
