<?php
///SPIES
$l_dig_title = "Dignitar Menu";
$l_dig = "Honoratiores";
$l_dig_disabled = "Dignataries er slået fra!";
$l_dig_noturn = "Du skal have mindst en tur til at sende en fornem til en planet.";
$l_dig_notonboard = "Du har ikke nogen fornem person om bord.";
$l_dig_ownplanet = "Du kan ikke sende en fornem person til en fjendtlig planet.";
$l_dig_unownedplanet = "Du kan ikke sende en fornem til unowned planet.";
$l_dig_planetfull = "Der er allerede tilladt [max] honoratiores på denne planet.";
$l_dig_sendtitle = "Sende en fornem [digID] til planet: <BR> Vælg dignitar&#39;s mission:";

$l_dig_codenumber = "Kode";
$l_dig_job = "Arbejde";
$l_dig_percent = "Procent";
$l_dig_move = "Movement";
$l_dig_action = "Action";
$l_dig_shipowner = "Reder";
$l_dig_shipname = "Skibsnavn";
$l_dig_shiptype = "Ship klasse";
$l_dig_shiplocation = "Ship Beliggenhed";
$l_dig_planetowner = "Planet Ejer";
$l_dig_planetname = "Planet";
$l_dig_sector = "Sektor";

$l_dig_waiting = "Venter på et job";
$l_dig_max = "Maksimal Per Planet";
$l_dig_legend = "Dignitar Legend";
$l_dig_description = "Dignitar Beskrivelse";
$l_dig_waiting_description = "Dignitar vil skabe torpedoer og krigere mens de venter på et job opgave.";
$l_dig_changeerror = "Dignitar jobskifte Report";

$l_dig_nospieshere = "Du har ikke nogen honoratiores på denne planet!";
$l_dig_transferred = "honoratiores overføres";
$l_dig_backonship = "Den dignitar er nu på dit skib.";
$l_dig_dismiss = "Afskedige dignitar?";
$l_dig_changebutton = "Ændre";
$l_dig_notyourplanet = "Det er ikke jeres planet.";

$l_dig_defaulttitle1 = "Honoratiores på fjendtlige skibe";
$l_dig_defaulttitle2 = "Honoratiores på dine planeter";
$l_dig_defaulttitle3 = "Honoratiores på dine planeter";
$l_dig_defaulttitle4 = "Honoratiores på dit skib";

$l_dig_no1 = "Du har ikke nogen honoratiores på fjendens skibe.";
$l_dig_no2 = "Du har ikke nogen honoratiores på din planeter.";
$l_dig_no3 = "Du har ikke nogen honoratiores på din planeter.";
$l_dig_no4 = "Du har ikke nogen honoratiores på dit skib.";
$l_dig_nodignitaryatall = "Du har ikke nogen honoratiores.";
$l_dig_notknown = "Ukendt";
$l_dig_dismiss = "Afvis";
$l_dig_dismiss2 = "Honoratiores afskediget.";
$l_dig_menu = "at vende tilbage til dignitar Menu.";

?>
