<?php
// probe.php probe2.php probe3.php
$l_probe_defense_levels = "Probe Niveauer";
$l_probe_engine = "Motor";
$l_probe_sensors = "Sensorer";
$l_probe_cloak = "Cloak";
$l_probe_title = "Space Probe Menu";
$l_probe_none = "Du er ikke i samme sektor som denne sonde, så du kan ikke interagere med det.";

$l_probe_named = "Velkommen til Probe Antal [probename], der ejes af [name], beliggende i sektor [sector].";
$l_probe_orders = "[orders] Probe at søge univers";
$l_probe_orders_link = "Program";
$l_probe_upgrade = "[upgrade] Probe Sensorer / Motor / Cloak";
$l_probe_upgrade_link = "Upgrade";
$l_probe_pickup = "[pickup] Probe til senere placering";
$l_probe_pickup_link = "Pickup";
$l_probe_update = "Opdatering";

$l_probe_att_link = "Attack";
$l_probe_att = "[attack] om sonde";
$l_probe_att_sure = "Er du sikker ...";
$l_probe_scn_link = "Scan";
$l_probe_scn = "[scan] sonde";

$l_probe_unknown = "Ukendt";
$l_plant_scn_turn = "Du skal have mindst en tur til at scanne en sonde.";
$l_probe_noscan = "Sensorer kan ikke få en rettelse på mål!";
$l_probe_logscanA = "[name] forsøgt at scanne en af dine sonder i sektor [sector], men det mislykkedes.";
$l_probe_logscanB = "En af dine sonder i sektor [sector] blev scannet af [name].";
$l_probe_scn_report = "Scan resultater på [name], der ejes af: [owner]";

$l_probe_caplog = "Din sonde &#39;[probename]&#39; i sektoren [sector] blev taget til fange af [name].";
$l_probe_scan = "Probe scanninger sektor [sector] og konstaterer:";
$l_probe_destroyprobe = "Destroy sonde";
$l_probe_destroyed = "Probe Destroyed!";
$l_probe_warning = "Gøre dette vil fuldstændigt ødelægge denne sonde";
$l_probe_confirm = "Vil du virkelig ønsker at ødelægge denne sonde?";
$l_gns_turn = "Du har ikke nok skiftes til at ødelægge denne sonde";
$l_probe_type = "Probe Type";
$l_probe_type0 = "Stationære Probe";
$l_probe_type1 = "Sentry Probe";
$l_probe_type2 = "Warp Probe";
$l_probe_type3 = "Realspace Probe";
$l_probe_type4 = "Sekventiel Realspace Probe";
$l_probe_target = "Target Sector";
$l_probe_ordered = "Programmeret Probe og vil begynde at søge.";
$l_probe_order2 = "Sonden er en [type] og er rettet mod sektor [target]";
$l_probe_pickedup = "Sonde samles op og placeres i aktiv opbevaring";
$l_probe_title = "Probe Menu";
$l_probe_messages = "at se, hvad dine spioner har opdaget.";

$l_probe_defaulttitle1 = "Aktiv Probes";
$l_probe_defaulttitle2 = "Sonder du har hentet";
$l_probe_defaulttitle3 = "Sonder på dine planeter";
$l_probe_defaulttitle4 = "Sonder på dit skib";
$l_probe_linkback = "at gå til sonden menuen.";
$l_probe_no1 = "Du har ikke nogen aktive sonder.";
$l_probe_no2 = "Du har ikke nogen sonder i opbevaring.";
$l_probe_no3 = "Du har ikke nogen sonder på din planeter.";
$l_probe_no4 = "Du har ikke nogen sonder på dit skib.";
$l_probe_noprobeatall = "Du har ikke nogen sonder.";
$l_probe_notknown = "Ukendt";
$l_probe_launch = "Tabe";
$l_probe_detect = "Detected";
$l_probe_codenumber = "Kode";
$l_probe_job = "Arbejde";
$l_probe_percent = "Procent";
$l_probe_move = "Movement";
$l_probe_view = "Se";
$l_probe_action = "Action";
$l_probe_shipowner = "Reder";
$l_probe_shipname = "Skibsnavn";
$l_probe_shiptype = "Ship klasse";
$l_probe_shiplocation = "Ship Beliggenhed";
$l_probe_planetowner = "Planet Ejer";
$l_probe_planetname = "Planet";
$l_probe_sector = "Nuværende Sector";
$l_probe_tsector = "Target Sector";
$l_probe_type = "Probe Type";
$l_probe_forbid = "Du kan ikke droppe sonder i denne sektor";

$l_probe2_title = "Launch Space Probe";
$l_probe2_turn = "Du skal have mindst en tur til at bruge en rumsonde.";
$l_probe2_onplanet = "Du kan ikke bruge denne enhed, mens på planeten overflade.";
$l_probe2_noprobe = "Du har ikke nogen rumsonder.";
$l_probe2_forbid = "Lancering af en sonde i denne sektor er ikke tilladt.";
$l_probe2_launched = "Rumsonde lanceret!";

$l_probe2_warplink = "Warplink";
$l_probe2_player = "Player";
$l_probe2_onboarda = "om bord på et";
$l_probe2_classship = "klasse skib";
$l_probe2_traveled = "rejste til sektor";
$l_probe2_fedjammed = "Føderation der blokerer alle føler scanninger til Sector 1.";
$l_probe2_lastseen = "Seneste Ship Seen";
$l_probe2_portfound = "Port Found";
$l_probe2_supports = "Understøtter";
$l_probe2_planets = "planeter";
$l_probe2_sectord = "Sektor forsvar Detected";
$l_probe2_mines = "Mines";
$l_probe2_fighters = "Fighters";
$l_probe2_ships = "Skibe Detected";
$l_probe2_ships2 = "Ship Detected";
$l_probe2_noneowned = "Nr. planeter ikke ejes af du er blevet opdaget.";
$l_probe2_warplinks = "Warplinks";
$l_probe2_nothing = "Intet Detected";
$l_probe2_nocredits = "Du har ikke nok kredit for denne transaktion. De samlede omkostninger er [total] kreditter og du kun har [credits] kreditter.";

$l_probe_forbidSG = "Du kan ikke sende en Realspace type sonde i Sektor Genesis skabt sektorer.";
$l_probe_forbidFED = "Du kan ikke sende en Realspace type sonde i Føderation eller Alliancen ejet sektorer.";
$l_probe_forbidINVALID = "Din destination sektor er et ugyldigt sektor navn.";
?>
