<?php
$l_die_title = "Self-Destruct";
$l_die_rusure = "Er du sikker på at du ønsker at ødelægge dit skib? Dette vil fjerne dig fra spillet.";
$l_die_goodbye = "Farvel grusom galakse!";
$l_die_check = "Er du positiv, at du ønsker at fjerne dig fra spillet?";
$l_die_nonono = "NEJ! NEJ! NEJ!";
$l_die_what = "Hvad tænkte jeg på?";
$l_die_count = "5 .. 4 .. 3 .. 2 .. 1 .. Boom!";
$l_die_vapor = "Du skibet og alle ombord er fordampet.";
$l_die_please1 = "logout";
$l_die_please2 = "Please, [logout_link]";
$l_die_exploit = "Må ikke lege med det, du ikke forstår.";
?>
