<?php
$l_opt2_title = "Gem indstillinger";
$l_opt2_passunchanged = "Password forblev uændret. <BR><BR>";
$l_opt2_srcpassfalse = "Original adgangskode forkert. Password forblev uændret. <BR><BR>";
$l_opt2_newpassnomatch = "Nyt password felter stemmer ikke overens. Password forblev uændret. <BR><BR>";
$l_opt2_passchanged = "Password ændret. <BR><BR>";
$l_opt2_passchangeerr = "Fejl ved ændring af adgangskode <BR><BR>";
$l_opt2_userintup = "Brugergrænseflade indstilling opdateret. <BR><BR>";
$l_opt2_userintfail = "Undladt at opdatere brugergrænseflade indstilling. <BR><BR>";
$l_opt2_chlang = "Sproget er blevet indstillet til [lang]. <p>";
$l_opt2_chtemplate = "Skabelon er blevet indstillet til [template]. <p>";
$l_opt2_dhtmlup = "Dynamisk html indstilling opdateret. <BR><BR>";
$l_opt2_dhtmlfail = "Undladt at opdatere dynamisk html indstilling. <BR><BR>";
$l_opt2_shipnamechanged = "Shipname ændret til [name]. <BR><BR>";
$l_opt2_playernamechanged = "Spiller navnet ændret til [name] og [amount] kreditter trukket fra din skib konto. <BR><BR>";
$l_opt2_mapwidth = "Lokale og Galaxy Kort Bredde:";
?>
