<?php
$l_opt_title = "Vælg en Team ikon";
$l_opt_errorsize = "Fejl: Dit billede må ikke være større end 64x64 pixels i størrelse.";
$l_opt_errortype = "Fejl: Billedet skal være JPG, GIF eller PNG";
$l_opt_errornographic = "Fejl: ingen grafisk valgt.";
$l_opt_currentavatar = "Din nuværende Team Icon";
$l_opt_uploadavatar = "Overføre et ikon";
$l_opt_directory = "Vælg Team Icon Directory";
$l_opt_change = "Skift Directory";
$l_opt_select = "Select Team Icon";
$l_opt_noteam = "Du er ikke på et hold.";
$l_opt_notleader = "Kun Team koordinator kan ændre Team Icon.";
$l_opt_inuse = "Alle Team Ikoner i denne mappe er i brug.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
