<?php
$l_lrs_title = "Long Range Scan";
$l_lrs_nofull = "Din scannere ikke har fuld lang række scanning kapaciteter.";
$l_lrs_noturns = "Du skal have mindst $ fullscan_cost tur (r) til at køre en fuld lang række scanning.";
$l_lrs_used = "Brugt";
$l_lrs_turns = "";
$l_lrs_left = "venstre";
$l_lrs_reach = "Følgende steder kan nås fra sektor [sector]:";
$l_lrs_links = "Links";
$l_lrs_ships = "Skibe";
$l_lrs_click = "Klik på et af linkene for at flytte til denne sektor.";
$l_lrs_cantscan = "Kan ikke scanne sektor fra nuværende sektor!";
$l_lrs_zero = "Sektor 1 er for mange mennesker til at scanne for skibe!";
$l_lrs_moveto = "at flytte til sektor";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet = "View Log";
$l_lrs_fedjammed = "Føderation der blokerer alle føler scanninger.";
$l_lrs_sectormissile_question = "til brand sektor missil.";
$l_log_months = "array ( &#39;januar&#39;, &#39;februar&#39;, &#39;Marts&#39;, &#39;april&#39;, &#39;maj&#39;, &#39;juni&#39;, &#39;juli&#39;, &#39;august&#39;, &#39;September&#39;, &#39;oktober&#39;, &#39;November&#39;, &#39;December&#39;)";
$l_log_months_short = "array ( &#39;Jan&#39;, &#39;februar&#39;, &#39;mar&#39;, &#39;apr&#39;, &#39;maj&#39;, &#39;Juni&#39;, &#39;Jul&#39;, &#39;aug&#39;, &#39;September&#39;, &#39;Oktober&#39;, &#39;nov&#39;, &#39;dec&#39;)";
?>
