<?php
$l_by_title = "Bounties";
$l_by_noturn = "Du skal have mindst en tur til sted eller ændre en dusør.";
$l_by_amount = "Bounty Beløb";
$l_by_place = "Sted Bounty";
$l_by_nobounties = "Der er i øjeblikket ingen bounties.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Placeret af";
$l_by_thefeds = "Federation";
$l_by_cancel = "Annuller";
$l_by_yourself = "Du kan ikke placere en dusør på dig selv.";
$l_by_notenough = "Du har ikke nok kredit for at placere en dusør af dette beløb.";
$l_by_toomuch = "Du kan ikke placere denne gavmildhed. Største dusør tilladt på en anden spiller er [percent] procent af din nettoformue";
$l_by_zeroamount = "Bounties skal være større end 0 kreditter.";
$l_by_placed = "The Bounty er blevet placeret.";
$l_by_nobounty = "At dusør ikke længere eksisterer.";
$l_by_notyours = "At dusør blev ikke placeret af dig.";
$l_by_canceled = "The Bounty er blevet annulleret.";
$l_by_action = "Action";
$l_by_placebounty = "Sted eller se bounties.";
$l_by_moredetails = "Klik på navnet for yderligere informationer.";
$l_by_fedbounty          = "<font color=\"red\" size=\"4\"><b>Attacking this player would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbounty2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of attacking much smaller players. It has placed a bounty on you.</b></font>";
$l_by_notexists = "Den spiller, du sætter dusør på ikke eksisterer.";
$l_by_destroyed = "Du kan ikke placere en dusør på en spiller med en ødelagt skibet.";
$l_by_nofedbounty = "Du vil ikke modtage en dusør, hvis du angriber dette spillere skib eller planet.";
$l_by_fedcollectonly = "Kun Føderation kan Collect Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color=\"red\" size=\"4\"><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color=\"red\" size=\"4\"><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy = "Du vil ikke modtage en dusør, hvis du placerer en spion på denne spillere planet.";
$l_pay_partial = "Foretag delbetaling";
$l_pay_button = "Betal";

$l_by_thealliance = "Alliancen";
$l_by_alliancecollectonly = "Kun Alliancen kan Collect Bounty";
$l_by_bountyscan = "Bounty";
?>
