<?php
$l_ze_title = "Edit Zone";
$l_ze_notowner = "Du er ikke ejer af denne zone, så du kan ikke redigere det.";
$l_ze_name = "Zone navn";
$l_ze_allow = "Tillade";
$l_ze_attacks = "Tillad at angribe andre skibe";
$l_ze_genesis = "Tillad at skabe nye planeter";
$l_ze_return = "at vende tilbage til zonen information side";
$l_ze_saved = "Dine ændringer er blevet gemt.";
$l_ze_namematch = "FEJL: Zonens navn, du angav, er ens eller matcher en eksisterende Zonens navn.";
?>
