<?php
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] ramt [chm_roll] miner i sektoren [chm_sector].";
$l_chm_youlostminedeflectors = "Du mistet [chm_roll] minen ledes væk.";
$l_chm_youlostallminedeflectors = "Du har mistet alle dine mine ledes væk.";
$l_chm_youhadnominedeflectors = "Du havde ingen min ledes væk.";
$l_chm_yourshieldshitforminesdmg = "Deres skjolde er ramt for [chm_mines_left] skader.";
$l_chm_yourshieldsaredown = "Deres skjolde er nede!";
$l_chm_youlostallyourshields = "Du har mistet alle dine skjolde!";
$l_chm_yourarmorhitforminesdmg = "Din rustning er ramt for [chm_mines_left] skader.";
$l_chm_yourhullisbreached = "Din skroget er overtrådt!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] blev ødelagt af din miner i sektoren [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Dit skib er blevet ødelagt!";
$l_chm_luckescapepod = "Heldigvis har du en flugt pod!";

$l_chm_yourdeflectormalf1 = "Mine Udkastertud lancere systemet fungerer korrekt.";
$l_chm_yourdeflectormalf2 = "Du har kun været i stand til at lancere";
$l_chm_yourdeflectormalf3 = "procent af din mine ledes væk.";
$l_chm_enemytorpfailshields = "har ikke iværksat nogen torpedoer mod dine skjolde.";
$l_chm_enemytorpfailarmor = "har ikke iværksat nogen torpedoer mod din rustning.";

$l_chm_minemalf1 = "Enemy Miner har fungerer korrekt.";
$l_chm_minemalf2 = "Kun";
$l_chm_minemalf3 = "procent af minerne angribe fundet dit skib.";

$l_chm_youhitsomemines = "Du ramte [chm_roll] miner ud af [total_mines] miner!";
$l_chm_yourdeflectormalf2a = "Du har kun været i stand til at lancere [deflectors] procent af din mine ledes væk.";
$l_chm_mines_destroyed = "[number] af [target] miner er blevet ødelagt!";
$l_chm_mine_deflectors_left = "Du har [number] minen deflektorer venstre.";
$l_chm_mines_left = "Der er [number] miner venstre, og de er, der påvirker din rustning!";
$l_chm_minemalf2a = "Kun [deflectors] procent af minerne angribe fundet dit skib.";
$l_chm_mines_exhausted = "[player] Mines haves!";
$l_chm_armor_left = "Du har [number] rustning point venstre!";

?>
