<?php
$l_opt_title = "Vælg en Avatar";
$l_opt_errorsize = "Fejl: Dit billede må ikke være større end 64x64 pixels i størrelse.";
$l_opt_errortype = "Fejl: Billedet skal være JPG, GIF eller PNG";
$l_opt_errornographic = "Fejl: ingen grafisk valgt.";
$l_opt_currentavatar = "Din nuværende Avatar";
$l_opt_uploadavatar = "Upload en Avatar";
$l_opt_directory = "Vælg avatar Directory";
$l_opt_change = "Skift Directory";
$l_opt_select = "Vælg avatar";
$l_opt_inuse = "Alle Avatars i denne mappe er i brug.";
$l_opt_uploadtypes = "(GIF, JPG, PNG)";
?>
