<?php
$l_nav_title = "Navigation Computer";
$l_nav_nocomp = "Navigation computer er ikke tilgængelig";
$l_nav_query = "Indtast sektor til at finde vej til:";
$l_nav_pathfnd = "Sti fundet";
$l_nav_answ1 = "Det vil tage dig";
$l_nav_answ2 = "skiftedes til at komme til denne sektor.";
$l_nav_proper = "Du skal opgradere din Fighter Bay teknologi, før dine krigere kan finde en kæde rute for denne afstand.";
$l_nav_autoroutename = "Valgfrit Autoroute Navn:";
$l_nav_manuallist = "Manuelt Indbygget WarpLink Autoroute List";
$l_nav_warplinksleaving = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving = "Der er ingen warplinks forlader denne sektor.";
$l_nav_warp_from = "Warp fra";
$l_nav_rs_from = "RSMove fra";
$l_nav_notinlogs = "Ingen tilgængelige oplysninger om denne sektor.";
?>
