<?php
$l_opt_title = "Valg";
$l_opt_chpass = "Skift adgangskode";
$l_opt_curpass = "Nuværende adgangskode:";
$l_opt_newpass = "Ny adgangskode:";
$l_opt_newpagain = "Ny adgangskode (igen):";
$l_opt_userint = "Brugergrænseflade";
$l_opt_usenew = "Brug nye layout?";
$l_opt_lang = "Sprog";
$l_opt_template = "Skabelon";
$l_opt_select = "Vælg én:";
$l_opt_enabled = "Enabled";
$l_opt_save = "Gemme";
$l_opt_teamicon = "Team Icon";
$l_opt_shipname = "Shipname:";
$l_opt_mapwidth = "Lokale og Galaxy Kort Bredde:";
$l_opt_profiletitle = "Profil";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registreret hos Profil Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "Når du registrerer din afspiller på en anden server skabelonen, Shoutbox og nyheder ovenstående indstillinger vil blive brugt på serveren.";
$l_opt_showshoutbox = "Vis Shoutbox:";
$l_opt_shownewscrawl = "Vis gennemgang af nyheder:";
$l_opt_playername = "Spiller Navn:";
$l_opt_playernamecost = "Federation Name Change Gebyr: [amount] credits";
?>
