<?php
$l_warp_cantsame = "Du kan ikke oprette et link, når kilden er den samme som destination.";
$l_warp_twoerror = "Brug af en Warp Editor til at skabe en to-vejs-link til sektor [target_sector] er ikke tilladt.";
$l_warp_sectex = "Kan ikke oprette kæde link fra nuværende sektor - at ville overskride det maksimum på $ link_max per sektor.";
$l_warp_linked = "Target sektor ([target_sector]) allerede har et link fra denne sektor.";
$l_warp_coneway = "Link skabt en måde at";
$l_warp_ctwoway = "Link skabt til og fra";
$l_warp_nomoney = "Du har ikke nok kredit for at skabe warp linket.";
$l_warp_noenergy = "Du har ikke nok energi til at skabe warp linket.";
?>
