<?php
$l_autoroute_missingwarp = "Næste warplink mangler i denne sektor. Warp flytte afbrudt.";
$l_autoroute_SDabort = "Flyt Afbrudt pga. Sektor Defenses i sektoren.";
$l_autoroute_turns = "Fratrækkes [triptime] Turns og flyttes til [targetlink]";
$l_autoroute_noturns = "Du er ude af drejninger.";
$l_autoroute_title = "Auto Routes";
$l_autoroute_id = "Auto Rute ID";
$l_autoroute_start = "Auto Rute Start";
$l_autoroute_destination = "Auto Rute Destination";
$l_autoroute_warps = "Auto Rute mellemlinerne";
$l_autoroute_deleteroute = "Slet Rute";
$l_autoroute_info = "Klik på Start sektor Realspace til denne sektor, og begynde warping til destinationen sektor.";
$l_autoroute_delete2 = "Slet Routes";
$l_autoroute_noroutes = "Ingen Auto Routes";
$l_autoroute_createroute = "Opret ny Auto Rute";
$l_autoroute_deleted = "Auto Routes slettet.";
$l_autoroute_return = "Retur til Auto Rute Menu klik";
$l_autoroute_created = "Auto Route er blevet oprettet.";
$l_autoroute_realmove = "Realspace flytte til sektor";
$l_autoroute_warpmove = "Warp flytte til næste sektor";
$l_autoroute_warpfinal = "Warp flytte til sidste sektor";
$l_autoroute_editname = "Rediger Navn";
?>
