<?php
$l_profile_title = "Profil Registrering";
$l_profile_notenabled = "Profiler er ikke aktiveret på denne server.";
$l_profile_registered = "Denne afspiller er nu registreret hos Master Profile Server.";
$l_profile_nomatch = "Kunne ikke matche en profil på Master Profile Server med det navn og server-password indtastes.";
$l_profile_tryagain = "Du kan indtaste din spillerprofil navn og server password igen klikke";
$l_profile_name = "Profil Spiller Navn";
$l_profile_password = "Profil Server Password";
$l_profile_bannedserver = "Denne server er ikke tilladt at indsende profil oplysninger til Master Profil Server.";
$l_profile_bannedplayer = "Du er blevet udelukket fra Master Profil Server og kan ikke registrere spillere.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "Denne <u><b>server</b></u> kræver hver ny spiller at have en registreret profil. Du vil ikke få lov til at oprette en ny spiller, medmindre du har en registreret profil.";
$l_profile_updated = "Din skabelon, Shoutbox og nyheder kravle globale indstillinger er blevet opdateret på Profil Master Server. Disse indstillinger vil automatisk blive brugt, når du registrerer din profil på alle spil.";

?>
