<?php
$l_att_title = "Attack Ship";
$l_att_notarg = "Målet ikke i denne sektor.";
$l_att_noturn = "Du skal have mindst en tur til at angribe.";
$l_att_noatt = "Angribe nogen i denne sektor er ikke tilladt.";
$l_att_flee = "Target ud manøvrerede dig!";
$l_att_ewd = "Målret udøver en nødsituation warp enhed, når angrebet!";
$l_att_att = "Offensiv";
$l_att_beams = "Beam Exchange";
$l_att_torps = "Torpedo Exchange";
$l_att_fighters = "Fighter Exchange";
$l_att_lost = "mistet";
$l_att_ylost = "Du har tabt";
$l_att_sdown = "&#39;s skjolde er nede!";
$l_att_ydown = "Deres skjolde er nede!";
$l_att_shits = "&#39;s skjolde er ramt af";
$l_att_yhits = "Deres skjolde er ramt af";
$l_att_dmg = "skade";
$l_att_sarm = "&#39;s overtrådt rustning!";
$l_att_yarm = "Din rustning er blevet overtrådt!";
$l_att_ashit = "&#39;s panser er ramt af";
$l_att_ayhit = "Din rustning er ramt af";

$l_att_efhit = "&#39;s krigere er ødelagt.";
$l_att_yfhit = "af dine krigere er ødelagt.";
$l_att_ethit = "&#39;s torpedoer er ødelagt.";
$l_att_ythit = "af dine torpedoer er ødelagt.";
$l_att_of = "af";
$l_att_lostt = "mistede alle torpedoer.";
$l_att_ylostt = "Du har mistet alle torpedoer.";

$l_att_lostf = "mistede alle kæmpere.";
$l_att_ylostf = "Du har mistet alle kæmpere.";
$l_att_sdest = "&#39;s skib er blevet ødelagt.";
$l_att_espod = "En flugt pod blev lanceret!";
$l_att_ysalv = "Du reddede [ship_salvage_rate]% af skibet for [ship_salvage] kreditter. <BR> Din bedømmelse ændres af [rating_change] point.";
$l_att_andused = "og anvendes";
$l_att_stilship = "Du har ikke destory [name] &#39;s skib.";
$l_att_atyou = "angrebet dig";
$l_att_and = "og";
$l_att_yshiplost = "Dit skib er blevet ødelagt!";
$l_att_salv = "[name] reddede [ship_salvage_rate]% af skibet for [ship_salvage] kreditter";
$l_att_loosepod = "Heldigvis har du en flugt pod!";

$l_att_tnobeams = "sømme at være ude af stråleenergi.";
$l_att_tnobeamsf = "sømme at være ude af stråle energi og kan ikke angribe din krigere.";
$l_att_tnobeamst = "sømme at være ude af stråle energi og kan ikke angribe din torpedoer.";
$l_att_tfnoattack = "er ikke sende nogen krigere til at angribe dit skib.";
$l_att_tnotorps = "synes at være ude af torpedoer.";

$l_att_anobeams = "Du har opbrugt dine skibe stråleenergi.";
$l_att_anobeamsf = "Du har opbrugt dine skibe stråle energi og kan ikke angribe fjendens krigere.";
$l_att_anobeamst = "Du har opbrugt dine skibe stråle energi og kan ikke angribe fjenden torpedoer.";
$l_att_anofighters = "Dit skib har udtømt alle kann krigere.";
$l_att_anotorps = "Du har opbrugt din kann torpedoer.";
$l_att_imtitle = "Skib under angreb";
$l_att_imbody = "er at angribe dit skib.";

$l_att_luckybeams = "Enemy bjælker overbelastning påføre";
$l_att_luckyfighters = "Fjendtlige krigere gøre en overraskelse lette angreb og forårsage";
$l_att_luckytorps = "Fjendtlige torpedoer fremkalde en cascading skade effekt, der får";
$l_att_luckytimes = "gange den normale skade!";
?>
