<?php
$l_ship2_buytitle = "Købe et nyt skib";
$l_ship2_storetitle = "Værft Storage Facility";
$l_ship2_wrongclass = "Forkert skib klasse specificeret";
$l_ship2_buying = "Du køber:";
$l_ship2_tradein = "Handel I:";
$l_ship2_value = "Nuværende Ship Værdi:";
$l_ship2_newvalue = "Nyt skib Værdi:";
$l_ship2_totalcost = "Total Cost:";
$l_ship2_nomoney = "Du har ikke nok kredit til at købe dette skib.";
$l_ship2_purchase = "Købe";
$l_ship2_buynstore = "Købe nye skibe og gemme gamle";
$l_ship2_nomoney2 = "Du har ikke nok kredit for at gennemføre denne transaktion.";
$l_ship2_paystorage = "Du har fjernet dit skib fra lageret.";
$l_ship2_turns = "Du skal have mindst [turns] skiftedes til at udføre denne handling";
$l_ship2_error = "Intern fejl. Kan ikke finde skibet klasse.";
$l_ship2_owned = "Du allerede ejer denne model af skibet.";
$l_ship2_shipbought = "Du har lige købt et nyt skib!";

?>
