<?php
$l_new_pwis = "Dit password er";
$l_new_charis = "Din karakter navn er";
$l_new_title2 = "Opret ny Player Phase Two";
$l_new_blank = "E-mail, skibets navn, og karakter navn må ikke være tomt.";
$l_new_inuse = "E-mail-adresse [username] er allerede i brug.";
$l_new_forgotpw = "Glemt password?";
$l_new_inusechar = "Character navn [character], er allerede i brug.";
$l_new_similar_inusechar = "Din karakter navn lyder for ens til [character], et navn allerede er i brug.";
$l_new_inuseship = "Skibsnavn [shipname], er allerede i brug.";
$l_new_similar_inuseship = "Dit skib navn lyder for ens til [shipname], et navn, der allerede er i brug.";
$l_new_pwsent = "Password er blevet sendt til [username].";
$l_new_err = "Prøv igen";
$l_new_topic = "Alien Assault Traders Password";
$l_new_message = "Greetings, \ n \ nSomeone fra IP-adressen $ ip anmodet om, at din adgangskode for erhvervsdrivende blive sendt til dig. \ N \ nDit password er: [pass] \ n \ nThank du \ n \ nDet Traders web-team.";
$l_new_invalidemail = "Ugyldig e-mail-adresse.";
$l_new_tutorial = "Klik her for at læse Mini-selvstudium, før du logger ind i spillet.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login = "at gå til login-skærmen.";

?>
