<?php
$l_shout_title = "Shout Box";
$l_shout_title2 = ".:: ShoutBox::.";
$l_shout_public = "Offentlig";
$l_shout_team = "Team";
$l_shout_smiles = "Smilie&#39;s";
$l_shout_else = "anden";
$l_shout_refresh = "Refresh";
$l_shout_close = "Luk vinduet";
$l_shout_saved = "Shout gemt!";
$l_shout_return = "Retur til";
$l_shout_prev = "Forrige";
$l_shout_next = "Næste";
$l_shout_selectpage = "Vælg side";
$l_shout_page = "Side:";
$l_shout_teamtitle = ".:: TEAM ShoutBox::.";
?>
