<?php
$l_mail_title = "Mail Password";
$l_mail_noplayer         ="No Such Player! - Create a new player <a href=new_player.php>here</a>.";
$l_mail_sent = "Password er blevet sendt til";
$l_mail_topic = "$ game_name Password";
$l_mail_message = "Greetings, \ n \ nSomeone fra IP-adressen $ ip anmodet om, at din adgangskode for $ game_name blive sendt til dig \ n \ nDit password er: [pass] \ n \ nThank du \ n \ nDet $ game_name webteam.";
$l_new_login = "at gå til login-skærmen.";
$l_mail_failed = "Password undladt at sende til";
?>
