<?php
// port.php port_purchase.php
$l_trade = "Erhverv";
$l_title_port = "Port Trading";
$l_title_trade = "Trading Commodities";
$l_sector_war = "Krig embargo";
$l_war_info = "Krigen raser i denne sektor. Du kan ikke nå havnen gennem alle de fjendtlige styrker.";
$l_no_trade = "Handel forbudt";
$l_no_trade_out = "Handel på denne port er ikke tilladt for udenforstående";
$l_no_trade_info = "Handel på denne port er ikke tilladt";
$l_buying = "Opkøb";
$l_selling = "Selling";
$l_commodity = "Commodity";
$l_amount = "Mængde";
$l_price = "Pris";
$l_buy = "Købe";
$l_sell = "Sælge";
$l_trade_st_info = "Du har [free_holds] tomme lastrum, kan bære [free_power] mere energi enheder, og har [credits] kreditter.";
$l_upgrade_port_title = "Upgrade Port";
$l_device_port_title = "Device Port";
$l_spacedock_port_title = "Spacedock";
$l_no_credits = "Ikke nok kreditter";
$l_creds_to_spend = "Du har [credits] kreditter til at bruge.";
$l_cost = "Omkostninger";
$l_avail = "Tilgængelig";
$l_profit = "Profit";
$l_current = "Nuværende";
$l_current_level = "Nuværende niveau";
$l_current_qty = "Nuværende Mængder";
$l_max = "Max";
$l_ifyouneedmore = "Hvis du har brug for mere, kan du få adgang til denne port&#39;s [igb]";
$l_ifyouneedplan = "Adgang til planetens";
$l_igb_term = "IGB Banking Terminal";
$l_upgrade = "Upgrade";
$l_unlimited = "Ubegrænset";
$l_full = "Fuld";
$l_equipped = "Udstyret";
$l_n_a = "n / a";
$l_item = "Punkt";
$l_totalcost = "Samlede omkostninger";
$l_would_dump = "Hvis du ønsker at dumpe alle dine kolonister her, klik";
$l_noport = "Der er ingen havn her!";
$l_trade_turnneed = "Du skal have mindst en tur til handel på en havn eller en planet.";
$l_returnto_port1 = "her";
$l_returnto_port2 = "Klik på [port_link] for at vende tilbage til havnen menuen.";
$l_notenough_cargo = "Du har ikke nok fri lastrum på de varer, du ønsker at købe.";
$l_notenough_power = "Du har ikke nok fri energi lager for den energi, du ønsker at købe.";
$l_notenough_credits = "Du har ikke nok kredit for at fuldføre transaktionen.";
$l_notenough_turns = "Du har ikke nok skiftes til at fuldføre transaktionen.";
$l_trade_result = "Resultaterne for denne handel";
$l_trade_complete = "Handel afsluttet";
$l_trade_upgraded = "Opgraderet til niveau";
$l_trade_added = "added";
$l_trade_installed = "installeret";
$l_port_bounty = "Du kan ikke få adgang til en speciel havn, mens du har en dusør på dig placeret af The Federation. <BR>";
$l_port_bounty2 	 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "Du har ikke nok credtis at betale dusør på [amount] kreditter. <BR>";
$l_port_bountypaid 	 = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "Den IGB har udstedt en låsning på dit skib konto på grund af en sen lån betaling. Du kan ikke handle på en særlig havn, indtil du betale dit lån.";
$l_port_returntospecial = "at vende tilbage til forsyningsdepot.";
$l_toprobemenu = "at gå til sonden menuen.";
$l_ports_shiplimit = "Mindste Ship klasse til at montere enheden:";
$l_ports_needrepair = "Reparation";

$l_ports_needcredits = "Du har ikke nok kredit for denne transaktion. De samlede omkostninger er";
$l_ports_needcredits1 = "kreditter og du kun har";

$l_ports_tradeforbidden = "Handel forbudt";
$l_ports_nooutsiders = "Handel på denne port er ikke tilladt for udenforstående.";

$l_bought = "Du har købt";
$l_sold = "Du solgt";
$l_notenough_commodity = "Du har ikke nok [commodity] for at fuldføre transaktionen.";
$l_exceed_commodity = "Antal [commodity] overstiger udbud / efterspørgsel.";
$l_port_shiptoolarge = "Dit skib er for stort til at handle til denne port.";

$l_port_hold_unit = "Holds per enhed";


$l_port_welcome = "Port [sectorname] Velkommen&#39;s [player]";
$l_port_amountforsale = "Havnen har [amount] enheder af [commodity] til salg på [credits] kreditter pr.";
$l_port_holdsperunit = "[holds] lastrum kræves pr.";
$l_port_howmanypurchase = "Hvor mange [commodity] enheder vil du gerne købe?";
$l_port_unitstobuy = "Enheder til Køb";
$l_port_shipcarryingbuy = "Dit skib er i færd [shipunits] enheder af [commodity]. Du kan købe [buyunits] enheder med tilgængelige lastrum plads.";
$l_port_howmanysell = "[amount] enheder af [commodity] @ [credits] kreditter pr.";
$l_port_unitstosell = "Enheder til Sælg";
$l_port_perform = "Udfør Transaction";
$l_port_cargoholds = "Lastrum";

?>
