<?php
$l_s_yes = "Ja";
$l_s_no = "Nej";
$l_s_enabled = "Enabled";
$l_s_disabled = "Handicappede";

$l_s_modules = "Moduler";
$l_s_modulename = "Modul Navn";
$l_s_moduleauthor = "Author";
$l_s_moduleinfo = "Info";
$l_s_nomodules = "Ingen Moduler Loaded";

$l_s_gamestatus = "Spil status";
$l_s_allowpl = "Tillad Spillere";
$l_s_allownewpl = "Tillad nye spillere";

$l_s_gameoptions = "Spillets indstillinger";
$l_s_allowteamplcreds = "Tillad Team Planet Credit Transfer";
$l_s_allowfullscan = "Tillad fuld Long Range Scan";
$l_s_sofa = "Tillad Sub-Orbital Fighter Angreb";
$l_s_showpassword = "Display Password om registrering";
$l_s_genesisdestroy = "Genesis torps kan ødelægge planeter";
$l_s_igb = "Intergalaktisk Bank (IGB)";
$l_s_ksm = "Kendt Space Maps";
$l_s_navcomp = "Navigation Computer";
$l_s_newbienice = "Newbie Nice";
$l_s_spies = "Spy System";
$l_s_spycapture = "Tillad Spies til at fange planeterne";

$l_s_gamesettings = "Spilindstillinger";
$l_s_gameversion = "Game version:";
$l_s_minhullmines = "Mindste skrog størrelse er nødvendig for at slå miner";
$l_s_averagetechewd = "Gennemsnit Tech plan Når Emergency Warp Nedbrydes";
$l_s_numsectors = "Række sektorer";
$l_s_maxwarpspersector = "Maksimal Links per sektor";
$l_s_averagetechfed = "Maksimale gennemsnitlige tech-plan for Federation Sektorer";
$l_s_igbirateperupdate = "IGB Rentesats pr update";
$l_s_igblrateperupdate = "IGB Lån sats pr update";
$l_s_techupgradebase = "Tech Niveau opgradere til Baser";
$l_s_collimit = "Kolonister Limit";
$l_s_maxturns = "Maksimalt antal akkumulerede vender";
$l_s_maxplanetssector = "Maksimalt antal planeter pr sektor";
$l_s_maxtraderoutes = "Maksimalt antal traderoutes per spiller";
$l_s_colreprodrate = "Kolonist Fødselsrate";
$l_s_energyperfighter = "Enhed energi, der anvendes pr sektor fighter";
$l_s_secfighterdegrade = "Sektor fighter nedbrydning procent";
$l_s_planetinterest = "Planet rente";
$l_s_spiesperplanet = "Maksimalt antal af spioner pr planet";
$l_s_spysuccessfactor = "Spy succesfaktor";
$l_s_spykillfactor = "Spy dræbe faktor";
$l_s_colsperfighter = "Kolonister er nødvendige for at producere 1 Fighter hver tur";
$l_s_colspertorp = "Kolonister er nødvendige for at producere 1 Torpedo hver tur";
$l_s_colsperore = "Kolonister er nødvendige for at producere 1 Ore hver tur";
$l_s_colsperorganics = "Kolonister er nødvendige for at producere 1 Organics hver tur";
$l_s_colspergoods = "Kolonister er nødvendige for at producere 1 Varer hver tur";
$l_s_colsperenergy = "Kolonister er nødvendige for at producere 1 Energy hver tur";
$l_s_colspercreds = "Kolonister er nødvendige for at producere 1 Credits hver tur";
$l_s_colsper = "Kolonister er nødvendige for at producere 1 [commodity] hver tur";

$l_s_gameschedsettings = "Game Scheduler Settings";
$l_s_schedtype = "Scheduler Type";
$l_s_cronbased = "Cron Baseret";
$l_s_playertriggered = "Player Triggered";
$l_s_minutes = "minut";
$l_s_ticksupdate = "Ticks ske hver";
$l_s_turnsupdate = "Slår vil ske hver";
$l_s_npcupdate = "Alliancen vil spille hver";
$l_s_igbturnsupdate = "Interesser på IGB regnskaber vil blive akkumuleret hver";
$l_s_newsupdate = "Nyheder vil blive genereret hver";
$l_s_planetupdate = "Planeter vil generere produktion hver";
$l_s_spyupdate = "Spies vil handle hver";
$l_s_portsupdate = "Havne vil genskabe alle";
$l_s_towupdate = "Skibe vil blive trukket fra fodret sektorer hver";
$l_s_scoreupdate = "Rankings vil blive genereret hver";
$l_s_secdefdegrupdate = "Sektor forsvar vil forringe hver";
$l_s_apocalypseupdate = "Planetsystemet apokalypse vil forekomme hvert";
$l_s_release_version = "Game version";
$l_s_time_since_reset = "Tid siden sidste nulstilling";
$l_s_independence = "Planetary Uafhængighed";
$l_s_dignitaryupdate = "Honoratiores vil handle hver";

$l_s_turnsupdate = "vender hver";
?>
