<?php
$l_cu_storing = "Lagring";
$l_cu_inistored = "<b>Alle ini værdier er blevet gemt.</b> <p>";
$l_cu_iniissue           = "<b><font color=\"yellow\">Issues occured during ini value storage.</font></b><br>\n";
$l_cu_inierror          = "<b><font color=\"red\">Error! database table does not exist!</font></b><p>\n";

$l_cu_id = "Auto Rute ID";
$l_cu_start = "Auto Rute Start";
$l_cu_destination = "Auto Rute Destination";
$l_cu_warps = "Auto Rute mellemlinerne";
$l_cu_deleteroute = "Slet Rute";
$l_cu_info = "Klik på Start sektor Realspace til denne sektor, og begynde warping til destinationen sektor.";
$l_cu_delete2 = "Slet Routes";
$l_cu_noroutes = "Ingen Auto Routes";
$l_cu_createroute = "Opret ny Auto Rute";
$l_cu_deleted = "Auto Routes slettet.";
$l_cu_return = "Retur til Auto Rute Menu klik";
$l_cu_created = "Auto Route er blevet oprettet.";
$l_cu_realmove = "Realspace flytte til sektor";
$l_cu_warpmove = "Warp flytte til næste sektor";
$l_cu_warpfinal = "Warp flytte til sidste sektor";
?>
