<?php
///SPIES
$l_spy_title = "Spy Menu";
$l_spy = "Spies";
$l_spy_disabled = "Spies er slået fra!";
$l_spy_noturn = "Du skal have mindst en tur til at sende en spion til en planet.";
$l_spy_notonboard = "Du har ikke nogen spioner om bord.";
$l_spy_ownplanet = "Du kan ikke sende en spion til din egen planet.";
$l_spy_unownedplanet = "Du kan ikke sende en spion til unowned planet.";
$l_spy_planetfull = "Der er allerede tilladt [max] spioner på denne planet.";
$l_spy_sendtitle = "Sende en spion [spyID] til planet: <BR> Vælg spion&#39;s mission:";
$l_spy_type1 = "Den spion kun handler om denne planet.";
$l_spy_type2 = "Den spion forsøger at infiltrere et skib, der udfører et planetarisk overførsel.";
$l_spy_type3 = "Den spion forsøger at infiltrere et skib, der udfører en planetarisk overførsel og derefter infiltrere til en anden planet.";
$l_spy_sendbutton = "Send til planet";
$l_spy_sendsuccessful = "Din spion infiltrater planeten og venter på det rigtige tidspunkt at begynde arbejdet.";
$l_spy_sendfailed = "Planet&#39;s Sensorer opdaget din spion, fordi din kappe enheden ikke kunne dække ham. Din spion er dræbt.";
$l_spy_noturn2 = "Du skal have mindst en tur til at ringe tilbage til en spion.";
$l_spy_confirm = "Er du sikker på du vil ringe tilbage til din spion [spyID]?";
$l_spy_cleanupplanet = "at rydde op, at planeten fra fjendens spioner.";
$l_spy_cleanupship = "Hvis du ønsker at rydde op i dit skib fra fjendens spioner, klik";
$l_spy_yourspies = "Din spioner på denne planet";
$l_spy_sendnew = "Send en ny spion";

$l_spy_codenumber = "Kode";
$l_spy_job = "Arbejde";
$l_spy_percent = "Procent";
$l_spy_move = "Movement";
$l_spy_action = "Action";
$l_spy_shipowner = "Reder";
$l_spy_shipname = "Skibsnavn";
$l_spy_shiptype = "Ship klasse";
$l_spy_shiplocation = "Ship Beliggenhed";
$l_spy_planetowner = "Planet Ejer";
$l_spy_planetname = "Planet";
$l_spy_sector = "Sektor";

$l_spy_moves['none'] = "Bevæger sig ikke";
$l_spy_moves['toship'] = "Til skib";
$l_spy_moves['toplanet'] = "Til planet";

$l_spy_comeback = "Ring tilbage";
$l_spy_nospieshere = "Du har ikke nogen spioner på denne planet!";
$l_spy_transferred = "spioner overføres";
$l_spy_backonship = "Den spion er nu på dit skib.";
$l_spy_backfailed = "Ring tilbage mislykkedes.";
$l_spy_changetitle = "Skiftende spion [spyID] egenskaber:";
$l_spy_occupied = "Din spion [spyID] i ansat som [job], med procent [percent].";
$l_spy_dismiss = "Afskedige den spion?";
$l_spy_changebutton = "Ændre";
$l_spy_changejob = "Skift job eller Movement";
$l_spy_linkback = "at gå til spion menuen.";
$l_spy_changed1 = "Movement ændret.";
$l_spy_changed2 = "Spy afskediget og hans bevægelse ændret.";
$l_spy_changefailed = "Skift mislykkedes.";
$l_spy_cleanupplanettitle = "Oprydning din planet fra fjendens spioner:";
$l_spy_notyourplanet = "Det er ikke jeres planet.";
$l_spy_cleanuptext[1] = "Hurtig oprydning. Anvender [creds] kreditter og [turns] sving.";
$l_spy_cleanuptext[2] = "Bedre rengøring. Anvender [creds] kreditter og [turns] sving.";
$l_spy_cleanuptext[3] = "Den bedste cleanup. Anvender [creds] kreditter og [turns] sving.";
$l_spy_cannotcleanupplanet = "Du har kun [credits] kreditter på denne planet, og [turns] sving.";
$l_spy_cleanupbutton1 = "Start rense jorden";
$l_spy_cleanupplanettitle2 = "Du tændt din Sensorer at finde fjendens spioner på denne planet.";
$l_spy_spyfoundonplanet = "Du har fundet en [player] &#39;s spion [spyID] på planeten. Du dræbte, at spion.";
$l_spy_spynotfoundonplanet = "Hvis du ikke fandt nogen fjende spioner på denne planet.";
$l_spy_notenough = "Du har ikke nok kreditter eller skiftes til at starte oprydningen.";

$l_spy_cleanupshiptitle = "Oprydning dit skib fra fjendens spioner:";
$l_spy_notinspecial = "Du skal være på et Devices havn for at rydde op i dit skib.";
$l_spy_cleanupshiptext[1] = "Hurtig oprydning. Anvender [creds] kreditter og [turns] sving.";
$l_spy_cleanupshiptext[2] = "Bedre rengøring. Anvender [creds] kreditter og [turns] sving.";
$l_spy_cleanupshiptext[3] = "Den bedste cleanup. Anvender [creds] kreditter og [turns] sving.";
$l_spy_cannotcleanupship = "Du har kun [credits] kreditter og [turns] sving.";
$l_spy_cleanupbutton2 = "Start rense dit skib";
$l_spy_cleanupshiptitle2 = "Du tændt din Sensorer at finde fjendens spioner på dit skib.";
$l_spy_spyfoundonship = "Du har fundet en [player] &#39;s spion [spyID] på dit skib. Du dræbte, at spion.";
$l_spy_spynotfoundonship = "Hvis du ikke fandt nogen fjende spioner på dit skib.";

$l_spy_infodeleted = "Besked slettet";
$l_spy_infonotyours = "Det er ikke din besked.";
$l_spy_noinfo = "Din spioner på fjendtlige skibe har ikke afsløre noget endnu.";
$l_spy_infotitle = "Din spioner har registreret følgende oplysninger";
$l_spy_time = "Tid";
$l_spy_type = "Type";
$l_spy_info = "Info";
$l_spy_datatype[1] = "Planet";
$l_spy_datatext[1] = "Der er en [player] &#39;s planet [planet] i sektor [sector].";
$l_spy_delete = "Slet";
$l_spy_messages = "at se, hvad dine spioner har opdaget.";
$l_spy_defaulttitle1 = "Spioner på fjendtlige skibe";
$l_spy_defaulttitle2 = "Spioner på fjendtlige planeter";
$l_spy_defaulttitle3 = "Spioner på din planeter";
$l_spy_defaulttitle4 = "Spioner på dit skib";

$l_spy_no1 = "Du har ikke nogen spioner på fjendens skibe.";
$l_spy_no2 = "Du har ikke nogen spioner på fjendtlige planeter.";
$l_spy_no3 = "Du har ikke nogen spioner på din planeter.";
$l_spy_no4 = "Du har ikke nogen spioner på dit skib.";
$l_spy_nospiesatall = "Du har ikke nogen spioner.";
$l_spy_notknown = "Ukendt";


$l_spy_trytitle = "På planeten denne spion vil forsøge at";

$l_spy_cantsendfeds = "Beklager, men Spies kan ikke sendes til Føderation eller Independent Planets.";
$l_spy_cantsendteam = "Du kan ikke placere Spies på en holdkammerater planet.";
$l_spy_messagesdeleted = "Alle slettede beskeder";
$l_spy_deleteall = "Slet alt";
$l_spy_onplanet = "Spioner på planeten";
$l_spy_menu = "at vende tilbage til Spy Menu.";
?>
