<?php
// New News Items

$l_news_planets = "planeter";
$l_news_cols = "Mio kolonister";
$l_news_p_headline = "[player] &#39;s imperium nu har [total] planeter";
$l_news_c_headline = "[player] &#39;s imperium nu har [total] mio kolonister";
$l_news_p_textXX = "Forbundet har udsendt advarsler om Empire of [name]. [name] har kontrol over [total] planeter og bør betragtes som meget farligt. Alle sektorer bør øge sektor forsvar straks.";
$l_news_c_textXX = "The Empire of [name] oplever massiv overbelægning på alle planeter med over [total] mio kolonister. Mangel på fødevarer kan forårsage uro. Alle sektorer bør være opmærksom på eventuelle aggressive handlinger, som [name] i fremtiden.";

$l_created_universe = "»Universe Creation &#39;";
$l_created_universe_full = "»Forskerne forsker begyndelsen af universet har enstemmigt besluttet, at i dag er den mest statistisk sandsynlighed dag for Universe Creation at have fundet sted«";

$l_news_p_text5 = "Den stigende imperium af [name] har nu fem planeter, vil FNN se handlinger [name] i højere grad i fremtiden!";
$l_news_p_text10 = "Den voksende imperium af [name] kontrollerer nu ti planeter, Samling af FNN sige, at en yderligere udvidelse af [name], kan føre til krig!";
$l_news_p_text25 = "De enorme imperium af [name] koloniseret 25 planeter, der allerede, i et interview, [name] meddelte, at han kunne overveje at bremse sin ekspansion i fremtiden!";
$l_news_p_text50 = "De enorme vidtstrakt imperium af [name], repræsenteret med 50 planeter i hele galaksen er at få en truende styrke. En af de FNN journalister fundet ud af, at [name] er at opgradere sit skib planlægger en større krig. I et interview [name] meddelte, at det sker på forsvar formålet alene!";
$l_news_c_text25 = "Den stigende imperium af [name] har nu 25 millioner kolonister, vil FNN se handlinger [name] i højere grad i fremtiden, men det meget klart, at fødselstal vil eksplodere!";
$l_news_c_text100 = "Den håbefulde imperium af [name] har nu 100 millioner kolonister, efter en eksplosion af fødselsrater, [name] kolonier syntes at være et godt sted for familier til at bosætte!";
$l_news_c_text500 = "Den store imperium af [name] er nu 500 millioner kolonister, [name] sagde i et interview, at koloniseringen af galaksen bare endnu ikke er begyndt";
$l_news_c_text1000 = "Den humongous imperium af [name] har nu en milliard kolonister, FNN journalister fundet ud af, at [name] er i besiddelse af nogle underlige kloning mekanisme, der gør det muligt for ham at avle nye kolonister i store mængder. Med dette beløb af kolonister, er econmic styrken af denne enorme imperium, FNN håber, at [name] ikke bruger sine penge på krigsførelse";

$l_news_indi_short = "FNN Rygte: over [planets] erklære uafhængighed.";
$l_news_indi = "FNN har det på godt myndighed, at over [planets] planeter har besluttet, at de er bedre styret af sig selv og er blevet uafhængige.";

$l_news_nova_short = "FNN Rapport: [name] bruger Nova Bomb.";
$l_news_nova = "FNN er breaking news, at [name] har brugt de frygtede Nova Bomb [total] gang (e) til at ødelægge en planet, og alle skibe på det.";
$l_news_nova_m_short = "FNN Rapport: [name] anvendelser Nova Bomb og savner.";
$l_news_nova_m = "FNN er breaking news, at [name] har brugt de frygtede Nova Bomb [total] gang (e) for at forsøge at ødelægge en planet. Nova Bomb blæste op uden for planeterne atmosfæren og forårsagede massive skader på planetarisk infrastruktur.";

$l_news_bounty = "FNN Rapport: [name] placerer en [amount] kredit dusør på [name2].";

$l_news_attackerpod_p_short = "FNN Rapport: [name] &#39;s skib er ødelagt.";
$l_news_attackerpod_P = "[name] &#39;s skib blev ødelagt, samtidig med at angribe en planet. Heldigvis [name] havde en Escape Pod og overlevede.";

$l_news_attackerdie_p_short = "FNN Rapport: [name] dør!";
$l_news_attackerdie_p = "[name] &#39;s skib blev ødelagt, samtidig med at angribe en planet, og de blev dræbt, fordi de har undladt at købe en Escape Pod.";

$l_news_destroyed_p_short = "FNN Rapport: [name] angriber og ødelægger en planet!";
$l_news_destroyed_p = "[name] angrebet [total] planet (r) ejet af [owner], og befolkningen i hver planet ødelagt planeten for at forhindre, at den bliver taget til fange!";

$l_news_defeated_p_short = "FNN Rapport: [name] angreb og besejrer en planet!";
$l_news_defeated_p = "[name] angrebet [total] planet (r) ejet af [owner], og besejrede den planetariske forsvaret!";

$l_news_notdefeated_p_short = "FNN Rapport: [name] angreb en planet og taber!";
$l_news_notdefeated_p = "[name] angreb [total] planet (r) ejet af [owner] og planetariske forsvar holdt mod de ubønhørlige angreb!";

$l_news_targetepod_short = "FNN Rapport: [name] angreb en [owner] og vinder!";
$l_news_targetepod = "[name] angrebet [owner] &#39;s skib og ødelagde den totalt. Heldigvis [owner] havde udstyret deres skib med en Escape Pod og de overlevede.";

$l_news_targetdies_short = "FNN Rapport: [name] angreb en [owner] og dræber dem!";
$l_news_targetdies = "[name] angrebet [owner] &#39;s skib og ødelagde den totalt. Desværre [owner] ikke har udstyret deres skib med en Escape Pod og de var fordampet.";

$l_news_fedcolbounty_short = "FNN Rapport: The Federation revner ned på [name]!";
$l_news_fedcolbounty = "Forbundet har i dag slået ned på den berygtede plads pirat [name]! [name], der rutinemæssigt overtrådt flere rum traktater, blev forlovet med Føderation slagkrydseren, som påførte [amount] kreditter til en værdi af skader på pirat&#39;s fartøj. Føderation embedsmænd lover yderligere sådanne aktioner i fremtiden!";

$l_news_alliancecolbounty_short = "FNN Rapport: Alliancen revner ned på [name]!";
$l_news_alliancecolbounty = "Alliancen har i dag slået ned på den berygtede plads pirat [name]! [name], der rutinemæssigt overtrådt flere rum traktater, blev forlovet med Alliancen, som påførte [amount] kreditter til en værdi af skader på pirat&#39;s fartøj. Alliancen embedsmænd lover yderligere sådanne aktioner i fremtiden!";

$l_news_fedcol_pbounty_short = "FNN Rapport: The Federation jagter ned [name]!";
$l_news_fedcol_pbounty = "Forbundet har i dag slået ned på den berygtede plads pirat [name]! [name], der rutinemæssigt overtrådt flere rum traktater, blev forlovet med Føderation slagkrydseren, som konfiskerede planeten [planetname] værdi [amount] kreditter i sektor [sector]. Føderation embedsmænd lover yderligere sådanne aktioner i fremtiden!";

$l_news_alliancecol_pbounty_short = "FNN Rapport: Alliancen jagter ned [name]!";
$l_news_alliancecol_pbounty = "Alliancen har i dag slået ned på den berygtede plads pirat [name]! [name], der rutinemæssigt overtrådt flere rum traktater, blev forlovet med Alliancen, som konfiskerede planeten [planetname] værdi [amount] kreditter i sektor [sector]. Alliancen embedsmænd lover yderligere sådanne aktioner i fremtiden!";

$l_news_fedcol_sbounty_short = "FNN Rapport: The Federation jagter ned [name]!";
$l_news_fedcol_sbounty = "Forbundet har i dag slået ned på den berygtede plads pirat [name]! [name], der rutinemæssigt overtrådt flere rum traktater, blev forlovet med Føderation slagkrydseren, der konfiskerede et skib ([shiptype]) værd [cost] i sektor [sector]. Føderation embedsmænd lover yderligere sådanne aktioner i fremtiden!";

$l_news_alliancecol_sbounty_short = "FNN Rapport: Alliancen jagter ned [name]!";
$l_news_alliancecol_sbounty = "Alliancen har i dag slået ned på den berygtede plads pirat [name]! [name], der rutinemæssigt overtrådt flere rum traktater, blev forlovet med Alliancen, der konfiskerede et skib [shiptype] værdi [cost] i sektor [sector]. Alliancen embedsmænd lover yderligere sådanne aktioner i fremtiden!";

$l_killheadline = "[target] blev dræbt i en ulykke";
$l_news_killed = "[target] blev dræbt i en tragisk ulykke i dag. Hvordan heroiske - [target] var det sidste medlem om bord på sit skib, da han mærkede, var der ingen flugt pod venstre for ham. Må han hvile i fred!";

$l_killSDheadline = "[target] blev dræbt af Sektor Defenses.";
$l_news_killedSD = "[target] blev dræbt af et overvældende antal af sektionen Defenses ejet af [killer]! Desværre skibet ikke var udstyret med en flugt pod.";

$l_killplanetheadline = "[target] blev dræbt angribe en planet.";
$l_news_killedplanet = "[target] blev dræbt, mens angribe en planet, der ejes af [killer] i dag. Desværre skibet ikke var udstyret med en flugt pod.";

$l_killshipheadline = "[target] blev dræbt skib bekæmpe.";
$l_news_killedship = "[target] blev dræbt i skib til skib bekæmpe med [killer] i dag. Kaptajnen tilsyneladende glemte at udstyre skibet med en flugt pod.";

$l_killsuicideheadline = "[target] begået selvmord.";
$l_news_killedsuicide = "[target] begik selvmord i dag. De tog kujoner vej ud, fordi de manglede evnen eller modet til at stå op til presset fra kommanderende deres eget skib.";

$l_killsofaheadline = "[target] blev dræbt sofa angribe en planet.";
$l_news_killedsofa = "[target] blev dræbt, mens sofa angribe en planet, der ejes af [killer] i dag. Desværre skibet ikke var udstyret med en flugt pod.";

$l_killnovaheadline = "[target] blev dræbt under et nova angreb.";
$l_news_killednova = "[target] blev dræbt af [killer] i en nova bombeattentat i dag. Desværre skibet ikke var udstyret med en flugt pod.";

$l_killnovabackfireheadline = "[target] blev dræbt af en nova give bagslag.";
$l_news_killednovabackfire = "[target] blev dræbt, da deres nova bombe gav bagslag i dag. Desværre skibet ikke var udstyret med en flugt pod.";

$l_killsectormissileheadline = "[target] blev dræbt af en sektor Missile.";
$l_news_killedsectormissile = "[target] blev dræbt, da en sektor missiler fra [killer] påvirket deres skjolde. Desværre skibet ikke var udstyret med en flugt pod.";

$l_killhunterprobeheadline = "[target] blev dræbt af en Hunter Probe.";
$l_news_killedhunterprobe = "[target] blev dræbt, da en Hunter Probe fra [killer] påvirket deres skjolde. Desværre skibet ikke var udstyret med en flugt pod.";

$l_killtrapprobeheadline = "[target] blev dræbt af en Sentry Trap Probe.";
$l_news_killedtrapprobe = "[target] blev dræbt, da en Sentry Trap Probe fra [killer] påvirket deres skjolde. Desværre skibet ikke var udstyret med en flugt pod.";

//-------------------

$l_killpodheadline = "[target] &#39;s skib blev ødelagt ved en ulykke";
$l_news_killedpod = "[target] &#39;s skib blev ødelagt i en tragisk ulykke i dag. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killSDpodheadline = "[target] &#39;s skib blev ødelagt af Sektor Defenses.";
$l_news_killedSDpod = "[target] &#39;s skib blev ødelagt af et overvældende antal af sektionen Defenses ejet af [killer]! En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killplanetpodheadline = "[target] &#39;s skib blev ødelagt angribe en planet.";
$l_news_killedplanetpod = "[target] &#39;s skib blev ødelagt, samtidig med at angribe en planet, der ejes af [killer] i dag. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killshippodheadline = "[target] &#39;s skib blev ødelagt i skibet bekæmpe.";
$l_news_killedshippod = "[target] &#39;s skib blev ødelagt i skib til skib bekæmpe med [killer] i dag. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killsofapodheadline = "[target] &#39;s skib blev ødelagt, mens sofa angribe en planet.";
$l_news_killedsofapod = "[target] &#39;s skib blev ødelagt, mens sofa angribe en planet, der ejes af [killer] i dag. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killnovapodheadline = "[target] &#39;s skib blev ødelagt under en nova angreb.";
$l_news_killednovapod = "[target] &#39;s skib blev ødelagt af [killer] i en nova bombeattentat i dag. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killnovabackfirepodheadline = "[target] &#39;s skib blev ødelagt af en nova give bagslag.";
$l_news_killednovabackfirepod = "[target] &#39;s skib blev ødelagt, da deres nova bombe gav bagslag i dag. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killsectormissilepodheadline = "[target] &#39;s skib blev ødelagt af en sektor Missile.";
$l_news_killedsectormissilepod = "[target] &#39;s skib blev ødelagt, da en sektor missiler fra [killer] påvirket deres skjolde. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killhunterprobepodheadline = "[target] &#39;s skib blev ødelagt af en Hunter Probe.";
$l_news_killedhunterprobepod = "[target] &#39;s skib blev ødelagt, da en Hunter Probe fra [killer] påvirket deres skjolde. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

$l_killtrapprobepodheadline = "[target] &#39;s skib blev ødelagt af en Sentry Trap Probe.";
$l_news_killedtrapprobepod = "[target] &#39;s skib blev ødelagt, da en Sentry Trap Probe fra [killer] påvirket deres skjolde. En Escape Pod transponder blev opdaget af Federation Search and Rescue.";

// --------------------------

$l_news_promotedheadline = "[name] er blevet forfremmet til [rank]";
$l_news_promoted = "Forbundet er en glæde at meddele fremme af [name] til rang af [rank].";

$l_news_demotedheadline = "[name] er blevet degraderet til [rank]";
$l_news_demoted = "Forbundet beklager at måtte meddele, degraderingen af [name] til rang af [rank].";

$l_news_namechangedheadline = "[oldname] skiftede navn til [newname]";
$l_news_namechanged = "[oldname] anvendes til Federation Review Board til at ændre deres navn til [newname]. Føderationen har indrømmet navneændring. Fra denne dag frem [oldname] skal nu være kendt som [newname]. Alle skibe og planeter bør opdatere deres registre straks.";

$l_news_found_planets_short = "Federation Survey: [found_planets] nye beliggende planeter.";
$l_news_found_planets = "Federation Survey Spejdere har placeret [found_planets] nye planeter i de nyligt opdagede sektorer.";

$l_news_new_ports_short = "Federation Survey: [new_ports] nyt bygget havne.";
$l_news_new_ports = "Federation Ingeniører har konstrueret [new_ports] nye havne i nyopdaget sektorer.";

$l_news_addedsectors_short = "Federation Survey: [addedsectors] sektorer opdaget.";
$l_news_addedsectors = "Federation Survey Spejdere har opdaget [addedsectors] nye sektorer. Forsigtighed tilrådes.";

$l_news_artifactheadline = "[playername] [artifact]";
$l_news_artifact = "[playername] har fundet alle de stykker af [artifact] og har alle de beføjelser, det kan give.";

$l_news_artifactfoundheadline = "[playername] findes [artifact] brik";
$l_news_artifactfound = "[playername] har fundet en af de stykker af de [artifact] og behov [pieces] mere [piece].";

?>
