<?php
$l_move_title = "Bevæge";
$l_move_turn = "Du skal have mindst en tur til at flytte.";
$l_move_failed = "Flyt mislykkedes!";
$l_rs_title = "RealSpace Flyt";
$l_rs_whichsector = "Hvilken branche ønsker du at nå gennem RealSpace?";
$l_rs_insector = "Du er i øjeblikket i sektor [sector] - og der er sektorer til rådighed fra 1. til [sector_max].";
$l_rs_submit = "Beregn";
$l_rs_movetime = "Med din motorer, vil det tage [triptime] skiftes til at fuldføre rejsen.";
$l_rs_energy = "Du ville samle [energy] enheder af energi";
$l_rs_noturns = "Du har ikke nok vender tilbage, og kan ikke gå i gang på denne rejse.";
$l_rs_engage_link = "Engage";
$l_rs_engage = "Du har [turns] sving. [engage] motorer?";
$l_rs_invalid = "Du kan ikke realspace til denne sektor fra her.";
$l_rs_ready = "Du er nu i sektor [sector]. Du brugte [triptime] vender, og erfaringer [energy] energi enheder.";
$l_warp_invalid = "Du kan ikke kæde til denne sektor fra her.";
$l_move_unknown = "Ukendt Movetype";
?>
