<?php
$l_readm_title = "Read Message";
$l_readm_delete = "Besked slettet";
$l_readm_nomessage = "Du har ingen meddelelser venter på dig ...";
$l_readm_center = "Besked Modtage Center";
$l_readm_sender = "Besked Sender";
$l_readm_captn = "Kaptajn";
$l_readm_del = "Slet";
$l_readm_repl = "Svar";
$l_readm_return = "Klik her for at vende tilbage til hovedmenuen";
$l_readm_title2 = "Mail Reader";
$l_readm_delete = "Slet alt";
$l_readm_subject = "Emne";
$l_readm_quote = "Citat";
$l_readm_block = "Block Sender";
$l_readm_alert = "System Alert";
$l_readm_alertbody = "Ship Computer";
?>
