<?php
$l_md_title = "Sektor forsvar";
$l_md_invalid = "Ugyldigt Sector forsvar";
$l_md_nolonger = "Sektoren valgte forsvaret ikke længere er der.";
$l_md_you = "du";
$l_md_bmines = "Din bjælker ødelagt";
$l_md_msgdownerb = "[name] ødelagt [mines] miner i sektor [sector].";
$l_md_retr = "Du har hentet";
$l_md_consist = "Denne sektor forsvar består af [qty] [type] ejes af [owner].";
$l_md_youcan = "Du kan";
$l_md_retrieve = "Hent";
$l_md_attack = "Attack";
$l_md_attdef = "Angribe Sector forsvarsværker. Alle sektor krigere vil gengælde.";
$l_md_noturn = "Du skal have mindst en tur.";
$l_md_nothere = "Du skal være i den samme sektor som sektoren forsvarsværker.";
$l_md_notyours = "Handling ikke tilladt. Disse sektor forsvar ikke tilhører dig.";
$l_md_yours = "Du kan ikke angribe din egen sektor forsvarsværker.";
?>
