<?php
$l_sf_attacking = "Sektor forsvaret krigere angriber dig! <BR>";
$l_sf_destfight = "Din bjælker ødelagt [lost] kæmpere <BR>";
$l_sf_destfightb = "Din bjælker ødelagt [lost] kæmpere <BR>";
$l_sf_torphit = "Torpedoer hit:";
$l_sf_destfightt = "Din torpedoer ødelagt [lost] kæmpere <BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "Du ødelagde alle de kæmpere. <BR>";
$l_sf_destfightt2 = "Du ødelagde [lost] krigere. <BR>";
$l_sf_lostfight = "Du har mistet alle kæmpere. <BR>";
$l_sf_lostfight2 = "Du mistet [lost] kæmpere. <BR>";
$l_sf_armorbreach = "Din rustning er overtrådt! <BR>";
$l_sf_armorbreach2 = "Din rustning er ramt for [lost] skader. <BR>";
$l_sf_sendlog = "[player] ødelagt [lost] sektor forsvar krigere i sektor [sector].";
$l_sf_lreport = "Du mistet [armor] rustning point, [fighters] krigere, og bruges [torps] torpedoer. <BR><BR>";
$l_sf_shipdestroyed = "Dit skib er blevet ødelagt! <BR><BR>";
$l_sf_sendlog2 = "Sektor forsvar krigere destrueret [player] i sektor [sector].";
$l_sf_escape = "Heldigvis har du en flugt pod! <BR><BR>";

$l_sf_fnoattack = "er ikke sende nogen krigere til at angribe din krigere.";
$l_sf_fnoattackt = "er ikke sende nogen krigere til at angribe dine torpedoer.";
$l_sf_fnoattacka = "er ikke sende nogen krigere til at angribe din rustning.";
$l_sf_flaunchmalf1 = "Din fighter at lancere systemet fungerer korrekt.";
$l_sf_flaunchmalf2 = "Du har kun været i stand til at lancere";
$l_sf_flaunchmalf3 = "procent af din krigere.";
$l_sf_fightertorpexg = "Fighter til Torpedo / Mine Exchange";
$l_sf_torpfighterexg = "Skib Torpedo til Sector Fighter Exchange";
$l_sf_fighterarmorexg = "Sektor Fighter til Ship Armor Exchange";
$l_sf_tlaunchmalf1 = "Din torpedo at lancere systemet fungerer korrekt.";
$l_sf_tlaunchmalf2 = "Du har kun været i stand til at lancere";
$l_sf_tlaunchmalf3 = "procent af dine torpedoer.";
$l_sf_bountysd = "Du har angrebet en sektor, der indeholder en planet, der vil give dig en dusør, hvis du angrebet planeten. Føderationen har aktiveret en automatisk selvdestruerende på alle dine krigere og torpedoer. Du må ikke angribe sektor forsvarsværker i denne sektor igen. Du er blevet advaret!";
?>
