<?php
$l_novabomb_turns = "Nova Bomb kræver atleast [turns] bliver til ild.";
$l_novabomb_planetsdamaged = "Planeter beskadiget af Nova Bomb";
$l_novabomb_planet = "Planet [name] har lidt skade fra Nova Bomb.";
$l_novabomb_novaexplode = "Nova bombe eksploderede, da den blev fyret og dit skib har lidt store tab.";
$l_novabomb_novaexplode2 = "Nova bombe eksploderede, da den blev fyret og dit skib blev ødelagt.";
$l_novabomb_notfedsec = "Nova Bomb kan ikke bruges på Føderation ejet sektorer.";
$l_novabomb_destroyed_planet = "Din nova bombe krakket overfladen af planeten og boret ind i kernen, hvor den eksploderede årsag til planeten for at splintres.";
$l_novabomb_wrongclass = "Dette skib klasse kan ikke fyre en Nova Bomb Enhed.";
$l_novabomb_nonova = "Du behøver ikke have en Nova Bomb installeret.";
$l_novabomb_novamiss = "Nova Bomb snævert misser, men påfører skade på planeten.";
$l_novabomb_success = "Sektor [sector] er blevet Nova bombet!";
$l_novabomb_mines = "Ødelagt [mines] sektor Mines.";
$l_novabomb_fighters = "Ødelagt [fighters] sektor Fighters.";
$l_novabomb_shipsdamaged = "Skibe beskadiget af Nova Bomb";
$l_novabomb_ship_damage = "Starship [shipname] lidt skade fra Nova Bomb.";
$l_novabomb_ship_survived = "Dit skib var langt nok væk, når de Nova bombe eksploderede for at undgå skader.";
?>
