<?php
$l_login_title = "Login";
$l_login_pw = "Password:";
$l_login_chooseres = "Stand til at bestemme din skærmopløsning. Vælg den der passer bedst til:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new_player.php\">here</A>.";
$l_login_prbs = "Problemer?";
$l_login_emailus = "E-mail os";
$l_login_forgot_pw = "Glemt password? Indtast det tomt og trykke login.";
$l_login_settings = "Spilindstillinger";
$l_login_change = "Ændre";
$l_login_title2 = "Vigtigste Login for AATraders";
$l_login_reset1 = "Ingen Nulstil Planlagt";
$l_login_reset2 = "Planlagt Reset:";
$l_login_reset3 = "Planlagte turneringer Reset:";
$l_login_notice = "Vigtig meddelelse:";
$l_login_endadminnews = "Udgangen af Admin Nyheder";
$l_login_tourney_signup = "Turnering Tilmeldinger Enabled";

$l_login_profile_only = "Profil Kun";
$l_login_newclosed_message = "Nye tilmeldinger Lukket";
$l_login_tourneymode = "Turnering Running";
$l_login_tourneystarts = "Starter:";
?>
