<?php
$l_warp_linkto = "Links bly fra denne sektor til";
$l_warp_nolink = "Der er ingen links ud af denne sektor.";
$l_warp_query = "Hvad sektor vil du gerne lave et link til?";
$l_warp_oneway = "One-way?";
$l_warp_dest = "Alternativt kan du ødelægge et link til sektor.";
$l_warp_destquery = "Hvad sektor ønsker du at fjerne et link til?";
$l_warp_bothway = "Både-måder";
$l_warp_create = "Opret en kæde mellem Sektor:";
$l_warp_andsector = "og Sektor:";
$l_warp_distance = "med en afstand på";
$l_warp_lightyears = "lysår";
$l_warp_delete = "Slet kæde mellem Sektor:";
$l_warp_costcreate = "Omkostninger til at skabe:";
$l_warp_costdelete = "Omkostninger til at slette:";
$l_warp_costenergy = "Energi, der skal:";
$l_warp_twoerror = "Brug af en Warp Editor til at skabe en to-vejs-link til sektor [target_sector] er ikke tilladt.";
?>
