<?php
$l_sofa = "Sub-Orbital Fighter Attack";
$l_planet_basenoturn = "Du skal have mindst 1 tur til at bygge en base";
$l_planet_upgrade = "Upgrade";
$l_planet_novamiss = "Nova Bomb snævert misser, men påfører skade på planeten.";
$l_planet_novaturns = "Nova Bomb kræver atleast [turns] bliver til ild.";
$l_planet_novafed = "Nova Bomb vil ikke magt op i Federation sektorer.";
$l_planet_nonova = "Du behøver ikke have en Nova Bomb installeret.";
$l_planet_firenova = "Fire Nova Bomb";
$l_planet_novaexplode = "Nova bombe eksploderede, da den blev fyret og dit skib har lidt store tab.";
$l_planet_novaexplode2 = "Nova bombe eksploderede, da den blev fyret og dit skib blev ødelagt.";
$l_planet_noautotrade = "Auto Handel Rute ikke fastsat for denne planet.";
$l_planet_autotrade   ="<font size='1'>Auto Trading";
$l_planet_autotradetype = "- [source_type] i havn [dest_id]";
$l_planet_autotradedelete = "Slet Auto Handel.";
$l_planet_autotradeadd = "Opret Auto Handel.";
$l_planet_tradedeleted = "Auto Handel Rute udgår.";
$l_planet_tradeadded = "Nye Auto Handel Rute Added.";
$l_planet_autotype = "Vælg det element, at handelen";
$l_planet_based = "<b><font color='#FFFFFF' size='2'>(</font><font color='#87d8ec' size='2'>Based</font><font color='#FFFFFF' size='2'>)</font></b>";
$l_planet_needcargo = "Du er nødt til at købe et fragtskib for denne planet, før du kan indstille en Auto Handel Rute.";
$l_planet_purchasecargo = "Hvis du ønsker at købe et fragtskib";
$l_planet_upgradecargo = "Hvis du ønsker at opgradere din Cargo Ship";

$l_planet_cargocapacity = "Kapacitet:";
$l_planet_cargoowned = "Du allerede ejer et fragtskib for denne planet.";
$l_planet_cargoshipbuy = "Køb Cargo Ship";
$l_planet_cargoshipupgrade = "Upgrade Cargo Ship";
$l_planet_cargoatmax = "Din Fragtskib er på det højeste opgraderingen niveau.";
$l_planet_cargoshipbuyinfo = "Vælg en forudindstillet Cargo Ship";
$l_planet_cargoshipupgradeinfo = "Opgrader din fragtskibe Hull.";
$l_planet_cargoshipbuildinfo = "Byg din egen Cargo Ship";
$l_planet_tradehelp = "1. Du kan indtaste en handels-havn for hver type af råvare. <br> 2. Du kan ikke handle en vare i en havn, der sælger den samme vare. <br> Handel med varer i en Varer Port, Ore på en Ore Port, ect.. vil gøre noget. <br> 3. Hvis du ikke ønsker at handle visse varer blot indtaste 0 for havnesektoren.";
$l_planet_cargocredits = "Auto Handel Credits Received:";
$l_planet_cargonoown = "Du skal eje jorden for at skabe en auto Traderoute.";
$l_planet_digtrans = "Transfer dignitar";
$l_planet_nocredits1 = "Du har ikke nok kredit for denne transaktion. De samlede omkostninger er";
$l_planet_nocredits2 = "kreditter og du kun har";
$l_planet_nobase = "Du skal have en base til at forvalte planeten forsvar niveauer.";
$l_planet_genesisnoturn = "Du skal have mindst 1 tur til at bruge Genesis enhed på planeten.";
$l_planet_nogenesis = "Du skal have en Genesis Enhed til at ødelægge en planet.";
$l_planet_wrongclass = "Dette skib klasse kan ikke fyre en Nova Bomb Enhed.";

$l_planet_combatpreview = "Combat Preview";
$l_planet_beamfire1 = "Deres angreb er blevet opdaget. Planetary Profiler fyring! Øget Beam Fire som dit skib kommer i for tæt på planeten til at lancere kæmpere.";
$l_planet_beamfire2 = "Deres angreb er blevet opdaget. Planetary Profiler fyring! Massive brande sats fra planeten som bredde Batterier lås på til flere hits!";
$l_planet_beamfire3 = "Deres angreb er blevet opdaget. Planetary Profiler fyring! Beam Batterier over hele planeten er lås på for massive flere ild! Beam brand langt højere end forventet!";
$l_planet_beamfire4 = "Deres angreb er blevet opdaget. Planetary Profiler fyring! Beam forsvar kan kun låse på for en fyring passere.";

$l_planet_sofanobeamsshields = "er ikke affyre stråler på dine skjolde.";
$l_planet_sofanobeamsarmor = "er ikke affyre stråler på din rustning.";
$l_planet_flauncherfailed1 = "Din fighter at lancere systemet fungerer korrekt.";
$l_planet_flauncherfailed2 = "Du har kun været i stand til at lancere";
$l_planet_flauncherfailed3 = "procent af din krigere.";
$l_planet_nodfightertofighter = "er ikke sende nogen krigere til at angribe din krigere.";
$l_planet_nodfightertotorp = "er ikke sende nogen krigere til at angribe din torps.";
$l_planet_flauncherfailed3 = "procent af din krigere.";
$l_planet_autotradetype = "- [source_type] i havn [dest_id]";

$l_planet_imtitleattack = "Planet under angreb";
$l_planet_imisattacking = "angriber";
$l_planet_iminsector = "i sektoren";
$l_planet_imnova = "bruger en Nova enhed på";
$l_planet_imsofa = "er SOFA-bombe";
$l_planet_team = "Denne planet er ejet af en holdkammerat, og du har ikke tilladelse til at få adgang til information for denne planet.";
?>
