<?php
$l_gns_title = "Brug Genesis Device";
$l_gns_turn = "Du skal have mindst en tur til at bruge en genesis enhed.";
$l_gns_onplanet = "Du kan ikke bruge denne enhed, mens på planeten overflade.";
$l_gns_full = "Dette solsystem er allerede fuld.";
$l_gns_planetex = "Der er allerede en planet i denne sektor.";
$l_gns_nogenesis = "Du har ikke nogen genesis enheder.";
$l_gns_forbid = "Oprettelse af en planet i denne sektor er ikke tilladt.";
$l_gns_bforbid = "Baserne i denne sektor er at gribe ind med din tilblivelse enheden. Planet skabelse ikke muligt.";
$l_gns_pcreate = "Planet oprettet.";
$l_sgns_title = "Brug Sector Genesis Device";
$l_sgns_pcreate = "Sektor [name] oprettet.";
$l_sgns_nogenesis = "Du har ikke nogen sektor genesis enheder.";
$l_sgns_forbid = "Oprettelse af en sektor, Genesis ormehul i denne sektor er ikke tilladt.";
$l_sgns_forbid1 = "Oprettelse af en sektor, Genesis ormehul en Føderation Sector er ikke tilladt.";
$l_sgcreate = "Opret ny Sektor Genesis Sektor";
$l_sgcreatens = "Opret ny Sektor Genesis Link tilbage til kendte rummet";
$l_sgns_forbid2 = "Mere end [limit] links i SG sektorer er ikke tilladt.";
$l_sgns_forbid3 = "Kan ikke oprette Sektor Genesis kæde link fra nuværende sektor - at ville overskride det maksimalt [limit] per sektor.";
$l_sgns_nocredits = "Du har ikke nok kredit for at oprette en ny sektor.";
$l_sgns_shipcredits = "Kreditter på skibet:";
$l_sgns_createcost = "Omkostninger til at skabe nye Sektor:";
$l_sgns_complete = "Normal Space Link Complete";
$l_sgns_sectorname = "Indtast Sektor Navn:";
$l_gns_max_unbased_planets = "Forbundet vil ikke tillade, at oprettelsen af flere planeter, indtil du har mindre end [max_unbased_planets] unbased planeter.";

?>
