<?php

// Confirmed common to multiple files:

$game_charset 		 = "ISO-8859-1";

$l_zname[1] = "Unchartered plads";
$l_zname[2] = "Federation space";
$l_zname[3] = "Alliance plads";
$l_zname[4] = "War Zone";

$l_nova = "Nova";
$l_nova = "Nova Bomb";
$l_lssd = "Sidste skib set enhed";
$l_lss = "Sidste skib ses i denne sektor";

// Common to : warpedit 1-3.php

$l_warp_title = "Brug Warp Editor";
$l_warp_turn = "Du skal have mindst en tur til at bruge en warp editor.";
$l_warp_none = "Du har ikke nogen warp redaktører.";
$l_warp_forbid = "Ved hjælp af en Warp Editor i denne sektor er ikke tilladt.";
$l_swarp_forbid = "Brug af en Warp Editor til eller fra SG sektorer er ikke tilladt.";
$l_warp_nosector = "Sektor ikke findes.";

// Not yet confirmed common to multiple files:

$l_yes = "Ja";
$l_no = "Nej";
$l_here = "her";
$l_submit = "Indsende";
$l_reset = "Nulstil";
$l_all = "Alle";
$l_max = "Max";

$l_trade = "Erhverv";
$l_ore = "Ore";
$l_commodity = "Commodity";
$l_commodities = "Råvarer";
$l_organics = "Organics";
$l_goods = "Varer";
$l_energy = "Energi";
$l_colonists = "Kolonister";
$l_credits = "Credits";
$l_units = "enheder";
$l_special = "Special";
$l_upgrade_ports = "Opgraderinger";
$l_device_ports = "Enheder";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_dig = "Honoratiores";
$l_spy = "Spies";

$l_cargo = "Cargo";
$l_fighters = "Fighters";
$l_mines = "Mines";
$l_torps = "Torpedoer";

$l_none = "Ingen";
$l_unnamed = "Unavngiven";
$l_name = "Navn";
$l_unowned = "Unowned";
$l_unknown = "Ukendt";
$l_clickme = "Klik her";
$l_player = "Player";
$l_ship = "Skib";
$l_ships = "Skibe";
$l_set = "sæt";
$l_realspace = "Realspace";
$l_armorpts = "Armor point";
$l_links = "Links";
$l_login_email = "E-mail-adresse:";
$l_add = "Tilføj";
$l_teamforum = "Team Forum";
$l_teamships = "Team Skibe";
$l_tutorial = "Tutorial / Hjælp";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Debris";
$l_localmap = "Lokale Kort";
$l_arm_weap = "Armor &amp; våben";
$l_3dmap = "3D Galaxy Kort";

$l_sectormissile = "Sektor Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Rumsonder";
$l_warpeditors = "Warp Redaktion";
$l_genesistorps = "Genesis Torpedoer";
$l_sgtorps = "SG Torpedoer";
$l_minesfighters = "Mines / Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Rapporter";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sektor Noter";
$l_maps = "Kort";
$l_messages = "Beskeder";
$l_shiptype = "Skibstype";
$l_help = "Hjælp";
$l_rank = "Rank";

$l_teamplanets = "Team Planeter";
$l_teamdefenses = "Team forsvar";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet forsvar";
$l_changeproduction = "Skift Produktion";
$l_galacticarm = "Galaktisk Arm";

$l_armor = "Armor";
$l_news_none = "Beklager, ingen nyheder i dag.";

$l_ranks_good = "God";
$l_ranks_evil = "Ond";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zone er nu en krigszone!";
$l_global_nzone = "Zone er en neutral zone.";
$l_global_team = "Område nu hører til hold";
$l_global_player = "Område nu tilhører spilleren";
$l_global_nochange = "Område ejerskab ændrede sig ikke";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Recruit";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "Petty Officer tredje klasse";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Lieutenant Junior Grade";
$l_insignia_name[11] = "Løjtnant";
$l_insignia_name[12] = "Orlogskaptajn";
$l_insignia_name[13] = "Commander";
$l_insignia_name[14] = "Kaptajn";
$l_insignia_name[15] = "Kontreadmiral (nederste halvdel)";
$l_insignia_name[16] = "Kontreadmiral (øverste halvdel)";
$l_insignia_name[17] = "Viceadmiral";
$l_insignia_name[18] = "Admiral";
$l_insignia_name[19] = "Fleet Admiral";

$l_main_title = "Hovedmenu";
$l_main_warpto = "Warp til";
$l_main_autoroute = "Autoroute til";
$l_main_rs_to = "RSMove til";
$l_main_other = "Anden";
$l_main_shipyard1 = "Værft";
$l_main_shipyard2 = "Adgang til";
$l_traderoutes = "Trade Routes";
$l_trade_control = "Handel Control";
$l_youhave = "Du har";
$l_turns_used = "Turns anvendes:";
$l_turns_have = "Turns rådighed:";
$l_score = "Score:";
$l_sector = "Sektor";
$l_help = "Hjælp";
$l_faq = "FAQ";
$l_feedback = "Tilbagemelding";
$l_forums = "Forums";
$l_logout = "Logout";
$l_commands = "Kommandoer";
$l_command_no = "Kommandoen er ikke tilgængelig.";
$l_devices = "Enheder";
$l_planets = "Planeter";
$l_log = "Log";
$l_sector_def = "Sektor forsvar";
$l_defense = "Forsvar";
$l_read_msg = "Læs Beskeder";
$l_send_msg = "Sende beskeder";
$l_rankings = "Rankings";
$l_teams = "Teams";
$l_ohno = "Self-Destruct";
$l_options = "Valg";
$l_navcomp = "Nav Computer";
$l_incompletemove = "Du har ikke udfyldt din tidligere flytte.";
$l_clicktocontinue = "Klik her for at fortsætte";
$l_toplanetmenu = "at gå til planeten menuen.";
$l_nonexistant_pl = "På et ikke-eksisterende planet???";
$l_abord = ", Ombord på";
$l_messages_wait = "Beskeder, der venter på dig.";
$l_no_warplink = "Ingen warp links";
$l_scan = "scan";
$l_fullscan = "Fuld scanning";
$l_port = "Port";
$l_tradingport = "Trading havn";
$l_planet_in_sec = "Planeter i sektoren";
$l_ships_in_sec = "Andre skibe i sektoren";
$l_sector_0 = "Der er så meget trafik i Sol, at du ikke engang kan isolere andre skibe!";
$l_map = "Kort";
$l_probe = "Probes";
$l_autotrade = "Autotrades";
$l_onboard = "bord på";
$l_classship = "klasse skib";
$l_traveled = "rejste til sektor";
$l_max_planets = "Maksimal habital planeter";
$l_block_msg = "Blokere beskeder";
$l_sectorinfo = "Sektor Info";
$l_add_note = "Add note";
$l_view_note = "Se";
$l_notes = "Noter";
$l_global_limitreached = "Du har nået grænsen for den mængde tid, du har lov til at være online hver dag. Log ind igen i morgen efter midnat.";
$l_onlinetimeleft = "Resterende tid:";
$l_planetmax = "Planetary Maksimum:";
$l_storedshipreport = "Lagrede Skibe";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Forrige Side";
$l_common_next = "Næste Side";
$l_common_totalpages = "Total Pages";
$l_common_selectpage = "Vælg side:";
$l_common_page = "Side:";
$l_templatechange = "Vil du beholde denne skabelon?";

$l_im_fed_bounty = "Føderationen har sat en dusør på dig for at angribe en sådan lavt rangerende spiller. Forbundet vil angribe dit skib på en regelmæssig basis, indtil du betale tilbage din gavmildhed. Du kan betale dine dusør til enhver Upgrade Port eller Spacedock.";
$l_im_fed_bounty_title = "Federation placeret en ekstra på dig!";
$l_im_alliance_bounty = "Alliancen har sat en dusør på dig for at angribe en sådan lavt rangerende spiller. Alliancen vil angribe dit skib på en regelmæssig basis, indtil du betale tilbage din gavmildhed. Du kan betale dine dusør til enhver Upgrade Port eller Spacedock.";
$l_im_alliance_bounty_title = "Alliancen lagde en ekstra på dig!";
$l_instant_messages_waiting = "Du har [count] beskeder, der venter på dig.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds fyld:";
$l_hold_space_free = "Holds Tom:";
$l_port_buys = "Port Buys:";

?>
