<?php
class Ship_Armor {

	var $planet_armor_hit_pts = 3000; // the amount of damage a single unit of armor can take before it is destroyed
	var $ship_armor_hit_pts = 1500; // the amount of damage a single unit of armor can take before it is destroyed

	var $price_modifier = 1; // The cost of each armor point is multiplied by this number
	var $armor_price = 5; // The cost of each armor point
}

?>